<?php
    // Set up page title:
    $this->headTitle($this->translate('Self Archiving'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li>';
?>

<?=$this->component('show-account-menu-button')?>

<div class="<?=$this->layoutClass('mainbody')?>">
  <h2><?=$this->transEsc('SelfArchiving_mainpage1')?></h2>
  <p><?=$this->transEsc('SelfArchiving_mainpage2')?></p>
  <p><?=$this->transEsc('SelfArchiving_mainpage3')?></p>
  <ul>
      <li><a href="/Feedback/Form/SelfArchivingAufsatz"><?=$this->transEsc('SelfArchiving_mainpage4')?></a></li>
      <li><a href="/Feedback/Form/SelfArchivingRezension"><?=$this->transEsc('SelfArchiving_mainpage5')?></a></li>
      <li><a href="/Feedback/Form/SelfArchivingLexikonartikel"><?=$this->transEsc('SelfArchiving_mainpage6')?></a></li>
      <li><a href="/Feedback/Form/SelfArchivingMonographie"><?=$this->transEsc('SelfArchiving_mainpage7')?></a></li>
  </ul>
  <p><?=$this->transEsc('SelfArchiving_mainpage8')?></p>
  <p><?=$this->transEsc('SelfArchiving_mainpage9')?></p>
  <p><?=$this->transEsc('SelfArchiving_mainpage10')?>: <a href="mailto:ixtheo-self-archiving@ub.uni-tuebingen.de">ixtheo-self-archiving@ub.uni-tuebingen.de</a></p>
</div>

<div class="<?=$this->layoutClass('sidebar')?>" id="myresearch-sidebar" role="navigation" aria-label="<?=$this->transEsc('account_menu_label')?>">
  <?=$this->accountMenu()->render('SelfArchiving')?>
</div>
