<?php $viewId = $this->viewId; ?>
<h1 class="cw-h1">Zeder Proof of Concept (&quot;<?=$viewId?>&quot;)</h1>
<table id="ZederView" class="table table-striped table-bordered table-condensed"></table>
<?php $this->headScript()->appendFile('zeder.js'); ?>
<?php
$translationKeys = ['Results per page', 'Search', 'showing_items_of_html'];
$translations = [];
foreach ($translationKeys as $translationKey) {
  $translations[$translationKey] = $this->translate($translationKey);
}
$jsonTranslations = json_encode($translations);
?>
<?=$this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, 'VuFind.addTranslations(' . $jsonTranslations . ');', 'SET')?>
<?=$this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, 'Zeder.RenderView("' . $viewId . '", "ZederView");', 'SET')?>
