<?php
    $tuefind = $this->tuefind();
    // Initialize from current search (if available) or defaults:
    if ($results = ($this->results ?? $this->searchMemory()->getCurrentSearch())) {
      $params = $results->getParams();
      $this->searchClassId = $params->getSearchClassId();
      $hiddenFilters = $params->getHiddenFilters();
      $lastSort = $params->getSort();
      $lastLimit = $params->getLimit();
      $options = $results->getOptions();
    } else {
      if (!isset($this->searchClassId)) {
        $config = $this->config()->get('config');
        $this->searchClassId = $config->Site->defaultSearchBackend ?? 'Solr';
        if (preg_match('"/Authority"i', $this->serverUrl(true)))
          $this->searchClassId = 'SolrAuth';
      }
      $options = $this->searchOptions($this->searchClassId);
      $hiddenFilters = $this->searchTabs()->getHiddenFilters($this->searchClassId, true, $this->ignoreHiddenFiltersInRequest ?? false);
      $lastSort = $this->searchMemory()->getLastSort($this->searchClassId);
      $lastLimit = $this->searchMemory()->getLastLimit($this->searchClassId);
      $params = null;
    }
    // Override search class ID with searchbox-specific settings, if necessary:
    $overrideSearchClassId = $options->getSearchBoxSearchClassId();
    if ($overrideSearchClassId !== $this->searchClassId) {
      $this->searchClassId = $overrideSearchClassId;
      $options = $this->searchOptions($overrideSearchClassId);
    }

    $routeParams = $tuefind->getRouteParams();

    // Load search actions and settings (if any):
    $keyboardLayouts = $this->searchbox()->getKeyboardLayouts();
    $handlers = $this->searchbox()->getHandlers(
        $this->searchClassId,
        $this->searchIndex ?? null
    );
    $handlerCount = count($handlers);
    $basicSearch = $this->searchbox()->combinedHandlersActive() ? 'combined-searchbox' : $options->getSearchAction();
    $searchHome = $options->getSearchHomeAction();
    $advSearch = $options->getAdvancedSearchAction();

    if (!isset($this->filterList) || !isset($this->checkboxFilters)) {
        $params ??= $this->searchMemory()->getLastSearchParams($this->searchClassId);
        $filterList = $params->getFilterList(true);
        $checkboxFilters = $params->getCheckboxFacets();
    } else {
        $filterList = is_array($this->filterList) ? $this->filterList : [];
        $checkboxFilters = is_array($this->checkboxFilters) ? $this->checkboxFilters : [];
    }
    $filterDetails = $this->searchbox()->getFilterDetails($filterList, $checkboxFilters);
    $showFilters = $filterDetails && ($results || $options->getRetainFilterSetting());
?>
<?php $tabConfig = $this->searchTabs()->getTabConfig($this->searchClassId, $this->lookfor, $this->searchIndex, $this->searchType, $hiddenFilters); ?>
<?php if ($this->searchType == 'advanced'): ?>
  <div class="navbar-form navbar-left flip">
    <?php $tabs = $this->context($this)->renderInContext('search/searchTabs', ['searchTabs' => $tabConfig['tabs'], 'showCounts' => false]); ?>
    <?php if (!empty($tabs)): ?><?=$tabs ?><div class="tab-content clearfix"><?php endif; ?>
      <p class="adv_search_terms"><?=$this->transEsc('Your search terms')?>: "<strong><?=$this->escapeHtml($this->lookfor)?></strong>"</p>
      <p class="adv_search_links">
        <a href="<?=$this->url($advSearch)?>?edit=<?=$this->escapeHtmlAttr($this->searchId)?>" rel="nofollow"><?=$this->transEsc('Edit this Advanced Search')?></a> |
        <a href="<?=$this->url($advSearch, [], ['query' => $hiddenFilters])?>" rel="nofollow"><?=$this->transEsc('Start a new Advanced Search')?></a> |
        <a href="<?=$this->url($searchHome, [], ['query' => $hiddenFilters])?>" rel="nofollow"><?=$this->transEsc('Start a new Basic Search')?></a>
      </p>
      <?=
        $this->context($this)->renderInContext(
        'search/filters.phtml',
        [
          'params' => $params ?? null,
          'urlQuery' => isset($results) ? $results->getUrlQuery() : null,
          'filterList' => $showFilters ? $filterList : [],
          'checkboxFilters' => $showFilters ? $checkboxFilters : [],
          'searchClassId' => $this->searchClassId,
          'searchType' => $this->searchType,
        ]
        );
      ?>
    <?php if (!empty($tabs)): ?></div><?php endif; ?>
  </div>
<?php else: ?>
  <div class="keyboard-box">
    <div class="simple-keyboard"></div>
  </div>
  <form id="searchForm" class="searchForm navbar-form navbar-left flip tuefind-event-searchForm-on-submit" method="get" action="<?=$this->url($basicSearch)?>" name="searchForm" autocomplete="off">
    <?= $this->context($this)->renderInContext('search/searchTabs', ['searchTabs' => $tabConfig['tabs'], 'hiddenFilters' => $hiddenFilters, 'showCounts' => $tabConfig['showCounts']]); ?>
    <div class="searchForm-inputs">
      <?php
        // Note: we need type="text" for autocomplete role="combobox"
        $searchboxAttributes = [
          'id' => 'searchForm_lookfor',
          'class' => 'searchForm_lookfor form-control search-query',
          'type' => 'text',
          'name' => 'lookfor',
          'value' => $this->lookfor,
          'aria-label' => $this->translate('search_terms'),
        ];
        if ($placeholder = $this->searchbox()->getPlaceholderText($tabConfig['selected']['id'] ?? $this->searchClassId)) {
          $searchboxAttributes['placeholder'] = $this->translate($placeholder);
        }
        if ($this->searchbox()->autocompleteEnabled($this->searchClassId)) {
          $searchboxAttributes['class'] .= " autocomplete searcher:{$this->searchClassId}"
            . ($this->searchbox()->autocompleteAutoSubmit($this->searchClassId) ? ' ac-auto-submit' : '');
          $searchboxAttributes['data-autocomplete-formatting-rules'] = $this->searchbox()->autocompleteFormattingRulesJson($this->searchClassId);
        }
        if (!empty($keyboardLayouts)) {
          $searchboxAttributes['class'] .= ' with-keyboard-selection';
        }
      ?>
      <div class="searchForm-query">
        <input<?=$this->htmlAttributes($searchboxAttributes)?>>
        <div id="searchForm_controls">
          <button id="searchForm-reset" class="searchForm-reset hidden" type="reset" tabindex="-1" aria-label="<?=$this->transEscAttr('searchform_reset_button')?>"><?=$this->icon('ui-reset-search');?></button>
          <?php if (!empty($keyboardLayouts)): ?>
            <?php
            $this->headScript()->appendFile('vendor/js.cookie.js');
            $this->headScript()->appendFile('vendor/simple-keyboard/index.js');
            $this->headScript()->appendFile('vendor/simple-keyboard-layouts/index.js');
            $this->headLink()->appendStylesheet('vendor/simple-keyboard/index.css');
            ?>
            <div class="keyboard-selection dropdown">
              <button class="btn btn-primary dropdown-toggle" type="button" id="keyboard-selection-button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <?=$this->icon('keyboard-o') ?>
                <?=$this->icon('caret-down') ?>
              </button>
              <ul class="dropdown-menu" aria-labelledby="keyboard-selection-button">
                <li>
                  <a class="dropdown-item keyboard-selection-item" href="#" data-value="none"><?= $this->transEsc('None') ?></a>
                </li>
                <?php foreach ($keyboardLayouts as $keyboardLayout): ?>
                  <li>
                    <a class="keyboard-selection-item" href="#" data-value="<?= $this->escapeHtmlAttr($keyboardLayout) ?>"><?= $this->transEsc("KeyboardLayout::$keyboardLayout") ?></a>
                  </li>
                <?php endforeach; ?>
              </ul>
            </div>
          <?php endif; ?>
        </div>
      </div>
      <?php if ($handlerCount > 1): ?>
        <select id="searchForm_type" class="searchForm_type form-control" name="type" data-native-menu="false" aria-label="<?=$this->transEscAttr('Search type')?>">
          <?php $currentGroup = $insideGroup = false; ?>
          <?php foreach ($handlers as $handler): ?>
            <?php
              if ($currentGroup !== ($handler['group'] ?? false)) {
                $currentGroup = $handler['group'];
                if ($insideGroup) {
                  echo '</optgroup>';
                }
                if ($currentGroup) {
                  echo '<optgroup label="' . $this->escapeHtmlAttr($currentGroup) . '">';
                  $insideGroup = true;
                } else {
                  $insideGroup = false;
                }
              }
            ?>
            <option value="<?=$this->escapeHtmlAttr($handler['value'])?>"<?=$handler['selected'] ? ' selected="selected"' : ''?>><?=$handler['indent'] ? '-- ' : ''?><?=$this->transEsc($handler['label'])?></option>
          <?php endforeach; ?>
          <?php if ($insideGroup): ?>
            </optgroup>
          <?php endif; ?>
        </select>
        <?php elseif ($handlerCount == 1): ?>
          <input type="hidden" name="type" value="<?=$this->escapeHtmlAttr($handlers[0]['value'])?>">
        <?php endif; ?>
        <button type="submit" class="btn btn-primary"><?=$this->icon('search') ?> <?=$this->transEsc('Find')?></button>
    <?php if ($geoUrl = $this->geocoords()->getSearchUrl($options)) : ?>
        <a href="<?=$geoUrl ?>" class="btn btn-link"><?=$this->transEsc('Geographic Search')?></a>
    <?php endif; ?>

    <?php $shards = $options->getShards(); ?>
     <?php if ($options->showShardCheckboxes() && !empty($shards)): ?>
      <?php
      $selectedShards = $this->selectedShards ?? $options->getDefaultSelectedShards();
      ?>
      <br>
      <?php foreach ($shards as $shard => $val): ?>
        <?php $isSelected = empty($selectedShards) || in_array($shard, $selectedShards); ?>
          <input type="checkbox" <?=$isSelected ? 'checked="checked" ' : ''?>name="shard[]" value='<?=$this->escapeHtmlAttr($shard)?>'> <?=$this->transEsc($shard)?>
      <?php endforeach; ?>
    <?php endif; ?>
    <?php if (($hasDefaultsApplied ?? false) || !empty($filterDetails)): ?>
      <?php if ($options->getRetainFilterSetting()): ?>
        <?php foreach ($filterDetails as $current): ?>
          <input class="applied-filter" id="<?=$this->escapeHtmlAttr($current['id'])?>" type="hidden" name="filter[]" value="<?=$this->escapeHtmlAttr($current['value'])?>">
        <?php endforeach; ?>
        <?php if ($hasDefaultsApplied ?? false): ?>
          <input class="applied-filter" id="dfApplied" type="hidden" name="dfApplied" value="1">
        <?php endif; ?>
      <?php endif; ?>
    <?php endif; ?>
    <?php foreach ($hiddenFilters as $key => $filter): ?>
      <?php foreach ($filter as $value): ?>
        <?php preg_match ( '/\[NOW-(\d+)DAY TO NOW\]-id:LR\*/', $value, $matchesValue ); if (count($filter) == 1 && !empty($matchesValue) && $routeParams['controller'] == 'Search' && $routeParams['action'] == 'NewItem'): ?>
          <input type="hidden" name="hiddenFilters[]" value="">
        <?php else: ?>
          <input type="hidden" name="hiddenFilters[]" value="<?=$this->escapeHtmlAttr($key) . ':' . $this->escapeHtmlAttr('"' . $value . '"')?>">
        <?php endif; ?>
      <?php endforeach; ?>
    <?php endforeach; ?>
    <?php
      /* Show hidden field for active search class when in combined handler mode. */
      if ($this->searchbox()->combinedHandlersActive()) {
        echo '<input type="hidden" name="activeSearchClassId" value="' . $this->escapeHtmlAttr($this->searchClassId) . '">';
      }
      /* Load hidden limit preference from Session */
      if (!empty($lastLimit)) {
        echo '<input type="hidden" name="limit" value="' . $this->escapeHtmlAttr($lastLimit) . '">';
      }
      if (!empty($lastSort) && $lastSort !== $params?->getDefaultSort()) {
        echo '<input type="hidden" name="sort" value="' . $this->escapeHtmlAttr($lastSort) . '">';
      }
    ?>
    </div>

    <ul class="nav nav-pills">
      <?php if ($advSearch): ?>
        <?php
          $advSearchQuery = $results ? ['edit' => $results->getSearchId()] : $hiddenFilters;
          $advSearchLink = $this->url($advSearch, [], ['query' => $advSearchQuery]);
        ?>
        <li><a href="<?=$advSearchLink?>" class="advanced-search-link btn btn-link" rel="nofollow"><?=$this->transEsc('Advanced')?></a></li>
      <?php endif; ?>

      <li class="dropdown">
        <a class="dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
          <?=$this->transEsc('Browse')?>
          <span class="caret"></span>
        </a>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
          <li><a href="<?=$this->url('keywordchainsearch-home')?>" rel="nofollow"><?=$this->transEsc('Browse Keywordchains')?></a></li>
          <li><a href="<?=$this->url('browse-home')?>" rel="nofollow"><?=$this->transEsc('Browse the Catalog')?></a></li>
          <li><a href="<?=$this->url('alphabrowse-home')?>" rel="nofollow"><?=$this->transEsc('Browse Alphabetically')?></a></li>
        </ul>
      </li>

      <li class="dropdown">
        <a class="dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
          <?=$this->transEsc('link_text_need_help')?>
          <span class="caret"></span>
        </a>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
          <li><a href="<?=$this->url('help-home')?>?topic=search" data-lightbox class="help-link" title="<?=$this->transEsc('Search Tips')?>"><?=$this->transEsc('Search Tips')?></a></li>
        </ul>
      </li>

      <li><a href="<?=$this->url('search-newitem')?>" class="advanced-search-link btn btn-link" rel="nofollow"><?=$this->transEsc('New Items')?></a></li>
    </ul>
    <?=$this->context($this)->renderInContext(
      'search/filters.phtml',
      [
        'params' => $params ?? null,
        'urlQuery' => isset($results) ? $results->getUrlQuery() : null,
        'filterList' => $showFilters ? $filterList : [],
        'checkboxFilters' => $showFilters ? $checkboxFilters : [],
        'searchClassId' => $this->searchClassId,
        'searchType' => $this->searchType,
      ]
    );?>
  </form>
<?php endif; ?>
