<div id="searchbox_news">
    <h2><?=$this->transEsc('RelBib News')?></h2>
    <ul>
        <li><a href="<?=$this->url('content-page', ['page' => 'survey_results_2023'])?>"><b>Ergebnisse der RelBib-Umfrage 2023</b></a></li>
        <li><a href="<?=$this->url('content-page', ['page' => 'news'])?>#11_2023"><b>RelBib LunchTalk "Zweitveröffentlichen mit RelBib – Der neue Self-Archiving Service des FID Religionswissenschaft" am 15.11.2023</b></a></li>
        <li><a href="<?=$this->url('content-page', ['page' => 'news'])?>#02_2023"><b>RelBib LunchTalk "Open Access publizieren – Allgemeine Informationen und Angebote des FID Religionswissenschaft" am 22.03.2023</b></a></li>
    </ul>
    <a href="<?=$this->url('content-page', ['page' => 'news'])?>#archive">Archiv</a>
</div>
