<div id="searchbox_news">
    <h2><?=$this->transEsc('RelBib News')?></h2>
    <ul>
        <li><a href="<?=$this->url('content-page', ['page' => 'news'])?>#11_2025"><b>Neues Kooperationsprojekt mit dem IAHR Women Scholars Network</b></a></li>
		<li><a href="<?=$this->url('content-page', ['page' => 'news'])?>#07_2025"><b>"Vocabulary for the Study of Religion Online" als FID-Lizenz freigeschaltet</b></a></li>
		<li><a href="<?=$this->url('content-page', ['page' => 'news'])?>#12_2024"><b>RelBib hostet die <i>Zeitschrift für junge Religionswissenschaft</i> (ZjR)</b></a></li>
    </ul>
    <a href="<?=$this->url('content-page', ['page' => 'news'])?>#archive">Archiv</a>
</div>