<div id="searchbox_news">
    <h2><?=$this->transEsc('RelBib News')?></h2>
    <ul>
        <li><a href="<?=$this->url('content-page', ['page' => 'news'])?>#07_2024"><b>Neues Open-Access-Angebot: Digitalisierung on Demand</b></a></li>
        <li><a href="<?=$this->url('content-page', ['page' => 'news'])?>#04_2024"><b>Handbuch der Religionen als FID-Lizenz freigeschaltet</b></a></li>
        <li><a href="<?=$this->url('content-page', ['page' => 'news'])?>#03_2024"><b>Ergebnisse der RelBib-Umfrage 2023</b></a></li>
    </ul>
    <a href="<?=$this->url('content-page', ['page' => 'news'])?>#archive">Archiv</a>
</div>
