<div id="searchbox_news">
    <h2><?=$this->transEsc('RelBib News')?></h2>
    <ul>
        <li><a href="<?=$this->url('content-page', ['page' => 'news'])?>#12_2024"><b>RelBib is hosting the <i>Zeitschrift für junge Religionswissenschaft</i> (ZjR)</b></a></li>
		<li><a href="<?=$this->url('content-page', ['page' => 'news'])?>#07_2024"><b>New Open Access service: Digitisation on Demand</b></a></li>
        <li><a href="<?=$this->url('content-page', ['page' => 'news'])?>#05_2022"><b>National Licence for World Religion Database (WRD) now available!</b></a></li>
    </ul>
    <a href="<?=$this->url('content-page', ['page' => 'news'])?>#archive">archive</a>
</div>
