<!-- RelBib: don't show university & library logos here, because we have it in header already -->
<div class="row rb-footer-partners-logos">
    <div class="col-xs-12 col-sm-1 rb-footer-supporter"></div>
    <div class="col-xs-12 col-sm-2 rb-footer-supporter">
        <a target="_blank" href="//dfg.de"><img src="<?=$this->imageLink('dfg_logo_schriftzug.svg') ?>" alt="DFG" width="" height="" /></a>
    </div>
    <div class="col-xs-12 col-sm-2 rb-footer-supporter">
        <a target="_blank" href="//www.dvrw.uni-hannover.de"><img src="<?=$this->imageLink('partners/dvrw_logo.png') ?>" alt="DVRW" width="" height="" /></a>
    </div>
    <div class="col-xs-12 col-sm-2 rb-footer-supporter">
        <a target="_blank" href="//www.remid.de"><img src="<?=$this->imageLink('partners/remid.jpg') ?>" alt="REMID" width="" height="" /></a>
    </div>
    <div class="col-xs-12 col-sm-2 rb-footer-supporter">
        <a target="_blank" href="//www.uni-marburg.de/de/ub"><img src="<?=$this->imageLink('partners/marburg.png') ?>" alt="Universit&auml; Marburg" width="" height="" /></a>
    </div>
    <div class="col-xs-12 col-sm-2 rb-footer-supporter">
        <a target="_blank" href="https://saekulareweltanschauungen.wordpress.com/"><img src="<?=$this->imageLink('partners/Logo_AKsaek.png') ?>" alt="AKsaek" width="" height="" /></a>
    </div>
    <div class="col-xs-12 col-sm-1 rb-footer-supporter"></div>
</div>
