<?php
$appellations = IxTheo\Auth\Database::$appellations;
$titles = IxTheo\Auth\Database::$titles;

  /**
   * TueFind:
   * - Changed order of fields
   * - This template is not only used when creating new users,
   *   but also when editing existing ones.
   */

$pattern = '';
if (isset($this->passwordPolicy['pattern'])) {
  if ($this->passwordPolicy['pattern'] == 'numeric') {
    $pattern = '\d+';
  } elseif ($this->passwordPolicy['pattern'] == 'alphanumeric') {
    $pattern = '[\da-zA-Z]+';
  } else {
    $pattern = $this->passwordPolicy['pattern'];
  }
}
?>
<div class="form-group">
  <label class="control-label" for="account_username"><?=$this->transEsc('Username')?>:</label>
  <input id="account_username" type="text" name="username" required aria-required="true" value="<?=$this->profile ? $this->escapeHtmlAttr($this->user->username) : $this->escapeHtmlAttr($this->request->get('username'))?>" class="form-control" <?=$this->profile ? 'disabled' : ''?>/>
  <?php if (!$this->profile && $this->usernamePolicy['hint']): ?>
    <div class="help-block"><?=$this->transEsc($this->usernamePolicy['hint']) ?></div>
  <?php endif; ?>
  <div class="help-block with-errors"></div>
</div>
<div class="form-group">
  <label class="control-label" for="account_email"><?=$this->transEsc('Email Address')?>:</label>
  <input id="account_email" type="email" name="email" required aria-required="true" value="<?=$this->profile ? $this->escapeHtmlAttr($this->user->email) : $this->escapeHtmlAttr($this->request->get('email'))?>" class="form-control" <?=$this->profile ? 'disabled' : ''?>/>
  <div class="help-block with-errors"></div>
</div>
<?php if (!$this->profile): ?>
<div class="form-group">
  <label class="control-label" for="account_password"><?= $this->transEsc('Password') ?>:</label>
    <input id="account_password" type="password" name="password" required aria-required="true" class="form-control"
      <?=isset($this->passwordPolicy['minLength']) ? ' data-minlength="' . $this->passwordPolicy['minLength'] . '" data-minlength-error="' . $this->transEscAttr('password_minimum_length', ['%%minlength%%' => $this->passwordPolicy['minLength']]) . '"' : ''?>
      <?=isset($this->passwordPolicy['maxLength']) ? ' maxlength="' . $this->passwordPolicy['maxLength'] . '"' : ''?>
      <?=$pattern ? ' pattern="' . $pattern . '"' : '' ?>
    />
  <?php if ($this->passwordPolicy['hint']): ?>
    <div class="help-block"><?=$this->transEsc($this->passwordPolicy['hint']) ?></div>
  <?php endif;?>
  <div class="help-block with-errors"></div>
</div>
<div class="form-group">
  <label class="control-label" for="account_password2"><?=$this->transEsc('Password Again')?>:</label>
  <input id="account_password2" type="password" name="password2" required class="form-control" data-match="#account_password" data-match-error="<?=$this->transEscAttr('Passwords do not match')?>" autocomplete="new-password">
  <div class="help-block with-errors"></div>
</div>
<?php endif; ?>

<!-- IxTheo-specific: Appellation + Title -->
<div class="form-group">
  <label class="control-label" for="ixtheo_appellation"><?= $this->transEsc('Appellation') ?>:</label>
  <select id="account_appellation" name="ixtheo_appellation" class="form-control">
    <?php foreach ($appellations as $appellation): ?>
      <?php $selected = $this->request->get('ixtheo_appellation') === $appellation ? 'selected' : ''; ?>
      <option <?= $selected; ?> value="<?= $appellation; ?>"><?= $this->transEsc($appellation); ?></option>
    <?php endforeach; ?>
  </select>
</div>
<div class="form-group">
  <label class="control-label" for="ixtheo_title"><?= $this->transEsc('Title') ?>:</label>
  <select id="account_title" name="ixtheo_title" class="form-control">
    <?php foreach ($titles as $title): ?>
      <?php $selected = $this->request->get('ixtheo_title') == $title ? 'selected' : ''; ?>
      <option <?= $selected; ?> value="<?= $title; ?>"><?= $this->transEsc($title); ?></option>
    <?php endforeach; ?>
  </select>
</div>

<div class="form-group">
  <label class="control-label" for="account_firstname"><?=$this->transEsc('First Name')?>:</label>
  <input id="account_firstname" type="text" name="firstname" value="<?=$this->escapeHtmlAttr($this->request->get('firstname'))?>" class="form-control"/>
</div>
<div class="form-group">
  <label class="control-label" for="account_lastname"><?=$this->transEsc('Last Name')?>:</label>
  <input id="account_lastname" type="text" name="lastname" value="<?=$this->escapeHtmlAttr($this->request->get('lastname'))?>" class="form-control"/>
</div>

<!-- TueFind-specific: Additional fields -->
<?=$this->context($this)->renderInContext("myresearch/additional_fields.phtml", [])?>
