<div class="row ix-footer-block">
    <div class="col-xs-12 col-md-6 col-lg-7 copyright">
        <?=$this->content()->renderTranslated('snippets/copyright'); ?>
    </div>
    <div class="col-xs-12 col-md-6 col-lg-5 footer-menu">
        <ul class="footer-menu">
            <li>
                <a target="blank" href="//bsky.app/profile/ixtheo.bsky.social"><img src="<?=$this->imageLink('bluesky.svg')?>" height="30" alt="Bluesky"></a>
                <a target="blank" href="//twitter.com/ix_theo"><img src="<?=$this->imageLink('twitter.svg')?>" height="30" alt="Twitter"></a>
                <a target="blank" href="//hcommons.social/@ixtheo"><img src="<?=$this->imageLink('mastodon.svg')?>" height="30" alt="Mastodon"></a>
            </li>
            <li><a href="<?=$this->url('content-page', ['page' => 'Impressum'])?>"><?=$this->translate('Imprint');?></a></li>
            <li><a target="_blank" href="<?=$this->url('content-page', ['page' => 'privacy'])?>"><?=$this->translate('Privacy Protection');?></a></li>
        </ul>
    </div>
</div>
