<div class="row ix2-footer-block">
    <div class="col-12 col-xs-12 col-sm-6 col-md-6 col-lg-7 copyright">
        <?=$this->content()->renderTranslated('snippets/copyright'); ?>
    </div>
    <div class="col-12 col-xs-12 col-sm-6 col-md-6 col-lg-5 footer-menu">
        <ul class="footer-menu">
            <li><a href="<?=$this->url('content-page', ['page' => 'Impressum'])?>"><?=$this->translate('About this site');?></a></li>
            <li><a target="_blank" href="<?=$this->url('content-page', ['page' => 'Privacy'])?>"><?=$this->translate('Privacy Policy');?></a></li>
        </ul>
    </div>
</div>
