<?php 
  $list = $this->params->getSortList(); 
  $listCount = count($list);
  $hiddenFilters = $params->getHiddenFilters();
  $currentPath = $this->currentPath();
?> 
<?php if ($listCount > 0): ?>
  <form class="search-sort" action="<?=$currentPath;?>" method="get" name="sort">
    <?=$this->results->getUrlQuery()->asHiddenFields(['sort' => '/.*/', 'page' => '/.*/']);?>
    <?php foreach ($hiddenFilters as $key => $filter): ?>
      <?php foreach ($filter as $value): ?>
        <?php if(!str_contains($currentPath, $key)): ?>
          <input type="hidden" name="hiddenFilters[]" value="<?=$this->escapeHtmlAttr($key) . ':' . $this->escapeHtmlAttr('"' . $value . '"')?>">
        <?php endif;?>
      <?php endforeach; ?>
    <?php endforeach; ?>
    <label for="sort_options_1"><?=$this->transEsc('Sort')?></label>
    <select id="sort_options_1" name="sort" class="jumpMenu form-control"
      <?php $default_sort = $this->params->getOptions()->getDefaultSortByHandler();?>
      <?php if ($default_sort != null): ?>
        data-default_sort="<?=$default_sort?>"
      <?php endif; ?>
      <?= $this->params->getOptions() instanceof \IxTheo\Search\Solr\Options && $this->params->getQuery() instanceof \VuFindSearch\Query\Query && in_array($this->params->getQuery()->getHandler(), $this->params->getOptions()->getForceDefaultSortSearches()) ? 'disabled' : '' ?>>
      <?php foreach ($list as $sortType => $sortData): ?>
        <option value="<?=$this->escapeHtmlAttr($sortType)?>"<?=$sortData['selected'] ? ' selected="selected"' : ''?><?=$sortData['default'] ? ' data-default' : ''?>><?=$this->transEsc($sortData['desc'])?></option>
      <?php endforeach; ?>
    </select>
    <noscript><input type="submit" class="btn btn-default" value="<?=$this->transEscAttr('Set')?>"></noscript>
  </form>
<?php endif; ?>
