<?php
  $this->metadata()->generateMetatags($this->driver);
?>
<?php /* TueFind: Intentionally omit schema.org type "Product".
       * For testing: https://search.google.com/test/rich-results
       */ ?>
<div class="media" vocab="http://schema.org/" resource="#record" typeof="<?=$this->driver->getSchemaOrgFormats()?>">
  <?php
    $QRCode = $this->record($this->driver)->getQRCode('core');
    $coverDetails = $this->record($this->driver)->getCoverDetails('core', 'medium', $this->record($this->driver)->getThumbnail('large'));
    $cover = $coverDetails['html'];
    $preview = ($this->previewOverride ?? false)
      ? $this->previewOverride : $this->record($this->driver)->getPreviews();
    $rating = $this->driver->isRatingAllowed();
  ?>

  <?php /* TueFind: Intentionally removed the whole block for QRCode / Cover / Preview at this point */ ?>

  <div class="media-body">

    <?php /* TueFind: Get title from custom RecordDriver function */ ?>
    <h3 property="name"><?=$this->escapeHtml($this->driver->getTitle())?></h3>

    <?php if ($this->driver->getExtraDetail('cached_record') && !$this->translationEmpty('cached_record_warning')): ?>
      <div class="alert alert-warning">
        <?=$this->transEsc('cached_record_warning')?>
      </div>
    <?php endif; ?>

    <?php foreach ($this->driver->tryMethod('getFullTitlesAltScript', [], []) as $altTitle): ?>
      <div class="title-alt">
        <?=$this->escapeHtml($altTitle)?>
      </div>
    <?php endforeach; ?>

    <?php if(!empty($this->extraControls)): ?>
      <?=$this->extraControls['actionControls'] ?? ''?>
      <?=$this->extraControls['availabilityInfo'] ?? ''?>
    <?php endif; ?>

    <?php if ($this->searchOptions($this->driver->getSourceIdentifier())->getVersionsAction()): ?>
      <?=$this->record($this->driver)->renderTemplate('versions-link.phtml')?>
    <?php endif; ?>

    <?php $summary = $this->driver->getSummary(); ?>
    <?php if ($summary = isset($summary[0]) ? $this->escapeHtml($summary[0]) : false): ?>
      <p><?=$this->truncate($summary, 300)?></p>

      <?php if(strlen($summary) > 300): ?>
        <p><a href="<?=$this->escapeHtmlAttr($this->recordLinker()->getTabUrl($this->driver, 'Description'))?>#tabnav"><?=$this->transEsc('Full description')?></a></p>
      <?php endif; ?>
    <?php endif; ?>

    <?php if ($this->userlist()->getMode() !== 'disabled'): ?>
      <?php /* Display the lists that this record is saved to */ ?>
      <div class="savedLists">
        <strong><?=$this->transEsc('Saved in')?>:</strong>
        <a href="<?=$this->url('myresearch-favorites')?>" data-lightbox class="tf-favoritesListModal tf-d-none">&nbsp;</a>
      </div>
    <?php endif; ?>

    <?php /* Display Main Details */ ?>
    <?php
      $formatter = $this->recordDataFormatter();
      $coreFields = $formatter->getData($driver, $formatter->getDefaults('core'));
    ?>
    <?php if (!empty($coreFields)): ?>
      <table class="table table-striped">
        <!-- TueFind: different column widths -->
        <colgroup>
          <col width="2*">
          <col width="5*">
        </colgroup>
        <caption class="sr-only"><?=$this->transEsc('Bibliographic Details')?></caption>
        <?php foreach ($coreFields as $current): ?>
          <?php /* TueFind: possibility to add rowId, e.g. for PDA */ ?>
          <tr<?=(isset($current['options']['rowId'])) ? ' id="'.$current['options']['rowId'].'"' : ''?>><th><?=$this->transEsc($current['label'])?>:</th><td><?=$current['value']?></td></tr>
        <?php endforeach; ?>
      </table>
    <?php endif; ?>
    <?php /* End Main Details */ ?>
  </div>
</div>
