<?php $infos = []; ?>
<?php $issue = $this->driver->getIssue(); ?>
<?php $pages = $this->driver->getPages(); ?>
<?php $volume = $this->driver->getVolume(); ?>
<?php $year = $this->driver->getYear(); ?>
<?php if (!empty($year)) { $infos[] = $this->transEsc('Year') . ': ' . $this->escapeHtml($year); }?>
<?php if (!empty($volume)) { $infos[] = $this->transEsc('Volume') . ': ' . $this->escapeHtml($volume); }?>
<?php if (!empty($issue)) { $infos[] = $this->transEsc('Issue') . ': ' . $this->escapeHtml($issue); }?>
<?php if (!empty($pages)) { $infos[] = $this->transEsc('Pages') . ': ' . $this->escapeHtml($pages); }?>
<?php $ids_and_titles = $this->driver->getContainerIDsAndTitles();?>
<?php if (sizeof($ids_and_titles)): ?>
  <?php $i=0; ?>
  <?php foreach ($ids_and_titles as $id => $title): ?>
    <a href="<?=$this->url("record", ["id" => $id]);?>">
      <?=$this->escapeHtml($title[0])?>
      <?php if (!empty($title[1])): ?>
        (<?=$title[1]?>)
      <?php endif; ?>
    </a>
    <br/>
    <?php if ($i == 0): ?><?=$this->escapeHtml(implode(', ', $infos));?><br/><?php endif; ?>
    <?php ++$i; ?>
  <?php endforeach; ?>
<?php elseif (!empty($this->driver->getSuperiorFrom773())): ?>
  <?=nl2br($this->escapeHtml(implode("\n\n", $this->driver->getSuperiorFrom773())));?>
<?php else: ?>
  <?=$this->escapeHtml(implode(', ', $infos));?>
<?php endif; ?>
