<?php if ($this->tuefind()->getKfl()->hasTitle($this->driver)): ?>
<a href="<?=$this->url('redirect-license', ['id' => $this->driver->getUniqueId()])?>" class="fulltext" data-lightbox="" rel="nofollow"><i class="fa fa-external-link"></i> FID-Lizenz: Zugriff mit <?=$this->tuefind()->getTueFindType()?>-Konto</a><br>
<?php endif; ?>

<?php $urls_and_material_types = $this->driver->getURLsAndMaterialTypes();?>
  <?php if ($this->showDspaceLink === true): ?>
    <?php $urls_and_material_types[$this->dspacelink] = $this->tuefind()->getTueFindType() . ' publication service'; ?>
  <?php endif; ?>
<?php if (!empty($urls_and_material_types)): ?>
  <?php $material_types = array_values($urls_and_material_types); ?>
  <?php $direct_oa_fulltext_present = !empty(preg_grep('/Volltext.*kostenfrei.*/', $material_types))?>
  <?php foreach ($urls_and_material_types as $url => $material_type): ?>
    <?php if ($direct_oa_fulltext_present && $material_type == 'Presumably Free Access'): ?>
      <?php continue; ?>
    <?php else: ?>
      <a href="<?=$url?>" class="fulltext" target="_blank"><i class="fa fa-external-link"></i>
      <?php if (preg_match('/([^)]+?)\s*\\(([^)]+)\\)/', $material_type, $material_type_components)): ?>
        <?=$this->transEsc($material_type_components[1]) . ' (' . $this->transEsc($material_type_components[2]) . ')'?>
      <?php else: ?>
        <?=$this->transEsc($material_type)?>
      <?php endif; ?>
      </a><br/>
    <?php endif; ?>
  <?php endforeach; ?>
<?php endif; ?>

<?=$this->identifierLinker($this->driver, 'record')?>

<?php /* IxTheo only: Show feedback form */ ?>
<?php /* If you want to use this in other instances, ensure proper configuration in FeedbackForms.yaml */ ?>
<?php if ($this->tuefind()->getTueFindSubsystem() == 'ixtheo'): ?>
  <a href="<?=$this->url('feedback-form', ['id' => 'SelfArchivingRegisterLink'])?>?ppn=<?=urlencode($this->driver->getUniqueID())?>" rel="nofollow">Open-Access-Link zu Volltext melden</a>
<?php endif; ?>
