<?php $config = $this->config()->get('fulltextsnippet')?>
<?php if (isset($config->Elasticsearch->base_url) && $this->driver->tryMethod('hasFulltextMatch')): ?>
<?php
  $query = $this->params->getQuery();
  $query_terms = $query->getAllTerms();
  $handler = $query instanceof \VuFindSearch\Query\Query ? $query->getHandler() :
              ($query instanceof \VuFindSearch\Query\QueryGroup ? $query->getReducedHandler() : "");
  $synonym_type = "";
  switch ($handler) {
    case "FulltextWithSynonyms":
      $synonym_type = "lang";
      break;
    case "FulltextAllSynonyms":
      $synonym_type = "all";
      break;
  }
  $fulltext_type_filters = $this->driver->getFulltextTypeFilters();
  $fulltext_types = $this->driver->getFulltextTypes();

?>

<span id="fulltext_snippets">
  <div style="color:grey" id="snippet_place_holder_<?=$this->driver->getUniqueID()?>" class="snippet_place_holder"
    data-id="<?=$this->driver->getUniqueID()?>" data-home-url="<?=$this->url('home')?>"
    data-query="<?=$this->escapeHtmlAttr($query_terms)?>" data-synonym-type="<?=$synonym_type?>" data-verbose="false"
    data-fulltext-type-filters="<?=implode(',', $fulltext_type_filters)?>" data-fulltext-types="<?=implode(',', $fulltext_types)?>">
    <?=$this->transEsc("Loading")?>...</div>
</span>
<?php endif; ?>
