<?php if ($this->accountCapabilities()->getPublicationSetting() === 'enabled'):
  $routeParams = $this->tuefind()->getRouteParams();
  $recordId = $routeParams['id'];
  $config = $this->tuefind()->getConfig('tuefind');
  $publication = $this->tuefind()->getPublicationByControlNumber($recordId);
  $authors = $this->driver->getDeduplicatedAuthors();
  $showDspaceLink = false;
  if (isset($publication)) {
    $showDspaceLink = true;
    $dspaceServer = $config->Publication->dspace_url_base;
    if(!strpos($publication->external_document_id, '/')) {
      $dspaceLink = $dspaceServer."/items/".$publication->external_document_guid;
    }else{
      $dspaceLink = $dspaceServer."/xmlui/handle/".$publication->external_document_id;
    }
  }?>
  <li>
    <?php if($showDspaceLink):?>
      <a class="toolbar-btn btn-type-publish" href="<?=$dspaceLink;?>"><?=$this->transEsc('publication_file_button')?></a>
    <?php elseif($this->auth()->isLoggedIn()): ?>
      <a class="toolbar-btn btn-type-publish" data-lightbox href="<?=$this->recordLinker()->getActionUrl($this->driver, 'Publish')?>" rel="nofollow"><?=$this->transEsc('publication_request_button')?></a>
    <?php else: ?>
      <a class="toolbar-btn btn-type-publish" data-lightbox href="<?=$this->url('help-home')?>?topic=publication" rel="nofollow"><?=$this->transEsc('publication_request_button')?></a>
    <?php endif; ?>
  </li>
<?php endif; ?>
