<?php $responseTopicsDataAndSettings = $this->authority()->getTopicsData($this->driver, $this->layout()->userLang); ?>
<?php if(!empty($responseTopicsDataAndSettings[0])): ?>
  <?php

    $this->headLink()->appendStylesheet('vendor/jqcloud.css');
    $this->headScript()->appendFile("vendor/jqcloud-2.0.3.min.js");

    $responseTopicsData = $responseTopicsDataAndSettings[0];
    $responseTopicsSettings = $responseTopicsDataAndSettings[1];

    $jsData = '[';
    foreach($responseTopicsData as $topic) {
      $jsArr = ['text' => $topic['topicTitle'],
                'weight' => $topic['topicNumber'],
                'html' => [
                  'title' => $topic['topicTitle'],
                  'class' => 'custom-class',
                ],
                'link' => [
                  'href' => $topic['topicLink'],
                  'target' => '_blank',
                  'rel' => 'nofollow',
                ]
      ];
      $jsData .= json_encode($jsArr) . ',';
    }
    $jsData .= ']';

    $ascSortingTopicsData = $responseTopicsData;

    $collator = collator_create($this->tuefind()->getTranslatorLocale());
    
    usort($ascSortingTopicsData, function($a, $b) use($collator){
      return $collator->compare($a['topicTitle'], $b['topicTitle']);
    });

    $countSortingTopicsData = $responseTopicsData;
    array_multisort(array_column($countSortingTopicsData, 'topicCount'), SORT_DESC, $countSortingTopicsData);

    $jsSnippetTags = <<<EOD
    $(function () {
      let word_list = $jsData;
      $("#topic_cloud").jQCloud(word_list,{
        autoResize: true,
        encodeURI: false
      });
    });
EOD;
  ?>
  <?=$this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, $jsSnippetTags, 'SET')?>

  <div class="col-md-12 tf-cloud-block">
    <h4><?=$this->transEsc('Suggested Topics')?></h4>
    <div>
      <!-- Nav tabs -->
      <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active"><a href="#authorityCloudFirst" aria-controls="home" role="tab" data-toggle="tab">Cloud</a></li>
        <li role="presentation"><a href="#authorityCloudSecond" aria-controls="profile" role="tab" data-toggle="tab"><?=$this->transEsc('By Alphabetical')?></a></li>
        <li role="presentation"><a href="#authorityCloudThird" aria-controls="messages" role="tab" data-toggle="tab"><?=$this->transEsc('By Popularity')?></a></li>
      </ul>
      <!-- Tab panes -->
      <div class="tab-content tf-p-0">
        <div role="tabpanel" class="tab-pane active" id="authorityCloudFirst">
          <div id="topic_cloud" class="tf-cloud-block-background"></div>
        </div>
        <div role="tabpanel" class="tab-pane" id="authorityCloudSecond">
          <div class="lightbox-scroll full-facets" style="max-height: 350px;">
            <div class="facet-group" id="facet-list-count">
              <?php foreach($ascSortingTopicsData as $topic): ?>
              <a href='<?=$topic['topicLink'];?>' class="facet js-facet-item facetAND" rel="nofollow">
                <span class="text">
                  <span class="facet-value"><?php echo $topic['topicTitle'];?></span>
                </span>
                <span class="badge"><?php echo $topic['topicCount'];?></span>
              </a>
              <?php endforeach; ?>
            </div>
          </div>
        </div>
        <div role="tabpanel" class="tab-pane" id="authorityCloudThird">
          <div class="lightbox-scroll full-facets" style="max-height: 350px;">
            <div class="facet-group" id="facet-list-count">
              <?php foreach($countSortingTopicsData as $topic): ?>
              <a href='<?=$topic['topicLink'];?>' class="facet js-facet-item facetAND" rel="nofollow">
                <span class="text">
                  <span class="facet-value"><?php echo $topic['topicTitle'];?></span>
                </span>
                <span class="badge"><?php echo $topic['topicCount'];?></span>
              </a>
              <?php endforeach; ?>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<?php endif;?>
