<?php
  $form = $this->form;
  $form->prepare();
  $title = $form->getTitle();
  $title = !empty($title)
    ? $this->translate($title) : null;

  $formUrl = $this->url('feedback-form', ['id' => $this->formId]);
  $form->setAttribute('action', $formUrl);
  $form->setAttribute('class', 'dynamic-form');
  $form->setAttribute('method', 'post');

  $translateParams = ['%%TueFindType%%' => $this->tuefind()->getTueFindType(),
                      '%%FIDType%%' => $this->tuefind()->getTueFindFID()];

  $help = $form->getHelp();
  $helpPre = $helpPost = null;
  $helpPre = isset($help['pre']) ? $form->getDisplayString($help['pre'], $translateParams) : null;
  $helpPost = isset($help['post']) ? $form->getDisplayString($help['post'], $translateParams) : null;
?>
<?php if (!$this->inLightbox): ?><div class="feedback-content"><?php endif; ?>
  <?php if ($title): ?>
    <?php $this->headTitle($title); ?>
    <?php $headTag = $this->inLightbox ? 'h2' : 'h1'; ?>
    <<?=$headTag?>><?=$this->escapeHtml($title)?></<?=$headTag?>>
  <?php endif; ?>
  <?=$this->flashmessages()?>

  <?= $this->form()->openTag($form); ?>

  <?php if ($this->formId == "DoD"): ?>
    <div style="font-size:medium; padding: 10px 0;">
      <?php if ($this->layout()->userLang == "de") { ?>
        <p>Der FID Religionswissenschaft fördert den freien Zugang zu religionswissenschaftlich relevanten Publikationen, die entweder gemeinfrei sind oder für die entsprechende Nutzungsrechte von Verlagsseite eingeräumt wurden.</p>
        <p>Mit dem DoD-Service bieten wir allen RelBib-Nutzer*innen mit einem (religions-)wissenschaftlichen Interesse die Möglichkeit, gewünschte Titel aus dem Bestand der UB Tübingen auf Kosten des FID digitalisieren zu lassen. Die Volltexte werden anschließend über RelBib frei zur Verfügung gestellt.</p>
        <p>Im Rahmen des Angebots können einzelne Titel digitalisiert werden, u.a. Monografien, Zeitschriftenbände, Jahrbücher und Sammelwerke, sofern die rechtlichen Bedingungen geklärt sind. Bei umfangreicheren Anfragen (z. B. Digitalisierung ganzer Reihen) nehmen Sie bitte gesondert <a href="mailto:relbib@ub.uni-tuebingen.de">Kontakt</a> mit uns auf.</p>
        <p>Und so geht es:</p>
        <ol>
          <li>Bevor Sie einen Digitalisierungsauftrag an uns richten, bitten wir Sie darum, anhand des <a href="https://kvk.bibliothek.kit.edu/?kataloge=K10PLUS&kataloge=BVB&kataloge=NRW&kataloge=HEBIS&kataloge=KOBV_SOLR&kataloge=DDB&kataloge=STABI_BERLIN&kataloge=TIB&kataloge=VD16&kataloge=VD17&kataloge=VD18&kataloge=BIBOPAC&kataloge=LBOE&kataloge=OENB&kataloge=ABES&kataloge=BASE&kataloge=DART_EUROPE&kataloge=DIGIBIB&kataloge=DFG_EBOOKS&kataloge=DFG_AUFSAETZE&kataloge=DOABOOKS&kataloge=DOAJ&kataloge=EROMM_WEBSEARCH&kataloge=EUROPEANA&kataloge=GOOGLE_BOOKS&kataloge=KUNST_HATHI&kataloge=ARCHIVE_ORG&kataloge=OAPEN&kataloge=ZVDD&kataloge=BHL&digitalOnly=1&embedFulltitle=0&newTab=0">Karlsruher Virtuellen Katalogs</a> zu prüfen, ob der gewünschte Titel bereits frei im Internet zugänglich ist.</li>
          <li>Idealerweise können Sie anhand der Lebensdaten bereits feststellen, ob es sich um einen gemeinfreien Titel handelt:
            <ul>
              <li><b>Ein Werk gilt in Deutschland und in den meisten anderen europäischen Ländern als gemeinfrei, wenn der bzw. die Urheber*in mehr als 70 Jahre verstorben ist (§ 64 UrhG). Bei mehreren Autor*innen gilt die 70-Jahre-Frist ab dem Tod der zuletzt verstorbenen Person. 
                    Wenn Sie als Autor*in eines Werkes vom Verlag die Nutzungsrechte haben, können Sie uns auch diesen Titel für den DoD-Service vorschlagen.
                    Bei Fragen z. B. zur Rechteklärung stehen wir Ihnen gerne beratend zur Seite.</b></li>
            </ul>
          </li>
          <li>Alles passt? Dann füllen Sie bitte das nachstehende Formular aus (Pflichtfelder sind markiert):</li>
        </ol>
      <?php } else {?>
        <p>The FID for the Study of Religion promotes free access to publications relevant to the study of religion that are either in public domain or for which the publisher has granted the corresponding rights of use. </p>
        <p>We offer the DoD service to all RelBib users with an academic interest in the study of religion. Provided that the legal requirements are met, individual titles (e.g. monographs, journal volumes, yearbooks and edited volumes) from the holdings of Tübingen University Library will be digitised at the expense of the FID. The full texts are then made publicly available via RelBib. For more extensive requests (e.g. the digitisation of an entire series), please <a href="mailto:relbib@ub.uni-tuebingen.de">contact us</a> individually.</p>
        <p>As the author of a publication, you can also suggest this title for the DoD service if the publisher has granted you the corresponding rights of use.</p>
        <p>We will be pleased to support you with any questions you may have, e.g. regarding copyright issues.</p>
        <p>This is how it works:</p>
        <ol>
          <li>Before you send us a digitisation request, we kindly ask you to look up the Karlsruhe Virtual Catalogue whether the desired title is already freely accessible via the Internet.</li>
          <li>Ideally, you also check whether the title is in public domain on the basis of the author's life dates.
            <ul>
              <li><b>In Germany and most other European countries, a publication is considered to be in public domain if more than 70 years have passed since the death of the author (§ 64 UrhG). If there is more than one author, the 70-year term applies from when the last of these authors has passed away.</b></li>
            </ul>
          </li>
          <li>Everything done? Then please complete the form below (mandatory fields are asterisked):</li>
        </ol>  
      <?php } ?>  
    </div>   
  <? endif ?>

  <?php if ($helpPre): ?>
  <div class="form-group">
    <div class="form-info pre">
      <?=$helpPre?>
    </div>
  </div>
  <?php endif ?>

  <?php $currentGroup = null; ?>
  <?php foreach ($form->getFormElementConfig() as $el): ?>
    <?php
    $formElement = $form->get($el['name']);

    // Group form elements into field sets
    $handleGroup = $group = null;
    if (isset($el['group']) && !empty($el['group'])) {
      $group = $el['group'];
    }
    if ($group && $currentGroup === null) {
      $handleGroup = 'open';
      $currentGroup = $group;
    } elseif ($currentGroup && !$group) {
      $handleGroup = 'close';
      $currentGroup = null;
    } elseif ($currentGroup !== $group) {
      $handleGroup = 'openAndClose';
      $currentGroup = $group;
    }
    $elementHelpPre = $elementHelpPost = '';
    if ($elementHelp = $el['help'] ?? null) {
      if (is_string($elementHelp)) {
        $elementHelpPre = $elementHelp;
      } else {
        $elementHelpPre = $elementHelp['pre'] ?? '';
        $elementHelpPost = $elementHelp['post'] ?? '';
      }
      $elementHelpPre = $form->getDisplayString($elementHelpPre);
      $elementHelpPost = $form->getDisplayString($elementHelpPost);
    }
    ?>

    <?php if (in_array($handleGroup, ['close', 'openAndClose'])): ?>
      </div>
    <?php endif ?>
    <?php if (in_array($handleGroup, ['open', 'openAndClose'])): ?>
      <?php if (in_array($el['type'], ['checkbox', 'radio'])): ?>
        <div class="field-set" role="group"<?= !empty($el['label']) ? ' aria-labelledby="' . $this->escapeHtmlAttr($el['name']) . '"' : ''?>>
      <?php else: ?>
        <div class="field-set"<?= !empty($elementHelpPre) ? ' role="contentinfo" aria-label="' . $this->escapeHtmlAttr($elementHelpPre) . '"' : ''?>>
      <?php endif ?>
    <?php endif ?>

    <div class="form-group <?= $el['type'] ?> group-<?=$this->escapeHtmlAttr($el['name'])?>">
    <?php if (!empty($elementHelpPre)): ?>
      <p class="info pre"><?=$elementHelpPre?></p>
    <?php endif ?>
    <?php if ($el['type'] !== 'submit'): ?>
      <?php if ($el['label']): ?>
        <?php
          $required = $el['required'] ?? false;
          $requireOne = $el['requireOne'] ?? false;
        ?>
        <?php if (in_array($el['type'], ['checkbox', 'radio'])): ?>
          <p id="<?=$this->escapeHtmlAttr($el['name'])?>" class="control-label radio-label<?=$required && !$requireOne? ' required' : ''?><?=$requireOne ? ' require-one' : ''?>"><?=$this->transEsc($el['label'])?>:</p>
        <?php else: ?>
        <label for="<?=$this->escapeHtmlAttr($el['name'])?>" class="control-label<?=$required ? ' required' : ''?>"><?=$this->transEsc($el['label'])?>:</label>
        <?php endif ?>
      <?php endif ?>
    <?php else: ?>
      <?php if ($helpPost): ?>
        <div class="form-info post">
          <?=$helpPost?>
        </div>
      <?php endif ?>
      <?=$this->captcha()->html($this->useCaptcha) ?>
    <?php endif ?>
    <?= $this->formRow($formElement) ?>
    <?php if (!empty($elementHelpPost)): ?>
      <p class="info post"><?=$elementHelpPost?></p>
    <?php endif ?>
    </div>
  <?php endforeach ?>
  <?= $this->form()->closeTag() ?>
<?php if (!$this->inLightbox): ?></div><?php endif; ?>
