---
# This file contains search specifications used by the authority module; for details
# on the workings of this file, see the comments in searchspecs.yaml.
#-----------------------------------------------------------------------------------

AllFields:
  DismaxFields:
    - allfields
  DismaxHandler: edismax

MainHeading:
  DismaxFields:
    - heading_search^500
