<div class="container cw-py-5">
  <div class="cw-row">
    <div class="cw-col-lg-8">
      <div class="cw-text-block">
        <h1 class="cw-h1">IxTheo A-Z</h1>
        <ul>
          <li><a href="<?=$this->url('content-page', ['page' => 'IxtheoAccount']) ?>">Account</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'News']) ?>">Aktuelles</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'Alerting']) ?>">Alerting</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'Historical']) ?>">Alte Drucke</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'NutzerinnengesteuerteErwerbung']) ?>">Anschaffungsvorschlag</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'ContactPersons']) ?>">Ansprechpartner*innen</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'Innovativ']) ?>">Archivmaterialien</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'Bibliographies']) ?>">Augustinus-Bibliographie: Kooperation</a></li>
          <li>
            <a target="_blank" href="https://ixtheo.de/docs/ixtheo-beacon.txt">BEACON</a><br />
            Die mit der GND-Nummer ausgezeichneten Katalogisate des IxTheo stehen im BEACON-Format (vgl. <a target="_blank" href="https://de.wikipedia.org/wiki/Wikipedia:BEACON">Wikipedia</a>). zur Verfügung. Damit sind wechselseitige Verlinkungen zwischen IxTheo und anderen Datenbanken möglich.
          </li>
          <li><a href="<?=$this->url('content-page', ['page' => 'Beratung']) ?>">Beratung</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'Discover']) ?>">Bibelstellensuche</a></li>
          <li><a target="_blank" href="https://ixtheo.de/docs/Bible_abbreviation.pdf">Biblische Bücher: Abkürzungen</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'Bibliographies']) ?>">BiBIL-Kooperation</a> (Bibliographie biblique informatisée de Lausanne)</li>
          <li><a href="<?=$this->url('content-page', ['page' => 'Bibliographies']) ?>">BILDI-Kooperation</a> (Bibelwissenschaftliche Literaturdokumentation Innsbruck)</li>
          <li><a href="<?=$this->url('content-page', ['page' => 'Innovativ']) ?>">Blogs</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'Discover']) ?>">Browsen</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'BooksAndJournals']) ?>">Bücher & Journals</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'Discover']) ?>">CIC-Suche</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'Bibliographies']) ?>">DaKaR-Kooperation</a> (Datenbank Kanonisches Recht Münster)</li>
          <li><a href="<?=$this->url('content-page', ['page' => 'Innovativ']) ?>">Datenbanken</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'Discover']) ?>">Dewey Decimal Classification (DDC)</a></li>
          <li>Digitalisierung: <a href="<?=$this->url('content-page', ['page' => 'TheologyDigital']) ?>">DigiTheo</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'Fernleihe']) ?>">Dokumentlieferung</a></li>
          <li>Exportieren von Suchergebnissen</li>
          <li><a href="<?=$this->url('content-page', ['page' => 'FidTheologie']) ?>">Fachinformationsdienst (FID) Theologie</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'Alerting']) ?>">Feed-Aggregator</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'Fernleihe']) ?>">Fernleihe</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'Innovativ']) ?>">Forschungsdaten</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'AboutUs']) ?>">Geschichte</a> des Index Theologicus</li>
          <li><a href="<?=$this->url('content-page', ['page' => 'Historical']) ?>">Historische Drucke</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'Impressum']) ?>">Impressum</a></li>
          <li><a target="_blank" href="https://bible.ixtheo.de/">Index Biblicus</a></li>
          <li><a target="_blank" href="https://churchlaw.ixtheo.de/">Index Canonicus</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'Discover']) ?>">Inhaltliche Suche</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'IxtheoAccount']) ?>">IxTheo Account</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'Innovativ']) ?>">IxTheo Innovativ</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'IxTheoClassification']) ?>">IxTheo Klassifikation</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'IxtheoAccount']) ?>">IxTheo-Konto</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'Bibliographies']) ?>">KALDI-Kooperation</a> (Kanonistische Literaturdokumentation Innsbruck)</li>
          <li><a href="<?=$this->url('content-page', ['page' => 'Discover']) ?>">Kirchenrecht (Suche)</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'IxTheoClassification']) ?>">Klassifikation</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'IxtheoAccount']) ?>">Konto</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'Networking']) ?>">Kooperationen</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'LexiconSearch']) ?>">Lexikonrecherche</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'IxtheoAccount']) ?>">Listen zusammenstellen</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'Innovativ']) ?>">Nachlässe/Vorlässe</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'Networking']) ?>">Networking</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'NutzerinnengesteuerteErwerbung']) ?>">Neuanschaffungen auf Nutzer*innenwunsch</a></li>
          <li>Neuerscheinungen: <a href="<?=$this->url('content-page', ['page' => 'Alerting']) ?>">Benachrichtigung (Alerting)</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'News']) ?>">Neuigkeiten</a></li>
          <li><a href="/Search/NewItem">Neuzugänge</a> in IxTheo</li>
          <li>Open Access:<a href="<?=$this->url('content-page', ['page' => 'Ubersicht']) ?>">Übersicht</a></li>
          <li>Open Access:<a href="<?=$this->url('content-page', ['page' => 'TheologyDigital']) ?>">Digitalisierung von Zeitschriften und Monographien (DigiTheo)</a></li>
          <li>Open Access:<a href="<?=$this->url('content-page', ['page' => 'OpenText']) ?>">Self-Archiving</a></li>
          <li>Open Journals:<a href="<?=$this->url('content-page', ['page' => 'OpenJournals']) ?>">Open Access-Zeitschriften</a></li>
          <li>Open Text Service:<a href="<?=$this->url('content-page', ['page' => 'OpenText']) ?>">Zweitveröffentlichung</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'NutzerinnengesteuerteErwerbung']) ?>">Patron Driven Acquisition (PDA)</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'AuthorityPages']) ?>">Personenseiten</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'Alerting']) ?>">Podcasts</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'BooksAndJournals']) ?>">Reihen</a></li>
          <li><a target="_blank" href="https://relbib.de/">RelBib</a> (Religionswissenschaftliche Bibliographie)</li>
          <li><a href="<?=$this->url('content-page', ['page' => 'Alerting']) ?>">RSS-Feed</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'OpenText']) ?>">Self-Archiving</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'Fernleihe']) ?>">subito: kostenpflichtiger Dokumentenlieferdienst</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'IxtheoAccount']) ?>">Suchanfragen speichern</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'Discover']) ?>">Suchen & Browsen</a></li>
          <li>
            <a target="_blank" href="https://uni-tuebingen.de/einrichtungen/universitaetsbibliothek/suchen-ausleihen/fernleihe-dokumentlieferdienste/tad-tuebinger-aufsatzdienst/">Tübinger Aufsatzdienst (TAD)</a><br />
            Lokaler Aufsatzlieferdienst (nur für Wissenschaftler*innen der Universität Tübingen)
          </li>
          <li><a target="_blank" href="https://www.ub.uni-tuebingen.de/">Universitätsbibliothek Tübingen</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'Historical']) ?>">VD16/17/18</a> (Verzeichnisse der im deutschen Sprachbereich erschienenen Drucke des 16., 17. und 18. Jahrhunderts)</li>
          <li><a href="<?=$this->url('content-page', ['page' => 'FullTextSearch']) ?>">Volltextsuche</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'Innovativ']) ?>">Vorlässe/Nachlässe</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'Discover']) ?>">Zeitraumsuche</a></li>
          <li>Zeitschriften: <a target="_blank" href="https://ixtheo.de/docs/ixtheo-journals.pdf">Auswertung in IxTheo</a></li>
          <li>Zeitschriften: <a href="<?=$this->url('content-page', ['page' => 'TheologyDigital']) ?>">Digitalisierung</a></li>
          <li>Zeitschriften: <a href="<?=$this->url('content-page', ['page' => 'OpenAccess']) ?>">Open Access</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => '']) ?>">Zitieren eines gefundenen Titels</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'OpenText']) ?>">Zweitveröffentlichung</a></li>
        </ul>
      </div>
    </div>
  </div>
</div>