<div class="container cw-py-5">
  <div class="cw-row">
    <div class="cw-col-lg-8">
      <div class="cw-text-block">
        <h1 class="cw-h1">IxTheo A-Z</h1>
        <ul>
          <li><a href="<?=$this->url('content-page', ['page' => 'Impressum']) ?>">About this site</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'IxtheoAccount']) ?>">Account</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'NutzerinnengesteuerteErwerbung']) ?>">Acquisition Recommendation</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'Beratung']) ?>">Advisory Services</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'Alerting']) ?>">Alerting</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'Innovativ']) ?>#js_collapse-inno-2">Archival Material</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'Bibliographies']) ?>">Augustinus-Bibliographie: Cooperation</a></li>
          <li><a target="_blank" href="https://ixtheo.de/docs/ixtheo-beacon.txt">BEACON</a><br />Those records of IxTheo which have a GND number are available in the BEACON format (vgl. <a target="_blank" href="https://en.wikipedia.org/wiki/Wikipedia:BEACON">Wikipedia</a>). (see Wikipedia). This makes it possible to create reciprocal links between IxTheo and other databases.</li>
          <li><a href="<?=$this->url('content-page', ['page' => 'Bibliographies']) ?>">BiBIL</a> (Bibliographie biblique informatisée de Lausanne): Cooperation</li>
          <li><a href="<?=$this->url('content-page', ['page' => 'Discover']) ?>#more_post-1">Bible Passages: Search</a></li>
          <li><a target="_blank" href="https://ixtheo.de/docs/Bible_abbreviation.pdf">Biblical Books: Abbreviations</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'Bibliographies']) ?>">BILDI</a> (Bibelwissenschaftliche Literaturdokumentation Innsbruck): Cooperation</li>
          <li><a href="<?=$this->url('content-page', ['page' => 'Innovativ']) ?>#js_collapse-inno-1">Blogs</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'NutzerinnengesteuerteErwerbung']) ?>">Book Acquisition Recommendation</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'BooksAndJournals']) ?>#js_collapse-inno-4">Book Series</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'BooksAndJournals']) ?>">Books & Journals</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'Discover']) ?>#browsing">Browsing</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'Discover']) ?>#more_post-2">Church Law: Search</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'AktionenImSuchergebnis']) ?>#zitieren">Citation of a Work Found in IxTheo</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'IxTheoClassification']) ?>">Classification</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'ContactPersons']) ?>">Contact Persons</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'Networking']) ?>">Cooperations</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'Bibliographies']) ?>">DaKaR</a> (Datenbank Kanonisches Recht): Cooperation</li>
          <li><a href="<?=$this->url('content-page', ['page' => 'Innovativ']) ?>#js_collapse-inno-5">Databases</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'Discover']) ?>#klassifikation">Dewey Decimal Classification (DDC)</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'LexiconSearch']) ?>">Dictionary Search</a></li>
          <li>Digitization: <a href="<?=$this->url('content-page', ['page' => 'TheologyDigital']) ?>">DigiTheo</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'Fernleihe']) ?>">Document Delivery</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'AktionenImSuchergebnis']) ?>#exportieren">Exporting search results</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'FidTheologie']) ?>">Fachinformationsdienst Theologie (FID) - Specialized Information Service in Theology</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'Alerting']) ?>">Feed Aggregator</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'FullTextSearch']) ?>">Full-text Search</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'Historical']) ?>">Historical Printed Works</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'AboutUs']) ?>">History of the Index Theologicus</a></li>
          <li><a target="_blank" href="https://bible.ixtheo.de/">Index Biblicus</a></li>
          <li><a target="_blank" href="https://churchlaw.ixtheo.de/">Index Canonicus</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'Fernleihe']) ?>">Interlibrary Loan</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'IxtheoAccount']) ?>">IxTheo Account</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'IxTheoClassification']) ?>">IxTheo Classification</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'Innovativ']) ?>">IxTheo Innovative</a></li>
          <li>Journals <a target="_blank" href="https://ixtheo.de/docs/ixtheo-journals.pdf">Catalogued and Indexed in IxTheo</a></li>
          <li>Journals: <a href="<?=$this->url('content-page', ['page' => 'TheologyDigital']) ?>">Digitization</a></li>
          <li>Journals: <a href="<?=$this->url('content-page', ['page' => 'OpenAccess']) ?>">Open Access</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'Bibliographies']) ?>">KALDI</a> (Kanonistische Literaturdokumentation Innsbruck): Cooperation</li>
          <li><a href="<?=$this->url('content-page', ['page' => 'IxtheoAccount']) ?>#more_post-3">Lists</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'Networking']) ?>">Networking</a></li>
          <li><a href="/Search/NewItem">New Items in IxTheo</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'Alerting']) ?>">New Publications (Alerting)</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'News']) ?>">News</a></li>
          <li>Open Access: <a href="<?=$this->url('content-page', ['page' => 'Ubersicht']) ?>">Overview</a></li>
          <li>Open Access: <a href="<?=$this->url('content-page', ['page' => 'TheologyDigital']) ?>">Digitization of Journals and Monographs (DigiTheo)</a></li>
          <li>Open Access: <a href="<?=$this->url('content-page', ['page' => 'OpenText']) ?>">Self-Archiving</a></li>
          <li>Open Journals: <a href="<?=$this->url('content-page', ['page' => 'OpenJournals']) ?>">Open Access Journals</a></li>
          <li>Open Text Service: <a href="<?=$this->url('content-page', ['page' => 'OpenText']) ?>">Republication</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'NutzerinnengesteuerteErwerbung']) ?>">Patron Driven Acquisition (PDA)</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'Innovativ']) ?>#js_collapse-inno-3">Personal Archives</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'AuthorityPages']) ?>">Person Information Pages</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'Alerting']) ?>">Podcasts</a></li>
          <li><a target="_blank" href="https://relbib.de/">RelBib</a> (Bibliography for Religious Studies)</li>
          <li><a href="<?=$this->url('content-page', ['page' => 'OpenText']) ?>">Republication</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'Innovativ']) ?>#js_collapse-inno-4">Research Data</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'Alerting']) ?>">RSS-Feed</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'IxtheoAccount']) ?>">Saving Search Requests</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'Discover']) ?>">Search and Browse</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'OpenText']) ?>">Self-Archiving</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'FidTheologie']) ?>">Specialized Information Service in Theology</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'Fernleihe']) ?>">subito: Document Delivery Service</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'Discover']) ?>#klassifikation">Subject Classification: Search</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'Discover']) ?>">Time Ranges: Search</a></li>
          <li><a target="_blank" href="https://uni-tuebingen.de/einrichtungen/universitaetsbibliothek/suchen-ausleihen/fernleihe-dokumentlieferdienste/tad-tuebinger-aufsatzdienst/">Tübinger Aufsatzdienst (TAD)</a><br />A local service to deliver journal articles (only for academics at the University of Tübingen).</li>
          <li><a target="_blank" href="https://uni-tuebingen.de/en/facilities/university-library/">University Library of Tübingen</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'Historical']) ?>">VD16/17/18</a> (Databases of works printed in the German-speaking world during the 16th, 17th and 18th centuries)</li>
        </ul>
      </div>
    </div>
  </div>
</div>
