<div class="cw-row">
  <div class="cw-col-lg-12">
    <div class="cw-text-block"><br>
      <span id="ixtheo_content"></span>
      <h1 class="cw-h1">Index Theologicus</h1>
      <p>Der Index Theologicus (IxTheo) ist eine internationale Open-Access-Bibliographie für Theologie und Religionswissenschaft und beinhaltet Angaben zu wissenschaftlich relevanter Literatur über das Christentum sowie über den Dialog mit anderen Religionen: konfessions-, sprachen-, medien- und zeitübergreifend.</p>
      <p>Herausgeber sind die <a target="_blank" href="https://uni-tuebingen.de/einrichtungen/universitaetsbibliothek/">Universitätsbibliothek Tübingen</a>, die <a target="_blank" href="https://uni-tuebingen.de/fakultaeten/evangelisch-theologische-fakultaet/fakultaet/aktuelles/">Evangelisch-Theologische Fakultät Tübingen</a> und die <a target="_blank" href="https://uni-tuebingen.de/fakultaeten/katholisch-theologische-fakultaet/fakultaet/">Katholisch-Theologische Fakultät Tübingen</a>.</p>
      <p style="text-decoration:underline; color:green;">Die Spezialbibliographien Index Biblicus und Index Canonicus werden in Zusammenarbeit mit Kooperationspartnern erarbeitet und herausgegeben: Beim Index Biblicus fungiert BILDI (Innsbruck) als Mitherausgeber, beim Index Canonicus DaKaR (Münster) und KALDI (Innsbruck).</p>

      <h5><b>Inhalt</b></h5>
      <p>Der Index Theologicus weist Monographien, Sammelwerke, Zeitschriften, Aufsätze, Lexikonartikel, Rezensionen sowie <span style="text-decoration:underline; color:green;">Datenbanken, Archivmaterialien, Nachlässe, Blogs, Podcasts, Forschungsdaten und andere elektronisch verfügbare Inhalte</span> aus allen Fachgebieten der Theologie nach. Die Auswertung erfolgt sprachen-, medien- und konfessionsübergreifend.</p>
      <p>In der Datenbank finden sich neben aktueller theologischer Literatur in zahlreichen Sprachen auch historische Titel bis zurück ins 16. Jahrhundert.</p>
      <p>Über 1.200 internationale theologische und religionswissenschaftliche Zeitschriften werden laufend ausgewertet und mit allen Aufsätzen und Rezensionen nachgewiesen. Bei vielen Zeitschriften sind alle Aufsätze bis zurück zum Erscheinungsbeginn erfasst. Auch der retrospektive Nachweis von Beiträgen aus Sammelwerken wird fortlaufend vorangetrieben.</p>
      <p>Aktuell umfasst die Datenbank rund 4 Mio. Einträge.</p>
      <p>Ausführlichere Informationen finden Sie unter <a href="#ixtheo_content">IxTheo Content</a>.</p>

      <h5><b>Geschichte</b></h5>
      <p>1975 wurde der Zeitschrifteninhaltsdienst Theologie (ZID) in Tübingen gegründet, der die Inhaltsverzeichnisse der wichtigsten im Sondersammelgebiet Theologie (UB Tübingen) abonnierten Zeitschriften abdruckte. Die monatlich erschienenen ZID-Hefte verfügten über Autoren-, Bibelstellen- und Personenregister.</p>
      <p>1995 erfolgte die Umstellung des ZID auf eine Datenbank, in der die bibliographischen Daten der ausgewerteten Zeitschriften elektronisch erfasst und dem Druck der Hefte zugrunde gelegt wurden. </p>
      <p>Zum Jahreswechsel 1995/1996 wies die Datenbank mehr als 22.000 Aufsätze aus ca. 480 Zeitschriften und ausgewählten Festschriften nach. Bereits 1998 war die Zahl der Nachweise auf ca. 67.000 Aufsätze aus fast 600 Zeitschriften und weit über 200 Festschriften angewachsen. Die in den älteren gedruckten Heften enthaltenen bibliographischen Angaben wurden retrospektiv mit erfasst.</p>
      <p>Die ZID-Datenbank wurde zunächst in Form von installierbaren Disketten, später als CD-ROM angeboten. Mit Ablauf des Jahres 2000 wurde die Druckversion des ZID eingestellt.</p>
      <p>Von 1997 bis 2001 vertrieb die UB Tübingen die Datenbank direkt; von 2002 bis 2006 erschien sie, nun unter dem Namen Index Theologicus, im Tübinger Verlag Mohr Siebeck.</p>
      <p>Seit 2007 steht die Datenbank ausschließlich online und kostenlos zur Verfügung.</p>
      <p>Zusätzlich zur Sacherschließung mit normierten Schlagwörtern wird in IxTheo seit 1995 eine Facettenklassifikation (IxTheo-Klassifikation) bestehend aus 13 Hauptgruppen und 139 Klassen verwendet, die eine gezielte Recherche nach Publikationen aus bestimmten Fächern und Themengebieten ermöglicht. Seit 1997 wird die Sacherschließung durch den Verband der Diözesen Deutschlands (VDD) gefördert. Eine wachsende Zahl an Kooperationspartnern <a href="<?=$this->url('content-page', ['page' => 'networking']) ?>">Networking</a> wirkt an der Sacherschließung mit.</p>
      <p>2011 beschloss die UB Tübingen, IxTheo zu einer umfassenden Bibliographie für Theologie und Religionswissenschaft auszubauen, in der neben Aufsätzen auch Monographien und andere fachlich relevante Quellen nachgewiesen werden. Zu diesem Zweck wurden seit 2013 alle neuen Titel im Südwestdeutschen Bibliotheksverbund (SWB) katalogisiert. Nach Abschluss umfangreicher Migrationsvorbereitungen wurden im März 2016 ca. 550.000 Titel aus der ehemaligen IxTheo Allegro-Datenbank in den SWB übertragen. </p>
      <p>Seit 2015 wird IxTheo im Rahmen des Fachinformationsdienstes <a href="<?=$this->url('content-page', ['page' => 'fid_theologie']) ?>"> FID Theologie</a> an der Universitätsbibliothek Tübingen mit Förderung der Deutschen Forschungsgemeinschaft (DFG) technisch und inhaltlich weiterentwickelt.</p>

    </div>
  </div>
</div>
