<div class="cw-row">
  <div class="cw-col-lg-12">
    <div class="cw-text-block"><br>
      <span id="ixtheo_content"></span>
      <h1 class="cw-h1">Index Theologicus</h1>
      <p>The Index Theologicus (IxTheo) is an international open access bibliography for theology and religious studies. It provides information on scholarly literature about Christianity as well as about the dialog with other religions. The bibliography references historical and current publications in multiple languages and formats concerning all confessions and denominations.</p>
      <p>Its editors are the <a target="_blank" href="https://uni-tuebingen.de/en/facilities/university-library/">Universitätsbibliothek Tübingen (University Library of Tübingen</a>, the <a target="_blank" href="https://uni-tuebingen.de/en/fakultaeten/evangelisch-theologische-fakultaet/fakultaet/aktuelles/">Evangelisch-Theologische Fakultät Tübingen (the Protestant faculty of theology of the university of Tübingen)</a> and the <a target="_blank" href="https://uni-tuebingen.de/en/faculties/faculty-of-catholic-theology/faculty/">Katholisch-Theologische Fakultät Tübingen (the Catholic faculty of theology of the university of Tübingen)</a>.</p>
      <p>The specialized bibliographies <a target="_blank" href="https://bible.ixtheo.de/">Index Biblicus</a> und <a target="_blank" href="https://churchlaw.ixtheo.de/?lng=en">Index Canonicus</a> are produced and published in cooperation with the following partners: <a target="_blank" href="https://www.uibk.ac.at/bildi/index.html.en">BILDI (Innsbruck)</a> and <a target="_blank" href="https://www.unil.ch/ftsr/en/home/menuinst/recherche/instituts/irsb.html">BiBIL (Lausanne)</a> for the Index Biblicus, <a target="_blank" href="https://www.uni-muenster.de/FB2/ikr/datenbank/index.shtml">DaKaR (Münster)</a> and <a target="_blank" href="https://www.uibk.ac.at/en/praktheol/kirchenrecht/kaldi/">KALDI (Innsbruck)</a> for the Index Canonicus.</p>
      
      <span id="ixtheo_inhalt"></span>
      <p>&nbsp;</p>
      <h3><b>Contents</b></h3>
      <p>The Index Theologicus provides references to monographs, essay collections, journals, journal articles, lexicon articles, reviews, databases, archival documents, personal archives, blogs, podcasts, research data and other contents which are electronically available from all fields of theology. We catalogue literature in many languages and formats concerning all confessions and denominations.</p>
      <p>Our database includes current theological literature in many languages and historical titles going as far back as the 16th century.</p>
      <p>We catalogue the contents of over 1200 international journals in theology and religious studies on a regular basis, referencing all articles and reviews. Many journals have been catalogued completely up to their very first issue. We are also continuing to catalogue essays from older collections.</p>
      <p>Our database currently holds approximately 4.5 million entries.</p>
      <p>More detailed information is available under  <a href="/#ixtheo-content">IxTheo Content</a>.</p>

      <p>&nbsp;</p>
      <span id="ixtheo_geschichte"></span>
      <h3><b>History</b></h3>
      <p>The “Zeitschrifteninhaltsdienst (ZID) Theologie” (“journal content service for theology”) was founded in 1975 in Tübingen. It provided the tables of contents for the most important journals to which the “Sondersammelgebiet Theologie” (“specialized theology collection”) of the University Library of Tübingen subscribed. The monthly issues of the ZID contained indexes of authors, Bible passages and persons.</p>
      <p>In 1995, the ZID was transferred to a database in which the bibliographical data of the journals was digitally catalogued and which served as the basis for the print issues.</p>
      <p>At the beginning of 1996, the database contained over 22,000 articles from approx. 480 journals and essay collections. In 1998, the contents had already grown to approx. 67,000 articles from almost 600 journals and more than 200 essay collections. The bibliographical information from older print issues of the ZID was also catalogued retrospectively.</p>
      <p>The ZID database was initially offered in installable diskettes, and later as CD-ROMs. The print version of the ZID ceased publication in 2000.</p>
      <p>From 1997 to 2001, the University Library of Tübingen published the database itself. From 2002 to 2006, it was distributed under the name Index Theologicus by the publishing house Mohr Siebeck from Tübingen.</p>
      <p>The database is available online only and free of charge since 2007.</p>
      <p>In addition to subject indexing with keywords, IxTheo has developed its own IxTheo classification system since 1995, consisting of 14 main categories and 141 classifications, which allow the user to search specifically for publications in certain fields and subjects. The indexing work is supported financially by the “Verband der Diözesen Deutschlands (VDD)” (the “association of German dioceses”) since 1997. A growing number of <a target="_blank" href="<?=$this->url('content-page', ['page' => 'Networking']) ?>#content">cooperation partners</a> are contributing to the indexing work. </p>
      <p>The University Library of Tübingen decided in 2011 to expand IxTheo into a comprehensive bibliography for theology and religious studies, in which monographs and other scholarly sources as well as journal articles are referenced. For this purpose, all new titles have been catalogued since 2013 in the system of the “Südwestdeutscher Bibliotheksverbund (SWB)” (the “south-west German library association”). Approx. 550,000 titles were migrated from the old Allegro database into the SWB in March 2016 after extensive preparations.</p>
      <p>Since 2015, the technology and content of IxTheo have been undergoing further development within the framework of the <a href="<?=$this->url('content-page', ['page' => 'FidTheologie']) ?>#content">Fachinformationsdienst Theologie (the “specialized information service in theology”)</a> thanks to grants from the “Deutsche Forschungsgemeinschaft” (the German Research Foundation). More information on the development of IxTheo and about the work in the past and present grant phases is available under <a href="<?=$this->url('content-page', ['page' => 'FidTheologie']) ?>#ixtheo_aufgaben">Tasks</a>.</p>
    
	    <p>&nbsp;</p>
      <span id="ixtheo_publications"></span>
      <h3><b>Further Reading</b></h3>
      <p>Martin Faßnacht, Historical and Media-Theoretical Implications of a Modern International Bibliography: Origin, Development and Future of the Index Theologicus in the Context of Other Specialised Bibliographies, in: Theological Libraries and Library Associations in Europe: A Festschrift on the Occasion of the 50th Anniversary of BETH, herausgegeben von Leo Kenis, Penelope Hall und Marek Rostkowski, Leiden: Brill 2022, 382–428, DOI: <a target="_blank" href="https://doi.org/10.1163/9789004523197_018">10.1163/9789004523197_018</a></p>
      <p>Marianne Dörr, Open Access Information Service for Researchers in Theology, in: LIBER quarterly, (28) 2018, 1-9, DOI: <a target="_blank" href="https://doi.org/10.18352/lq.10245">10.18352/lq.10245</a></p>
      <p>Timotheus Chang-Whae Kim / Philipp Zumstein, Semiautomatische Katalogisierung und Normdatenverknüpfung mit Zotero im Index Theologicus, in: LIBREAS. Library ideas, (29) 2016, 47-56, DOI: <a target="_blank" href="https://doi.org/10.18452/9093">10.18452/9093</a></p>
      <p>Martin Faßnacht / Winfried Gebhard, Index Theologicus - neue Produktionsverfahren bei der Bibliographieerstellung, in: BIT online, (volume 19, issue 6) 2016, 511-514, DOI: <a target="_blank" href="https://doi.org/10.15496/publikation-84614">10.15496/publikation-84614</a></p>
      <p>Martin Faßnacht, Neuausrichtung der Sondersammelgebiete in Deutschland. Überlegungen zum SSG Theologie an der UB Tübingen. Vortrag von Dr. Martin Faßnacht auf dem Katholisch-Theologischen Fakultätentag 2013, hdl: <a target="_blank" href="http://hdl.handle.net/10900/43957">10900/43957</a></p>
      <p>A complete list of publications about the Index Theologicus is available under: <a target="_blank" href="https://ixtheo.de/MyResearch/MyList/3984?filter%5B%5D=lists%3A%223984%22&sort=year+DESC">Publications about IxTheo</a>.</p>
    </div>
	
  </div>
</div>
