<div class="container cw-py-5">
  <div class="cw-row">
    <div class="cw-col-lg-8">
      <div class="cw-text-block">
        <h1 class="cw-h1">Aktionen im Suchergebnis</h1>

        <h1 class="cw-h5" id="zitieren">Zitieren</h1>
        <p>Wenn Sie gefundene Titel zitieren möchten, stehen Ihnen dafür verschiedene Zitationsstile zur Verfügung.</p>
        <p>Gehen Sie in die Vollanzeige des gesuchten Werks und klicken oben links über dem Titel auf die Schaltfläche „Zitieren“.</p>
        <a class="thumbnail" href="#" data-image-id="" data-toggle="modal" data-title="" data-caption="" data-image="/themes/ixtheo2/images/content_img/en/cite_this_eng.png" data-target="#image-gallery">
            <img class="img-responsive" src="/themes/ixtheo2/images/content_img/en/cite_this_eng.png" alt="<?=$this->transEscAttr('symbolic_image_table16');?>">
        </a>
        <p>Sie bekommen den Titel im APA, Chicago- und MLA-Zitierstil angezeigt.</p>
        <a class="thumbnail" href="#" data-image-id="" data-toggle="modal" data-title="" data-caption="" data-image="/themes/ixtheo2/images/content_img/en/citation_styles_eng.png" data-target="#image-gallery">
            <img class="img-responsive" src="/themes/ixtheo2/images/content_img/en/citation_styles_eng.png" alt="<?=$this->transEscAttr('symbolic_image_table17');?>">
        </a>
        <h1 class="cw-h5" id="exportieren">Exportieren</h1>
        <p>Alternativ können Sie Suchergebnisse auch direkt aus IxTheo in Ihr Literaturverwaltungsprogramm exportieren.</p>
        <p>Hierzu klicken Sie in der Liste der Suchergebnisse alle Resultate an, die Sie exportieren möchten (Haken im Kasten links neben dem Titel). Dann klicken Sie auf die Option „Export“ oberhalb der Titelliste.</p>
        <a class="thumbnail" href="#" data-image-id="" data-toggle="modal" data-title="" data-caption="" data-image="/themes/ixtheo2/images/content_img/en/export_results_eng.png" data-target="#image-gallery">
            <img class="img-responsive" src="/themes/ixtheo2/images/content_img/en/export_results_eng.png" alt="<?=$this->transEscAttr('symbolic_image_table18');?>">
        </a>
        <p>Sie haben die Wahl zwischen den Formaten EndNote, RefWorks und RIS (für Citavi, Zotero etc.)</p>
        <a class="thumbnail" href="#" data-image-id="" data-toggle="modal" data-title="" data-caption="" data-image="/themes/ixtheo2/images/content_img/en/export_format_eng.png" data-target="#image-gallery">
            <img class="img-responsive" src="/themes/ixtheo2/images/content_img/en/export_format_eng.png" alt="<?=$this->transEscAttr('symbolic_image_table19');?>">
        </a>
      </div>
    </div>
  </div>
</div>
