<div class="container cw-py-5">
  <div class="cw-row">
    <div class="cw-col-lg-8">
      <div class="cw-text-block">
        <h1 class="cw-h1">Actions in a Query Result</h1>

        <h1 class="cw-h5" id="zitieren">Citation</h1>
        <p>If you would like to quote a piece of literature (e.g. book, article, etc.), you can apply various citation styles.</p>
        <p>Display the full record of the piece (by clicking on its title in the list of search results) and click on the button labelled “Cite this” on the top corner of the record.</p>
        <a class="thumbnail" href="#" data-image-id="" data-toggle="modal" data-title="" data-caption="" data-image="<?=$this->imageLink('content_img/en/cite_this_eng.png')?>" data-target="#image-gallery">
            <img class="img-responsive" src="<?=$this->imageLink('content_img/en/cite_this_eng.png')?>" alt="<?=$this->transEscAttr('symbolic_image_table16');?>">
        </a>
        <p>The bibliographic information is then displayed in the following citation styles: APA, Chicago and MLA.</p>
        <a class="thumbnail" href="#" data-image-id="" data-toggle="modal" data-title="" data-caption="" data-image="<?=$this->imageLink('content_img/en/citation_styles_eng.png')?>" data-target="#image-gallery">
            <img class="img-responsive" src="<?=$this->imageLink('content_img/en/citation_styles_eng.png')?>" alt="<?=$this->transEscAttr('symbolic_image_table17');?>">
        </a>
        <h1 class="cw-h5" id="exportieren">Export</h1>
        <p>You can also export your search query results directly from IxTheo into your own reference management software.</p>
        <p>To do this, select in the results list all items which you would like to export (by ticking the box on the left-hand side next to the title). Then click on the “Export” button above the list.</p>
        <a class="thumbnail" href="#" data-image-id="" data-toggle="modal" data-title="" data-caption="" data-image="<?=$this->imageLink('content_img/en/export_results_eng.png')?>" data-target="#image-gallery">
            <img class="img-responsive" src="<?=$this->imageLink('content_img/en/export_results_eng.png')?>" alt="<?=$this->transEscAttr('symbolic_image_table18');?>">
        </a>
        <p>You can choose between the following formats: EndNote, RefWorks and RIS (for Citavi, Zotero, etc.)</p>
        <a class="thumbnail" href="#" data-image-id="" data-toggle="modal" data-title="" data-caption="" data-image="<?=$this->imageLink('content_img/en/export_format_eng.png')?>" data-target="#image-gallery">
            <img class="img-responsive" src="<?=$this->imageLink('content_img/en/export_format_eng.png')?>" alt="<?=$this->transEscAttr('symbolic_image_table19');?>">
        </a>
      </div>
    </div>
  </div>
</div>
