<div class="cw-row">
    <div class="cw-col-lg-12 cw-ml-lg-4">
        <div class="cw-text-block"><br>
            <h1 class="cw-h1">Alerting</h1>

            <h3><b>Meine Alerts (Neuerscheinungen)</b></h3>

            <p>Die Alerting-Funktion bietet Ihnen die Möglichkeit, sich automatisch über neu erschienene Aufsätze / Bände aus bestimmten Zeitschriften oder Reihen informieren zu lassen. Sie können frei entscheiden, in welchen Fällen Sie eine Benachrichtigung wünschen. </p>
            <p>Um Benachrichtigungen für eine Zeitschrift oder Reihe zu erhalten, müssen Sie die Gesamtaufnahme der Zeitschrift oder Reihe „abonnieren“. Rufen Sie dazu den Eintrag für die Zeitschrift oder Reihe insgesamt auf und klicken Sie rechts auf das blaue Symbol „Glocke“. </p>
            <p style="text-align: center; padding: 15px 0;"><img src="<?=$this->imageLink('content_img/alerting_img_1.png');?>" width="600" /></p>
            <p>Falls Sie nicht eingeloggt sind, werden Sie aufgefordert, sich in Ihr Benutzerkonto einzuloggen. Im Benutzerkonto können Sie das „Abonnement“ verwalten (und z.B. auch Benachrichtigungen für eine Reihe wieder abbestellen).</p>
            <p>Beispiel 1 (Zeitschrift): Um über neu erschienene Beiträge in der Theologischen Quartalschrift informiert zu werden, geben Sie in den Suchschlitz den Reihentitel „Theologische Quartalschrift“ oder die Abkürzung „ThQ“ ein. Sie können alternativ auch gezielt nach einer ISSN suchen. Geben Sie dafür im Suchschlitz issn:ISSN-Nummer ein (Beispiel: „issn:0342-1430“ findet die Theologische Quartalschrift. Achtung: Die Eingabe darf kein Leerzeichen enthalten!)</p>
            <p>Wählen Sie im Anschluss rechts unter „Medienart“ die Facette „Zeitschrift“ aus. Sie erhalten 2 Treffer: zum einen die gedruckte, zum anderen die elektronische Ausgabe der ThQ. Meist ist es – wie in diesem Fall – sinnvoll, beide Einträge zu abonnieren. Wenn Sie bei beiden auf das Symbol „Glocke“ rechts neben dem Titel klicken, erhalten Sie Nachrichten über alle neuen Aufsätze der Zeitschrift.</p>
            <p><Screenshot></p>
            <p>Beispiel 2 (Reihe): Um die Reihe Wissenschaftliche Untersuchungen zum Neuen Testament zu abonnieren, geben Sie in den Suchschlitz „Wissenschaftliche Untersuchungen zum Neuen Testament“ oder „WUNT“ ein. Sie erhalten mehrere Treffer. In der rechten Spalte unter „Medienart“ können Sie diese auf Einträge für „Schriftenreihe/Zeitschrift“ einschränken und dann die gewünschte Reihe auswählen. Abonnieren Sie diese durch Klick auf das Symbol „Glocke“.</p>
            <p><Screenshot></p>
            <p>Für die Alerting-Funktion stehen die zahlreichen Zeitschriften und Reihen zur Verfügung, die im IxTheo regelmäßig und systematisch ausgewertet werden. Andere Reihen und Zeitschriften werden im IxTheo auch genannt, können aber nicht im Rahmen des Alerting abonniert werden. Ob ein Titel abonniert werden kann, erkennen Sie daran, ob die oben erwähnten Symbole angezeigt werden.</p>
            <p>Wir sind bemüht, die Auswahl der Zeitschriften und Reihen zukünftig bequemer für Sie zu gestalten. Angedacht ist, dass Sie Zeitschriften, die im IxTheo ausgewertet werden, auch blockweise nach theologischen Disziplinen oder Themen geordnet abonnieren können.</p>

            <h3><b>Meine Feeds</b></h3>  
            
            <p>Unter „Meine Feeds“ wird Ihnen eine Liste theologischer und religionswissenschaftlicher Blogs und Podcasts angezeigt, die im IxTheo ausgewertet werden. Um über neue Beiträge eines bestimmten Portals informiert zu werden, klicken Sie auf den Schieber rechts unter „Abonnieren“.</p>
            <p>Wenn Sie zusätzlich die Option „Möchten Sie eine E-Mail-Benachrichtigung über neue Blogeinträge erhalten?“ auswählen, erhalten Sie bei neuen Beiträgen eine Nachricht per E-Mail.</p>
            <p>Unter der Rubrik „Persönlichen RSS-Feed anzeigen“ finden Sie eine Liste aller aktuellen Beiträge aus den Foren, die Sie abonniert haben. Wenn Sie auf dieser Seite den Link „Hier finden Sie Ihren persönlichen RSS Feed“ kopieren, können Sie auch die RSS-Funktion in Ihrem Internet-Browser nutzen, um sich über neue Beiträge aus allen abonnierten Foren informieren zu lassen.</p>
            <p><a href="#" style="color: green;">Weitere Möglichkeiten</a></p>
            <p>Das Benutzerkonto bietet noch weitere Möglichkeiten, Titel abzuspeichern oder sich über neue Titel informieren zu lassen. Siehe dazu <a href="<?=$this->url('myresearch-home')?>">„IxTheo Account“</a>.</p>

         </div>
    </div>
</div>




<?php /*
<section class="cw-hero cw-py-5 cw-py-lg-7">
  <div class="container position-relative">
    <h1 class="cw-hero-heading cw-mb-5">Alerting</h1>
    <div class="row">
      <div class="col-xl-8 mx-auto"><p class="lead mb-0">As am hastily invited settled at limited civilly fortune me. Really spring in extent an by. Judge but built party world. Of so am he remember although required. Bachelor unpacked be advanced at. Confined in declared marianne is vicinity. </p></div>
    </div>
  </div>
</section>

<section class="cw-py-6">
  <div class="container">
    <div class="cw-py-4">
      <h2 class="cw-h2 cw-mb-5 cw-text-primary">Shopping</h2>
      <div class="cw-row">
        <div class="cw-col-md-6">
          <h5 class="cw-h5">What shipping method does Sell use?</h5>
          <p class="text-muted cw-mb-4">The bedding was hardly able to cover it and seemed ready to slide off any moment. His many legs, pitifully thin compared with the size of the rest of him, waved about helplessly as he looked. "What's happened to me?" he thought. It wasn't a dream.</p>
          <h5 class="cw-h5">What countries do you to?</h5>
          <p class="text-muted cw-mb-4">His room, a proper human room although a little too small, lay peacefully between its four familiar walls. A collection of textile samples lay spread out on the table.</p>
        </div>
        <div class="cw-col-md-6">
          <h5 class="cw-h5">One of my items is missing</h5>
          <p class="text-muted cw-mb-4">Samsa was a travelling salesman - and above it there hung a picture that he had recently cut out of an illustrated magazine and housed in a nice, gilded frame.</p>
          <h5 class="cw-h5">Remote areas - delivery</h5>
          <p class="text-muted cw-mb-4">He must have tried it a hundred times, shut his eyes so that he wouldn't have to look at the floundering legs, and only stopped when he began to feel a mild, dull pain there that he had never felt before.</p>
        </div>
      </div>
    </div>
    <hr class="cw-hr">
    <div class="cw-py-4">
      <h2 class="cw-h2 cw-mb-5 cw-text-primary">Payment</h2>
      <div class="cw-row">
        <div class="cw-col-md-6">
          <h5 class="cw-h5">Can I pay COD - cash on delivery?</h5>
          <p class="text-muted cw-mb-4">One morning, when Gregor Samsa woke from troubled dreams, he found himself transformed in his bed into a horrible vermin. He lay on his armour-like back, and if he lifted his head a little he could see his brown belly, slightly domed and divided by arches into stiff sections</p>
          <h5 class="cw-h5">Payment methods accepted</h5>
          <p class="text-muted cw-mb-4">One morning, when Gregor Samsa woke from troubled dreams, he found himself transformed in his bed into a horrible vermin. He lay on his armour-like back, and if he lifted his head a little he could see his brown belly, slightly domed and divided by arches into stiff sections</p>
        </div>
        <div class="cw-col-md-6">
          <h5 class="cw-h5">What is Paypal?</h5>
          <p class="text-muted cw-mb-4">The bedding was hardly able to cover it and seemed ready to slide off any moment. His many legs, pitifully thin compared with the size of the rest of him, waved about helplessly as he looked. "What's happened to me?" he thought. It wasn't a dream.</p>
          <h5 class="cw-h5">How do the conversion rates work</h5>
          <p class="text-muted cw-mb-4">His room, a proper human room although a little too small, lay peacefully between its four familiar walls. A collection of textile samples lay spread out on the table.</p>
        </div>
      </div>
    </div>
    <hr class="cw-hr">
    <div class="cw-py-4">
      <h2 class="cw-h2 cw-mb-5 cw-text-primary">Warranty and return</h2>
      <div class="cw-row">
        <div class="cw-col-md-6">
          <h5 class="cw-h5">My product has a problem what should I do?</h5>
          <p class="text-muted cw-mb-4">Samsa was a travelling salesman - and above it there hung a picture that he had recently cut out of an illustrated magazine and housed in a nice, gilded frame.</p>
          <h5 class="cw-h5">What if the product is broken?</h5>
          <p class="text-muted cw-mb-4">He must have tried it a hundred times, shut his eyes so that he wouldn't have to look at the floundering legs, and only stopped when he began to feel a mild, dull pain there that he had never felt before.</p>
        </div>
        <div class="cw-col-md-6">
          <h5 class="cw-h5">Why should I buy insurance at the checkout?</h5>
          <p class="text-muted cw-mb-4">One morning, when Gregor Samsa woke from troubled dreams, he found himself transformed in his bed into a horrible vermin. He lay on his armour-like back, and if he lifted his head a little he could see his brown belly, slightly domed and divided by arches into stiff sections</p>
        </div>
      </div>
    </div>
  </div>
</section>
*/?>