<div class="cw-row">
    <div class="cw-col-lg-12 cw-ml-lg-4">
        <div class="cw-text-block"><br />
            <h1 class="cw-h1">Alerting</h1>

            <h3><b>My Alerts (New Publications)</b></h3>

            <p>The alerting function allows you to get automatic updates on recently published articles or volumes from certain journals. You can decide in which cases you would like to receive a notification.</p>
            <p>If you would like to receive a notification whenever a new article is published, you need to sign up for the respective journal. First search for the journal, then click on the "bell" symbol displayed in the catalog entry.</p>

            <p style="text-align: center; padding: 15px 0;"><img src="<?=$this->imageLink('content_img/alerting_img_1.png');?>" width="600" alt="<?=$this->transEscAttr('symbolic_image_table20');?>." /></p>

            <p>If you are not already logged in, you will be asked to log into your user account. In your user account, you can manage the list of publications for which you signed up (and e.g. cancel one of them if you don’t want notifications anymore for a given journal).</p>
            <p>Example: In order to receive a notification whenever a new article of the journal "Theologische Quartalschrift" appears, enter the name of the journal or its abbreviation "ThQ" in the search field. You can also search for an ISSN by selecting the option "ISBN/ISSN" on the right-hand side of the search field (e.g. if you enter the ISSN "0342-1430" and select this option, you will find the Theologische Quartalschrift).</p>
            <p>Afterwards, select the "Journal" facet under the heading "Format" on the right-hand side. You will then see a list of two entries: The first one is the print version, the second one the electronic version of the journal. It is usually best to sign up to both versions. If you click on the "bell" symbol in both entries, you will receive a notification per e-mail whenever there is a new article in this journal.</p>

            <p style="text-align: center; padding: 15px 0;"><img src="<?=$this->imageLink('content_img/alerting_img_2.png');?>" width="600" alt="<?=$this->transEscAttr('symbolic_image_table21');?>" /></p>

            <p>This function is available for a great number of journals which are systematically and regularly catalogued in IxTheo. However, it is not provided for some journals and series which can be found in IxTheo; in such cases, no "bell" symbol is displayed.</p>
            <p>We are working to make the selection of journals for alerting easier. We hope to allow the possibility of selecting blocks of journals grouped according to theological fields or themes in the future.</p>

            <h3 style="margin-top: 35px;"><b>My Newsfeeds</b></h3>

            <p>Under "My newsfeeds", a list of blogs and podcasts in theology and in religious studies which are processed in IxTheo is shown. To receive notifications of new contributions on a given portal, click on the slider to the right of the entry under "subscribe".</p>
            <p>If you select the option "Would you like to receive a notification of new entries via e-mail?", an e-mail will be sent to you whenever a new post or episode from one of the blogs and podcasts you selected is available.</p>
            <p>In the section “Show personal RSS feed”, you can find a list of all current contributions from the forums to which you subscribe. If you copy the link labelled “Get your raw RSS feed here” from that page, you can also use the RSS-function in your browser to get information on the new posts from all the forums to which you subscribe.</p>

			<h3 style="margin-top: 35px;"><b>Further Options</b></h3>
            <p>You can also use your user account to save your search results or get information on new publications. See  <a href="<?=$this->url('content-page', ['page' => 'IxtheoAccount']) ?>">IxTheo Account</a>.</p>
        </div>
    </div>
</div>
