<div class="container cw-py-5">
    <div class="cw-row">
        <div class="cw-col-lg-8">
            <div class="cw-text-block">
                <h1 class="cw-h1">Alerting</h1>

                <h3><b>Meine Alerts (Neuerscheinungen)</b></h3>

                <p>Die Alerting-Funktion bietet Ihnen die Möglichkeit, sich automatisch über neu erschienene Aufsätze / Bände aus bestimmten Zeitschriften oder Reihen informieren zu lassen. Sie können frei entscheiden, in welchen Fällen Sie eine Benachrichtigung wünschen. </p>
                <p>Um Benachrichtigungen für eine Zeitschrift oder Reihe zu erhalten, müssen Sie die Gesamtaufnahme der Zeitschrift oder Reihe „abonnieren“. Rufen Sie dazu den Eintrag für die Zeitschrift oder Reihe insgesamt auf und klicken Sie rechts auf das blaue Symbol „Glocke“. </p>
                <p style="text-align: center; padding: 15px 0;"><img src="<?=$this->imageLink('content_img/alerting_img_1.png');?>" width="600" /></p>
                <p>Falls Sie nicht eingeloggt sind, werden Sie aufgefordert, sich in Ihr Benutzerkonto einzuloggen. Im Benutzerkonto können Sie das „Abonnement“ verwalten (und z.B. auch Benachrichtigungen für eine Reihe wieder abbestellen).</p>
                <p>Beispiel 1 (Zeitschrift): Um über neu erschienene Beiträge in der Theologischen Quartalschrift informiert zu werden, geben Sie in den Suchschlitz den Reihentitel „Theologische Quartalschrift“ oder die Abkürzung „ThQ“ ein. Sie können alternativ auch gezielt nach einer ISSN suchen. Geben Sie dafür im Suchschlitz issn:ISSN-Nummer ein (Beispiel: „issn:0342-1430“ findet die Theologische Quartalschrift. Achtung: Die Eingabe darf kein Leerzeichen enthalten!)</p>
                <p>Wählen Sie im Anschluss rechts unter „Medienart“ die Facette „Zeitschrift“ aus. Sie erhalten 2 Treffer: zum einen die gedruckte, zum anderen die elektronische Ausgabe der ThQ. Meist ist es – wie in diesem Fall – sinnvoll, beide Einträge zu abonnieren. Wenn Sie bei beiden auf das Symbol „Glocke“ rechts neben dem Titel klicken, erhalten Sie Nachrichten über alle neuen Aufsätze der Zeitschrift.</p>
                <p>"Screenshot"</p>
                <p>Beispiel 2 (Reihe): Um die Reihe Wissenschaftliche Untersuchungen zum Neuen Testament zu abonnieren, geben Sie in den Suchschlitz „Wissenschaftliche Untersuchungen zum Neuen Testament“ oder „WUNT“ ein. Sie erhalten mehrere Treffer. In der rechten Spalte unter „Medienart“ können Sie diese auf Einträge für „Schriftenreihe/Zeitschrift“ einschränken und dann die gewünschte Reihe auswählen. Abonnieren Sie diese durch Klick auf das Symbol „Glocke“.</p>
                <p>"Screenshot"</p>
                <p>Für die Alerting-Funktion stehen die zahlreichen Zeitschriften und Reihen zur Verfügung, die im IxTheo regelmäßig und systematisch ausgewertet werden. Andere Reihen und Zeitschriften werden im IxTheo auch genannt, können aber nicht im Rahmen des Alerting abonniert werden. Ob ein Titel abonniert werden kann, erkennen Sie daran, ob die oben erwähnten Symbole angezeigt werden.</p>
                <p>Wir sind bemüht, die Auswahl der Zeitschriften und Reihen zukünftig bequemer für Sie zu gestalten. Angedacht ist, dass Sie Zeitschriften, die im IxTheo ausgewertet werden, auch blockweise nach theologischen Disziplinen oder Themen geordnet abonnieren können.</p>
                
                <h3 style="margin-top: 35px;"><b>Meine Feeds</b></h3>  

                <p>Unter „Meine Feeds“ wird Ihnen eine Liste theologischer und religionswissenschaftlicher Blogs und Podcasts angezeigt, die im IxTheo ausgewertet werden. Um über neue Beiträge eines bestimmten Portals informiert zu werden, klicken Sie auf den Schieber rechts unter „Abonnieren“.</p>
                <p>Wenn Sie zusätzlich die Option „Möchten Sie eine E-Mail-Benachrichtigung über neue Blogeinträge erhalten?“ auswählen, erhalten Sie bei neuen Beiträgen eine Nachricht per E-Mail.</p>
                <p>Unter der Rubrik „Persönlichen RSS-Feed anzeigen“ finden Sie eine Liste aller aktuellen Beiträge aus den Foren, die Sie abonniert haben. Wenn Sie auf dieser Seite den Link „Hier finden Sie Ihren persönlichen RSS Feed“ kopieren, können Sie auch die RSS-Funktion in Ihrem Internet-Browser nutzen, um sich über neue Beiträge aus allen abonnierten Foren informieren zu lassen.</p>
                <p><a href="#">Weitere Möglichkeiten</a></p>
                <p>Das Benutzerkonto bietet noch weitere Möglichkeiten, Titel abzuspeichern oder sich über neue Titel informieren zu lassen. Siehe dazu <a href="<?=$this->url('myresearch-home')?>">„IxTheo Account“</a>.</p>
            </div>
        </div>
    </div>
</div>
