<div class="container cw-py-5">
  <div class="cw-row">
    <div class="cw-col-lg-8">
      <div class="cw-text-block">
        <h1 class="cw-h1">Alle Services</h1>
        <ul>
          <li><a href="<?=$this->url('content-page', ['page' => 'Alerting']) ?>">Alerting</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'Beratung']) ?>">Beratung</a></li>
          <li>Digitalisierung
            <ul>
              <li><a href="<?=$this->url('content-page', ['page' => 'TheologyDigital']) ?>">DigiTheo</a></li>
              <li><a href="<?=$this->url('content-page', ['page' => 'OpenText']) ?>">Zweitveröffentlichung</a></li>
            </ul>
          </li>
          <li><a href="<?=$this->url('content-page', ['page' => 'Fernleihe']) ?>">Fernleihe</a></li>
          <li>IxTheo <a href="<?=$this->url('content-page', ['page' => 'IxtheoAccount']) ?>">Account</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'LexiconSearch']) ?>">Lexikonrecherche</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'NutzerinnengesteuerteErwerbung']) ?>">Neuanschaffungen auf Nutzer*innenwunsch</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'OpenAccess']) ?>">Open Access</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'AuthorityPages']) ?>">Personenseiten</a></li>
          <li>
            Suchen und Browsen
            <ul>
              <li><a href="<?=$this->url('content-page', ['page' => 'Discover']) ?>#more_post-1">Bibelstellensuche</a></li>
              <li><a href="<?=$this->url('content-page', ['page' => 'Discover']) ?>#browsing">Browsen</a></li>
              <li><a href="<?=$this->url('content-page', ['page' => 'Discover']) ?>#more_post-2">CIC-Suche</a></li>
              <li><a href="<?=$this->url('content-page', ['page' => 'Discover']) ?>#klassifikation">Inhaltliche Suche</a></li>
              <li><a href="<?=$this->url('content-page', ['page' => 'FullTextSearch']) ?>">Volltextsuche</a></li>
              <li><a href="<?=$this->url('content-page', ['page' => 'Discover']) ?>#more_post-3">Zeitraumsuche</a></li>
            </ul>
          </li>
          <li>
            <a target="_blank" href="https://ixtheo.de/docs/TAD.pdf">Tübinger Aufsatzdienst (TAD)</a>
            <p>Lokaler Aufsatzlieferdienst (nur für Wissenschaftler*innen der Universität Tübingen)</p>
          </li>
        </ul>
        <p>Haben Sie nicht gefunden, was Sie suchen? Weitere Verweise finden Sie auch unter <a href="<?=$this->url('content-page', ['page' => 'a_z']) ?>">IxTheo A-Z</a> oder fragen Sie uns (<a href="<?=$this->url('content-page', ['page' => 'ContactPersons']) ?>">Ansprechpartner*innen</a>).</p>
      </div>
    </div>
  </div>
</div>