<div class="container cw-py-5">
  <div class="cw-row">
    <div class="cw-col-lg-8">
      <div class="cw-text-block">
        <h1 class="cw-h1">Alle Services</h1>
        <ul>
          <li><a href="<?=$this->url('content-page', ['page' => 'Beratung']) ?>">Advisory Services</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'Alerting']) ?>">Alerting</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'NutzerinnengesteuerteErwerbung']) ?>">Book Acquisition Recommendation</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'LexiconSearch']) ?>">Dictionary Search</a></li>
          <li>Digitization
            <ul>
              <li><a href="<?=$this->url('content-page', ['page' => 'TheologyDigital']) ?>">DigiTheo</a></li>
              <li><a href="<?=$this->url('content-page', ['page' => 'OpenText']) ?>">Republication</a></li>
            </ul>
          </li>
          <li><a href="<?=$this->url('content-page', ['page' => 'Fernleihe']) ?>">Interlibrary Loan</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'IxtheoAccount']) ?>">IxTheo Account</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'Ubersicht']) ?>">Open Access</a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'AuthorityPages']) ?>">Person Information Pages</a></li>
          <li>
            Search and Browse
            <ul>
              <li><a href="<?=$this->url('content-page', ['page' => 'Discover']) ?>#more_post-1">Searching for Bible Passages</a></li>
              <li><a href="<?=$this->url('content-page', ['page' => 'Discover']) ?>#browsing">Browsing</a></li>
              <li><a href="<?=$this->url('content-page', ['page' => 'Discover']) ?>#more_post-2">Searching for Passages in Church Law</a></li>
              <li><a href="<?=$this->url('content-page', ['page' => 'Discover']) ?>#klassifikation">Searching by Subject Classification</a></li>
              <li><a href="<?=$this->url('content-page', ['page' => 'FullTextSearch']) ?>">Full-Text Search</a></li>
              <li><a href="<?=$this->url('content-page', ['page' => 'Discover']) ?>#more_post-3">Searching for Time Ranges</a></li>
            </ul>
          </li>
          <li>
            <a target="_blank" href="https://ixtheo.de/docs/TAD.pdf">Tübinger Aufsatzdienst (TAD)</a>
            <p>A local service to deliver journal articles (only for academics at the University of Tübingen).</p>
          </li>
        </ul>
        <p>If you didn’t find what you were looking for, please consult the list <a href="<?=$this->url('content-page', ['page' => 'A_Z']) ?>">IxTheo A-Z</a> or ask us (<a href="<?=$this->url('content-page', ['page' => 'ContactPersons']) ?>">Contact</a>).</p>
      </div>
    </div>
  </div>
</div>
