<div class="container cw-py-5">
  <div class="cw-row">
    <div class="cw-col-lg-8">
      <div class="cw-text-block">
        <h1 class="cw-h1">Archivierung von Forschungsberichten</h1>

        <p>Abschlussberichte zu Forschungsprojekten können über den Fachinformationsdienst (FID) Theologie einfach und schnell archiviert und über den Index Theologicus (IxTheo) zugänglich gemacht werden. </p>

        <p>Viele Forschungsförderinstitutionen sehen inzwischen vor, dass Abschlussberichte von Projekten im Open Access zur Verfügung gestellt werden. Auch für andere Wissenschaftler*innen, die im gleichen Feld arbeiten, ist dies sehr hilfreich.</p>

        <p>So rät die Deutsche Forschungsgemeinschaft (DFG), Abschlussberichte in Repositorien einzustellen und empfiehlt für Berichte aus dem Fach Theologie das Fachrepositorium des FID (<a target="_blank" href="https://www.dfg.de/en/research-funding/proposal-funding-process/final-reports/publication">Website der DFG</a>). Dort erhält jede Publikation einen Permalink (PID), der im Anschluss im elan-Portal der DFG gemeldet werden kann.</p>

        <p>Vorteile einer Publikation auf dem Fachrepositorium Theologie:</p>
        <ul>
            <li>Verzeichnung im Index Theologicus</li>
            <li>weltweite Auffindbarkeit, auch bei thematischen Suchen</li>
            <li>digitale Langzeitarchivierung durch die Universitätsbibliothek Tübingen</li>
            <li>Open Access ohne Login oder Zugriffsbeschränkungen</li>
            <li>Permalink (doi)</li>
        </ul>
        <p>Wenn Sie Ihren Forschungsbericht auf dem Fachrepositorium publizieren möchten, wenden Sie sich bitte per E-Mail an uns: <a href="mailto:theologie@ub.uni-tuebingen.de">theologie@ub.uni-tuebingen.de</a> </p>
        <p>Wir beraten Sie, verzeichnen den Bericht im IxTheo und laden die Datei für Sie hoch. Ggf. können wir auch Forschungsberichte im IxTheo verzeichnen, die auf dem Repositorium Ihrer Universität oder Forschungsinstitution archiviert wurden. Bitte sprechen Sie uns an.</p>
      </div>
    </div>
  </div>
</div>
