<div class="container cw-py-5">
  <div class="cw-row">
    <div class="cw-col-lg-8">
      <div class="cw-text-block">
        <h1 class="cw-h1">Archiving of Research Reports</h1>

        <p>Final reports on research projects can be archived through the Fachinformationsdienst Theologie (Specialized Information Service in Theology) and made available through the Index Theologicus (IxTheo).</p>
        <p>Many funding institutions require that final research reports be made available in Open Access. This is also very useful for other researchers working in the same academic field.</p>
        <p>For instance, the Deutsche Forschungsgemeinschaft (DFG, German Research Foundation) ( advises researchers to make their reports available  in repositories and recommends the FID Theologie’s repository for reports on theological projects  (<a target="_blank" href="https://www.dfg.de/en/research-funding/proposal-funding-process/final-reports/publication">Website der DFG</a>). Every publication on our repository gets a permalink (PID) which can be submitted to the elan-portal of the DFG.</p>
        <p>Advantages of publishing reports on the FID Theologie’s repository:</p>
        <ul>
            <li>Reports are listed in the Index Theologicus</li>
            <li>International visibility, also in thematic searches</li>
            <li>Long-term archiving through the University Library of Tübingen</li>
            <li>Open Access without any access restrictions</li>
            <li>Permalink (doi)</li>
        </ul>
        <p>If you would like to publish your research report in our repository, please contact us at the following address: <a href="mailto:theologie@ub.uni-tuebingen.de">theologie@ub.uni-tuebingen.de</a>. We will advise you, list your report in IxTheo and upload the file for you. We can also list research reports in IxTheo which are archived on the repository of your university or your research institution. Please contact us.</p>
        <p>We will advise you, list your report in IxTheo and upload the file for you. We can also list research reports in IxTheo which are archived on the repository of your university or your research institution. Please contact us.</p>
      </div>
    </div>
  </div>
</div>
