<div class="cw-row">
    <div class="cw-col-lg-12">
        <div class="cw-text-block"><br>
            <span id="ixtheo_content"></span>
            <h1 class="cw-h1">Aufgabenfelder</h1>
            <div role="tablist" class="digiTabs">
                <br />
                <div class="cw-card cw-mb-3">
                    <div>
                        <!-- Nav tabs -->
                        <ul class="nav nav-tabs nav-justified" role="tablist">
                            <li role="presentation" class="active"><a href="#tab1" aria-controls="" role="tab" data-toggle="tab">Aufgabenfelder 2024-2026</a></li>
                            <li role="presentation"><a href="#tab2" aria-controls="" role="tab" data-toggle="tab">Aufgabenfelder 2021–2023</a></li>
                            <li role="presentation"><a href="#tab3" aria-controls="" role="tab" data-toggle="tab">Aufgabenfelder 2018–2020</a></li>
                            <li role="presentation"><a href="#tab4" aria-controls="" role="tab" data-toggle="tab">Aufgabenfelder 2015–2017</a></li>
                        </ul>

                        <!-- Tab panes -->
                        <div class="tab-content">
                            <div role="tabpanel" class="tab-pane active" id="tab1">
                                <h5><b>Inhalte:</b></h5>
                                <ul>
                                    <li>laufende Auswertung von über 1.200 internationalen Zeitschriften, zahlreichen Reihen sowie der deutschen, englischen und französischen Nationalbibliographie </li>
                                    <li>Erweiterung des Portfolios ausgewerteter Zeitschriften</li>
                                    <li>Fortsetzung der retrospektiven Erschließung von Aufsätzen aus Zeitschriften und Sammelwerken</li>
                                    <li>Integration weiterer Bibliographien und Spezialsammlungen (BiBIL, Bibliotheca Augustiniana, Finding Augustine, Maurits-Sabbe-Bibliothek Leuven)</li>
                                    <li>Systematische Verzeichnung von digitalen Editionen </li>
                                    <li>Nachweis von nachträglich in Open Access gestellten wissenschaftlichen Reihen und weiteren auf Repositorien nachgewiesenen Publikationen</li>
                                    <li>Nachweis von Forschungsdaten aus allen theologischen Fachgebieten</li>
                                    <li>Ausbau der Sacherschließung zusammen mit weiteren Kooperationspartnern (Augustinus-Bibliographie, BiBIL)</li>
                                    <li>Automatisierte Auszeichnung eines großen Bestands an Datensätzen mit der IxTheo-Notation</li>
                                </ul>

                                <h5><b>Features:</b></h5>
                                <ul>
                                    <li>Einführung von Polnisch als weiterer Recherchesprache im IxTheo</li>
                                    <li>Einführung eines Formulars zur Meldung von nicht im IxTheo erfassten Publikationen</li>
                                    <li>Einbindung der Option, direkt in IxTheo eine Fernleihe auszulösen</li>
                                    <li>Einbindung von WorldCat in die Verfügbarkeitsanzeige</li>
                                    <li>Ausweitung der Volltextsuche auf weitere Verlage </li>
                                </ul>

                                <h5><b>Dienste:</b></h5>
                                <ul>
                                    <li>IxTheo Open Journals: Gründung neuer und Aufnahme bestehender Zeitschriften in Open Access (Zeitschriften-Publikationssystem OJS)</li>
                                    <li>IxTheo Open Text: Weiterführung des Zweitveröffentlichungsservice für angemeldete deutschsprachige Wissenschaftler*innen </li>
                                    <li>Self Archiving Service: Möglichkeit für Wissenschaftler*innen, eigene Publikationen selbst in Open Access zweitzuveröffentlichen. Dieser Service steht international zur Verfügung.</li>
                                    <li>Digitalisierung on Demand: Digitalisierung einzelner urheberrechtsfreier Bände auf Nutzer*innenwunsch in Kooperation mit dem FID Geschichtswissenschaft</li>
                                    <li>Forschungsdatenmanagement: Beratung für Wissenschaftler*innen aus allen theologischen Fächern zu Erfassung, Langzeitarchivierung und Nachweis von Forschungsdaten, ggf. Verweis an spezialisierte Repositorien und Ansprechpartner</li>
                                </ul>
                            </div>

                            <div role="tabpanel" class="tab-pane" id="tab2">
                                <h5><b>Inhalte:</b></h5>
                                <ul>
                                    <li>Erweiterung des Portfolios ausgewerteter Zeitschriften </li>
                                    <li>Ausweitung der retrospektiven Erschließung</li>
                                    <li>Auswertung der Nationalbibliographien aus England, Frankreich und weiteren Ländern</li>
                                    <li>Bereitstellung von Literaturverzeichnissen bei Monographien</li>
                                    <li>Integration wichtiger theologischer Lexika </li>
                                    <li>Nachweis theologisch relevanter Alter Drucke aus dem 16.-18. Jahrhundert (VD16, VD17, VD18)</li>
                                    <li>Verzeichnung zahlreicher Sammlungen aus der Datenbank Princeton Theological Commons</li>
                                    <li>Einbeziehung wichtiger Bestände zur evangelischen Kirchengeschichte durch Kooperation mit folgenden Institutionen: 
                                        <ul>
                                            <li>Forschungsbibliothek Gotha (Forschungs- und Studienstätte für die Kulturgeschichte des Protestantismus in der Frühen Neuzeit)</li>
                                            <li>Johannes a Lasco Bibliothek, Emden</li>
                                            <li>Franckesche Stiftungen zu Halle, Studienzentrum August Hermann Francke, Halle</li>
                                            <li>Reformationsgeschichtliche Forschungsbibliothek Wittenberg</li>
                                        </ul>
                                    </li>
                                </ul>
                                
                                <h5><b>Features:</b></h5>
                                <ul>
                                    <li>Einführung von Personenseiten zu theologischen Autorinnen und Autoren (Publikationen, Links, weiterführende Informationen)</li>
                                    <li>Ausweitung der Volltextsuche auf weitere Verlage</li>
                                    <li>Einführung eines Feed-Aggregators mit Alerting-Funktion</li>
                                </ul>
                                <h5><b>Dienste:</b></h5>
                                <ul>
                                    <li>IxTheo Open Journals: Gründung neuer und Aufnahme bestehender Zeitschriften in Open Access (Zeitschriften-Publikationssystem OJS)</li>
                                    <li>IxTheo Self-Archiving: Upload und Open Access-Bereitstellung von Zweitveröffentlichungen wissenschaftlicher Publikationen durch die Autor*innen </li>
                                    <li>IxTheo Open Text: Zweitveröffentlichungsservice für Wissenschaftler*innen im Rahmen des Urheberrechts</li>
                                </ul>
                            </div>

                            <div role="tabpanel" class="tab-pane" id="tab3">
                                <h5><b>Inhalte:</b></h5>
                                <ul>
                                    <li>Erweiterung des Spektrums ausgewerteter Zeitschriften (auch unter Einbeziehung von Zeitschriften, deren Erscheinen eingestellt wurde)</li>
                                    <li>Einbezug ausgewählter Rezensionsorgane</li>
                                    <li>Umfassender, systematischer Nachweis von Monographien</li>
                                    <li>Nachweis aller relevanten Datenbanken</li>
                                    <li>Integration von frei zugänglichen elektronischen Zeitschriften und digitalen Inhalten</li>
                                    <li>Nachweis von Nachlässen von Theolog*innen und weiteren Archivmaterialien </li>
                                </ul>
                                
                                <h5><b>Features:</b></h5>
                                <ul>
                                    <li>Entwicklung einer Volltextsuche für kommerzielle Titel und Open-Access-Titel</li>
                                    <li>Übertragung des Bibelstellensuche-Algorithmus auf Kirchenrechtsquellen (CIC, CCEO) und auf eine Suche nach Zeiträumen</li>
                                    <li>Alerting-Services: Möglichkeit für Nutzer*innen, sich automatisch über neue Publikationen aus bestimmten Fächern oder Themengebieten informieren zu lassen</li>
                                </ul>

                                <h5><b>Dienste:</b></h5>
                                <ul>
                                    <li>IxTheo Open Journals: Gründung neuer und Aufnahme bestehender Zeitschriften in Open Access (Zeitschriften-Publikationssystem OJS)</li>
                                    <li>IxTheo Open Text: Zweitveröffentlichungsservice für Wissenschaftler*innen im Rahmen des Urheberrechts</li>
                                </ul>
                            </div>

                            <div role="tabpanel" class="tab-pane" id="tab4">
                                <h5><b>Inhalte</b></h5>
                                <ul>
                                    <li>Ausbau des IxTheo als forschungsorientiertes Recherchesystem und internationale Open-Access-Bibliographie</li>
                                    <li>Integration zahlreicher wichtiger theologischer Textgattungen in den IxTheo: Monographien, Aufsätze, Rezensionen, Datenbanken</li>
                                </ul>

                                <h5><b>Features</b></h5>
                                <ul>
                                    <li>technische Weiterentwicklung des IxTheo auf der Basis eines modernen und frei verfügbaren Discovery Systems (VuFind)</li>
                                    <li>Erstellung eines Bibelstellensuche-Algorithmus, der sich an den Bedürfnissen wissenschaftlicher Nutzer*innen orientiert</li>
                                </ul>
                                <h5><b>Dienste </b></h5>
                                <ul>
                                    <li>Aufbau eines theologischen Fachrepositoriums</li>
                                    <li>Etablierung des Zeitschriften-Publikationssystems Open Journal Systems</li>
                                </ul>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div> 
