<div class="cw-row">
    <div class="cw-col-lg-12 cw-ml-lg-4">
        <div class="cw-text-block"><br />
            <h1 class="cw-h1">Personenseiten</h1>

            <p>Personenseiten ermöglichen die gezielte Recherche nach Informationen zu Personen, Institutionen / Körperschaften und Tagungen. Dazu gehören im Index Theologicus (IxTheo) verzeichnete Publikationen von und über diese Person, häufige Sachthemen in ihrem Werk, biographische Daten, Archivquellen und Informationen aus weiteren externen Datenbanken.</p>
            <p>Um eine Personenseite aufzurufen, wählen Sie oberhalb des Suchschlitzes den Reiter „Personen/Körperschaften“ aus und geben dann den Namen der Person oder Institution ein. Bei mehreren passenden Treffern öffnet sich ggf. eine Liste, aus der Sie den gewünschten Eintrag auswählen können.</p>
            <p style="text-align: center; padding: 15px 0;"><img width="800" src="<?=$this->imageLink('content_img/en/persons_corporations_eng.png');?>" alt="<?=$this->translate('Screenshot: Tab „Persons / Corporations“ above the search bar');?>" /></p>
            <p>Auf der Personenseite finden Sie folgende Informationen:</p>

            <h3><b>Personendaten</b></h3>
            <p style="text-align: center; padding: 15px 0;"><img src="<?=$this->imageLink('content_img/en/personal_information_eng.png');?>" alt="<?=$this->translate('Screenshot: Personal information on the person page of an author (date of birth, date of death, variations of the name, occupation, biographical references, links to archival material and more)');?>" /></p>
            <p>Die hier verzeichneten Angaben beruhen auf Normdaten der Deutschen Nationalbibliothek (DNB). Für Korrekturen und Ergänzungen wenden Sie sich daher bitte an die <a href="mailto:gnd-info@dnb.de">zuständige Stelle der DNB</a>.</p>
            <p>Die Rubrik „Archivmaterial“ ermöglicht den direkten Zugriff auf Nachweise archivalischer und anderer handschriftlicher Quellen, z.B. Nachlässe oder Briefwechsel.</p>
            <p>Der Link https://ixtheo.de/AuthorityRecord/.... der in der Adressleiste des Browsers angezeigt wird, ist dauerhaft stabil. Sie können ihn z.B. in Seminarmaterialien oder Publikationslisten einbinden.</p>

            <p>Wenn es sich bei der Person um Sie selbst handelt, können Sie über die Schaltfläche „Zugriffsrechte beantragen“ Rechte beantragen, um eigene Publikationen <a href="<?=$this->url('content-page', ['page' => 'OpenText']) ?>">als Zweitveröffentlichung auf IxTheo hochladen</a> zu können.</p>

            <h3><b>Neueste Titel (von)</b></h3>
            <p>Angezeigt werden die jeweils neuesten in IxTheo verzeichneten Titel, die von der Person / Institution verfasst oder herausgegeben wurden. Ein Klick auf „Alle anzeigen“ führt zu einer Liste aller im IxTheo verzeichneten Publikationen, die von dieser Person / Institution stammen.</p>
            <p style="text-align: center; padding: 15px 0;"><img src="<?=$this->imageLink('content_img/en/newest_publications_by_eng.png');?>" alt="<?=$this->translate('Screenshot: List “Newest publications (by)” on the person page of an author');?>" /></p>

            <h3><b>Neueste Titel (über)</b></h3>
            <p>Unter dieser Rubrik sind beispielsweise Arbeiten über die Theologie einer Person, Biographien, Festschriften oder Nachrufe verzeichnet.</p>
            <p style="text-align: center; padding: 15px 0;"><img src="<?=$this->imageLink('content_img/en/newest_publications_about_eng.png');?>" alt="<?=$this->translate('Screenshot: List “Newest publications (about)” on the person page of an author');?>" /></p>

            <h3><b>Verbundene Personen und Institutionen</b></h3>
            <p>Hier geht es um das wissenschaftliche Netzwerk einer Person oder Institution: Aufgelistet werden diejenigen Autor*innen, mit denen sie besonders häufig gemeinsame Texte verfasst oder Publikationen gemeinschaftlich herausgegeben hat. Berücksichtigt werden auch Autor*innen, deren Werke die Person ediert hat oder Autor*innen, die umgekehrt Arbeiten über die Person verfasst haben.</p>
            <p style="text-align: center; padding: 15px 0;"><img src="<?=$this->imageLink('content_img/en/related_authors_eng.png');?>" alt="<?=$this->translate('Screenshot: List of related authors on the person page of an author');?>" /></p>

            <h3><b>Häufige Schlagwörter</b></h3>
            <p>Diese Funktion gibt einen Überblick über die Schlagwörter, die im IxTheo mit den Publikationen einer Person verknüpft sind. Das ermöglicht einen raschen Überblick über die Sachthemen, die in ihrem Werk eine besonders große Rolle spielen. Die Schlagwörter können über die Reiter wahlweise als Cloud, nach Häufigkeit oder als alphabetisch sortierte Liste angezeigt werden.</p>
            <p style="text-align: center; padding: 15px 0;"><img src="<?=$this->imageLink('content_img/en/wordcloud_eng.png');?>" alt="<?=$this->translate('Screenshot: Word cloud on the person page of an author which displays the keywords used most frequently to describe his works');?>" /></p>

            <h3><b>Veröffentlichungen</b></h3>
            <p>In der Grafik ist auf einen Blick die Chronologie der Veröffentlichungen einer Person erkennbar. Ebenso ist zu sehen, wann besonders viel über sie publiziert wurde (z.B. anlässlich von Jubiläen). Durch einen Klick auf die Schaltfläche "von" bzw. "über" oberhalb der Grafik können Sie sich auch nur Publikationen von oder nur Texte über die Person anzeigen lassen.</p>
            <p style="text-align: center; padding: 15px 0;"><img src="<?=$this->imageLink('content_img/en/publication_timeline_eng.png');?>" alt="<?=$this->translate('Screenshot: Bar chart on the person page of an author, showing the number of publications by and about this person sorted by year');?>"/></p>

        </div>
    </div>
</div>
