<div class="cw-row">
    <div class="cw-col-lg-12 cw-ml-lg-4">
        <div class="cw-text-block"><br />
            <h1 class="cw-h1">Person Information Pages</h1>

            <p>Person information pages provide information on persons, institutions / corporations and conferences. This information includes all publications catalogued in the Index Theologicus (IxTheo) from and about this person / institution, frequent subjects in their work, biographical data, archival sources and information from external databases.</p>
            <p>To call up a specific person information page, select the tab labelled “Persons / Corporations” above the search field and enter the name of the person or institution. If there are several persons or institutions with this name, you will see a list of them in which you can select the correct entry.</p>
            <p style="text-align: center; padding: 15px 0;"><img width="800" src="<?=$this->imageLink('content_img/en/persons_corporations_eng.png');?>" alt="<?=$this->transEscAttr('symbolic_image_table22');?>" /></p>
            <p>On the person information page, you will find the following information:</p>

            <h3><b>Biographical Information</b></h3>
            <p style="text-align: center; padding: 15px 0;"><img src="<?=$this->imageLink('content_img/en/personal_information_eng.png');?>" alt="<?=$this->transEscAttr('symbolic_image_table23');?>" /></p>
            <p>The information provided here is based on authority records from the German National Library (Deutsche Nationalbibliothek, DNB). If you wish to make corrections or provide supplemental information, please <a href="mailto:gnd-info@dnb.de">contact the DNB</a>.</p>
            <p>The section labelled “Archived Material” provides direct links to portals and other websites on which archived material (such as personal archives, unpublished letters, etc.) from or about this person is available.</p>
            <p>The link https://ixtheo.de/AuthorityRecord/.... which appears in the address bar of the browser is permanent. You can use it e.g. in seminar materials or publications lists.</p>

            <p>If you happen to be the person whose information is displayed, you can click on the button “Request access rights (This is me!)”, which will allow you to use our Self-Archiving Service to <a href="<?=$this->url('content-page', ['page' => 'OpenText']) ?>">upload your own publications on IxTheo</a>.</p>

            <h3><b>Newest Publications (by)</b></h3>
            <p>In this section, the newest publications written or edited by this person / institution and catalogued in IxTheo are displayed. If you click on “see all”, you will get a list of all publications in IxTheo which were written or edited by this person / institution.</p>
            <p style="text-align: center; padding: 15px 0;"><img src="<?=$this->imageLink('content_img/en/newest_publications_by_eng.png');?>" alt="<?=$this->transEscAttr('symbolic_image_table24');?>" /></p>

            <h3><b>Newest Publications (about)</b></h3>
            <p>In this section, entries such as publications on the theology of a person, biographies, festschrifts or obituaries are listed.</p>
            <p style="text-align: center; padding: 15px 0;"><img src="<?=$this->imageLink('content_img/en/newest_publications_about_eng.png');?>" alt="<?=$this->transEscAttr('symbolic_image_table25');?>" /></p>

            <h3><b>Related Authors and Institutions</b></h3>
            <p>This section concerns the academic network of a person or institution: The authors listed are those who most frequently wrote texts or edited publications together with the person concerned. Authors whose work was edited by this person and authors who wrote about this person are also included.</p>
            <p style="text-align: center; padding: 15px 0;"><img src="<?=$this->imageLink('content_img/en/related_authors_eng.png');?>" alt="<?=$this->transEscAttr('symbolic_image_table26');?>" /></p>

            <h3><b>Frequent Keywords</b></h3>
            <p>This section provides an overview of the keywords in IxTheo associated with the publications of the person in question. This allows you to get a quick overview of the subjects which are especially important in their work. The keywords can be displayed as a word cloud, as a list sorted by alphabetical order or as a list sorted by frequency by selecting the corresponding tab.</p>
            <p style="text-align: center; padding: 15px 0;"><img src="<?=$this->imageLink('content_img/en/wordcloud_eng.png');?>" alt="<?=$this->transEscAttr('symbolic_image_table27');?>" /></p>

            <h3><b>Publication Timeline</b></h3>
            <p>This graph displays the number of publications of the person from year to year. It also shows in which year(s) this person was the subject of an especially large number of publications (e.g. on special anniversaries). By clicking on the button “by” or “about”, you can choose to display only the number of publications “by” or “about” the person respectively.</p>
            <p style="text-align: center; padding: 15px 0;"><img src="<?=$this->imageLink('content_img/en/publication_timeline_eng.png');?>" alt="<?=$this->transEscAttr('symbolic_image_table28');?>"/></p>

        </div>
    </div>
</div>
