<div class="cw-row">
  <div class="cw-col-lg-12">
    <div class="cw-text-block"><br>
        <span id="ixtheo_content"></span>
        <h1 class="cw-h1">Beirat</h1>
        <p>Der Beirat setzt sich aus 10 Beiratsmitgliedern zusammen, je fünf Vertreter*innen der evangelischen und der katholischen Theologie. 
            Darunter sind je ein/e Vertreter*in aus den Dekanaten der beiden Tübinger theologischen Fakultäten sowie der Vorsitzende der 
            <a target="_blank" href="https://wgth.de">Wissenschaftlichen Gesellschaft für Theologie (WGTh)</a> [evangelisch] und der Sprecher der 
            <a target="_blank" href="https://www.katholische-theologie.info/zusammenschl%C3%BCsse">Vereinigung der Arbeitsgemeinschaften für Katholische Theologie (VAKT)</a> [katholisch].</p>
      
        <h5><b>Evangelische Community</b></h5>
        <ul>
            <li>Prof. Dr. Malte Dominik Krüger (Marburg)</li>
            <li>Prof. Dr. Kristin Merle (Hamburg)</li>
            <li>Prof. Dr. Andreas Müller (Kiel)</li>
            <li>Prof. Dr. Konrad Schmid (Zürich)</li>
            <li>Prof. Dr. Birgit Weyel (Tübingen)</li>
        </ul>
        <h5><b>Katholische Community</b></h5>
        <ul>
            <li>Prof. Dr. Rita Burrichter (Paderborn)</li>
            <li>Prof. Dr. Gerd Häfner (München)</li>
            <li>Prof. Dr. Marianne Heimbach-Steins (Münster)</li>
            <li>Prof. Dr. Andreas Holzem (Tübingen)</li>
            <li>Prof. Dr. Klaus Unterburger (Regensburg)</li>
        </ul>
    </div>
  </div>
</div>