<div class="container cw-py-5">
  <div class="cw-row">
    <div class="cw-col-lg-8">
      <div class="cw-text-block">
        <h1 class="cw-h1">Advisory Services</h1>
        <p>The IxTheo team offers extensive advisory services to the academic community on all aspects of searching for academic literature and resources, specialized subject information and publishing in all fields of theology. You are welcome to contact us if you have questions or would like more information on the following topics:</p>
        <h1 class="cw-h5">Open Access</h1>
        <ul>
            <li>Founding a new open access journal</li>
            <li>Transforming an existing journal into an open access journal</li>
            <li>Self-archiving your own academic publications</li>
        </ul>
        <h1 class="cw-h5">Academic Searches</h1>
        <ul>
            <li>Introduction to performing searches in IxTheo</li>
            <li>Courses in specialized search techniques for certain academic fields</li>
            <li>Support on particular search issues</li>
            <li>Advice on further resources (e.g. databases, information services for related academic fields)</li>
        </ul>
        <h1 class="cw-h5">Research Data</h1>
        <ul>
            <li>Documenting research data in IxTheo</li>
            <li>Services for providing and long-term archiving of various data types (e.g. survey data, documentation on archaeological digs, audio data, digital editions) [in development]</li>
            <li>Networking between research projects, NFDI (the various consortia for Research Data Infrastructure in Germany) and repositories</li>
        </ul>
        <h1 class="cw-h5">Cooperations</h1>
        <ul>
            <li>Networking between IxTheo and other bibliographies/databases</li>
            <li>Cooperation for indexing (e.g. subject terms)</li>
        </ul>
        <p>If you have any questions, please contact us: <a href="<?=$this->url('content-page', ['page' => 'ContactPersons']) ?>">Contact persons</a></p>
      </div>
    </div>
  </div>
</div>
