<div class="container cw-py-5">
  <div class="cw-row">
    <div class="cw-col-lg-8">
      <div class="cw-text-block">
        <h1 class="cw-h1">Beratung</h1>
        <p>Das IxTheo Team bietet der Fachcommunity umfangreiche Beratung zu allen Aspekten wissenschaftlicher Recherche, Fachinformation und Publikation in der Theologie. Sie können sich unter anderem zu folgenden Themen gerne an uns wenden:</p>
        <p>Open Access</p>
        <ul>
            <li>Neugründung von Open-Access-Zeitschriften</li>
            <li>Open-Access-Transformation bestehender Zeitschriften</li>
            <li>Zweitveröffentlichung und Self Archiving eigener wissenschaftlicher Texte</li>
        </ul>
        <p>Recherche</p>
        <ul>
            <li>Einführung in die Recherche in IxTheo</li>
            <li>Vertiefende Schulungen für bestimmte Fach- und Themengebiete</li>
            <li>Unterstützung bei speziellen Recherchefragen</li>
            <li>Beratung zu weiteren Ressourcen (z.B. Datenbanken, Fachinformation für benachbarte Fachgebiete)</li>
        </ul>
        <p>Forschungsdaten</p>
        <ul>
            <li>Nachweis von Forschungsdaten</li>
            <li>Beratung zu Bereitstellung und Langzeitarchivierung unterschiedlicher Datentypen (z.B. Umfragedaten, Grabungsdokumentationen, Audiodaten, digitale Editionen)</li>
            <li>Vernetzung zwischen Forschungsprojekten, NFDI und Repositorien</li>
        </ul>
        <p>Kooperationen</p>
        <ul>
            <li>Vernetzung anderer Bibliographien/Datenbanken mit IxTheo</li>
            <li>Kooperationen bei der Erschließung (z.B. Sachschlagwörter)</li>
        </ul>
        <p>Für Ihre Fragen und Anliegen stehen wir gerne zur Verfügung: <a href="<?=$this->url('content-page', ['page' => 'ContactPersons']) ?>">Ansprechpartner*innen</a></p>
      </div>
    </div>
  </div>
</div>