<div class="cw-row">
    <div class="cw-col-lg-12 cw-ml-lg-4">
        <div class="cw-text-block"><br>
            <h1 class="cw-h1">Bibliographien</h1>

            <p>IxTheo wird in Zusammenarbeit mit weiteren Bibliographien erstellt. Die Kooperationspartner beteiligen sich an der Aufnahme neuer Titel und der Sacherschließung. Alle vormals nur in den jeweiligen Bibliographien auffindbaren Daten sind im IxTheo recherchierbar.</p>
            <p>Aktuell arbeitet IxTheo mit folgenden Bibliographien zusammen:</p>
            <ul>
                <li>Augustinus-Bibliographie (Würzburg)</li>
                <li>BiBIL (Lausanne) [in Vorbereitung]</li>
                <li>BILDI (Innsbruck)</li>
                <li>DaKaR (Münster)
                    <ul>
                        <li>Lehrstuhl für Kirchenrecht und kirchliche Rechtsgeschichte an der Katholischen Universität Eichstätt-Ingolstadt</li>
                        <li>Lehrstuhl für Kirchenrecht und Kirchliche Rechtsgeschichte an der Albert-Ludwigs-Universität Freiburg</li>
                        <li>Generalvikariat im Erzbistum Hamburg</li>
                        <li>Seminar für Kirchenrecht, kirchliche Rechtsgeschichte und Staatskirchenrecht der JohannesGutenberg-Universität Mainz</li>
                        <li>Institut für Kanonisches Recht der Universität Münster</li>
                        <li>Bischöfliches Generalvikariat Osnabrück</li>
                        <li>Abteilung für Kirchenrecht an der Katholisch-Theologischen Fakultät der Universität Tübingen</li>
                    </ul>
                </li>
                <li>KALDI (Innsbruck)</li>
            </ul>
            <p>IxTheo ist offen für neue Kooperationen mit bereits bestehenden Bibliographien. Wenn Sie Interesse an einer Zusammenarbeit haben, wenden Sie sich gerne an <a href="mailto:ixtheo@ub.uni-tuebingen.de">ixtheo@ub.uni-tuebingen.de</a>.</p>
        </div>
    </div>
</div>