<div class="cw-row">
    <div class="cw-col-lg-12 cw-ml-lg-4">
        <div class="cw-text-block"><br>
            <h1 class="cw-h1">Bücher & Journals</h1>
            <p>Als internationale Open-Access-Bibliographie für Theologie und Religionswissenschaft verzeichnet der Index 
                Theologicus (IxTheo) wissenschaftlich relevante Literatur über das Christentum, über alle Fachgebiete christlicher 
                Theologie sowie über den Dialog mit anderen Religionen: konfessions-, sprachen-, medien- und zeitübergreifend.</p>
            <p>Schwerpunkte der Auswertung sind das 19.–21. Jahrhundert. Daneben enthält die Datenbank auch Texte, die im 16.–18. 
                Jahrhundert erschienen sind. Nachgewiesen werden Monographien, Aufsätze, Rezensionen sowie Reihen, Zeitschriften und Sammelbände.</p>
            <p>Wenn es lizenzrechtlich möglich ist, kann mit einem Klick auf digitale Publikationen zugegriffen werden. Die Funktion 
                „Verfügbarkeit prüfen“ erlaubt eine schnelle Auskunft über die Verfügbarkeit des gedruckten Werkes in Ihrer Heimatbibliothek.</p>
            <p>Insgesamt umfasst der IxTheo rund 3,8 Millionen theologisch und religionswissenschaftlich relevante Einträge:</p>
            
            
            <section class="cw-py-5">
                <div class="cw-container panel-group">
                    <div class="cw-row">
                        <!-- item-->
                        <div class="col-sm-6 col-lg-3 col-md-3 cw-mb-5 hover-animate tf-cursor-pointer">
                            <div data-toggle="collapse" data-target="#collapse-inno-1">
                                <div class="cw-card h-100 border-0 shadow">
                                    <div class="cw-card-img-top cw-overflow-hidden cw-dark-overlay cw-bg-cover innovativ-image-9">
                                        <!--img.img-fluid(src="#{imgBasePath}#{val.image}" alt="#{val.name}")-->
                                        <div class="cw-card-img-overlay-bottom cw-z-index-20">
                                            <h4 class="cw-h4 cw-text-white cw-text-shadow">Zeitschriften</h4>
                                            <!--<p class="cw-mb-2 cw-text-xs"><i class="fa fa-star text-warning"></i><i class="fa fa-star text-warning"></i><i class="fa fa-star text-warning"></i><i class="fa fa-star text-warning"></i><i class="fa fa-star text-gray-300"></i></p>-->
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="collapse" id="collapse-inno-1">
                                <div class="card card-body">
                                    <ul>
                                        <li>Systematischer Nachweis von einzelnen Aufsätzen und Rezensionen aus ca. 1.200 laufend ausgewerteten theologischen und religionswissenschaftlichen Zeitschriften</li>
                                        <li>Sukzessive Neu-Erfassung von 200 Zeitschriften, die von der theologischen Community für eine Auswertung im IxTheo priorisiert wurden. Für eine Übersicht konsultieren Sie bitte die <a target="_blank" href="https://ixtheo.de/docs/ixtheo-journals.pdf">Liste</a>. </li>
                                        <li>bei 700 Zeitschriften Nachweis aller Aufsätze bis zurück zum Erscheinungsbeginn</li>
                                        <li>Nachweis von ca. 35.000 Zeitschriften mit Informationen zu Erscheinungsverlauf, Vorgänger/Nachfolger, Herausgebenden und Verlag </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <!-- end item-->
                        <!-- item-->
                        <div class="col-sm-6 col-lg-3 cw-mb-5 hover-animate tf-cursor-pointer">
                            <div data-toggle="collapse" data-target="#collapse-inno-2">
                                <div class="cw-card h-100 border-0 shadow">
                                    <div class="cw-card-img-top cw-overflow-hidden cw-dark-overlay cw-bg-cover innovativ-image-10">
                                        <!--img.img-fluid(src="#{imgBasePath}#{val.image}" alt="#{val.name}")-->
                                        <div class="cw-card-img-overlay-bottom cw-z-index-20">
                                            <h4 class="cw-h4 cw-text-white cw-text-shadow">Monographien</h4>
                                            <!--<p class="cw-mb-2 cw-text-xs"><i class="fa fa-star text-warning"></i><i class="fa fa-star text-warning"></i><i class="fa fa-star text-warning"></i><i class="fa fa-star text-warning"></i><i class="fa fa-star text-gray-300"></i></p>-->
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="collapse" id="collapse-inno-2">
                                <div class="card card-body">
                                    <ul>
                                        <li>Systematischer Nachweis forschungsrelevanter Literatur aus den Nationalbibliographien verschiedener Sprachräume (deutsch, englisch, französisch, italienisch, portugiesisch, spanisch).</li>
                                        <li>Kooperation mit der Bayerischen Staatsbibliothek zum Nachweis von Literatur aus Ost-, Ostmittel- und Südosteuropa</li>              
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <!-- end item-->
                        <!-- item-->
                        <div class="col-sm-6 col-lg-3 cw-mb-5 hover-animate tf-cursor-pointer">
                            <div data-toggle="collapse" data-target="#collapse-inno-3">
                                <div class="cw-card h-100 border-0 shadow">
                                    <div class="cw-card-img-top cw-overflow-hidden cw-dark-overlay cw-bg-cover innovativ-image-11">
                                        <!--img.img-fluid(src="#{imgBasePath}#{val.image}" alt="#{val.name}")-->
                                        <div class="cw-card-img-overlay-bottom cw-z-index-20">
                                            <h4 class="cw-h4 cw-text-white cw-text-shadow">Sammelbände</h4>
                                            <!--<p class="cw-mb-2 cw-text-xs"><i class="fa fa-star text-warning"></i><i class="fa fa-star text-warning"></i><i class="fa fa-star text-warning"></i><i class="fa fa-star text-warning"></i><i class="fa fa-star text-gray-300"></i></p>-->
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="collapse" id="collapse-inno-3">
                                <div class="card card-body">
                                    <ul>
                                        <li>thematische Aufsatzbände</li>
                                        <li>Tagungsbände</li>
                                        <li>Festschriften</li>
                                        <li>Systematischer Nachweis von einzelnen Aufsätzen aus Sammelwerken</li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <!-- end item-->
                        <!-- item-->
                        <div class="col-sm-6 col-lg-3 cw-mb-5 hover-animate tf-cursor-pointer">
                            <div data-toggle="collapse" data-target="#collapse-inno-4">
                                <div class="cw-card h-100 border-0 shadow">
                                    <div class="cw-card-img-top cw-overflow-hidden cw-dark-overlay cw-bg-cover innovativ-image-12">
                                        <!--img.img-fluid(src="#{imgBasePath}#{val.image}" alt="#{val.name}")-->
                                        <div class="cw-card-img-overlay-bottom cw-z-index-20">
                                            <h4 class="cw-h4 cw-text-white cw-text-shadow">Reihen</h4>
                                            <!--<p class="cw-mb-2 cw-text-xs"><i class="fa fa-star text-warning"></i><i class="fa fa-star text-warning"></i><i class="fa fa-star text-warning"></i><i class="fa fa-star text-warning"></i><i class="fa fa-star text-gray-300"></i></p>-->
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="collapse" id="collapse-inno-4">
                                <div class="card card-body">
                                    <ul>
                                        <li>Dauerhafte und vollständige Erwerbung von <a target="_blank" href="https://ixtheo.de/docs/ixtheo-serials.pdf">Reihen und Fortsetzungen</a> durch die UB Tübingen im Rahmen des FID Theologie. Alle enthaltenen Werke und Aufsätze werden im IxTheo verzeichnet.</li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <!-- end item-->
                    </div>
                </div>
            </section>
            
            <?php /*
            <ul>
                <li>Zeitschriften
                    <ul>
                        <li>Systematischer Nachweis von einzelnen Aufsätzen und Rezensionen aus ca. 1.200 laufend ausgewerteten theologischen und religionswissenschaftlichen Zeitschriften</li>
                        <li>Sukzessive Neu-Erfassung von 200 Zeitschriften, die von der theologischen Community für eine Auswertung im IxTheo priorisiert wurden. Für eine Übersicht konsultieren Sie bitte die <a target="_blank" href="https://ixtheo.de/docs/ixtheo-journals.pdf">Liste</a>. </li>
                        <li>bei 700 Zeitschriften Nachweis aller Aufsätze bis zurück zum Erscheinungsbeginn</li>
                        <li>Nachweis von ca. 35.000 Zeitschriften mit Informationen zu Erscheinungsverlauf, Vorgänger/Nachfolger, Herausgebenden und Verlag </li>
                    </ul>
                </li>
                <li>Monographien
                    <ul>
                        <li>Systematischer Nachweis forschungsrelevanter Literatur aus den Nationalbibliographien verschiedener Sprachräume (deutsch, englisch, französisch, italienisch, portugiesisch, spanisch).</li>
                        <li>Kooperation mit der Bayerischen Staatsbibliothek zum Nachweis von Literatur aus Ost-, Ostmittel- und Südosteuropa</li>              
                    </ul>
                </li>
                <li>Sammelwerke
                    <ul>
                        <li>thematische Aufsatzbände</li>
                        <li>Tagungsbände</li>
                        <li>Festschriften</li>
                        <li>Systematischer Nachweis von einzelnen Aufsätzen aus Sammelwerken</li>
                    </ul>
                </li>
                <li>Laufende Reihen und Fortsetzungen
                    <ul>
                        <li>Dauerhafte und vollständige Erwerbung von <a target="_blank" href="https://ixtheo.de/docs/ixtheo-serials.pdf">Reihen und Fortsetzungen</a> durch die UB Tübingen im Rahmen des FID Theologie. Alle enthaltenen Werke und Aufsätze werden im IxTheo verzeichnet.</li>
                    </ul>
                </li>
                
            </ul>
            */?>
        </div>
    </div>
</div>

<style>
.cw-card-img-top  {
    min-width: 200px;
}

.innovativ-image-9 {
    background-image: url(/themes/ixtheo2/images/innovativ/Zeitschriften.jpg);
    min-height: 200px;
}
.innovativ-image-10 {
    background-image: url(/themes/ixtheo2/images/innovativ/Monographien.jpg);
    min-height: 200px;
}
.innovativ-image-11 {
    background-image: url(/themes/ixtheo2/images/innovativ/Sammelbande.jpg);
    min-height: 200px;
}
.innovativ-image-12 {
    background-image: url(/themes/ixtheo2/images/innovativ/Reihen.jpg);
    min-height: 200px;
}
</style>