<div class="cw-row">
    <div class="cw-col-lg-12 cw-ml-lg-4">
        <div class="cw-text-block"><br>
            <h1 class="cw-h1">Books & Journals</h1>
            <p>As an international open access bibliography for theology and religious studies, the Index Theologicus (IxTheo) provides information on scholarly literature about Christianity, about all fields of Christian theology and about the dialog with other religions. It references publications in multiple languages and formats concerning all confessions and denominations.</p>
            <p>IxTheo focuses mainly on publications which appeared from the 19th century to the present, but its database also contains information on publications from the 16th to the 18th century. The publications referenced include monographs, articles, reviews as well as series, journals and essay collections.</p>
            <p>With one click, you can access digital publications (depending on the licensing rights). The “Check availability” function allows you to quickly get information on the availability of printed literature at your local library.</p>
            <p>IxTheo currently references approx. 4.6 million publications on theology and religious studies:</p>
            
            
            <section class="cw-py-5">
                <div class="cw-container panel-group">
                    <div class="cw-row">
                        <!-- item-->
                        <div class="col-xs-12 col-sm-6 col-md-3 col-lg-3 cw-mb-5 hover-animate tf-cursor-pointer">
                            <div data-toggle="collapse" data-target="#collapse-inno-1">
                                <div class="cw-card h-100 border-0 shadow">
                                    <div class="cw-card-img-top cw-overflow-hidden cw-dark-overlay cw-bg-cover innovativ-image-9" title="<?=$this->transEscAttr('symbolic_image_table29');?>."></div>
                                    <div class="ix2-sub-item-title">Journals</div>
                                </div>
                            </div>
                            <div class="collapse" id="collapse-inno-1">
                                <div class="card card-body">
                                    <ul>
                                        <li>Systematic referencing of individual articles and reviews from approx. 1,200 journals of theology and religious studies which are catalogued on a regular basis</li>
                                        <li>Successive integration of 200 additional journals according to priorities set by the theological community. An overview of these journals is available in this <a target="_blank" href="https://ixtheo.de/docs/ixtheo-journals.pdf">list</a>. </li>
                                        <li>Cataloguing of all articles in 700 journals from the publication start to the present</li>
                                        <li>References to approx. 35,000 journals with information on publication history, predecessor/successor, editors and publishing house</li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <!-- end item-->
                        <!-- item-->
                        <div class="col-xs-12 col-sm-6 col-md-3 col-lg-3 cw-mb-5 hover-animate tf-cursor-pointer">
                            <div data-toggle="collapse" data-target="#collapse-inno-2">
                                <div class="cw-card h-100 border-0 shadow">
                                    <div class="cw-card-img-top cw-overflow-hidden cw-dark-overlay cw-bg-cover innovativ-image-10" title="<?=$this->transEscAttr('symbolic_image_table30');?>"></div>
                                    <div class="ix2-sub-item-title">Monographs</div>
                                </div>
                            </div>
                            <div class="collapse" id="collapse-inno-2">
                                <div class="card card-body">
                                    <ul>
                                        <li>Systematic references to academic research literature from national bibliographies in various language areas (German, English, French, Italian, Portuguese and Spanish)</li>
                                        <li>Cooperation with the Bayerische Staatsbibliothek Münc hen (Bavarian state library in Munich) for references to literature from East, East-Central and Southeast Europe</li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <!-- end item-->
                        <!-- item-->
                        <div class="col-xs-12 col-sm-6 col-md-3 col-lg-3 cw-mb-5 hover-animate tf-cursor-pointer">
                            <div data-toggle="collapse" data-target="#collapse-inno-3">
                                <div class="cw-card h-100 border-0 shadow">
                                    <div class="cw-card-img-top cw-overflow-hidden cw-dark-overlay cw-bg-cover innovativ-image-11" title="<?=$this->transEscAttr('symbolic_image_table15');?>"></div>
                                    <div class="ix2-sub-item-title">Essay Collections</div>
                                </div>
                            </div>
                            <div class="collapse" id="collapse-inno-3">
                                <div class="card card-body">
                                    <ul>
                                        <li>Thematic essay collections</li>
                                        <li>Conference proceedings</li>
                                        <li>Festschrifts</li>
                                        <li>Systematic cataloguing of individual articles from essay collections</li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <!-- end item-->
                        <!-- item-->
                        <div class="col-xs-12 col-sm-6 col-md-3 col-lg-3 cw-mb-5 hover-animate tf-cursor-pointer">
                            <div data-toggle="collapse" data-target="#collapse-inno-4">
                                <div class="cw-card h-100 border-0 shadow">
                                    <div class="cw-card-img-top cw-overflow-hidden cw-dark-overlay cw-bg-cover innovativ-image-12" title="<?=$this->transEscAttr('symbolic_image_table31');?>"></div>
                                    <div class="ix2-sub-item-title">Series</div>
                                </div>
                            </div>
                            <div class="collapse" id="collapse-inno-4">
                                <div class="card card-body">
                                    <ul>
                                        <li>Permanent and complete acquisition of  <a target="_blank" href="https://ixtheo.de/docs/ixtheo-serials.pdf">series and sequels</a> by the University Library of Tübingen within the framework of the FID Theologie. All the works and articles contained in these series are referenced in IxTheo.</li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <!-- end item-->
                    </div>
                </div>
            </section>
        </div>
    </div>
</div>
