<div class="cw-row">
    <div class="cw-col-lg-12 cw-ml-lg-4">
        <div class="cw-text-block"><br>
            <h1 class="cw-h1">Bücher & Journals</h1>
            <p>Als internationale Open-Access-Bibliographie für Theologie und Religionswissenschaft verzeichnet der Index 
                Theologicus (IxTheo) wissenschaftlich relevante Literatur über das Christentum, über alle Fachgebiete christlicher 
                Theologie sowie über den Dialog mit anderen Religionen: konfessions-, sprachen-, medien- und zeitübergreifend.</p>
            <p>Schwerpunkte der Auswertung sind das 19.–21. Jahrhundert. Daneben enthält die Datenbank auch Texte, die im 16.–18. 
                Jahrhundert erschienen sind. Nachgewiesen werden Monographien, Aufsätze, Rezensionen sowie Reihen, Zeitschriften und Sammelbände.</p>
            <p>Wenn es lizenzrechtlich möglich ist, kann mit einem Klick auf digitale Publikationen zugegriffen werden. Die Funktion 
                „Verfügbarkeit prüfen“ erlaubt eine schnelle Auskunft über die Verfügbarkeit des gedruckten Werkes in Ihrer Heimatbibliothek.</p>
            <p>Insgesamt umfasst der IxTheo rund 3,8 Millionen theologisch und religionswissenschaftlich relevante Einträge:</p>
            <ul>
                <li>Zeitschriften
                    <ul>
                        <li>Systematischer Nachweis von einzelnen Aufsätzen und Rezensionen aus ca. 1.200 laufend ausgewerteten theologischen und religionswissenschaftlichen Zeitschriften</li>
                        <li>Sukzessive Neu-Erfassung von 200 Zeitschriften, die von der theologischen Community für eine Auswertung im IxTheo priorisiert wurden. Für eine Übersicht konsultieren Sie bitte die <a target="_blank" href="https://ixtheo.de/docs/ixtheo-journals.pdf">Liste</a>. </li>
                        <li>bei 700 Zeitschriften Nachweis aller Aufsätze bis zurück zum Erscheinungsbeginn</li>
                        <li>Nachweis von ca. 35.000 Zeitschriften mit Informationen zu Erscheinungsverlauf, Vorgänger/Nachfolger, Herausgebenden und Verlag </li>
                    </ul>
                </li>
                <li>Monographien
                    <ul>
                        <li>Systematischer Nachweis forschungsrelevanter Literatur aus den Nationalbibliographien verschiedener Sprachräume (deutsch, englisch, französisch, italienisch, portugiesisch, spanisch).</li>
                        <li>Kooperation mit der Bayerischen Staatsbibliothek zum Nachweis von Literatur aus Ost-, Ostmittel- und Südosteuropa</li>              
                    </ul>
                </li>
                <li>Sammelwerke
                    <ul>
                        <li>thematische Aufsatzbände</li>
                        <li>Tagungsbände</li>
                        <li>Festschriften</li>
                        <li>Systematischer Nachweis von einzelnen Aufsätzen aus Sammelwerken</li>
                    </ul>
                </li>
                <li>Laufende Reihen und Fortsetzungen
                    <ul>
                        <li>Dauerhafte und vollständige Erwerbung von <a target="_blank" href="https://ixtheo.de/docs/ixtheo-serials.pdf">Reihen und Fortsetzungen</a> durch die UB Tübingen im Rahmen des FID Theologie. Alle enthaltenen Werke und Aufsätze werden im IxTheo verzeichnet.</li>
                    </ul>
                </li>
                
            </ul>
        </div>
    </div>
</div>