<div class="container cw-py-5 ix2-collection">
    <div class="cw-row">
        <div class="cw-col-lg-12">
            <div class="cw-text-block">
                <h1 class="cw-h1">Collections</h1>
				<p>The Index Theologicus (IxTheo) provides information on relevant collections from various sources in theology and religious studies. Some of these include older works from important libraries, others include more recent literature.</p>
				<p>These collections are searchable through IxTheo and can also be accessed directly through the links below.</p>
				<p>The following collections are currently searchable in IxTheo:</p>
				
				<section class="cw-py-2">
					<div class="cw-container panel-group">
						<div class="cw-row">
							<!-- item-->
							<div class="col-xs-12 col-sm-4 col-lg-4 cw-mb-5" >
								<div class="col-sm-12 col-lg-12 hover-animate tf-cursor-pointer">
									<div data-toggle="collapse" data-target="#collapse-inno-5">
										<div class="cw-card-img-top cw-overflow-hidden cw-dark-overlay cw-bg-cover innovativ-image">
											<div class="innovativ-image-bg innovativ-image-small">
												<img src="<?=$this->imageLink('innovativ/collection_logo5.png')?>" alt="<?=$this->transEscAttr('symbolic_image_table32');?>" class="cw-img-fluid cw-mb-5">
											</div>
										</div>
										<div class="cw-card h-100 border-0 shadow">
											<div class="cw-card-img-overlay-bottom cw-z-index-20">
												<h4 class="cw-h4 cw-text-white cw-text-shadow cw-text-small">Princeton Theological Commons</h4>
											</div>
										</div>
									</div>
									<div class="collapse" id="collapse-inno-5">
										<div class="card card-body">
											<p>The Princeton Theological Commons is a freely accessible digital library made available by Princeton Theological Seminary. It contains various resources on theology and religion. It includes over 158,000 books, journals, audio recordings, images and other formats from the 10th century to the present. <a href="https://commons.ptsem.edu/">More information on this collection</a></p>
											<p><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:PRTC') ?>">Holdings in IxTheo</a></p>
											<ol>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:ahom') ?>">Academy of Homiletics</a></li> 
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:afum') ?>">Albert Andrew Fulton Manuscript Collection</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:agsm') ?>">Ashbel Green Simonton Manuscript Collection</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:bslm') ?>">The Belle Sparr Luckett Manuscript Collection</a></li>		
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:behy') ?>">Benson Collection of Hymnals and Hymnology</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:bmsi') ?>">Beth Mardutho: The Syriac Institute</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:cbam') ?>">Caleb Cook Baldwin Manuscript Collection</a></li> 
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:djwt') ?>">David and Jane Wales Trumbull Manuscript Collection</a></li> 
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:epac') ?>">Earl Palmer Collection</a></li> 
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:ewam') ?>">Edward Warren Manuscript Collection</a></li> 
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:ghbm') ?>">The George H. Bowen Manuscript Collection</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:harm') ?>">The Harry A. Rhodes Manuscript Collection</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:jwam') ?>">The James Watt Manuscript Collection</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:jamc') ?>">John A. Mackay Collection</a></li> 
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:lksm') ?>">Langley Kitching South Africa / Madagascar Collection</a></li> 
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:laam') ?>">Latin America Collection</a></li> 
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:ljam') ?>">Levi Janvier Manuscript Collection</a></li> 
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:mcum') ?>">Michael S. Culbertson Manuscript Collection</a></li> 
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:mise') ?>">Missio Seminary Collection</a></li> 
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:moko') ?>">Moffett Korea Collection</a></li> 
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:mlrp') ?>">MRL Pamphlets</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:psam') ?>">Payne Seminary / AME Archive</a></li> 
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:ptsj') ?>">Princeton Theological Seminary Journals</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:ptsj') ?>">Princeton Theological Seminary Media Archive</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:resm') ?>">Robert Elliott Speer Manuscript Collection</a></li> 
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:rhnm') ?>">Robert Hamill Nassau Manuscript Collection</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:sfco') ?>">The Scott Family Collection</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:seev') ?>">Seminario Evangélico P. R.</a></li> 
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:shja') ?>">Sheldon Jackson Collection</a></li> 
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:tapo') ?>">Tanis Postcards Collection</a></li> 
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:tftc') ?>">Thomas F. Torrance Collection</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:wemi') ?>">Weld Missionary Papers</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:yole') ?>">Youth Lectures</a></li>
											</ol>
										</div>
									</div>
								</div>
							</div>
							<!-- end item-->
							<!-- item-->
							<div class="col-xs-12 col-sm-4 col-lg-4 cw-mb-5">
								<div class="col-sm-12 col-lg-12 hover-animate tf-cursor-pointer">
									<div data-toggle="collapse" data-target="#collapse-inno-2">
										<div class="cw-card-img-top cw-overflow-hidden cw-dark-overlay cw-bg-cover innovativ-image">
											<div class="innovativ-image-bg innovativ-image-small">
												<img src="<?=$this->imageLink('innovativ/collection_logo2.svg')?>" alt="<?=$this->transEscAttr('symbolic_image_table33');?>" class="cw-img-fluid cw-mb-5">
											</div>
										</div>
										<div class="cw-card h-100 border-0 shadow">
											<div class="cw-card-img-overlay-bottom cw-z-index-20">
												<h4 class="cw-h4 cw-text-white cw-text-shadow cw-text-small">Francke Foundations in Halle</h4>
											</div>
										</div>
									</div>
									<div class="collapse" id="collapse-inno-2">
										<div class="card card-body">
											<p>The library of the Francke Foundations in Halle holds significant collections of historical works with a main focus on the church history and cultural history of the early modern period.  <a href="https://www.francke-halle.de/en/science/archives-and-library/holdings">More information on this collection</a></p>
											<p><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:FRST') ?>">Holdings in IxTheo</a></p>
											<ol>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:cabi') ?>">Cansteinsche Bibelsammlung</a></li> 
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:oimi') ?>">Bibliothek der Ostindischen Missionsanstalt</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:lemw') ?>">Bibliothek des Leipziger Missionswerkes</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:misb') ?>">Missionsbibliothek in Leipzig</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:tami') ?>">Indienbibliothek mit Tamildrucken</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:lehb') ?>">Lehrerbibliothek</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:verb') ?>">Verlagsbibliothek</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:gesb') ?>">Gesangbuchsammlung</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:thol') ?>">Tholuckbibliothek</a></li>		
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:thok') ?>">Unterbibliothek Martin Kähler</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:thog') ?>">Unterbibliothek Martin von Gerlach</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:thos') ?>">Unterbibliothek Schlesisches Konvikt</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:belz') ?>">Bibliothek Walter Beltz</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:gepi') ?>">Aufsätze zur Geschichte des Pietismus</a></li>
											</ol>
										</div>
									</div>
								</div>
							</div>
							<!-- end item-->
							<!-- item-->
							<div class="col-xs-12 col-sm-4 col-lg-4 cw-mb-5" >
								<div class="col-sm-12 col-lg-12 hover-animate tf-cursor-pointer">
									<div data-toggle="collapse" data-target="#collapse-inno-4">
										<div class="cw-card-img-top cw-overflow-hidden cw-dark-overlay cw-bg-cover innovativ-image">
											<div class="innovativ-image-bg innovativ-image-small">
												<img src="<?=$this->imageLink('innovativ/collection_logo4.svg')?>" alt="<?=$this->transEscAttr('symbolic_image_table34');?>" class="cw-img-fluid cw-mb-5">
											</div>
										</div>
										<div class="cw-card h-100 border-0 shadow">
											<div class="cw-card-img-overlay-bottom cw-z-index-20">
												<h4 class="cw-h4 cw-text-white cw-text-shadow cw-text-small">Gotha Research Library</h4>
											</div>
										</div>
									</div>
									<div class="collapse" id="collapse-inno-4">
										<div class="card card-body">
										<p>The Gotha Research Library has comprehensive holdings of historical printed works, manuscripts, autographs and personal archives. Its collections on the cultural history of Protestantism in the early modern period are especially significant.  <a href="https://www.uni-erfurt.de/en/gotha-research-library">More information</a</p>
											<p><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:FRGO') ?>">Holdings in IxTheo</a></p>
											<ol>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:goth') ?>">Bestand Theologie</a></li> 
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:gols') ?>">Lesesaalbestand Theologie</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:godi') ?>">Theologische Dissertationen</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:gocs') ?>">Geistliche Lieder</a></li> 
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:golp') ?>">Leichenpredigten</a></li> 
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:gohs') ?>">Herzogliche Sammlung</a></li> 		
											</ol>
										</div>
									</div>
								</div>
							</div>
							<!-- end item-->
						</div>
					</div>
				</section>

				<section class="cw-py-2">
					<div class="cw-container panel-group">
						<div class="cw-row">
							<!-- item-->
							<div class="col-xs-12 col-sm-4 col-lg-4 cw-mb-5" >
								<div class="col-sm-12 col-lg-12 hover-animate tf-cursor-pointer">
									<div data-toggle="collapse" data-target="#collapse-inno-3">
										<div class="cw-card-img-top cw-overflow-hidden cw-dark-overlay cw-bg-cover innovativ-image">
											<div class="innovativ-image-bg innovativ-image-small">
												<img src="<?=$this->imageLink('innovativ/collection_logo3.svg')?>" alt="<?=$this->transEscAttr('symbolic_image_table35');?>" class="cw-img-fluid cw-mb-5 cw-big">
											</div>
										</div>
										<div class="cw-card h-100 border-0 shadow">
											<div class="cw-card-img-overlay-bottom cw-z-index-20">
												<h4 class="cw-h4 cw-text-white cw-text-shadow cw-text-small">Reformationsgeschichtliche Forschungsbibliothek Wittenberg</h4>
											</div>
										</div>
									</div>
									<div class="collapse" id="collapse-inno-3">
										<div class="card card-body">
										<p>The Reformationsgeschichtliche Forschungsbibliothek Wittenberg holds significant collections from the 9th century to the present. Its main areas of focus are the 16th and 17th centuries, church history, university history, the history of education and the history of Wittenberg as well as theology and religious education. <a href="https://www.rfb-wittenberg.de/bibliothek/ueber-die-bestaende">More information</a></p>
											<p><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:RFBW') ?>">Holdings in IxTheo</a></p>
											<p><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:rfuw') ?>">Übergeordnete Werke</a></p>
											<p><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:rfne') ?>">RFB Neubestand</a></p>
											<ol>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:bips') ?>">Bibliothek des Evangelischen Predigerseminars</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:rfne') ?>">Predigerseminar Neubestand (2018-2023)</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:psnb') ?>">Predigerseminar Neubestand (1952-2017)</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:psma') ?>">Predigerseminar Mittlere Abteilung (1817-1951)</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:psab') ?>">Predigerseminar Altbestand</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:psra') ?>">Predigerseminar Rara</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:pscc') ?>">Bibliothek Carl Clemen</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:pswt') ?>">Bibliothek Wolfgang Trillhaas</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:psib') ?>">Bibliothek des ehemaligen Predigerseminars Ilsenburg</a></li>					
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:psek') ?>">Kirchenkanzlei der EKU</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:pssh') ?>">Sammlung Heubner</a></li>
												
											</ol>
											<ol>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:lglu') ?>">Bibliothek des Lutherhauses der Stiftung Luthergedenkstätten in Sachsen-Anhalt</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:lgnb') ?>">Bibliothek des Lutherhauses Neubestand</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:lgme') ?>">Melanchthonhaus Wittenberg</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:lgfi') ?>">Bibliothek Johannes Ficker</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:lgka') ?>">Bibliothek Gustav Kawerau</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:lgbm') ?>">Arbeitsbibliothek Bernd Moeller</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:lghj') ?>">Arbeitsbibliothek Helmar Junghans</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:lghr') ?>">Arbeitsbibliothek Heimo Reinitzer</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:lgmb') ?>">Arbeitsbibliothek Martin Brecht</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:lgmg') ?>">Bibliothek Merseburg</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:lgau') ?>">Augustinische Sammlung</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:lgsk') ?>">Sammlung Karl Knaake</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:lgss') ?>">(Großteils Lutherdrucke)</a></li>
											</ol>
											<ol>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:ulbm') ?>">ULB Sammlung Mahlmann</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:ulds') ?>">ULB Sammlung Mahlmann (Dissertationen)</a></li>
											</ol>
										</div>
									</div>
								</div>
							</div>
							<!-- end item-->
							<!-- item-->
							<div class="col-xs-12 col-sm-4 col-lg-4 cw-mb-5" >
								<div class="col-sm-12 col-lg-12 hover-animate tf-cursor-pointer">
									<div data-toggle="collapse" data-target="#collapse-inno-1">
										<div class="cw-card-img-top cw-overflow-hidden cw-dark-overlay cw-bg-cover innovativ-image">
											<div class="innovativ-image-bg innovativ-image-small">
												<img src="<?=$this->imageLink('innovativ/collection_logo1.png')?>" alt="<?=$this->transEscAttr('symbolic_image_table36');?>" class="cw-img-fluid cw-mb-5 cw-big">
											</div>
										</div>
										<div class="cw-card h-100 border-0 shadow">
											<div class="cw-card-img-overlay-bottom cw-z-index-20">
												<h4 class="cw-h4 cw-text-white cw-text-shadow cw-text-small">Johannes a Lasco Bibliothek</h4>
											</div>
										</div>
									</div>
									<div class="collapse" id="collapse-inno-1">
										<div class="card card-body">
										<p>The Johannes a Lasco Bibliothek in Emden is a theological research library. It focuses mainly on Reformed Protestantism and confessional history of the early modern period.<a href="https://www.jalb.de/23462-0-0-66.html">More information</a></p>
											<p><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:JALB') ?>">Holdings in IxTheo</a></p>
											<ol>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:jpja') ?>">Sammlung Johann Philipp Janssen</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:jpjt') ?>">Sammlung Johann Philipp Janssen (Theologie)</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:arha') ?>">Sammlung Albert Rizaeus Hardenberg</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:ysbu') ?>">Sammlung Ysenburg-Büdingen</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:peme') ?>">Sammlung Petrus Medmann</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:sebe') ?>">Sammlung Schloss Ebersdorf</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:frit') ?>">Sammlung Friedrich Ritter</a></li>
											</ol>
										</div>
									</div>
								</div>
							</div>
							<!-- end item-->
						</div>
					</div>
				</section>
									
				<section class="cw-py-2">
					<div class="cw-container panel-group">
						<h2 class="cw-py-2"><b>Collections in Cooperation with the Specialized Information Service in Religious Studies (RelBib)</b></h2>
						<div class="cw-row">
							<!-- item-->
							<div class="col-xs-12 col-sm-4 col-lg-4 cw-mb-5 cw-mb-5">
								<div class="hover-animate tf-cursor-pointer">
									<div data-toggle="collapse" data-target="#collapse-inno-7">
										<div class="cw-card-img-top cw-overflow-hidden cw-dark-overlay cw-bg-cover">
											<div class="cw-card-img-top cw-overflow-hidden cw-dark-overlay cw-bg-cover">
												<div class="innovativ-image-default-bg"></div>
											</div>
										</div>
										<div class="cw-card h-100 border-0 shadow">
											<div class="cw-card-img-overlay-bottom cw-z-index-20">
												<h4 class="cw-h4 cw-text-white cw-text-shadow cw-text-small">Archives of the Religionswissenschaftlicher Medien- und Informationsdienst (REMID), Universitätsbibliothek Marburg</h4>
											</div>
										</div>
									</div>
									<div class="collapse" id="collapse-inno-7">
										<div class="card card-body">
											<p>The archives of the Religionswissenschaftlicher Medien- und Informationsdienst (REMID) hold a comprehensive collection of primary sources on religious groups in the German-speaking world, especially the new religious movements. <a href="https://www.uni-marburg.de/de/ub/forschen/historische-bestaende/sammlungen/remid-archiv">More information on the website of the University of Marburg</a></p>
											<p><a target="_blank" href="https://relbib.de/Content/cooperations_institutions#col4">Information on the RelBib website</a></p>
											<p><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:remi') ?>">Publications and archival materials</a></p>
										</div>
									</div>
								</div>
							</div>
							<!-- end item-->
							<!-- item-->
							<div class="col-xs-12 col-sm-4 col-lg-4 cw-mb-5">
								<div class="hover-animate tf-cursor-pointer">
									<div data-toggle="collapse" data-target="#collapse-inno-9">
										<div class="cw-card-img-top cw-overflow-hidden cw-dark-overlay cw-bg-cover">
											<div class="cw-card-img-top cw-overflow-hidden cw-dark-overlay cw-bg-cover">
												<div class="innovativ-image-default-bg"></div>
											</div>
										</div>
										<div class="cw-card h-100 border-0 shadow">
											<div class="cw-card-img-overlay-bottom cw-z-index-20">
												<h4 class="cw-h4 cw-text-white cw-text-shadow cw-text-small">Archives and Dokumentationsstelle “Religiöser und weltanschaulicher Pluralismus”, University of Leipzig</h4>
											</div>
										</div>
									</div>
									<div class="collapse" id="collapse-inno-9">
										<div class="card card-body">
											<p><a target="_blank" href="https://relbib.de/Content/cooperations_institutions#col4">Information on the website of RelBib</a></p>
											<p><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:redo') ?>">Publications and archival materials</a></p>
										</div>
									</div>
								</div>
							</div>
							<!-- end item-->
							<!-- item-->
							<div class="col-xs-12 col-sm-4 col-lg-4 cw-mb-5">
								<div class="hover-animate tf-cursor-pointer">
									<div data-toggle="collapse" data-target="#collapse-inno-10">
										<div class="cw-card-img-top cw-overflow-hidden cw-dark-overlay cw-bg-cover">
											<div class="cw-card-img-top cw-overflow-hidden cw-dark-overlay cw-bg-cover">
												<div class="innovativ-image-default-bg"></div>
											</div>
										</div>
										<div class="cw-card h-100 border-0 shadow">
											<div class="cw-card-img-overlay-bottom cw-z-index-20">
												<h4 class="cw-h4 cw-text-white cw-text-shadow cw-text-small">Collections of other Specialized Information Services in Germany with relevant information on religious studies or theology</h4>
											</div>
										</div>
									</div>
									<div class="collapse" id="collapse-inno-10">
										<div class="card card-body">
											<p><a target="_blank" href="https://relbib.de/Content/cooperations_institutions#col3">Information on the website of RelBib</a></p>
											<p><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:hdsa') ?>">Holdings of the FID South Asia concerning religious studies</a></p>
											<p><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:fivi') ?>">Holdings in the “Fachinformationsverbund Internationale Beziehungen und Länderkunde” concerning religious studies</a></p>
										</div>
									</div>
								</div>
							</div>
							<!-- end item-->
						</div>
					</div>
				</section>	

			 </div>
        </div>
    </div>
</div>
