<div class="container cw-py-5 ix2-collection">
    <div class="cw-row">
        <div class="cw-col-lg-12">
            <div class="cw-text-block">
                <h1 class="cw-h1">Sammlungen</h1>
				<p>Der Index Theologicus (IxTheo) wertet theologisch und religionswissenschaftlich relevante Sammlungen aus unterschiedlichen Quellen aus. Dabei handelt es sich teils um theologisch relevante Altbestände wichtiger Bibliotheken, teils um aktuelle Literatur.</p>
				<p>Die Sammlungen sind nicht nur mit ihren einzelnen Einträgen über IxTheo durchsuchbar, sondern lassen sich auch gezielt über die im Folgenden genannten Links abrufen.</p>
				<p>Derzeit sind folgende Sammlungen im IxTheo recherchierbar:</p>
				
				<section class="cw-py-2">
					<div class="cw-container panel-group">
						<div class="cw-row">
							<!-- item-->
							<div class="col-sm-4 col-lg-4 cw-mb-5" >
								<div class="col-sm-12 col-lg-12 hover-animate tf-cursor-pointer">
									<div data-toggle="collapse" data-target="#collapse-inno-5">
										<div class="cw-card-img-top cw-overflow-hidden cw-dark-overlay cw-bg-cover innovativ-image">
											<div class="innovativ-image-bg innovativ-image-small">
												<img src="<?=$this->imageLink('innovativ/collection_logo5.png')?>" alt="" class="cw-img-fluid cw-mb-5">
											</div>
										</div>
										<div class="cw-card h-100 border-0 shadow">
											<div class="cw-card-img-overlay-bottom cw-z-index-20">
												<h4 class="cw-h4 cw-text-white cw-text-shadow cw-text-small">Princeton Theological Commons</h4>
											</div>
										</div>
									</div>
									<div class="collapse" id="collapse-inno-5">
										<div class="card card-body">
											<p>Princeton Theological Commons ist eine vom Princeton Theological Seminary bereitgestellte digitale Bibliothek, die unterschiedliche Sammlungen zu Theologie und Religion umfasst. Sie enthält über 158.000 Bücher, Zeitschriften, Audioquellen, Bildquellen und weitere Medien vom 10. Jahrhundert bis zur Gegenwart.  <a href="https://commons.ptsem.edu/">Nähere Informationen zur Sammlung</a></p>
											<p><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:PRTC') ?>">Gesamtbestand in IxTheo</a></p>
											<ol>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:ahom') ?>">Academy of Homiletics</a></li> 
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:afum') ?>">Albert Andrew Fulton Manuscript Collection</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:agsm') ?>">Ashbel Green Simonton Manuscript Collection</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:bslm') ?>">The Belle Sparr Luckett Manuscript Collection</a></li>		
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:behy') ?>">Benson Collection of Hymnals and Hymnology</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:bmsi') ?>">Beth Mardutho: The Syriac Institute</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:cbam') ?>">Caleb Cook Baldwin Manuscript Collection</a></li> 
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:djwt') ?>">David and Jane Wales Trumbull Manuscript Collection</a></li> 
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:epac') ?>">Earl Palmer Collection</a></li> 
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:ewam') ?>">Edward Warren Manuscript Collection</a></li> 
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:ghbm') ?>">The George H. Bowen Manuscript Collection</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:harm') ?>">The Harry A. Rhodes Manuscript Collection</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:jwam') ?>">The James Watt Manuscript Collection</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:jamc') ?>">John A. Mackay Collection</a></li> 
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:lksm') ?>">Langley Kitching South Africa / Madagascar Collection</a></li> 
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:laam') ?>">Latin America Collection</a></li> 
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:ljam') ?>">Levi Janvier Manuscript Collection</a></li> 
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:mcum') ?>">Michael S. Culbertson Manuscript Collection</a></li> 
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:mise') ?>">Missio Seminary Collection</a></li> 
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:moko') ?>">Moffett Korea Collection</a></li> 
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:mlrp') ?>">MRL Pamphlets</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:psam') ?>">Payne Seminary / AME Archive</a></li> 
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:ptsj') ?>">Princeton Theological Seminary Journals</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:ptsj') ?>">Princeton Theological Seminary Media Archive</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:resm') ?>">Robert Elliott Speer Manuscript Collection</a></li> 
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:rhnm') ?>">Robert Hamill Nassau Manuscript Collection</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:sfco') ?>">The Scott Family Collection</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:seev') ?>">Seminario Evangélico P. R.</a></li> 
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:shja') ?>">Sheldon Jackson Collection</a></li> 
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:tapo') ?>">Tanis Postcards Collection</a></li> 
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:tftc') ?>">Thomas F. Torrance Collection</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:wemi') ?>">Weld Missionary Papers</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:yole') ?>">Youth Lectures</a></li>
											</ol>
										</div>
									</div>
								</div>
							</div>
							<!-- end item-->
							<!-- item-->
							<div class="col-sm-4 col-lg-4 cw-mb-5">
								<div class="col-sm-12 col-lg-12 hover-animate tf-cursor-pointer">
									<div data-toggle="collapse" data-target="#collapse-inno-2">
										<div class="cw-card-img-top cw-overflow-hidden cw-dark-overlay cw-bg-cover innovativ-image">
											<div class="innovativ-image-bg innovativ-image-small">
												<img src="<?=$this->imageLink('innovativ/collection_logo2.svg')?>" alt="" class="cw-img-fluid cw-mb-5">
											</div>
										</div>
										<div class="cw-card h-100 border-0 shadow">
											<div class="cw-card-img-overlay-bottom cw-z-index-20">
												<h4 class="cw-h4 cw-text-white cw-text-shadow cw-text-small">Franckesche Stiftungen zu Halle</h4>
											</div>
										</div>
									</div>
									<div class="collapse" id="collapse-inno-2">
										<div class="card card-body">
											<p>Die Bibliothek der Franckeschen Stiftungen zu Halle verfügt über einen bedeutenden Altbestand mit Schwerpunkt auf der Kirchen- und Kulturgeschichte der Frühen Neuzeit. <a href="https://www.francke-halle.de/de/studienzentrum/fachinformationen-bestaende">Nähere Informationen zur Sammlung</a></p>
											<p><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:FRST') ?>">Gesamtbestand in IxTheo</a></p>
											<ol>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:cabi') ?>">Cansteinsche Bibelsammlung</a></li> 
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:oimi') ?>">Bibliothek der Ostindischen Missionsanstalt</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:lemw') ?>">Bibliothek des Leipziger Missionswerkes</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:misb') ?>">Missionsbibliothek in Leipzig</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:tami') ?>">Indienbibliothek mit Tamildrucken</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:lehb') ?>">Lehrerbibliothek</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:verb') ?>">Verlagsbibliothek</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:gesb') ?>">Gesangbuchsammlung</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:thol') ?>">Tholuckbibliothek</a></li>		
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:thok') ?>">Unterbibliothek Martin Kähler</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:thog') ?>">Unterbibliothek Martin von Gerlach</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:thos') ?>">Unterbibliothek Schlesisches Konvikt</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:belz') ?>">Bibliothek Walter Beltz</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:gepi') ?>">Aufsätze zur Geschichte des Pietismus</a></li>
											</ol>
										</div>
									</div>
								</div>
							</div>
							<!-- end item-->
							<!-- item-->
							<div class="col-sm-4 col-lg-4 cw-mb-5" >
								<div class="col-sm-12 col-lg-12 hover-animate tf-cursor-pointer">
									<div data-toggle="collapse" data-target="#collapse-inno-4">
										<div class="cw-card-img-top cw-overflow-hidden cw-dark-overlay cw-bg-cover innovativ-image">
											<div class="innovativ-image-bg innovativ-image-small">
												<img src="<?=$this->imageLink('innovativ/collection_logo4.svg')?>" alt="" class="cw-img-fluid cw-mb-5">
											</div>
										</div>
										<div class="cw-card h-100 border-0 shadow">
											<div class="cw-card-img-overlay-bottom cw-z-index-20">
												<h4 class="cw-h4 cw-text-white cw-text-shadow cw-text-small">Forschungsbibliothek Gotha</h4>
											</div>
										</div>
									</div>
									<div class="collapse" id="collapse-inno-4">
										<div class="card card-body">
											<p><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:FRGO') ?>">Gesamtbestand</a></p>
											<ol>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:goth') ?>">Bestand Theologie</a></li> 
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:gols') ?>">Lesesaalbestand Theologie</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:godi') ?>">Theologische Dissertationen</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:gocs') ?>">Geistliche Lieder</a></li> 
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:golp') ?>">Leichenpredigten</a></li> 
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:gohs') ?>">Herzogliche Sammlung</a></li> 		
											</ol>
										</div>
									</div>
								</div>
							</div>
							<!-- end item-->
						</div>
					</div>
				</section>

				<section class="cw-py-2">
					<div class="cw-container panel-group">
						<div class="cw-row">
							<!-- item-->
							<div class="col-sm-4 col-lg-4 cw-mb-5" >
								<div class="col-sm-12 col-lg-12 hover-animate tf-cursor-pointer">
									<div data-toggle="collapse" data-target="#collapse-inno-3">
										<div class="cw-card-img-top cw-overflow-hidden cw-dark-overlay cw-bg-cover innovativ-image">
											<div class="innovativ-image-bg innovativ-image-small">
												<img src="<?=$this->imageLink('innovativ/collection_logo3.svg')?>" alt="" class="cw-img-fluid cw-mb-5 cw-big">
											</div>
										</div>
										<div class="cw-card h-100 border-0 shadow">
											<div class="cw-card-img-overlay-bottom cw-z-index-20">
												<h4 class="cw-h4 cw-text-white cw-text-shadow cw-text-small">Reformationsgeschichtliche Forschungsbibliothek Wittenberg</h4>
											</div>
										</div>
									</div>
									<div class="collapse" id="collapse-inno-3">
										<div class="card card-body">
											<p><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:RFBW') ?>">Gesamtbestand</a></p>
											<p><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:rfuw') ?>">Übergeordnete Werke</a></p>
											<p><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:rfne') ?>">RFB Neubestand</a></p>
											<ol>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:bips') ?>">Bibliothek des Evangelischen Predigerseminars</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:rfne') ?>">Predigerseminar Neubestand (2018-2023)</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:psnb') ?>">Predigerseminar Neubestand (1952-2017)</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:psma') ?>">Predigerseminar Mittlere Abteilung (1817-1951)</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:psab') ?>">Predigerseminar Altbestand</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:psra') ?>">Predigerseminar Rara</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:pscc') ?>">Bibliothek Carl Clemen</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:pswt') ?>">Bibliothek Wolfgang Trillhaas</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:psib') ?>">Bibliothek des ehemaligen Predigerseminars Ilsenburg</a></li>					
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:psek') ?>">Kirchenkanzlei der EKU</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:pssh') ?>">Sammlung Heubner</a></li>
												
											</ol>
											<ol>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:lglu') ?>">Bibliothek des Lutherhauses der Stiftung Luthergedenkstätten in Sachsen-Anhalt</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:lgnb') ?>">Bibliothek des Lutherhauses Neubestand</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:lgme') ?>">Melanchthonhaus Wittenberg</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:lgfi') ?>">Bibliothek Johannes Ficker</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:lgka') ?>">Bibliothek Gustav Kawerau</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:lgbm') ?>">Arbeitsbibliothek Bernd Moeller</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:lghj') ?>">Arbeitsbibliothek Helmar Junghans</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:lghr') ?>">Arbeitsbibliothek Heimo Reinitzer</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:lgmb') ?>">Arbeitsbibliothek Martin Brecht</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:lgmg') ?>">Bibliothek Merseburg</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:lgau') ?>">Augustinische Sammlung</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:lgsk') ?>">Sammlung Karl Knaake</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:lgss') ?>">(Großteils Lutherdrucke)</a></li>
											</ol>
											<ol>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:ulbm') ?>">ULB Sammlung Mahlmann</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:ulds') ?>">ULB Sammlung Mahlmann (Dissertationen)</a></li>
											</ol>
										</div>
									</div>
								</div>
							</div>
							<!-- end item-->
							<!-- item-->
							<div class="col-sm-4 col-lg-4 cw-mb-5" >
								<div class="col-sm-12 col-lg-12 hover-animate tf-cursor-pointer">
									<div data-toggle="collapse" data-target="#collapse-inno-1">
										<div class="cw-card-img-top cw-overflow-hidden cw-dark-overlay cw-bg-cover innovativ-image">
											<div class="innovativ-image-bg innovativ-image-small">
												<img src="<?=$this->imageLink('innovativ/collection_logo1.png')?>" alt="" class="cw-img-fluid cw-mb-5 cw-big">
											</div>
										</div>
										<div class="cw-card h-100 border-0 shadow">
											<div class="cw-card-img-overlay-bottom cw-z-index-20">
												<h4 class="cw-h4 cw-text-white cw-text-shadow cw-text-small">Johannes a Lasco Bibliothek</h4>
											</div>
										</div>
									</div>
									<div class="collapse" id="collapse-inno-1">
										<div class="card card-body">
											<p><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:JALB') ?>">Gesamtbestand</a></p>
											<ol>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:jpja') ?>">Sammlung Johann Philipp Janssen</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:jpjt') ?>">Sammlung Johann Philipp Janssen (Theologie)</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:arha') ?>">Sammlung Albert Rizaeus Hardenberg</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:ysbu') ?>">Sammlung Ysenburg-Büdingen</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:peme') ?>">Sammlung Petrus Medmann</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:sebe') ?>">Sammlung Schloss Ebersdorf</a></li>
												<li><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:frit') ?>">Sammlung Friedrich Ritter</a></li>
											</ol>
										</div>
									</div>
								</div>
							</div>
							<!-- end item-->
						</div>
					</div>
				</section>
									
				<section class="cw-py-2">
					<div class="cw-container panel-group">
						<div class="cw-row">
							<!-- item-->
							<div class="col-sm-4 col-lg-4 cw-mb-5 cw-mb-5">
								<div class="hover-animate tf-cursor-pointer">
									<div data-toggle="collapse" data-target="#collapse-inno-7">
										<div class="cw-card-img-top cw-overflow-hidden cw-dark-overlay cw-bg-cover">
											<div class="cw-card-img-top cw-overflow-hidden cw-dark-overlay cw-bg-cover">
												<div class="innovativ-image-default-bg"></div>
											</div>
										</div>
										<div class="cw-card h-100 border-0 shadow">
											<div class="cw-card-img-overlay-bottom cw-z-index-20">
												<h4 class="cw-h4 cw-text-white cw-text-shadow cw-text-small">Archiv des Religionswissenschaftlichen Medien- und Informationsdienstes (REMID), Universitätsbibliothek Marburg</h4>
											</div>
										</div>
									</div>
									<div class="collapse" id="collapse-inno-7">
										<div class="card card-body">
											<p>Das Archiv des Religionswissenschaftlichen Medien- und Informationsdienstes (REMID) enthält eine umfassende Sammlung von Primärquellen religiöser Gruppen im deutschsprachigen Raum, insbesondere der sogenannten Neuen Religiösen Bewegungen. <a href="https://www.uni-marburg.de/de/ub/forschen/historische-bestaende/sammlungen/remid-archiv">Nähere Informationen</a></p>
											<p><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:remi') ?>">Publikationen und Archivmaterialien</a></p>
										</div>
									</div>
								</div>
							</div>
							<!-- end item-->
							<!-- item-->
							<div class="col-sm-4 col-lg-4 cw-mb-5">
								<div class="hover-animate tf-cursor-pointer">
									<div data-toggle="collapse" data-target="#collapse-inno-9">
										<div class="cw-card-img-top cw-overflow-hidden cw-dark-overlay cw-bg-cover">
											<div class="cw-card-img-top cw-overflow-hidden cw-dark-overlay cw-bg-cover">
												<div class="innovativ-image-default-bg"></div>
											</div>
										</div>
										<div class="cw-card h-100 border-0 shadow">
											<div class="cw-card-img-overlay-bottom cw-z-index-20">
												<h4 class="cw-h4 cw-text-white cw-text-shadow cw-text-small">Archiv mit Dokumentationsstelle „Religiöser und weltanschaulicher Pluralismus“, Universität Leipzig</h4>
											</div>
										</div>
									</div>
									<div class="collapse" id="collapse-inno-9">
										<div class="card card-body">
										<p><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:redo') ?>">Publikationen und Archivmaterialien</a></p>
										</div>
									</div>
								</div>
							</div>
							<!-- end item-->
							<!-- item-->
							<div class="col-sm-4 col-lg-4 cw-mb-5">
								<div class="hover-animate tf-cursor-pointer">
									<div data-toggle="collapse" data-target="#collapse-inno-10">
										<div class="cw-card-img-top cw-overflow-hidden cw-dark-overlay cw-bg-cover">
											<div class="cw-card-img-top cw-overflow-hidden cw-dark-overlay cw-bg-cover">
												<div class="innovativ-image-default-bg"></div>
											</div>
										</div>
										<div class="cw-card h-100 border-0 shadow">
											<div class="cw-card-img-overlay-bottom cw-z-index-20">
												<h4 class="cw-h4 cw-text-white cw-text-shadow cw-text-small">Religionswissenschaftlich und theologisch relevante Teilsammlungen anderer Fachinformationsdienste</h4>
											</div>
										</div>
									</div>
									<div class="collapse" id="collapse-inno-10">
										<div class="card card-body">
											<p><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:hdsa') ?>">Religionswissenschaftlich relevanter Bestand des FID Südasien</a></p>
											<p><a href="<?=$this->url('search-results') ?>?lookfor=<?=urlencode('rs:fivi') ?>">Religionswissenschaftlich relevanter Bestand der Bibliotheken des Fachinformationsverbunds Internationale Beziehungen und Länderkunde</a></p>
										</div>
									</div>
								</div>
							</div>
							<!-- end item-->
						</div>
					</div>
				</section>	

			 </div>
        </div>
    </div>
</div>

<style>
.ix2-collection .hover-animate {
	padding: 5px;
	border: 5px solid #3586b2;
	border-radius: 15px;
}

.innovativ-image{
	text-align: center;
}

.innovativ-image img {
	max-height: 160px;
	margin: auto;
}

.innovativ-image img.cw-big {
	margin: auto;
}

.innovativ-image .innovativ-image-big {
	max-width: 300px;
	max-height: 250px;
	min-width: 300px;
	margin: auto;
}

.innovativ-image .innovativ-image-bg.innovativ-image-small {
	min-height: 262px;
    display: flex;
	justify-content: center;
	align-items: center;
}

.ix2-collection .innovativ-image-default-bg {
    background-color: #c5c5c5;
	min-height: 250px;
}

.ix2-collection .shadow {
	background-color: black;
}
.ix2-collection .cw-card-img-overlay-bottom {
	position: relative !important;
	bottom: 0 !important;
	top: 5px;
	left: 8px;
	right: 5px;
}
.ix2-collection .card-body {
	padding-top: 10px;
	padding-left: 10px;
}

.cw-text-small {
	font-size: 13px !important;
	max-width: 290px;
}

</style>
