<div class="cw-row">
  <div class="cw-col-lg-12">
    <div class="cw-text-block"><br>
      <span id="ixtheo_content"></span>
      <h1 class="cw-h1">Contact Persons</h1>
        <ul>
            <li><a target="_blank" href="https://uni-tuebingen.de/einrichtungen/universitaetsbibliothek/ueber-uns/ansprechpartner/fachreferenten-wissenschaftlicher-dienst/fassnacht/">Dr. Martin Faßnacht</a> (Head) <a target="_blank" href="https://uni-tuebingen.de/einrichtungen/universitaetsbibliothek/formulare/kontakt/fassnacht/">Kontakt</a></li>
            <li><a target="_blank" href="https://uni-tuebingen.de/einrichtungen/universitaetsbibliothek/ueber-uns/ansprechpartner/fachreferenten-wissenschaftlicher-dienst/kim/">Timotheus Chang Whae Kim</a> (Deputy Head) <a target="_blank" href="http://www.ub.uni-tuebingen.de/formulare/kontakt/Kim.html">Kontakt</a></li>
            <li><a target="_blank" href="https://uni-tuebingen.de/einrichtungen/universitaetsbibliothek/ueber-uns/ansprechpartner/fachreferenten-wissenschaftlicher-dienst/brenner/">Dr. Janca Brenner</a> (subject librarian) <a target="_blank" href="mailto:janca.brenner@uni-tuebingen.de">Kontakt</a></li>
            <li><a target="_blank" href="https://uni-tuebingen.de/einrichtungen/universitaetsbibliothek/ueber-uns/ansprechpartner/fachreferenten-wissenschaftlicher-dienst/ehlers/">Dr. Corinna Ehlers</a> (subject librarian) <a target="_blank" href="mailto:corinna.ehlers@uni-tuebingen.de">Kontakt</a></li>
        </ul>
        <p>For general inquiries please contact: <a target="_blank" href="mailto:ixtheo@ub.uni-tuebingen.de">ixtheo@ub.uni-tuebingen.de</a></p>
    </div>
  </div>
</div>