<div class="ixtheo50 container-fluid">
      <section class="cw-p-3 col-md-12 bl1">
        <div class="container">
          <!--<h1 class="cw-h1">IxTheo 50</h1>-->
          <h4 style="font-size: 15px; margin-bottom:3px; margin-top:35px;">Wissenschaftliche Tagung und Festakt IxTheo (Februar 2026)</h4>
          <h1 class="cw-h1" style="font-size: 20px;">Theologische Forschung, Lehre und Infrastruktur im Kontext von Digitalisierung und KI</h1><br />

          <p>Datum: Donnerstag 12. Februar 2026, 12:15 Uhr – Freitag, 13. Februar 2026, 13:00 Uhr<br />
          Ort: Alte Aula, Münzgasse 30, 72070 Tübingen<br />
          <b>Wir bitten um Anmeldung unter: <a target="_blank" href="https://pretix.eu/ixtheo-tagung/3rswp/">https://pretix.eu/ixtheo-tagung/3rswp/</a></b><br />
          Eine Online-Teilnahme an den Vorträgen und den Lightning Talks ist möglich. Bitte melden Sie sich auch hierzu an.<br />
          Bei Fragen wenden Sie sich bitte an: <a href="mailto:theologie@ub.uni-tuebingen.de">theologie@ub.uni-tuebingen.de</a></p>

          <p>Digitalisierung stellt theologische Forschung und Lehre vor vielfältige Herausforderungen: von der Datenanalyse mit Methoden der Digital Humanities über den Umgang mit Künstlicher Intelligenz bis zur Publikation in Open Access und der Vermittlung in modernen Kommunikationsformaten. Diesen Fragen widmet sich die Tagung, die vom Evangelisch-Theologischen Fakultätentag in Zusammenarbeit mit dem Katholisch-Theologischen Fakultätentag, der Konferenz der Institute für Evangelische Theologie, dem TheoLab-Forschungsverbund Computational Theology und dem Fachinformationsdienst Theologie an der Universitätsbibliothek Tübingen organisiert wird.</p>
          <p>Die Tagung ist verbunden mit einem Festakt zum 50jährigen Jubiläum des <i>Index Theologicus</i>, der vom Fachinformationsdienst Theologie erarbeitet und von der Universitätsbibliothek Tübingen zusammen mit den beiden Tübinger Theologischen Fakultäten herausgegeben wird.
             Aus dem 1975 begründeten Zeitschrifteninhaltsdienst hat sich eine moderne Open-Access-Bibliographie entwickelt, die neben Aufsätzen auch Monographien, Rezensionen und vielfältige digitale Publikationsformen (Forschungsdaten, Podcasts, Datenbanken u.a.) nachweist. Mit aktuell über 4,7 Mio. Einträgen, viele davon mit Link zum digitalen Volltext, ist sie ein zentrales Instrument im Forschungsalltag der internationalen theologischen Fachcommunity.</p>
          <p>Im Rahmen von Tagung und Festakt wird die Frage nach Perspektiven für Theologie im 21. Jahrhundert gestellt: Wie müssen sich Forschung, Lehre und Informationsinfrastruktur im Kontext digitaler Transformationen weiterentwickeln? Wie kann die reflektierte Anwendung digitaler oder KI-gestützter Methoden in der Praxis aussehen?</p>
        </div>
      </section>

      <section class="cw-p-3 col-md-12 cw-bg-gray-100 bl2">
        <div class="container">
          <h3 class="cw-mt-6"><b>Programm</b></h3>
          <div class="col-md-12 row">
            <div class="col-md-6 row">
              <table class="table table-striped">
                <thead>
                  <tr>
                    <th colspan="2" style="color:#2c6f94;">Donnerstag, 12. Februar 2026</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td class="uhr-td">ab 12:15 Uhr</td>
                    <td>Ankommen und Kaffee</td>
                  </tr>
                  <tr>
                    <td>13:00 Uhr</td>
                    <td>Begrüßung</td>
                  </tr>
                  <tr>
                    <td>13:30 Uhr</td>
                    <td>
                      <i>Welche Infrastrukturen braucht die Theologie im 21. Jahrhundert?</i><br />Prof. Dr. Thomas Stäcker / Dr. Annette von Stockhausen<br />
                      <a href="/Content/digi2026#details">Details</a>
                    </td>
                  </tr>
                  <tr>
                    <td>14:30 Uhr</td>
                    <td>
                      <i>Digitalisierung in der theologischen Forschung</i><br />PD Dr. Friederike van Oorschot / Prof. Dr. Thomas Schlag<br />
                      <a href="/Content/digi2026#details">Details</a>
                    </td>
                  </tr>
                  <tr>
                    <td>15:30 Uhr</td>
                    <td>Kaffeepause</td>
                  </tr>
                  <tr>
                    <td>16:00 Uhr</td>
                    <td>
                      Hands-on-Workshops<br />
                      <a href="/Content/digi2026#details">Details</a>
                    </td>
                  </tr>
                  <tr>
                    <td>ca. 17:00 Uhr</td>
                    <td>Pause</td>
                  </tr>
                  <tr>
                    <td>18:30 Uhr</td>
                    <td>Festakt: <i>50 Jahre Index Theologicus</i> <br />Festvortrag: Prof. Dr. Marianne Heimbach-Steins<br />Grußworte</td>
                  </tr>
                  <tr>
                    <td>20:00 Uhr</td>
                    <td>Empfang</td>
                  </tr>
                  <tr>
                    <td>21:15 Uhr</td>
                    <td>Nachtkonzert (Stiftskirche Tübingen)</td>
                  </tr>
                </tbody>
              </table>
            </div>
            <div class="col-md-6">
              <table class="table table-striped">
                <thead>
                  <tr>
                    <th colspan="2" style="color:#2c6f94;">Freitag, 13. Februar 2026</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td class="uhr-td">9:00 Uhr</td>
                    <td>
                      <i>Digitalisierung in der theologischen Lehre</i><br />Prof. Dr. Sabrina Müller / Prof. Dr. Johannes Heger<br />
                      <a href="/Content/digi2026#details">Details</a>
                    </td>
                  </tr>
                  <tr>
                    <td>10:00 Uhr</td>
                    <td>Kaffeepause</td>
                  </tr>
                  <tr>
                    <td>10:30 Uhr</td>
                    <td>
                      <i>Lightning Talks</i><br />
                      <a href="/Content/digi2026#talks">Call for Lightning Talks</a>
                    </td>
                  </tr>
                  <tr>
                    <td>12:30 Uhr</td>
                    <td><i>Abschlusspanel</i></td>
                  </tr>
                  <tr>
                    <td>13:00 Uhr</td>
                    <td>Ende der Tagung</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>
        <span id="talks">&nbsp;</span>
      </section>

      <section class="cw-p-3 cw-pb-6 col-md-12 bl3">
        <div class="container">
          <h3 class="cw-mt-6"><b>Call for Lightning Talks</b></h3>
          <p>Haben Sie ein spannendes Projekt im Bereich der Digitalen oder Computationellen Theologie, der Digital Humanities oder zu computer- bzw. KI-gestützten und datengetriebenen Methoden in der Theologie oder der religionsbezogenen Forschung?</p>
          <p>Dann nutzen Sie die Gelegenheit, Ihre Ideen und Forschungsergebnisse in einem kurzen <b>Lightning Talk (5–8 Minuten)</b> vorzustellen!</p>

          <p>Die Session bietet Raum für:</p>
          <ul>
            <li>Projektvorstellungen: Laufende oder abgeschlossene Forschungsprojekte</li>
            <li>Methodische Innovationen: Neue Ansätze, Tools und Workflows für digitale und KI-gestützte Forschung</li>
            <li>Anwendungsbeispiele: Digitale Kompetenzen und KI im  Theologiestudium und in der Forschungspraxis </li>
            <li>Vernetzung: Hinweise auf bestehende Netzwerke, Ideen für gemeinsame Projekte oder für kollaborative Arbeit</li>
          </ul>

          <p>Im Anschluss an jeden Talk gibt es kurze Fragen aus dem Publikum, um den Austausch anzuregen.</p>
          <p><b>Wir bitten um Vorschläge an: <a href="mailto:theologie@ub.uni-tuebingen.de">theologie@ub.uni-tuebingen.de</a> bis 9. Januar 2026</b>
          <p>Bringen Sie Ihre Ideen ein – gestalten Sie die Zukunft theologischer Forschung mit!</p>
          <span id="details">&nbsp;</span>
        </div>
      </section>

      <section class="cw-p-3 col-md-12 cw-bg-gray-100 bl2">
        <div class="container ">
            <h3 class="cw-mt-6"><b>Abstracts der Vorträge</b></h3>
            <p class="detail-title">Thomas Stäcker</p>
            <p class="detail-des"><i>Welche Infrastrukturen braucht die Theologie im 21. Jahrhundert? Die Perspektive eines Bibliothekars</i></p>
            <p>Bibliotheken haben von alters her Wissenschaft mit Literatur versorgt. Ist diese Aufgabe im Zeitalter von Open Access und KI nicht obsolet? Theologische Quellen und Forschungsliteratur sind frei im Netz verfügbar, werden zuverlässig von Suchmaschinen gefunden und mit KI mundgerecht aufbereitet und ausgewertet. Der Beitrag versucht in einer Welt des informellen Überflusses eine Neubestimmung der Aufgabe der Bibliothek. Dabei spielen Fragen des Open Access Publizierens, der Qualitätssicherung, der Datensouveränität, data literacy und des Datenschutzes eine zentrale Rolle.</p>

            <p class="detail-title">Annette von Stockhausen</p>
            <p class="detail-des"><i>Welche Infrastrukturen braucht die Theologie im 21. Jahrhundert? Die Perspektive einer Forscherin</i></p>
            <p>Abstract: Die Theologie steht im 21. Jahrhundert vor der Herausforderung, sich an die gerade in den letzten Jahren massiv gewachsenen Möglichkeiten und Anforderungen der digitalen Welt anzupassen. Aus der Perspektive einer textbasiert-historisch arbeitenden Forscherin werde ich fünf Thesen zur Diskussion stellen, auf welchen Infrastrukturen eine zukunftsfähige Theologie über den Verlauf des gesamten Forschungsprozesses hinweg basieren sollte. Der Kerngedanke wird sein, dass die traditionellen Infrastrukturen (Bibliotheken, Publikationsformen, Verlagswesen) weiterentwickelt werden müssen. Damit werden in manchen Fällen auch radikale Veränderungen (auch jenseits der Infrastrukturen) einhergehen, zugleich aber neue Impulse und Forschungsperspektiven ermöglicht.</p>

            <p class="detail-title">Thomas Schlag / Frederike van Oorschot</p>
            <p class="detail-des"><i>Theologische Forschung zwischen Digital Religion(s) und Digital Theology</i></p>
            <p>Abstract: Präsentiert werden in diesem Impulsvortrag Zielsetzungen, Struktur und bisherige Ergebnisse des interdisziplinären Zürcher Universitären Forschungsschwerpunkt „Digital Religion(s). Communication, Interaction and Transformation“ (2021-2032). Dabei wird ein besonderer Fokus auf die Frage gelegt, in welchem Sinn und in welcher inhaltlichen und methodischen Dimensionierung (praktisch-)theologische Forschung auf spezifische und kollaborative Weise zu den Forschungen im Feld digitaler Kommunikationspraktiken beiträgt. Ein weiterer Fokus liegt auf dem Zusammenspiel der Debatten Digital Religion(s) und Digital Theology, das am Beispiel exemplarischer Denkfiguren der Systematischen Theologie diskutiert wird.</p>

            <p class="detail-title">Sabrina Müller</p>
            <p class="detail-des"><i>Theologische Lehre reloaded: Zwischen Hörsaal, Zoom und KI</i></p>
            <p>Digitale Transformation und KI verändern die theologische Lehre grundlegend. Zwischen Hörsaal, Zoom und ChatGPT verschieben sich Lernräume, Rollenverständnisse und Bewertungspraktiken. Der Beitrag fragt, wie theologische Lehre im digitalen Zeitalter Bildungsziele neu justieren kann: Welche Formen von Präsenz und Resonanz entstehen im Zusammenspiel von Raum, Online-Lehre und KI? Anknüpfend an das „AAA“-Modell (Awareness, Agency, Action) wird eine theologische Didaktik entworfen, die digitale Technologien nicht nur reguliert, sondern kritisch, kreativ und gemeinschaftsbildend integriert.</p>

            <p class="detail-title">Johannes Heger</p>
            <p class="detail-des"><i>„Theologische Lehre trotz, angesichts oder mit Künstlicher Intelligenz? – Bausteine zur Positionierung und Orientierung“</i></p>

            <h3 style="margin-top: 45px; margin-bottom:25px;"><b>Abstracts der Hands-on Sessions</b></h3>
            <p class="detail-des"><i>Andrea Beyer</i></p>
            <p>KI-Chatbots können gut übersetzen - auch lateinische und altgriechische Texte. Sie können Fragen zu diesen Texten beantworten, die Texte zusammenfassen und bieten auch Interpretationen. Wozu also noch mühsam eine gern als tot bezeichnete Sprache wie Latein erwerben? Dieser Frage gehen wir gemeinsam an einem Beispiel (Passio und Acta Perpetuae) nach.</p>
            <p>Der Workshop wird eingeleitet durch einen kurzen Impuls zur Leistungsfähigkeit aktueller KI-Systeme, ihren Einsatzmöglichkeiten beim Lernen, Lehren und Prüfen sowie den möglichen Problemen ihrer Verwendung insbesondere im Kontext historischer Texte (Bias). Anschließend testen wir an einem Textauszug die Funktionalität verschiedener Large Language Models und diskutieren, warum der häufig vorgebrachte Vergleich von KI mit einem Taschenrechner viel zu kurz greift.</p>
            <p>Die Teilnehmer und Teilnehmerinnen sollten bitte einen Laptop mit WLAN-Zugang und einen (fake) Google-Account mitbringen.</p>

            <p class="detail-title">Philipp Pilhofer</p>
            <p class="detail-des"><i>Digitale Karten der Alten Welt</i></p>
            <p>In diesem Workshop sollen die Potentiale digitaler Kartographie für christentumsgeschichtliche Forschung und Lehre gemeinsam erprobt und diskutiert werden. Nach einem Überblick zu existierenden Kartenprojekten und einer kleinen Einführung zu den Potentialen wird es Zeit zu eigenen Erkundungen geben. Auf dieser Basis soll ein abschließender Austausch stattfinden und Raum für Rückfragen sein. Zum Mitmachen sollte ein internetfähiger Laptop/Tablet mitgebracht werden.</p>
        </div>
      </section>

      <section class="cw-p-3 col-md-12 bl1">
        <div class="container">
          <h1 class="cw-h1" style="margin-top:25px; margin-bottom:-5px; font-size: 20px;">Tagung und Festakt werden ermöglicht durch:</h1><br />
          <p>Evangelisch-Theologischer Fakultätentag<br />
            Katholisch-Theologischer Fakultätentag<br />
            Konferenz der Institute für Evangelische Theologie<br />
            TheoLab-Forschungsverbund Computational Theology<br />
            Fachinformationsdienst Theologie (Universitätsbibliothek Tübingen)<br />
            Evangelisch-Theologische Fakultät Tübingen<br />
            Katholisch-Theologische Fakultät Tübingen<br />
            Evangelische Kirche in Deutschland (EKD)
          <p>
        </div>
      </section>
</div>

<style>
  .detail-title {
    padding-bottom: 0;
    margin-top: 25px;
    margin-bottom: 0;
  }
  .detail-des {
    padding-bottom: 0;
    margin-top: 5px;
    margin-bottom: 5px;
  }
  .uhr-td {
    width: 115px;
  }
  .iu {
    text-decoration: underline;
  }
</style>
