<div class="cw-row">
    <div class="cw-py-5">
        <h1 class="cw-h1">Suchen und Browsen</h1>
        <p>IxTheo enthält mehr als 4,5 Mio. Titel in vielen verschiedenen Sprachen. Ca. 25.000 neu erschienene Titel kommen jährlich hinzu. Um in dieser großen Menge von Informationen eine präzise Suche nach den gewünschten Ressourcen zu ermöglichen, stehen verschiedene Features zur Verfügung. Neben speziellen Suchfunktionen für Bibelstellen, Stellen aus dem Kirchenrecht und historische Zeiträume sind auch Filtern nach Sachgebieten oder Browsen unter verschiedenen Aspekten möglich.</p>
    </div>

    <!-- one block -->
    <div class="col-md-4 ix-panel-news">
        <div class="panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    Bibelstellensuche
                </h4>
            </div>
            <div class="panel-collapse">
                <div class="panel-body">
                    <input type="checkbox" class="read-more-state" id="post-1" />
                    <div class="read-more-wrap cw-wrap-smoll">
                        <p>Ein besonderes Feature des Index Theologicus (IxTheo) ist die Bibelstellensuche. Sie ermöglicht eine gezielte Recherche nach Literatur zu Bibelstellen (vom Vers bis zur ganzen Perikope), auch wenn diese nicht im Titel der Publikation erwähnt sind</p>
                        <div class="read-more-target">
                            <p>Um die Bibelstellensuche zu aktivieren, muss rechts neben dem Suchschlitz der Suchaspekt „Bibelstellen“ ausgewählt werden.</p>
                            <p>Bibelstellen können in der international üblichen Form und mit den bekannten Abkürzungen eingegeben werden. Daneben können Abkürzungen verwendet werden, die im Englischen, Französischen, Italienischen und Spanischen gebräuchlich sind, ebenso Varianten sowie die von Nestle-Aland und der Vulgata genutzten Formen.</p>
                            <p>In wenigen Fällen gibt es Ambiguitäten bei den Abkürzungen in den verschiedenen Sprachen. So wird z.B. die Abkürzung „es“ im Französischen für das Jesajabuch, im Italienischen aber für das Buch Exodus verwendet. In diesen Fällen musste entschieden werden, welche Abkürzungen zugelassen werden, damit keine uneindeutigen Treffer erzeugt werden. Die Liste der gültigen Abkürzungen für die Bibelstellensuche finden Sie <a target="_blank" href="https://ixtheo.de/docs/Bible_abbreviation.pdf">hier</a>.</p>
                            <p>Geben Sie die gesuchte Stelle in folgender Form ein: </p>
                            <p>Abkürzung_des_Bibelbuches Kapitel, Versangaben. Einzelverse innerhalb des Kapitels können durch Punkte getrennt werden.</p>
                            <p>Beispiele:</p>

                            <ul>
                              <li>Joh 5,1-20 oder Jn 5,1-20</li>
                              <li>1Kor 10 oder 1 Kor 10 oder 1 K 10</li>
                              <li>Röm 14,1-15,13 oder Rm 14,1-15,13</li>
                              <li>Gen 1,1-3.4-5.7.9</li>
                            </ul>

                            <p>Sie erhalten als Treffer nicht nur die Einträge, bei denen genau diese Bibelstelle angegeben ist, sondern auch alle Einträge, bei denen es eine Überschneidung zur gesuchten Stelle gibt:</p>

                            <ul class="ix2-content-ul1">
                                <li>Die eingegebene Stelle stimmt genau mit der gefundenen Stelle überein.
                                    Beispiel: Suche nach Mk 5,25-34 findet Mk 5,25-34.</li>

                                <li>Die gesuchte Stelle ist in der gefundenen Stelle enthalten.
                                    Beispiel: Suche nach Mk 5,25-34 findet auch Treffer für Mk 5,24-34 oder für das gesamte Kapitel Mk 5.</li>

                                <li>Die gefundene Stelle ist in der gesuchten Stelle enthalten.
                                    Beispiel: Suche nach Lk 2,22-35 findet auch Treffer für Lk 2,29-32.</li>

                                <li>Die gefundene und die gesuchte Stelle überschneiden sich.
                                    Beispiel: Suche nach Gen 1,1-2 findet auch Treffer für Gen 1,2-5.</li>

                                <li>Die gefundene Stelle ist mit einem Schlagwort verbunden, das eine mit der Suche übereinstimmende oder sich damit überschneidende Bibelstelle bezeichnet.
                                    Beispiel: Bei einer Suche nach Mk 5,25-34 werden auch alle Titel gefunden, die mit dem Datensatz „Blutflüssige Frau“ verbunden sind. Diesem sind die synoptischen Stellen Mk 5,25-34 sowie Mt 9,20-22 und Lk 8,43-48 zugeordnet.</li>
                            </ul>

                            <p>Die Treffer werden nach ihrer Nähe zur gesuchten Stelle sortiert: Exakte Treffer erscheinen als erste; die übrigen Treffer werden danach geordnet, wie gut sie zum gesuchten Bereich passen. So erscheinen z.B. bei einer Suche nach Mk 5,25-34 die Treffer für Mk 5,21-43 vor Treffern für das gesamte Kapitel Mk 5.</p>
                            <p>Damit Sie die Relevanz der Treffer einschätzen können, werden die Stellenangaben in der Kurztitelliste direkt angezeigt.</p>

                            <a class="thumbnail" href="#" data-image-id="" data-toggle="modal" data-title="" data-caption="" data-image="/themes/ixtheo2/images/content_img/block_1_img_1.jpg" data-target="#image-gallery">
                                <img class="img-responsive" src="/themes/ixtheo2/images/content_img/block_1_img_1.jpg" alt="<?=$this->translate('Screenshot: A bibliographic record in IxTheo, with a reference to a Bible passage below');?>">
                            </a>

                            <p>Achtung: Es ist nicht ausgeschlossen, dass es Titel gibt, die nicht mit den Normsätzen der Bibelstellen verknüpft sind. Deswegen kann zusätzlich eine Suche nach einer Bibelstelle mit dem Suchaspekt „Alle Felder“ erfolgreich sein. Die Vorteile der IxTheo-Bibelstellensuche sind dann aber nicht gegeben.</p>
                            <p>Bei Interesse an der technischen Umsetzung der Suche finden Sie weiterführende Informationen unter: <a target="_blank" href="https://github.com/ubtue/tuefind/wiki/Bereichssuche-Technischer-%C3%9Cberblick">https://github.com/ubtue/tuefind/wiki/Bereichssuche-Technischer-%C3%9Cberblick</a></p>
                        </div>
                    </div>
                    <label for="post-1" class="read-more-trigger"></label>
                </div>
            </div>
        </div>
    </div>
    <!-- end one block -->

    <!-- one block -->
    <div class="col-md-4 ix-panel-news">
        <div class="panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    Suche nach Zeiträumen
                </h4>
            </div>
            <div class="panel-collapse">
                <div class="panel-body">
                    <input type="checkbox" class="read-more-state" id="post-3" />
                    <div class="read-more-wrap cw-wrap-smoll">
                        <p>Die Suche nach Zeiträumen ermöglicht die gezielte Recherche nach Publikationen, die einen bestimmten Zeitraum behandeln. Es kann nach Jahreszahlen und Zeiträumen gesucht werden.</p>
                        <div class="read-more-target">
                        <p>Um die Suche nach Zeiträumen zu aktivieren, muss rechts neben dem Suchschlitz die Option „Zeitbereiche“ ausgewählt werden.</p>
                        <p>Bei Jahreszahlen vor der Zeitenwende muss ein „v“ hinzugefügt werden. Eingegebene Jahreszahlen ohne Zusatz werden automatisch als „nach der Zeitenwende“ interpretiert.</p>
                        <p>Beispiele:</p>
                            • Suche eines bestimmten Jahrs nach der Zeitenwende: Eingabe der Jahreszahl (z.B. 1970) 
                            • Suche eines Zeitraums nach der Zeitenwende: Eingabe beider Zahlen ohne Leerstellen (z.B. 1526-1530)
                            • Suche nach einem Jahr vor der Zeitenwende: Eingabe des Kürzels v vor dem Datum (z.B. v70)
                            • Suche eines Zeitraums vor der Zeitenwende: Eingabe des Kürzels v vor beiden Zahlen (z.B. v70-v60)
                            • Suche über die Zeitenwende hinweg: Kombination dieser Optionen (z.B. v566-100)
                            
                        <p>Sie erhalten als Treffer nicht nur die Einträge, bei denen genau dieser Zeitraum angegeben ist, sondern auch alle Einträge, bei denen es eine Überschneidung zu dem gesuchten Zeitraum gibt:</p>
                            
                            • Der eingegebene Zeitraum stimmt genau mit dem gefundenen überein.
                              Beispiel: Suche nach 1648 findet 1648.

                            • Der gesuchte Zeitraum ist in dem gefundenen Zeitraum enthalten.
                              Beispiel: Suche nach v70 findet auch v76-v60.

                            • Der gefundene Zeitraum ist in dem gesuchten Zeitraum enthalten.
                              Beispiel: Suche nach 1800-1850 findet auch 1800-1848.

                            • Der gefundene und der gesuchte Zeitraum überschneiden sich.
                              Beispiel: Suche nach 1517-1522 findet auch 1520-1525.

                            • Außerdem werden Datensätze gefunden, die mit einem Schlagwort verknüpft sind, das einen zur Suche passenden Zeitraum bezeichnet.
                              Beispiel: Suche nach 30-100 findet auch Treffer mit dem Schlagwort „Urchristentum“.
                        
                        <p>Die Treffer werden nach Nähe zur gesuchten Stelle sortiert. Exakte Treffer stehen ganz oben; die übrigen Treffer werden danach sortiert, wie gut sie zu dem gesuchten Zeitraum passen.</p>
                        <p>Damit Sie die Relevanz der Treffer einschätzen können, werden die Stellenangaben in der Kurztitelliste direkt angezeigt.</p>

                        <a class="thumbnail" href="#" data-image-id="" data-toggle="modal" data-title="" data-caption="" data-image="/themes/ixtheo2/images/content_img/block_3_img_1.jpg" data-target="#image-gallery">
                            <img class="img-responsive" src="/themes/ixtheo2/images/content_img/block_3_img_1.jpg" alt="<?=$this->translate('Screenshot: A bibliographic record in IxTheo, with a reference to a time period below');?>">
                        </a>

                        <p>Technisch funktioniert die Zeitraumsuche analog zur Bibelstellensuche. Bei Interesse finden <br />  Sie nähere Informationen <a target="_blank" href="https://github.com/ubtue/tuefind/wiki/Times">https://github.com/ubtue/tuefind/wiki/Times</a></p>
                        </div>
                    </div>
                    <label for="post-3" class="read-more-trigger"></label>
                </div>
            </div>
        </div>
    </div>
    <!-- end one block -->


    <!-- one block -->
    <div class="col-md-4 ix-panel-news">
        <div class="panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    Suche nach Kirchenrechtsquellen
                </h4>
            </div>
            <div class="panel-collapse">
                <div class="panel-body">
                    <input type="checkbox" class="read-more-state" id="post-2" />
                    <div class="read-more-wrap cw-wrap-smoll">
                        <p>Die Suche nach Kirchenrechtsquellen ist ebenfalls ein spezielles Feature von IxTheo. Sie ermöglicht die gezielte Recherche nach Literatur zu Stellen im CIC/CCEO. Es kann nach einem ganzen Codex, Teilen eines Codex, einzelnen Canones oder Paragraphen gesucht werden.</p>
                        <div class="read-more-target">
                            <p>Um die Suche zu aktivieren, muss rechts neben dem Suchschlitz „Codexsuche“ ausgewählt werden.</p>
                            <p>Folgende Codices sind suchbar:</p>

                            <ul>
                                <li>CIC17 = Codex Iuris Canonici 1917</li>
                                <li>CIC83 = Codex Iuris Canonici 1983</li>
                                <li>CCEO = Codex Canonum Ecclesiarum Orientalium</li>
                            </ul> 

                            <p>Geben Sie die Stelle in folgender Form an:</p>
                            <p>Abkürzung der Quelle - Bereich oder Paragraph</p>
                            <p>Beispiele:</p>

                            <ul>
                                <li>CIC17</li>
                                <li>CIC83 951</li>
                                <li>CCEO 1087,2</li>
                                <li>CIC83 790,1-2</li>
                            </ul> 

                            <p>Sie erhalten als Treffer nicht nur die Einträge, bei denen genau diese Stelle angegeben ist, sondern auch alle Einträge, bei denen es eine Überschneidung zur gesuchten Stelle gibt:</p>

                            <ul>
                                <li>Die gesuchte Stelle stimmt genau mit der gefundenen Stelle überein.<br />
                                    Beispiel: Suche nach CIC83 951 findet §951 im Codex Iuris Canonici von 1983.</li>

                                <li>Die gesuchte Stelle ist in der gefundenen Stelle enthalten.<br />
                                    Beispiel: Suche nach CIC83 790,2 findet auch CIC83 790,1-3.</li>

                                <li>Die eingegebene Stelle ist Teil des gefundenen Canon.<br />
                                    Beispiel: Suche nach CCEO 1087,2 findet auch CCEO 1087.</li>

                                <li>Die gefundene Stelle ist in der gesuchten Stelle enthalten.<br />
                                    Beispiel: Suche nach CCEO 1-322 findet auch CCEO 187.</li>
                            </ul>

                            <p>Die Treffer werden nach Nähe zur gesuchten Stelle sortiert. Exakte Treffer stehen ganz oben; die übrigen Treffer werden danach sortiert, wie gut sie zum gesuchten Abschnitt passen.</p>
                            <p>Damit Sie die Relevanz der Treffer einschätzen können, werden die Stellenangaben in der Kurztitelliste direkt angezeigt.</p>

                            <a class="thumbnail" href="#" data-image-id="" data-toggle="modal" data-title="" data-caption="" data-image="/themes/ixtheo2/images/content_img/block_2_img_1.jpg" data-target="#image-gallery">
                                <img class="img-responsive" src="/themes/ixtheo2/images/content_img/block_2_img_1.jpg" alt="<?=$this->translate('Screenshot: A bibliographic record in IxTheo, with a reference to a passage from canon law below');?>">
                            </a>

                            <p>Technisch funktioniert die Kirchenrechtssuche analog zur Bibelstellensuche. Bei Interesse finden Sie nähere Informationen hier: <a target="_blank" href="https://github.com/ubtue/tuefind/wiki/Codices">https://github.com/ubtue/tuefind/wiki/Codices</a></p>
                        </div>
                    </div>
                    <label for="post-2" class="read-more-trigger"></label>
                </div>
            </div>
        </div>
    </div>
    <!-- end one block -->
 
    <!-- one block -->
    <div class="col-md-6 ix-panel-news" id="klassifikation">
        <div class="panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    IxTheo-Klassifikation
                </h4>
            </div>
            <div class="panel-collapse">
                <div class="panel-body">
                    <input type="checkbox" class="read-more-state" id="post-4" />
                    <div class="read-more-wrap">
                        <p>Im IxTheo werden zahlreiche Publikationen nach Fachgebieten erschlossen und mit einer entsprechenden Klassifikation versehen (z.B. HC: Neues Testament, NBP: Systematische Theologie, Teilgebiet Sakramentslehre). Dies ermöglicht eine gezielte Eingrenzung der Suche auf bestimmte Fachgebiete</p>
                        <div class="read-more-target">
                            <p>Einen Überblick über die IxTheo-Klassen finden Sie hier: <a href="<?=$this->url('content-page', ['page' => 'IxTheoClassification']) ?>#content">IxTheoClassification</a></p>
                            <p>Unter dem Button "Erweiterte Suche" finden sich die einzelnen Klassen der IxTheo-Klassifikation. Durch Anklicken können Sie eine entsprechende Klasse auswählen. Mehrere Klassen können als Block durch das Halten der Umstell-Taste beim Anklicken markiert werden. Durch das Halten der „command“-Taste (Apple) oder der „Strg-Taste“ (Windows) können beim Anklicken mehrere Klassen gleichzeitig markiert werden.</p>
                            <p>Durch Klick auf „Suche“ starten Sie eine gezielte Suche nach den ausgewählten IxTheo-Klassen.</p>

                            <a class="thumbnail" href="#" data-image-id="" data-toggle="modal" data-title="" data-caption="" data-image="/themes/ixtheo2/images/content_img/block_4_img_1.jpg" data-target="#image-gallery">
                                <img class="img-responsive" style="width: 150px;" src="/themes/ixtheo2/images/content_img/block_4_img_1.jpg" alt="<?=$this->translate('Screenshot: list from which IxTheo classifications can be selected when doing an advanced search');?>">
                            </a>
                        </div>
                    </div>
                    <label for="post-4" class="read-more-trigger"></label>
                </div>
            </div>
        </div>
    </div>
    <!-- end one block -->
    <!-- one block -->
    <div class="col-md-6 ix-panel-news">
        <div class="panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    Verbale Suchbegriffe
                </h4>
            </div>
            <div class="panel-collapse">
                <div class="panel-body">
                    <input type="checkbox" class="read-more-state" id="post-5" />
                    <div class="read-more-wrap cw-wrap-long-smoll">
                        <p>Zahlreiche Titel im IxTheo sind mit Schlagwörtern und Keywords erschlossen. Diese können ebenfalls gezielt durchsucht werden.</p>
                        <div class="read-more-target">
                            <p>Tippen Sie den Suchbegriff in den Suchschlitz und belassen Sie den Suchaspekt „Alle Felder“. Der eingegebene Begriff wird dann in allen Suchfeldern gesucht.</p>

                            <p>Für eine gezielte inhaltliche Suche ist die Auswahl des Suchaspektes „Schlagwort“ nützlich. Hier werden intellektuell vergebene Schlagwörter und Schlagwortfolgen durchsucht.</p>

                            <a class="thumbnail" href="#" data-image-id="" data-toggle="modal" data-title="" data-caption="" data-image="/themes/ixtheo2/images/content_img/block_5_img_1.jpg" data-target="#image-gallery">
                                <img class="img-responsive" src="/themes/ixtheo2/images/content_img/block_5_img_1.jpg" alt="<?=$this->translate('Screenshot: search bar of IxTheo with a dropdown list to choose the search category');?>">
                            </a>

                        </div>
                    </div>
                    <label for="post-5" class="read-more-trigger"></label>
                </div>
            </div>
        </div>
    </div>
    <!-- end one block -->
    <!-- one block -->
    <div class="col-md-4 ix-panel-news" id="browsing">
        <div class="panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    IxTheo Themen-Browsing
                </h4>
            </div>
            <div class="panel-collapse">
                <div class="panel-body">
                    <input type="checkbox" class="read-more-state" id="post-6" />
                    <div class="read-more-wrap">
                        <p>Das IxTheo Themen-Browsing ermöglicht Ihnen, sich einen Überblick über die Kontexte zu verschaffen, in denen ein bestimmtes Schlagwort vorkommt.
                        Sie finden den Browsing-Modus durch Klick auf „Browsen“ unterhalb des Suchschlitzes. Wählen Sie „Thema browsen“.
                        </p>
                        <div class="read-more-target">

                        <p>&nbsp;</p>

                        <a class="thumbnail" href="#" data-image-id="" data-toggle="modal" data-title="" data-caption="" data-image="/themes/ixtheo2/images/content_img/block_6_img_1.jpg" data-target="#image-gallery">
                            <img class="img-responsive" src="/themes/ixtheo2/images/content_img/block_6_img_1.jpg" alt="<?=$this->translate('Screenshot: dropdown menu for choosing the browsing options “Browse by Subject”, “Browse the Catalog” or “Browse alphabetically” below the search bar');?>">
                        </a>

                        <p>Es öffnet sich ein weiterer Suchschlitz, in den Sie Ihren Suchbegriff eingeben können. Er dient als Startpunkt für das benutzergesteuerte Browsen.</p>
                        <p>Beispiel 1: Geben Sie den Begriff „Gott“ ein. Es wird eine Liste mit Schlagwortfolgen angezeigt, in denen der Begriff „Gott“ vorkommt.</p>
                        <p>Beispiel 2: Geben Sie die Begriffe „Gott“ und „Bibel“ ein. Es wird eine Liste mit Schlagwortfolgen angezeigt, in denen die Begriffe „Gott“ und „Bibel“ vorkommen.</p>

                        <a class="thumbnail" href="#" data-image-id="" data-toggle="modal" data-title="" data-caption="" data-image="/themes/ixtheo2/images/content_img/block_6_img_2.jpg" data-target="#image-gallery">
                            <img class="img-responsive" src="/themes/ixtheo2/images/content_img/block_6_img_2.jpg" alt="<?=$this->translate('Screenshot: a list of keyword combinations: “God / Bible”, “God / Bible / Apathy of God / Suffering”, “God / Bible / Apocalypticism / Time”, and others');?>">
                        </a>

                        <p>Durch Klick auf „Datensätze ansehen“ werden die mit dieser Schlagwortfolge verbundenen Titel angezeigt.</p>
                        <p>Sie können auch einzelne Begriffe aus der Liste der Schlagwortfolgen in den Suchschlitz übernehmen/ausschließen, indem Sie die Umstelltaste festhalten und gleichzeitig auf den Begriff klicken.</p>
                        <p>Wenn Sie rechts oben auf der Website die Sprache ändern, werden die Begriffe in der jeweiligen Sprache angezeigt, sofern sie in der Sprachkonkordanz vorhanden sind.</p>
                        </div>
                    </div>
                    <label for="post-6" class="read-more-trigger"></label>
                </div>
            </div>
        </div>
    </div>
    <!-- end one block -->
    <!-- one block -->
    <div class="col-md-4 ix-panel-news">
        <div class="panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    Katalogbrowsen
                </h4>
            </div>
            <div class="panel-collapse">
                <div class="panel-body">
                    <input type="checkbox" class="read-more-state" id="post-7" />
                    <div class="read-more-wrap">
                        <p>Die Katalog-Browsing-Funktion des IxTheo ermöglicht das Browsen in verschiedenen Feldern: Thema (Schlagwort), Verfasser, DDC-Klassifikation, IxTheo-Klassifikation und Verlag.
                        Sie finden den Browsing-Modus durch Klick auf „Browsen“ unterhalb des Suchschlitzes. Wählen Sie „Katalog browsen“.
                        </p>
                        <div class="read-more-target">
                            <p>&nbsp;</p>

                            <a class="thumbnail" href="#" data-image-id="" data-toggle="modal" data-title="" data-caption="" data-image="/themes/ixtheo2/images/content_img/block_7_img_1.jpg" data-target="#image-gallery">
                                <img class="img-responsive" src="/themes/ixtheo2/images/content_img/block_7_img_1.jpg" alt="<?=$this->translate('Screenshot: dropdown menu for choosing the browsing options “Browse by Subject”, “Browse the Catalog” or “Browse alphabetically” below the search bar');?>">
                            </a>
                            
                            <p>In einem weiteren Schritt kann das Browsing durch andere Felder eingeschränkt werden.</p>
                            <p>Beispiel: Wählen Sie „Verfasser“, dann „Nach IxTheo-Klassifikation“, dann „HB Altes Testament“ aus. Es wird eine Liste von Autor*innen angezeigt, die im Bereich des Alten Testaments publiziert haben, sortiert nach Häufigkeit ihrer Publikationen im IxTheo.</p>

                            <a class="thumbnail" href="#" data-image-id="" data-toggle="modal" data-title="" data-caption="" data-image="/themes/ixtheo2/images/content_img/block_7_img_2.jpg" data-target="#image-gallery">
                                <img class="img-responsive" src="/themes/ixtheo2/images/content_img/block_7_img_2.jpg" alt="<?=$this->translate('Screenshot: options to refine browsing results by selecting the categories “author”, “By IxTheo classification” and “HB Old Testament” in several menus ordered from left to right. On the right-hand side a list of authors who meet all the selected criteria is displayed');?>">
                            </a>

                        </div>
                    </div>
                    <label for="post-7" class="read-more-trigger"></label>
                </div>
            </div>
        </div>
    </div>
    <!-- end one block -->
    <!-- one block -->
    <div class="col-md-4 ix-panel-news">
        <div class="panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    Alphabetisch browsen
                </h4>
            </div>
            <div class="panel-collapse">
                <div class="panel-body">
                    <input type="checkbox" class="read-more-state" id="post-8" />
                    <div class="read-more-wrap">
                        <p>Die Funktion „Alphabetisch browsen“ ermöglicht Ihnen, in einer alphabetisch sortierten Liste von Themen, Verfasser*innen, Titeln oder Klassifikationen zu blättern.
                        Sie finden den Browsing-Modus durch Klick auf „Browsen“ unterhalb des Suchschlitzes. Wählen Sie „Alphabetisch browsen“.
                        </p>
                        <div class="read-more-target">
                            <p>&nbsp;</p>
                            
                            <a class="thumbnail" href="#" data-image-id="" data-toggle="modal" data-title="" data-caption="" data-image="/themes/ixtheo2/images/content_img/block_8_img_1.jpg" data-target="#image-gallery">
                                <img class="img-responsive" src="/themes/ixtheo2/images/content_img/block_8_img_1.jpg" alt="<?=$this->translate('Screenshot: dropdown menu for choosing the browsing options “Browse by Subject”, “Browse the Catalog” or “Browse alphabetically” below the search bar');?>">
                            </a>

                            <p>Nach der Auswahl des Browsing-Aspektes (möglich sind „Thema“, Verfasser, Titel und DDC-Klassifikation) geben Sie den Buchstaben ein, ab dem das Browsing starten soll.</p>
                            <p>Beispiel 1: Wählen Sie „Nach Verfasser“ und geben Sie ein: ab „Z“. Es werden dann alle Verfasser aufgelistet, die mit dem Buchstaben Z beginnen.</p>
                            <p>Beispiel 2: Wählen Sie „Nach Titel“ und geben Sie ein: ab „Tr“. Es werden dann alle Titel aufgelistet, die mit der Buchstabenfolge Tr beginnen.</p>
                          
                            <a class="thumbnail" href="#" data-image-id="" data-toggle="modal" data-title="" data-caption="" data-image="/themes/ixtheo2/images/content_img/block_8_img_2.jpg" data-target="#image-gallery">
                                <img class="img-responsive" src="/themes/ixtheo2/images/content_img/block_8_img_2.jpg" alt="<?=$this->translate('Screenshot: An alphabetical list of authors whose surname begins with the letter Z');?>">
                            </a>

                        </div>
                    </div>
                    <label for="post-8" class="read-more-trigger"></label>
                </div>
            </div>
        </div>
    </div>
    <!-- end one block -->
</div>

<style type="text/css">
    .ix-panel-news .read-more-wrap.cw-wrap-smoll {
        min-height: 180px;
    }
    .ix-panel-news .read-more-wrap.cw-wrap-long-smoll {
        min-height: 132px;
    }
    .ix2-content-ul1 {
        margin-bottom: 10px;
    }
    .ix2-content-ul1 li {
        margin: 10px 0;
    }
    .panel-default {
        margin-bottom: 20px;
        background-color: #fff;
        border: 1px solid #ddd;
        border-radius: 4px;
        -webkit-box-shadow: 0 1px 1px rgba(0,0,0,.05);
        box-shadow: 0 1px 1px rgba(0,0,0,.05);
    } 
    .panel-heading {
        padding: 10px 15px;
        border-bottom: 1px solid transparent;
        border-top-left-radius: 3px;
        border-top-right-radius: 3px;
    }
    .panel-collapse p {
        text-align: justify !important;
    }
</style>

