<div class="cw-row">
  <div class="cw-col-lg-12 cw-ml-lg-4">
      <div class="cw-text-block"><br />
        <h1 class="cw-h1">Interlibrary Loan</h1>
        <p>If your library does not have in its holdings a book which you found in IxTheo, you have various options at your disposal.</p>
        <h1 class="cw-h5">1. Interlibrary Loan within Germany</h1>
        <p>New: An interlibrary loan within Germany can be triggered directly from your search result.</p>
        <p>First search for the book you need. Then click on the title of the book you want in the list of results. You will now see the bibliographic details and various other options. Select the option “Interlibrary Loan for the Fachinformationsdienste (Specialized Information Services in Germany)”.</p>
        <a class="thumbnail" href="#" data-image-id="" data-toggle="modal" data-title="" data-caption="" data-image="<?=$this->imageLink('content_img/en/interlibrary_loan_eng.png')?>" data-target="#image-gallery">
            <img class="img-responsive" width="800" src="<?=$this->imageLink('content_img/en/interlibrary_loan_eng.png')?>" alt="<?=$this->transEscAttr('symbolic_image_table48');?>">
        </a>
        <p>An overview of the German library associations  is then displayed. Select the region in which your academic library (i.e. the one for which you have a user ID card) is located:</p>
        <a class="thumbnail" href="#" data-image-id="" data-toggle="modal" data-title="" data-caption="" data-image="<?=$this->imageLink('content_img/fernleihe_img_2.png')?>" data-target="#image-gallery">
            <img class="img-responsive" width="800" src="<?=$this->imageLink('content_img/fernleihe_img_2.png')?>" alt="<?=$this->transEscAttr('symbolic_image_table49');?>">
        </a>
        <p>You then get redirected to the portal of your library association. Select “Per Fernleihe bestellen” and follow the directions to access your library account.</p>
        <p>Most German libraries charge a small processing fee for each book ordered per interlibrary loan (normally between 1,50 and 3,00 Euros).</p>
        <h1 class="cw-h5">2. International Interlibrary Loan</h1>
        <p>You can order books which are not available in any library of your country per international interlibrary loan.</p>
        <p>Usually, you must fill out special forms. There are fees depending on the location of the book you are ordering (approx. 15-30 Euros, more in some cases). For more information, please contact your library.</p>
        <p>Books which are still in print but not available at any German library can be ordered through IxTheo using an <a href="<?=$this->url('content-page', ['page' => 'NutzerinnengesteuerteErwerbung']) ?>">acquisition recommendation</a>. This service is mostly free of charge. However, please note that it may take months to complete the acquisition process.</p>
        <h1 class="cw-h5">3. subito (Delivery Service for a Fee)</h1>
        <p>Subito allows you to order literature directly at a library of your choice and have it delivered to an address you specify.</p>
        <p><a target="_blank" href="https://www.subito-doc.de/">Link to the subito book and article delivery service</a></p>
        <p>Subito charges a fee for its services (starting at 5,50 Euros). You can order articles and books. Articles are delivered per e-mail, mail or fax. Books are delivered by mail and must be returned to the library at the end of the loan period.</p>
        <p>You can choose between the normal service (your order is then processed within three workdays) and the express service (processing within 24 hours). If the order cannot be fulfilled, you are notified per e-mail.</p>
      </div>
  </div>
</div>
