<div class="cw-row">
  <div class="cw-col-lg-12 cw-ml-lg-4">
    <div class="cw-text-block"><br />
      <h1 class="cw-h1">Fernleihe</h1>
      <p>Wenn Sie auf ein in IxTheo gefundenes Werk an Ihrer Bibliothek nicht zugreifen können, stehen Ihnen unterschiedliche Optionen zur Verfügung.</p>
      <h1 class="cw-h5">1. Fernleihe innerhalb Deutschlands</h1>
      <p>Neu: Fernleihen innerhalb Deutschlands können direkt aus Ihrer IxTheo-Suche heraus aufgegeben werden.</p>
      <p>Rufen Sie das gesuchte Werk in IxTheo auf und wählen Sie die Option „Fernleihe: Fernleihe für die Fachinformationsdienste“.</p>
      <a class="thumbnail" href="#" data-image-id="" data-toggle="modal" data-title="" data-caption="" data-image="/themes/ixtheo2/images/content_img/fernleihe_img_1.png" data-target="#image-gallery">
          <img class="img-responsive" width="800" src="/themes/ixtheo2/images/content_img/fernleihe_img_1.png" alt="<?=$this->transEscAttr('symbolic_image_table48');?>">
      </a>
      <p>Es erscheint eine Übersicht über die deutschen Bibliotheksverbünde. Wählen Sie die Region, zu der Ihre wissenschaftliche Bibliothek gehört (für die Sie einen Bibliotheksausweis haben):</p>
      <a class="thumbnail" href="#" data-image-id="" data-toggle="modal" data-title="" data-caption="" data-image="/themes/ixtheo2/images/content_img/fernleihe_img_2.png" data-target="#image-gallery">
          <img class="img-responsive" width="800" src="/themes/ixtheo2/images/content_img/fernleihe_img_2.png" alt="<?=$this->transEscAttr('symbolic_image_table49');?>">
      </a>
      <p>Sie werden auf das Portal Ihres Bibliotheksverbundes weitergeleitet. Wählen Sie „Per Fernleihe bestellen“ und folgen Sie den Anweisungen zur Anmeldung in Ihrem Bibliothekskonto.</p>
      <p>Die meisten deutschen Bibliotheken erheben für jedes per Fernleihe bestellte Werk eine geringe Bearbeitungsgebühr (normalerweise zwischen 1,50 und 3,00 Euro).</p>
      <h1 class="cw-h5">2. Internationale Fernleihe</h1>
      <p>Werke, die in keiner Bibliothek Ihres Landes vorhanden sind, können Sie per internationaler Fernleihe bestellen.</p>
      <p>Dafür sind zumeist spezielle Formulare auszufüllen. Je nachdem, von wo das gesuchte Werk beschafft werden muss, fallen Kosten an (ca. 15–30 Euro, in Einzelfällen auch mehr). Für Details wenden Sie sich an Ihre wissenschaftliche Bibliothek.</p>
      <p>Für Werke, die noch lieferbar und in keiner deutschen Bibliothek vorhanden sind, können Sie alternativ ggf. auch über IxTheo einen <a href="<?=$this->url('content-page', ['page' => 'NutzerinnengesteuerteErwerbung']) ?>">Anschaffungsvorschlag</a> aufgeben. Dabei fallen für Sie keine oder geringere Kosten an. Beachten Sie aber, dass der Anschaffungsprozess mehrere Monate dauern kann.</p>
      <h1 class="cw-h5">3. subito (kostenpflichtiger Lieferdienst)</h1>
      <p>Der Lieferdienst subito bietet Ihnen die Möglichkeit, Literatur direkt bei einer Bibliothek Ihrer Wahl zu bestellen und an eine von Ihnen angegebene Adresse liefern zu lassen.</p>
      <p><a target="_blank" href="https://www.subito-doc.de/">Zum Lieferdienst subito: Bestellung von Aufsätzen und Büchern</a></p>
      <p>Die Angebote von subito sind kostenpflichtig (ab 5,50 Euro aufwärts). Sie können Aufsätze und Bücher bestellen. Die Lieferung von Aufsätzen erfolgt wahlweise elektronisch via E-Mail, per Post oder per Fax. Bücher werden auf dem Postweg geliefert und müssen nach Ablauf der Leihfrist wieder an die Bibliothek zurückgesandt werden.</p>
      <p>Sie können zwischen Normaldienst (Bearbeitung Ihrer Bestellung innerhalb von drei Arbeitstagen) und Eildienst (Bearbeitung innerhalb von 24 Stunden) wählen. Sollte eine Bestellung nicht ausführbar sein, erhalten Sie eine Nachricht per E-Mail.</p>
    </div>
  </div>
</div>
