<div class="cw-row">
  <div class="cw-col-lg-12">
    <div class="cw-text-block"><br>
      <span id="ixtheo_content"></span>
      <h1 class="cw-h1">FID Theologie</h1>
      <p>Der von der Deutschen Forschungsgemeinschaft geförderte Fachinformationsdienst (FID) Theologie ist seit 2015 an der Universitätsbibliothek Tübingen angesiedelt. Der FID Theologie knüpft an die Arbeit des von 1949-2014 an der UB Tübingen verantworteten Sondersammelgebiets (SSG) Theologie an und bietet neue Dienstleistungen für die theologische Forschung. <a target="_blank" href="http://wikis.sub.uni-hamburg.de/webis/index.php/Theologie">Weitere Informationen</a></p>
      <p>Der FID ergänzt die an den einzelnen Universitäten und Forschungseinrichtungen bereitgestellte Infrastruktur für das Fach Theologie durch spezialisierte Angebote und orientiert sich dabei eng an den Bedürfnissen der Forschung. Hierzu gehören beispielsweise die Bereitstellung spezieller Medien und Recherchemöglichkeiten sowie Angebote im Bereich Open Access. </p>
      <p>Alle Medien, Services und Informationsangebote des FID Theologie sind über den Index Theologicus als zentrale Datenbank <a href="<?=$this->url('content-page', ['page' => 'about_us']) ?>">Index Theologicus</a> recherchierbar.</p>
      <p>Mehr Informationen über das DFG-Förderprogramm "Fachinformationsdienste für die Wissenschaft" finden Sie <a target="_blank" href="https://www.dfg.de/foerderung/programme/infrastruktur/lis/lis_foerderangebote/fachinfodienste_wissenschaft/">hier</a>.</p>
    </div>
  </div>
</div>

<style type="text/css">
.digiTabs .nav-tabs>li>a {
  font-size: 11px;
}
.digiTabs .tab-content {
  padding: 10px;
}
.digiTabs .nav-tabs>li>a {
  font-size: 16px;
}
</style>