<div class="cw-row">
  <div class="cw-col-lg-12">
    <div class="cw-text-block"><br>
      <span id="ixtheo_content"></span>
      <h1 class="cw-h1">FID Theologie</h1>
      <p>The “Fachinformationsdienst (FID) Theologie” (“specialized information service in theology”), which is supported by the Deutsche Forschungsgemeinschaft (German Research Foundation), was founded in 2015 at the University Library of Tübingen (Universitätsbibliothek Tübingen). It has transformed and expanded the work done by the former “Sondersammelgebiet (SSG) Theologie” (the “specialized collection in theology”), which existed from 1949 to 2014 at the University Library of Tübingen, and offers new services for theological research. Further information on the FID can be found at the <a target="_blank" href="http://wikis.sub.uni-hamburg.de/webis/index.php/Theologie">portal of the FIDs in Germany</a>.</p>
      <p>The FID complements the infrastructure at universities and research institutions in the field of theology by providing specialized services, and it is closely oriented to the needs of the research community. For instance, it provides access to specialized publications and search functions and offers services for open access publications.</p>
      <p>All publications, services and information provided by the FID Theologie are accessible and searchable through the <a href="<?=$this->url('content-page', ['page' => 'AboutUs']) ?>">Index Theologicus</a> as its central database.</p>
      <p>More information on the program “Fachinformationsdienste für die Wissenschaft” (“specialized information services for research”) is available at the <a target="_blank" href="https://www.dfg.de/en/research-funding/funding-opportunities/programmes/infrastructure/lis/funding-opportunities/specialised-info-services">homepage of the German Research Foundation</a>.</p> 
      <span id="ixtheo_aufgaben"></span>
      <h3 class="cw-mt-5"><b>Tasks</b></h3>
          <div role="tablist" class="digiTabs">
              <div class="cw-card cw-mb-3">
                  <div>
                      <!-- Nav tabs -->
                      <ul class="nav nav-tabs nav-justified" role="tablist">
                          <li role="presentation" class="active"><a href="#tab1" aria-controls="" role="tab" data-toggle="tab">Tasks for 2024-2026</a></li>
                          <li role="presentation"><a href="#tab2" aria-controls="" role="tab" data-toggle="tab">Tasks for 2021–2023</a></li>
                          <li role="presentation"><a href="#tab3" aria-controls="" role="tab" data-toggle="tab">Tasks for 2018–2020</a></li>
                          <li role="presentation"><a href="#tab4" aria-controls="" role="tab" data-toggle="tab">Tasks for 2015–2017</a></li>
                      </ul>

                      <!-- Tab panes -->
                      <div class="tab-content">
                          <div role="tabpanel" class="tab-pane active" id="tab1">
                              <h5><b>Contents:</b></h5>
                              <ul>
                                  <li>Ongoing cataloguing and indexing of over 1,200 international journals, numerous academic series as well as the German, English and French national bibliographies</li>
                                  <li>Expansion of the journal portfolio</li>
                                  <li>Continuation of the retrospective cataloguing and indexing of articles from essay collections and journals</li>
                                  <li>Integration of additional bibliographies and special collections into IxTheo (BiBIL, Bibliotheca Augustiniana, Finding Augustine, Maurits Sabbe Library in Leuven)</li>
                                  <li>Cataloguing of digital editions</li>
                                  <li>Cataloguing of academic series which have been made available in open access and of other publications in repositories (with their respective links)</li>
                                  <li>Cataloguing of research data from all fields in theology</li>
                                  <li>Expansion of the indexing work in cooperation with new partners (Augustinus-Bibliographie, BiBIL)</li>
                                  <li>Automated indexing of a large number of records with IxTheo classifications</li>
                              </ul>

                              <h5><b>Features:</b></h5>
                              <ul>
                                  <li>Addition of Polish as a search language to IxTheo</li>
                                  <li>Addition of a form to report publications not yet catalogued in IxTheo</li>
                                  <li>Integration of the option to directly trigger an inter-library loan in IxTheo</li>
                                  <li>Integration of WorldCat in the availability information</li>
                                  <li>Expansion of the full text search to include publications from additional publishing houses</li>
                              </ul>

                              <h5><b>Services::</b></h5>
                              <ul>
                                  <li>IxTheo Open Journals: Founding of new journals and flipping of existing journals into open access (OJS publishing system)</li>
                                  <li>IxTheo Open Text: Continuation of the service for registered German scholars to republish their works in open access</li>
                                  <li>Self-Archiving Service: This service gives scholars the opportunity to self-archive their own publications in open access. It is available worldwide.</li>
                                  <li>Digitization on Demand: Digitization of copyright-free volumes at the request of users, in cooperation with the FID Geschichtswissenschaft (Specialized Information Service for History)</li>
                                  <li>Research Data Management: Advisory service for scholars from all fields of theology on documenting and long-term archiving of research data, with further information on specialized repositories and contact persons</li>
                              </ul>
                          </div>

                          <div role="tabpanel" class="tab-pane" id="tab2">
                              <h5><b>Contents:</b></h5>
                              <ul>
                                  <li>Expansion of the journal portfolio</li>
                                  <li>Expansion of the retrospective cataloguing and indexing of journals</li>
                                  <li>Systematic inclusion of the national bibliographies of England, France and other countries in the cataloguing process</li>
                                  <li>Scanning the bibliographies of monographs and making them searchable</li>
                                  <li>Cataloguing the lemmas of important theological lexicons</li>
                                  <li>Inclusion of metadata about historical printed books from the 16th to the 18th century that are relevant to the subject of theology (from the databases VD16, VD17, VD18)</li>
                                  <li>Integration of numerous collections from the Princeton Theological Commons database</li>
                                  <li>Integration of important collections on the history of Protestantism in cooperation with the following institutions:
                                      <ul>
                                          <li>Forschungsbibliothek Gotha (Forschungs- und Studienstätte für die Kulturgeschichte des Protestantismus in der Frühen Neuzeit, the “Library for the Cultural and Intellectual History of the Modern Era”)</li>
                                          <li>Johannes a Lasco Bibliothek, Emden</li>
                                          <li>Franckesche Stiftungen zu Halle, Studienzentrum August Hermann Francke, Halle</li>
                                          <li>Reformationsgeschichtliche Forschungsbibliothek Wittenberg (research library on the history of the Reformation in Wittenberg)</li>
                                      </ul>
                                  </li>
                              </ul>
                              
                              <h5><b>Features:</b></h5>
                              <ul>
                                  <li>Person Information Pages on theological authors with lists of publications, links and further information</li>
                                  <li>Expansion of the full text search to include publications from additional publishing houses</li>
                                  <li>Aggregator for new blog posts with an alerting function</li>
                              </ul>
                              <h5><b>Services:</b></h5>
                              <ul>
                                  <li>IxTheo Open Journals: Founding of new journals and flipping of existing journals into open access (OJS publishing system)</li>
                                  <li>IxTheo Self-Archiving: Self-archiving of scholarly publications in open access via IxTheo</li>
                                  <li>IxTheo Open Text: service for scholars to republish their works in open access in compliance with copyright law</li>
                              </ul>
                          </div>

                          <div role="tabpanel" class="tab-pane" id="tab3">
                              <h5><b>Contents:</b></h5>
                              <ul>
                                  <li>Expansion of the spectrum of journals catalogued and indexed (including journals which have ceased publication)</li>
                                  <li>Integration of selected review journals</li>
                                  <li>Comprehensive and systematic cataloguing of monographs</li>
                                  <li>Cataloguing of all relevant databases</li>
                                  <li>Integration of freely accessible online journals and digital content</li>
                                  <li>Inclusion of personal archives from theologians and of other archival materials</li>
                              </ul>
                              
                              <h5><b>Features:</b></h5>
                              <ul>
                                  <li>Development of a full text search for open access publications and commercial publications</li>
                                  <li>Development of a search function for sources in church and Canon Law (CIC, CCEO) and for publications covering a specified historical period on the basis of the algorithm used to search for Bible passages</li>
                                  <li>Alerting services: Function to automatically receive information on new publications in theological fields of their choice</li>
                              </ul>

                              <h5><b>Services:</b></h5>
                              <ul>
                                  <li>IxTheo Open Journals: Founding of new journals and flipping of existing journals into open access (OJS publishing system)</li>
                                  <li>IxTheo Open Text: service for scholars to republish their works in open access in compliance with copyright law</li>
                              </ul>
                          </div>

                          <div role="tabpanel" class="tab-pane" id="tab4">
                              <h5><b>Contents:</b></h5>
                              <ul>
                                  <li>Development of IxTheo as a research-oriented discovery system and as an international open access bibliography</li>
                                  <li>Integration of numerous important theological publication types in IxTheo: monographs, articles, reviews, databases</li>
                              </ul>

                              <h5><b>Features:</b></h5>
                              <ul>
                                  <li>Technical development of IxTheo on the basis of a modern open-source discovery system (VuFind)</li>
                                  <li>Development of an algorithm to search for Bible passages which meets the needs of scholarly users</li>
                              </ul>
                              <h5><b>Services:</b></h5>
                              <ul>
                                  <li>Establishment of a specialized theological repository</li>
                                  <li>Introduction of the journal publishing system Open Journal Systems (OJS)</li>
                              </ul>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
		  
		  <div>
		   <p><a target="_blank" href="<?=$this->url('content-page', ['page' => 'ContactPersons']) ?>">Contact Persons for the FID Theologie</a></p>
		  </div>
		  
        <span id="ixtheo_beirat"></span>
        
        <h3 class="cw-mt-5"><b>Scholarly Advisory Board</b></h3>
        <p>The advisory board is composed of 10 members: 5 Protestant theologians and 5 Roman Catholic theologians, including one member of the deans’ offices of each theology faculty in Tübingen, the chairperson of the
            <a target="_blank" href="https://wgth.de">Wissenschaftliche Gesellschaft für Theologie (WGTh)</a> [which is Protestant] and the spokesperson of the
            <a target="_blank" href="https://www.katholische-theologie.info/zusammenschl%C3%BCsse">Vereinigung der Arbeitsgemeinschaften für Katholische Theologie (VAKT)</a> [which is Roman Catholic].
        </p>
      
        <h5><b>Protestant Community</b></h5>
        <ul>
            <li>Prof. Dr. Claudia Jahnel (Hamburg)</li>
            <li>Prof. Dr. Malte Dominik Krüger (Marburg)</li>
            <li>Prof. Dr. Andreas Müller (Kiel)</li>
            <li>Prof. Dr. Konrad Schmid (Zürich)</li>
            <li>Prof. Dr. Birgit Weyel (Tübingen)</li>
        </ul>
        <h5><b>Roman Catholic Community</b></h5>
        <ul>
            <li>Prof. Dr. Katharina Klöcker (Erfurt)</li>
            <li>Prof. Dr. Johannes Schnocks (Münster)</li>
			<li>Prof. Dr. Bernhard Spielberg (Freiburg)</li>
            <li>Prof. Dr. Klaus Unterburger (München)</li>
			<li>Prof. Dr. Saskia Wendel (Tübingen)</li>
        </ul>
		<h5><b>Former Members of the Scholarly Advisory Board</b></h5>
		<ul>
			<li>Prof. Dr. Albrecht Beutel (Münster)</li>
			<li>Prof. Dr. Rita Burrichter (Paderborn)</li>
			<li>Prof. Dr. Gerd Häfner (München)</li>
			<li>Prof. Dr. Marianne Heimbach-Steins (Münster)</li>
			<li>Prof. Dr. Andreas Holzem (Tübingen)</li>
			<li>Prof. Dr. Volker Leppin (Tübingen)</li>
			<li>Prof. Dr. Kristin Merle (Hamburg)</li>
			<li>Prof. Dr. Michael Meyer-Blanck (Bonn)</li>
			<li>Prof. Dr. Johanna Rahner (Tübingen)</li>
			<li>Prof. Dr. Bernd Schipper (Berlin)</li>
			<li>Prof. Dr. Michael Schüßler (Tübingen)</li>
			<li>Prof. Dr. Michael Theobald (Tübingen)</li>
			<li>Prof. Dr. Michael Tilly (Tübingen)</li>
		</ul>
        <hr />
    </div>
  </div>
</div>

<style type="text/css">
.digiTabs .nav-tabs>li>a {
  font-size: 11px;
}
.digiTabs .tab-content {
  padding: 10px;
}
.digiTabs .nav-tabs>li>a {
  font-size: 16px;
}
</style>