<div class="container cw-py-5">
  <div class="cw-row">
    <div class="cw-col-lg-8">
      <div class="cw-text-block">
        <h1 class="cw-h1">Multilingual full-text search</h1>
        <p>Theological texts from various publishing houses and from open access sources can be searched through the IxTheo full-text search. With this tool, the Index Theologicus (IxTheo) allows you to search for keywords and expressions in a large body of literature.</p>
        <h3><b>Searchable literature</b></h3>
        <p>The IxTheo full-text search is currently available for publications from the Brill, Mohr Siebeck, De Gruyer and Aschendorff publishing houses. We plan to integrate monographs, essay collections, lexicons and journals from other important theological publishing houses in the future.</p>
        <p>At the same time, it is possible to search through extensive open access literature: The full-text search is also available for publications from IxTheo digitization and self-archiving projects.</p>
        <p>Tables of contents, literature indexes and summaries / abstracts from many other publications are also searchable via the full-text search.</p>
        <p>The searchable body of literature currently consists of approx. 600,000 documents:</p>
        <ul>
          <li>Full texts</li>
          <li>Abstracts</li>
          <li>Tables of contents</li>
          <li>Literature indexes</li>
        </ul>
        <h3><b>Search options</b></h3>
        <p>The IxTheo full-text search allows you to search not only for specific terms, but also, at the same time, for synonyms and translations of these terms in several languages.<br />The following search modes are available:</p>
        <ol>
          <li>Full texts without synonyms</li>
          <li>Full texts with synonyms</li>
          <li>Full texts with multilingual synonyms</li>
        </ol>
        <p>You can restrict your search to specific text types (full text, table of contents, literature index, summary / abstract) and combine it with IxTheo facets.</p>
        <p>In addition to searching through all titles available in our database, you can also perform a search through the full text of a specific publication.</p>
      </div>
    </div>
  </div>
</div>