<div class="container cw-py-5">
  <div class="cw-row">
    <div class="cw-col-lg-8">
      <div class="cw-text-block">
        <h1 class="cw-h1">Multilinguale Volltextsuche</h1>
        <p>Mit der IxTheo-Volltextsuche können theologisch relevante Volltexte aus verschiedenen Verlagen und aus Open Access-Quellen gleichzeitig durchsucht werden. Damit bietet der Index Theologicus (IxTheo) die Möglichkeit, in einem großen Textkorpus nach bestimmten Stichwörtern und Phrasen zu recherchieren.</p>
        <h3><b>Durchsuchbare Inhalte</b></h3>
        <p>Momentan können Publikationen der Verlage Brill, Mohr Siebeck, De Gruyter und Aschendorff im Volltext durchsucht werden. Eine Integration der Monographien, Sammelbände, Lexika und Zeitschriften weiterer wichtiger theologischer Verlage ist geplant.</p>
        <p>Zugleich kann in umfangreichen Open-Access-Inhalten recherchiert werden: Bei Werken aus den Digitalisierungsprojekten des IxTheo wird ebenfalls der gesamte Text durchsucht.</p>
        <p>Für zahlreiche weitere Publikationen stehen Inhaltsverzeichnisse, Literaturverzeichnisse und Zusammenfassungen zur Verfügung.</p>
        <p>Das durchsuchbare Textkorpus besteht zurzeit aus ca. 600.000 Digitalisaten:</p>
        <ul>
          <li>Volltexte</li>
          <li>Abstracts</li>
          <li>Inhaltsverzeichnisse</li>
          <li>Literaturverzeichnisse</li>
        </ul>
        <h3><b>Suchoptionen</b></h3>
        <p>Die IxTheo-Volltextsuche bietet die Möglichkeit, nicht nur nach den konkret eingegebenen Begriffen, sondern auch nach Synonyma und deren Übersetzungen in mehrere Sprachen zu suchen.<br />Folgende Suchmodi stehen zur Verfügung:</p>
        <ol>
          <li>Volltexte ohne Synonyme</li>
          <li>Volltexte + Synonyme</li>
          <li>Volltexte + mehrsprachige Synonyme</li>
        </ol>
        <p>Die Suche kann auf einzelne Texttypen (Volltext, Inhaltsverzeichnis, Literaturverzeichnis, Zusammenfassung) eingeschränkt und mit den bekannten IxTheo-Facetten kombiniert werden.</p>
        <p>Neben der gleichzeitigen Recherche in allen vorhandenen Titeln ist es auch möglich, den Volltext eines ausgewählten Einzeltitels zu durchsuchen.</p>
      </div>
    </div>
  </div>
</div>