<div class="cw-row">
    <div class="cw-col-lg-12 cw-ml-lg-4">
        <div class="cw-text-block"><br>
            <h1 class="cw-h1">Historical Printed Works</h1>

            <p>In addition to current literature, the Index Theologicus (IxTheo) also includes printed works from the 16th, 17th and 18th centuries. Thus, IxTheo makes it possible to search specifically for theological publications from the early modern period. This period can be specified as a criterion in a thematic search; it is also possible to perform a search for original sources from this period, and secondary literature on this period simultaneously.</p>
            <p>During the funding period 2021-2023, the bibliography of historical printed works in IxTheo was expanded to include two important components:</p>

            <h3 style="font-weight: bold;">Cooperation with Specialized Libraries</h3>

            <p>Through a cooperation agreement with renowned specialized libraries, their printed works of theological nature, and works which are important for research in church history, are also documented in IxTheo. Thus, comprehensive and, in some cases, unique collections of early modern printed works are directly searchable in IxTheo.</p>
            <p>We cooperate with the following institutions:</p>
            <ul>
              <li><a target="_blank" href="https://www.uni-erfurt.de/en/gotha-research-library">Gotha Research Library (Research and Study Centre for the Cultural History of Protestantism in the Early Modern Period)</a></li>
              <li><a target="_blank" href="https://www.jalb.de/">Johannes a Lasco Bibliothek, Emden</a></li>
              <li><a target="_blank" href="https://www.francke-halle.de/en/science/archives-and-library">Francke Foundations in Halle, Studienzentrum August Hermann Francke, Halle</a></li>
              <li><a target="_blank" href="https://www.rfb-wittenberg.de/">Reformationsgeschichtliche Forschungsbibliothek Wittenberg</a></li>
            </ul>

            <p>For more information on the collections in IxTheo, see <a target="_blank" href="<?=$this->url('content-page', ['page' => 'Collections'])?>">Collections</a>.</p>

            <h3 style="font-weight: bold;">Printed Works from VD16, VD17 and VD18</h3>

            <p>The comprehensive bibliographies of works printed in the German-speaking world during the 16th, 17th and 18th centuries (<a target="_blank" href="https://www.bsb-muenchen.de/sammlungen/historische-drucke/recherche/vd-16/">VD16</a>, <a target="_blank" href="http://www.vd17.de/">VD17</a>, <a target="_blank" href="https://kxp.k10plus.de/DB=1.65/SET=1/TTL=1/START_WELCOME">VD18</a>) (VD16, VD17, VD18) contain numerous theologically relevant printed works. These are being successively integrated in IxTheo.</p>
            <ul>
              <li>This makes it possible to conduct comprehensive searches for publications concerning the theology and church history of the German-speaking world in the early modern period.</li>
              <li>Exact bibliographical information on these publications is provided.</li>
              <li>References to the catalogs of the libraries which keep these printed works are provided through VD16, VD17, VD18.</li>
              <li>Many of the works are available in digitized form.</li>
            </ul>
      </div>
    </div>
</div>
