<?php $this->headLink()->appendStylesheet('vendor/slick/slick.css');?>
<?php $this->headLink()->appendStylesheet('vendor/slick/slick-theme.css');?>
<?php $this->headLink()->appendStylesheet('vendor/cw/swiper.css');?>

<?php $this->headScript()->appendFile('vendor/slick/slick.min.js');?>
<?php $this->headScript()->appendFile('vendor/cw/ofi.js');?>
<?php $this->headScript()->appendFile('vendor/cw/smooth-scroll.js');?>
<?php $this->headScript()->appendFile('vendor/cw/swiper.js');?>
<?php $this->headScript()->appendFile('vendor/cw/theme.js');?>

<?=$this->render('content/sections/aktuelles'); ?>

<?=$this->render('content/sections/discover'); ?>

<?=$this->render('content/sections/resource'); ?>

<?=$this->render('content/sections/special'); ?>

<?=$this->render('content/sections/networking'); ?>

<div class="tf-background-body ix-display-none">
    <div id="content" class="container">
        <div class="row">
            <?=$this->content()->renderTranslated('panels/discover'); ?>
            <?=$this->content()->renderTranslated('panels/services'); ?>
            <?=$this->content()->renderTranslated('panels/derivatives'); ?>
        </div>
    </div>
</div>
