<?php $this->headTitle($this->translate('Impressum'));?>
<h1>Impressum</h1>
<p>General information in accordance with § 5 TMG, § 55 RStVG</p>
<table class="table table-striped">
    <tr>
        <td>Service Provider</td>
        <td>University Library of the Eberhard Karls Universität Tübingen</td>
    </tr>
    <tr>
        <td>Address</td>
        <td>Universitätsbibliothek<br/>
            Wilhelmstraße 32<br/>
            72074 Tübingen<br/>
			Germany</td>
    </tr>
    <tr>
        <td>Kontakt</td>
        <td>IxTheo Team of the Tübingen University Library<br/>
            ixtheo@ub.uni-tuebingen.de<br/>
            +49 (0)7071 29 74029</td>
    </tr>
    <tr>
        <td>Legal Form</td>
        <td>The Eberhard Karls Universität Tübingen is a public body. It is legally represented by the Rector Prof. Dr. Dr. h. c. (Dōshisha) Karla Pollmann (E-Mail: rektorin@uni-tuebingen.de).</td>
    </tr>
    <tr>
        <td>VAT Number</td>
        <td>in accordance with § 27a of the German VAT law:<br>DE812383453</td>
    </tr>
    <tr>
        <td>Supervisory Authority</td>
        <td>Ministerium für Wissenschaft, Forschung und Kunst Baden Württemberg</td>
    </tr>
    <tr>
        <td>Liability Disclaimer</td>
        <td>Although we verify our contents carefully, we do not assume any responsibility or liability for the contents of external links. Only the providers of the websites linked are responsible for the contents of their websites.</td>
    </tr>
    <tr>
        <td>Person responsible for the information provided on the Index Theologicus in accordance with §18 Par. 2 MStV:</td>
        <td>Regine Tobias (Director of the Tübingen University Library)</td>
    </tr>
</table>

