<div class="cw-row">
    <div class="cw-col-lg-12 cw-ml-lg-4">
        <div class="cw-text-block"><br>
            <h1 class="cw-h1">IxTheo Innovative</h1>
            <p>In addition to books and journals, other information sources which go beyond the contents of a traditional bibliography are searchable in the Index Theologicus (IxTheo). Thus, you can pursue specific research questions but also discover new media.</p>
            <p>After any search, you can use the “Format” facet on the right-hand side next to the list of results to select certain types of publications or sources in your search results. There are also several innovative tools to facilitate the searching process.</p>

            <section class="cw-py-5">
                <div class="cw-container panel-group">
                    <div class="cw-row">
                        <!-- item-->
                        <div class="col-xs-12 col-sm-6 col-lg-3 cw-mb-5 hover-animate tf-cursor-pointer">
                            <div data-toggle="collapse" data-target="#collapse-inno-1">
                                <div class="cw-card h-100 border-0 shadow">
                                    <div class="cw-card-img-top cw-overflow-hidden cw-dark-overlay cw-bg-cover innovativ-image-1" title="<?=$this->transEscAttr('symbolic_image_table50');?>"></div>
                                    <div class="ix2-sub-item-title">Weblogs and Podcasts</div>
                                </div>
                            </div>
                            <div class="collapse" id="collapse-inno-1">
                                <div class="card card-body">
                                    <p>Many researchers and institutions publish content in blogs and podcasts. Some comment primarily on current events in the church and in theology; others deal in longer series and more in depth with topics in theology and religious studies. Many of these contributions aim to present current research in a manner accessible to the greater public.</p>
                                    <p>You can search for relevant blogs by selecting the option “Weblog” in the “Format” facet in IxTheo.</p>
                                    <p>It is also possible to follow several blogs and podcasts at the same time by using IxTheo’s feed aggregator. Once you’ve selected the blogs and podcasts you wish to follow, you are informed per e-mail or RSS-feed whenever a new contribution or episode is available.</p>
                                    <p>You can get an overview of all blogs currently accessible through IxTheo with <a href="<?=$this->url('search-results', [], ['query' => ['lookfor' => '','type'=>'AllFields','filter' => 'format:"Weblog"']]); ?>">this search query</a>.</p>
                                </div>
                            </div>
                        </div>
                        <!-- end item-->

                        <!-- item-->
                        <div class="col-xs-12 col-sm-6 col-lg-3 cw-mb-5 hover-animate tf-cursor-pointer">
                            <div data-toggle="collapse" data-target="#collapse-inno-2">
                                <div class="cw-card h-100 border-0 shadow">
                                    <div class="cw-card-img-top cw-overflow-hidden cw-dark-overlay cw-bg-cover innovativ-image-2" title="<?=$this->transEscAttr('symbolic_image_table51');?>."></div>
                                    <div class="ix2-sub-item-title">Archival Material</div>
                                </div>
                            </div>
                            <div class="collapse" id="collapse-inno-2">
                                <div class="card card-body">
                                    <p>You can restrict your search in IxTheo to archival material. If you click on the link labeled “Archivdatenbank ” in a record, you get access to further information in the corresponding archival databases and possibly to the corresponding digital files (if applicable).</p>
                                    <p>To perform a specific search for archived material connected with a person, do the following: Select the “Persons / Corporations” tab above the search field on top of the page and enter the name of the person in the search field. Once you’ve chosen the appropriate person in the list of results, information about this person from various databases will be displayed on the person information page. The section labeled “Archival Collections” gives you a direct access to references of archived material and other manuscript sources, e.g. letters or personal archives. More information on person information pages is available at <a href="<?=$this->url('content-page', ['page' => 'AuthorityPages']) ?>">Person Information Pages</a>.</p>
                                    <p>You can get an overview of all archived material currently referenced in IxTheo with <a href="<?=$this->url('search-results', [], ['query' => ['lookfor' => '','type'=>'AllFields','filter' => 'format:"Archived Material"']]); ?>">this search query</a>.</p>
                                </div>
                            </div>
                        </div>
                        <!-- end item-->

                        <!-- item-->
                        <div class="col-xs-12 col-sm-6 col-lg-3 cw-mb-5 hover-animate tf-cursor-pointer">
                            <div data-toggle="collapse" data-target="#collapse-inno-3">
                                <div class="cw-card h-100 border-0 shadow">
                                    <div class="cw-card-img-top cw-overflow-hidden cw-dark-overlay cw-bg-cover innovativ-image-3" title="<?=$this->transEscAttr('symbolic_image_table52');?>"></div>
                                    <div class="ix2-sub-item-title">Personal Archives</div>
                                </div>
                            </div>
                            <div class="collapse" id="collapse-inno-3">
                                <div class="card card-body">
                                    <p>In IxTheo, you can filter your search so that it finds only personal archives (which the person has deposited in a library or public archive). This allows you to determine the archive or the library in which the personal archives of a person are kept and the size of those collections.</p>
                                    <p>There are two different ways to find  personal archives: After a search query, you can select the “Personal archives” option in the “Format” facet. Alternatively, you can select the “Persons / Corporations” tab above the search field and enter the name of the person in the search field. In the section labeled “Archival Collections”, personal papers are also listed. More information on person information pages is available at <a href="<?=$this->url('content-page', ['page' =>'AuthorityPages']) ?>">Person Information Pages</a>.</p>
                                    <p>You can get an overview of all personal archives currently referenced in IxTheo with <a href="<?=$this->url('search-results', [], ['query' => ['lookfor' => '','type'=>'AllFields','filter' => 'format:"Literary Remains"']]); ?>">this search query</a>.</p>
                                </div>
                            </div>
                        </div>
                        <!-- end item-->

                        <!-- item-->
                        <div class="col-xs-12 col-sm-6 col-lg-3 cw-mb-5 hover-animate tf-cursor-pointer">
                            <div data-toggle="collapse" data-target="#collapse-inno-4">
                                <div class="cw-card h-100 border-0 shadow">
                                    <div class="cw-card-img-top cw-overflow-hidden cw-dark-overlay cw-bg-cover innovativ-image-4" title="<?=$this->transEscAttr('symbolic_image_table53');?>."></div>
                                    <div class="ix2-sub-item-title">Research Data</div>
                                </div>
                            </div>
                            <div class="collapse" id="collapse-inno-4">
                                <div class="card card-body">
                                    <p>Research data of various types may be produced while planning, conducting or documenting academic research; in theology, this could be e.g. survey results, XML data for digital editions or drawings from archaeological digs. In addition to processing and analyzing this data in their own publications, an increasing number of researchers make their data available to the academic community for subsequent use.</p>
                                    <p>To find research data in IxTheo, select the “Research Data” option in the “Format” facet after a search. The link to the data is displayed for every entry. Research data from various areas of theology is thus easily accessible and can be reused.</p>
                                    <p>You can get an overview of all research data currently referenced in IxTheo with <a href="<?=$this->url('search-results', [], ['query' => ['lookfor' => '','type'=>'AllFields','filter' => 'format:"Research Data"']]); ?>">this search query</a>.</p>
                                </div>
                            </div>  
                        </div>
                        <!-- end item-->
                    
                        <!-- item-->
                        <div class="col-xs-12 col-sm-6 col-lg-3 cw-mb-5 hover-animate tf-cursor-pointer">
                            <div data-toggle="collapse" data-target="#collapse-inno-5">
                                <div class="cw-card h-100 border-0 shadow">
                                    <div class="cw-card-img-top cw-overflow-hidden cw-dark-overlay cw-bg-cover innovativ-image-5" title="<?=$this->transEscAttr('symbolic_image_table54');?>."></div>
                                    <div class="ix2-sub-item-title">Databases</div>
                                </div>
                            </div>
                            <div class="collapse" id="collapse-inno-5">
                                <div class="card card-body">
                                    <p>Several hundred theologically relevant databases can be found in IxTheo. You can use keywords to search for databases specifically suited to a particular theological issue.</p>
                                    <p>Just a few clicks are necessary to gain access either directly or through a redirection to any given database. If the licensing requirements allow it, a quick and easy access to their contents is provided. A growing number of databases are available in Open Access.</p>
                                    <p>You can get an overview of all databases currently referenced in IxTheo with <a href="<?=$this->url('search-results', [], ['query' => ['lookfor' => '','type'=>'AllFields','filter' => 'format:"Database"']]); ?>">this search query</a>.</p>
                                </div>
                            </div>
                        </div>
                        <!-- end item-->

                        <!-- item-->
                        <div class="col-xs-12 col-sm-6 col-lg-3 cw-mb-5 hover-animate tf-cursor-pointer">
                            <div data-toggle="collapse" data-target="#collapse-inno-6">
                                <div class="cw-card h-100 border-0 shadow">
                                    <div class="cw-card-img-top cw-overflow-hidden cw-dark-overlay cw-bg-cover innovativ-image-6" title="<?=$this->transEscAttr('symbolic_image_table55');?>."></div>
                                    <div class="ix2-sub-item-title">Websites</div>
                                </div>
                            </div>
                            <div class="collapse" id="collapse-inno-6">
                                <div class="card card-body">
                                    <p>Many institutions and groups from the field of theology provide information on their respective websites. One can find further relevant links, publications or references on these homepages.</p>
                                    <p>IxTheo allows you to restrict your search to homepages from theologically relevant research societies, commissions, associations and news portals.</p>
                                    <p>You can get an overview of all homepages currently referenced in IxTheo with <a href="<?=$this->url('search-results', [], ['query' => ['lookfor' => '','type'=>'AllFields','filter' => 'format:"Website"']]); ?>">this search query</a>.</p>
                                </div>
                            </div>
                        </div>
                        <!-- end item-->

                        <!-- item-->
                        <div class="col-xs-12 col-sm-6 col-lg-3 cw-mb-5 hover-animate tf-cursor-pointer">
                            <div data-toggle="collapse" data-target="#collapse-inno-7">
                                <div class="cw-card h-100 border-0 shadow">
                                    <div class="cw-card-img-top cw-overflow-hidden cw-dark-overlay cw-bg-cover innovativ-image-7" title="<?=$this->transEscAttr('symbolic_image_table56');?>."></div>
                                    <div class="ix2-sub-item-title">Statistics</div>
                                </div>
                            </div>
                            <div class="collapse" id="collapse-inno-7">
                                <div class="card card-body">
                                    <p>In IxTheo, it is also possible to search for “statistics” as a format category. You can thus find publications with statistical components, which can be used for further research, as well as statistics which were separately published as research data.</p>
                                    <p>You can get an overview of all statistics currently referenced in IxTheo with <a href="<?=$this->url('search-results', [], ['query' => ['lookfor' => '','type'=>'AllFields','filter' => 'format:"Statistics"']]); ?>">this search query</a>.</p>
                                </div>
                            </div>
                        </div>
                        <!-- end item-->

                        <!-- item-->
                        <div class="col-xs-12 col-sm-6 col-lg-3 cw-mb-5 hover-animate tf-cursor-pointer">
                            <div data-toggle="collapse" data-target="#collapse-inno-8">
                                <div class="cw-card h-100 border-0 shadow">
                                    <div class="cw-card-img-top cw-overflow-hidden cw-dark-overlay cw-bg-cover innovativ-image-8" title="<?=$this->transEscAttr('symbolic_image_table57');?>."></div>
                                    <div class="ix2-sub-item-title">Dictionary articles</div>
                                </div>
                            </div>
                            <div class="collapse" id="collapse-inno-8">
                                <div class="card card-body">
                                    <p>In IxTheo, you can search for numerous lemmas from various dictionaries. If you want to restrict your search to dictionary articles, select the option “Dictionary entry/article” in the “Format” facet. More information on the search for dictionary articles is available at <a href="<?=$this->url('content-page', ['page' => 'LexiconSearch']) ?>">Dictionary Articles</a>.</p>
                                    <p>You can get an overview of all lemmas currently referenced in IxTheo with <a href="<?=$this->url('search-results', [], ['query' => ['lookfor' => '','type'=>'AllFields','filter' => 'format:"Dictionary entry/article"']]); ?>">this search query</a>.</p>
                                </div>
                            </div>   
                        </div>
                        <!-- end item-->
                    </div>
                </div>
            </section>

        </div>
    </div>
</div>
