<div class="cw-row">
    <div class="cw-col-lg-12 cw-ml-lg-4">
        <div class="cw-text-block"><br>
            <h1 class="cw-h1">IxTheo Innovativ</h1>
            <p>Neben Büchern und Zeitschriften sind im Index Theologicus (IxTheo) weitere Inhalte recherchierbar, die über das Angebot einer klassischen Bibliographie hinausgehen. Sie können dadurch spezifische Forschungsfragen verfolgen, aber auch neue Medien entdecken.</p>
            <p>Nach einer beliebigen Suche können Sie über eine Auswahl in der Facette „Medienart“ im rechts angezeigten Menü Ihre Suche gezielt auf bestimmte Arten von Quellen oder Publikationen ausrichten. Vielfach stehen zudem innovative Tools zur Verfügung, die die Recherche erleichtern.</p>

            <section class="cw-py-5">
                <div class="cw-container panel-group">
                    <div class="cw-row">
                        <!-- item-->
                        <div class="col-sm-6 col-lg-3 cw-mb-5 hover-animate tf-cursor-pointer">
                            <div data-toggle="collapse" data-target="#collapse-inno-1">
                                <div class="cw-card h-100 border-0 shadow">
                                    <div class="cw-card-img-top cw-overflow-hidden cw-dark-overlay cw-bg-cover innovativ-image-1">
                                        <!--img.img-fluid(src="#{imgBasePath}#{val.image}" alt="#{val.name}")-->
                                        <div class="cw-card-img-overlay-bottom cw-z-index-20">
                                            <h4 class="cw-h4 cw-text-white cw-text-shadow">Weblogs und Podcasts</h4>
                                            <!--<p class="cw-mb-2 cw-text-xs"><i class="fa fa-star text-warning"></i><i class="fa fa-star text-warning"></i><i class="fa fa-star text-warning"></i><i class="fa fa-star text-warning"></i><i class="fa fa-star text-gray-300"></i></p>-->
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="collapse" id="collapse-inno-1">
                                <div class="card card-body">
                                    <p>Viele Wissenschaftler*innen und Institutionen publizieren inzwischen auch in Blogs und Podcasts. Einige kommentieren vor allem aktuelle Ereignisse aus Theologie und Kirche; andere behandeln in längeren Serien Themen aus dem Bereich der Theologie und Religionswissenschaft. Ein Akzent liegt häufig auf der anschaulichen Vermittlung aktueller Forschung.</p>
                                    <p>Relevante Blogs können recherchiert werden, indem in der Facette „Medienart“ im IxTheo die Option „Weblog“ ausgewählt wird.</p>
                                    <p>Mit dem Feed-Aggregator des IxTheo ist es zudem möglich, verschiedene Blogs und Podcasts gesammelt zu abonnieren. Sie können selbst entscheiden, welche Blogs und Podcasts für Sie von Interesse sind und werden regelmäßig per Mail oder RSS-Feed über neue Einträge und Folgen informiert.</p>
                                    <p>Eine Übersicht über die Gesamtzahl der Blogs, die in IxTheo nachgewiesen sind, finden Sie <a href="<?=$this->url('search-results', [], ['query' => ['lookfor' => '','type'=>'AllFields','filter' => 'format:"Weblog"']]); ?>">hier</a>.</p>
                                </div>
                            </div>
                        </div>
                        <!-- end item-->

                        <!-- item-->
                        <div class="col-sm-6 col-lg-3 cw-mb-5 hover-animate tf-cursor-pointer">
                            <div data-toggle="collapse" data-target="#collapse-inno-2">
                                <div class="cw-card h-100 border-0 shadow">
                                    <div class="cw-card-img-top cw-overflow-hidden cw-dark-overlay cw-bg-cover innovativ-image-2">
                                        <!--img.img-fluid(src="#{imgBasePath}#{val.image}" alt="#{val.name}")-->
                                        <div class="cw-card-img-overlay-bottom cw-z-index-20">
                                            <h4 class="cw-h4 cw-text-white cw-text-shadow">Archivmaterialien</h4>
                                            <!--<p class="cw-mb-2 cw-text-xs"><i class="fa fa-star text-warning"></i><i class="fa fa-star text-warning"></i><i class="fa fa-star text-warning"></i><i class="fa fa-star text-warning"></i><i class="fa fa-star text-gray-300"></i></p>-->
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="collapse" id="collapse-inno-2">
                                <div class="card card-body">
                                    <p>Im IxTheo können Sie Ihre Suche auf Archivmaterialien eingrenzen. Durch einen Klick auf die Schaltfläche „Archivdatenbank“ im jeweiligen Eintrag gelangen Sie zu den weiterführenden Informationen in den jeweiligen Archivdatenbanken und ggf. zum Digitalisat.</p>
                                    <p>Für die gezielte Recherche nach Archivalien zu einer Person bietet sich folgendes Vorgehen an: Wählen Sie oberhalb des Suchschlitzes den Reiter „Personen/Körperschaften“ und geben Sie den Namen ein. Nach der Auswahl der gesuchten Person werden Ihnen Informationen aus unterschiedlichen Datenbanken angezeigt. Die Rubrik „Archivmaterial“ ermöglicht den direkten Zugriff auf Nachweise archivalischer und anderer handschriftlicher Quellen, z.B. Nachlässe oder Briefwechsel. Unter der Rubrik „Externe Ressourcen“ auf der rechten Seite finden sich zum Teil weitere Archivquellen. Nähere Informationen zu den Personenseiten finden Sie unter Link.</p>
                                    <p>Eine Übersicht über die Gesamtzahl der Archivmaterialien, die in IxTheo nachgewiesen sind, finden Sie <a href="<?=$this->url('search-results', [], ['query' => ['lookfor' => '','type'=>'AllFields','filter' => 'format:"Archived Material"']]); ?>">hier</a>.</p>
                                </div>
                            </div>
                        </div>
                        <!-- end item-->

                        <!-- item-->
                        <div class="col-sm-6 col-lg-3 cw-mb-5 hover-animate tf-cursor-pointer">
                            <div data-toggle="collapse" data-target="#collapse-inno-3">
                                <div class="cw-card h-100 border-0 shadow">
                                    <div class="cw-card-img-top cw-overflow-hidden cw-dark-overlay cw-bg-cover innovativ-image-3">
                                        <!--img.img-fluid(src="#{imgBasePath}#{val.image}" alt="#{val.name}")-->
                                        <div class="cw-card-img-overlay-bottom cw-z-index-20">
                                            <h4 class="cw-h4 cw-text-white cw-text-shadow">Nachlässe</h4>
                                            <!--<p class="cw-mb-2 cw-text-xs"><i class="fa fa-star text-warning"></i><i class="fa fa-star text-warning"></i><i class="fa fa-star text-warning"></i><i class="fa fa-star text-warning"></i><i class="fa fa-star text-gray-300"></i></p>-->
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="collapse" id="collapse-inno-3">
                                <div class="card card-body">
                                    <p>Im IxTheo besteht die Möglichkeit, nach Nachlässen oder Teilnachlässen zu filtern. So können Sie leicht feststellen, in welchem Archiv oder in welcher Bibliothek der Nachlass oder Teilnachlass einer Person liegt und wie umfangreich dieser ist.</p>
                                    <p>Neben der Option, die entsprechende Medienart nach einer einfachen Suche auszuwählen, ist auch hier die Recherche nach dem Namen der Person über den Reiter „Personen/Körperschaften“ oberhalb des Suchschlitzes möglich. Unter der Rubrik „Archivmaterial“ werden auch Nachlässe angezeigt. Nähere Informationen dazu finden Sie hier Link.</p>
                                    <p>Eine Übersicht über die Gesamtzahl der Nachlässe, die in IxTheo nachgewiesen sind, finden Sie <a href="<?=$this->url('search-results', [], ['query' => ['lookfor' => '','type'=>'AllFields','filter' => 'format:"Literary Remains"']]); ?>">hier</a>.</p>
                                </div>
                            </div>
                        </div>
                        <!-- end item-->

                        <!-- item-->
                        <div class="col-sm-6 col-lg-3 cw-mb-5 hover-animate tf-cursor-pointer">
                            <div data-toggle="collapse" data-target="#collapse-inno-4">
                                <div class="cw-card h-100 border-0 shadow">
                                    <div class="cw-card-img-top cw-overflow-hidden cw-dark-overlay cw-bg-cover innovativ-image-4">
                                        <!--img.img-fluid(src="#{imgBasePath}#{val.image}" alt="#{val.name}")-->
                                        <div class="cw-card-img-overlay-bottom cw-z-index-20">
                                            <h4 class="cw-h4 cw-text-white cw-text-shadow">Forschungsdaten</h4>
                                            <!--<p class="cw-mb-2 cw-text-xs"><i class="fa fa-star text-warning"></i><i class="fa fa-star text-warning"></i><i class="fa fa-star text-warning"></i><i class="fa fa-star text-warning"></i><i class="fa fa-star text-gray-300"></i></p>-->
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="collapse" id="collapse-inno-4">
                                <div class="card card-body">
                                    <p>Bei Forschungsdaten kann es sich um unterschiedliche Arten von Daten handeln, die bei der Planung, Durchführung und Dokumentation wissenschaftlicher Vorhaben entstanden sind, im Bereich der Theologie z. B. um Befragungsergebnisse, Editionsdateien oder Grabungszeichnungen. Neben der Auswertung und Analyse in einer Publikation werden solche Daten zunehmend auch frei zur Verfügung gestellt und für eine Nachnutzung verfügbar gemacht.</p>
                                    <p>Über eine Auswahl der Facette „Forschungsdaten“ können Sie Ihre Suche im IxTheo nach bereits veröffentlichten Daten filtern. Der Link zu den Datensätzen ist im IxTheo-Eintrag hinterlegt. Forschungsdaten aus verschiedensten theologischen Fachbereichen sind so einfach nachnutzbar.</p>
                                    <p>Eine Übersicht über die Gesamtzahl der Forschungsdaten, die in IxTheo nachgewiesen sind, finden Sie <a href="<?=$this->url('search-results', [], ['query' => ['lookfor' => '','type'=>'AllFields','filter' => 'format:"Research Data"']]); ?>">hier</a>.</p>
                                </div>
                            </div>  
                        </div>
                        <!-- end item-->
                    
                        <!-- item-->
                        <div class="col-sm-6 col-lg-3 cw-mb-5 hover-animate tf-cursor-pointer">
                            <div data-toggle="collapse" data-target="#collapse-inno-5">
                                <div class="cw-card h-100 border-0 shadow">
                                    <div class="cw-card-img-top cw-overflow-hidden cw-dark-overlay cw-bg-cover innovativ-image-5">
                                        <!--img.img-fluid(src="#{imgBasePath}#{val.image}" alt="#{val.name}")-->
                                        <div class="cw-card-img-overlay-bottom cw-z-index-20">
                                            <h4 class="cw-h4 cw-text-white cw-text-shadow">Datenbanken</h4>
                                            <!--<p class="cw-mb-2 cw-text-xs"><i class="fa fa-star text-warning"></i><i class="fa fa-star text-warning"></i><i class="fa fa-star text-warning"></i><i class="fa fa-star text-warning"></i><i class="fa fa-star text-gray-300"></i></p>-->
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="collapse" id="collapse-inno-5">
                                <div class="card card-body">
                                    <p>Im IxTheo sind mehrere Hundert theologisch relevante Datenbanken nachgewiesen. Die Kennzeichnung mit Schlagworten ermöglicht eine gezielte Recherche nach passenden Datenbanken für eine Fragestellung.</p>
                                    <p>Es genügen wenige Klicks, um direkt oder über eine Weiterleitung zu den jeweiligen Datenbanken zu gelangen. Wenn es lizenzrechtlich möglich ist, kann so schnell und komfortabel auf die Inhalte zugegriffen werden. Eine wachsende Zahl von Datenbanken ist vollständig im Open Access verfügbar.</p>
                                    <p>Eine Übersicht über die Gesamtzahl der Datenbanken, die in IxTheo nachgewiesen sind, finden Sie <a href="<?=$this->url('search-results', [], ['query' => ['lookfor' => '','type'=>'AllFields','filter' => 'format:"Database"']]); ?>">hier</a>.</p>
                                </div>
                            </div>
                        </div>
                        <!-- end item-->

                        <!-- item-->
                        <div class="col-sm-6 col-lg-3 cw-mb-5 hover-animate tf-cursor-pointer">
                            <div data-toggle="collapse" data-target="#collapse-inno-6">
                                <div class="cw-card h-100 border-0 shadow">
                                    <div class="cw-card-img-top cw-overflow-hidden cw-dark-overlay cw-bg-cover innovativ-image-6">
                                        <!--img.img-fluid(src="#{imgBasePath}#{val.image}" alt="#{val.name}")-->
                                        <div class="cw-card-img-overlay-bottom cw-z-index-20">
                                            <h4 class="cw-h4 cw-text-white cw-text-shadow">Webseiten</h4>
                                            <!--<p class="cw-mb-2 cw-text-xs"><i class="fa fa-star text-warning"></i><i class="fa fa-star text-warning"></i><i class="fa fa-star text-warning"></i><i class="fa fa-star text-warning"></i><i class="fa fa-star text-gray-300"></i></p>-->
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="collapse" id="collapse-inno-6">
                                <div class="card card-body">
                                    <p>Viele Einrichtungen, Institutionen und Gruppierungen aus dem Bereich der Theologie stellen aktuelle Informationen auf ihren jeweiligen Webseiten zur Verfügung. Der Blick auf diese Homepages ermöglicht es, auf weiterführende Links, Publikationen oder Hinweise zu stoßen.</p>
                                    <p>Der IxTheo erlaubt eine einfache Einschränkung Ihrer Suche nach Homepages von theologisch relevanten Forschungsassociations, Kommissionen, Vereinen und Nachrichtenportalen.</p>
                                    <p>Eine Übersicht über die Gesamtzahl der Homepages, die in IxTheo nachgewiesen sind, finden Sie <a href="<?=$this->url('search-results', [], ['query' => ['lookfor' => '','type'=>'AllFields','filter' => 'format:"Website"']]); ?>">hier</a>.</p>
                                </div>
                            </div>
                        </div>
                        <!-- end item-->

                        <!-- item-->
                        <div class="col-sm-6 col-lg-3 cw-mb-5 hover-animate tf-cursor-pointer">
                            <div data-toggle="collapse" data-target="#collapse-inno-7">
                                <div class="cw-card h-100 border-0 shadow">
                                    <div class="cw-card-img-top cw-overflow-hidden cw-dark-overlay cw-bg-cover innovativ-image-7">
                                        <!--img.img-fluid(src="#{imgBasePath}#{val.image}" alt="#{val.name}")-->
                                        <div class="cw-card-img-overlay-bottom cw-z-index-20">
                                            <h4 class="cw-h4 cw-text-white cw-text-shadow">Statistiken</h4>
                                            <!--<p class="cw-mb-2 cw-text-xs"><i class="fa fa-star text-warning"></i><i class="fa fa-star text-warning"></i><i class="fa fa-star text-warning"></i><i class="fa fa-star text-warning"></i><i class="fa fa-star text-gray-300"></i></p>-->
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="collapse" id="collapse-inno-7">
                                <div class="card card-body">
                                    <p>In der IxTheo-Suche besteht auch die Möglichkeit, nach Statistiken zu filtern. Es handelt sich dabei zum einen um Publikationen, in denen statistische Komponenten enthalten sind, die für weitergehende Forschungsvorhaben genutzt werden können. Zum anderen werden Ihnen Statistiken angezeigt, die als Forschungsdaten separat publiziert wurden.</p>
                                    <p>Eine Übersicht über die Gesamtzahl der Statistiken, die in IxTheo nachgewiesen sind, finden Sie <a href="<?=$this->url('search-results', [], ['query' => ['lookfor' => '','type'=>'AllFields','filter' => 'format:"Statistics"']]); ?>">hier</a>.</p>
                                </div>
                            </div>
                        </div>
                        <!-- end item-->

                        <!-- item-->
                        <div class="col-sm-6 col-lg-3 cw-mb-5 hover-animate tf-cursor-pointer">
                            <div data-toggle="collapse" data-target="#collapse-inno-8">
                                <div class="cw-card h-100 border-0 shadow">
                                    <div class="cw-card-img-top cw-overflow-hidden cw-dark-overlay cw-bg-cover innovativ-image-8">
                                        <!--img.img-fluid(src="#{imgBasePath}#{val.image}" alt="#{val.name}")-->
                                        <div class="cw-card-img-overlay-bottom cw-z-index-20">
                                            <h4 class="cw-h4 cw-text-white cw-text-shadow">Lexikonartikel</h4>
                                            <!--<p class="cw-mb-2 cw-text-xs"><i class="fa fa-star text-warning"></i><i class="fa fa-star text-warning"></i><i class="fa fa-star text-warning"></i><i class="fa fa-star text-warning"></i><i class="fa fa-star text-gray-300"></i></p>-->
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="collapse" id="collapse-inno-8">
                                <div class="card card-body">
                                    <p>In IxTheo sind zahlreiche Lemmata aus diversen Lexika recherchierbar. Wenn Sie Ihre Suche auf Lexikonartikel einschränken wollen, können Sie dazu rechts in der Facette „Medienart“ den entsprechenden Reiter auswählen. Eine ausführliche Erklärung zur Recherche von Lexikonartikeln finden Sie unter Link zum Text „Lexikonrecherche“.</p>
                                    <p>Eine Übersicht über die Gesamtzahl der Lexikonartikel, die in IxTheo nachgewiesen sind, finden Sie <a href="<?=$this->url('search-results', [], ['query' => ['lookfor' => '','type'=>'AllFields','filter' => 'format:"Dictionary entry/article"']]); ?>">hier</a>.</p>
                                </div>
                            </div>   
                        </div>
                        <!-- end item-->
                    </div>
                </div>
            </section>

            <!--/#
            <h2><b>Weblogs und Podcasts</b></h2>
            <p>Viele Wissenschaftler*innen und Institutionen publizieren inzwischen auch in Blogs und Podcasts. Einige kommentieren vor allem aktuelle Ereignisse aus Theologie und Kirche; andere behandeln in längeren Serien Themen aus dem Bereich der Theologie und Religionswissenschaft. Ein Akzent liegt häufig auf der anschaulichen Vermittlung aktueller Forschung.</p>
            <p>Relevante Blogs können recherchiert werden, indem in der Facette „Medienart“ im IxTheo die Option „Weblog“ ausgewählt wird.</p>
            <p>Mit dem Feed-Aggregator des IxTheo ist es zudem möglich, verschiedene Blogs und Podcasts gesammelt zu abonnieren. Sie können selbst entscheiden, welche Blogs und Podcasts für Sie von Interesse sind und werden regelmäßig per Mail oder RSS-Feed über neue Einträge und Folgen informiert.</p>
            <p>Eine Übersicht über die Gesamtzahl der Blogs, die in IxTheo nachgewiesen sind, finden Sie <a href="<?=$this->url('search-results', [], ['query' => ['lookfor' => '','type'=>'AllFields','filter' => 'format:"Weblog"']]); ?>">hier</a>.</p>
            
            <h2><b>Archivmaterialien</b></h2>
            <p>Im IxTheo können Sie Ihre Suche auf Archivmaterialien eingrenzen. Durch einen Klick auf die Schaltfläche „Archivdatenbank“ im jeweiligen Eintrag gelangen Sie zu den weiterführenden Informationen in den jeweiligen Archivdatenbanken und ggf. zum Digitalisat.</p>
            <p>Für die gezielte Recherche nach Archivalien zu einer Person bietet sich folgendes Vorgehen an: Wählen Sie oberhalb des Suchschlitzes den Reiter „Personen/Körperschaften“ und geben Sie den Namen ein. Nach der Auswahl der gesuchten Person werden Ihnen Informationen aus unterschiedlichen Datenbanken angezeigt. Die Rubrik „Archivmaterial“ ermöglicht den direkten Zugriff auf Nachweise archivalischer und anderer handschriftlicher Quellen, z.B. Nachlässe oder Briefwechsel. Unter der Rubrik „Externe Ressourcen“ auf der rechten Seite finden sich zum Teil weitere Archivquellen. Nähere Informationen zu den Personenseiten finden Sie unter Link.</p>
            <p>Eine Übersicht über die Gesamtzahl der Archivmaterialien, die in IxTheo nachgewiesen sind, finden Sie <a href="<?=$this->url('search-results', [], ['query' => ['lookfor' => '','type'=>'AllFields','filter' => 'format:"Archived Material"']]); ?>">hier</a>.</p>
            
            <h2><b>Nachlässe</b></h2>
            <p>Im IxTheo besteht die Möglichkeit, nach Nachlässen oder Teilnachlässen zu filtern. So können Sie leicht feststellen, in welchem Archiv oder in welcher Bibliothek der Nachlass oder Teilnachlass einer Person liegt und wie umfangreich dieser ist.</p>
            <p>Neben der Option, die entsprechende Medienart nach einer einfachen Suche auszuwählen, ist auch hier die Recherche nach dem Namen der Person über den Reiter „Personen/Körperschaften“ oberhalb des Suchschlitzes möglich. Unter der Rubrik „Archivmaterial“ werden auch Nachlässe angezeigt. Nähere Informationen dazu finden Sie hier Link.</p>
            <p>Eine Übersicht über die Gesamtzahl der Nachlässe, die in IxTheo nachgewiesen sind, finden Sie <a href="<?=$this->url('search-results', [], ['query' => ['lookfor' => '','type'=>'AllFields','filter' => 'format:"Literary Remains"']]); ?>">hier</a>.</p>

            <h2><b>Forschungsdaten</b></h2>
            <p>Bei Forschungsdaten kann es sich um unterschiedliche Arten von Daten handeln, die bei der Planung, Durchführung und Dokumentation wissenschaftlicher Vorhaben entstanden sind, im Bereich der Theologie z. B. um Befragungsergebnisse, Editionsdateien oder Grabungszeichnungen. Neben der Auswertung und Analyse in einer Publikation werden solche Daten zunehmend auch frei zur Verfügung gestellt und für eine Nachnutzung verfügbar gemacht.</p>
            <p>Über eine Auswahl der Facette „Forschungsdaten“ können Sie Ihre Suche im IxTheo nach bereits veröffentlichten Daten filtern. Der Link zu den Datensätzen ist im IxTheo-Eintrag hinterlegt. Forschungsdaten aus verschiedensten theologischen Fachbereichen sind so einfach nachnutzbar.</p>
            <p>Eine Übersicht über die Gesamtzahl der Forschungsdaten, die in IxTheo nachgewiesen sind, finden Sie <a href="<?=$this->url('search-results', [], ['query' => ['lookfor' => '','type'=>'AllFields','filter' => 'format:"Research Data"']]); ?>">hier</a>.</p>
            
            <h2><b>Datenbanken</b></h2>
            <p>Im IxTheo sind mehrere Hundert theologisch relevante Datenbanken nachgewiesen. Die Kennzeichnung mit Schlagworten ermöglicht eine gezielte Recherche nach passenden Datenbanken für eine Fragestellung.</p>
            <p>Es genügen wenige Klicks, um direkt oder über eine Weiterleitung zu den jeweiligen Datenbanken zu gelangen. Wenn es lizenzrechtlich möglich ist, kann so schnell und komfortabel auf die Inhalte zugegriffen werden. Eine wachsende Zahl von Datenbanken ist vollständig im Open Access verfügbar.</p>
            <p>Eine Übersicht über die Gesamtzahl der Datenbanken, die in IxTheo nachgewiesen sind, finden Sie <a href="<?=$this->url('search-results', [], ['query' => ['lookfor' => '','type'=>'AllFields','filter' => 'format:"Database"']]); ?>">hier</a>.</p>
            
            <h2><b>Webseiten</b></h2>
            <p>Viele Einrichtungen, Institutionen und Gruppierungen aus dem Bereich der Theologie stellen aktuelle Informationen auf ihren jeweiligen Webseiten zur Verfügung. Der Blick auf diese Homepages ermöglicht es, auf weiterführende Links, Publikationen oder Hinweise zu stoßen.</p>
            <p>Der IxTheo erlaubt eine einfache Einschränkung Ihrer Suche nach Homepages von theologisch relevanten Forschungsassociations, Kommissionen, Vereinen und Nachrichtenportalen.</p>
            <p>Eine Übersicht über die Gesamtzahl der Homepages, die in IxTheo nachgewiesen sind, finden Sie <a href="<?=$this->url('search-results', [], ['query' => ['lookfor' => '','type'=>'AllFields','filter' => 'format:"Website"']]); ?>">hier</a>.</p>
            
            <h2><b>Statistiken</b></h2>
            <p>In der IxTheo-Suche besteht auch die Möglichkeit, nach Statistiken zu filtern. Es handelt sich dabei zum einen um Publikationen, in denen statistische Komponenten enthalten sind, die für weitergehende Forschungsvorhaben genutzt werden können. Zum anderen werden Ihnen Statistiken angezeigt, die als Forschungsdaten separat publiziert wurden.</p>
            <p>Eine Übersicht über die Gesamtzahl der Statistiken, die in IxTheo nachgewiesen sind, finden Sie <a href="<?=$this->url('search-results', [], ['query' => ['lookfor' => '','type'=>'AllFields','filter' => 'format:"Statistics"']]); ?>">hier</a>.</p>
            
            <h2><b>Lexikonartikel</b></h2>
            <p>In IxTheo sind zahlreiche Lemmata aus diversen Lexika recherchierbar. Wenn Sie Ihre Suche auf Lexikonartikel einschränken wollen, können Sie dazu rechts in der Facette „Medienart“ den entsprechenden Reiter auswählen. Eine ausführliche Erklärung zur Recherche von Lexikonartikeln finden Sie unter Link zum Text „Lexikonrecherche“.</p>
            <p>Eine Übersicht über die Gesamtzahl der Lexikonartikel, die in IxTheo nachgewiesen sind, finden Sie <a href="<?=$this->url('search-results', [], ['query' => ['lookfor' => '','type'=>'AllFields','filter' => 'format:"Dictionary entry/article"']]); ?>">hier</a>.</p>
            -->
            <!--- ---->

            <!----- --->

        </div>
    </div>
</div>

<style>
.innovativ-image-1 {
    background-image: url(/themes/ixtheo2/images/innovativ/Podcast.jpg);
    min-height: 200px;
}
.innovativ-image-2 {
    background-image: url(/themes/ixtheo2/images/innovativ/Archivmaterialien.jpg);
    min-height: 200px;
}
.innovativ-image-3 {
    background-image: url(/themes/ixtheo2/images/innovativ/Nachlass.jpg);
    min-height: 200px;
}
.innovativ-image-4 {
    background-image: url(/themes/ixtheo2/images/innovativ/Forschungsdaten.jpg);
    min-height: 200px;
}
.innovativ-image-5 {
    background-image: url(/themes/ixtheo2/images/innovativ/Datenbanken.jpg);
    min-height: 200px;
}
.innovativ-image-6 {
    background-image: url(/themes/ixtheo2/images/innovativ/Webseiten.jpg);
    min-height: 200px;
}
.innovativ-image-7 {
    background-image: url(/themes/ixtheo2/images/innovativ/Statistiken.jpg);
    min-height: 200px;
}
.innovativ-image-8 {
    background-image: url(/themes/ixtheo2/images/innovativ/Lexikonartikel.jpg);
    min-height: 200px;
}

</style>