<div class="cw-row">
    <div class="cw-py-5">
        <h1 class="cw-h1">IxTheo Account</h1>
        <p>Wenn Sie einen persönlichen Account anlegen, stehen Ihnen zusätzliche Funktionen zur Verfügung. Dafür müssen Sie sich lediglich einmalig mit einer gültigen E-Mail-Adresse sowie einem Benutzernamen und einem Passwort registrieren; weitere Angaben sind optional. Die Registrierung ist kostenlos.</p>   
        <p>Den Link zur Registrierung und zum Login finden Sie auf der Startseite rechts oben unter dem Button „Login“.</p>
        <p style="text-align: center; margin: 30px 0px;"><img src="/themes/ixtheo2/images/content_img/block2_1.jpg" style="width: 80%;"  /></p>
        <p>Nach dem Login wird Ihnen der Button „Mein Konto“ angezeigt. Im personalisierten Bereich stehen Ihnen folgende Funktionen zur Verfügung:</p>
    </div>

    <!-- one block -->
    <div class="col-md-6 ix-panel-news">
        <div class="panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <b>Suchanfragen speichern</b>
                </h4>
            </div>
            <div class="panel-collapse">
                <div class="panel-body">
                    <input type="checkbox" class="read-more-state" id="post-1" />
                    <div class="read-more-wrap">
                        <p>Standardmäßig werden Suchanfragen nur während der aktuellen Sitzung temporär gespeichert. Wenn Sie bestimmte Suchanfragen häufiger verwenden wollen, können Sie diese Anfragen in Ihrem Konto abspeichern. </p>
                        <div class="read-more-target">
                            <p>Um eine Suchanfrage abzuspeichern, wählen Sie unter „Mein Konto“ rechts den Menüpunkt „Gespeicherte Suche“ aus.</p>
                            
                            <a class="thumbnail" href="#" data-image-id="" data-toggle="modal" data-title="" data-caption="" data-image="/themes/ixtheo2/images/content_img/block2_2.jpg" data-target="#image-gallery">
                                <img class="img-responsive" src="/themes/ixtheo2/images/content_img/block2_2.jpg" alt="">
                            </a>

                            <p>Hier werden Ihnen alle in der aktuellen Sitzung ausgeführten Suchen angezeigt. Durch Klick auf den Button „Speichern“ rechts neben den gesuchten Begriffen können Sie beliebige Suchanfragen dauerhaft abspeichern. Sie stehen dann dauerhaft unter dem Menüpunkt „Gespeicherte Suchanfragen“ zur Verfügung und können durch Anklicken erneut ausgeführt werden.</p>
                            <p>Auf diese Weise können Sie sich schnell einen Überblick über neu erschienene Literatur zu einem bestimmten Thema verschaffen, an dem Sie längerfristig interessiert sind. Dies lohnt sich besonders bei komplexen Abfragen.</p>
                        </div>
                    </div>
                    <label for="post-1" class="read-more-trigger"></label>
                </div>
            </div>
        </div>
    </div>
    <!-- end one block -->
    <!-- one block -->
    <div class="col-md-6 ix-panel-news">
        <div class="panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <b>Favoriten</b>
                </h4>
            </div>
            <div class="panel-collapse">
                <div class="panel-body">
                    <input type="checkbox" class="read-more-state" id="post-2" />
                    <div class="read-more-wrap">
                        <p>Speichern Sie interessante Titel direkt in Ihrem Konto ab. Damit stehen Ihnen die Angaben zu diesen Publikationen dauerhaft zur Verfügung.</p>
                        <div class="read-more-target">
                            <p>Einträge können durch einen Klick auf das blaue Sternchen neben dem Titel direkt abgespeichert werden:</p>
                            
                            <a class="thumbnail" href="#" data-image-id="" data-toggle="modal" data-title="" data-caption="" data-image="/themes/ixtheo2/images/content_img/block2_3.jpg" data-target="#image-gallery">
                                <img class="img-responsive" src="/themes/ixtheo2/images/content_img/block2_3.jpg" alt="">
                            </a>
                            
                        </div>
                    </div>
                    <label for="post-2" class="read-more-trigger"></label>
                </div>
            </div>
        </div>
    </div>
    <!-- end one block -->
    <!-- one block -->
    <div class="col-md-6 ix-panel-news">
        <div class="panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <b>Meine Listen</b>
                </h4>
            </div>
            <div class="panel-collapse">
                <div class="panel-body">
                    <input type="checkbox" class="read-more-state" id="post-3" />
                    <div class="read-more-wrap">
                        <p>Um die gespeicherten Titel zu ordnen, können Sie selbst Listen definieren, in denen die Favoriten gespeichert werden. So können Publikationen bestimmten Forschungsprojekten oder Themen zugeordnet werden. </p>
                        <div class="read-more-target">
                        <p>Um eine Liste anzulegen, wählen Sie rechts unter „Meine Listen“ die Funktion „Eine Liste erstellen“. Titel und Beschreibung können Sie frei wählen. Unter dem Punkt „Zugangseinschränkungen“ können Sie beim Anlegen der Liste oder beim späteren Bearbeiten entscheiden, ob die Liste nur von Ihnen eingesehen werden kann (Einstellung: privat) oder ob Sie die Liste mit anderen Nutzern teilen möchten (Einstellung: öffentlich).</p>

                        <a class="thumbnail" href="#" data-image-id="" data-toggle="modal" data-title="" data-caption="" data-image="/themes/ixtheo2/images/content_img/block2_4.jpg" data-target="#image-gallery">
                            <img class="img-responsive" src="/themes/ixtheo2/images/content_img/block2_4.jpg" alt="">
                        </a>

                        <p>Um öffentliche Listen mit anderen Personen zu teilen, kopieren Sie einfach die URL der Liste aus Ihrem Browser und verschicken oder verknüpfen diesen Link. Beispiel einer öffentlichen Liste mit Literaturvorschlägen zum Thema „Christentum und Europa“: <a target="_blank" href="https://www.ixtheo.de/MyResearch/MyList/83">https://www.ixtheo.de/MyResearch/MyList/83</a></p>
                        <p>Wenn Sie nun neue Favoriten abspeichern, können Sie beliebig auswählen, welcher Liste diese zugeordnet werden sollen. Alle Listen und Favoriten finden Sie unter dem Menüpunkt „Meine Listen“.</p>

                        <a class="thumbnail" href="#" data-image-id="" data-toggle="modal" data-title="" data-caption="" data-image="/themes/ixtheo2/images/content_img/block2_5.jpg" data-target="#image-gallery">
                            <img class="img-responsive" src="/themes/ixtheo2/images/content_img/block2_5.jpg" alt="">
                        </a>

                        <p>Sie können Favoriten aus Ihrem Konto in Literaturverwaltungsprogramme (Zotero, Citavi u.a.) exportieren, per E-Mail verschicken oder ausdrucken.</p>

                        </div>
                    </div>
                    <label for="post-3" class="read-more-trigger"></label>
                </div>
            </div>
        </div>
    </div>
    <!-- end one block -->
    <!-- one block -->
    <div class="col-md-6 ix-panel-news">
        <div class="panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <b>Alerting</b>
                </h4>
            </div>
            <div class="panel-collapse">
                <div class="panel-body">
                    <input type="checkbox" class="read-more-state" id="post-4" />
                    <div class="read-more-wrap">
                        <p>Die Alerting-Funktion bietet Ihnen die Möglichkeit, sich automatisch über neue Publikationen informieren zu lassen.</p>
                        <div class="read-more-target">
                        <p><i>Meine Alerts (Neuerscheinungen)</i></p>
                        <p>Mit der Funktion „Meine Alerts“ können Sie sich automatisch über neu erschienene Aufsätze / Bände aus bestimmten Zeitschriften oder Reihen informieren lassen. Sie können frei entscheiden, in welchen Fällen Sie eine Benachrichtigung wünschen.</p>
                        <p>Nähere Informationen finden Sie unter „Alerting“. <Link zur Rubrik Alerting hier einfügen></p>

                        <p><i>Meine Feeds</i></p>
                        <p>Mit der Funktion „Meine Feeds“ können Sie sich automatisch über neu publizierte Beiträge in theologischen und religionswissenschaftlichen Blogs und Podcasts informieren lassen. Sie können frei entscheiden, für welche Plattformen Sie eine Benachrichtigung wünschen.</p>
                        <p>Nähere Informationen finden Sie unter „Alerting“. <Link zur Rubrik Alerting hier einfügen></p>

                        </div>
                    </div>
                    <label for="post-4" class="read-more-trigger"></label>
                </div>
            </div>
        </div>
    </div>
    <!-- end one block -->
    <!-- one block -->
    <div class="col-md-6 ix-panel-news">
        <div class="panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <b>Buchbeschaffung</b>
                </h4>
            </div>
            <div class="panel-collapse">
                <div class="panel-body">
                    <input type="checkbox" class="read-more-state" id="post-5" />
                    <div class="read-more-wrap">
                        <p>Über die Funktion „Buchbeschaffung“ können Sie Werke zur Anschaffung vorschlagen.</p>
                        <div class="read-more-target">
                          <p>Wenn Sie im IxTheo ein wissenschaftliches Buch gefunden haben, das in keiner Bibliothek in Deutschland vorhanden ist, wird Ihnen dies angezeigt. Über Ihr IxTheo-Konto können Sie beauftragen, dass dieses Buch kostenlos über die UB Tübingen beschafft wird, damit Sie es im Anschluss über die Bibliothek oder über die Fernleihe bestellen können. Folgen Sie dazu den Anweisungen.</p>

                          <p>Wenn ein Buch, das Sie benötigen, nicht im Index Theologicus verzeichnet ist, können Sie es mit diesem Formular dem FID Theologie zur Anschaffung vorschlagen <a href="/Feedback/Form/AcquisitionRequest">Request</a>.</p>
                        </div>
                    </div>
                    <label for="post-5" class="read-more-trigger"></label>
                </div>
            </div>
        </div>
    </div>
    <!-- end one block -->
    <!-- one block -->
    <div class="col-md-6 ix-panel-news">
        <div class="panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <b>Meine Publikationen</b>
                </h4>
            </div>
            <div class="panel-collapse">
                <div class="panel-body">
                    <input type="checkbox" class="read-more-state" id="post-6" />
                    <div class="read-more-wrap">
                        <p>Hier können Sie selbst Zweitveröffentlichungen zu Ihren wissenschaftlichen Publikationen hochladen.</p>
                        <div class="read-more-target">
                          <p>Nähere Informationen zu diesem Service finden Sie unter <a href="<?=$this->url('content-page', ['page' => 'OpenText']) ?>">IxTheo Open Text</a>.</p>
                          <p>Sobald Sie Publikationen hochgeladen haben, wird in Ihrem Konto eine Liste dieser Texte angezeigt.</p>
                        </div>
                    </div>
                    <label for="post-6" class="read-more-trigger"></label>
                </div>
            </div>
        </div>
    </div>
    <!-- end one block -->
    <!-- one block -->
    <div class="col-md-6 ix-panel-news">
        <div class="panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <b>Persönliche Angaben</b>
                </h4>
            </div>
            <div class="panel-collapse">
                <div class="panel-body">
                    <input type="checkbox" class="read-more-state" id="post-7" />
                    <div class="read-more-wrap">
                        <p>Unter „Persönliche Angaben“ können Sie persönliche Angaben (Name, E-Mail-Adresse, Institution) eintragen und ändern.</p>
                        <div class="read-more-target">
                          <p>Sie können hier auch einstellen, in welcher Sprache der IxTheo für Sie angezeigt wird, sobald Sie in Ihrem Konto eingeloggt sind.</p>
                        </div>
                    </div>
                    <label for="post-7" class="read-more-trigger"></label>
                </div>
            </div>
        </div>
    </div>
    <!-- end one block -->

</div>

<style type="text/css">
.ix2-content-ul1 {
    margin-bottom: 10px;
}

.ix2-content-ul1 li {
    margin: 10px 0;
}

.panel-default {
    margin-bottom: 20px;
    background-color: #fff;
    border: 1px solid #ddd;
    border-radius: 4px;
    -webkit-box-shadow: 0 1px 1px rgba(0,0,0,.05);
    box-shadow: 0 1px 1px rgba(0,0,0,.05);
}
.panel-heading {
    padding: 10px 15px;
    border-bottom: 1px solid transparent;
    border-top-left-radius: 3px;
    border-top-right-radius: 3px;
}
</style>
