<div class="cw-row">
    <div class="cw-py-5">
        <h1 class="cw-h1">IxTheo Account</h1>
        <p>If you create a personal account, additional functions are available to you. You only need to register once with a valid email address, a username and a password; further details are optional. Registration is free of charge.</p>   
        <p>The link for registration and login is located at the top right corner and is labelled "login".</p>
        <p style="text-align: center; margin: 30px 0px;"><img src="/themes/ixtheo2/images/content_img/en/login_button_eng.png" style="width: 80%;" alt="<?=$this->transEscAttr('symbolic_image_table58');?>" /></p>
        <p>After you log in, the "My Account" button is displayed near the place where the “Login” button was. Click on it to access the following functions in your account:</p>
    </div>

    <!-- one block -->
    <div class="col-md-6 ix-panel-news">
        <div class="panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <b>Saving Search Queries</b>
                </h4>
            </div>
            <div class="panel-collapse">
                <div class="panel-body">
                    <input type="checkbox" class="read-more-state" id="post-1" />
                    <div class="read-more-wrap">
                        <p>By default, search queries are only temporarily saved during the current session. If you want to use certain search queries more than once, you can save them in your account.</p>
                        <div class="read-more-target">
                            <p>To save a search query, first select the menu item “Search History” located on the right-hand side below the label "My Account".</p>
                            
                            <a class="thumbnail" href="#" data-image-id="" data-toggle="modal" data-title="" data-caption="" data-image="/themes/ixtheo2/images/content_img/en/save_searches_eng.png" data-target="#image-gallery">
                                <img class="img-responsive" src="/themes/ixtheo2/images/content_img/en/save_searches_eng.png" alt="<?=$this->transEscAttr('symbolic_image_table59');?>.">
                            </a>

                            <p>You will then see under "Current searches" a list of all the searches you performed so far in the current session. You can permanently save any search query in that list by clicking on the "Save" button to the right of the search query. It is then moved above to the list of “Saved searches”, where it remains permanently available and can be executed again by clicking on it.</p>
                            <p>In this way, you can quickly get an overview of newly published literature on a specific topic in which you have an enduring interest. This is especially useful for complex queries.</p>
                        </div>
                    </div>
                    <label for="post-1" class="read-more-trigger"></label>
                </div>
            </div>
        </div>
    </div>
    <!-- end one block -->
    <!-- one block -->
    <div class="col-md-6 ix-panel-news">
        <div class="panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <b>Saved Items</b>
                </h4>
            </div>
            <div class="panel-collapse">
                <div class="panel-body">
                    <input type="checkbox" class="read-more-state" id="post-2" />
                    <div class="read-more-wrap">
                        <p>You can save IxTheo entries for publications in which you are interested directly in your account. The bibliographical information on these publications then remains permanently at your disposal.</p>
                        <div class="read-more-target">
                            <p>Entries can be saved directly by clicking on the blue star next to the title:</p>
                            
                            <a class="thumbnail" href="#" data-image-id="" data-toggle="modal" data-title="" data-caption="" data-image="/themes/ixtheo2/images/content_img/en/Favorite_eng.png" data-target="#image-gallery">
                                <img class="img-responsive" src="/themes/ixtheo2/images/content_img/en/Favorite_eng.png" alt="<?=$this->transEscAttr('symbolic_image_table60');?>">
                            </a>
                            
                        </div>
                    </div>
                    <label for="post-2" class="read-more-trigger"></label>
                </div>
            </div>
        </div>
    </div>
    <!-- end one block -->
    <!-- one block -->
    <div class="col-md-6 ix-panel-news">
        <div class="panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <b>My Lists</b>
                </h4>
            </div>
            <div class="panel-collapse">
                <div class="panel-body">
                    <input type="checkbox" class="read-more-state" id="post-3" />
                    <div class="read-more-wrap">
                        <p>You can organize the publication entries which you keep in your account by defining lists in which these entries are saved. This allows you to assign publications to specific research projects or topics.</p>
                        <div class="read-more-target">
                        <p>To create a list, select the function "Create a List" on the right-hand side under "My Lists". You can freely choose the title and description of your list. The "Access" option underneath the description field allows you, when you create the list or modify it later, to decide whether the list should be viewed only by you (setting: "Private") or whether you would like to share it with other users (setting: "Public").</p>

                        <a class="thumbnail" href="#" data-image-id="" data-toggle="modal" data-title="" data-caption="" data-image="/themes/ixtheo2/images/content_img/en/creating_list_eng.png" data-target="#image-gallery">
                            <img class="img-responsive" src="/themes/ixtheo2/images/content_img/en/creating_list_eng.png" alt="<?=$this->transEscAttr('symbolic_image_table61');?>.">
                        </a>

                        <p>To share public lists with other people, simply copy the list URL from your browser and send it as a link. <a target="_blank" href="https://www.ixtheo.de/MyResearch/MyList/83">Example of a public list with literature suggestions on the topic "Christianity and Europe"</a></p>
                        <p>Whenever you save new publication entries, you can choose in which list you would like to keep them. You can find all lists under the menu item "My Lists".</p>

                        <a class="thumbnail" href="#" data-image-id="" data-toggle="modal" data-title="" data-caption="" data-image="/themes/ixtheo2/images/content_img/en/save_to_list_eng.png" data-target="#image-gallery">
                            <img class="img-responsive" src="/themes/ixtheo2/images/content_img/en/save_to_list_eng.png" alt="<?=$this->transEscAttr('symbolic_image_table62');?>.">
                        </a>

                        <p>You can export entries from your account to reference management software (Zotero, Citavi, etc.), send them by email or print them.</p>

                        </div>
                    </div>
                    <label for="post-3" class="read-more-trigger"></label>
                </div>
            </div>
        </div>
    </div>
    <!-- end one block -->
    <!-- one block -->
    <div class="col-md-6 ix-panel-news">
        <div class="panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <b>Alerting</b>
                </h4>
            </div>
            <div class="panel-collapse">
                <div class="panel-body">
                    <input type="checkbox" class="read-more-state" id="post-4" />
                    <div class="read-more-wrap">
                        <p>The alerting function allows you to get automatic updates on new publications.</p>
                        <div class="read-more-target">
                        <p><i>My alerts (New Publications)</i></p>
                        <p>The function "My Alerts" lets you automatically get updates on newly published articles / volumes from specific journals or series. You can decide in which cases you want to receive a notification.</p>
                        <p>Further information can be found under  <a href="<?=$this->url('content-page', ['page' => 'Alerting']) ?>">Alerting</a>.</p>

                        <p><i>My newsfeeds</i></p>
                        <p>The function "My newsfeeds" lets you get automatic updates on newly published contributions in theological and religious studies blogs and podcasts. You can choose the platforms you want to follow.</p>
                        <p>Further information can be found under <a href="<?=$this->url('content-page', ['page' => 'Alerting']) ?>">Alerting</a>.</p>

                        </div>
                    </div>
                    <label for="post-4" class="read-more-trigger"></label>
                </div>
            </div>
        </div>
    </div>
    <!-- end one block -->
    <!-- one block -->
    <div class="col-md-6 ix-panel-news">
        <div class="panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <b>Book acquisition</b>
                </h4>
            </div>
            <div class="panel-collapse">
                <div class="panel-body">
                    <input type="checkbox" class="read-more-state" id="post-5" />
                    <div class="read-more-wrap">
                        <p>This function allows you to suggest works for acquisition.</p>
                        <div class="read-more-target">
                          <p>Whenever you find in the Index Theologicus a scholarly book which is not available in any library in Germany, this is indicated in the record. Through your IxTheo account, you can request that this book be purchased by the University Library of Tübingen so that you can subsequently order it from the library or via interlibrary loan. This service is free of charge. Just follow the instructions.</p>

                          <p>If a book you require is not listed in IxTheo, you can send an acquisition request to the FID Theologie by using <a href="/Feedback/Form/AcquisitionRequest">this form</a>.</p>
                        </div>
                    </div>
                    <label for="post-5" class="read-more-trigger"></label>
                </div>
            </div>
        </div>
    </div>
    <!-- end one block -->
    <!-- one block -->
    <div class="col-md-6 ix-panel-news">
        <div class="panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <b>My publications</b>
                </h4>
            </div>
            <div class="panel-collapse">
                <div class="panel-body">
                    <input type="checkbox" class="read-more-state" id="post-6" />
                    <div class="read-more-wrap">
                        <p>You can upload your scholarly publications here for self-archiving.</p>
                        <div class="read-more-target">
                          <p>Further information on this service can be found under <a href="<?=$this->url('content-page', ['page' => 'OpenText']) ?>">IxTheo Open Text</a>.</p>
                          <p>Once you have uploaded publications, a list of these texts will appear in your account.</p>
                        </div>
                    </div>
                    <label for="post-6" class="read-more-trigger"></label>
                </div>
            </div>
        </div>
    </div>
    <!-- end one block -->
    <!-- one block -->
    <div class="col-md-6 ix-panel-news">
        <div class="panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <b>Profile</b>
                </h4>
            </div>
            <div class="panel-collapse">
                <div class="panel-body">
                    <input type="checkbox" class="read-more-state" id="post-7" />
                    <div class="read-more-wrap">
                        <p>You can enter and modify your personal information (name, email address, institution) here.</p>
                        <div class="read-more-target">
                          <p>You can also set the default language in which IxTheo will be displayed for you whenever you log into your account.</p>
                        </div>
                    </div>
                    <label for="post-7" class="read-more-trigger"></label>
                </div>
            </div>
        </div>
    </div>
    <!-- end one block -->

</div>

<style type="text/css">
.ix2-content-ul1 {
    margin-bottom: 10px;
}

.ix2-content-ul1 li {
    margin: 10px 0;
}

.panel-default {
    margin-bottom: 20px;
    background-color: #fff;
    border: 1px solid #ddd;
    border-radius: 4px;
    -webkit-box-shadow: 0 1px 1px rgba(0,0,0,.05);
    box-shadow: 0 1px 1px rgba(0,0,0,.05);
}
.panel-heading {
    padding: 10px 15px;
    border-bottom: 1px solid transparent;
    border-top-left-radius: 3px;
    border-top-right-radius: 3px;
}
</style>
