<div class="container cw-py-5">
    <div class="cw-row">
        <div class="cw-col-lg-8">
            <div class="cw-text-block">
                <h1 class="cw-h1">Lexikonrecherche</h1>
				<p>Als Nutzer*in haben Sie im Index Theologicus (IxTheo) verschiedene Möglichkeiten, in Lexika zu recherchieren. Wo möglich, bietet IxTheo einen direkten und freien Zugang zum Lexikonartikel an.</p>
				<p>Zum einen sind in IxTheo zahlreiche Lemmata aus diversen Lexika recherchierbar. Wenn Sie Ihre Suche auf Lexikonartikel einschränken wollen, können Sie dazu rechts in der Facette „Medienart“ den entsprechenden Reiter auswählen.</p>
				<p>Darüber hinaus wird in der Förderphase 2021–2023 im IxTheo ein Lexikon-Modul aufgebaut.</p>
				<p>Wichtige theologische Lexika werden dabei vollständig nachgewiesen und in die IxTheo-Volltextsuche integriert. Ein Textsnippet zeigt den Kontext um einen gesuchten Begriff an.</p>
				<p>Folgende Lexika mit insgesamt mehr als 53.000 Lemmata stehen im Rahmen dieser neuen Suchmöglichkeit zur Verfügung:</p>
				<ol>
					<li><a href="https://ptah.ub.uni-tuebingen.de:4445/Search/Results?lookfor=Brill+Encyclopedia+of+Early+Christianity+Online*&type=AllFields&sort=title&botprotect=">Brill Encyclopedia of Early Christianity Online [Brill]</a></li> 
					<li><a href="https://ptah.ub.uni-tuebingen.de:4445/Search/Results?lookfor=superior_ppn%3A1809055768&type=AllFields&sort=title&botprotect=">Brill's Encyclopedia of Global Pentecostalism Online [Brill]</a></li>
					<li><a href="https://ptah.ub.uni-tuebingen.de:4445/Search/Results?lookfor=Brill%27s+Encyclopedia+of+Hinduism+&type=AllFields&sort=title&botprotect=">Brill's Encyclopedia of Hinduism Online [Brill]</a></li>
					<li><a href="https://ptah.ub.uni-tuebingen.de:4445/Search/Results?lookfor=superior_ppn%3A1777997526&type=AllFields&sort=title&botprotect=">Brill’s Encyclopedia of the Religions of the Indigenous People of South Asia Online [Brill]</a></li>
					<li><a href="https://ptah.ub.uni-tuebingen.de:4445/Search/Results?lookfor=superior_ppn%1015234194&type=AllFields&sort=title&botprotect=">Encyclopedia of Jewish-Christian Relations [De Gruyter]</a></li>
					<li><a href="https://ptah.ub.uni-tuebingen.de:4445/Search/Results?lookfor=superior_ppn%3A635135574&type=AllFields&sort=title&botprotect=">Encyclopedia of Jews in the Islamic World Online [Brill]</a></li>
					<li><a href="https://ptah.ub.uni-tuebingen.de:4445/Search/Results?lookfor=superior_ppn%3A840011121&type=AllFields&sort=title&botprotect=">Encyclopedia of Law and Religion Online [Brill]</a></li>
					<li><a href="https://ptah.ub.uni-tuebingen.de:4445/Search/Results?lookfor=superior_ppn%3A612654680&type=AllFields&sort=title&botprotect=">Encyclopedia of the Bible and its Reception [De Gruyter]</a></li>
					<li><a href="https://ptah.ub.uni-tuebingen.de:4445/Search/Results?lookfor=superior_ppn%1654493813&type=AllFields&sort=title&botprotect=">Lexikon der Bibelhermeneutik [De Gruyter]</a></li>
					<li><a href="https://ptah.ub.uni-tuebingen.de:4445/Search/Results?lookfor=superior_ppn%3A1655071696&type=AllFields&sort=title&botprotect=">Lexikon für Kirchen- und Religionsrecht Online [Brill]</a></li>
					<li><a href="https://ptah.ub.uni-tuebingen.de:4445/Search/Results?lookfor=superior_ppn%1735471887&type=AllFields&sort=title&botprotect=">Religion and Urbanity [De Gruyter]</a></li>
					<li><a href="https://ptah.ub.uni-tuebingen.de:4445/Search/Results?lookfor=superior_ppn%3A1657067688&type=AllFields&sort=title&botprotect=">Religion in Geschichte und Gegenwart Online (RGG4) [Mohr Siebeck / Brill]</a></li>
					<li><a href="https://ptah.ub.uni-tuebingen.de:4445/Search/Results?lookfor=superior_ppn%3A832783099&type=AllFields&sort=title&botprotect=">Religion Past and Present Online [Brill]</a></li>
					<li><a href="https://ptah.ub.uni-tuebingen.de:4445/Search/Results?lookfor=superior_ppn%1795825812&type=AllFields&sort=title&botprotect=">Religious Minorities Online [De Gruyter]</a></li>
					<li><a href="https://ptah.ub.uni-tuebingen.de:4445/Search/Results?lookfor=superior_ppn%3A1653634359&type=AllFields&sort=title&botprotect=">The Brill Dictionary of Religion Online [Brill]</a></li>
					<li><a href="https://ptah.ub.uni-tuebingen.de:4445/Search/Results?lookfor=superior_ppn%3A1809053870&type=AllFields&sort=title&botprotect=">The Encyclopedia of Christianity Online [Brill]</a></li>
					<li><a href="https://ptah.ub.uni-tuebingen.de:4445/Search/Results?lookfor=superior_ppn%1648438466&type=AllFields&sort=title&botprotect=">Theologische Realenzyklopädie [De Gruyter]</a></li>
					<li><a href="https://ptah.ub.uni-tuebingen.de:4445/Search/Results?lookfor=superior_ppn%3A837395917&type=AllFields&limit=20&sort=title&botprotect=">Vocabulary for the Study of Religion Online [Brill]</a></li>
					<li><a href="https://ptah.ub.uni-tuebingen.de:4445/Search/Results?lookfor=superior_ppn%3A896670716&type=AllFields&sort=title&botprotect=">WiBiLex – Das wissenschaftliche Bibellexikon im Internet [Open Access - Deutsche Bibelgesellschaft]</a></li>
					<li><a href="https://ptah.ub.uni-tuebingen.de:4445/Search/Results?lookfor=superior_ppn%3A896670740&type=AllFields&sort=title&botprotect=">WiReLex – Das Wissenschaftlich-Religionspädagogische Lexikon im Internet [Open Access - Deutsche Bibelgesellschaft]</a></li>
					<li><a href="https://ptah.ub.uni-tuebingen.de:4445/Search/Results?lookfor=superior_ppn%3A1809051452&type=AllFields&limit=20&sort=title&botprotect=">World Christian Encyclopedia Online [Brill]</a></li>
				</ol>
				<h3 class="cw-h3">Weitere vorgesehene Lexika:</h3>
				<ol>
					<li><a href="https://ptah.ub.uni-tuebingen.de:4445/Record/1667206990">Augustinus-Lexikon online (AL) [Schwabe Verlag]</a></li>
					<li><a href="https://ptah.ub.uni-tuebingen.de:4445/Record/1793495394">Dizionario dei Protestanti in Italia [Open Access – Società di Studi Valdesi]</a></li>
					<li><a href="https://ptah.ub.uni-tuebingen.de:4445/Record/783963122">Images of the Biblical World [De Gruyter]</a></li>
				</ol>
            </div>
        </div>
    </div>
</div>
