<div class="cw-row">
    <div class="cw-col-lg-12 cw-ml-lg-4">
        <div class="cw-text-block"><br>
            <h1 class="cw-h1">Bibliothekarische Verbände</h1>

            <p>IxTheo ist eng mit verschiedenen theologisch-bibliothekarischen Verbänden vernetzt. Im Rahmen von Tagungen und Konferenzen findet ein regelmäßiger Austausch statt.</p>
            <p>Aktuell gibt es Kooperationen mit folgenden bibliothekarischen Verbänden:</p>
            <ul>
                <li>AKThB (Arbeitsgemeinschaft Katholisch-Theologischer Bibliotheken)</li>
                <li>BETH (Bibliothèques Européennes de Théologie)</li>
                <li>VkwB (Verband kirchlich-wissenschaftlicher Bibliotheken)</li>
            </ul>
            <p>IxTheo ist offen für neue Kooperationen und Partnerschaften mit bibliothekarischen Verbänden und Zusammenschlüssen. Wenn Sie Interesse an einer Zusammenarbeit haben, wenden Sie sich gerne an <a href="mailto:ixtheo@ub.uni-tuebingen.de">ixtheo@ub.uni-tuebingen.de</a>.</p>
        </div>
    </div>
</div>