<?php
    $this->assetManager()->appendStyleLink('vendor/fontawesome-free-6/awesome.css');
    $this->assetManager()->appendStyleLink('vendor/fontawesome-free-6/solid.css');
?>

<section class="cw-p-2">
    <div id="map" class="map"></div>
    <?php $jsSnippet = <<<EOD
    $(function () {
        IxTheo2.loadMap('ver');
    });
    EOD;
    ?>
<?=$this->assetManager()->outputInlineScriptString($jsSnippet)?>
</section>
<div class="cw-row">
    <div class="cw-col-lg-12 cw-ml-lg-4">
        <div class="cw-text-block"><br>
            <h1 class="cw-h1">Library Associations</h1>

            <p>IxTheo keeps close ties with various theological library associations. We exchange information during conferences and meetings on a regular basis.</p>
            <p>We currently cooperate with the following library associations:</p>
            <ul>
                <li>AKThB (Arbeitsgemeinschaft Katholisch-Theologischer Bibliotheken)</li>
                <li>BETH (Bibliothèques Européennes de Théologie)</li>
                <li>VkwB (Verband kirchlich-wissenschaftlicher Bibliotheken)</li>
            </ul>
            <p>IxTheo is always interested in new cooperations and partnerships with library associations. If you are interested in working with us, please contact us at: <a href="mailto:ixtheo@ub.uni-tuebingen.de">ixtheo@ub.uni-tuebingen.de</a>.</p>
        </div>
    </div>
</div>