<?php
    $this->assetManager()->appendStyleLink('vendor/fontawesome-free-6/awesome.css');
    $this->assetManager()->appendStyleLink('vendor/fontawesome-free-6/solid.css');
?>

<section class="cw-p-2">
    <div id="map" class="map"></div>
    <?php $jsSnippet = <<<EOD
    $(function () {
        IxTheo2.loadMap('bibliotheken');
    });
    EOD;
    ?>
<?=$this->assetManager()->outputInlineScriptString($jsSnippet)?>
</section>
<div class="cw-row">
    <div class="cw-col-lg-12 cw-ml-lg-4">
        <div class="cw-text-block"><br>
            <h1 class="cw-h1">Bibliotheken</h1>
            <p>Theologisch relevante Bestände aus verschiedenen Bibliotheken werden im Index Theologicus (IxTheo) nachgewiesen. Auch darüber hinaus gibt es vielfältige gemeinsame Projekte.</p>
            <p>Aktuell arbeitet IxTheo mit folgenden Bibliotheken zusammen:</p>
            <ul>
                <li>Augustijns Historisch Instituut (AHI), Leuven (Heverlee) </li>
                <li>Bibliothek des Internationalen Katholischen Missionswerkes missio e.V. (mikado), Aachen [vorgesehen]</li>
                <li>Diözesanbibliothek Münster</li>
                <li>Erzbischöfliche Diözesan- und Dombibliothek Köln mit Bibliothek St. Albertus Magnus</li>
				<li>Evangelische Hochschul- und Zentralbibliothek Württemberg (EHZ-Bibliothek)</li>
                <li>Forschungsbibliothek Gotha </li>
                <li>Franckesche Stiftungen zu Halle </li>
                <li>Institut für Theologie und Frieden (ithf), Hamburg</li>
                <li>Johannes a Lasco Bibliothek, Emden</li>
                <li>Maurits-Sabbe-Bibliothek, Leuven</li>
                <li>Princeton Theological Seminary</li>
                <li>Reformationsgeschichtliche Forschungsbibliothek Wittenberg</li>
                <li>Zentrum für Augustinus-Forschung (ZAF), Würzburg</li>
            </ul>
            <p>IxTheo ist offen für Kooperationen und Partnerschaften mit weiteren Bibliotheken. Wenn Sie Interesse an einer Zusammenarbeit haben, wenden Sie sich gerne an <a href="mailto:ixtheo@ub.uni-tuebingen.de">ixtheo@ub.uni-tuebingen.de</a>.</p>
        </div>
    </div>
</div>