<section class="cw-p-2">
    <?php $this->headScript()->appendFile('vendor/ol/ol.js');?>
    <?php $this->headScript()->appendFile('vendor/ol/wrapper.js');?>
    <?php $this->headLink()->appendStylesheet('vendor/ol/ol.css');?>
    <div id="map" class="map"></div>
    <div id="popup" class="ol-popup">
        <a href="#" id="popup-closer" class="ol-popup-closer">x</a>
        <div id="popup-content"></div>
    </div>
    <?php
        $partners = [
            // Cooperations
            [   'lon' => '11.384495',
                'lat' => '47.263359',
                'group' => 'cooperation',
                'logo' => $this->imageLink('partners/logo-uibk.svg'),
                'url' => '//www.uibk.ac.at/theol/theoldi/index.html.de',
                'popup' => '<font color="black"><b><a href="//www.uibk.ac.at/theol/theoldi/index.html.de" target="_blank">Theoldi</a></b><br>Universität Innsbruck<br>Innrain 52<br>A-6020 Innsbruck<br><br><img src="'.$this->imageLink('partners/logo-uibk.svg').'" width="180"></font>',
            ],
            [   'lon' => '7.62560',
                'lat' => '51.96262',
                'group' => 'cooperation',
                'logo' => $this->imageLink('partners/wwu.svg'),
                'url' => '//www.uni-muenster.de/FB2/ikr/datenbank/index.shtml',
                'popup' => '<font color="black"><b><a href="//www.uni-muenster.de/FB2/ikr/datenbank/index.shtml" target="_blank">DaKaR</a></b><br>Institut für Kanonisches Recht<br>Domplatz 23<br>D-48143 Münster<br><br><img src="'.$this->imageLink('partners/wwu.svg').'" width="180"></font>',
            ],
            [   'lon' => '9.93202',
                'lat' => '49.79608',
                'group' => 'cooperation',
                'logo' => $this->imageLink('partners/ZAF_Logo_3.png'),
                'logo_wrap' => ['start' => '<div style="background-color: red; text-align: center;">', 'end' => '</div>'],
                'url' => '//www.augustinus.de',
                'popup' => '<font color="black"><b><a href="//www.augustinus.de" target="_blank">Augustinus-Forschungsdatenbank</a></b><br>Zentrum für Augustinusforschung<br>Dominikanerplatz 4<br>D-97070 Würzburg<br><br><div style="background-color: red; text-align: center;"><img src="'.$this->imageLink('partners/ZAF_Logo_3.png').'" width="180"></div></font>',
            ],
            [   'lon' => '6.95137',
                'lat' => '50.94415',
                'group' => 'cooperation',
                'logo' => $this->imageLink('partners/logo_bibliothek_2017_10_24_420x70.jpg'),
                'url' => '//dombibliothek-koeln.de',
                'popup' => '<font color="black"><b><a href="//dombibliothek-koeln.de" target="_blank">Erzbischöfliche Diözesan- und Dombibliothek Köln</a></b><br> Kardinal-Frings-Straße 1-3<br>D-50668 Köln<br><br><img src="'.$this->imageLink('partners/logo_bibliothek_2017_10_24_420x70.jpg').'" width="180"></font>',
            ],
            // Protestant Community
            [   'lon' => '8.77202',
                'lat' => '50.80794',
                'group' => 'protestant',
                'logo' => $this->imageLink('partners/logo-marburg.svg'),
                'url' => '//www.uni-marburg.de/de/fb05/fachgebiete/fachgebiete/systematische-theologie/personal/prof-dr-krueger-1',
                'popup' => '<font color="black"><b><a href="//www.uni-marburg.de/de/fb05/fachgebiete/fachgebiete/systematische-theologie/personal/prof-dr-krueger-1" target="_blank">Prof. Dr. Malte Krüger</a></b><br>Philipps-Universität Marburg<br>Lahntor 3<br>D-35032 Marburg<br><br><img src="'.$this->imageLink('partners/logo-marburg.svg').'" width="180"></font>',
            ],
            [   'lon' => '9.98460',
                'lat' => '53.55749',
                'group' => 'protestant',
                'logo' => $this->imageLink('partners/logo-hamburg.svg'),
                'url' => '//www.theologie.uni-hamburg.de/einrichtungen/kontakt/kristin-merle.html',
                'popup' => '<font color="black"><b><a href="//www.theologie.uni-hamburg.de/einrichtungen/kontakt/kristin-merle.html" target="_blank">Prof. Dr. Kristin Merle</a></b><br>Universität Hamburg<br>Institut für Praktische Theologie<br>Gorch-Fock-Wall 7<br>D-20354 Hamburg<br><br><img src="'.$this->imageLink('partners/logo-hamburg.svg').'" width="180"></font>',
            ],
            [   'lon' => '10.11030',
                'lat' => '54.34504',
                'group' => 'protestant',
                'logo' => $this->imageLink('partners/logo-kiel.svg'),
                'url' => '//www.theol.uni-kiel.de/de/professuren/kg-mueller/team/mueller',
                'popup' => '<font color="black"><b><a href="//www.theol.uni-kiel.de/de/professuren/kg-mueller/team/mueller" target="_blank">Prof. Dr. Andreas Müller</a></b><br>Christian-Albrechts-Universität zu Kiel<br>Theologische Fakultät<br>Leibnitzstr. 4<br>D-24118 Kiel<br><br><img src="'.$this->imageLink('partners/logo-kiel.svg').'" width="180"></font>',
            ],
            [   'lon' => '8.54461',
                'lat' => '47.37001',
                'group' => 'protestant',
                'logo' => $this->imageLink('partners/logo-zuerich.jpg'),
                'url' => '//www.theologie.uzh.ch/de/faecher/altes-testament/Lehrst%C3%BChle-und-Personen/konrad-schmid.html',
                'popup' => '<font color="black"><b><a href="//www.theologie.uzh.ch/de/faecher/altes-testament/Lehrst%C3%BChle-und-Personen/konrad-schmid.html" target="_blank">Prof. Dr. Konrad Schmid</a></b><br>Universität Zürich<br>Kirchgasse 9<br>CH-8001 Zürich<br><br><img src="'.$this->imageLink('partners/logo-zuerich.jpg').'" width="180"></font>',
            ],
            [   'lon' => '9.05533',
                'lat' => '48.52535',
                'group' => 'protestant',
                'logo' => $this->imageLink('Logo_Universitaet_Tuebingen.svg'),
                'url' => '//uni-tuebingen.de/fakultaeten/evangelisch-theologische-fakultaet/lehrstuehle-und-institute/kirchengeschichte/kirchengeschichte-i/mitarbeiter/leppin-volker-prof-dr/',
                'popup' => '<font color="black"><b><a href="//uni-tuebingen.de/fakultaeten/evangelisch-theologische-fakultaet/lehrstuehle-und-institute/kirchengeschichte/kirchengeschichte-i/mitarbeiter/leppin-volker-prof-dr/" target="_blank">Prof. Dr. Volker Leppin</a></b><br>Eberhard Karls Universität Tübingen<br>Evangelisch-Theologische Fakultät<br>Liebermeisterstr. 12<br>D-72076 Tübingen<br><br><img src="'.$this->imageLink('Logo_Universitaet_Tuebingen.svg').'" width="180"></font>',
            ],
            // Catholic Community
            [   'lon' => '8.77052',
                'lat' => '51.70649',
                'group' => 'catholic',
                'logo' => $this->imageLink('partners/logo-paderborn.png'),
                'url' => '//kw.uni-paderborn.de/institut-fuer-katholische-theologie/praktische-theologie/team/prof-dr-rita-burrichter/',
                'popup' => '<font color="black"><b><a href="//kw.uni-paderborn.de/institut-fuer-katholische-theologie/praktische-theologie/team/prof-dr-rita-burrichter/" target="_blank">Prof. Dr. Rita Burrichter</a></b><br>Universität Paderborn<br>Pohlweg 55<br>D-33098 Paderborn<br><br><img src="'.$this->imageLink('partners/logo-paderborn.png').'" width="180"></font>',
            ],
            [   'lon' => '11.57980',
                'lat' => '48.15049',
                'group' => 'catholic',
                'logo' => $this->imageLink('partners/logo-muenchen.jpg'),
                'url' => '//www.kaththeol.uni-muenchen.de/lehrstuehle/bibl_einleitung/personen/haefner/index.html',
                'popup' => '<font color="black"><b><a href="//www.kaththeol.uni-muenchen.de/lehrstuehle/bibl_einleitung/personen/haefner/" target="_blank">Prof. Dr. Gerd Häfner</a></b><br>Ludwig-Maximilians-Universität München<br>Katholisch-Theologische Fakultät<br>Geschwister-Scholl-Platz 1<br>D-80539 München<br><br><img src="'.$this->imageLink('partners/logo-muenchen.jpg').'" width="180"></font>',
            ],
            [   'lon' => '7.60707',
                'lat' => '51.95951',
                'group' => 'catholic',
                'logo' => $this->imageLink('partners/wwu.svg'),
                'url' => '//www.uni-muenster.de/FB2/personen/ics/heimbach-steins.html',
                'popup' => '<font color="black"><b><a href="//www.uni-muenster.de/FB2/personen/ics/heimbach-steins.html" target="_blank">Prof. Dr. Marianne Heimbach-Steins</a></b><br>WWU Münster<br>Institut für Christliche Sozialwissenschaft<br>Robert-Koch-Str. 29<br>D-48149 Münster<br><br><img src="'.$this->imageLink('partners/wwu.svg').'" width="180"></font>',
            ],
            [   'lon' => '12.0962',
                'lat' => '48.9964',
                'group' => 'catholic',
                'logo' => $this->imageLink('partners/logo-regensburg.gif'),
                'url' => '//www.uni-regensburg.de/theologie/mittlere-und-neue-kirchengeschichte/personen/prof-dr-klaus-unterburger/',
                'popup' => '<font color="black"><b><a href="//www.uni-regensburg.de/theologie/mittlere-und-neue-kirchengeschichte/personen/prof-dr-klaus-unterburger/" target="_blank">Prof. Dr. Klaus Unterburger</a></b><br>Universität Regensburg<br>Fakultät für Katholische Theologie<br>Universitätsstr. 31<br>D-93040 Regensburg<br><br><img src="'.$this->imageLink('partners/logo-regensburg.gif').'" width="180"></font>',
            ],
            [   'lon' => '9.05555',
                'lat' => '48.52561',
                'group' => 'catholic',
                'logo' => $this->imageLink('Logo_Universitaet_Tuebingen.svg'),
                'url' => '//uni-tuebingen.de/fakultaeten/katholisch-theologische-fakultaet/lehrstuehle/praktische-theologie/lehrstuhl-fuer-praktische-theologie/team/prof-dr-michael-schuessler/',
                'popup' => '<font color="black"><b><a href="//uni-tuebingen.de/fakultaeten/katholisch-theologische-fakultaet/lehrstuehle/praktische-theologie/lehrstuhl-fuer-praktische-theologie/team/prof-dr-michael-schuessler/" target="_blank">Prof. Dr. Michael Schüßler</a></b><br>Eberhard Karls Universität Tübingen<br>Katholisch-Theologische Fakultät<br>Liebermeisterstr. 12<br>D-72076 Tübingen<br><br><img src="'.$this->imageLink('Logo_Universitaet_Tuebingen.svg').'" width="180"></font>',
            ],
            // Tuebingen (should be last entries so they overwrite earlier drawn markers)
            [
                'lon' => '9.06178',
                'lat' => '48.52515',
                'group' => 'tuebingen',
                'logo' => $this->imageLink('Logo_Universitaet_Tuebingen.svg'),
                'url' => '//uni-tuebingen.de/fakultaeten/katholisch-theologische-fakultaet/lehrstuehle/praktische-theologie/lehrstuhl-fuer-praktische-theologie/team/prof-dr-michael-schuessler/',
                'popup' => '<font color="black"><b><a href="//ub.uni-tuebingen.de" target="_blank">Index Theologicus</a></b><br>Universitätsbibliothek Tübingen<br>Wilhelmstr. 32<br>D-72074 Tübingen<br><br><img src="' . $this->imageLink('Logo_Universitaet_Tuebingen.svg'). '" width="180"></font>',
            ],
        ];
        $partners = json_encode($partners);
    ?>

<?php $jsSnippet = <<<EOD
$(function () {

    let partnersArray = {$partners};
   
    // Add markers to new or existing map
    function AddMarkers(highlightGroup=null) {
        let markers = {
            'default': "{$this->imageLink('ol/marker.svg')}",
            'highlight': "{$this->imageLink('ol/marker-tuebingen.png')}",
            'tuebingen': "{$this->imageLink('ol/marker-tuebingen.png')}",
            'cooperation': "{$this->imageLink('ol/marker-green.png')}",
            'protestant': "{$this->imageLink('ol/marker-purple.png')}",
            'catholic': "{$this->imageLink('ol/marker-black.png')}"
        };

        let marker = markers.default;
        partnersArray.forEach(function(oneParter){
            marker = markers.default;
            if (highlightGroup != null && highlightGroup === oneParter.group){
                if(markers.hasOwnProperty(highlightGroup)) {
                    marker = markers[highlightGroup];
                }
            }
            OpenStreetMapWrapper.AddLocation(oneParter.lon, oneParter.lat, marker, oneParter.popup);
        });
        
    }

    // Initial drawing of the map
    function DrawMap() {
        OpenStreetMapWrapper.DrawMap(12.810, 51.352, /* zoom */ 5, /* proxy */ '/proxy/load?');
        AddMarkers();
        OpenStreetMapWrapper.BuildLocationLayer();
    }

    // Re-use existing map, remove location/marker layer and re-draw markers
    function HighlightMarkerGroup(highlightGroup) {
        OpenStreetMapWrapper.ResetLocationLayer();
        AddMarkers(highlightGroup);
        OpenStreetMapWrapper.BuildLocationLayer();
    }

    $('.high-light-marker-group').click(function(){
        let lightGroup = $(this).data('group');
        OpenStreetMapWrapper.ResetLocationLayer();
        AddMarkers(lightGroup);
        OpenStreetMapWrapper.BuildLocationLayer();
    })

    $(function() {
        DrawMap();
    });
});
EOD;
?>
<?=$this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, $jsSnippet, 'SET')?>

    <div class="cw-py-2 map-navigation">
        <div class="map-cooperation high-light-marker-group" data-group="cooperation" ><button>Kooperationen</button></div>
        <div class="map-catholic high-light-marker-group" data-group="catholic"><button>Katholische Fachcommunity</button></div>
        <div class="map-protestant high-light-marker-group" data-group="protestant"><button>Evangelische Fachcommunity</button></div>
        <div class="map-tuebingen high-light-marker-group" data-group="tuebingen"><button>Tübingen</button></div>
    </div>
</section>

<section class="cw-py-5 bg-gray-100 shadow">
    <div class="cw-container">
        <h1 class="cw-h1">Networking</h1>
        <p class="cw-lead">
            Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi.
        </p>
    </div>
</section>


<section class="cw-py-5">
    <div class="cw-container panel-group">
        <div class="cw-row">
            <!-- item-->
            <div class="col-sm-6 col-lg-4 cw-mb-5 hover-animate tf-cursor-pointer">
                <a href="<?=$this->url('content-page', ['page' => 'theological_community']) ?>">
                    <div data-toggle="collapse" data-target="#collapse-inno-1">
                        <div class="cw-card h-100 border-0 shadow">
                            <div class="cw-card-img-top cw-overflow-hidden cw-dark-overlay cw-bg-cover networking-image-1">
                                <div class="cw-card-img-overlay-bottom cw-z-index-20">
                                    <h4 class="cw-h4 cw-text-white cw-text-shadow">Theologische Community</h4>
                                </div>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <!-- end item-->

            <!-- item-->
            <div class="col-sm-6 col-lg-4 cw-mb-5 hover-animate tf-cursor-pointer">
                <a href="<?=$this->url('content-page', ['page' => 'librarian_associations']) ?>">
                    <div data-toggle="collapse" data-target="#collapse-inno-1">
                        <div class="cw-card h-100 border-0 shadow">
                            <div class="cw-card-img-top cw-overflow-hidden cw-dark-overlay cw-bg-cover networking-image-2">
                                <div class="cw-card-img-overlay-bottom cw-z-index-20">
                                    <h4 class="cw-h4 cw-text-white cw-text-shadow">Bibliothekarische Verbände</h4>
                                 </div>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <!-- end item-->

            <!-- item-->
            <div class="col-sm-6 col-lg-4 cw-mb-5 hover-animate tf-cursor-pointer">
                <a href="<?=$this->url('content-page', ['page' => 'speakers']) ?>">
                    <div data-toggle="collapse" data-target="#collapse-inno-1">
                        <div class="cw-card h-100 border-0 shadow">
                            <div class="cw-card-img-top cw-overflow-hidden cw-dark-overlay cw-bg-cover networking-image-3">
                                <div class="cw-card-img-overlay-bottom cw-z-index-20">
                                    <h4 class="cw-h4 cw-text-white cw-text-shadow">Fachreferent*innen und theologische Bibliothekar*innen</h4>
                                </div>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <!-- end item-->

            <!-- item-->
            <div class="col-sm-6 col-lg-3 cw-mb-5 hover-animate tf-cursor-pointer">
                <a href="<?=$this->url('content-page', ['page' => 'bibliographies']) ?>">
                    <div data-toggle="collapse" data-target="#collapse-inno-1">
                        <div class="cw-card h-100 border-0 shadow">
                            <div class="cw-card-img-top cw-overflow-hidden cw-dark-overlay cw-bg-cover networking-image-4">
                                <div class="cw-card-img-overlay-bottom cw-z-index-20">
                                    <h4 class="cw-h4 cw-text-white cw-text-shadow">Bibliographies</h4>
                                </div>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <!-- end item-->

            <!-- item-->
            <div class="col-sm-6 col-lg-3 cw-mb-5 hover-animate tf-cursor-pointer">
                <a href="<?=$this->url('content-page', ['page' => 'libraries']) ?>">
                    <div data-toggle="collapse" data-target="#collapse-inno-1">
                        <div class="cw-card h-100 border-0 shadow">
                            <div class="cw-card-img-top cw-overflow-hidden cw-dark-overlay cw-bg-cover networking-image-5">
                                <div class="cw-card-img-overlay-bottom cw-z-index-20">
                                    <h4 class="cw-h4 cw-text-white cw-text-shadow">Bibliotheken</h4>
                                </div>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <!-- end item-->

            <!-- item-->
            <div class="col-sm-6 col-lg-3 cw-mb-5 hover-animate tf-cursor-pointer">
                <a href="<?=$this->url('content-page', ['page' => 'specialist_information_services']) ?>">
                    <div data-toggle="collapse" data-target="#collapse-inno-1">
                        <div class="cw-card h-100 border-0 shadow">
                            <div class="cw-card-img-top cw-overflow-hidden cw-dark-overlay cw-bg-cover networking-image-6">
                                <div class="cw-card-img-overlay-bottom cw-z-index-20">
                                    <h4 class="cw-h4 cw-text-white cw-text-shadow">Fachinformationsdienste (FID)</h4>
                                </div>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <!-- end item-->

            <!-- item-->
            <div class="col-sm-6 col-lg-3 cw-mb-5 hover-animate tf-cursor-pointer">
                <a href="<?=$this->url('content-page', ['page' => 'publishers']) ?>">
                    <div data-toggle="collapse" data-target="#collapse-inno-1">
                        <div class="cw-card h-100 border-0 shadow">
                            <div class="cw-card-img-top cw-overflow-hidden cw-dark-overlay cw-bg-cover networking-image-7">
                                <div class="cw-card-img-overlay-bottom cw-z-index-20">
                                    <h4 class="cw-h4 cw-text-white cw-text-shadow">Verlage</h4>
                                </div>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <!-- end item-->

        </div>
    </div>
</section>

<style>
.networking-image-1 {
    background-image: url(/themes/ixtheo2/images/networking/TheolCommunity.jpg);
    min-height: 200px;
}
.networking-image-2 {
    background-image: url(/themes/ixtheo2/images/networking/BibliothekarischeVerbände.jpg);
    min-height: 200px;
}
.networking-image-3 {
    background-image: url(/themes/ixtheo2/images/networking/Fachreferenten.jpg);
    min-height: 200px;
}
.networking-image-4 {
    background-image: url(/themes/ixtheo2/images/networking/Bibliographien.jpg);
    min-height: 200px;
}
.networking-image-5 {
    background-image: url(/themes/ixtheo2/images/networking/Bibliotheken.jpg);
    min-height: 200px;
}
.networking-image-6 {
    background-image: url(/themes/ixtheo2/images/networking/Fachinformationsdienste.jpg);
    min-height: 200px;
}
.networking-image-7 {
    background-image: url(/themes/ixtheo2/images/networking/Verlage.jpg);
    min-height: 200px;
}
</style>
