<div class="cw-row">
  <div class="cw-col-lg-12 cw-ml-lg-4">
    <div class="cw-text-block"><br>
      <span id="self-archiving">&nbsp;</span>
      <h1 class="cw-h1">Self-Archiving</h1> 
      <div class="row">
        <div class="col-md-3">
          <img src="<?=$this->imageLink('slider/mode/pexels-anete-lusina.jpg')?>" />
        </div>
        <div class="col-md-9">
          <p>Ab sofort können Sie Zweitveröffentlichungen Ihrer Publikationen über IxTheo selbst hochladen und im Open Access zur Verfügung stellen.</p>
          <p>Das erhöht die internationale Sichtbarkeit Ihrer Forschung: Alle zweitveröffentlichten Texte sind sofort weltweit abrufbar und über IxTheo recherchierbar.</p>
          <p>Für das Self-Archiving benötigen Sie lediglich einen kostenlosen IxTheo Account. Nach einer einmaligen Registrierung können Sie jederzeit mit wenigen Klicks eigene Publikationen als pdf-Datei hochladen. <a target="_blank" href="<?=$this->url('content-page', ['page' => 'PublicationFAQ']) ?>#content">Zur Anleitung</a> </p>
        </div>
      </div>
      <p class="ix-news-date">(Oktober 2024)</p>
      
      <span id="aggregator">&nbsp;</span>
      <h1 class="cw-h1">Alerting für Blogs und Podcasts</h1>
      <div class="row">
        <div class="col-md-3">
          <img src="<?=$this->imageLink('slider/mode/pexels-george-milton.jpg')?>" />
        </div>
        <div class="col-md-9">
          <p>Mit dem Feed-Aggregator haben Sie eine komfortable Möglichkeit, sich über neue Beiträge aus verschiedenen theologisch relevanten Blogs und Podcasts zu informieren.</p>
          <p>Sobald neue Beiträge und Folgen Ihrer bevorzugten Blogs und Podcasts erscheinen, erhalten Sie automatisch eine Benachrichtigung per E-Mail. Alternativ kann ein persönlicher RSS-Feed erstellt werden. <a target="_blank" href="<?=$this->url('content-page', ['page' => 'alerting']) ?>#content">Wie richte ich eine Benachrichtigung oder einen Feed ein?</a></p>
          <p>Alle Blogs und Podcasts finden Sie unter: <a target="_blank" href="https://ixtheo.de/RssFeed/Full">https://ixtheo.de/RssFeed/Full</a> </p>
        </div>
      </div>
      <p class="ix-news-date">(Oktober 2024)</p>


      <span id="personenseiten">&nbsp;</span>
      <h1 class="cw-h1">Personenseiten</h1>
      <div class="row">
        <div class="col-md-3">
          <img src="<?=$this->imageLink('slider/mode/pexels-gabby.jpg')?>" />
        </div>
        <div class="col-md-9">
          <p>Die Personenseiten ermöglichen eine gezielte Recherche zu Autor*innen. Hier finden Sie nicht nur alle im IxTheo verzeichneten Publikationen der Person und weitere Informationen dazu (häufig behandelte Schlagworte, Publikationsstatistik u.ä.), sondern auch biographische Angaben und Links zu weiteren relevanten Datenbanken. "Zur Personensuche"</p>
        </div>
      </div>
      <p class="ix-news-date">(Oktober 2024)</p>
    </div>
  </div>
</div>

<style>
  .ix-news-date {
    font-weight: 700;
}
</style>
