<div class="cw-row">
  <div class="cw-col-lg-12 cw-ml-lg-4">
    <div class="cw-text-block"><br>
      <span id="self-archiving">&nbsp;</span>
      <h1 class="cw-h1">Self-Archiving</h1>
      <div class="row">
        <div class="col-md-3">
          <img src="<?=$this->imageLink('slider/mode/pexels-anete-lusina.jpg')?>" />
        </div>
        <div class="col-md-9">
          <p>Ab sofort können Sie Zweitveröffentlichungen Ihrer Publikationen über IxTheo selbst hochladen und im Open Access zur Verfügung stellen.</p>
          <p>Das erhöht die internationale Sichtbarkeit Ihrer Forschung: Alle zweitveröffentlichten Texte sind sofort weltweit abrufbar und über IxTheo reche>
          <p>Für das Self-Archiving benötigen Sie lediglich einen kostenlosen IxTheo Account. Nach einer einmaligen Registrierung können Sie jederzeit mit we>
        </div>
      </div>
      <span id="aggregator">&nbsp;</span>
      <h1 class="cw-h1">Alerting für Blogs und Podcasts</h1>
      <div class="row">
        <div class="col-md-3">
        <img src="<?=$this->imageLink('innovativ/mode/Podcast.jpg')?>" />
        </div>
        <div class="col-md-9">
          <p>Mit dem Feed-Aggregator haben Sie eine komfortable Möglichkeit, sich über neue Beiträge aus verschiedenen theologisch relevanten Blogs und Podca>
          <p>Sobald neue Beiträge und Folgen Ihrer bevorzugten Blogs und Podcasts erscheinen, erhalten Sie automatisch eine Benachrichtigung per E-Mail. Alte>
          <p>Alle Blogs und Podcasts finden Sie unter: <a target="_blank" href="https://ixtheo.de/RssFeed/Full">https://ixtheo.de/RssFeed/Full</a> </p>
        </div>
      </div>
      <p class="ix-news-date">(Dezember 2024)</p>
      <span id="personenseiten">&nbsp;</span>
      <h1 class="cw-h1">Personenseiten</h1>
      <div class="row">
        <div class="col-md-3">
          <img src="<?=$this->imageLink('slider/mode/pexels-gabby.jpg')?>" />
        </div>
        <div class="col-md-9">
          <p>Die Personenseiten ermöglichen eine gezielte Recherche zu Autor*innen. Hier finden Sie nicht nur alle im IxTheo verzeichneten Publikationen der >
        </div>
      </div>
      <p class="ix-news-date">(Oktober 2024)</p>
    </div>
  </div>
</div>

<style>
  .ix-news-date {
    font-weight: 700;
}
</style>
