<div class="cw-row">
  <div class="cw-col-lg-12 cw-ml-lg-4">
    <div class="cw-text-block"><br>
      <span id="new_homepage">&nbsp;</span>
      <h1 class="cw-h1">New IxTheo Homepage</h1>
      <div class="row">
        <div class="col-md-3">
          <img src="<?=$this->imageLink('slider/mode/hands-2178566_640.jpg')?>" alt="<?=$this->transEscAttr('symbolic_image_table63');?>" />
        </div>
        <div class="col-md-9">
          <p>The Index Theologicus will appear from July 2025 with a new design.</p>
          <p>On the new homepage, you will find comprehensive information on the features of IxTheo, on the various kinds of publications listed and on the services of the Fachinformationsdienst Theologie (Special Information Service in Theology).</p>
          <p>In addition, we are happy to present our cooperation partners and our network in more detail.</p>
		  <p>We wish you a pleasant time exploring our new site!</p>
        </div>
      </div>
      <p class="ix-news-date">(July 2025)</p>
	  <span id="self-archiving">&nbsp;</span>
      <h1 class="cw-h1">Self-Archiving</h1>
      <div class="row">
        <div class="col-md-3">
          <img src="<?=$this->imageLink('slider/mode/pexels-anete-lusina.jpg')?>" alt="<?=$this->transEscAttr('symbolic_image_table8');?>" />
        </div>
        <div class="col-md-9">
          <p>You can now self-archive your publications and make them available in Open Access by uploading them on IxTheo.</p>
          <p>This enhances the visibility of your research at the international level, since all self-archived texts are immediately accessible all over the world and are searchable on IxTheo.</p>
          <p>In order to use our self-archiving service, you only need a free IxTheo account. Once you’ve registered, you can upload your own publications as pdf files with just a few clicks. <a target="_blank" href="<?=$this->url('content-page', ['page' => 'PublicationFAQ']) ?>#content">Manual for Self-Archiving</a> </p>
        </div>
      </div>
      <p class="ix-news-date">(February 2025)</p>

      <span id="aggregator">&nbsp;</span>
      <h1 class="cw-h1">Alerting for Blogs und Podcasts</h1>
      <div class="row">
        <div class="col-md-3">
          <img src="<?=$this->imageLink('innovativ/mode/Podcast.jpg')?>" alt="<?=$this->transEscAttr('symbolic_image_table50');?>" />
        </div>
        <div class="col-md-9">
          <p>Thanks to our feed aggregator, you can easily get information on new postings and episodes from various blogs and podcasts of interest for theological research.</p>
          <p>As soon as new postings or episodes from your favorite blogs and podcasts are available, you automatically get a notification per e-mail. You can also set up a personal RSS feed.  <a target="_blank" href="<?=$this->url('content-page', ['page' => 'Alerting']) ?>#content">How can I get alerts or set up a feed?</a></p>
          <p>You can find all blogs and podcasts under: <a target="_blank" href="https://ixtheo.de/RssFeed/Full">https://ixtheo.de/RssFeed/Full</a> </p>
        </div>
      </div>
      <p class="ix-news-date">(December 2024)</p>

      <span id="personenseiten">&nbsp;</span>
      <h1 class="cw-h1">Person Information Pages</h1>
      <div class="row">
        <div class="col-md-3">
          <img src="<?=$this->imageLink('slider/mode/pexels-gabby.jpg')?>" alt="<?=$this->transEscAttr('symbolic_image_table10');?>" />
        </div>
        <div class="col-md-9">
          <p>Person Information Pages provide comprehensive information on an author. An author’s information page provides not only access to all of this author’s publications catalogued in IxTheo, but also additional information such as keywords most often associated with this author, publication statistics, biographical information and links to other relevant databases. <a target="_blank" href="<?=$this->url('content-page', ['page' => 'AuthorityPages']) ?>#content">Further Information on Person Information Pages</a></p>
        </div>
      </div>
      <p class="ix-news-date">(October 2024)</p>
    </div>
  </div>
</div>

<style>
  .ix-news-date {
    font-weight: 700;
}
</style>
