<div class="container cw-py-5">
  <div class="cw-row">
    <div class="cw-col-lg-8">
      <div class="cw-text-block">
        <h1 class="cw-h1">User-Driven Literature Purchases</h1>
        <p>There are various ways to ask IxTheo to purchase literature which you might need for your research and to which you currently have no access.</p>

        <h1 class="cw-h5">Patron Driven Acquisition (PDA): Print</h1>
        <p>If a book which you found in IxTheo is not available in any academic library in Germany, it is indicated in the description of the book (under “Book acquisition”).</p>

        <a class="thumbnail" href="#" data-image-id="" data-toggle="modal" data-title="" data-caption="" data-image="/themes/ixtheo2/images/content_img/en/acquisition_UB_eng.png" data-target="#image-gallery">
            <img class="img-responsive" src="/themes/ixtheo2/images/content_img/en/acquisition_UB_eng.png" alt="<?=$this->translate('Screenshot: A bibliographic entry in IxTheo which shows the option: “Not available in Germany: acquire free of charge via UB Tübingen”');?>">
        </a>

        <p>If you are logged into your IxTheo account, you can trigger a book purchase. We will then try to acquire this book.</p>
        <p>If we are unable to purchase it (e.g. because it is out of print), we will inform you per e-mail.</p>
        <p>If we can purchase it, we will inform you as soon as the book has arrived in Tübingen. You can then obtain it per interlibrary loan.</p>
        <p>This PDA-service is free of charge. However, your home library may charge you fees for the interlibrary loan.</p>

        <h1 class="cw-h5">Acquisition Recommendation</h1>

        <p>If you can’t find a theological book in IxTheo, you can send us a recommendation to acquire it by using <a target="_blank" href="/Feedback/Form/AcquisitionRequest">this form</a>.</p>
        <p>If we purchase this book, you can then obtain it at your home library per interlibrary loan.</p>
        <p>We do not charge you for this acquisition, but your home library may charge you fees for the interlibrary loan.</p>

        <h1 class="cw-h5">Patron Driven Acquisition (PDA): E-Books [in development]</h1>

        <p>In order to offer a quick access to the books you wish to read, IxTheo catalogs e-books from select publishing houses in cooperation with a book aggregator. You can directly trigger the purchase of these e-books in your IxTheo account and then use them immediately.<p>

        <p>This service is still in development. We plan to offer it in the course of 2025.</p>
      </div>
    </div>
  </div>
</div>
