<div class="container cw-py-5">
  <div class="cw-row">
    <div class="cw-col-lg-8">
      <div class="cw-text-block">
        <h1 class="cw-h1">Neuanschaffungen auf Nutzer*innenwunsch</h1>
        <p>IxTheo bietet Ihnen verschiedene Möglichkeiten, Titel zur Anschaffung vorzuschlagen, die Sie für Ihre 
        Forschung benötigen und auf die Sie momentan keinen Zugriff haben.</p>

        <h1 class="cw-h5">Patron Driven Acquisition (PDA): Print</h1>
        <p>Wenn ein gesuchter Buchtitel im IxTheo verzeichnet, aber in keiner wissenschaftlichen Bibliothek in 
        Deutschland vorhanden ist, wird unter „Buchbeschaffung“ ein entsprechender Hinweis angezeigt.</p>

        <a class="thumbnail" href="#" data-image-id="" data-toggle="modal" data-title="" data-caption="" data-image="/themes/ixtheo2/images/content_img/nutzer_img_1.png" data-target="#image-gallery">
            <img class="img-responsive" src="/themes/ixtheo2/images/content_img/nutzer_img_1.png" alt="<?=$this->translate('Screenshot: A bibliographic entry in IxTheo which shows the option: “Not available in Germany: acquire free of charge via UB Tübingen”');?>">
        </a>

        <p>Sobald Sie in Ihrem IxTheo Account eingeloggt sind, haben Sie nun die Möglichkeit, eine Buchbestellung auszulösen. 
        Wir werden im Anschluss versuchen, das gewünschte Buch zu erwerben.</p>
        <p>Falls der Titel nicht erworben werden kann (z.B. weil er nicht mehr lieferbar ist), informieren wir Sie per Mail.</p>
        <p>Kann das Buch angeschafft werden, erhalten Sie eine Benachrichtigung, sobald der Titel in Tübingen eingetroffen ist. 
        Sie können dann unmittelbar eine Fernleihbestellung aufgeben.</p>
        <p>Der PDA-Service ist kostenlos. Für die Bestellung der Fernleihe können Gebühren Ihrer Heimatbibliothek anfallen.</p>

        <h1 class="cw-h5">Anschaffungsvorschlag</h1>

        <p>Wenn Sie ein Buch nicht im IxTheo finden, können Sie es mit Hilfe des <a target="_blank" href="/Feedback/Form/AcquisitionRequest">hier verlinkten Formulars</a> zur Anschaffung vorschlagen.</p>
        <p>Der Titel wird von uns geprüft. Im Fall einer Anschaffung haben Sie die Möglichkeit, den Titel über die Fernleihe 
        in die von Ihnen genutzte Bibliothek zu bestellen.</p>
        <p>Die Anschaffung des gewünschten Buches ist kostenlos. Für die Bestellung der Fernleihe können Gebühren Ihrer Heimatbibliothek anfallen.</p>

        <h1 class="cw-h5">Patron Driven Acquisition (PDA): E-Books [im Aufbau]</h1>

        <p>Um einen schnellen Zugang zu gewünschten Buchtiteln zu ermöglichen, werden in Zusammenarbeit mit einem Buch-Aggregator 
        E-Books ausgewählter Verlage im IxTheo nachgewiesen. Sie können den Erwerb dieser E-Books direkt aus 
        Ihrem IxTheo Konto veranlassen und das E-Book unmittelbar nutzen.<p>

        <p>Dieser Service wird gerade aufgebaut und soll in der zweiten Jahreshälfte 2025 zur Verfügung stehen.</p>
      </div>
    </div>
  </div>
</div>
