<div class="cw-row">
    <div class="cw-col-lg-8 cw-ml-lg-4">
        <div class="cw-text-block"><br>
            <h1 class="cw-h1">Zweitveröffentlichung</h1>
            <p>Der Fachinformationsdienst Theologie fördert den freien Zugang (Open Access) zu bereits publizierten theologischen Forschungsbeiträgen. Wissenschaftler*innen aus allen Gebieten der Theologie haben verschiedene Möglichkeiten zur Zweitveröffentlichung ihrer Texte.</p>
			<br>

            <h3><b>IxTheo Self-Archiving Service (weltweit)</b></h3>
	        <p>Im Rahmen des Self-Archiving Service können Forschende aus allen theologischen Fachgebieten  Zweitveröffentlichungen ihrer wissenschaftlichen Publikationen selbst im Index Theologicus (IxTheo) hochladen und im Open Access zur Verfügung stellen.</p>
		    <p>Alle Zweitveröffentlichungen werden mit dem zugehörigen Eintrag im IxTheo verknüpft und sind für die weltweite Fachcommunity frei verfügbar.</p>
	        <p>Die Teilnahme am Self-Archiving Service ist kostenlos: Nach einer einmaligen Registrierung können eigene Publikationen jederzeit als PDF-Datei hochgeladen werden.</p>

            <h3>Vorteile für Autor*innen</h3>
            <ul>
                <li>legale und nichtkommerzielle Möglichkeit zur Zweitveröffentlichung</li>
                <li>einfache Auffindbarkeit Ihrer Beiträge und der hochgeladenen Texte im IxTheo</li>
                <li>erhöhte internationale Sichtbarkeit und Rezeption der eigenen Forschung</li>
                <li>langfristige Archivierung auf dem Fachrepositorium Theologie der UB Tübingen</li>
                <li>zitierfähiger Link (DOI), der für Forschung und Lehre verwendet werden kann</li>
                <li>freie und weltweite Zugänglichkeit von Publikationen – auch für Interessierte außerhalb von Universitäten oder in Kontexten, in denen aktuelle Forschungsliteratur sonst kaum verfügbar ist</li>
            </ul>

            <h3>Nähere Informationen</h3>
            <h5><p><a href="/Content/PublicationFAQ#content">Häufig gestellte Fragen zum Self-Archiving Service (FAQ)</a></p></h5>
			<br>

            <h3><b>IxTheo Open Text Service</b></h3>
            <p>Bei diesem umfangreicheren Service übernimmt der FID die Prüfung der rechtlichen Bedingungen, die Katalogisierung und die Digitalisierung der einzelnen Beiträge. Alle Zweitveröffentlichungen sind im IxTheo weltweit recherchierbar und frei zugänglich.</p>
	        <p>Der Service wird auf Basis des deutschen Urheberrechts für Wissenschaftler*innen im D-A-CH-Raum angeboten. 2023 konnten sich Forschende für eine neue Phase des Open Text Service anmelden.</p>

	        <h3>Nähere Informationen</h3>
            <h5><p><a href="https://ixtheo.de/docs/Zweitveroeffentlichung_Infoblatt.pdf">Ablauf des Zweitveröffentlichungsprozesses</a></p></h5>
			<h5><p><a href="https://ixtheo.de/docs/Zweitveroeffentlichung_FAQ.pdf">Häufig gestellte Fragen zum Open Text Service (FAQ)</a></p></h5>
		    <br>

            <h3><b>Ansprechpartner*innen</b></h3>
            <p>Dr. Janca Brenner <a href="mailto:janca.brenner@uni-tuebingen.de">Kontakt</a></p>
            <p>Dr. Corinna Ehlers <a href="mailto:corinna.ehlers@uni-tuebingen.de">Kontakt</a></p>
        </div>
    </div>
</div>