<div class="cw-row">
    <div class="cw-col-lg-8 cw-ml-lg-4">
        <div class="cw-text-block"><br>
            <h1 class="cw-h1">Self-Archiving / Republication</h1>
            <p>The FID Theologie supports authors who wish to make their already published theological research available in Open Access. Researchers from all fields of theology have various possibilities at their disposal to republish or self-archive their texts.</p>
			<br>

            <h3><b>IxTheo Self-Archiving Service (worldwide)</b></h3>
	        <p>Thanks to our Self-Archiving Service, researchers from all fields of theology can upload their own academic publications on the Index Theologicus (IxTheo) and make them available in Open Access.</p>
		    <p>Each self-archived publication is linked with the corresponding entry in IxTheo and is freely available to the worldwide academic community.</p>
	        <p>The Self-Archiving Service is free of charge. After you register, you can upload any of your own publications as a pdf file.</p>

            <h3>Advantages for Authors</h3>
            <ul>
                <li>Legal and non-commercial platform for self-archiving</li>
                <li>Your publications and full texts are easy to find on IxTheo</li>
                <li>Enhanced international visibility of your research</li>
                <li>Long-term archiving on the theological subject repository at the University Library of Tübingen</li>
                <li>Permanent link (DOI) which can be quoted in research and teaching</li>
                <li>Free and worldwide access to publications – also for people outside of universities or in contexts where current research literature is scarcely accessible</li>
            </ul>

            <h3>For more information</h3>
            <h5><p><a href="/Content/PublicationFAQ#content">Self-Archiving Service FAQ</a></p></h5>
			<br>

            <h3><b>IxTheo Open Text Service</b></h3>
            <p>With this extensive service, the FID Theologie assesses the legal situation and takes care of the cataloguing and the digitization of each publication. The publications are then freely accessible and searchable in IxTheo from across the world.</p>
	        <p>We offer this service to academics and researchers in Germany, Austria and Switzerland on the basis of German copyright law. Researchers could apply for a new phase of the Open Text Service in 2023.</p>

	        <h3>Nähere Informationen</h3>
            <h5><p><a href="https://ixtheo.de/docs/Zweitveroeffentlichung_Infoblatt.pdf">Self-Archiving Process</a></p></h5>
			<h5><p><a href="https://ixtheo.de/docs/Zweitveroeffentlichung_FAQ.pdf">Open Text Service FAQ</a></p></h5>
		    <br>

            <h3><b>Contact Persons</b></h3>
            <p>Dr. Janca Brenner <a href="mailto:janca.brenner@uni-tuebingen.de">Kontakt</a></p>
            <p>Dr. Corinna Ehlers <a href="mailto:corinna.ehlers@uni-tuebingen.de">Kontakt</a></p>
        </div>
    </div>
</div>