<div class="cw-row">
  <div class="cw-col-lg-12 cw-ml-lg-4">
    <div class="cw-text-block"><br>
      <h1 class="cw-h1">IxTheo Open Journals</h1>

      <h3>Open Access Journal Service</h3>

      <p>The FID Theologie offers editors the possibility of permanently hosting their academic theological journals or series in open access. Our service not only helps you to start a new open access journal, but can also assist you in transforming an already existing publication into an open access one.
	  <br>With the help of our publication management system  <a href="https://pkp.sfu.ca/ojs/"> Open Journal Systems (OJS)</a> you can manage every step of the editing process from the submission of articles to the publication of each journal issue.</p>
      <p>Working with “IxTheo Open Journals” gives you the following advantages:</p>
      <ul>
        <li>The FID Theologie / the Library of the University of Tübingen provides the OJS software free of charge, sets up the journal or series and offers training and ongoing support</li>
        <li>With OJS, all the editing steps from the submission of the articles to the peer review to the publication itself are managed and implemented with one system only</li>
        <li>The layout and design of an OJS-journal can be customized</li>
        <li>A persistent identifier (DOI), which guarantees that a publication can be found permanently across the whole world, is assigned to all articles</li>
        <li>All journal articles are catalogued and can be searched in IxTheo</li>
      </ul>
      <p>This offer is available to all editors of theological journals and series. <br> If you are interested, please contact Dr. Janca Brenner (<a href="mailto:janca.brenner@uni-tuebingen.de">contact</a>) or Dr. Corinna Ehlers (<a href="mailto:corinna.ehlers@uni-tuebingen.de">contact</a>).</p>

      <h3>Open Access Journals</h3>

      <!--<p>Sortierung nach Veröffentlichungsdatum | alphabetische Sortierung</p>-->

      <table class="ix-journals-table">
	      <tr>
          <td>
            <table border="1">
              <tr>
                <td class="img-td">
                  <img src="<?=$this->imageLink('journals/CdTh.jpg')?>" alt="<?=$this->translate('Logo of the journal Campus der Theologien');?>"/>
                </td>
                <td rowspan="2" class="text-td">
                  <h3>Campus der Theologien</h3>
                  <p>
                   Since the summer of 2024, the University of Tübingen has a “Campus der Theologien” (campus of theologies) which consists of the three theological institutions at the university: the Faculty of Protestant Theology (Evangelisch-Theologische Fakultät), the Faculty of Catholic Theology (Katholisch-Theologische Fakultät) and the Center for Islamic Theology (Zentrum für Islamische Theologie). This “campus of theologies”, which refers initially to the spatial proximity of the institutions, builds upon existing forms of cooperation and aims to intensify the academic cooperation between the participating institutions in research and teaching and to strengthen the ecumenical and inter-religious profile of the theologies in Tübingen. The academic journal “Campus der Theologien – Theologische Studien und Kritik” makes the theological fruits of the “campus of theologies” available to the public and strengthens the mutual dialog.
                  </p>
                  <p><a href="https://campus-der-theologien.de/ojs/index.php/cdt/" target="_blank">Link to the journal</a> | <a href="<?=$this->url('search-results')?>?lookfor=superior_ppn%3A1921973196&type=AllFields&sort=year+desc%2C+volume_sort+desc%2C+issue_sort+desc%2C+start_page+asc%2C+first_indexed+desc&botprotect=">All articles in IxTheo</a></p>
                </td>
              </tr>
              <tr>
                <td class="text-td">
                  <p>Publication: 2025-<br>ISSN: 3052-4989</br></p>
                </td>
              </tr>
            </table>
          </td>
        </tr>
		<tr>
          <td>
            <table border="1">
              <tr>
                <td rowspan="2" class="text-td">
                  <h3>Africa Theological Journal</h3>
                  <p>
                    Africa Theological Journal (ATJ) is a peer-reviewed international journal established in 1968 by the then Lutheran Theological College Makumira. The goal of ATJ is to promote theological research conducted by local and foreign scholars in the context of Africa.</br>
                    
                  </p>
                  <p><a href="https://atj.makumira.ac.tz/ojs/index.php/atj/index" target="_blank">Link zur Zeitschrift</a> | <a href="<?=$this->url('search-results')?>?lookfor=superior_ppn%3A1916428312&type=AllFields&botprotect=">All articles in IxTheo</a></p>
                </td>
                <td class="img-td">
                  <img src="<?=$this->imageLink('journals/ATJ.jpg')?>" alt="<?=$this->translate('Logo of Africa Theological Journal');?>"/>
                </td>
              </tr>
              <tr>
                <td class="text-td">
                  <p>Publication: 2024-<br>ISSN: 2961-6492</p>
                </td>
              </tr>
            </table>
          </td>
        </tr>
		<tr>
          <td>
            <table border="1">
              <tr>
                <td class="img-td">
                  <img src="<?=$this->imageLink('journals/BETH_Logo.jpg')?>" alt="<?=$this->translate('Logo of the journal BETH Bulletin');?>"/>
                </td>
                <td rowspan="2" class="text-td">
                  <h3>BETH Bulletin</h3>
                  <p>
                    The BETH Bulletin is published by Bibliothèques Européennes de Théologie (BETH). BETH is an ecumenical association of European national theological library organizations as well as single libraries. Its members together represent nearly 1.500 libraries, spreading from north to south, east to west, of Europe. BETH builds networks and establishes contacts, supports and promotes cooperation, stimulates library development, serves the interests of European theological libraries, and works for the preservation of the rich cultural patrimony found in the theological and ecclesiastical libraries of Europe.</br>
                  </p>
                  <p><a href="https://bethbulletin.eu/ojs/index.php/bethyb/index" target="_blank">Link to the journal</a> | <a href="<?=$this->url?>/Record/1861536410">This journal in IxTheo</a></p>
                </td>
              </tr>
              <tr>
                <td class="text-td">
                  <p>Publication: 2023-<br>ISSN: 2960-3463</br></p>
                </td>
              </tr>
            </table>
          </td>
        </tr>
		
		<tr>
          <td>
            <table border="1">
              <tr>
                <td rowspan="2" class="text-td">
                  <h3>Transformatio</h3>
                  <p>
                    <br>Transformation is the theme of the Bible and of liturgy. It is the core of the Christian message. As a fundamental characteristic of life and of culture, transformation is a key task of politics and societies.</br>
                    <br><b>transformatio;</b> observes the current spiritual search movements, the changes in religious practices, the evolution of Church life, the opportunities of interreligious contacts.</br>
                    <br><b>transformatio;</b> understands the Bible and liturgy as sources of meaning and as guides for new forms of religious life, peaceful cooperation and global development.</br>
                    <br><b>transformatio;</b> accompanies the current religious transformation processes with articles on theological fundamentals (peer reviewed) and with reports, essays, book reviews, sermons and inputs from practice.</br>
                  </p>
                  <p><a href="https://transformatio-journal.org/ojs/index.php/trans/index" target="_blank">Link to the journal</a> | <a href="<?=$this->url('search-results')?>?lookfor=superior_ppn%3A1805192892&type=AllFields&sort=year+desc%2C+volume_sort+desc%2C+issue_sort+desc%2C+start_page+asc%2C+first_indexed+desc&botprotect=">All articles in IxTheo</a></p>
                </td>
                <td class="img-td">
                  <img src="<?=$this->imageLink('journals/tranformatio.png')?>" alt="<?=$this->translate('Logo of the journal transformatio');?>"/>
                </td>
              </tr>
              <tr>
                <td class="text-td">
                  <p>Publication: 2022-<br>ISSN: 2813-4613</p>
                </td>
              </tr>
            </table>
          </td>
        </tr>
		
		<tr>
          <td>
            <table border="1">
              <tr>
                <td class="img-td">
                  <img src="<?=$this->imageLink('journals/aabner.png')?>" alt="<?=$this->translate('Logo of the journal Advances in Ancient Biblical and Near Eastern Research');?>"/>
                </td>
                <td rowspan="2" class="text-td">
                  <h3>Advances in Ancient Biblical and Near Eastern Research (AABNER)</h3>
                  <p>
                    The journal is the first open-access and forum-peer-reviewed journal that covers the entire field of biblical studies and cognate fields in its diversity, and it is committed to the principles of the EABS in terms of equal opportunity, non-discrimination, and academic rigor. The journal will encompass all fields touching on and relevant for the study of both the Hebrew Bible and the New Testament, early Jewish and Christian studies, from ancient times to reception in the present. This journal innovates the way humanities scholarship is published, by utilizing an open peer-review system  known as "forum review."
                  </p>
                  <p><a href="https://aabner.org/" target="_blank">Link to the journal</a> | <a href="<?=$this->url('search-results')?>?lookfor=superior_ppn%3A1758930020&type=AllFields&sort=year+desc%2C+volume_sort+desc%2C+issue_sort+desc%2C+start_page+asc%2C+first_indexed+desc&botprotect=">All articles in IxTheo</a></p>
                </td>
              </tr>
              <tr>
                <td class="text-td">
                  <p>Publication: 2021-<br>ISSN: 2748-6419</p>
                </td>
              </tr>
            </table>
          </td>
        </tr>
		
		  <tr>
		  <td>
            <table border="1">
              <tr>
                <td colspan="2" rowspan="2" class="text-td">
                  <h3 class="journals-title">Journal of European Baptist Studies</h3>
                  <p>
                    The Journal of European Baptist Studies (JEBS) was founded in 2000 by the International Baptist Theological Seminary (IBTS) in Prague, Czech Republic, to provide a means for promising new Baptist researchers to publish the results of their reflections on theology. The primary focus of the journal is on the implementation and application of research and reflection. Most of the contributions are from new or established researchers from within the European Baptist Federation region.
                  </p>
                  <p><a href="https://jebs.eu/" target="_blank">Link to the journal</a> | <a href="<?=$this->url('search-results')?>?lookfor=issn%3A1804-6444&type=AllFields&sort=year+desc%2C+volume_sort+desc%2C+issue_sort+desc%2C+start_page+asc%2C+first_indexed+desc&botprotect=">All articles in IxTheo</a></p>
                </td>
                <td class="img-td">
                <img src="<?=$this->imageLink('journals/ibtscentre.png')?>" alt="<?=$this->translate('Logo of the International Baptist Theological Seminary Centre which edits the Journal of European Baptist Studies');?>"/>
                </td>
              </tr>
              <tr>
                <td class="text-td">
                  <p>Publication: 2019-<br>ISSN: 1804-6444</p>
                </td>
              </tr>
            </table>
          </td>
        </tr>
		
        <tr>
          <td>
            <table border="1">
              <tr>
                <td class="img-td">
                  <img src="<?=$this->imageLink('journals/iapt.png')?>" alt="<?=$this->translate('Logo of the International Academy of Practical Theology. Conference Series');?>"/>
                </td>
                <td rowspan="2" class="text-td">
                  <h3>International Academy of Practical Theology. Conference Series (IAPT.CS)</h3>
                  <p>
                    The “International Academy of Practical Theology. Conference Series” (IAPT.CS) provides documentation of the bi-annual conferences of the Academy for scholars and interested readers around the world.
                  </p>
                  <p>
                    This way, the Conference Series shares the values and goals of the International Academy of Practical Theology to promote the study of and critical reflection on practical theological thought and action – bearing in mind the various historical and cultural contexts in which practical theology is done.
                  </p>
                  <p><a href="https://iapt-cs.org/" target="_blank">Link to the journal</a> | <a href="<?=$this->url('search-results')?>?lookfor=issn%3A2628-0000&type=AllFields&sort=year+desc%2C+volume_sort+desc%2C+issue_sort+desc%2C+start_page+asc%2C+first_indexed+desc&botprotect=">The journal in IxTheo</a></p>
                </td>
              </tr>
              <tr>
                <td class="text-td">
                  <p>Publication: 2019-<br>ISSN: 2628-0000</p>
                </td>
              </tr>
            </table>
          </td>
        </tr>
		
         <tr>
          <td>
            <table border="1">
              <tr>
                <td colspan="2" rowspan="2" class="text-td">
                  <h3>Journal of Ethics in Antiquity and Christianity (JEAC)</h3>
                  <p>
                    The Open Access Journal „Journal for Ethics in Antiquity and Christianity (JEAC)“ establishes a dialogue between exegetical, Jewish, patristic, philosophical and systematic theological approaches to current ethical issues. In so doing, it seeks to introduce the ethical dimensions of ancient texts to the contemporary ethical discourse.
                  </p>
                  <p><a href="https://jeac.de/" target="_blank">Link to the journal</a> | <a href="<?=$this->url('search-results')?>?lookfor=issn%3A2627-6062&type=AllFields&sort=year+desc%2C+volume_sort+desc%2C+issue_sort+desc%2C+start_page+asc%2C+first_indexed+desc&botprotect=">All articles in IxTheo</a></p>
                </td>
                <td class="img-td">
                  <img src="<?=$this->imageLink('journals/jeac.png')?>" alt="<?=$this->translate('Logo of the Journal of Ethics in Antiquity and Christianity');?>"/>
                </td>
              </tr>
              <tr>
                <td class="text-td">
                  <p>Publication: 2019-<br>ISSN: 2627-6062</p>
                </td>
              </tr>
            </table>
          </td>
        </tr> 
		
        <tr>
          <td>
            <table border="1">
              <tr>
                <td class="img-td">
                  <img src="<?=$this->imageLink('journals/akademie.png')?>" alt="<?=$this->translate('Logo of the Academy of the Diocese of Rottenburg-Stuttgart which edits the journal Im Dialog');?>"/>
                </td>
                <td rowspan="2" class="text-td">
                  <h3>Im Dialog. Beiträge aus der Akademie der Diözese Rottenburg-Stuttgart</h3>
                  <p>The journal “Im Dialog” gathers contributions from discussions and projects of the Academy of the Diocese of Rottenburg-Stuttgart. The Academy understands itself as a forum for dialog on the issues of our time. It brings people together for discussion - across professional, national, ethnic, ideological, cultural, denominational and religious boundaries, from academia and society, politics and practice, within the horizon of Christian orientations. It addresses topics with lasting relevance, including those that go against the mainstream.
                  </p>
                  <p><a href="https://imdialog.akademie-rs.de/" target="_blank">Link to the journal</a> | <a href="<?=$this->url('search-results')?>?lookfor=issn%3A2698-5446&type=AllFields&sort=year+desc%2C+volume_sort+desc%2C+issue_sort+desc%2C+start_page+asc%2C+first_indexed+desc&botprotect=">All articles in IxTheo</a></p>
                </td>
              </tr>
              <tr>
                <td class="text-td">
                  <p>Publication: 2019-<br>ISSN: 2698-5446</p>
                </td>
              </tr>
            </table>
          </td>
        </tr>
		
        <tr>
          <td>
            <table border="1">
              <tr>
                <td colspan="2" rowspan="2" class="text-td">
                  <h3>Vulgata in Dialogue. A biblical online review</h3>
                  <p>
                    Vulgata in Dialogue was founded in 2016. Its articles focus on Biblical exegesis, theological, linguistic, historical and interdisciplinary topics related to the domain of the Biblia Sacra Vulgata.
                  </p>
                  <p><a href="https://vulgata-dialog.ch/" target="_blank">Link to the journal</a> | <a href="<?=$this->url('search-results')?>?lookfor=issn%3A2504-5156&type=AllFields&sort=year+desc%2C+volume_sort+desc%2C+issue_sort+desc%2C+start_page+asc%2C+first_indexed+desc&botprotect=">All articles in IxTheo</a></p>
                </td>
                <td class="img-td">
                  <img src="<?=$this->imageLink('journals/vulgata.png')?>" alt="<?=$this->translate('Logo of the journal Vulgata in Dialogue');?>"/>
                </td>
              </tr>
              <tr>
                <td class="text-td">
                  <p>Publication: 2017-<br>ISSN: 2504-5156</p>
                </td>
              </tr>
            </table>
          </td>
        </tr>
		
        <tr>
          <td>
            <table border="1">
              <tr>
                <td class="img-td">
                  <img src="<?=$this->imageLink('journals/zfbeg.png')?>" alt="<?=$this->translate('Logo of the Zeitschrift für christlich-jüdische Begegnung im Kontext (Journal for Jewish-Christian dialogue in context)');?>"/>
                </td>
                <td rowspan="2" class="text-td">
                  <h3>Zeitschrift für christlich-jüdische Begegnung im Kontext</h3>
                  <p>
                   In times of urgent dialogue between different religions and worldviews, the concern for Christian-Jewish encounter continues to be of particular importance. The renewed Zeitschrift für christlich-jüdische Begegnung im Kontext (ZfBeg) is the successor journal of the traditional Freiburger Rundbrief and is published by the association Freiburger Rundbrief - Arbeitskreis für christlich-jüdische Begegnung e.V.. The chairmen are Prof. Dr. Reinhold Boschki, Tübingen and Prof. Dr. Wilhelm Schwendemann, Freiburg im Breisgau.
				   As an overriding objective, the Journal for Christian-Jewish Encounter in Context aims to promote the relationship and understanding between Christians and Jews, to counter anti-Semitism and racism at all levels, to keep the memory of the Holocaust alive, to deepen the friendship between Christians and Jews, to promote human rights and to open the dialogue to other religions and groups, especially with Muslims. In doing so, it wants to have an impact on churches, theology, religious communities and the social public, especially in the field of education.
				   The ZfBeg is currently published twice a year. It is made available in open access with a moving wall of one year.
                  </p>
                  <p><a href="https://zfbeg.org/ojs/index.php/cjbk" target="_blank">Link to the journal</a> | <a href="<?=$this->url('search-results')?>lookfor=superior_ppn%3A1698812183&type=AllFields&sort=year+desc%2C+volume_sort+desc%2C+issue_sort+desc%2C+start_page+asc%2C+first_indexed+desc&botprotect=">All articles in IxTheo</a></p>
                </td>
              </tr>
              <tr>
                <td class="text-td">
                  <p>Publication: 2017-<br>ISSN: 2513-1389 | <br>E-ISSN: 2751-2959</br><br>(with embargo)</br></p>
                </td>
              </tr>
            </table>
          </td>
        </tr>
		
        <tr>
          <td>
            <table border="1">
              <tr>
                <td rowspan="2" class="text-td">
                  <h3>Ethik und Gesellschaft (EuG)</h3>
                  <p>
                    Ethik und Gesellschaft publishes articles twice a year on topics in theological social ethics. The articles appear in thematical issues and handle the topic of the issue from varied perspectives, which contributes to a comprehensive and interdisciplinary engagement with the topic.
                  </p>
                  <p><a href="https://ethik-und-gesellschaft.de" target="_blank">Link to the journal</a> | <a href="<?=$this->url('search-results')?>?lookfor=issn%3A2365-6565&type=AllFields&sort=year+desc%2C+volume_sort+desc%2C+issue_sort+desc%2C+start_page+asc%2C+first_indexed+desc&botprotect=">All articles in IxTheo</a></p>
                </td>
                <td class="img-td">
                  <img src="<?=$this->imageLink('journals/eug.png')?>" alt="<?=$this->translate('Logo of the journal Ethik und Gesellschaft (Ethics and Society)');?>"/>
                </td>
              </tr>
              <tr>
                <td class="text-td">
                  <p>Publication: 2007-<br>ISSN: 2628-0000</p>
                </td>
              </tr>
            </table>
          </td>
        </tr>
		
	      <tr>
          <td>
            <table border="1">
              <tr>
                <td class="img-td">
                  <img src="<?=$this->imageLink('journals/theo_geschichte.jpg')?>" alt="<?=$this->translate('Logo of the journal theologie.geschichte');?>"/>
                </td>
                <td rowspan="2" class="text-td">
                  <h3>theologie.geschichte</h3>
                  <p>
                   The multilingual peer-reviewed open access journal theologie.geschichte is a discussion platform for researchers of various disciplines and nationalities who conduct research with the aim of coming to terms with the past. Whenever people confront the burdens of the past, this can shed a critical light on current issues and help shape the future.</p>
                  <p><a href="https://theologie-geschichte.de/ojs2/index.php/tg/index" target="_blank">Link to the journal</a> | <a href="<?=$this->url('search-results')?>?lookfor=superior_ppn%534678750&type=AllFields&sort=year+desc%2C+volume_sort+desc%2C+issue_sort+desc%2C+start_page+asc%2C+first_indexed+desc&botprotect=">All articles in IxTheo</a></p>
                </td>
              </tr>
              <tr>
                <td class="text-td">
                  <p>Publication: 2006-<br>ISSN: 1862-1678</p>
                </td>
              </tr>
            </table>
          </td>
        </tr>	
		
            </table>
          </td>
        </tr>
      </table>
    </div>
  </div>
</div>
