<!--
    Original privacy statement, see: https://uni-tuebingen.de/meta/datenschutzerklaerung
    All changes to the original should be marked as class="changed"!!!
    Uncomment the following block to highlight changed sections for debugging purposes:
-->
<!--
<style type="text/css">
    .changed {
        color: blue !important;
    }
</style>
-->

<div id="tf-imprint">
    <h1 class="changed">Privacy policy of the FID Websites of the University Library of Tübingen</h1>
    <p class="changed">Dear users of the FID websites,</p>
    <p class="changed">We very much appreciate your interest in the Specialized Information Services (“Fachinformationsdienst” or FID) in theology, religious studies and criminology.</p>
    <p>Through this declaration on our privacy policy, we would like to inform you regarding the processing of your personal data (hereinafter “data”) which results from your visit or your use of functions on our FID websites.</p>
    <p>We ask you to read this privacy policy carefully before you continue your visit or use some of the functions offered on our FID websites.</p>
    <p>By visiting one of the FID websites, you consent to the processing and use of your data as described below.</p>
    <p>This privacy policy is only applicable for the FID websites, not for the websites of third parties.</p>

    <h2>Data Protection and Data Security</h2>
    <p>The protection of your privacy is very important to us. The University Library of Tübingen takes many technical and organizational measures for the protection of your data in order to prevent any unauthorized access, copying, manipulation, loss and unauthorized deletion of your data.</p>
    <p>We update our protection measures regularly, following legal requirements, “best practice” approaches as well as new technical developments.</p>
    <p>In the following, we inform you about which data the University Library of Tübingen gathers, processes and uses when you visit one of our websites or use one of the functions offered on our websites; we also inform you about how we gather and process this data, and about the goals of our data collection.</p>

    <h2>Person responsible for this privacy policy and this website</h2>
    <div class="changed">
        <p><b>Universitätsbibliothek Tübingen</b></p>
        <p>
            Regine Tobias<br/>
            Wilhelmstr. 32<br/>
            72074 Tübingen<br/>
            E-Mail: <a href="mailto:direktion@ub.uni-tuebingen.de">direktion@ub.uni-tuebingen.de</a><br/>
            Telephone number: +49 7071 29-77854
        </p>
    </div>

    <h2>Contact person for data protection</h2>
        <b>Data Protection Officer</b><br/>
        Geschwister-Scholl-Platz<br/>
        72074 Tübingen<br/>
        E-Mail: <a href="mailto:datenschutz@uni-tuebingen.de">datenschutz@uni-tuebingen.de</a><br/>
        Telephone number: +49 70 71 29-0<br/>
        <a target="_blank" href="//uni-tuebingen.de/einrichtungen/personalvertretungen-beratung-beauftragte/datenschutzbeauftragter/">Website of the Data Protection Officer</a>
    </p>

    <h2>Scope of the data collection, processing and use</h2>
    <p>Our goal is to limit the amount of personal data we collect, process and use during your visits to our websites to the minimum necessary for their operation.</p>
    <p>We do not knowingly collect personal data from minors (i.e. people under 18 years of age). If we discover that we have received personal data from minors, we delete it immediately unless it is part of an ongoing process. We recommend that parents and guardians monitor the Internet activities of minors under their care.</p>

    <h2>Personal Data</h2>
    <p>Personal data is any information that can be used to identify a natural person in accordance with Art. 4 of the General Data Protection Regulation (GDPR). It includes the first name, family name, address, e-mail address, telephone number, mobile phone number and also the IP-address.</p>

    <h2>Purpose of Data Collection</h2>
    <p>We do not collect, process or use the data which you voluntarily provide us for any purpose other than the purposes for which you provided it, which are the following:</p>

    <!-- all chapters in this element are completely new and do not exist in the original privacy statement -->
    <!-- (e.g. VuFind/TueFind-specific features) -->
    <div class="changed">
        <h2>Identification Data</h2>
        <p>In order to use special personal functions in IxTheo/RelBib/KrimDok, you must have a user account. These special functions include e.g. managing favorites, setting up alerts (notifications of new publications in the database), saving searches and book orders. By creating an account, you consent to the gathering and processing of the information you provide.</p>
        <table class="table">
            <tr><th>Field name</th><th>Mandatory field?</th><th>Purpose</th></tr>
            <tr><td>E-Mail-Address</td><td>yes</td><td>Authentication,<br/>Alerts/Notifications,<br/>Exporting Search Queries,<br/>Communication for Book Orders,<br/>Book Exchange</td></tr>
            <tr><td>Username</td><td>yes</td><td>Authentication</td></tr>
            <tr><td>Password</td><td>yes</td><td>Authentication</td></tr>
            <tr><td>Title</td><td>no</td><td>Communication</td></tr>
            <tr><td>First/Last Name</td><td>no</td><td>Communication</td></tr>
            <tr><td>Institution, Country</td><td>no</td><td>Licensing Information, Delivery Capacities</td></tr>
            <tr><td>Language</td><td>no</td><td>User Comfort, Communication</td></tr>
        </table>

        <h2>Online Contact Forms, Feedback Forms, Suggestions for Book Purchases, PDA</h2>
        <p>For new works in the database which cannot be borrowed from a library yet in Germany, it is possible to have the FID order and deliver that work. We use personal data to organize the purchase and delivery as well as to clear up any further questions (see above).</p>
        <p>If you provide us your data when contacting us with a query, a reply (or feedback), a notification or a suggestion for a purchase, we will process and use this data exclusively to fulfill your request or answer your question.</p>

        <h2>Favorites</h2>
        <p>You can save favorites on our FID websites. These are bibliographic entries in the database which you can easily find through a selection in your account. For this purpose, bibliographic entries you select are saved in your account.</p>

        <h2>Saved Searches</h2>
        <p>You can also save searches. You can use this feature to check if there are new publications or new information on a given topic. The search parameters are saved in your account. Searches which are not permanently saved remain up to 30 days in your account history. For unregistered users, the search is saved as a part of the browser session (see the “Cookies” section).</p>

        <h2>Alerts</h2>
        <p>You can receive alerts on journals, publication series or RSS feeds. Through our alerting function, you get a notification every time there is a new article in a journal or an RSS feed you monitor. The journals, series and RSS feeds you select are stored in your account.</p>

        <h2>Rights to your Author ID</h2>
        <p>You can request the rights to your author ID. The information on your request (including time stamp and processing state) are stored in the database.</p>

        <h2>Self-Archiving Service</h2>
        <p>You can self-archive your own publications. The information stored on your publications includes information on the confirmation of your current declaration of consent, the IDs of the self-archived document as well as a time stamp.</p>
    </div>

    <h2>Improvement of our Websites</h2>
    <p class="changed">In order to improve the contents, presentation, functions and user-friendliness of the FID websites, we collect, process and use the following data:</p>
    <ul>
        <li>IP-Address of the computer which called up the website</li>
        <li>Date and time of the call</li>
        <li>URL-path of the website/file called up and access method requested</li>
        <li>Access status of the webserver (e.g. file transferred, file not found)</li>
        <li>Amount of data transferred</li>
        <li>Information on the software used to access the website (usually the browser type and version, and the operating system of the computer making the call)</li>
        <li>URL from which the website/file was called up</li>
    </ul>
    <p>The University Library of Tübingen uses the access protocol data to identify and track unallowed access attempts and calls to the website. The server log files are stored for a duration of 3 months and then deleted. The access protocol data is stored and then analyzed anonymously to optimize our websites. The data no longer allows for the identification of persons.</p>
    <p>We collect, process and use this data exclusively for the statistical and non-commercial purposes described above in an anonymous or pseudonymous form which prevents the identification of any person.</p>

    <h2>Use of the Matomo Web Analysis Service</h2>
    <p>We use Matomo (Piwik), an open source software, for our statistical analysis of the user access to our websites. Matomo allows us to conduct an anonymous analysis of your use of our websites. Cookies are used only for the option to opt out of this analysis (see below). Matomo is configured in such a way that no tracking cookies are created. The identification of a given user is not possible because your IP-address gets anonymized immediately after the processing but before the saving.</p>
    <p>You can object to the processing and saving of your data through Matomo at any time (Link: <a href="https://vitruv.uni-tuebingen.de/piwik/index.php?module=CoreAdminHome&action=optOut&language=de&backgroundColor=&fontColor=&fontSize=&fontFamily=">https://vitruv.uni-tuebingen.de/piwik/index.php?module=CoreAdminHome&action=optOut&language=de&backgroundColor=&fontColor=&fontSize=&fontFamily=</a>). In such case, a permanent “opt-out” cookie gets stored in your browser which prevents Matomo from collecting and processing your data. If you delete this cookie (whether intentionally or not), your objection to the analysis of your data gets lifted, but it can be renewed by using the link above again.</p>
    <p>Another way to prevent Matomo from collecting your data is to use the “Do not track” option which is provided by most modern browsers as a way of telling websites not to monitor your user activities. Matomo does not track your data when this option is selected.</p>

    <h2>Cookies</h2>
    <p>The FID websites of the University Library of Tübingen use so-called cookies. Cookies cause no damage on your computer and don’t contain any virus. Cookies are used to make our websites more user-friendly, effective and secure. Cookies are small text files which are stored on your computer by your browser.</p>
    <p>We use the following cookies:</p>
    <ul class="changed">
        <li>
            User interface cookies (which remain up to 30 days after the browser is closed)
            <ul>
                <li>Language parameters</li>
                <li>Design parameters (if applicable)</li>
                <li>Session-ID of the user logged in</li>
            </ul>
        </li>
    </ul>
    <p>You can configure your browser to notify you when cookies are created and require your approval on a case-by-case basis. You can also prohibit the creation of cookies in certain cases altogether or activate the automatic deletion of your cookies when you close it. If you deactivate cookies on your browser, it may affect the functionality of our websites.</p>
    <p>Cookies help us to:
        <ul>
            <li>identify how often certain areas of our websites are accessed</li>
            <li>discern the preferences of our users, so that we can optimize our websites accordingly</li>
            <li>make navigation on our websites easier and more user-friendly</li>
            <li>hold information over a certain period of time and identify the computer used when you return to one of our websites. This allows us to recover your user settings, so that you don’t have to enter them again (e.g. language used, log-in information).</li>
        </ul>
    </p>

    <h2>Links to Other Websites</h2>
    <p>Our websites provide links to external websites. We have no control over these external websites, which means that we do not accept any responsibility or liability for the admissibility, accuracy, representation and completeness of the contents published or shown on these websites.</p>
    <p>We inform you hereby, that the website operators of external websites may record your IP-address when you access their website.</p>
    <p>When you leave our websites, we recommend that you examine the privacy policy of the external website operators before you access their website or use the functions they provide.</p>

    <h2>Transmission of Your Data</h2>
    <p>We do not transfer the data we collect, process and use to a third party or to our business partners without your explicit consent unless:
        <ul>
            <li>it is necessary to fulfill our contractual obligations.</li>
            <li>it is necessary to enforce our claims.</li>
            <li>it is legitimized through a legal permission, or we are legally obligated to pass on the data.</li>
            <li>for the purposes of a criminal prosecution, for danger prevention or to protect our websites.</li>
            <li>for the enforcement of the rights of third parties or to fulfill statutory disclosure requirements or a court order to provide information.</li>
        </ul>
    </p>

    <h2>Information Rights</h2>
    <p>In accordance with Art. 15 of the GDPR, visitors to our website may request information about the processing of their personal data at the University Library of Tübingen at any time and free of charge. The scope of the information is specified in Art. 15 of the GDPR.</p>
    <p>Please send your demand for information to this e-mail address (<a href="mailto:datenschutz@uni-tuebingen.de">datenschutz@uni-tuebingen.de</a>) or per mail to the following address: Universität Tübingen, Datenschutzbeauftragter, Geschwister-Scholl-Platz, 72074 Tübingen, Germany.</p>

    <h2>Right to Correction of Your Data</h2>
    <p>In accordance with Art. 16 of the GDPR, you have the right to request the correction or completion of any incorrect or incomplete data concerning you. We will review such requests and take the appropriate action when justified.</p>

    <h2>Right to Deletion and Blocking of Your Data</h2>
    <p>In accordance with Art. 17 of the GDPR, you have the right to have your data deleted.<br/>
       The personal data which we keep is deleted or destroyed in compliance with data protection law in one of the following cases:
        <ul>
            <li>The legal data retention period is expired.</li>
            <li>The data collection or processing is or was illegal.</li>
            <li>The data is no longer necessary for the purposes for which it was collected.</li>
            <li>If you withdraw your consent to processing and use.</li>
            <li>If you object, in accordance with Art. 21 of the GDPR, to the processing of your data, and there are no overriding legitimate grounds for the processing.</li>
        </ul>
    </p>
    <p>We inform you that a complete deletion takes place only after the expiry of the corresponding deadlines specified by tax regulations and commercial laws. Your data remains blocked and does not get processed by us until these deadlines have expired and the data is finally deleted.</p>
    <p class="changed">
        You can delete your account yourself under &quot;Default settings&quot;-&gt;&quot;Delete Account&quot;.<br/>
        This causes all the data which was listed under “Personal Data” to be deleted.
    </p>

    <h2>Right to Limit Data Processing</h2>
    <p>In accordance with Art. 18 of the GDPR, you have the right to request that we restrict the processing of your data to the extent and in the cases specified in Art. 18 of the GDPR. We will review such requests and take the appropriate action when justified.</p>

    <h2>Right to Data Portability</h2>
    <p>In accordance with Art. 20 of the GDPR, you have the right to receive the data that we have processed about you in a structured, commonly used and machine-readable format. Upon your request, we will transmit your data to the specific entities you name, provided that we are technically capable and permitted by data protection law to do so.</p>

    <h2>Right of Cancellation and of Objection</h2>
    <p>In accordance with Art. 21 of the GDPR, you have the right to withdraw your consent to the collection, processing, and use of your data at any time, free of charge, and without giving reasons. You also have the right to object to the processing of your data. Please send your cancellation or objection per e-mail to (<a href="mailto:datenschutz@uni-tuebingen.de">datenschutz@uni-tuebingen.de</a>) or per mail to the following address:  Universität Tübingen, Datenschutzbeauftragter, Geschwister-Scholl-Platz, 72074 Tübingen, Germany.</p>

    <h2>Right to File a Complaint to a Regulatory Authority</h2>
    <p>In accordance with Art. 14 in conjunction with Art. 77 of the GDPR, you have the right to file a complaint with a data protection supervisory authority if you believe that your data is being processed in violation of the GDPR. The responsible supervisory authority is the Ministry of Science, Research and the Arts of Baden-Württemberg.</p>

    <h2>Right to an Effective Judicial Remedy Against Responsible Persons</h2>
    <p>In accordance with Art. 79 of the GDPR, you have the right to an effective judicial remedy if you believe that your aforementioned rights have been violated as a result of the processing of your data by us or by a processor commissioned by us that does not comply with the GDPR’s requirements.</p>

    <h2>Liability and Right to Claim Damages</h2>
    <p>In accordance with Art. 82 of the GDPR, you may file a claim against us or the processors we have commissioned if you have suffered material or non-material damage as a result of a GDPR breach.</p>

    <h2>Changes to our Privacy Policy</h2>
    <p>We will update this privacy policy as needed to comply with new legal requirements or significant changes to the scope of our website's functionality. Therefore, we recommend reading our privacy policy periodically.</p>

    <!-- basierend auf Original-Datenschutzerklärung mit letzter Änderung 16.03.2021 -->
    <p>Last modification: 19.02.2024</p>
</div>
