<div class="cw-row">
    <div class="cw-col-lg-12 cw-ml-lg-4">
        <div class="cw-text-block"><br>
            <h1 class="cw-h1">Verlage</h1>

            <p>IxTheo kooperiert mit zahlreichen Verlagen. Von Seiten der Verlage werden bibliographische Daten oder durchsuchbare Volltexte bereitgestellt. Weiterhin bestehen Kooperationen im Blick auf verschiedene Digitalisierungsprojekte.</p>
            <p>Aktuell arbeitet IxTheo mit folgenden Verlagen zusammen:</p>
            <ul>
                <li>Aschendorff</li>
                <li>Brill</li>
                <li>De Gruyter</li>
                <li>Duncker & Humblot</li>
                <li>Echter</li>
                <li>Evangelische Verlagsanstalt</li>
                <li>Harrassowitz</li>
                <li>Herder</li>
                <li>Kohlhammer</li>
                <li>Mohr Siebeck</li>
                <li>Patmos</li>
                <li>Pustet</li>
                <li>Taylor & Francis</li>
                <li>Vandenhoeck & Ruprecht</li>
            </ul>
            <p>IxTheo ist offen für Kooperationen und Partnerschaften mit weiteren Verlagen. Wenn Sie Interesse an einer Zusammenarbeit haben, wenden Sie sich gerne an <a href="mailto:ixtheo@ub.uni-tuebingen.de">ixtheo@ub.uni-tuebingen.de</a>.</p>
        </div>
    </div>
</div>