<div class="cw-row">
    <div class="cw-col-lg-12 cw-ml-lg-4">
        <div class="cw-text-block"><br>
            <h1 class="cw-h1">Publishers</h1>

            <p>IxTheo cooperates with several publishing houses. Publishing houses provide bibliographic data or searchable full texts for the IxTheo catalog. There are also cooperation agreements for various digitization projects.</p>
            <p>IxTheo currently cooperates with the following publishing houses:</p>
            <ul>
                <li>Aschendorff</li>
                <li>Brill</li>
                <li>De Gruyter</li>
                <li>Duncker & Humblot</li>
                <li>Echter</li>
                <li>Evangelische Verlagsanstalt</li>
                <li>Harrassowitz</li>
                <li>Herder</li>
                <li>Kohlhammer</li>
                <li>Mohr Siebeck</li>
                <li>Patmos</li>
                <li>Pustet</li>
                <li>Taylor & Francis</li>
                <li>Vandenhoeck & Ruprecht</li>
            </ul>
            <p>IxTheo is always interested in new cooperations and partnerships with other publishing houses. If you are interested in working with us, please contact us at: <a href="mailto:ixtheo@ub.uni-tuebingen.de">ixtheo@ub.uni-tuebingen.de</a>.</p>
        </div>
    </div>
</div>
