<div class="cw-row">
    <div class="cw-col-lg-12 cw-ml-lg-4">
        <div class="cw-text-block"><br>
            <h1 class="cw-h1">Historische Drucke</h1>

            <p>Neben aktueller Literatur werden im Index Theologicus (IxTheo) auch Drucke des 16., 17. und 18. Jahrhunderts nachgewiesen. Damit ermöglicht der IxTheo gezielte Recherchen zu theologischen Publikationen der Frühen Neuzeit. Deren Einbeziehung in thematische Suchen ist ebenso möglich wie eine gemeinsame Recherche nach Originaldrucken, Textausgaben und Sekundärliteratur.</p>
            <p>In der Förderphase 2021-2023 wurde der Nachweis Historischer Drucke im IxTheo um zwei wichtige Komponenten erweitert:</p>

            <h3 style="font-weight: bold;">Kooperation mit Spezialbibliotheken</h3>

            <p>In Kooperation mit einer Reihe renommierter Spezialbibliotheken werden die dort vorhandenen theologisch und kirchenhistorisch relevanten Druckschriften auch im IxTheo nachgewiesen. Dadurch sind umfassende, teils einzigartige Bestände frühneuzeitlicher Drucke direkt über den IxTheo recherchierbar.</p>
            <p>Folgende Institutionen nehmen an der Kooperation teil:</p>
            <ul>
              <li><a target="_blank" href="https://www.uni-erfurt.de/forschungsbibliothek-gotha/forschung/studienstaette-protestantismus/studienstaette-protestantismus">Forschungsbibliothek Gotha (Forschungs- und Studienstätte für die Kulturgeschichte des Protestantismus in der Frühen Neuzeit)</a></li>
              <li><a target="_blank" href="https://www.jalb.de/">Johannes a Lasco Bibliothek, Emden</a></li>
              <li><a target="_blank" href="https://www.francke-halle.de/de/">Franckesche Stiftungen zu Halle, Studienzentrum August Hermann Francke, Halle</a></li>
              <li><a target="_blank" href="https://www.rfb-wittenberg.de/">Reformationsgeschichtliche Forschungsbibliothek Wittenberg</a></li>
            </ul>

            <h3 style="font-weight: bold;">Nachweis Historischer Drucke aus <a target="_blank" href="https://www.bsb-muenchen.de/sammlungen/historische-drucke/recherche/vd-16/">VD16</a>, <a target="_blank" href="http://www.vd17.de/">VD17</a> und <a target="_blank" href="file:///mnt/ZE020110/FID-Projekte/IxTheo%20Design/Texte/vd18.de">VD18</a></h3>

            <p>Die umfassenden Bibliographien zur Druckproduktion des deutschen Sprachraums im 16., 17. und 18. Jahrhundert (VD16, VD17, VD18) enthalten eine Vielzahl theologisch relevanter Druckschriften. Diese werden sukzessive auch im IxTheo nachgewiesen.</p>
            <ul>
              <li>Publikationen zu Theologie und Kirchengeschichte der Frühen Neuzeit im deutschen Sprachraum sind damit umfassend im IxTheo recherchierbar</li>
              <li>bibliographisch exakter Nachweis</li>
              <li>Verlinkung auf Kataloge der besitzenden Bibliotheken via VD16, VD17, VD18</li>
              <li>vielfach sind Digitalisate verfügbar</li>
            </ul>
      </div>
    </div>
</div>