<div class="container cw-py-5">
  <div class="cw-row">
    <div class="cw-col-lg-8">
      <div class="cw-text-block">
        <h1 class="cw-h1">Unterseite Publikationsmeldungen</h1>

        <p>Mit dieser Funktion können Sie uns auf wissenschaftliche theologische und religionswissenschaftliche Publikationen hinweisen, die noch nicht im Index Theologicus (IxTheo) verzeichnet sind.</p>
        <p>Loggen Sie sich dazu in Ihr IxTheo-Konto ein. Falls Sie noch kein IxTheo-Konto haben, können Sie sich in wenigen Schritten kostenlos registrieren: <a href="https://ixtheo.de/Content/IxtheoAccount?lng=de#content">IxTheo-Konto</a></p>
        <p>Wählen Sie nun in Ihrem IxTheo-Konto rechts an der Seite die Option „Noch nicht verzeichnete Publikation melden“. </p>
        
        <p>&nbsp;</p>
        <p><img class="img-responsive" style="width: 40%;" src="<?=$this->imageLink('content_img/pub1_de.png')?>" alt="Screenshot der Sidebar mit der Funktion „Nicht verzeichnete Funktion melden“"></p>
        <p>&nbsp;</p>    
        
        <p>Wählen Sie den Publikationstyp aus, den Sie melden möchten:</p>
        
        <p>&nbsp;</p>
        <p><img class="img-responsive" style="width: 60%;" src="<?=$this->imageLink('content_img/pub2_de.png')?>" alt="Screenshot von Links zu den Formularen für vier Publikationstypen: Aufsatz in einer Zeitschrift oder in einem Sammelband, Rezension, Lexikonartikel, Monographie oder herausgegebenes Werk"></p>
        <p>&nbsp;</p>
        
        <p>Es erscheint ein Formular, in das Sie die bibliographischen Daten eintragen können.</p>

        <p>&nbsp;</p>
        <p><img class="img-responsive" src="<?=$this->imageLink('content_img/pub3_de.png')?>" alt="Screenshot des Formulars zur Meldung eines Aufsatzes, mit Feldern für verschiedene bibliographische Angaben (Verfasser*in, Titel u.a.)"></p>
        <p>&nbsp;</p>

        <p>Besonderheiten und Unklarheiten jeglicher Art können Sie im Kommentarfeld vermerken.</p>
        <p>Nach der erfolgreichen Übermittlung des Formulars wird der gemeldete Titel geprüft und in IxTheo aufgenommen. Sie können den neuen Eintrag nach wenigen Tagen in IxTheo finden. Ab diesem Zeitpunkt können Sie bei eigenen Titeln außerdem unseren Self-Archiving Service nutzen und ein Digitalisat Ihrer Publikation als PDF-Datei hochladen.</p>

        <p>Falls sich im Zuge der Bearbeitung Fragen ergeben sollten, kommen wir auf Sie zu.</p>

        <p>Wenn Sie eine Publikation melden möchten, die zu keinem der vier aufgelisteten Typen gehört, wenden Sie sich bitte per E-Mail an uns: <a href="mailto:ixtheo-self-archiving@ub.uni-tuebingen.de">ixtheo-self-archiving@ub.uni-tuebingen.de</a></p>

      </div>
    </div>
  </div>
</div>
