<div class="container cw-py-5">
  <div class="cw-row">
    <div class="cw-col-lg-8">
      <div class="cw-text-block">
        <h1 class="cw-h1">Unterseite Reporting unlisted publications</h1>

        
        <p>This function allows you to report academic publications in theology and religious studies which are not yet listed in the Index Theologicus (IxTheo).</p>
        <p>First log into your IxTheo account. If you don’t have an IxTheo account yet, you can register for free in just a few steps: <a href="https://ixtheo.de/Content/IxtheoAccount?lng=en#content">IxTheo-Konto</a></p>
        <p>In your IxTheo account, select the option “Report unlisted publication” in the right-hand sidebar.</p>
        
        <p>&nbsp;</p>
        <p><img class="img-responsive" src="<?=$this->imageLink('content_img/pub1_en.png')?>" alt="Screenshot of the sidebar with the button “Report unlisted publication”"></p>
        <p>&nbsp;</p>    
        
        <p>Select the type of publication you would like to report:</p>
        
        <p>&nbsp;</p>
        <p><img class="img-responsive" src="<?=$this->imageLink('content_img/pub2_en.png')?>" alt="Screenshot of a list with links leading to forms for reporting four types of publications:  Article in a journal or in a collection of essays, Review, Article in a lexicon, Monograph or essay collection"></p>
        <p>&nbsp;</p>
        
        <p>A form then appears in which you can enter the bibliographic information.</p>

        <p>&nbsp;</p>
        <p><img class="img-responsive" src="<?=$this->imageLink('content_img/pub3_en.png')?>" alt="Screenshot of the form for reporting an article, containing fields for bibliographic details (author, title, etc.)"></p>
        <p>&nbsp;</p>

        <p>You can specify special features of the publication and uncertainties of any type in the field “Additional information”.</p>
        <p>Once you’ve sent us this form, we review the information and add it to IxTheo. You will find the new entry in IxTheo within a few days. Afterwards, if it is your own publication, you can also use our self-archiving service and upload it as a PDF-file.</p>

        <p>If we have any questions regarding the submitted information, we will let you know.</p>

        <p>If you would like to report a publication which doesn’t belong to any of the four types listed in the forms, please contact us at the following address: <a href="mailto:ixtheo-self-archiving@ub.uni-tuebingen.de">ixtheo-self-archiving@ub.uni-tuebingen.de</a></p>

      </div>
    </div>
  </div>
</div>
