<div class="cw-row">
    <div class="cw-col-lg-12 cw-ml-lg-4">
        <div class="cw-text-block"><br>
            <h1 class="cw-h1">Fachreferent*innen und theologische Bibliothekar*innen</h1>
            <p>Im Kontakt zu Studierenden und Wissenschaftler*innen an den Universitätsstandorten sind Fachreferent*innen für 
                Theologie und theologische Bibliothekar*innen wichtige Multiplikator*innen. Sie bilden die Schnittstelle 
                zwischen Bibliotheken und Fakultäten oder Instituten. Der Fachinformationsdienst (FID) Theologie bietet Vernetzungstreffen für 
                Fachreferent*innen und theologische Bibliothekar*innen an. Weiterhin gibt es eine Mailingliste, 
                die über neue Entwicklungen informiert:</p>
            <p><a target="_blank" href="https://listserv.uni-tuebingen.de/mailman/listinfo/fachreferat_theol">https://listserv.uni-tuebingen.de/mailman/listinfo/fachreferat_theol</a></p>
        </div>
    </div>
</div>