<div class="cw-row">
    <div class="cw-col-lg-12 cw-ml-lg-4">
        <div class="cw-text-block"><br>
            <h1 class="cw-h1">Subject Specialists and Theological Librarians</h1>
            <p>Subject specialists and theological librarians are important multipliers through their contacts with students and academics. They constitute a vital link between libraries and faculties or institutes. The Specialized Information Service (Fachinformationsdienst, FID) in theology offers networking meetings for subject specialists and theological librarians. We have a mailing list which keeps you informed of new developments (in German):</p>
            <p><a target="_blank" href="https://listserv.uni-tuebingen.de/mailman/listinfo/fachreferat_theol">https://listserv.uni-tuebingen.de/mailman/listinfo/fachreferat_theol</a></p>
        </div>
    </div>
</div>
