<?php
    $this->assetManager()->appendStyleLink('vendor/fontawesome-free-6/awesome.css');
    $this->assetManager()->appendStyleLink('vendor/fontawesome-free-6/solid.css');
?>

<section class="cw-p-2">
    <div id="map" class="map"></div>
    <?php $jsSnippet = <<<EOD
    $(function () {
        IxTheo2.loadMap('fachin');
    });
    EOD;
    ?>
<?=$this->assetManager()->outputInlineScriptString($jsSnippet)?>
</section>
<div class="cw-row">
    <div class="cw-col-lg-12 cw-ml-lg-4">
        <div class="cw-text-block"><br>
            <h1 class="cw-h1">Specialized Information Services</h1>

            <p>We have cooperation agreements with several other Specialized Information Services in Germany (Fachinformationsdienste, FIDs) to document literature which is important for our respective academic fields. We also work together on issues such as licensing agreements, purchases and data exchange.</p>
            <p>We currently have cooperation agreements with the following FIDs:</p>
            <ul>
                <li><a target="_blank" href="https://www.fu-berlin.de/sites/philbib/02Service/service-fuer-die-forschung/Fachinformationsdienste/FID-Altertumswissenschaften.html">FID Altertumswissenschaften</a> (<a target="_blank" href="https://www.propylaeum.de/">Propylaeum</a>)</li>
                <li><a target="_blank" href="https://www.bsb-muenchen.de/ueber-uns/projekte/fachinformationsdienst-geschichtswissenschaft/">FID Geschichtswissenschaft</a> (<a target="_blank" href="https://www.historicum.net/home">historicum.net</a>)</li>
                <li><a target="_blank" href="https://www.ub.uni-frankfurt.de/judaica3/">FID Jüdische Studien</a> (<a target="_blank" href="https://portal.jewishstudies.de/">portal.jewishstudies</a>)</li>
                <li><a target="_blank" href="https://www.ub.uni-heidelberg.de/fachinfo/kunst/Welcome.html">FID Kunst, Fotografie, Design</a> (<a target="_blank" href="https://www.arthistoricum.net/">arthistoricum.net</a>)</li>
                <li><a target="_blank" href="https://bibliothek.uni-halle.de/nutzen-besuchen/fachspezifische-services/fachinformationsdienst-fid-nahost-nordafrika-und-islamstudien/">FID Nahost-, Nordafrika- und Islamstudien</a> (<a target="_blank" href="https://www.menalib.de/">menalib</a>)</li>
                <li><a target="_blank" href="https://www.bsb-muenchen.de/sammlungen/osteuropa/fachinformationsdienst/">FID Ost-, Ostmittel-, Südosteuropa</a> (<a target="_blank" href="https://www.osmikon.de/">osmikon</a>)</li>
                <li><a target="_blank" href="https://ub.uni-koeln.de/forschen-publizieren/projekte/fachinformationsdienst-philosophie">FID Philosophie</a> (<a target="_blank" href="https://philportal.de/">philportal</a>)</li>
                <li><a target="_blank" href="https://uni-tuebingen.de/einrichtungen/universitaetsbibliothek/ueber-uns/bibliotheksbestand/fachinformationsdienste/religionswissenschaft/">FID Religionswissenschaft</a> (<a target="_blank" href="https://relbib.de/">RelBib</a>)</li>
                <li><a target="_blank" href="https://fiviblk.de/">Fachinformationsverbund Internationale Beziehungen und Länderkunde</a> (<a target="_blank" href="https://ireon-portal.de/">IREON</a>)</li>
            </ul>
            <p>IxTheo is always interested in new cooperations and partnerships with other FIDs. If you are interested in working with us, please contact us at: <a href="mailto:ixtheo@ub.uni-tuebingen.de">ixtheo@ub.uni-tuebingen.de</a>.</p>
        </div>
    </div>
</div>
