<div class="cw-row">
    <div class="cw-col-lg-12 cw-ml-lg-4">
        <div class="cw-text-block"><br>
            <h1 class="cw-h1">Theologische Community</h1>

            <p>Die Zusammenarbeit mit verschiedenen Organisationen der theologischen Community ermöglicht vielfältige Synergien. Regelmäßig werden die Gremien über Neuerungen im IxTheo informiert.</p>
            <p>Aktuell arbeitet IxTheo mit folgenden Institutionen aus der theologischen Community zusammen:</p>
            <ul>
                <li>Vereinigung der Arbeitsgemeinschaften für Katholische Theologie (VAKT)</li>
                <li>Wissenschaftliche Gesellschaft für Theologie (WGTh)</li>
                <li>Evangelisch-Theologischer Fakultätentag</li>
                <li>Katholisch-Theologischer Fakultätentag</li>
                <li>Conferenza Episcopale Italiana</li>
                <li>Globethics</li>
                <li>International Academy of Practical Theology (IAPT)</li>
                <li>RESILIENCE (Religious Studies Infrastructure: Tools, Innovation, Experts, Connections and Centres in Europe)</li>
            </ul>
            <p> IxTheo ist offen für neue Kooperationen und Partnerschaften innerhalb der theologischen Community. Wenn Sie Interesse an einer Zusammenarbeit haben, wenden Sie sich gerne an <a href="mailto:ixtheo@ub.uni-tuebingen.de">ixtheo@ub.uni-tuebingen.de</a>.</p>
        </div>
    </div>
</div>