<div class="cw-row">
  <div class="cw-col-lg-12 cw-ml-lg-4">
    <div class="cw-text-block"><br>
      <h1 class="cw-h1">Digitalisierung (DigiTheo)</h1>
      <p>Im Rahmen verschiedener von der Deutschen Forschungsgemeinschaft (DFG) geförderter Projekte werden vom Fachinformationsdienst Theologie regelmäßig umfangreiche Digitalisierungsprojekte durchgeführt.</p>
      <p>Zeitschriften und Bücher früherer Jahrhunderte ebenso wie aktuelle Publikationen werden professionell digitalisiert und die
          Digitalisate werden mit eigenen Einträgen im Index Theologicus (IxTheo) verknüpft.
          So können die Werke und die darin enthaltenen Aufsätze im IxTheo recherchiert und mit einem
          Klick digital eingesehen oder heruntergeladen werden. Vielfach kann außerdem der Volltext der Publikationen durchsucht werden.</p>
      <p>Bislang wurden in fünf „DigiTheo“-Projekten zahlreiche wichtige theologische Publikationen online gestellt:</p>
      <div role="tablist" class="digiTabs">
        <br />
        <div class="cw-card cw-mb-3">
          <div>

            <!-- Nav tabs -->
            <ul class="nav nav-tabs nav-justified" role="tablist">
              <li role="presentation"><a href="#tab1" aria-controls="" role="tab" data-toggle="tab">DigiTheo 1 (2009–2012)</a></li>
              <li role="presentation"><a href="#tab2" aria-controls="" role="tab" data-toggle="tab">DigiTheo 2 (2011–2015)</a></li>
              <li role="presentation"><a href="#tab3" aria-controls="" role="tab" data-toggle="tab">DigiTheo 3 (2015–2017)</a></li>
              <li role="presentation"><a href="#tab4" aria-controls="" role="tab" data-toggle="tab">DigiTheo 4</a></li>
              <li role="presentation" class="active"><a href="#tab5" aria-controls="" role="tab" data-toggle="tab">DigiTheo 5 (2020–2024)</a></li>
            </ul>

            <!-- Tab panes -->
            <div class="tab-content">
              <div role="tabpanel" class="tab-pane" id="tab1">
                <p><b>Digitalisierung zentraler theologischer Zeitschriften und ausgewählter Monographien des 19. Jahrhunderts</b></p>
                <p>Im Projekt DigiTheo 1 wurden theologische Publikationsorgane und Monographien berücksichtigt, die im Prozess der theologischen Schulenbildung des 19. Jahrhunderts entstanden sind bzw. in denen dieser Prozess wissenschaftlich rekonstruierbar wird.</p> 
				<p>Für nähere Informationen zum Projekt vgl. <a href="https://ixtheo.de/Record/1893565319">diesen Aufsatz</a>.</p>
				<p>Folgende Zeitschriften wurden digitalisiert:</p>
                <ol>
				<li><a href="https://opendigi.ub.uni-tuebingen.de/digitue/theo/akzs.html">Allgemeine kirchliche Zeitschrift (Elberfeld 1860-1872)</a></li>			
				<li><a href="https://opendigi.ub.uni-tuebingen.de/digitue/theo/artl.html">Allgemeines Repertorium für die theologische Litteratur und kirchliche Statistik (Berlin 1833-1860)</a></li>
				<li><a href="https://opendigi.ub.uni-tuebingen.de/digitue/theo/agtck.html">Annalen der gesammten Theologie und christlichen Kirche (Bayreuth 1831-1836)</a></li>
				<li><a href="https://opendigi.ub.uni-tuebingen.de/digitue/theo/dzcw.html">Deutsche Zeitschrift für christliche Wissenschaft und christliches Leben (Berlin 1850-1861)</a></li>	
				<li><a href="https://opendigi.ub.uni-tuebingen.de/digitue/theo/jdth.html">Jahrbücher für deutsche Theologie (Gotha/Stuttgart 1856-1878)</a></li>				
				<li><a href="https://opendigi.ub.uni-tuebingen.de/digitue/theo/jpth.html">Jahrbücher für protestantische Theologie (Braunschweig 1875-1892)</a></li>
				<li><a href="https://opendigi.ub.uni-tuebingen.de/digitue/theo/jthkr.html">Jahrschrift für Theologie und Kirchenrecht der Katholiken (Ulm 1806 - 1830)</a></li>		
				<li><a href="https://opendigi.ub.uni-tuebingen.de/digitue/theo/kath.html">Der Katholik: Zeitschrift für katholisches Wissen und kirchliches Leben (Mainz 1821-1918) </a></li>				
				<li><a href="https://opendigi.ub.uni-tuebingen.de/digitue/theo/litrdsch.html">Literarische Rundschau (Freiburg i.Br. 1875-1880)</a></li>				
				<li><a href="https://opendigi.ub.uni-tuebingen.de/digitue/theo/stml.html">Stimmen aus Maria Laach (Freiburg i.Br. 1871-1914)</a></li>				
				<li><a href="https://opendigi.ub.uni-tuebingen.de/digitue/theo/thjbt.html">Theologische Jahrbücher (Tübingen 1842-1857) </a></li>
				<li><a href="https://opendigi.ub.uni-tuebingen.de/digitue/theo/thq.html">Theologische Quartalschrift (Ostfildern 1819-1900)</a></li>
				<li><a href="https://opendigi.ub.uni-tuebingen.de/digitue/theo/thstkr.html">Theologische Studien und Kritiken: Beiträge zur Theologie und Religionswissenschaft (Leipzig 1828-1941) </a></li>				
				<li><a href="https://opendigi.ub.uni-tuebingen.de/digitue/theo/tzw.html">Theologische Zeitschrift (Wien 1813-1826)</a></li>				
				<li><a href="http://idb.ub.uni-tuebingen.de/digitue/theo/thlblb">Theologisches Literaturblatt (Bonn 1866-1877)</a></li>				
				<li><a href="https://opendigi.ub.uni-tuebingen.de/digitue/theo/tzth.html">Tübinger Zeitschrift für Theologie (Tübingen 1828-1840)</a></li>
				<li><a href="https://opendigi.ub.uni-tuebingen.de/digitue/theo/zlthk.html">Zeitschrift für die gesammte lutherische Theologie und Kirche (Leipzig 1840-1878)</a></li>
				<li><a href="https://opendigi.ub.uni-tuebingen.de/digitue/theo/zpkt.html">Zeitschrift für Philosophie und katholische Theologie (Bonn 1832-1853)</a></li>
				<li><a href="https://opendigi.ub.uni-tuebingen.de/digitue/theo/zpk.html">Zeitschrift für Protestantismus und Kirche (Erlangen 1838-1876)</a></li>
				<li><a href="https://opendigi.ub.uni-tuebingen.de/digitue/theo/zth.html">Zeitschrift für Theologie (Freiburg i.Br. 1839-1849)</a></li>
				</ol>
				<p>Folgende Monographien wurden digitalisiert:</p>
				<ol>
				<li><a href="https://opendigi.ub.uni-tuebingen.de/opendigi/andlaw1863">Andlaw, Heinrich von: Offenes Sendschreiben an Herrn Dr. Joh. von Kuhn, Professor der Theologie an der Universität Tübingen, über die Frage der "freien katholischen Universität" (1863)</a></li>				
				<li><a href="https://opendigi.ub.uni-tuebingen.de/opendigi/baur1827">Baur, Ferdinand Christian: Primae rationalismi et supranaturalismi historiae capita potiora (1827)</a></li>
				<li><a href="https://opendigi.ub.uni-tuebingen.de/opendigi/baur1834">Baur, Ferdinand Christian: Der Gegensatz des Katholicismus und Protestantismus nach den Principien und Hauptdogmen der beiden Lehrbegriffe: Mit besonderer Rücksicht auf Herrn Dr. Möhlers Symbolik (1834)</a></li>
				<li><a href="https://opendigi.ub.uni-tuebingen.de/opendigi/baur1836">Baur, Ferdinand Christian: Der Gegensatz des Katholicismus und Protestantismus nach den Principien und Hauptdogmen der beiden Lehrbegriffe: Zweite verbesserte, mit einer Uebersicht über die neuesten, auf die Symbolik sich beziehenden, Controversen vermehrte, Ausgabe (1836)</a></li>		
				<li><a href="https://opendigi.ub.uni-tuebingen.de/opendigi/beck1838">Beck, Johann Tobias: Einleitung in das System der christlichen Lehre: propädeutische Entwicklung der christlichen Lehr-Wissenschaft (1838)</a></li>
				<li><a href="https://opendigi.ub.uni-tuebingen.de/opendigi/baur1855">Baur, Ferdinand Christian: An Herrn Dr. Karl Hase, Prof. der Theol. an der Univ. Jena, H. G. A. Geh. Kirchenrath, Ritter des G. S. W. O. vom weißen Falken (1855)</a></li>
				<li><a href="https://opendigi.ub.uni-tuebingen.de/opendigi/baur1860">Baur, Ferdinand Christian: Die Tübinger Schule und ihre Stellung zur Gegenwart: Zweite, neu durchgesehene und mit einigen Zusätzen vermehrte Auflage (1860)</a></li>
				<li><a href="https://opendigi.ub.uni-tuebingen.de/opendigi/baur1861">Baur, Ferdinand Christian: Worte der Erinnerung an Ferdinand Christian von Baur (1861)</a></li>								
				<li><a href="https://opendigi.ub.uni-tuebingen.de/opendigi/beck1836">Beck, Johann Tobias: Ueber die wissenschaftliche Behandlung der christlichen Lehre (1836)</a></li>				
				<li><a href="https://opendigi.ub.uni-tuebingen.de/opendigi/beck1843">Beck, Johann Tobias: Ueber das Verhältniss des Christenthums zum Zeitleben (1843)</a></li>	
				<li><a href="https://opendigi.ub.uni-tuebingen.de/opendigi/beck1848">Beck, Johann Tobias: Die alte Wahrheit für die neue Zeit (1848)</a></li>				
				<li><a href="https://opendigi.ub.uni-tuebingen.de/opendigi/beck1879">Beck, Johann Tobias: Worte der Erinnerung an Dr. Johann Tobias Beck (1879)</a></li>				
				<li><a href="https://opendigi.ub.uni-tuebingen.de/opendigi/bengel1831">Bengel, Ernst Gottlieb: Reden über Religion und Christenthum an Studierende der Universität Tübingen aus allen Facultäten (1831)</a></li>				
				<li><a href="https://opendigi.ub.uni-tuebingen.de/opendigi/dieringer1849">Dieringer, Franz Xaver: Offenes Sendschreiben "über die kirchlichen Zustände der Gegenwart" (1849)</a></li>				
				<li><a href="https://opendigi.ub.uni-tuebingen.de/opendigi/drey1819">Drey, Johann Sebastian: Kurze Einleitung in das Studium der Theologie: mit Rücksicht auf den wissenschaftlichen Standpunct und das katholische System (1819)</a></li>				
				<li><a href="https://opendigi.ub.uni-tuebingen.de/opendigi/drey1834">Drey, Johann Sebastian von: Was ist in unserer Zeit von Synoden zu erwarten? (1834)</a></li>	
				<li><a href="https://opendigi.ub.uni-tuebingen.de/opendigi/ewald1842">Ewald, Heinrich Georg August: Ein Wort zum Frieden beider Kirchen (1842)</a></li>						
				<li><a href="https://opendigi.ub.uni-tuebingen.de/opendigi/ewald1848">Ewald, Heinrich Georg August: Heinrich Ewald über seinen Weggang von der Universität Tübingen mit anderen Zeitbetrachtungen (1848)</a></li>						
				<li><a href="https://opendigi.ub.uni-tuebingen.de/opendigi/evthfaktue1830">Feier des dritten Säkularfestes der Uebergabe der Augsburgischen Confession auf der Universität Tübingen (1830)</a></li>				
				<li><a href="https://opendigi.ub.uni-tuebingen.de/opendigi/feilmoser1830">Feilmoser, Andreas Benedict: Einleitung in die Bücher des neuen Bundes (1830)</a></li>				
				<li><a href="https://opendigi.ub.uni-tuebingen.de/opendigi/flatt1806">Flatt, Carl Christian: Kritische Beiträge zu Storrs Dogmatik (1806)</a></li>				
				<li><a href="https://opendigi.ub.uni-tuebingen.de/opendigi/gottschick1891">Gottschick, Johannes: Das Verhältnis des christlichen Glaubens zum modernen Geistesleben (1891)</a></li>				
				<li><a href="https://opendigi.ub.uni-tuebingen.de/opendigi/gottschick1893">Gottschick, Johannes: Die Bedeutung der historisch-kritischen Schriftforschung für die evangelische Kirche (1893)</a></li>
				<li><a href="https://opendigi.ub.uni-tuebingen.de/opendigi/gottschick1901">Gottschick, Johannes: Abschiedspredigten an die aus der Predigeranstalt austretenden Kandidaten (1901)</a></li>				
				<li><a href="https://opendigi.ub.uni-tuebingen.de/opendigi/gratz_1817">Gratz, Peter Aloys: Ueber die Gränzen der Freiheit, die einem Katholiken in Betreff der Erklärung der heiligen Schrift zusteht (1817)</a></li>				
				<li><a href="https://opendigi.ub.uni-tuebingen.de/opendigi/harless1834">Harleß, Adolf von: Die kritische Bearbeitung des Lebens Jesu von Dr. Dav. Friedr. Strauß (1836)</a></li>				
				<li><a href="https://opendigi.ub.uni-tuebingen.de/opendigi/hase1855">Hase, Karl August von: Die Tübinger Schule: Ein Sendschreiben an Herrn Dr. Ferdinand Christian von Baur, ersten Professor der evang. Theol. an der Univ. Tübingen, Ritter des Ordens der würtemb. Krone (1855)</a></li>
				<li><a href="https://opendigi.ub.uni-tuebingen.de/opendigi/hefele1870">Hefele, Karl Joseph: Defensio episcopi Rottenburgensis (1870)</a></li>				
				<li><a href="https://opendigi.ub.uni-tuebingen.de/opendigi/hirscher1843">Hirscher, Johann Baptist von: Erklärung des Professors Dr. von Hirscher zu Freiburg (1843)</a></li>				
				<li><a href="https://opendigi.ub.uni-tuebingen.de/opendigi/hirscher1849">Hirscher, Johann Baptist von: Die kirchlichen Zustände der Gegenwart (1843)</a></li>				
				<li><a href="https://opendigi.ub.uni-tuebingen.de/opendigi/kautysch1883">Kautzsch, Emil Friedrich: Drei Vorträge (1883)</a></li>				
				<li><a href="https://opendigi.ub.uni-tuebingen.de/opendigi/kautysch1900">Kautzsch, Emil Friedrich: Bibelwissenschaft und Religionsunterricht: sechs Thesen (1900)</a></li>				
				<li><a href="https://opendigi.ub.uni-tuebingen.de/opendigi/keppler1883">Keppler, Paul Wilhelm von: Das Johannes-Evangelium und das Ende des ersten christlichen Jahrhunderts (1883)</a></li>				
				<li><a href="https://opendigi.ub.uni-tuebingen.de/opendigi/knobel1844">Knobel, August: Exegetisches Vademecum für Herrn Professor Ewald in Tübingen (1844)</a></li>				
				<li><a href="https://opendigi.ub.uni-tuebingen.de/opendigi/koestlin1815">Köstlin, Nathanael Friedrich: Abschieds-Predigt am Sonntag Estomihi den 5. Februar 1815 (1815)</a></li>				
				<li><a href="https://opendigi.ub.uni-tuebingen.de/opendigi/kuhn1838">Kuhn, Johannes: Das Leben Jesu: wissenschaftlich bearbeitet. Erster Band. (1838)</a></li>
				<li><a href="https://opendigi.ub.uni-tuebingen.de/opendigi/linsenmann1877">Linsenmann, Franz Xaver: Konrad Summenhart: ein Culturbild aus den Anfängen der Universität Tübingen (1877)</a></li>
				<li><a href="https://opendigi.ub.uni-tuebingen.de/opendigi/mack1836">Mack, Martin Joseph: Über die ursprünglichen Leser des Briefes an die Hebräer (1836)</a></li>				
				<li><a href="https://opendigi.ub.uni-tuebingen.de/opendigi/marheineke1833">Marheineke, Philipp: Über J. A. Möhler's Symbolik (1833)</a></li>				
				<li><a href="https://opendigi.ub.uni-tuebingen.de/opendigi/moehler1834">Möhler, Johann Adam: Neue Untersuchungen der Lehrgegensätze zwischen den Katholiken und Protestanten: Eine Vertheidigung meiner Symbolik gegen die Kritik des Herrn Professors Dr. Baur in Tübingen (1834)</a></li>
				<li><a href="https://opendigi.ub.uni-tuebingen.de/opendigi/neander1836">Neander, August: Erklärung in Beziehung auf einen ihn betreffenden Artikel der Allgemeinen Zeitung (1836)</a></li>
				<li><a href="https://opendigi.ub.uni-tuebingen.de/opendigi/oehler1845">Oehler, Gustav Friedrich: Prolegomena zur Theologie des Alten Testaments (1845)</a></li>
				<li><a href="https://opendigi.ub.uni-tuebingen.de/opendigi/oehler1872">Oehler, Gustav Friedrich: Gesammelte Seminar-Reden (1872)</a></li>
				<li><a href="https://opendigi.ub.uni-tuebingen.de/opendigi/osiander1837">Osiander, Johann Ernst: Apologie des Lebens Jesu gegen den neuesten Versuch, es in Mythen aufzulösen (1837)</a></li>
				<li><a href="https://opendigi.ub.uni-tuebingen.de/opendigi/palmer1839">Palmer, Christian David Friedrich von: An Freunde und Feinde des Pietismus (1839)</a></li>
				<li><a href="https://opendigi.ub.uni-tuebingen.de/opendigi/sack1836">Sack, Karl Heinrich: Bemerkungen über den Standpunkt der Schrift: Das Leben Jesu, kritisch bearbeitet von D. F. Strauss (1836)</a></li>
				<li><a href="https://opendigi.ub.uni-tuebingen.de/opendigi/schlatter1896">Schlatter, Adolf: Heilige Anliegen der Kirche (1896)</a></li>
				<li><a href="https://opendigi.ub.uni-tuebingen.de/opendigi/schmid1852">Schmid, Christian Friedrich von: Blätter der Erinnerung an Christian Friedrich von Schmid (1852)</a></li>
				<li><a href="https://opendigi.ub.uni-tuebingen.de/opendigi/steudel1814">Steudel, Johann Christian Friedrich: über die Haltbarkeit des Glaubens an geschichtliche höhere Offenbarung Gottes (1814)</a></li>
				<li><a href="https://opendigi.ub.uni-tuebingen.de/opendigi/steudel1823">Steudel, Johann Christian Friedrich: De messianorum vaticiniorum momento in nostrae etiam aetatis pios Christi cultores vi sua nequaquam destituto prolusio (1823)</a></li>				
				<li><a href="https://opendigi.ub.uni-tuebingen.de/opendigi/steudel1831">Steudel, Johann Christian Friedrich: Mein Verhältniss zu den Rationalisten und zu der Evangelischen Kirchenzeitung (1831)</a></li>				
				<li><a href="https://opendigi.ub.uni-tuebingen.de/opendigi/steudel1832">Steudel, Johann Christian Friedrich: Welche Behandlung der Dogmatik verlangt an uns die Rücksicht auf die Anforderungen der Kirche, wie sie in unsern Tagen laut werden? (1832)</a></li>
				<li><a href="https://opendigi.ub.uni-tuebingen.de/opendigi/steudel1837">Steudel, Johann Christian Friedrich: J. C. F. Steudels kurzer Bescheid auf Dav. Friedr. Straussens Streitschriften (1837)</a></li>
				<li><a href="https://opendigi.ub.uni-tuebingen.de/opendigi/storr1803">Storr, Gottlob Christian: Lehrbuch der christlichen Dogmatik (1803)</a></li>
				<li><a href="https://opendigi.ub.uni-tuebingen.de/opendigi/strauss1839">Strauß, David Friedrich: Auseinandersetzungen um David Friedrich Strauß in Zürich (Sammlung von Flugschriften) (1839)</a></li>
				<li><a href="https://opendigi.ub.uni-tuebingen.de/opendigi/strauss1848">Strauß, David Friedrich: Sechs theologisch-politische Volksreden: Aus der deutschen Vierteljahresschrift besonders abgedruckt (1848)</a></li>
				<li><a href="https://opendigi.ub.uni-tuebingen.de/opendigi/kuhn1840">Volkmuth, Peter: Der Tübinger Januskopf oder Glauben und Wissen des Johannes Kuhn (1840)</a></li>
				<li><a href="https://opendigi.ub.uni-tuebingen.de/opendigi/weiysaecker1877">Weizsäcker, Carl von: Lehrer und Unterricht an der evangelisch-theologischen Facultät der Universität Tübingen von der Reformation bis zur Gegenwart (1877)</a></li>
				<li><a href="https://opendigi.ub.uni-tuebingen.de/opendigi/zeller1871">Zeller, Eduard: Die päpstliche Unfehlbarkeit und die Säcularisation des Kirchenstaats (1871)</a></li>
				<li><a href="https://opendigi.ub.uni-tuebingen.de/opendigi/zeller1880">Zeller, Eduard: Die freie Kirche im freien Staat (1880)</a></li>				
				</ol>
				<p>Weitere Informationen zur Förderung durch die DFG: <a target="_blank" href="https://gepris.dfg.de/gepris/projekt/154994557"><i class="fa fa-arrow-right"></i></a></p>
              </div>

              <div role="tabpanel" class="tab-pane" id="tab2">
                <p><b>Digitalisierung der Zeitschriften Theologisches Literaturblatt (1880–1943) und Theologische Literaturzeitung (1876–1995)</a></b></p> 
                <p>Im Projekt DigiTheo 2 wurden <a target="_blank" href="http://idb.ub.uni-tuebingen.de/digitue/theo/thlbl">„Theologisches Literaturblatt“ (1880–1943)</a> und <a target="_blank" href="http://idb.ub.uni-tuebingen.de/digitue/theo/thlz">„Theologische Literaturzeitung“ (1876–1995)</a> als zentrale theologische Rezensions-Zeitschriften des deutschen Sprachraums digitalisiert.</p>
				<p>Weitere Informationen zur Förderung durch die DFG:
                <a target="_blank" href="http://idb.ub.uni-tuebingen.de/digitue/theo/thq"><i class="fa fa-arrow-right"></i></a></p>
              </div>

              <div role="tabpanel" class="tab-pane" id="tab3">
                <p><b>Digitalisierung der Theologischen Quartalschrift (1901-2006)</b></p>
                Im Projekt DigiTheo 3 wurden die <a target="_blank" href="http://idb.ub.uni-tuebingen.de/digitue/theo/thq">Jahrgänge 1901-2006 der Theologischen Quartalschrift</a> als wichtigem Publikationsorgan der Katholisch-Theologischen Fakultät der Universität Tübingen digitalisiert. Das Projekt wurde von der Diözese Rottenburg-Stuttgart gefördert. Die Jahrgänge 1819–1900 waren bereits im Rahmen von DigiTheo 1 digitalisiert worden.
              </div>

              <div role="tabpanel" class="tab-pane" id="tab4">
                <p><b>Digitalisierung der Theologischen Revue (1902–2017)</b></p>
                Das als eigenständig geplante DigiTheo 4 Projekt wurde in das Projekt DigiTheo 5 integriert.
              </div>

              <div role="tabpanel" class="tab-pane active" id="tab5">
                <p><b>Digitalisierung von 71 theologischen Zeitschriften des 19., 20. und 21. Jahrhunderts</b></p>
                <p>Im Rahmen des Projektes DigiTheo 5 wurden Zeitschriften und Rezensionsorgane bearbeitet, die teils seit über hundert Jahren von zentraler Bedeutung für die Fachdiskussion sind. Jede Zeitschrift erhält eine eigene Website auf Basis der Plattform Open Journal Systems (OJS). Gleichzeitig werden die Beiträge einzeln in IxTheo verlinkt und sind von dort aus direkt erreichbar. Alle Aufsätze und Rezensionen werden mit maschinenlesbaren Volltexten (OCR) versehen und in die Volltextsuche des IxTheo integriert. Zusätzlich werden die Aufsätze mit der IxTheo-Klassifikation erschlossen und sind damit auch nach Fächern bzw. Themen recherchierbar.
                </p>
                <p>Für nähere Informationen zum Projekt vgl. <a href="https://ixtheo.de/Record/1697196101">diesen Aufsatz</a>.</p>
				<p>Folgende Zeitschriften wurden digitalisiert (in vielen Fällen einschließlich ihrer Beihefte und Vorgängerzeitschriften):</p>
                <ol>
				<li>Amt und Gemeinde (1947-2017)</li>
				<li>Analecta Praemonstratensia (1905-2013)</li>
				Analectes de l'ordre de Prémontré (1905-1914)
				<li>Augustiniana (1951-2012)</li>
				<li><a href="https://bgbr-zeitschrift.de/">Beiträge zur Geschichte des Bistums Regensburg (1967-2020)</a></li>
				<li><a href="https://biblische-notizen.digitheo.de">Biblische Notizen (1976-2009)</a></li>
				<li>Cistercienserchronik (1889-2016)</li>
				<li><a href="https://concilium-de.org/">Concilium (1965-2015)</a></li>
				<li><a href="https://diakonia.digitheo.de/">Diakonia (1966-2009)</a></li>
				Diakonia: Der Seelsorger (1970-1971)
				<li><a href="https://edith-stein-jahrbuch.de/">Edith Stein Jahrbuch (1995-2003)</a></li>
				<li><a href="https://ejt-journal.digitheo.de">European Journal of Theology (1992-2015)</a></li>
				<li><a href="https://fkth.org/">Forum Katholische Theologie (1985-2017)</a></li>
				<li>Freiburger Rundbrief (1948-2016)</li>
				Rundbrief zur Förderung der Freundschaft zwischen dem alten und dem neuen Gottesvolk (1948-1952/53)
				<li><a href="https://freikirchenforschung-jahrbuch.de/">Freikirchenforschung (1991-2016)</a></li>
				<li>Heiliger Dienst (1947-2018)</li>
				<li><a href="https://helvetia-franciscana.org/">Helvetia Franciscana (1932-2014)</a></li>
				Collectanea Helvetico-Franciscana (1932-1951)
				<li><a href="https://herderkorrespondenz.digitheo.de/">Herder-Korrespondenz (1946-1999)</a></li>
				<li><a href="https://ikaz-communio.de/">Internationale katholische Zeitschrift Communio (1972-2020)</a></li>
				<li>Jahrbuch für Augsburger Bistumsgeschichte (1967-2017)</li>
				<li><a href="https://jahrbuch-kbbw.digitheo.de">Jahrbuch Kirchliches Buch- und Bibliothekswesen (2000-2017)</a></li>
				<li><a href="https://jrp.digitheo.de">Jahrbuch der Religionspädagogik (1984-2015)</a></li>
				<li>Jahrbuch für Berlin-Brandenburgische Kirchengeschichte (1904-2017)</li>
				Jahrbuch für brandenburgische Kirchengeschichte (1904-1942)
				<li>Jahrbuch für Geschichte und Kunst im Bistum Hildesheim (1927-2017)</li>
				Die Diözese Hildesheim in Vergangenheit und Gegenwart (1964-2004)<br/>
				Unsere Diözese in Vergangenheit und Gegenwart (1927-1963)
				<li><a href="https://jeth.digitheo.de">Jahrbuch für evangelikale Theologie (1987-2016)</a></li>
				<li>Jahrbuch für evangelische Kirchengeschichte des Rheinlandes (1907-2018)</li>
				Monatshefte für evangelische Kirchengeschichte des Rheinlandes (1952-2012)<br/>
				Monatshefte für rheinische Kirchengeschichte (1907-1942)
				<li><a href="https://jskg-jahrbuch.de">Jahrbuch für schlesische Kirchengeschichte (1882-2017)</a></li>
				Jahrbuch für schlesische Kirche und Kirchengeschichte (1953-1959) <br/>
				Jahrbuch des Vereins für Schlesische Kirchengeschichte (1929-1941) <br/>
				Korrespondenzblatt des Vereins für Geschichte der Evangelischen Kirche Schlesiens (1882-1928)
				<li><a href="https://jahrbuch-wkg.de">Jahrbuch für westfälische Kirchengeschichte (1899-2016)</a></li>
				<a href="https://beiheft.jahrbuch-wkg.de">Jahrbuch für westfälische Kirchengeschichte. Beihefte (1954-1983)</a> <br/>
				Jahrbuch des Vereins für Westfälische Kirchengeschichte (1927-1972) <br/>
				Jahrbuch des Evangelischen Vereins für Westfälische Kirchengeschichte (1924-1926) <br/>
				Jahrbuch des Vereins für die Evangelische Kirchengeschichte Westfalens (1903-1922) <br/>
				Jahrbuch des Vereins für die Evangelische Kirchengeschichte der Grafschaft Mark (1899-1902)
				<li>Katechetische Blätter (1875-2016)</li>
				<li>Kirchliches Jahrbuch für die Evangelische Kirche in Deutschland (1874-2017)</li>
				Kirchliches Jahrbuch für die evangelischen Landeskirchen Deutschlands (1910-1934) <br/>
				Kirchliches Jahrbuch (1900-1909) <br/>
				Theologisches Jahrbuch (1875-1899) <br/>
				Schreib- und Hülfskalender für Geistliche <br/>
				<li>Luther (1919-1992)</li>
				<li><a href="https://lutherische-beitraege.de/">Lutherische Beiträge (1996-2018)</a></li>
				<li><a href="https://mlb-jahrbuch.de">Lutherische Kirche in der Welt (1946-2019)</a></li>
				Jahrbuch des Martin-Luther-Bundes (1946-1969)
				<li>Lutherjahrbuch (1919-2004)</li>
				<li>Mennonitische Geschichtsblätter (1936-2016)</li>
				<li><a href="https://mfcg-ci-reihe.de/">Mitteilungen und Forschungsbeiträge der Cusanus-Gesellschaft (1961-2014)</a></li>
				<li><a href="https://meakiz.digitheo.de">Mitteilungen zur kirchlichen Zeitgeschichte (1978-2006)</a></li>
				<li><a href="https://oekumenische-rundschau-zeitschrift.de/">Ökumenische Rundschau (1952-2011)</a></li>
				<li><a href="https://ordkorr.de/">Ordenskorrespondenz (1960-2017)</a></li>
				<li><a href="https://orienschristianus.de/">Oriens christianus (1901-2014)</a></li>
				<li>Orthodoxes Forum (1987-2014)</li>
				<li><a href="https://owep-archiv.digitheo.de">Ost-West: Europäische Perspektiven (2001-2016)</a></li>
				<li><a href="https://www.uni-muenster.de/Ejournals/index.php/zpth/index">Pastoraltheologische Informationen (1968-2009)</a></li>
				<li><a href="https://protokolle-zur-liturgie.de/">Protokolle zur Liturgie (2007-2018)</a></li>
				<li><a href="https://www.rpb-journal.eu">Religionspädagogische Beiträge (1978-2017)</a></li>
				<li><a href="https://rtlu.org">Rivista teologica di Lugano (1996-2004)</a></li>
				<li><a href="https://rjkg.de">Rottenburger Jahrbuch für Kirchengeschichte (1982-2017)</a></li>
				<li><a href="https://roemischequartalschrift.digitheo.de">Römische Quartalschrift für christliche Altertumskunde und Kirchengeschichte (1887-2009)</a></li>
				<li><a href="https://sathz.digitheo.de/">Salzburger theologische Zeitschrift (1997-2011)</a></li>
				<li><a href="https://zshkg.de">Schriften des Vereins für Schleswig-Holsteinische Kirchengeschichte (1897-2009)</a></li>
				Schriften des Vereins für Schleswig-Holsteinische Kirchengeschichte. 2. Reihe, Beiträge und Mitteilungen (1897-2006)
				<li>Stimmen der Zeit (1915-2009)</li>
				<li>Studien und Mitteilungen zur Geschichte des Benediktinerordens und seiner Zweige (1880-2014)</li>
				Studien und Mitteilungen aus dem Benediktiner- und dem Cistercienser-Orden (1882-1910) <br/>
				Wissenschaftliche Studien und Mittheilungen aus dem Benedictiner-Orden (1880-1881)
				<li>Texte & Kontexte (1978-2018)</li>
				<li><a href="https://theologie-philosophie.digitheo.de">Theologie und Philosophie (1926-2020)</a></li> 
				<a href="https://scholastik.digitheo.de">Scholastik (1926-1965)</a>
				<li><a href="https://thpq-archiv.org">Theologisch-praktische Quartalschrift (1848-2022)</a></li>
				<li>Theologische Revue (1902-2019)</li>
				<li><a href="https://theologisches-gespraech.org">Theologisches Gespräch (1977-2017)</a></li>
				<li><a href="https://zeitschrift-unitas-fratrum.de">Unitas Fratrum (1977-2018)</a></li>
				<li><a href="https://westh-zeitschrift.de">Werkstatt Schwule Theologie (1994-2015)</a></li>
				<li>Wichmann-Jahrbuch des Diözesangeschichtsvereins Berlin (1930-2017)</li>
				<li><a href="https://zeitschrift-althebraistik.digitheo.de">Zeitschrift für Althebraistik (1988-2015)</a></li>
				<li>Zeitschrift für bayerische Kirchengeschichte (1887-2013)</li>
				Beiträge zur bayerischen Kirchengeschichte (1894-1925) <br/>
				Blätter für bayerische Kirchengeschichte (1887-1891)
				<li><a href="https://zkg.digitheo.de/">Zeitschrift für Kirchengeschichte (1877-2015)</a></li>
				<li><a href="https://www.zmr-online.de/">Zeitschrift für Missionswissenschaft und Religionswissenschaft (1911-2016)</a></li>
				Missionswissenschaft und Religionswissenschaft (1938-1949)
				<li><a href="https://zthg.de/">Zeitschrift für Theologie und Gemeinde (1996-2018)</a></li>
				</ol>
				<p>Weitere Informationen zur Förderung durch die DFG: <a target="_blank" href="https://gepris.dfg.de/gepris/projekt/449077614"><i class="fa fa-arrow-right"></i></a></p>
              </div>
            </div>
          </div>
        </div>
      </div>
      <br />
      <br />
    </div>
  </div>
</div>

<style type="text/css">
.digiTabs .nav-tabs>li>a {
  font-size: 11px;
}
.digiTabs .tab-content {
  padding: 10px;
}
.digiTabs .nav-tabs>li>a {
  font-size: 16px;
}
</style>