<div class="container cw-py-5">
  <div class="cw-row">
    <div class="cw-col-lg-1">&nbsp;</div>
    <div class="cw-col-lg-10">
      <div class="cw-text-block">
        <h1 class="cw-h1">Digitalisierung</h1>
        <div class="cw-card cw-border-0 cw-shadow cw-mb-3">
          <div class="cw-card-header cw-bg-primary-100 cw-border-0 cw-py-0">
            <a class="cw-accordion-link collapsed" data-toggle="collapse" href="#collapse1" role="button" aria-expanded="false" aria-controls="collapse1">
              tab 1 title
            </a>
          </div>
          <div class="collapse" id="collapse1">
            <div class="cw-card-body cw-py-5">
              <p>teb1 text</p>
            </div>
          </div>
        </div>
        <div class="cw-card cw-border-0 cw-shadow cw-mb-3">
          <div class="cw-card-header cw-bg-primary-100 cw-border-0 cw-py-0">
            <a class="cw-accordion-link collapsed" data-toggle="collapse" href="#collapse2" role="button" aria-expanded="false" aria-controls="collapse2">
             tab 2 title
            </a>
          </div>
          <div class="collapse" id="collapse2">
            <div class="cw-card-body cw-py-5">
              <p>teb2 text</p>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="cw-col-lg-1">&nbsp;</div>
  </div>
</div>