<div class="cw-row">
  <div class="cw-col-lg-8">
    <div class="cw-text-block"><br>
      <h1 class="cw-h1">Digitalisierung (DigiTheo)</h1>
      <p>Im Rahmen verschiedener DFG-Projekte werden vom FID Theologie regelmäßig umfangreiche Digitalisierungsprojekte durchgeführt.</p>
      <p>Hierbei werden Zeitschriften und Bücher früherer Jahrhunderte ebenso wie aktuelle Publikationen professionell digitalisiert und die
          Digitalisate mit eigenen Einträgen im Index Theologicus (IxTheo) verknüpft.
          So können die Werke und die darin enthaltenen Aufsätze im IxTheo recherchiert und mit einem
          Klick digital eingesehen oder heruntergeladen werden. Vielfach kann außerdem der Volltext der Publikationen durchsucht werden.</p>
      <p>Bislang wurden in fünf „DigiTheo“-Projekten zahlreiche wichtige theologische Publikationen online gestellt:</p>
      <div role="tablist" class="digiTabs">
        <br />
        <div class="cw-card cw-mb-3">
          <div>

            <!-- Nav tabs -->
            <ul class="nav nav-tabs nav-justified" role="tablist">
              <li role="presentation"><a href="#tab1" aria-controls="" role="tab" data-toggle="tab">DigiTheo 1 (2009–2012)</a></li>
              <li role="presentation"><a href="#tab2" aria-controls="" role="tab" data-toggle="tab">DigiTheo 2 (2011–2015)</a></li>
              <li role="presentation"><a href="#tab3" aria-controls="" role="tab" data-toggle="tab">DigiTheo 3 (2015–2017)</a></li>
              <li role="presentation"><a href="#tab4" aria-controls="" role="tab" data-toggle="tab">DigiTheo 4</a></li>
              <li role="presentation" class="active"><a href="#tab5" aria-controls="" role="tab" data-toggle="tab">DigiTheo 5 (2020–2024)</a></li>
            </ul>

            <!-- Tab panes -->
            <div class="tab-content">
              <div role="tabpanel" class="tab-pane" id="tab1">
                Digitalisierung <a href="<?=$this->url('content-page', ['page' => 'theology_digital'])?>">zentraler theologischer Zeitschriften</a> und ausgewählter <a href="<?=$this->url('content-page', ['page' => 'theology_digital'])?>">Monographien des 19. Jahrhunderts</a> 
                Im Projekt DigiTheo 1 wurden theologische Publikationsorgane und Monographien berücksichtigt, die im Prozess der theologischen Schulenbildung des 19. Jahrhunderts entstanden sind bzw. in denen dieser Prozess wissenschaftlich rekonstruierbar wird.
                Weitere Informationen zur Förderung durch die DFG: <a target="_blank" href="https://gepris.dfg.de/gepris/projekt/154994557">https://gepris.dfg.de/gepris/projekt/154994557</a>
              </div>

              <div role="tabpanel" class="tab-pane" id="tab2">
                Digitalisierung der Zeitschriften <a target="_blank" href="http://idb.ub.uni-tuebingen.de/digitue/theo/thlblb">„Theologisches Literaturblatt“ (1880–1943)</a> und <a target="_blank" href="http://idb.ub.uni-tuebingen.de/digitue/theo/thlz">„Theologische Literaturzeitung“ (1876–1995)</a> als zentrale theologische Rezensions-Zeitschriften des deutschen Sprachraums
                Weitere Informationen zur Förderung durch die DFG:
                <a target="_blank" href="http://idb.ub.uni-tuebingen.de/digitue/theo/thq">https://gepris.dfg.de/gepris/projekt/208358441</a>
              </div>

              <div role="tabpanel" class="tab-pane" id="tab3">
                Digitalisierung der <a target="_blank" href="http://idb.ub.uni-tuebingen.de/digitue/theo/thq">Theologischen Quartalschrift (1901–2006)</a> als wichtiges Publikationsorgan der Katholisch-Theologischen Fakultät der Universität Tübingen
                Das Projekt wurde von der Diözese Rottenburg gefördert. Die Jahrgänge 1819–1900 wurden bereits im Rahmen von DigiTheo 1 digitalisiert.
              </div>

              <div role="tabpanel" class="tab-pane" id="tab4">
                Digitalisierung der Theologischen Revue (1902–2017)
                Das als eigenständig geplante DigiTheo 4 Projekt wurde in das Projekt DigiTheo 5 integriert.
              </div>

              <div role="tabpanel" class="tab-pane active" id="tab5">
                Digitalisierung von 71 theologischen Zeitschriften des 19., 20. und 21. Jahrhunderts
                Im Rahmen des Projektes DigiTheo 5 wurden Zeitschriften und Rezensionsorgane bearbeitet, die teils seit über hundert Jahren von zentraler Bedeutung für die Fachdiskussion sind. Jede Zeitschrift erhält eine eigene Website auf Basis der Plattform Open-Journal-System (OJS). Gleichzeitig werden die Beiträge einzeln in IxTheo verlinkt und sind von dort aus direkt erreichbar. Alle Aufsätze und Rezensionen werden mit maschinenlesbaren Volltexten (OCR) versehen und in die Volltextsuche des IxTheo integriert. Zusätzlich werden die Aufsätze mit der IxTheo-Klassifikation erschlossen und sind damit auch nach Fächern bzw. Themen recherchierbar.
                Eine Liste der bearbeiteten Zeitschriften und Jahrgänge finden Sie hier:  <a href="https://ixtheo.de/docs/DigiTheo5_de.pdf">https://ixtheo.de/docs/DigiTheo5_de.pdf</a>
                Weitere Informationen zur Förderung durch die DFG: <a target="_blank" href="https://gepris.dfg.de/gepris/projekt/449077614">https://gepris.dfg.de/gepris/projekt/449077614</a>
              </div>
            </div>
          </div>
        </div>
      </div>
      <br />
      <br />
    </div>
  </div>
</div>

<style type="text/css">
.digiTabs .nav-tabs>li>a {
  font-size: 11px;
}
.digiTabs .tab-content {
  padding: 10px;
}
</style>