<div class="container cw-py-5">
  <div class="cw-row">
    <div class="cw-col-lg-8">
      <div class="cw-text-block">
        <h1 class="cw-h1">Übersicht Open Access</h1>
          <p>Der Fachinformationsdienst (FID) Theologie setzt sich für den freien Zugang zu theologischer und religionswissenschaftlicher Literatur ein. Das geschieht im Rahmen von unterschiedlichen Projekten zum Thema Open Access:</p>

          <h1 class="cw-h5">IxTheo Open Journals</h1>
          <p>Der FID Theologie bietet die Möglichkeit, theologische wissenschaftlichen Zeitschriften dauerhaft in Open Access zu hosten. Neben der Gründung neuer Publikationsorgane begleiten wir auch die Transformation bestehender Zeitschriften in Open Access.</p>
          <p>Nähere Informationen finden Sie <a href="<?=$this->url('content-page', ['page' => 'OpenJournals']) ?>">hier</a>.</p>

          <h1 class="cw-h5">Self-Archiving</h1>
          <p>Forschende aus allen theologischen Fachgebieten können Zweitveröffentlichungen ihrer wissenschaftlichen Publikationen selbst im Index Theologicus (IxTheo) hochladen und im Open Access zur Verfügung stellen.</p>
          <p>Nähere Informationen finden Sie <a href="<?=$this->url('content-page', ['page' => 'OpenText']) ?>">hier</a>.</p>

          <h1 class="cw-h5">Open Text Service (Zweitveröffentlichung)</h1>
          <p>Bei diesem Service übernimmt der FID die Prüfung, Katalogisierung und Digitalisierung der Beiträge, die Forschende zweitveröffentlichen möchten. 2023 konnten sich Autor*innen für eine neue Projektphase anmelden.</p>
          <p>Nähere Informationen finden Sie <a href="<?=$this->url('content-page', ['page' => 'OpenText']) ?>">hier</a>.</p>

          <h1 class="cw-h5">DigiTheo</h1>
          <p>In mehreren Projekten werden wichtige theologische Zeitschriften und Monographien vollständig digitalisiert und im Open Access zur Verfügung gestellt.</p>
          <p>Nähere Informationen und eine Übersicht über die einzelnen Projekte finden Sie <a href="<?=$this->url('content-page', ['page' => 'TheologyDigital']) ?>">hier</a>.</p>

          <h1 class="cw-h5">Digitalisierung on demand</h1>
          <p>In Zusammenarbeit mit der Bayerischen Staatsbibliothek München bietet der FID Theologie die Möglichkeit, einzelne urheberrechtsfreie Bände kostenfrei zu digitalisieren, wenn diese für die Forschung benötigt werden.</p>
          <p>Damit ein Werk im Rahmen dieses Services digitalisiert werden kann, müssen folgende Voraussetzungen erfüllt sein:</p>
            <ul>
              <li>Das Werk ist gemeinfrei (bei in Deutschland erschienenen Werken im Normalfall nach Ablauf von 70 Jahren seit dem Tod des Urhebers).</li>
              <li>Der Band befindet sich im Bestand der Universitätsbibliothek Tübingen oder der Bayerischen Staatsbibliothek München.</li>
              <li>Das Werk ist inhaltlich einem der an der UB Tübingen oder der BSB München vertretenen Fachinformationsdienste (Theologie, Religionswissenschaft, Geschichtswissenschaft, Altertumswissenschaft, Ost-, Ostmittel- und Südosteuropa) zuzuordnen oder wird für Forschung in einem der genannten Fachgebiete benötigt.</li>
              <li>Es handelt sich um einen einzelnen Band oder wenige Einzelfälle (im Rahmen dieses Services können keine Zeitschriftenjahrgänge oder ganzen Literaturlisten digitalisiert werden).</li>
            </ul>
          <p>Wenn Sie ein Werk im Rahmen dieses Service digitalisieren lassen möchten, wenden Sie sich an: <a href="mailto:ixtheo@ub.uni-tuebingen.de">Kontakt</a></p>
      </div>
    </div>
  </div>
</div>