<div class="container cw-py-5">
  <div class="cw-row">
    <div class="cw-col-lg-8">
      <div class="cw-text-block">
        <h1 class="cw-h1">Open Access</h1>
          <p>The Specialized Information Service (Fachinformationsdienst, FID) in Theology actively supports open access to academic literature in theology and religious studies. We do this through various projects and services:</p>

          <h1 class="cw-h5">IxTheo Open Journals</h1>
          <p>The FID Theology provides a service to host theological academic journals permanently in open access. We assist users in starting new journals as well as in transforming existing journals into open access journals.</p>
          <p>For more information on this service, see <a href="<?=$this->url('content-page', ['page' => 'OpenJournals']) ?>">IxTheo Open Journals</a>.</p>

          <h1 class="cw-h5">Self-Archiving</h1>
          <p>Researchers in all theological disciplines can self-archive their academic publications and make them available online in open access by uploading them in the Index Theologicus (IxTheo).</p>
          <p>For more information on this service, see <a href="<?=$this->url('content-page', ['page' => 'OpenText']) ?>">Self-Archiving</a>.</p>

          <h1 class="cw-h5">Open Text Service (Republication)</h1>
          <p>With this service, the FID Theology handles the checking, cataloguing and digitalization of essays which researchers would like to republish. This service is only offered to academics and researchers in Germany, Austria and Switzerland on the basis of German copyright law. Researchers could apply for a new phase of the Open Text Service in 2023.</p>
          <p>For more information on this service, see <a href="<?=$this->url('content-page', ['page' => 'OpenText']) ?>">Republication</a>.</p>

          <h1 class="cw-h5">DigiTheo</h1>
          <p>In several projects, important theological journals and monographs are being digitized and made available in open access.</p>
          <p>For more information on this project, see <a href="<?=$this->url('content-page', ['page' => 'TheologyDigital']) ?>">Digitization</a>.</p>

          <h1 class="cw-h5">Digitization on Demand</h1>
          <p>In cooperation with the Bayerische Staatsbibliothek in Munich, the FID Theologie offers a service in which individual works whose copyright has expired are digitized free of charge if they are needed for research.</p>
          <p>This service is offered under the following conditions:</p>
            <ul>
              <li>The work is in the public domain (for works published in Germany, this is normally the case 70 years after the death of the author).</li>
              <li>The work belongs to the collection of the Universitätsbibliothek Tübingen or the Bayerische Staatsbibliothek in Munich.</li>
              <li>The subject matter of the work falls within the academic disciplines covered by one of the specialized information services housed at the Universitätsbibliothek Tübingen or at the Bayerische Staatsbibliothek in Munich, or it is needed for research in one of these academic fields.</li>
              <li>One work or a few works are concerned (i.e. it is not possible to digitize a complete volume of a journal or a whole list of literature with this service).</li>
            </ul>
          <p>If you would like to use this service to have a book digitized, please contact: <a href="mailto:ixtheo@ub.uni-tuebingen.de">Contact</a>.</p>
      </div>
    </div>
  </div>
</div>