<section class="cw-py-5 col-md-12">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div class="cw-text-center">
                    <p class="cw-subtitle cw-text-primary"><?=$this->translate("section_aktuelles_title1")?></p>
                    <h2 class="cw-h2 cw-mb-5"><?=$this->translate("section_aktuelles_title2")?></h2>
                </div>

                <div class="slick-slider-multiple-item" align="center">
                    <a href="/Content/digi2026">
                        <div class="ix-slick-slider-item" title="Wissenschaftliche Tagung und Festakt IxTheo" style="background-image: url(<?=$this->imageLink('slider/mode/News_Tagung.jpg')?>);">
                            <div class="ix-slick-slider-item-title">Wissenschaftliche Tagung und Festakt IxTheo</div>
                        </div>
                    </a>
                    <a href="<?=$this->url('content-page', ['page' => 'News']) ?>#new_homepage">
                        <div class="ix-slick-slider-item" title="<?=$this->transEscAttr('symbolic_image_table63');?>" style="background-image: url(<?=$this->imageLink('slider/hands-2178566.jpg')?>);">
                            <div class="ix-slick-slider-item-title"><?=$this->translate("section_aktuelles_title17")?></div>
                        </div>
                    </a>
                    <a href="<?=$this->url('content-page', ['page' => 'News']) ?>#self-archiving">
                        <div class="ix-slick-slider-item" title="<?=$this->transEscAttr('symbolic_image_table8');?>." style="background-image: url(<?=$this->imageLink('slider/mode/pexels-anete-lusina.jpg')?>);">
                            <div class="ix-slick-slider-item-title"><?=$this->translate("section_aktuelles_title3")?></div>
                        </div>
                    </a>
                    <a href="<?=$this->url('content-page', ['page' => 'News']) ?>#aggregator">
                        <div class="ix-slick-slider-item" title="<?=$this->transEscAttr('symbolic_image_table9');?>." style="background-image: url(<?=$this->imageLink('slider/mode/pexels-george-milton.jpg')?>);">
                            <div class="ix-slick-slider-item-title"><?=$this->translate("section_aktuelles_title4")?></div>
                        </div>
                    </a>
                    <a href="<?=$this->url('content-page', ['page' => 'News']) ?>#personenseiten">
                        <div class="ix-slick-slider-item" title="<?=$this->transEscAttr('symbolic_image_table10');?>." style="background-image: url(<?=$this->imageLink('slider/mode/pexels-gabby.jpg')?>);">
                            <div class="ix-slick-slider-item-title"><?=$this->translate("section_aktuelles_title5")?></div>
                        </div>
                    </a>
                </div>
            </div>
            <div class="col-md-6">
                <div class="cw-text-center">
                    <p class="cw-subtitle cw-text-primary"><?=$this->translate("section_aktuelles_title6")?></p>
                    <h2 class="cw-h2 cw-mb-5"><?=$this->translate("section_aktuelles_title7")?></h2>
                    <div class="ix-news-right">
                        <div class="ix-news-container">
                            <div class="ix-news-panel ix-news-panel-1">
                                <a href="<?=$this->url('content-page', ['page' => 'OpenJournals'])?>">
                                    <div><b><?=$this->translate("section_aktuelles_title8")?></b></div>
                                    <div><small><?=$this->translate("section_aktuelles_title9")?></small></div>
                                </a>
                            </div>
                            <div class="ix-news-panel ix-news-panel-2">
                                <a href="<?=$this->url('content-page', ['page' => 'OpenText'])?>">
                                    <div><b><?=$this->translate("section_aktuelles_title10")?></b></div>
                                    <div><small><?=$this->translate("section_aktuelles_title11")?></small></div>
                                </a>
                            </div>
                            <div class="ix-news-panel ix-news-panel-3">
                                <a href="<?=$this->url('content-page', ['page' => 'FullTextSearch'])?>">
                                    <div><b><?=$this->translate("section_aktuelles_title12")?></b></div>
                                    <div><small><?=$this->translate("section_aktuelles_title13")?></small></div>
                                </a>
                            </div>
                            <div class="ix-news-panel ix-news-panel-4">
                                <a href="<?=$this->url('content-page', ['page' => 'LexiconSearch'])?>">
                                    <div><b><?=$this->translate("section_aktuelles_title14")?></b></div>
                                    <div><small><?=$this->translate("section_aktuelles_title15")?></small></div>
                                </a>
                            </div>
                            <div class="ix-clear-both">&nbsp;</div>
                            <div class="ix-news-container-footer"><a class="cw-text-white ix2-underline" href="<?=$this->url('content-page', ['page' => 'AllServices'])?>"><?=$this->translate("section_aktuelles_title16")?></a></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<style>
.slick-slider-multiple-item .ix-slick-slider-item {
  background-repeat: no-repeat;
  background-attachment: fixed;
  background-position: center;
}
</style>

<?php
$jsSnippet = <<< 'EOD'
$(document).ready(function(){
    let $slider = $('.slick-slider-multiple-item');

    $slider.slick({
        dots: true,
        autoplay: false,       // default stop autorotation
        infinite: true,
        speed: 1000,
        fade: true,
        cssEase: 'linear',
        arrows: true
    });

    // run slider rotation if mouse hover
    $slider.on('mouseenter', function () {
        $slider.slick('slickPlay');
    });

    // stop slider rotation
    $slider.on('mouseleave', function () {
        $slider.slick('slickPause');
    });
});
EOD;?>
<?=$this->assetManager()->outputInlineScriptString($jsSnippet)?>