<section class="cw-py-5">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div class="cw-text-center">
                    <p class="cw-subtitle cw-text-primary">Aktuelles</p>
                    <h2 class="cw-h2 cw-mb-5">IxTheo News</h2>
                </div>

                <div class="slick-slider-single-item" align="center">
                    <a href="<?=$this->url('content-page', ['page' => 'news']) ?>">
                        <div class="ix-slick-slider-item" style="background-image: url(<?=$this->imageLink('frontpage/authors.jpg')?>);">
                            <div class="ix-slick-slider-item-title">Aktuelles</div>
                        </div>
                    </a>
                    <div class="ix-slick-slider-item" style="background-image: url(<?=$this->imageLink('frontpage/discover.jpg')?>);">
                        <div class="ix-slick-slider-item-title">Blog-Aggregator</div>
                    </div>
                    <div class="ix-slick-slider-item" style="background-image: url(<?=$this->imageLink('frontpage/publishers.jpg')?>);">
                        <div class="ix-slick-slider-item-title">Workshop 2.-3.12.19</div>
                    </div>
                </div>

                <?php
                  $jsSnippet = <<< 'EOD'
                    $(document).ready(function(){
                        $('.slick-slider-single-item').slick({
                            dots: true,
                            infinite: true,
                            speed: 300,
                            fade: true,
                            cssEase: 'linear',
                            arrows: true
                        });
                    });
EOD;
              ?>
              <?=$this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, $jsSnippet, 'SET')?>
            </div>
            <div class="col-md-6">
                <div class="cw-text-center">
                    <p class="cw-subtitle cw-text-primary">Highlights</p>
                    <h2 class="cw-h2 cw-mb-5">IxTheo Services</h2>
                    <div class="ix-news-right">
                        <div class="ix-news-container">
                            <div class="ix-news-panel ix-news-panel-1">
                                <a href="<?=$this->url('content-page', ['page' => 'open_access_journals'])?>">
                                    <div><b>IxTheo Open Journals</b></div>
                                    <div><small>Open Access Zeitschriften Service</small></div>
                                </a>
                            </div>
                            <div class="ix-news-panel ix-news-panel-2">
                                <a href="<?=$this->url('content-page', ['page' => 'open_text'])?>">
                                    <div><b>IxTheo Open Text</b></div>
                                    <div><small>Zweitveröffentlichung von Aufsätzen</small></div>
                                </a>
                            </div>
                            <div class="ix-news-panel ix-news-panel-3">
                                <a href="<?=$this->url('content-page', ['page' => 'full_text_search'])?>">
                                    <div><b>Volltextsuche</b></div>
                                    <div><small>Theologica durchsuchen</small></div>
                                </a>
                            </div>
                            <div class="ix-news-panel ix-news-panel-4">
                                <a href="<?=$this->url('content-page', ['page' => 'lexicon_search'])?>">
                                    <div><b>Lexikonrecherche</b></div>
                                    <div><small>Theologische Lexika durchsuchen</small></div>
                                </a>
                            </div>
                            <div class="ix-clear-both">&nbsp;</div>
                            <div class="ix-news-container-footer">Alle Services</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>