<section class="cw-py-5 cw-bg-gray-100">
    <div class="container">
        <div class="text-center cw-pb-lg-4">
            <p class="cw-subtitle cw-text-primary">Finden | Suchen | Nutzen</p>
            <h2 class="cw-h2 cw-mb-5">IxTheo entdecken</h2>
        </div>
        <div class="row">
            <a href="<?=$this->url('content-page', ['page' => 'discover']) ?>">
                <div class="col-lg-3 cw-mb-3 cw-mb-lg-0 text-center">
                    <div class="cw-px-0 cw-px-lg-3">
                        <div class="cw-icon-rounded cw-bg-primary-light cw-mb-3">
                            <i class="fa fa-search"></i>
                        </div>
                        <h3 class="cw-h5">Suchen und Browsen</h3>
                        <div><small>Bibelstellen | CIC | Zeiträume | VerfasserInnen</small></div>
                    </div>
                </div>
            </a>
            <a href="<?=$this->url('content-page', ['page' => 'ixtheo_account']) ?>">
                <div class="col-lg-3 cw-mb-3 cw-mb-lg-0 text-center">
                    <div class="cw-px-0 cw-px-lg-3">
                        <div class="cw-icon-rounded cw-bg-primary-light cw-mb-3">
                            <i class="fa fa-user-plus"></i>
                        </div>
                        <h3 class="cw-h5">IxTheo Account</h3>
                        <div><small>Suchanfragen speichern | Favoriten speichern</small></div>
                    </div>
                </div>
            </a>
            <a href="<?=$this->url('content-page', ['page' => 'alerting']) ?>">
                <div class="col-lg-3 cw-mb-3 cw-mb-lg-0 text-center">
                    <div class="cw-px-0 cw-px-lg-3">
                        <div class="cw-icon-rounded cw-bg-primary-light cw-mb-3">
                            <i class="fa fa-bell"></i>
                        </div>
                        <h3 class="cw-h5">Alerting</h3>
                        <div><small>Neuerscheinungen | Blogs | Podcasts</small></div>
                    </div>
                </div>
            </a>
            <a href="<?=$this->url('content-page', ['page' => 'authority_pages']) ?>">
                <div class="col-lg-3 cw-mb-3 cw-mb-lg-0 text-center">
                    <div class="cw-px-0 cw-px-lg-3">
                        <div class="cw-icon-rounded cw-bg-primary-light cw-mb-3">
                            <i class="fa fa-address-card"></i>
                        </div>
                        <h3 class="cw-h5">Personenseiten</h3>
                        <div><small>Autor*innen | Institutionen</small></div>
                    </div>
                </div>
            </a>
        </div>
    </div>
</section>