<section class="cw-position-relative cw-dark-overlay ix2-networking-block">
    <img class="" src="<?=$this->imageLink('networking.png');?>" />
    <div class="net-main">
        <a href="<?=$this->url('content-page', ['page' => 'Networking']) ?>">
            <div class="row">
                <div class="col-lg-1 cw-mb-3 cw-mb-lg-0 text-center col-mob-none"></div>
                <div class="col-lg-10 cw-overlay-content cw-text-white cw-py-lg-5 ixtheo2-networking-block">
                    <h3 class="cw-display-3 cw-font-weight-bold cw-text-serif cw-text-shadow ixtheo2-networking-link">Networking</h3>
                </div>
                <div class="col-lg-1 cw-mb-3 cw-mb-lg-0 text-center col-mob-none"></div>
            </div>
        </a>
        <div class="row">
            <div class="col-lg-1 cw-mb-3 cw-mb-lg-0 text-center col-mob-none"></div>
            <div class="col-lg-10 cw-overlay-content cw-text-white sub-nav-networking">
                <span class="sub-title-networking"><a href="<?=$this->url('content-page', ['page' => 'Networking']) ?>">Theologische Community | Bibliothekarische Community | Weitere Kooperationen</a></span>
            </div>
            <div class="col-lg-1 cw-mb-3 cw-mb-lg-0 text-center col-mob-none"></div>
        </div>
    </div>
</section>
