<section class="cw-position-relative cw-dark-overlay ix-networking-block">
    <a href="<?=$this->url('content-page', ['page' => 'networking']) ?>">
        <img src="<?=$this->imageLink('searchbar.jpg')?>" alt="" class="cw-bg-image">
        <div class="row">
            <div class="col-lg-1 cw-mb-3 cw-mb-lg-0 text-center"></div>
            <div class="col-lg-10 cw-overlay-content cw-text-white cw-py-lg-5 ixtheo2-networking-block">
                <h3 class="cw-display-3 cw-font-weight-bold cw-text-serif cw-text-shadow ixtheo2-networking-link">Networking</h3>
            </div>
            <div class="col-lg-1 cw-mb-3 cw-mb-lg-0 text-center"></div>
        </div>
    </a>
    <div class="row">
        <div class="col-lg-1 cw-mb-3 cw-mb-lg-0 text-center"></div>
        <div class="col-lg-10 cw-overlay-content cw-text-white">
            <span class="sub-title-networking"><a href="<?=$this->url('content-page', ['page' => 'networking']) ?>">Theologische Community | Bibliothekarische Community | Weitere Kooperationen</a></span>
        </div>
        <div class="col-lg-1 cw-mb-3 cw-mb-lg-0 text-center"></div>
    </div>
    </section>

<style>
.ixtheo2-networking-block {
    padding-bottom: 0 !important;
}
.sub-title-networking {
    position: relative;
    padding-bottom: 20px;
}
</style>