<section class="cw-py-5">
    <div class="container">
        <div class="row cw-mb-5">
            <div class="col-md-12 text-center cw-mt-5">
                <p class="cw-subtitle cw-text-primary">Content</p>
                <h2 class="cw-h2"> IxTheo Ressourcen</h2>
            </div>
        </div>
        <div class="swiper cw-guides-slider mx-n2 cw-pt-3 swiper-container-horizontal">
            <!-- Additional required wrapper-->
            <div class="swiper-wrapper">
                <!-- Slides-->
                <div class="swiper-slide cw-h-auto cw-px-2">
                    <div class="cw-card cw-card-poster cw-gradient-overlay cw-hover-animate cw-mb-4 cw-mb-lg-0">
                        <a href="<?=$this->url('content-page', ['page' => 'BooksAndJournals']) ?>" class="cw-tile-link"></a>
                        <img src="<?=$this->imageLink('slider/mode/fid_content.jpg')?>" alt="Card image" class="cw-bg-image">
                        <div class="cw-card-body cw-overlay-content">
                            <h6 class="cw-card-title text-cw-shadow text-uppercase">Bücher & Journals</h6>
                        </div>
                    </div>
                </div>
                <div class="swiper-slide cw-h-auto cw-px-2">
                    <div class="cw-card cw-card-poster cw-gradient-overlay cw-hover-animate cw-mb-4 cw-mb-lg-0">
                        <a href="<?=$this->url('content-page', ['page' => 'Innovativ']) ?>" class="cw-tile-link"></a>
                        <img src="<?=$this->imageLink('slider/mode/digitale_quellen.jpg')?>" alt="Card image" class="cw-bg-image">
                        <div class="cw-card-body cw-overlay-content">
                            <h6 class="cw-card-title text-cw-shadow text-uppercase">IxTheo Innovativ</h6>
                        </div>
                    </div>
                </div>
                <div class="swiper-slide cw-h-auto cw-px-2">
                    <div class="cw-card cw-card-poster cw-gradient-overlay cw-hover-animate cw-mb-4 cw-mb-lg-0">
                        <a href="<?=$this->url('content-page', ['page' => 'TheologyDigital']) ?>" class="cw-tile-link"></a>
                        <img src="<?=$this->imageLink('slider/mode/theologie_digital.jpg')?>" alt="Card image" class="cw-bg-image">
                        <div class="cw-card-body cw-overlay-content">
                            <h6 class="cw-card-title text-cw-shadow text-uppercase">Digitalisierung</h6>
                        </div>
                    </div>
                </div>
                <div class="swiper-slide cw-h-auto cw-px-2">
                    <div class="cw-card cw-card-poster cw-gradient-overlay cw-hover-animate cw-mb-4 cw-mb-lg-0">
                        <a href="<?=$this->url('content-page', ['page' => 'Historical']) ?>" class="cw-tile-link"></a>
                        <img src="<?=$this->imageLink('slider/mode/historische_drucke.jpg')?>" alt="Card image" class="cw-bg-image">
                        <div class="cw-card-body cw-overlay-content">
                            <h6 class="cw-card-title text-cw-shadow text-uppercase">Historische Drucke</h6>
                        </div>
                    </div>
                </div>
                <div class="swiper-slide cw-h-auto cw-px-2">
                    <div class="cw-card cw-card-poster cw-gradient-overlay cw-hover-animate cw-mb-4 cw-mb-lg-0">
                        <a href="<?=$this->url('content-page', ['page' => 'Collections']) ?>" class="cw-tile-link"></a>
                        <img src="<?=$this->imageLink('slider/mode/buchstapel.jpg')?>" alt="Card image" class="cw-bg-image">
                        <div class="cw-card-body cw-overlay-content">
                            <h6 class="cw-card-title text-cw-shadow text-uppercase">Sammlungen</h6>
                        </div>
                    </div>
                </div>
            </div>
            <div class="cw-mt-1 swiper-pagination-parent">
                <div class="swiper-button-next"></div>
                <div class="swiper-button-prev"></div>
                <div class="swiper-pagination"></div>
            </div>    
        </div>
    </div>

<?php
  $jsSnippet = <<< 'EOD'
    var guidesSlider = new Swiper('.cw-guides-slider', {
        slidesPerView: 5,
        spaceBetween: 15,
        loop: true,
        roundLengths: true,
        breakpoints: {
            1200: {
                slidesPerView: 4
            },
            991: {
                slidesPerView: 3
            },
            768: {
                slidesPerView: 2
            },
            400: {
                slidesPerView: 1
            }
        },
        navigation: {
            nextEl: '.swiper-button-next',
            prevEl: '.swiper-button-prev',
        },
    });
EOD;
?>
<?=$this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, $jsSnippet, 'SET')?>
</section>
