<section class="cw-py-5">
    <div class="container">
        <div class="row cw-mb-5">
            <div class="col-md-12 text-center cw-mt-5">
                <span id="ixtheo-content"></span>
                <p class="cw-subtitle cw-text-primary"><?=$this->translate("section_resource_title1")?></p>
                <h2 class="cw-h2"><?=$this->translate("section_resource_title2")?></h2>
            </div>
        </div>
        <div class="swiper cw-guides-slider mx-n2 cw-pt-3 swiper-container-horizontal">
            <!-- Additional required wrapper-->
            <div class="swiper-wrapper">
                <!-- Slides-->
                <div class="swiper-slide cw-h-auto cw-px-2">
                    <div class="cw-card cw-card-poster cw-gradient-overlay cw-hover-animate cw-mb-4 cw-mb-lg-0">
                        <a href="<?=$this->url('content-page', ['page' => 'BooksAndJournals']) ?>" class="cw-tile-link"></a>
                        <img src="<?=$this->imageLink('slider/mode/fid_content.jpg')?>" alt="<?=$this->transEscAttr('symbolic_image_table11');?>" class="cw-bg-image">
                        <div class="cw-card-body cw-overlay-content">
                            <h6 class="cw-card-title text-cw-shadow text-uppercase"><?=$this->translate("section_resource_title3")?></h6>
                        </div>
                    </div>
                </div>
                <div class="swiper-slide cw-h-auto cw-px-2">
                    <div class="cw-card cw-card-poster cw-gradient-overlay cw-hover-animate cw-mb-4 cw-mb-lg-0">
                        <a href="<?=$this->url('content-page', ['page' => 'Innovativ']) ?>" class="cw-tile-link"></a>
                        <img src="<?=$this->imageLink('slider/mode/digitale_quellen.jpg')?>" alt="<?=$this->transEscAttr('symbolic_image_table12');?>" class="cw-bg-image">
                        <div class="cw-card-body cw-overlay-content">
                            <h6 class="cw-card-title text-cw-shadow text-uppercase"><?=$this->translate("section_resource_title4")?></h6>
                        </div>
                    </div>
                </div>
                <div class="swiper-slide cw-h-auto cw-px-2">
                    <div class="cw-card cw-card-poster cw-gradient-overlay cw-hover-animate cw-mb-4 cw-mb-lg-0">
                        <a href="<?=$this->url('content-page', ['page' => 'TheologyDigital']) ?>" class="cw-tile-link"></a>
                        <img src="<?=$this->imageLink('slider/mode/theologie_digital.jpg')?>" alt="<?=$this->transEscAttr('symbolic_image_table13');?>" class="cw-bg-image">
                        <div class="cw-card-body cw-overlay-content">
                            <h6 class="cw-card-title text-cw-shadow text-uppercase"><?=$this->translate("section_resource_title5")?></h6>
                        </div>
                    </div>
                </div>
                <div class="swiper-slide cw-h-auto cw-px-2">
                    <div class="cw-card cw-card-poster cw-gradient-overlay cw-hover-animate cw-mb-4 cw-mb-lg-0">
                        <a href="<?=$this->url('content-page', ['page' => 'Historical']) ?>" class="cw-tile-link"></a>
                        <img src="<?=$this->imageLink('slider/mode/historische_drucke.jpg')?>" alt="<?=$this->transEscAttr('symbolic_image_table14');?>" class="cw-bg-image">
                        <div class="cw-card-body cw-overlay-content">
                            <h6 class="cw-card-title text-cw-shadow text-uppercase"><?=$this->translate("section_resource_title6")?></h6>
                        </div>
                    </div>
                </div>
                <div class="swiper-slide cw-h-auto cw-px-2">
                    <div class="cw-card cw-card-poster cw-gradient-overlay cw-hover-animate cw-mb-4 cw-mb-lg-0">
                        <a href="<?=$this->url('content-page', ['page' => 'Collections']) ?>" class="cw-tile-link"></a>
                        <img src="<?=$this->imageLink('slider/mode/buchstapel.jpg')?>" alt="<?=$this->transEscAttr('symbolic_image_table15');?>" class="cw-bg-image">
                        <div class="cw-card-body cw-overlay-content">
                            <h6 class="cw-card-title text-cw-shadow text-uppercase"><?=$this->translate("section_resource_title7")?></h6>
                        </div>
                    </div>
                </div>
            </div>
            <div class="swiper-pagination"></div>   
        </div>
    </div>

<?php
  $jsSnippet = <<< 'EOD'
    var guidesSlider = new Swiper('.cw-guides-slider', {
        slidesPerView: 5,
        spaceBetween: 15,
        direction: "horizontal",
        loop: true,
        breakpoints: {
            1200: {
                slidesPerView: 4
            },
            991: {
                slidesPerView: 3
            },
            768: {
                slidesPerView: 2
            },
            400: {
                slidesPerView: 1
            }
        },
        pagination: {
            el: ".swiper-pagination",
            dynamicBullets: true,
            clickable: true,
        },
    });
EOD;
?>
<?=$this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, $jsSnippet, 'SET')?>
</section>
