<section class="cw-py-5 cw-bg-gray-100">
    <div class="container">
        <div class="text-center cw-pb-lg-4">
            <p class="cw-subtitle cw-text-primary"><?=$this->translate("section_special_title1")?></p>
            <h2 class="cw-h2 cw-mb-5"><?=$this->translate("section_special_title2")?></h2>
        </div>
        <div class="row">
            <div class="swiper cw-guides-slider-special mx-n2 cw-pt-3 swiper-container-horizontal">
                <!-- Additional required wrapper-->
                <div class="swiper-wrapper">
                    <!-- Slides-->
                    <div class="swiper-slide cw-h-auto cw-px-2">
                        <a target="_blank" href="https://relbib.de">
                            <div class="cw-mb-lg-0 text-center">
                                <div class="cw-px-0 cw-px-lg-3">
                                    <img src="<?=$this->imageLink('smallRelBibLogo.png')?>" alt="Card image" >
                                    <div><small><?=$this->translate("section_special_title3")?></small></div>
                                </div>
                            </div>
                        </a>
                    </div>
                    <div class="swiper-slide cw-h-auto cw-px-2">
                        <a target="_blank" href="https://bible.ixtheo.de/">
                            <div class="cw-mb-lg-0 text-center">
                                <div class="cw-px-0 cw-px-lg-3">
                                    <h1 class="cw-h1 ix-spez">Index <br /> Biblicus</h1>
                                    <div style="margin-top:-12px;"><small>BILDI / IxTheo / BiBIL</small></div>
                                </div>
                            </div>
                        </a>
                    </div>
                    <div class="swiper-slide cw-h-auto cw-px-2">
                        <a target="_blank" href="https://churchlaw.ixtheo.de/">
                            <div class="cw-mb-lg-0 text-center">
                                <div class="cw-px-0 cw-px-lg-3">
                                    <h1 class="cw-h1 ix-spez">Index <br /> Canonicus</h1>
                                    <div style="margin-top:-12px;"><small>IxTheo / KALDI / DaKaR</small></div>
                                </div>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="swiper-pagination"></div>
            </div>
        </div>
    </div>
</section>

<?php
  $jsSnippet = <<< 'EOD'
    var guidesSlider = new Swiper('.cw-guides-slider-special', {
        slidesPerView: 3,
        spaceBetween: 0,
        loop: true,
        roundLengths: true,
        breakpoints: {
            1200: {
                slidesPerView: 3
            },
            991: {
                slidesPerView: 3
            },
            768: {
                slidesPerView: 2
            },
            400: {
                slidesPerView: 1
            }
        },
        pagination: {
            el: ".swiper-pagination",
            dynamicBullets: true,
            clickable: true,
        }
    });
EOD;
?>
<?=$this->assetManager()->outputInlineScriptString($jsSnippet)?>