<section class="cw-py-5 cw-bg-gray-100">
    <div class="container">
        <div class="text-center cw-pb-lg-4">
            <p class="cw-subtitle cw-text-primary">Finden | Suchen | Nutzen</p>
            <h2 class="cw-h2 cw-mb-5">Spezialbibliografien</h2>
        </div>
        <div class="row">
            <a target="_blank" href="https://relbib.de">
                <div class="col-lg-4 cw-mb-3 cw-mb-lg-0 text-center">
                    <div class="cw-px-0 cw-px-lg-3">
                        <img src="<?=$this->imageLink('smallRelBibLogo.png')?>" alt="Card image" >
                        <div><small>Religionswissenschaftliche Bibliografie</small></div>
                    </div>
                </div>
            </a>
            <a target="_blank" href="https://bible.ixtheo.de/">
                <div class="col-lg-4 cw-mb-3 cw-mb-lg-0 text-center">
                    <div class="cw-px-0 cw-px-lg-3">
                        <h3 class="cw-h5">BILDI-IxTheo</h3>
                        <div style="margin-top:29px;"><small>Index Biblicus</small></div>
                    </div>
                </div>
            </a>
            <a target="_blank" href="https://churchlaw.ixtheo.de/">
                <div class="col-lg-4 cw-mb-3 cw-mb-lg-0 text-center">
                    <div class="cw-px-0 cw-px-lg-3">
                        <h3 class="cw-h5">IxTheo / KALDI / DaKaR</h3>
                        <div style="margin-top:29px;"><small>Index Canonicus</small></div>
                    </div>
                </div>
            </a>
        </div>
    </div>
</section>