<?php

$script = <<<JS
    $(function() {

      hideDefaultMultifield();

      function hideDefaultMultifield() {

        let addButton = "<i class='fa fa-plus-circle addjsicon' aria-hidden='true'></i>";
        let removeButton = "<i class='fa fa-minus-circle removejsicon' aria-hidden='true'></i>";
        $('.multifieldtext').each(function(){
          $(this).find('input').after(addButton);
          $(this).find('input').after(removeButton);
        })
        $('.multifieldtext').hide();
        $('.multifieldtext:first').show();
        $('.addjsicon:first').addClass('mainaddjsicon');
        $('.removejsicon:first').hide();
      }

      $('.addjsicon').click(function(){
        $(this).parents('.multifieldtext').next().show();
      })

      $('.removejsicon').click(function(){
        $(this).parents('.multifieldtext').hide();
      })

      function linkOnlineversion() {
        $('.group-onlineversion_werk_group_fulltext').toggle();
        $('.group-onlineversion_werk_group_openaccess').toggle();
      }

      function zeitschriftSelected() {
        $('.group-sammelband_werk_group_ISBN').hide();
        $('.group-sammelband_werk_group_Herausgeber').hide();

        $('.group-zeitschrift_werk_group_ISSN').show();
        $('.group-zeitschrift_werk_group_band').show();
        $('.group-zeitschrift_werk_group_heft').show();
        $('.group-zeitschrift_werk_group_jahr').show();
        $('.group-zeitschrift_werk_group_aufsatz_ID').show();
      }

      function sammelbandSelected() {
        $('.group-zeitschrift_werk_group_ISSN').hide();
        $('.group-zeitschrift_werk_group_band').hide();
        $('.group-zeitschrift_werk_group_heft').hide();
        $('.group-zeitschrift_werk_group_jahr').hide();
        $('.group-zeitschrift_werk_group_aufsatz_ID').hide();

        $('.group-zeitschrift_werk_group_erscheinungsjahr').show();
        $('.group-sammelband_werk_group_ISBN').show();
        $('.group-sammelband_werk_group_Herausgeber').show();
      }
      
      zeitschriftSelected();

      $(document).on("change", "#form_SelfArchivingAufsatz_inwerkradio_o2", function() {
        $(this).parents('.inwerkgroup').find('i').show();
        sammelbandSelected();
      })

      $(document).on("change", "#form_SelfArchivingAufsatz_inwerkradio_o1", function() {
        $(this).parents('.inwerkgroup').find('i').hide();

        zeitschriftSelected();
      })

      $('#form_SelfArchivingAufsatz_onlineversion_o1,#form_SelfArchivingAufsatz_onlineversion_o2').change(function(){
        linkOnlineversion();
      })

    });

  JS;

print $this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, $script, 'SET');
?>
<style>
  .fa-plus-circle {
    color:#089DE3; 
  }
  .fa-minus-circle {
    color:red; 
  }

  .addjsicon.mainaddjsicon {
    top: -26px;
    right: -22px;
  }

  .addjsicon {
    font-size: 18px;
    float: right;
    cursor: pointer;
    position: relative;
    top: -18px;
    right: -35px;
  }

  .removejsicon {
    font-size: 18px;
    float: right;
    cursor: pointer;
    position: relative;
    top: -36px;
    right: -20px;
  }

  .werkgroup, .inwerkgroup {
    background-color: #f5f5f5;
    padding: 10px;
    border-radius: 5px;
  }
</style>
