<?php

$script = <<<JS
    $(document).ready(function() {
      // Show/Hide print_online-specific fields
      $('input[type=radio][name=print_online]').change(function() {
        if (this.value == 'o1') {
          $('.group-superior_article_id').show();
        } else {
          $('.group-superior_article_id').hide();
        }
      });

      // Show/Hide superior_work_type-specific fields
      $('input[type=radio][name=superior_work_type]').change(function() {
        if (this.value == 'o1') {
          $('.group-superior_issn').show();
          $('.group-superior_isbn').hide();
          $('.group-superior_volume').show();
          $('.group-superior_year').show();
          $('.group-superior_issue').show();
          if ($('input[name="print_online"]:checked').val() == 'o1') {
            $('.group-superior_article_id').show();
          } else {
            $('.group-superior_article_id').hide();
          }
          $('.group-superior_publishers').hide();
        } else {
          $('.group-superior_issn').hide();
          $('.group-superior_isbn').show();
          $('.group-superior_volume').hide();
          $('.group-superior_year').hide();
          $('.group-superior_issue').hide();
          $('.group-superior_article_id').hide();
          $('.group-superior_publishers').show();
        }
      });
      $('#form_SelfArchivingAddMetadata_superior_work_type_o1').trigger('click');

      // Show/Hide online_exists-specific fields
      $('input[type=radio][name=online_exists]').change(function() {
        // Show options depending on which field is selected
        if (this.value == 'o1') {
          $('.group-online_url').show();
          $('.group-online_license').show();
        } else {
          $('.group-online_url').hide();
          $('.group-online_license').hide();
        }
      });
      $('#form_SelfArchivingAddMetadata_online_exists_o1').trigger('click');
    });

  JS;

print $this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, $script, 'SET');
