<?php
$tuefind = $this->tuefind();
$publicationEmail = $tuefind->getPublicationEmail();
?>

<p>Im Moment ist es leider nicht möglich, den Self-Archiving Service zu nutzen, wenn Sie nicht als Hauptverfasser*in im Eintrag der Publikation aufgeführt sind.</p> 
<p>Wenn die Rechte an der Publikation bei Ihnen liegen und Sie sie gerne zweitveröffentlichen möchten, wenden Sie sich an uns: <b><?=$publicationEmail;?></b>.</p>
