<p>The FID for the Study of Religion promotes free access to publications relevant to the study of religion that are either in public domain or for which the publisher has granted the corresponding rights of use. </p>
<p>We offer the DoD service to all RelBib users with an academic interest in the study of religion. Provided that the legal requirements are met and that it is possible from a preservative and technical point of view, individual titles (e.g. monographs, journal volumes, yearbooks and edited volumes) from the holdings of Tübingen University Library will be digitised at the expense of the FID. The full texts are then made publicly available via RelBib. For more extensive requests (e.g. the digitisation of an entire series), please <a href='mailto:relbib@ub.uni-tuebingen.de'>contact us</a> individually.</p>
<p><a href='<?=$this->url('search-results') . '?lookfor=' . urlencode('rs:dods')?>&type=AllFields'>Digitised titles in RelBib</a></p>
<p>As the author of a publication, you can also suggest this title for the DoD service if the publisher has granted you the corresponding rights of use. We will then get in touch with you regarding the further procedure.</p>
<p>We will be pleased to support you with any questions you may have, e.g. regarding copyright issues.</p>
<p>This is how it works:</p>
<ol>
    <li>Before you send us a digitisation request, we kindly ask you to look up the <a href='https://kvk.bibliothek.kit.edu/?digitalOnly=1&embedFulltitle=0&newTab=0' target='_blank'>Karlsruhe Virtual Catalogue</a> whether the desired title is already freely accessible via the Internet.</li>
    <li>Ideally, you also check whether the title is in public domain on the basis of the author's life dates.
        <ul style="list-style-type: none;">
            <li>
                <i>In Germany and most other European countries, a publication is considered to be in public domain if more than 70 years have passed since the death of the author (§ 64 UrhG). If there is more than one author, the 70-year term applies from when the last of these authors has passed away.</i>
            </li>
        </ul>
    </li>
    <li>Everything done? Then please complete the form below (mandatory fields are asterisked):</li>
</ol>
