<p>Der FID Religionswissenschaft fördert den freien Zugang zu religionswissenschaftlich relevanten Publikationen, die entweder gemeinfrei sind oder für die entsprechende Nutzungsrechte von Verlagsseite eingeräumt wurden.</p>
<p>Mit dem DoD-Service bieten wir allen RelBib-Nutzer*innen mit einem (religions-)wissenschaftlichen Interesse die Möglichkeit, gewünschte Titel aus dem Bestand der UB Tübingen auf Kosten des FID digitalisieren zu lassen. Die Volltexte werden anschließend über RelBib frei zur Verfügung gestellt.</p>
<p>Im Rahmen des Angebots können einzelne Titel digitalisiert werden, u.a. Monografien, Zeitschriftenbände, Jahrbücher und Sammelwerke, sofern die rechtlichen Bedingungen geklärt sind. Bei umfangreicheren Anfragen (z. B. Digitalisierung ganzer Reihen) nehmen Sie bitte gesondert <a href='mailto:relbib@ub.uni-tuebingen.de'>Kontakt</a> mit uns auf.</p>
<p>Und so geht es:</p>
<ol>
    <li>Bevor Sie einen Digitalisierungsauftrag an uns richten, bitten wir Sie darum, anhand des <a href='https://kvk.bibliothek.kit.edu/?kataloge=K10PLUS&kataloge=BVB&kataloge=NRW&kataloge=HEBIS&kataloge=KOBV_SOLR&kataloge=DDB&kataloge=STABI_BERLIN&kataloge=TIB&kataloge=VD16&kataloge=VD17&kataloge=VD18&kataloge=BIBOPAC&kataloge=LBOE&kataloge=OENB&kataloge=ABES&kataloge=BASE&kataloge=DART_EUROPE&kataloge=DIGIBIB&kataloge=DFG_EBOOKS&kataloge=DFG_AUFSAETZE&kataloge=DOABOOKS&kataloge=DOAJ&kataloge=EROMM_WEBSEARCH&kataloge=EUROPEANA&kataloge=GOOGLE_BOOKS&kataloge=KUNST_HATHI&kataloge=ARCHIVE_ORG&kataloge=OAPEN&kataloge=ZVDD&kataloge=BHL&digitalOnly=1&embedFulltitle=0&newTab=0'>Karlsruher Virtuellen Katalogs</a> zu prüfen, ob der gewünschte Titel bereits frei im Internet zugänglich ist.</li>
    <li>Idealerweise können Sie anhand der Lebensdaten bereits feststellen, ob es sich um einen gemeinfreien Titel handelt: 
        <ul>
            <li>
                <i>Ein Werk gilt in Deutschland und in den meisten anderen europäischen Ländern als gemeinfrei, wenn der bzw. die Urheber*in mehr als 70 Jahre verstorben ist (§ 64 UrhG). Bei mehreren Autor*innen gilt die 70-Jahre-Frist ab dem Tod der zuletzt verstorbenen Person. Wenn Sie als Autor*in eines Werkes vom Verlag die Nutzungsrechte haben, können Sie uns auch diesen Titel für den DoD-Service vorschlagen. Bei Fragen z. B. zur Rechteklärung stehen wir Ihnen gerne beratend zur Seite.</i>
            </li>
        </ul>
    </li>
    <li>Alles passt? Dann füllen Sie bitte das nachstehende Formular aus (Pflichtfelder sind markiert):</li>
</ol>
