<div class="row">
  <div class="col-xs-12 col-sm-4 col-4 cw-text-center">
    <h5><?=$this->translate("Service of")?></h5>
    <a target="_blank" href="//www.uni-tuebingen.de">
      <img src="<?=$this->imageLink('Logo_Universitaet_Tuebingen.svg') ?>" alt="Universität T&uuml;bingen" width="260"/>
    </a>
    <br/>
    <br/>
    <a target="_blank" href="//ub.uni-tuebingen.de">
      <img src="<?=$this->imageLink('Logo_Universitaetsbibliothek_Tuebingen.svg') ?>" alt="UB" />
    </a>
    <br/>
    <br/>
    <a target="_blank" href="//uni-tuebingen.de/fakultaeten/katholisch-theologische-fakultaet/fakultaet/">
      <img src="<?=$this->imageLink('k-theologische-fak.svg') ?>" alt="Katholisch-Theologische Fakult&auml;t" width="320"/>
    </a>
    <br/>
    <br/>
    <a target="_blank" href="//uni-tuebingen.de/fakultaeten/evangelisch-theologische-fakultaet/fakultaet/">
      <img src="<?=$this->imageLink('e-theologische-fak.svg') ?>" alt="Evangelisch-Theologische Fakult&auml;t" width="320"/>
    </a>
  </div>

  <div class="col-xs-12 col-sm-4 col-4 cw-text-center">
    <h5><?=$this->translate("In collaboration with")?></h5>
    <div class="col-auto">
      <a target="_blank" href="https://www.augustinus.de">
        <img src="<?=$this->imageLink('partners/uni-wuerzburg-logo.svg') ?>" width="170" alt="Universität Würzburg">
        <br />
        <span>
            Zentrum für Augustinus-Forschung<br>
            an der Julius-Maximilians-Universität Würzburg
        </span>
      </a>
      <br />
    </div>
    <hr class="hr-support" />
    <div class="col-auto">
      <a target="_blank" href="https://www.augustiniana.be">
        <img src="<?=$this->imageLink('partners/Augustijns_Historisch_Instituut.png') ?>" width="300" alt="Augustijns Historisch Instituut (AHI), Leuven">
        <br />
        <span>Augustijns Historisch Instituut (AHI), Leuven</span>
      </a>
    </div>
  </div>

  <div class="col-xs-12 col-sm-4 col-4 cw-text-center">
    <h5><?=$this->translate("Funded by")?></h5>
    <a target="_blank" href="//dfg.de">
      <img src="<?=$this->imageLink('dfg_logo_schriftzug.svg') ?>" alt="DFG" width="250" height="31" />
    </a>
  </div>
</div>
<br />