<?php
  $title = $this->translate('Icons');
  $titleEsc = $this->escapeHtml($title);
  $this->headTitle($title);
  $this->breadcrumbs()->set('Development Tools', $this->url('devtools-home'))
    ->add($title, active: true);
  $icons = [];
  $lastIcon = '';
  foreach ($aliases as $icon) {
    if ($icon === "$lastIcon-rtl") {
      if (!$this->layout()->rtl) {
        array_pop($icons);
        $icons[] = $this->icon($lastIcon) . ' (ltr) ' . $this->escapeHtml($lastIcon)
          . ' (rtl) ' . $this->icon($icon) . '<br>';
      }
    } else {
      $icons[] = $this->icon($icon) . ' ' . $this->escapeHtml($icon) . '<br>';
    }
    $lastIcon = $icon;
  }
?>
<h1 class="mb-5" style="border-bottom: 1px solid black;">You can use any icon from <a href="https://fontawesome.com/v6/search?ic=free-collection" target="_blank">Font Awesome 6</a></h1>
<div class="devtools-icon-container"><?=implode('', $icons)?></div>
