<?php $account = $this->auth()->getManager(); ?>
<div class="banner search container navbar">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#header-collapse" aria-label="<?=$this->transEscAttr('mobile_toggle_navigation_text')?>">
      <?=$this->icon('ui-menu') ?>
    </button>
    <a class="navbar-brand lang-<?=$this->layout()->userLang ?>" href="<?=$this->url('home')?>"><?=$this->translate($this->tuefind()->getConfig('config')->Site->title)?></a>
  </div>
  <?php if (!isset($this->layout()->renderingError)): ?>
    <div class="collapse navbar-collapse" id="header-collapse">
      <nav id="ix-nav-header">
        <ul class="nav navbar-nav navbar-right flip">
          <li class="active"><a href="<?=$this->url('home')?>"><?=$this->transEsc('Home');?></a></li>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"><?=$this->transEsc('About');?> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="/Content/Impressum"><?=$this->transEsc('Impressum');?></a></li>
              <li><a target="_blank" href="<?=$this->url('content-page', ['page' => 'privacy'])?>"><?=$this->transEsc('Privacy Protection');?></a></li>
            </ul>
          </li>
          <li><a href="/Content/A-Z">IxTheo A-Z</a></li>
          <?php if ($this->feedback()->tabEnabled()): ?>
            <li>
              <a class="icon-link" id="feedbackLink" data-lightbox href="<?=$this->url('feedback-home') ?>">
                <?=$this->icon('feedback', 'icon-link__icon') ?>
                <span class="icon-link__label"><?=$this->transEsc('Feedback')?></span>
              </a>
            </li>
          <?php endif; ?>
          <?php $cart = $this->cart(); ?>
          <?php if ($cart->isActive()): ?>
            <li id="cartSummary" aria-live="polite" aria-atomic="true">
              <a id="cartItems" class="icon-link" data-lightbox title="<?=$this->transEscAttr('View Book Bag')?>" href="<?=$this->url('cart-home')?>">
                  <?=$this->icon('cart', 'icon-link__icon') ?>
                  <span class="icon-link__label">
                  <span class="sr-only"><?=$this->transEsc('Book Bag')?>:</span>
                  <span role="status"><strong><?=count($cart->getItems())?></strong> <?=$this->transEsc('items')?></span>
                    <span class="full<?=!$cart->isFull() ? ' hidden' : '' ?>">(<?=$this->transEsc('bookbag_full') ?>)</span>
                  </span>
              </a>
            </li>
          <?php endif; ?>
          <?php if (is_object($account) && $account->loginEnabled()): // hide login/logout if unavailable ?>
            <?php if ($account->isLoggedIn()): ?>
              <li class="logoutOptions<?php if ($account->dropdownEnabled()): ?> with-dropdown<?php endif ?>">
                <a href="<?=$this->url('myresearch-home', [], ['query' => ['redirect' => 0]])?>" class="icon-link">
                  <span id="account-icon" class="icon-link__icon"><?=$this->icon('my-account') ?></span>
                  <span class="icon-link__label"><?=$this->transEsc('Your Account')?></span>
                </a>
            </li>
              <?php if ($account->dropdownEnabled()): ?>
                <li id="login-dropdown" class="dropdown<?php if(!$account->isLoggedIn()): ?> hidden<?php endif ?>">
                <a href="#" data-toggle="dropdown"><?=$this->icon('dropdown-caret') ?></a>
                <div class="dropdown-menu">
                  <?=$this->render('myresearch/menu'); ?>
                </div>
              </li>
            <?php endif; ?>
              <li class="logoutOptions<?php if(!$account->isLoggedIn()): ?> hidden<?php endif ?>">
              <a href="<?=$this->url('myresearch-logout')?>" class="logout icon-link">
                    <?=$this->icon('sign-out', 'icon-link__icon') ?>
                    <span class="icon-link__label"><?=$this->transEsc('Log Out')?></span>
              </a>
            </li>
            <?php else: ?>
              <li id="loginOptions">
              <?php if ($account->getSessionInitiator($this->serverUrl($this->url('myresearch-home')))): ?>
                  <a href="<?=$this->url('myresearch-userlogin')?>" class="icon-link">
                    <?=$this->icon('sign-in', 'icon-link__icon') ?>
                    <span class="icon-link__label"><?=$this->transEsc('Institutional Login')?></span>
                  </a>
              <?php else: ?>
                  <a href="<?=$this->url('myresearch-userlogin')?>" class="icon-link" data-lightbox>
                    <?=$this->icon('sign-in', 'icon-link__icon') ?>
                    <span class="icon-link__label"><?=$this->transEsc('Login')?></span>
                  </a>
              <?php endif; ?>
            </li>
          <?php endif; ?>
          <?php endif; ?>

          <?php if (isset($this->layout()->themeOptions) && count($this->layout()->themeOptions) > 1): ?>
              <?=$this->component('menu-button', [
                  'toggleLabel' => 'Theme',
                  'wrapperTag' => 'li',
                  'menuItems' => array_map(
                      function ($item) {
                          $item['label'] = $item['desc'];
                          $item['url'] = $this->url()->addQueryParameters(['ui' => $item['name']]);

                          return $item;
                      },
                      $this->layout()->themeOptions
                  ),
              ]) ?>
          <?php endif; ?>

          <?php if (isset($this->layout()->allLangs) && count($this->layout()->allLangs) > 1): ?>
              <?=$this->component('menu-button', [
                  'toggleLabel' => 'Language',
                  'wrapperClass' => 'language',
                  'wrapperTag' => 'li',
                  'menuItems' => array_map(
                      function ($langCode, $langName) {
                          return [
                            'label' => $this->displayLanguageOption($langName),
                            'url' => $this->url()->addQueryParameters(['lng' => $langCode]),
                            'selected' => $this->layout()->userLang == $langCode,
                          ];
                      },
                      array_keys($this->layout()->allLangs),
                      array_values($this->layout()->allLangs),
                  ),
              ]) ?>
          <?php endif; ?>
        </ul>
      </nav>
    </div>
  <?php endif; ?>
  <section class="section-home">
    <div class="panel-home">
      <br />
      <br />
      <div class="visible-lg">
        <h1>
          <a href="<?=$this->url('home')?>" title="Index Theologicus">Index Theologicus</a>
        </h1>
        <small><?=$this->transEsc("ixtheo_subtitle")?></small>
        <br />
      </div>
      <?php if ($this->ils()->getOfflineMode() == "ils-offline"): ?>
        <div class="alert alert-warning">
          <h2><?= $this->transEsc('ils_offline_title') ?></h2>

          <p><strong><?= $this->transEsc('ils_offline_status') ?></strong></p>

          <p><?= $this->transEsc('ils_offline_home_message') ?></p>
          <?php $supportEmail = $this->escapeHtmlAttr($this->systemEmail()); ?>
          <p><a href="mailto:<?= $supportEmail ?>"><?= $supportEmail ?></a></p>
        </div>
      <?php endif; ?>
      <?php if ($this->layout()->searchbox !== false): ?>
        <nav class="nav searchbox hidden-print">
          <?=$this->layout()->searchbox ?>
        </nav>
      <?php endif; ?>
    </div>
  </section>
</div>
