<?php if ($this->recommend->getResults()->getResultTotal() > 0): ?>
  <?php $similarAuthors = $this->recommend->getSimilarAuthors(); ?>
  <?php if (!empty($similarAuthors['list'])): ?>
    <p class="author-label"><?=$this->transEsc('Author Results for')?> <strong><?=$this->escapeHtml($this->recommend->getSearchTerm()) ?></strong></p>
    <div class="author-facets">
      <div class="author-list">
      <?php foreach ($similarAuthors['list'] as $i => $author): ?>
        <?php if ($i == 5): ?>
            <a href="<?=$this->url('author-search') . '?lookfor=' . urlencode($this->recommend->getSearchTerm()) ?>"><strong><?=$this->transEsc('see all') ?> <?=(isset($similarAuthors['count']) && $similarAuthors['count']) ? $similarAuthors['count'] : ''?> &raquo;</strong></a>
          </div>
          <div class="author-list">
        <?php endif; ?>
        <?php
          // TueFind: Split author id + heading
          $authorToDisplay = $author['value'];
          if (str_contains($authorToDisplay, ':')) {
            $authorDetails = explode(':', $author['value']);
            $authorLabel = $authorDetails[0];
            $authorId = $authorDetails[1];
            if (!empty($authorId)) {
                $authorUrl = $this->url('solrauthrecord', ['id' => $authorId]);
            } else {
                $authorUrl = $this->url('author-home') . '?author=' . urlencode($authorToDisplay);
            }
          }
        ?>
        <a href="<?=$authorUrl?>"><?=$this->escapeHtml($authorLabel)?><?php /* count disabled -- uncomment to add: echo ' - ' . $author['count']; */ ?></a>
        <?php if ($i + 1 < count($similarAuthors['list'])): ?>
          <br>
        <?php endif; ?>
      <?php endforeach; ?>
      </div>
    </div>
    <br>
  <?php endif; ?>
<?php endif; ?>
