<?php $rssItems = $this->tuefind()->getRssNewsEntries($this->rssMaxItems, /* $only_newest_item_per_feed = */true);?>
<?php if (count($rssItems) == 0):?>
    <?=$this->translate('rss_news_missing')?>
<?php else:?>
    <?php $redirectGroup = $this->tuefind()->getTueFindInstance() . '-rss-short'; ?>
    <ul id="tf-rss-short">
        <?php foreach ($rssItems as $rssItem):?>
            <?php $rssFeed = $rssItem->getRssFeed(); ?>
            <li>
                <a class="tf-rss-short-link-icon" target="_blank" href="<?=$this->tuefind()->getRedirectUrl($rssFeed->getWebsiteUrl(), $redirectGroup)?>" title="<?=$this->escapeHtmlAttr($rssFeed->getFeedName())?>" rel="nofollow"><img src="<?=$this->tuefind()->getRssFeedIcon($rssFeed->getFeedName())?>" height="16" title="<?=$this->escapeHtmlAttr($rssFeed->getFeedName())?>"/></a>
                <a class="tf-rss-short-link-title" target="_blank" href="<?=$this->tuefind()->getRedirectUrl($rssItem->getItemUrl(), $redirectGroup)?>" title="<?=str_replace('"', '&quot;', strip_tags($rssItem->getItemDescription() ?? $rssItem->getItemTitle()))?>" rel="nofollow"><?=$this->escapeHtml($rssItem->getItemTitle())?></a>
            </li>
        <?php endforeach;?>
    </ul>
<?php endif;?>
