<?php $rssItems = $this->tuefind()->getRssNewsEntries($this->rssMaxItems, /* $only_newest_item_per_feed = */true);?>
<?php if (count($rssItems) == 0):?>
    <?=$this->translate('rss_news_missing')?>
<?php else:?>
    <?php $redirectGroup = $this->tuefind()->getTueFindInstance() . '-rss-short'; ?>
    <ul id="tf-rss-short">
        <?php foreach ($rssItems as $rssItem):?>
            <li>
                <a class="tf-rss-short-link-icon" target="_blank" href="<?=$this->tuefind()->getRedirectUrl($rssItem['rssFeed']['websiteUrl'], $redirectGroup)?>" title="<?=$rssItem['rssFeed']['feedName']?>" rel="nofollow"><img src="<?=$this->tuefind()->getRssFeedIcon($rssItem['rssFeed']['feedName'])?>" height="16" title="<?=$rssItem['rssFeed']['feedName']?>"/></a>
                <a class="tf-rss-short-link-title" target="_blank" href="<?=$this->tuefind()->getRedirectUrl($rssItem['itemUrl'], $redirectGroup)?>" title="<?=str_replace('"', '&quot;', strip_tags($rssItem['itemDescription'] ?? $rssItem['itemTitle']))?>" rel="nofollow"><?=$rssItem['itemTitle']?></a>
            </li>
        <?php endforeach;?>
    </ul>
<?php endif;?>