<?php $routeParams = $this->tuefind()->getRouteParams(); $advancedSearch = ""; $homePage = false;
  if($routeParams['controller'] == "Search" && $routeParams['action'] == "Advanced") {
    $advancedSearch = "advancedSearch";
  }
  if($routeParams['controller'] == "index" && $routeParams['action'] == "Home") {
    $homePage = true;
  }
?>

<!--
  Start Preloader
  ==================================== -->
  <div id="preloader">
    <div class='preloader'>
      <span></span>
      <span></span>
      <span></span>
      <span></span>
      <span></span>
      <span></span>
    </div>
  </div>
  <!--
  End Preloader
  ==================================== -->

<!--
Fixed Navigation
==================================== -->
<header class="navigation fixed-top">
  <div class="container">
    <!-- main nav -->

    <nav class="navbar container-fluid navbar-expand-lg navbar-light px-0">
      <!-- logo -->
      <a class="navbar-brand logo" href="/">
        <?php /* ?><img loading="lazy" class="logo-default" src="<?=$this->imageLink('logo.png');?>" alt="logo" />
        <img loading="lazy" class="logo-white" src="<?=$this->imageLink('logo.png');?>" alt="logo" /> <?php */?>
        IxTheo
      </a>
      <!-- /logo -->

      <ul class="navbar-nav navbar-right text-center">

        <!-- s-media -->
        <li class="nav-item social-media tf-cursor-pointer">
            <span class="dropdown-toggle nav-link" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fa fa-share-alt" aria-hidden="true"></i> <span class="cw-hide-for-xsmoll"><?=$this->transEsc("Social media")?></span><b class="caret"></b></span>
            <ul class="dropdown-menu">
              <li class="sub-menu"><a target="blank" href="//bsky.app/profile/ixtheo.bsky.social"><img src="<?=$this->imageLink('bluesky.svg')?>" height="16" alt="Bluesky"> Bluesky</a></li>
              <li class="sub-menu"><a target="blank" href="//hcommons.social/@ixtheo"><img src="<?=$this->imageLink('mastodon.svg')?>" height="16" alt="Mastodon"> Mastodon</a></li>
            </ul>
        </li>

        <?=$this->render('header/login');?>
      
        <?php if (isset($this->layout()->themeOptions) && count($this->layout()->themeOptions) > 1): ?>
          <li class="theme dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?=$this->transEsc("Theme")?> <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <?php foreach ($this->layout()->themeOptions as $current): ?>
                <li<?=$current['selected'] ? ' class="active"' : ''?>>
                  <a href="<?=$this->escapeHtmlAttr($this->url()->addQueryParameters(['ui' => $current['name']])) ?>" rel="nofollow">
                    <?=$this->transEsc($current['desc']) ?>
                  </a>
                </li>
              <?php endforeach; ?>
            </ul>
          </li>
        <?php endif; ?>

        <?php if (isset($this->layout()->allLangs) && count($this->layout()->allLangs) > 1): ?>
          <li class="nav-item language tf-cursor-pointer">
            <span class="dropdown-toggle nav-link" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class='fa fa-globe' ></i> <span class="cw-hide-for-xsmoll"><?=$this->transEsc("Language")?></span><b class="caret"></b></span>
            <ul class="dropdown-menu">
              <?php
                //TueFind: Basic VuFind functionality changed, removed author ID from URL
                foreach ($this->layout()->allLangs as $langCode => $langName): ?>
                  <li<?=$this->layout()->userLang == $langCode ? ' class="active"' : ''?>>
                    <?php $langURL = $this->escapeHtmlAttr($this->url()->addQueryParameters(['lng' => $langCode]));
                        if($routeParams['controller'] == "Authority" && $routeParams['action'] == "Home") {
                            $langURL = $this->escapeHtmlAttr($this->url()->addQueryParametersToAuthority(['lng' => $langCode]));
                        }
                    ?>
                    <a href="<?=$langURL?>" rel="nofollow">
                      <?=$this->displayLanguageOption($langName) ?>
                    </a>
                  </li>
              <?php endforeach; ?>
            </ul>
          </li>
        <?php endif; ?>

        <?=$this->render('header/menu');?>

        <!-- End section Main Menu -->
      </ul>
    </nav>
    
    <!-- /main nav -->
  </div>
</header>
<!--
End Fixed Navigation
==================================== -->

 <!--
Welcome Slider
==================================== -->
<div class="logo-wrapper">
  <?php if($homePage):?>
  <img class="searchbar_horizontal" src="<?=$this->imageLink('searchbar_origin.jpg');?>" />
  <img class="searchbar_vertical" src="<?=$this->imageLink('searchbar_vertical.jpg');?>" />
  <div class="text-content">
    <h1><a href="<?=$this->url('home')?>" title="Index Theologicus">Index Theologicus</a></h1>
    <small><?=$this->transEsc("ixtheo_subtitle")?></small>
  </div>
  <?php else: ?>
  <div class="contentLogoBlock">
    <h1><a href="<?=$this->url('home')?>" title="Index Theologicus">Index Theologicus</a></h1>
    <small><?=$this->transEsc("ixtheo_subtitle")?></small>
  </div>
  <?php endif;?>
</div>

<?php if($homePage):?>
  <span class="ix-copyright logo-tooltip" title="test" >© <span class="ix-copyright-name"><img src="<?=$this->imageLink('Seezeichen.jpg');?>" width="600" />Seezeichen, © Marco Varenkamp</span></span>
<?php endif;?>

<?php if (isset($this->layout()->srmessage)): // message for benefit of screen-reader users ?>
  <span class="sr-only" role="heading" aria-level="1"><?=$this->layout()->srmessage ?></span>
<?php endif; ?>
<a class="sr-only sr-only-focusable" href="#content"><?=$this->transEsc('Skip to content') ?></a>

<!-- IxTheo2: Display searchbox as separate section -->
<?php $routeParams = $this->tuefind()->getRouteParams();
if(isset($routeParams['page']) && $routeParams['page'] == 'digi2026'): ?>
  <!-- On the 50th Ixtheo page we don't display a search form. -->
<?php else: ?>
  <!-- Breadcrumbs -->
  <?php if(!empty($this->layout()->breadcrumbs)): ?>
    <div class="container breadcrumb-wrapper hidden-print <?=$advancedSearch;?>">
      <?php if(is_array($this->layout()->breadcrumbs)): ?>
        <?php if(count($this->layout()->breadcrumbs) > 1): ?>
          <?=$this->render('breadcrumbs/multi.phtml', [
            'parents' => $this->layout()->breadcrumbs,
            'title' => $this->layout()->title,
            'from' => $this->layout()->from
          ]) ?>
        <?php else: ?>
          <?=$this->render('breadcrumbs/default.phtml', [
            'parents' => $this->layout()->breadcrumbs,
            'title' => $this->layout()->title
          ]) ?>
        <?php endif; ?>
      <?php elseif ($this->layout()->breadcrumbs !== false): ?>
        <?=$this->render('breadcrumbs/simple.phtml'); ?>
      <?php endif; ?>
    </div>
  <?php endif; ?>
  <?=$this->layout()->searchbox; ?>
<?php endif; ?>
