<?php $routeParams = $this->tuefind()->getRouteParams(); $advancedSearch = "";
  if($routeParams['controller'] == "Search" && $routeParams['action'] == "Advanced") {
    $advancedSearch = "advancedSearch";
  }
?>

<!--
  Start Preloader
  ==================================== -->
  <div id="preloader">
    <div class='preloader'>
      <span></span>
      <span></span>
      <span></span>
      <span></span>
      <span></span>
      <span></span>
    </div>
  </div>
  <!--
  End Preloader
  ==================================== -->

<!--
Fixed Navigation
==================================== -->
<header class="navigation fixed-top">
  <div class="container">
    <!-- main nav -->

    <nav class="navbar container-fluid navbar-expand-lg navbar-light px-0">
      <!-- logo -->
      <a class="navbar-brand logo" href="/">
        <?php /* ?><img loading="lazy" class="logo-default" src="<?=$this->imageLink('logo.png');?>" alt="logo" />
        <img loading="lazy" class="logo-white" src="<?=$this->imageLink('logo.png');?>" alt="logo" /> <?php */?>
        IxTheo
      </a>
      <!-- /logo -->

      <ul class="navbar-nav navbar-right text-center">

        <?=$this->render('header/login');?>
      
        <?php if (isset($this->layout()->themeOptions) && count($this->layout()->themeOptions) > 1): ?>
          <li class="theme dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?=$this->transEsc("Theme")?> <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <?php foreach ($this->layout()->themeOptions as $current): ?>
                <li<?=$current['selected'] ? ' class="active"' : ''?>>
                  <a href="<?=$this->escapeHtmlAttr($this->url()->addQueryParameters(['ui' => $current['name']])) ?>" rel="nofollow">
                    <?=$this->transEsc($current['desc']) ?>
                  </a>
                </li>
              <?php endforeach; ?>
            </ul>
          </li>
        <?php endif; ?>

        <?php if (isset($this->layout()->allLangs) && count($this->layout()->allLangs) > 1): ?>
          <li class="language nav-item dropdown active">
            <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown"><i class='fa fa-globe' ></i> <?=$this->transEsc("Language")?><b class="caret"></b></a>
            <ul class="dropdown-menu">
              <?php
                //TueFind: Basic VuFind functionality changed, removed author ID from URL
                $routeParams = $this->tuefind()->getRouteParams();
                foreach ($this->layout()->allLangs as $langCode => $langName): ?>
                  <li<?=$this->layout()->userLang == $langCode ? ' class="active"' : ''?>>
                    <?php $langURL = $this->escapeHtmlAttr($this->url()->addQueryParameters(['lng' => $langCode]));
                        if($routeParams['controller'] == "Authority" && $routeParams['action'] == "Home") {
                            $langURL = $this->escapeHtmlAttr($this->url()->addQueryParametersToAuthority(['lng' => $langCode]));
                        }
                    ?>
                    <a href="<?=$langURL?>" rel="nofollow">
                      <?=$this->displayLanguageOption($langName) ?>
                    </a>
                  </li>
              <?php endforeach; ?>
            </ul>
          </li>
        <?php endif; ?>

        <?=$this->render('header/menu');?>

        <!-- End section Main Menu -->
      </ul>
    </nav>
    
    <!-- /main nav -->
  </div>
</header>
<!--
End Fixed Navigation
==================================== -->

 <!--
Welcome Slider
==================================== -->
<div class="logo-wrapper">
  <img class="searchbar_horizontal" src="<?=$this->imageLink('searchbar_origin.jpg');?>" />
  <img class="searchbar_vertical" src="<?=$this->imageLink('searchbar_vertical.jpg');?>" />
  <div class="text-content">
    <h1><a href="<?=$this->url('home')?>" title="Index Theologicus">Index Theologicus</a></h1>
    <small><?=$this->transEsc("ixtheo_subtitle")?></small>
  </div>
</div>

<style>
.logo-wrapper {
  position: relative;
}

.logo-wrapper img {
  width: 100%;
  height: auto;
}

.logo-wrapper .text-content {
    min-height: 200px;
    padding-top: 3.0vw;
}

.text-content {
  position: absolute;
  top:0;
  left:0;
  right:0;
  bottom: 0;
  padding:3vw;
}

.logo-wrapper .text-content h1 a {
    color: #3586b2;
    text-shadow: none;
    font-family: 'Open Sans', Arial, Helvetica, sans-serif !important;
    font-weight: 400;
    font-size:2.5vw;
}

.logo-wrapper .text-content h1 {
    margin-bottom: 0px;
    text-align: center;
}

.logo-wrapper .text-content small {
    display: block;
    text-align: center;
    margin: 5px 0 auto;
    padding-bottom: 12px;
    color: #495057;
    text-shadow: none;
    font-size: 0.8vw;
}
.searchbar_vertical {
  display: none;
}


/* Extra small devices (portrait phones, less than 576px) */

@media (max-width: 575.98px) {
  ul.navbar-nav.navbar-right li{
    float: left;
    margin-right: 10px;
  }
  .navbar-nav {
    margin: 0;
    padding: 0;
    margin-right: -10px;
    float: right;
  }
  .navigation .navbar-light .navbar-nav .nav-item .nav-link{
    padding:0;
  }
  .navbar-brand.logo {
    display: none;
  }
}

/* Small devices (landscape phones, 576px and up) */

@media (min-width: 576px) and (max-width: 767.98px) {
  ul.navbar-nav.navbar-right li{
    float: left;
    margin-right: 10px;
  }
  .navbar-nav {
    padding: 0;
    margin: 0;
    margin-right: -10px;
    float: right;
  }
  .navigation .navbar-light .navbar-nav .nav-item .nav-link{
    padding:0;
  }
}

/* Medium devices (tablets, 768px and up) */
/*
@media (min-width: 768px) and (max-width: 991.98px) {
  .hero-area {
    background-image: url(../themes/ixtheo2/images/slider/searchbar_520.png);
  }
}

/* Large devices (desktops, 992px and up) */
/*
@media (min-width: 992px) and (max-width: 1199.98px) {
  .hero-area {
    background-image: url(../themes/ixtheo2/images/slider/searchbar_980.png);
  }
}
*/
/* Extra large devices (large desktops, 1200px and up) */
/*
@media (min-width: 1200px) and (max-width: 1919.98px) {
  .hero-area {
    background-image: url(../themes/ixtheo2/images/slider/searchbar_1200.png);
  }
}
*/
@media (max-width: 1300px) {
  .searchbar_vertical {
    display: initial;
  }
  .searchbar_horizontal {
    display: none;
  }
  .logo-wrapper .text-content h1 a{
    font-size:3.5vw;
  }
  .logo-wrapper .text-content small {
    font-size: 1.8vw;
  }
  .logo-wrapper .text-content {
    padding-top: 16.5vw;
  }
}
</style>


<span class="ix-copyright logo-tooltip" title="test" >© <span class="ix-copyright-name"><img src="<?=$this->imageLink('Seezeichen.jpg');?>" width="600" />Seezeichen, © Marco Varenkamp</span></span>
<!-- Breadcrumbs -->
<?php if(!empty($this->layout()->breadcrumbs)): ?>
  <div class="container breadcrumb-wrapper hidden-print <?=$advancedSearch;?>">
    <?php if(is_array($this->layout()->breadcrumbs)): ?>
      <?php if(count($this->layout()->breadcrumbs) > 1): ?>
        <?=$this->render('breadcrumbs/multi.phtml', [
          'parents' => $this->layout()->breadcrumbs,
          'title' => $this->layout()->title,
          'from' => $this->layout()->from
        ]) ?>
      <?php else: ?>
        <?=$this->render('breadcrumbs/default.phtml', [
          'parents' => $this->layout()->breadcrumbs,
          'title' => $this->layout()->title
        ]) ?>
      <?php endif; ?>
    <?php elseif ($this->layout()->breadcrumbs !== false): ?>
      <?=$this->render('breadcrumbs/simple.phtml'); ?>
    <?php endif; ?>
  </div>
<?php endif; ?>


<!-- IxTheo2: Display searchbox as separate section -->
<?=$this->layout()->searchbox ?>

<style>
  .ix-copyright {
    float: left;
    margin-top: -33px;
    margin-left: 13px;
    color: #495057;
    cursor: pointer;
    font-size: 20px;
  }
  .ix-copyright-name {
    display: none;
    color: #495057;
  }

  .ui-tooltip, .arrow:after {
    color: #495057;
    border: 2px solid white;
    background-color: white;
  }
  .ui-tooltip {
    padding: 10px 10px;
    border-radius: 20px;
    font: bold 14px "Helvetica Neue", Sans-Serif;
    box-shadow: 0 0 7px black;
  }
  .arrow {
    width: 70px;
    height: 16px;
    overflow: hidden;
    position: absolute;
    left: 50%;
    margin-left: -35px;
    bottom: -14px;
  }
  .arrow.left {
    left: 25px;
  }
  .arrow:after {
    content: "";
    position: absolute;
    left: 20px;
    top: -20px;
    width: 25px;
    height: 25px;
    box-shadow: 6px 5px 9px -9px black;
    transform: rotate(45deg);
  }
</style>
