<?php

function OnlyOrdered($signatures)
{
  foreach ($signatures as $signature) {
    if (preg_match('"^(UB|IFK): bestellt"i', $signature)) {
      return true;
    }
  }
  return false;
}

$signatures = $this->driver->getLocalSignatures();

if (!OnlyOrdered($signatures)) {
  echo $this->transEsc('Available in Tubingen') . '.<br>';
}
foreach ($signatures as $signature) {
  echo $this->escapeHtml($signature) . '<br>';
}
