<nav class="record-nav">
  <ul class="action-toolbar" aria-label="<?=$this->transEscAttr('ajaxview_label_tools'); ?>">
    <?php if (count($this->driver->getCitationFormats()) > 0): ?>
      <li role="none">
        <a class="cite-record toolbar-btn btn-type-cite" data-lightbox href="<?=$this->recordLinker()->getActionUrl($this->driver, 'Cite')?>" rel="nofollow">
          <span class="icon icon--font fa fa-asterisk" role="img" aria-hidden="true"></span>
          <?=$this->transEsc('Cite this')?>
        </a>
      </li>
    <?php endif; ?>

    <?php if ($this->accountCapabilities()->getSmsSetting() !== 'disabled'): ?>
      <li role="none">
        <a class="sms-record toolbar-btn btn-type-phone" data-lightbox href="<?=$this->recordLinker()->getActionUrl($this->driver, 'SMS')?>" rel="nofollow">
          <span class="icon icon--font fa fa-phone" role="img" aria-hidden="true"></span>
          <?=$this->transEsc('Text this')?>
        </a>
      </li>
    <?php endif; ?>

    <!-- KrimDok: Disabled on purpose
    <li><a class="mail-record toolbar-btn btn-type-email" data-lightbox href="<?=$this->recordLinker()->getActionUrl($this->driver, 'Email')?>" rel="nofollow"><?=$this->transEsc('Email this')?></a></li>
    -->

    <li>
      <a class="print-record toolbar-btn btn-type-print" href="<?=$this->url()->addQueryParameters(['print' => true])?>" rel="nofollow">
        <span class="icon icon--font fa fa-print" role="img" aria-hidden="true"></span>
        <?=$this->transEsc('Print')?>
      </a>
    </li>

    <?php $exportFormats = $this->export()->getFormatsForRecord($this->driver); ?>
    <?php if(count($exportFormats) > 0): ?>
      <li role="none" class="dropdown">
        <a class="export-toggle toolbar-btn btn-type-export dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" href="<?=$this->recordLinker()->getActionUrl($this->driver, 'Export')?>" rel="nofollow" aria-expanded="false" aria-controls="export-options">
          <span class="icon icon--font fa fa-external-link" role="img" aria-hidden="true"></span>
          <?=$this->transEsc('Export Record') ?>
        </a>
        <ul class="dropdown-menu" id="export-options" role="menu">
          <?php foreach ($exportFormats as $exportFormat): ?>
            <li role="none"><a <?php if ($this->export()->needsRedirect($exportFormat)): ?>target="<?=$this->escapeHtmlAttr($exportFormat)?>Main" <?php endif; ?>href="<?=$this->escapeHtmlAttr($this->recordLinker()->getActionUrl($this->driver, 'Export', [], '', ['excludeSearchId' => true]))?>?style=<?=$this->escapeHtmlAttr($exportFormat)?>" rel="nofollow" role="menuitem"><?=$this->transEsc('Export to')?> <?=$this->transEsc($this->export()->getLabelForFormat($exportFormat))?></a></li>
          <?php endforeach; ?>
        </ul>
      </li>
    <?php endif; ?>

    <?php if ($this->userlist()->getMode() !== 'disabled'): ?>
      <li role="none">
        <?php if ($this->permission()->allowDisplay('feature.Favorites')): ?>
          <a class="save-record toolbar-btn btn-type-save" data-lightbox href="<?=$this->recordLinker()->getActionUrl($this->driver, 'Save')?>" rel="nofollow">
            <span class="icon icon--font fa fa-star" role="img" aria-hidden="true"></span>
            <?=$this->transEsc('Add to favorites')?>
          </a>
        <?php elseif ($block = $this->permission()->getAlternateContent('feature.Favorites')): ?>
          <?=$block?>
        <?php endif; ?>
      </li>
    <?php endif; ?>
    <?php if (!empty($addThis)): ?>
      <li role="none"><a class="addThis addthis_button" href="https://www.addthis.com/bookmark.php?v=250&amp;pub=<?=urlencode($addThis)?>"><i class="fa fa-bookmark" aria-hidden="true"></i> <?=$this->transEsc('Bookmark')?></a></li>
    <?php endif; ?>
    <?=$this->render('record/cart-buttons.phtml', ['id' => $this->driver->getUniqueId(), 'source' => $this->driver->getSourceIdentifier()]); ?>

    <!-- TueFind: Publish button -->
    <?=$this->render('RecordDriver/DefaultRecord/toolbar-publish.phtml'); ?>
  </ul>
</nav>

<!-- TueFind: Social Media buttons -->
<!-- KrimDok: Disabled on purpose -->
<?php //print $this->render('share/buttons.phtml', ['text' => $this->driver->getShortTitle()]); ?>
