<nav class="record-nav" aria-label="<?=$this->transEscAttr('ajaxview_label_tools'); ?>">
  <ul class="action-toolbar">
    <?php if (count($this->driver->getCitationFormats()) > 0): ?>
      <li role="none">
        <a class="cite-record toolbar-btn" data-lightbox href="<?=$this->escapeHtmlAttr($this->recordLinker()->getActionUrl($this->driver, 'Cite'))?>" rel="nofollow">
          <span><?=$this->icon('cite') ?></span>
          <span><?=$this->transEsc('Cite this')?></span>
        </a>
      </li>
    <?php endif; ?>

    <?php if ($this->accountCapabilities()->getSmsSetting() !== 'disabled'): ?>
      <li role="none">
        <a class="sms-record toolbar-btn" data-lightbox href="<?=$this->escapeHtmlAttr($this->recordLinker()->getActionUrl($this->driver, 'SMS'))?>" rel="nofollow">
          <span><?=$this->icon('send-sms') ?></span>
          <span><?=$this->transEsc('Text this')?></span>
        </a>
      </li>
    <?php endif; ?>

    <?php if ($this->accountCapabilities()->isEmailActionAvailable()): ?>
    <li role="none">
        <a class="mail-record toolbar-btn" data-lightbox href="<?=$this->escapeHtmlAttr($this->recordLinker()->getActionUrl($this->driver, 'Email'))?>" rel="nofollow">
          <span><?=$this->icon('send-email') ?></span>
          <span><?=$this->transEsc('Email this')?></span>
      </a>
    </li>
    <?php endif; ?>

    <li>
      <a class="print-record toolbar-btn" href="<?=$this->url()->addQueryParameters(['print' => true])?>" rel="nofollow">
        <span><?=$this->icon('print') ?></span>
        <span><?=$this->transEsc('Print')?></span>
      </a>
    </li>

    <?php $exportFormats = $this->export()->getFormatsForRecord($this->driver); ?>
    <?php if (count($exportFormats) > 0): ?>
      <li role="none" class="dropdown">
        <a class="export-toggle toolbar-btn btn-type-export dropdown-toggle" data-bs-toggle="dropdown" aria-haspopup="true" href="<?=$this->recordLinker()->getActionUrl($this->driver, 'Export')?>" rel="nofollow" aria-expanded="false" aria-controls="export-options">
          <span><?=$this->icon('export') ?></span>
          <span><?=$this->transEsc('Export Record') ?></span>
        </a>
        <ul class="dropdown-menu" id="export-options" role="menu">
          <?php foreach ($exportFormats as $exportFormat): ?>
            <li role="none">
              <a class="dropdown-item" <?php if ($this->export()->needsRedirect($exportFormat)): ?>target="<?=$this->escapeHtmlAttr($exportFormat)?>Main" <?php endif; ?>href="<?=$this->escapeHtmlAttr($this->recordLinker()->getActionUrl($this->driver, 'Export', [], '', ['excludeSearchId' => true]))?>?style=<?=$this->escapeHtmlAttr($exportFormat)?>" rel="nofollow" role="menuitem">
                <?=$this->transEsc('export_to', ['%%target%%' => $this->translate($this->export()->getLabelForFormat($exportFormat))])?>
              </a>
            </li>
          <?php endforeach; ?>
        </ul>
      </li>
    <?php endif; ?>

    <?php if ($this->userlist()->getMode() !== 'disabled'): ?>
      <li role="none">
        <?php if ($this->permission()->allowDisplay('feature.Favorites')): ?>
          <a class="save-record toolbar-btn btn-type-save" data-lightbox href="<?=$this->escapeHtmlAttr($this->recordLinker()->getActionUrl($this->driver, 'Save'))?>" rel="nofollow">
            <span><?=$this->icon('user-favorites') ?></span>
            <span><?=$this->transEsc('Add to favorites')?></span>
          </a>
        <?php elseif ($block = $this->permission()->getAlternateContent('feature.Favorites')): ?>
          <?=$block ?>
        <?php endif; ?>
      </li>
    <?php endif; ?>
    <?php if (!empty($addThis)): ?>
      <li role="none">
          <a class="addThis addthis_button" href="https://www.addthis.com/bookmark.php?v=250&amp;pub=<?=urlencode($addThis)?>">
          <?=$this->icon('addthis-bookmark') ?>
          <?=$this->transEsc('Bookmark')?>
        </a>
      </li>
    <?php endif; ?>

        <?php if ($this->cart()->isActive()): ?>
      <li>
        <?=$this->render('record/cart-buttons.phtml', ['id' => $this->driver->getUniqueId(), 'source' => $this->driver->getSourceIdentifier()]); ?>
      </li>
    <?php endif; ?>

    <?php if ($this->config()->get('config')->Record->permanent_link ?? true): ?>
      <li role="none">
        <a class="permalink-record toolbar-btn" data-lightbox href="<?=$this->escapeHtmlAttr($this->recordLinker()->getActionUrl($this->driver, 'Permalink'))?>" rel="nofollow">
          <?=$this->icon('external-link') ?>
          <?=$this->transEsc('permanent_link')?>
        </a>
      </li>
    <?php endif ?>

    <!-- IxTheo: Subscribe button -->
    <?php if ($this->accountCapabilities()->getSubscriptionSetting() === 'enabled'):?>
      <?php if ($this->IxTheo()->isRecordSubscribed($this->driver) || $this->IxTheo()->isRecordSubscribedViaBundle($this->driver)): ?>
        <li>
          <a class="subscribe-record toolbar-btn" data-lightbox href="<?=$this->recordLinker()->getActionUrl($this->driver, 'Subscribe')?>" rel="nofollow">
            <span class="icon icon--font fa fa-bell" role="img" aria-hidden="true"></span>
            <?=$this->transEsc('Unsubscribe')?>
          </a>
        </li>
      <?php elseif ($this->driver->isSubscribable()): ?>
        <li>
          <a class="subscribe-record toolbar-btn" data-lightbox href="<?=$this->recordLinker()->getActionUrl($this->driver, 'Subscribe')?>" rel="nofollow">
            <span class="icon icon--font fa fa-bell" role="img" aria-hidden="true"></span>
            <?=$this->transEsc('Subscribe')?>
          </a>
        </li>
      <?php endif; ?>
    <?php endif; ?>

    <!-- TueFind: Publish button -->
    <?=$this->render('RecordDriver/DefaultRecord/toolbar-publish.phtml'); ?>
  </ul>
</nav>

<!-- TueFind: Social Media buttons -->
<?=$this->render('share/buttons.phtml', ['text' => $this->driver->getShortTitle()])?>
