<div class="panel panel-top panel-default tf-panel-home-4">
    <a class="panel-default-link" href="<?=$this->url('content-page', ['page' => 'albert_krebs_bibliothek']) ?>">
        <div class="panel-image" style="background-image: url(<?=$this->imageLink('newfrontpage/albert_krebs_bibliothek.jpg') ?>);"></div>
        <div class="panel-content">
            <h4>Albert-Krebs Bibliothek</h4>
        </div>
    </a>
    <div class="col-lg-12 mini-search-block">
        <div class="input-group">
            <form class="krebs_form" action="<?=$this->url("search-results", [], [])?>" method="get">
                <div class="input-group">
                    <input type="text" class="form-control lookfor" name="lookfor" value="" placeholder="Hier suchen...">
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="submit"><i class="fa fa-search"></i></button>
                    </span>
                </div>
            </form>
        </div>
    </div>
</div>

<style>
.mini-search-block {
    margin-top: 100px;
}
.mini-search-block .form-control {
    border-radius: 4px;
}
</style>

<?php
$script = <<<JS
    $('.krebs_form').submit(function(){
        let lookfor = $('.lookfor');
        lookfor.val("rs:kreb "+lookfor.val());
    });
JS;
?>
<?=$this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, $script, 'SET');
