<div class="panel panel-top panel-default col-md-6">
    <a class="panel-default-link" href="<?=$this->url('content-page', ['page' => 'ausland', 'container' => 'false']) ?>">
        <div class="panel-image" style="background-image: url(<?=$this->imageLink('newfrontpage2026/Image5.jpg') ?>);"></div>
    </a>
    <div class="panel-content">
        <a class="panel-default-link" href="<?=$this->url('content-page', ['page' => 'ausland', 'container' => 'false']) ?>">
            <h4>Programas de máster en criminología fuera de Alemania</h4>
            <p></p>
        </a>
    </div>
</div>
