<div class="panel panel-bottom panel-default tf-panel-home-4">
    <a class="panel-default-link" href="<?=$this->url('content-page', ['page' => 'catalogs']) ?>">
        <div class="panel-image" style="background-image: url(<?=$this->imageLink('frontpage/publishers.jpg') ?>);"></div>
        <div class="panel-content">
            <h4>Catalogues & Databases</h4>
        </div>
    </a>
    <div class="col-lg-12 mini-search-block">
        <div class="input-group">
        </div>  
    </div> 
</div>
