<div class="panel panel-top panel-default tf-panel-home-4">
    <a class="panel-default-link" href="<?=$this->url('content-page', ['page' => 'catalogs']) ?>">
        <div class="panel-image" style="background-image: url(<?=$this->imageLink('frontpage/publishers.jpg') ?>);"></div>
        <div class="panel-content">
            <h4>Kataloge & Datenbanken</h4>
        </div>
    </a>
    <div class="col-lg-12 mini-search-block">
        <div class="input-group">
            <form action="<?=$this->url("search-results", [], [])?>" method="get">
                <input type="hidden" name="filter" value="format:Database">
                <div class="input-group">
                    <input type="text" class="form-control" name="lookfor" value="" placeholder="Search for...">
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="submit"><i class="fa fa-search"></i></button>
                    </span>
                </div> 
            </form>   
        </div>  
    </div>
</div>

<style>
.mini-search-block {
    margin-top: 100px;
}    
.mini-search-block .form-control {
    border-radius: 4px;
}
</style>
