<div class="panel panel-top panel-default col-md-6">
    <a class="panel-default-link" href="<?=$this->url('content-page', ['page' => 'europa']) ?>">
        <div class="panel-image" style="background-image: url(<?=$this->imageLink('newfrontpage2026/Image12.jpg') ?>);"></div>
    </a>
    <div class="panel-content">
        <a class="panel-default-link" href="<?=$this->url('content-page', ['page' => 'europa']) ?>">
            <h4>Europa</h4>
            <p></p>
        </a>
    </div>
</div>
