<div class="panel panel-top panel-default col-md-6">
    <a class="panel-default-link" href="<?=$this->url('content-page', ['page' => 'spezialsuche', 'container' => 'false']) ?>">
        <div class="panel-image" style="background-image: url(<?=$this->imageLink('newfrontpage/fid_krim_s.jpg') ?>);"></div>
        <div class="panel-content">
            <h4>Specific Search</h4>
        </div>
    </a>
</div>
