<div class="panel panel-top panel-default col-6 col-xs-6 col-sm-6 col-md-4">
    <a class="panel-default-link" href="<?=$this->url('content-page', ['page' => 'fid_services', 'container' => 'false']) ?>">
        <div class="panel-image" style="background-image: url(<?=$this->imageLink('fid_krim.jpg') ?>);"></div>
        <div class="panel-content">
            <h4>Estudios y Docencia</h4>
        </div>
    </a>
</div>
