<div class="panel panel-bottom panel-default tf-panel-home-3">
    <a class="panel-default-link" href="<?=$this->url('content-page', ['page' => 'forschungsdatenmanagement'])?>">
        <div class="panel-image" style="background-image: url(<?=$this->imageLink('frontpage/research_data.jpg') ?>);"></div>
        <div class="panel-content">
            <h4>Forschungsdatenmanagement</h4>
        </div>
    </a>
</div>
