<div class="panel panel-bottom panel-default col-6 col-xs-6 col-sm-6 col-md-4">
    <a class="panel-default-link" href="<?=$this->url('content-page', ['page' => 'forschungsdatenmanagement'])?>">
        <div class="panel-image" style="background-image: url(<?=$this->imageLink('frontpage/research_data.jpg') ?>);"></div>
        <div class="panel-content">
            <h4>Research Data Management</h4>
        </div>
    </a>
</div>
