<div class="panel panel-bottom panel-default tf-panel-home-3">
    <a class="panel-default-link" href="<?=$this->url('content-page', ['page' => 'kooperierende_FIDs'])?>">
        <div class="panel-image" style="background-image: url(<?=$this->imageLink('newfrontpage/kooperierende_FIDs.jpg') ?>);"></div>
        <div class="panel-content">
            <h4>Kooperierende FIDs</h4>
        </div>
    </a>
</div>
