<div class="panel panel-top panel-default tf-panel-home-2">
    <a class="panel-default-link" href="<?=$this->url('content-page', ['page' => 'krimdok']) ?>">
        <!--<div class="panel-image" style="background-image: url(<?//=$this->imageLink('frontpage/krim_dok.jpg') ?>);"></div>-->
        <div class="panel-image" style="background-image: url(<?=$this->imageLink('newfrontpage/krim_dok.jpg') ?>);"></div>
        <div class="panel-content">
            <h4>Über KrimDok</h4>
        </div>
    </a>
</div>
