<div class="panel panel-top panel-default tf-panel-home-3">
    <a class="panel-default-link" href="<?=$this->url('content-page', ['page' => 'krimdok_and_fid', 'container' => 'false']) ?>">
        <div class="panel-image" style="background-image: url(<?=$this->imageLink('background_fid.jpg') ?>);"></div>
        <div class="panel-content">
            <h4>KrimDok</h4>
        </div>
    </a>
    <div class="tf-result-link-block">
        <a class="yt-boards" target="_blank" href="https://www.youtube.com/watch?v=FL3yDlcvO0s&list=PLs76r5p4LoGzWTyvj06MI2VLysyXuVUYn"><img src="<?=$this->imageLink('youtubeBoard.png') ?>" class="tf-youtubeBoard"/><br />Video-Tutorials</a>
        <a target="_blank" href="https://krimdok.jimdofree.com/" class="btn btn-default btn-panel-more btn-panel-more-new" role="button" ><?=$this->transEsc('KrimBlog')?></a><br />
    </div>
</div>

<style>
    .tf-result-link-block .yt-boards {
        float: left;
        margin-left: 10px;
    }
    .tf-result-link-block .yt-boards img {
        height: 110px;
    }
    .tf-result-link-block .btn-panel-more-new {
        margin-top: 95px;
        margin-right: 20px;
    }
</style>
