<div class="panel panel-top panel-default col-md-6">
    <a class="panel-default-link" href="<?=$this->url('content-page', ['page' => 'master', 'container' => 'false']) ?>">
        <div class="panel-image" style="background-image: url(<?=$this->imageLink('newfrontpage2026/Image4.jpg') ?>);"></div>
    </a>
    <div class="panel-content">
        <a class="panel-default-link" href="<?=$this->url('content-page', ['page' => 'master', 'container' => 'false']) ?>">
            <h4>Programas de máster en criminología en Alemania</h4>
            <p></p>
        </a>
    </div>
</div>
