<div class="panel panel-bottom panel-default tf-panel-home-3">
    <a class="panel-default-link" href="<?=$this->url('content-page', ['page' => 'monografien']) ?>">
        <div class="panel-image" style="background-image: url(<?=$this->imageLink('newfrontpage/monografien.jpg') ?>);"></div>
    </a>
    <div class="panel-content">
        <a class="panel-default-link" href="<?=$this->url('content-page', ['page' => 'monografien']) ?>">
            <h4>Monographs</h4>
            <p></p>
        </a>
    </div>
</div>
