<div class="panel panel-top panel-inverse tf-panel-home-3">
    <div class="panel-image" style="background-image: url(<?=$this->imageLink('newfrontpage/news.jpg') ?>);"></div>
    <div class="panel-content">
        <h4>Anuncios y fechas</h4>
        <p>
        <ul>
            <li><a class="panel-inverse-link" href="<?=$this->url('content-page', ['page' => 'call_for_papers']) ?>">Convocatoria de ponencias</a></li>
            <li><a class="panel-inverse-link" href="<?=$this->url('content-page', ['page' => 'events']) ?>">Reuniones y conferencias</a></li>
        </ul>
        </p>
    </div>
</div>
