<div class="panel panel-bottom panel-default tf-panel-home-3">
    <a class="panel-default-link" href="<?=$this->url('content-page', ['page' => 'partners','container' => 'false'])?>">
        <div class="panel-image" style="background-image: url(<?=$this->imageLink('newfrontpage/unsere_partner.jpg') ?>);"></div>
        <div class="panel-content">
            <h4>Unsere Partner</h4>
        </div>
    </a>
</div>
