<div class="panel panel-top panel-default col-md-4">
    <a class="panel-default-link" href="<?=$this->url('content-page', ['page' => 'upload_tool']) ?>">
        <div class="panel-image" style="background-image: url(<?=$this->imageLink('newfrontpage2026/Image1.jpg') ?>);"></div>
        <div class="panel-content">
            <h4>Herramienta de subida para el autoarchivo</h4>
        </div>
    </a>
</div>
