<div class="panel panel-bottom panel-default tf-panel-home-4">
    <a class="panel-default-link" href="<?=$this->url('content-page', ['page' => 'weitere_kataloge']) ?>">
        <div class="panel-image" style="background-image: url(<?=$this->imageLink('frontpage/publishers.jpg') ?>);"></div>
    </a>
    <div class="panel-content">
        <a class="panel-default-link" href="<?=$this->url('content-page', ['page' => 'weitere_kataloge']) ?>">
            <h4>Weitere Kataloge und Datenbanken</h4>
            <p></p>
        </a>
    </div>
</div>
