<div class="panel panel-bottom panel-default tf-panel-home-4">
    <a class="panel-default-link" href="<?=$this->url('content-page', ['page' => 'zeitschriften']) ?>">
        <div class="panel-image" style="background-image: url(<?=$this->imageLink('newfrontpage/zeitschriften.jpg') ?>);"></div>
        <div class="panel-content">
            <h4>Open Text Service</h4>
            <p></p>
        </div>
    </a>
</div>