<p>The Fachinformationsdienst Theologie (Specialized Information Service in Theology) promotes free access to publications relevant to  theological research that are either in the public domain or for which the publisher has granted the corresponding rights of use.</p>

<p>We offer the DoD service to all IxTheo users with an academic interest in the study of theology and religion. Provided that the legal requirements are met and that it is possible from a preservative and technical point of view, individual titles (e.g. monographs, journal volumes, yearbooks and edited volumes) from the holdings of Tübingen University Library will be digitised at the expense of the FID. The full texts are then made publicly available via IxTheo. For more extensive requests (e.g. the digitisation of an entire series), please contact us individually.</p>

<p>Digitised titles in <a target="_blank" href="<?=$this->url('search-results') . '?lookfor=' . urlencode('rs:dods')?>&type=AllFields">IxTheo</a></p>

<p>As the author of a publication, you can also suggest this title for the DoD service if the publisher has granted you the corresponding rights of use or if the rights lie with yourself for another reason (e.g. if it is a dissertation that has never been published). We will then get in touch with you regarding the further procedure.</p>

<p>We will be pleased to support you with any questions you may have, e.g. regarding copyright issues.</p>

<p>This is how it works:</p>

<ul>
    <li>Before you send us a digitisation request, we kindly ask you to look up in the <a href="https://kvk.bibliothek.kit.edu/index.html?lang=en" target="_blank">Karlsruhe Virtual Catalogue</a> whether the desired title is already available in Open Access.</li>
    <li>Ideally, you can already find out whether the work is in the public domain on the basis of the author's life dates.</li>
    <li>In Germany and most other European countries, a publication is considered to be in the public domain if more than 70 years have passed since the death of the author (§ 64 UrhG). If there is more than one author, the 70-year term applies from when the last of these authors has died.</li>
    <li>Everything fits? Then please complete the form below (mandatory fields are marked with an asterisk):</li>
</ul>

