<p>Der FID Theologie fördert den freien Zugang zu theologisch und religionswissenschaftlich relevanten Publikationen, die entweder gemeinfrei sind oder für die entsprechende Nutzungsrechte von Verlagsseite eingeräumt wurden.</p>

<p>Mit dem DoD-Service bieten wir allen  IxTheo-Nutzer*innen mit einem wissenschaftlichen Interesse die Möglichkeit, gewünschte theologisch relevante Titel aus dem Bestand der UB Tübingen auf Kosten des FID digitalisieren zu lassen. Die Volltexte werden anschließend über IxTheo frei zur Verfügung gestellt.</p>

<p>Bereits digitalisierte Titel in <a target="_blank" href="<?=$this->url('search-results') . '?lookfor=' . urlencode('rs:dods')?>&type=AllFields">IxTheo</a></p>

<p>Im Rahmen des Angebots können einzelne Titel digitalisiert werden, u.a. Monografien, Zeitschriftenbände, Jahrbücher und Sammelwerke, sofern die rechtlichen Bedingungen geklärt und die Titel konservatorisch und technisch digitalisierbar sind. Bei umfangreicheren Anfragen (z. B. Digitalisierung ganzer Reihen) nehmen Sie bitte gesondert Kontakt mit uns auf.</p>

<p>Wenn Sie als Autor*in eines Werkes die Nutzungsrechte vom Verlag erhalten haben oder die Nutzungsrechte aus anderen Gründen (z.B. nur maschinenschriftlich publizierte Dissertation) bei Ihnen liegen, können Sie uns auch diesen Titel für den DoD-Service vorschlagen. Wir setzen uns dann mit Ihnen wegen des weiteren Prozederes in Verbindung. Bei Fragen z. B. zur Rechteklärung stehen wir Ihnen gerne beratend zur Seite.</p>

<p>Und so geht es:</p>
<ul>
    <li>Bevor Sie einen Digitalisierungsauftrag an uns richten, bitten wir Sie darum, anhand des <a href="https://kvk.bibliothek.kit.edu/index.html?lang=en" target="_blank">Karlsruher Virtuellen Katalogs</a> zu prüfen, ob der gewünschte Titel bereits frei im Internet zugänglich ist.</li>
    <li>Idealerweise können Sie anhand der Lebensdaten bereits feststellen, ob es sich um einen gemeinfreien Titel handelt:</li>
    <li>Ein Werk gilt in Deutschland und in den meisten anderen europäischen Ländern als gemeinfrei, wenn der bzw. die Urheber*in seit mehr als 70 Jahren verstorben ist (§ 64 UrhG). Bei mehreren Autor*innen gilt die 70-Jahre-Frist ab dem Tod der zuletzt verstorbenen Person.</li>
    <li>Alles passt? Dann füllen Sie bitte das nachstehende Formular aus (Pflichtfelder sind markiert):</li>
</ul>
