<h2>Perfil de adquisiciones</h2>
<p>El FID de Criminología adquiere literatura especializada relevante para la materia. Esto incluye obras específicas y obras de interés criminológico de las ciencias afines como la sociología, la psicología, la pedagogía y la jurisprudencia.</p>

<h3>I. Áreas específicas</h3>
<ul>
    <li>Delincuencia y criminalización</li>
    <li>Política penal</li>
    <li>Prevención de la delincuencia</li>
    <li>Pronóstico de criminalidad y del tratamiento</li>
    <li>Personalidad, categorías y grupos de delincuentes</li>
    <li>Cuestiones victimológicas en criminología</li>
    <li>Enjuiciamiento y diversión o sanción informal</li>
    <li>Sentencias y medidas, así como ejecución de sentencias</li>
    <li>Sistema penal, penal juvenil y de medidas de tratamiento</li>
    <li>Supervisión de delincuentes y tratamiento de delincuentes en libertad</li>
    <li>Alternativas a la justicia penal tradicional (justicia transicional, justicia reparadora, mediación entre víctima y delincuente, etc.)</li>
</ul>

<h3>II. Áreas relacionadas</h3>
Aspectos criminológicos
<ul>
    <li>de problemas sociales</li>
    <li>del derecho, la economía y la sociedad</li>
    <li>de la socialización y el control social informal</li>
    <li>de las instituciones y los procedimientos del control social formal</li>
    <li>de la normatividad de la sociedad (formación, establecimiento y ruptura de normas, y reacción social)</li>
</ul>
<p>Si echa en falta alguna obra que se ajuste al perfil de adquisiciones del FID de Criminología, puede hacer una <a href="/Feedback/Form/AcquisitionRequest">sugerencia de adquisición</a>.</p>
