<h1>Wissenschaftlicher Beirat</h1>

<p>Der FID Kriminologie wird durch den 2018 berufenen Beirat begleitet und konzeptionell beraten. Durch das breite Spektrum an vertretenen Fächern bildet der Beirat die Interdisziplinarität des Faches Kriminologie gut ab und gewährleistet so eine kontinuierliche Anbindung an die Fachcommunity.</p>

<h2>Dem Beirat gehören an:</h2>

<p><a target="_blank" href="https://www.hwr-berlin.de/prof/marc-coester/">Prof. Dr. Mark Coester</a> (FB Polizei und Sicherheitsmanagement, Hochschule für Wirtschaft und Recht Berlin)</p>
<p><a target="_blank" href="https://www.iu.de/hochschule/lehrende/fischer-thomas/">Prof. Dr. Thomas A. Fischer</a> (Soziale Arbeit, IU Internationale Hochschule)</p>
<p><a target="_blank" href="https://www.rewi.hu-berlin.de/de/lf/ls/hfl">Prof. Dr. Katrin Höffler</a> (Lehrstuhl für Strafrecht, Strafprozessrecht, Kriminologie und Rechtssoziologie, Humboldt-Universität zu Berlin)</p>
<p><a target="_blank" href="https://uni-tuebingen.de/fakultaeten/juristische-fakultaet/lehrstuehle-und-personen/lehrstuehle/emeritierte-und-pensionierte-professoren/kerner-hans-juergen/">Prof. em. Dr. Hans-Jürgen Kerner</a> (Institut für Kriminologie, Eberhard Karls Universität Tübingen)</p>
<p><a target="_blank" href="https://uni-tuebingen.de/en/fakultaeten/juristische-fakultaet/lehrstuehle-und-personen/lehrstuehle/lehrstuehle-strafrecht/kinzig/">Prof. Dr. Jörg Kinzig </a> (Institut für Kriminologie, Eberhard Karls Universität Tübingen)</p>
<p><a target="_blank" href="https://www.hs-bremerhaven.de/dominic-kudlacek">Prof. Dr. Dominic Kudlacek</a> (Integrated Safety and Security Management, Hochschule Bremerhaven)</p>
<p><a target="_blank" href="https://www.jura.uni-hannover.de/de/meier/lehrstuhlinhaber">Prof. Dr. Bernd-Dieter Meier</a> (Juristische Fakultät, Kriminalwissenschaftliches Institut, Leibnitz Universität Hannover)</p>
<p><a target="_blank" href="https://kriminologischer-dienst-bw.justiz-bw.de/pb/,Lde/Startseite/Der+Kriminologische+Dienst/Organisation">Dr. Bernadette Schaffer</a> (Kriminologischer Dienst Baden-Württemberg)</p>
<p><a target="_blank" href="https://www.hs-esslingen.de/personen/sabine-schneider/">Prof. Dr. Sabine Schneider</a> (Fakultät Soziale Arbeit, Bildung und Pflege, Hochschule Esslingen)</p>
