<h1>Consejo Asesor Científico</h1>

<p>El FID de Criminología está acompañado y es asesorado conceptualmente por un Consejo Asesor creado en 2018. Debido al amplio espectro de temas representados, el Consejo Asesor refleja adecuadamente la interdisciplinariedad del campo de la criminología y garantiza así una conexión continua con la comunidad profesional.</p>

<h2>Los miembros del Consejo Asesor son:</h2>

<p><a target="_blank" href="https://www.hwr-berlin.de/prof/marc-coester/">Prof. Dr. Mark Coester</a> (Policía y Gestión de Seguridad, HWR Escuela de Economía y Derecho de Berlín)</p>
<p><a target="_blank" href="https://www.iu.de/hochschule/lehrende/fischer-thomas/">Prof. Dr. Thomas A. Fischer</a> (Trabajo Social, IU Internationale Hochschule)</p>
<p><a target="_blank" href="https://www.rewi.hu-berlin.de/de/lf/ls/hfl">Prof. Dr. Katrin Höffler</a> (Derecho Penal, Derecho Procesal Penal, Criminología y Sociología del Derecho, Universidad Humboldt de Berlin)</p>
<p><a target="_blank" href="https://uni-tuebingen.de/fakultaeten/juristische-fakultaet/lehrstuehle-und-personen/lehrstuehle/emeritierte-und-pensionierte-professoren/kerner-hans-juergen/">Prof. em. Dr. Hans-Jürgen Kerner</a> (Instituto de Criminología, Universidad Eberhard Karls de Tubinga)</p>
<p><a target="_blank" href="https://uni-tuebingen.de/en/fakultaeten/juristische-fakultaet/lehrstuehle-und-personen/lehrstuehle/lehrstuehle-strafrecht/kinzig/">Prof. Dr. Jörg Kinzig</a> (Instituto de Criminología, Universidad Eberhard Karls de Tubinga) </p>
<p><a target="_blank" href="https://www.hs-bremerhaven.de/dominic-kudlacek">Prof. Dr. Dominic Kudlacek</a> (Gestión Integrada de Seguridad, Hochschule Bremerhaven)</p>
<p><a target="_blank" href="https://www.jura.uni-hannover.de/de/meier/">Prof. Dr. Bernd-Dieter Meier</a> (Facultad de Derecho, Instituto de Policía Científica, Universidad Leibnitz de Hanover)</p>
<p><a target="_blank" href="https://kriminologischer-dienst-bw.justiz-bw.de/pb/,Lde/Startseite">Dr. Bernadette Schaffer</a> (Servicio Criminológico de Baden-Württemberg)</p>
<p><a target="_blank" href="https://www.hs-esslingen.de/personen/sabine-schneider/">Prof. Dr. Sabine Schneider</a> (Facultad de Trabajo Social, Educación y Cuidados, Universidad Esslingen)</p>
