<h1>Scientific Advisory Board</h1>

<p>The FID Criminology benefits from the guidance and conceptual advice of its scientific advisory board, which was appointed in 2018. The advisory board is composed of experts from diverse fields, ensuring a comprehensive and interdisciplinary representation of the subject of criminology. By maintaining close ties to the professional community, the advisory board ensures a consistent connection to the latest developments in the field.</p>

<h2>The members of the advisory board include:</h2>

<p><a target="_blank" href="https://www.hwr-berlin.de/prof/marc-coester/">Prof. Dr. Mark Coester</a> (Department of Police and Security Management, Berlin School of Economics and Law)</p>
<p><a target="_blank" href="https://www.iu.de/hochschule/lehrende/fischer-thomas/">Prof. Dr. Thomas A. Fischer</a> (Department of Police and Security Management, Berlin School of Economics and Law)</p>
<p><a target="_blank" href="https://www.rewi.hu-berlin.de/de/lf/ls/hfl">Prof. Dr. Katrin Höffler</a> (Criminal Law, Criminal Procedural Law, Criminology, Sociology of Law, Humboldt University of Berlin) </p>
<p><a target="_blank" href="https://uni-tuebingen.de/fakultaeten/juristische-fakultaet/lehrstuehle-und-personen/lehrstuehle/emeritierte-und-pensionierte-professoren/kerner-hans-juergen/">Prof. em. Dr. Hans-Jürgen Kerner</a> (Institute for Criminology, Eberhard Karls University Tübingen)</p>
<p><a target="_blank" href="https://uni-tuebingen.de/en/fakultaeten/juristische-fakultaet/lehrstuehle-und-personen/lehrstuehle/lehrstuehle-strafrecht/kinzig/">Prof. Dr. Jörg Kinzig</a> (Institute for Criminology, Eberhard Karls University Tübingen) </p>
<p><a target="_blank" href="https://www.hs-bremerhaven.de/dominic-kudlacek">Prof. Dr. Dominic Kudlacek</a> (Integrated Safety and Security Management, Hochschule Bremerhaven)</p>
<p><a target="_blank" href="https://www.jura.uni-hannover.de/de/meier/">Prof. Dr. Bernd-Dieter Meier</a> (Faculty of Law, Institute of Criminology, Leibnitz University Hanover)</p>
<p><a target="_blank" href="https://kriminologischer-dienst-bw.justiz-bw.de/pb/,Lde/Startseite">Dr. Bernadette Schaffer</a> (Criminological Service Baden-Württemberg)</p>
<p><a target="_blank" href="https://www.hs-esslingen.de/personen/sabine-schneider/">Prof. Dr. Sabine Schneider</a> (Faculty of Social Work, Education and Nursing Sciences, Esslingen University)</p>


