<div class="table_content">
    <div class="table_content_header">
        <h1>Kriminologie und Gewaltprävention</h1>
        <h3>Master of Arts (M.A.)</h3>
        <h2>Hochschule für Wirtschaft und Recht</h2>
    </div>
    <table>
        <tr>
            <td>Studienform</td>
            <td>Berufsbegleitender Fernstudiengang, Blended-Learning (Präsenz- & Onlinelehre), interdisziplinär, anwendungsorientiert, berufsgruppenübergreifend</td>
        </tr>
        <tr>
            <td>Inhalte</td>
            <td>Kriminologie, Soziologie, Psychologie, Politik- und Rechts-wissenschaft, Viktimologie, Kriminalpolitik, empirische Sozialforschung, Evaluations- und Evidenzforschung, Implementationsforschung, Projekt-/Netzwerk-/Kooperationsmanagement
            verbindet Kriminologie, Kriminalprävention, Präventionswissenschaft und Präventionspraxis</td>
        </tr>
        <tr>
            <td>Semesteranzahl</td>
            <td>4 Semester</td>
        </tr>
        <tr>
            <td>Beginn</td>
            <td>1. Oktober</td>
        </tr>
        <tr>
            <td>ECTS</td>
            <td>90 ECTS</td>
        </tr>
        <tr>
            <td>Voraussetzungen</td>
            <td>abgeschlossenes Hochschulstudium sowie mind. 1 Jahr qualifizierte Berufserfahrung im kriminologischen oder kriminalpräventiven Bereich nach dem ersten Hochschulabschluss</td>
        </tr>
        <tr>
            <td>Studiengebühren</td>
            <td>8900 € für das gesamte Studium</td>
        </tr>
        <tr>
            <td>Bewerbungszeitraum</td>
            <td>01.05.-15.07.</td>
        </tr>
        <tr>
            <td>Bewerbungsprozess</td>
            <td>Online-Bewerbung</td>
        </tr>
        <tr>
            <td>Sonstiges</td>
            <td>keine Angaben</td>
        </tr>
        <tr>
            <td>Link zur Homepage</td>
            <td><a target="_blank" href="https://www.hwr-berlin.de/studium/studiengang/detail/165-kriminologie-und-kriminalpraevention">https://www.hwr-berlin.de/studium/studiengang/detail/165-kriminologie-und-kriminalpraevention</a></td>
        </tr>
    </table>

    <p class="table_content_footer kursiv">Stand: 10.7.2026</p>

</div>
