<div class="table_content">
    <div class="table_content_header">
        <h1>Kriminologie, Kriminalistik und Polizeiwissenschaften</h1>
        <h3>Master of Arts (M.A.)</h3>
        <h2>Ruhr Universität Bochum</h2>
    </div>
    <table>
        <tr>
            <td>Studienform</td>
            <td>Berufsbegleitet, interdisziplinär, multiperspektivisch, Blended-Learning (Präsenz- & Onlinelehre)</td>
        </tr>
        <tr>
            <td>Inhalte</td>
            <td>Grundlagen, aktuelle Forschungsergebnisse, empirische Methoden in Kriminologie, Kriminalistik und Polizeiwissenschaften<br />
                Wahlbereiche: Kriminologie oder Kriminalistik
            </td>
        </tr>
        <tr>
            <td>Semesteranzahl</td>
            <td>4 Semester (3 Lehrsemester, 1 Prüfungssemester)</td>
        </tr>
        <tr>
            <td>Beginn</td>
            <td>1. Januar</td>
        </tr>
        <tr>
            <td>ECTS</td>
            <td>60 ECTS</td>
        </tr>
        <tr>
            <td>Voraussetzungen</td>
            <td>Abgeschlossenes Hochschul-/Fachhochschulstudium mit kriminologischem, kriminalistischem und/oder polizeiwissenschaftlichem Bezug von mindestens 240 CP<br />
                Mindestens einjährige Berufserfahrung in einem für die Kriminologie, Kriminalistik und/oder Polizeiwissenschaft relevanten Bereich
            </td>
        </tr>
        <tr>
            <td>Studiengebühren</td>
            <td>5800€ für das gesamte Studium</td>
        </tr>
        <tr>
            <td>Bewerbungszeitraum</td>
            <td>15.04.-30.06.</td>
        </tr>
        <tr>
            <td>Bewerbungsprozess</td>
            <td>1. Onlinebewerbung mit Unterlagen<br />
                2. Nach erfüllten Voraussetzungen findet ein online Auswahlverfahrenstest* statt<br />
                Das Testergebnis entscheidet über Ab-/Zusage, bzw. Wartelisteplatz (erfolgt bis Ende September/Anfang Oktober)
            </td>
        </tr>
        <tr>
            <td>Sonstiges</td>
            <td>Workload: ca. 15 Stunden pro Woche (ca. 2h am Tag)<br />
                * Auswahlverfahrenstest:<br />
                3 Arbeitsaufträge:<br />
                2 deutsche Lektüren und 1 englischer kriminologischer, kriminalistischer oder kriminalpolitischer Text<br />
                4. Arbeitsauftrag: Recherche zu aktueller oder klassischer soziologischer oder kriminologischer Studie;<br />
                90-minütiger Onlinetest zu 4 Arbeitsaufträgen (80%) und weiteres (20%)
            </td>
        </tr>
        <tr>
            <td>Link zur Homepage</td>
            <td><a target="_blank" href="https://www.makrim.de/">https://www.makrim.de/</a></td>
        </tr>
    </table>

    <p class="table_content_footer kursiv">Stand: 24.6.2026</p>

</div>
