<div class="table_content">
    <div class="table_content_header">
        <h1>Kriminologie, Kriminalistik und Polizeiwissenschaften</h1>
        <h3>Master of Arts (M.A.)</h3>
        <h2>Ruhr Universität Bochum</h2>
    </div>
    <table>
        <tr>
            <td>Studienform</td>
            <td>berufsbegleitender Blended-Learning Studiengang mit Präsenzphasen; interdisziplinär, multiperspektivisch und berufsgruppenübergreifend</td>
        </tr>
        <tr>
            <td>Inhalte</td>
            <td>Grundlagen und aktuelle Forschungsergebnisse in Kriminologie, Kriminalistik und Polizeiwissenschaft; Soziologie und empirische Sozialforschung; rechtliche 
                Perspektiven auf ausgewählte Kriminalitätsphänomene; berufsfeldnahe interdisziplinäre Perspektiven auf Kriminalität <br />
                Wahlbereiche: Kriminologie <span style="text-decoration: underline;">oder</span> Kriminalistik
            </td>
        </tr>
        <tr>
            <td>Semesteranzahl</td>
            <td>4 Semester (3 Lehrsemester, 1 Semester für die Erstellung der Masterthesis („Prüfungssemester“))</td>
        </tr>
        <tr>
            <td>Beginn</td>
            <td>1. Januar</td>
        </tr>
        <tr>
            <td>ECTS</td>
            <td>60 ECTS</td>
        </tr>
        <tr>
            <td>Voraussetzungen</td>
            <td>abgeschlossenes (Fach-)Hochschulstudium mit kriminologischem, kriminalistischem und/oder polizeiwissenschaftlichem Bezug, Nachweis von mindestens 240 CP, <br />
                sowie <br />
                mindestens einjährige einschlägige Berufserfahrung zum Zeitpunkt des Studienbeginns sowie Englischkenntnisse auf Niveau B 2
            </td>
        </tr>
        <tr>
            <td>Studiengebühren</td>
            <td>5.800€ für das gesamte Studium</td>
        </tr>
        <tr>
            <td>Bewerbungszeitraum</td>
            <td>15.04.-30.06.</td>
        </tr>
        <tr>
            <td>Bewerbungsprozess</td>
            <td>1. Bewerbung mit Unterlagen über das Bewerbungsportal <br />
                2. Bei Erfüllung der Voraussetzungen findet ein Online-Auswahlverfahrenstest* statt. Das Testergebnis entscheidet über Ab-/Zusage, bzw. Wartelistenplatz (erfolgt bis Ende September/Anfang Oktober)
            </td>
        </tr>
        <tr>
            <td>Sonstiges</td>
            <td>Workload: ca. 15 Stunden pro Woche (ca. 2h am Tag) <br />
                * Auswahlverfahrenstest: <br />
                90-minütiger Onlinetest zu vier Arbeitsaufträgen (80%) und weitere Arbeitsaufträge (20%): Lektüre eines englischen und zwei deutscher kriminologisch, kriminalistisch oder kriminalpolitischer Texte sowie Recherche zu einer aktuellen oder klassischen soziologischen oder kriminologischen Studie
            </td>
        </tr>
        <tr>
            <td>Link zur Homepage</td>
            <td><a target="_blank" href="https://www.makrim.de/">https://www.makrim.de/</a></td>
        </tr>
    </table>

    <p class="table_content_footer kursiv">Stand: 15.7.2026</p>

</div>
