<h2>Call for Papers</h2>
<h2>2026</h2>
<h3>Journal</h3>
<p>Rolling deadline</p>
<ul>
    <li>Monographien und bearbeitete Sammlungen: <a target="_blank" href="https://www.acjrd.ie/images/PDFs/newsletters/attachments/Proposals-New-Advances-in-Crime-and-Social-Harm.pdf">NEW ADVANCES IN CRIME AND SOCIAL HARM</a></li>
</ul>
<h3>Tagung</h3>
<ul>
    <li>British Society of Criminology Conference 2026 (Nottingham): <a target="_blank" href="https://www.ntu.ac.uk/about-us/events/events/2026/7/british-society-of-criminology-conference-2026">Building Resilience and Hope into Criminology and Criminal Justice </a> (Deadline für Einreichung: 22.02.2026)</li>
    <li>Rechtsextreminsmus Tagung and der HWR Berlin (Berlin): <a target="_blank" href="https://zeitgeschichte-extreme-rechte.de/2026/01/27/cfp-demokratieschutz/">Demokratieschutz durch Verbote? Möglichkeiten und Grenzen staatlicher Maßnahmen gegen die extreme Rechte</a> (Deadline für Einreichung: 28.02.2026)</li>
    <li>Zwischen Tradition und Neuerung: <a target="_blank" href="/krimdok_docs/CfP_Zwischen_Tradition_und_Neuerung.pdf">Rechtsstaatlichkeit und Wandel gesellschaftlicher Ordnungen in der Bundesrepublik bis zum Ende der 1970er Jahre</a> (Deadline für Einreichung: 12.04.2026)</li>
    <li>Jahrestagung des Arbeitskreis Empirische Polizeiforschung: <a target="_blank" href="/krimdok_docs/CFP_Jahrestagung_2026_Polizei_zwischen_Fuhren_und_Folgen.pdf">Polizei zwischen Führen und Folgen</a> (Deadline für Einreichungen: 15.04.2026)</li>
    <li>FlexFunds im Bereich Forschungsdatenmanagement: <a target="_blank" href="https://www.konsortswd.de/flexfunds/">Leistungsfähige Tools für das Forschungsdatenmanagement insbesondere sensibler Daten</a> (Deadline für Einreichung: 15.04.2026)</li>
    <li>61. Kolloquium der Südwestdeutschen und Schweizerischen Kriminologischen Institute und Lehrstühle: <a target="_blank" href="https://kolloquium.strafrecht-online.org/"></a> (Deadline für Einreichung: 30.04.2026)</li>
    <li>20th International Symposium On Victimology (2030; Montreal): <a target="_blank" href="https://www.worldsocietyofvictimology.org/bid-2030/"></a> (Deadline für Einreichung: 31.03.2027)</li>
</ul>
