<h2>Call for Papers</h2>
<h2>2026</h2>
<h3>Journal</h3>
<p>Fixed Deadline</p>
<ul>
    <li>Journal of Right-Wing Studies - Special Issue: <a target="_blank" href="/krimdok_docs/CfP-Journal-of-Right-Wing-Studies.pdf">Psychoanalytic Social Psychological Perspectives on Contemporary Authoritarianism</a> (Submission Deadline: 15.07.2026)</li>
    <li>Journal of Criminal Justice: <a target="_blank" href="https://www.sciencedirect.com/special-issue/329119/the-geography-of-crime-in-the-digital-era">The Geography of Crime in the Digital Era</a> (Submission Deadline: 01.08.2026)</li>
    <li>forum kriminalprävention: <a target="_blank" href="https://www.forum-kriminalpraevention.de/">Cyberkriminalität</a> (Submission Deadline: 28.09.2026)</li>
</ul>
<p>Rolling Deadline</p>
<ul>
    <li>Monographien und bearbeitete Sammlungen: <a target="_blank" href="https://www.acjrd.ie/images/PDFs/newsletters/attachments/Proposals-New-Advances-in-Crime-and-Social-Harm.pdf">NEW ADVANCES IN CRIME AND SOCIAL HARM</a></li>
</ul>
<h3>Conference</h3>
<ul>
    <li>20th International Symposium On Victimology (2030; Montreal): <a target="_blank" href="https://www.worldsocietyofvictimology.org/bid-2030/">https://www.worldsocietyofvictimology.org/bid-2030/</a> (Submission Deadline: 31.03.2027)</li> 
</ul>