<h2>Call for Papers</h2>
<h2>2026</h2>
<h3>Journal</h3>
<p>Rolling deadline</p>
<ul>
    <li>Monographien und bearbeitete Sammlungen: <a target="_blank" href="https://www.acjrd.ie/images/PDFs/newsletters/attachments/Proposals-New-Advances-in-Crime-and-Social-Harm.pdf">NEW ADVANCES IN CRIME AND SOCIAL HARM</a></li>
</ul>
<h3>Conferencia</h3>
<ul>
    <li>European Journal on Criminal Policy and Research: <a target="_blank" href="https://link.springer.com/collections/fafadbeihh">Criminology & Virtual Reality in Europe: Research, Current Needs, and Future Paths</a> (Deadline: 15.05.2026)</li>
    <li>Workshop (1.&2.12.2026) Osnabrück University: <a target="_blank" href="https://www.uni-osnabrueck.de/imis/en/news-events/detail-news/2026/05/call-for-papers-workshop-data-practices-from-below">Data practices from below: Alternative archiving, counter-mapping and social-media activism in response to violence, oppression and ignorance</a> (Deadline: 14.06.2026)</li>
    <li>Journal of Criminal Justice: <a target="_blank" href="https://www.sciencedirect.com/special-issue/329119/the-geography-of-crime-in-the-digital-era">The Geography of Crime in the Digital Era</a> (Deadline: 01.08.2026)</li>
    <li>20th International Symposium On Victimology (2030; Montreal): <a target="_blank" href="https://www.worldsocietyofvictimology.org/bid-2030/">https://www.worldsocietyofvictimology.org/bid-2030/</a> (Deadline: 31.03.2027)</li> 
</ul>