<h2>Convocatoria de ponencias</h2>
<h2>2025</h2>

<h3>Diciembre</h3>
<ul>
    <li>09.-10.04.2026, Prag: <a target="_blank" href="https://tact-forsed.eu/2025/10/07/call-for-papers-for-international-conference-organised-by-tact-forsed/">Engaging with Conspiracy Theories, Fostering Democracy – International Conference (TaCT-FoRSED)</a> (Deadline für Einreichungen: 05.12.2025)</li>
    <li>05-07.11.2026, Gemeinsame Tagung des AK Historische Kriminalitätsforschung, der GiwK und des CiCS: <a target="_blank" href="https://www.hsozkult.de/event/id/event-157250">Selektive Strafen: Kontrolle, Kriminalität und Kriminalisierung im Blick von Historischer Kriminalitätsforschung und Kriminologie (Deadline für Einreichungen: 15.12.2025)</a></li>
    <li>19.-20.03.2026, 7. Netzwerktagung "Kriminologie in NRW": <a target="_blank" href="https://www.kriminologie-nrw.de/freie_downloads/Call%20Netzwerktagung%20Kriminologie%20M%C3%A4rz%2026%20Bochum.pdf">Kriminologie im Dialog – Aktuelle Projekte und innovative Ansätze (Deadline für Einreichungen: 15.12.2025)</a></li>
</ul>

<h2>2026</h2>

<h3>Abril</h3>
<ul>
    <li>08.09.2026, Forschungswerkstatt des Arbeitskreises Empirische Polizeiforschung: <a target="_blank" href="/krimdok_docs/CFP_Junges_Forum.pdf">Junges Forum (Deadline für Einreichungen: 15.04.2026)</a></li>
    <li>09.–11.09.2026, Jahrestagung des Arbeitskreis Empirische Polizeiforschung: <a target="_blank" href="/krimdok_docs/CFP_Jahrestagung_2026_Polizei_zwischen_Fuhren_und_Folgen.pdf">Polizei zwischen Führen und Folgen (Deadline für Einreichungen: 15.04.2026)</a></li>
</ul>
<h3>Sin fecha</h3>
<ul>
    <li>Monographien und bearbeitete Sammlungen: <a target="_blank" href="https://www.acjrd.ie/images/PDFs/newsletters/attachments/Proposals-New-Advances-in-Crime-and-Social-Harm.pdf">NEW ADVANCES IN CRIME AND SOCIAL HARM</a></li>
</ul>
