<h2>Call for Papers</h2>
<h2>2026</h2>
<h3>Journal</h3>
<p>Feste Deadline</p>
<ul>
    <li>RadiX – Zeitschrift für Radikalisierungsforschung und Prävention: <a target="_blank" href="/krimdok_docs/RadiX-PDF.pdf">Frauen im Extremismus: Aktuelle Dynamiken und Forschungsbefunde</a> (Deadline für Einreichung: 09.09.2026)</li>
    <li>forum kriminalprävention: <a target="_blank" href="https://www.forum-kriminalpraevention.de/">Cyberkriminalität</a> (Deadline für Einreichung: 28.09.2026)</li>
</ul>
<p>Rolling Deadline</p>
<ul>
    <li>Monographien und bearbeitete Sammlungen: <a target="_blank" href="https://www.acjrd.ie/images/PDFs/newsletters/attachments/Proposals-New-Advances-in-Crime-and-Social-Harm.pdf">NEW ADVANCES IN CRIME AND SOCIAL HARM</a></li>
</ul>
<h3>Tagung</h3>
<ul>
    <li>Fachtagung der DHPol Münster (Februar, 2027): <a target="_blank" href="/krimdok_docs/DHPol.pdf">Wenn Erfahrung Wissen wird: Betroffenenperspektiven als ein Wegweiser professioneller Polizeiarbeit</a> (Deadline für Einreichung: 30.09.2026)</li>
    <li>20th International Symposium On Victimology (2030; Montreal): <a target="_blank" href="https://www.worldsocietyofvictimology.org/bid-2030/">https://www.worldsocietyofvictimology.org/bid-2030/</a> (Deadline für Einreichung: 31.03.2027)</li> 
</ul>
