<h2>Call for Papers</h2>
<h2>2025</h2>

<h3>Oktober</h3>
<ul>
    <li>13.-14.04.2026, Hannover: <a target="_blank" href="https://www.praeventionstag.de/nano.cms/bewerbungen">31. Deutscher Präventionstag: "KI in der Prävention" (Deadline für Einreichungen: 31.10.2025)</a></li>
    <li>Herbst 2026, Sammelband: <a target="_blank" href="">Umweltskriminalität - Interdisziplinäre Perspektiven auf unsichtbares Unrecht (Deadline für Einreichungen: 31.10.2025)</a></li>
</ul>
<h3>November</h3>
<ul>
    <li>2027, Schwerpunktheft: <a target="_blank" href="">Widerruf von Strafaussetzungen, Umgang mit Rückfalldelikten, Nichterfüllung von Auflagen und Weisungen (Deadline für Einreichungen: 15.11.2025)</a></li>
</ul>
<h3>Dezember</h3>
<ul>
    <li>05-07.11.2026, Gemeinsame Tagung des AK Historische Kriminalitätsforschung, der GiwK und des CiCS: <a target="_blank" href="https://www.hsozkult.de/event/id/event-157250">Selektive Strafen: Kontrolle, Kriminalität und Kriminalisierung im Blick von Historischer Kriminalitätsforschung und Kriminologie (Deadline für Einreichungen: 15.12.2025)</a></li>
    <li>19.-20.03.2026, 7. Netzwerktagung "Kriminologie in NRW": <a target="_blank" href="https://www.kriminologie-nrw.de/freie_downloads/Call%20Netzwerktagung%20Kriminologie%20M%C3%A4rz%2026%20Bochum.pdf">Kriminologie im Dialog – Aktuelle Projekte und innovative Ansätze (Deadline für Einreichungen: 15.12.2025)</a></li>
</ul>
<h3>Ohne Datum</h3>
<ul>
    <li>Monographien und bearbeitete Sammlungen: <a target="_blank" href="https://www.acjrd.ie/images/PDFs/newsletters/attachments/Proposals-New-Advances-in-Crime-and-Social-Harm.pdf">NEW ADVANCES IN CRIME AND SOCIAL HARM</a></li>
</ul>
