<h2>Call for Papers</h2>
<h2>2026</h2>
<h3>Journal</h3>
<p>Rolling deadline</p>
<ul>
    <li>Monographien und bearbeitete Sammlungen: <a target="_blank" href="https://www.acjrd.ie/images/PDFs/newsletters/attachments/Proposals-New-Advances-in-Crime-and-Social-Harm.pdf">NEW ADVANCES IN CRIME AND SOCIAL HARM</a></li>
</ul>
<h3>Conference</h3>
<ul>
    <li>24th Annual STS Conference Graz 2026 <a target="_blank" href="https://www.wu.ac.at/fileadmin/wu/d/i/sozio/Dateien_zu_News/CfA_Digital_Criminology_STS_Graz_final.pdf">Digital Criminology – Bridging Technologies, Human Practices and Environments</a> (Deadline für Einreichung: 27.01.2026)</li>
    <li>The Stockholm Criminology Symposium <a target="_blank"b href="https://criminologysymposium.com/event/call-for-presentations.html">Contemporary criminology - A Better Understanding of Migration, Ethnicity and Crime - The Power of Crime Prevention Programs</a> (Deadline für Einreichung:13.02.2026)</li>
    <li>British Society of Criminology Conference 2026 (Nottingham): <a target="_blank" href="https://www.ntu.ac.uk/about-us/events/events/2026/7/british-society-of-criminology-conference-2026">Building Resilience and Hope into Criminology and Criminal Justice </a> (Deadline für Einreichung: 22.02.2026)</li>
    <li>Jahrestagung des Arbeitskreis Empirische Polizeiforschung: <a target="_blank" href="/krimdok_docs/CFP_Jahrestagung_2026_Polizei_zwischen_Fuhren_und_Folgen.pdf">Polizei zwischen Führen und Folgen</a> (Deadline für Einreichungen: 15.04.2026)</li>
</ul>
