<h2>Call for Papers</h2>
<h2>2026</h2>
<h3>Journal</h3>
<p>Rolling deadline</p>
<ul>
    <li>Monographien und bearbeitete Sammlungen: <a target="_blank" href="https://www.acjrd.ie/images/PDFs/newsletters/attachments/Proposals-New-Advances-in-Crime-and-Social-Harm.pdf">NEW ADVANCES IN CRIME AND SOCIAL HARM</a></li>
</ul>
<h3>Conferencia</h3>
<ul>
    <li>04.-05.03.2026, Jahreskonferenz des Verbundprojekts MOTRA (Wiesbaden): <a target="_blank" href="https://www.motra.info/motra-k-26/">Extremismus/Radikalisierung/Prävention (Plazo de presentación: 15.01.2026)</a></li>
    <li>08.-15.06.2026, The Stockholm Criminology Symposium <a target="_blank"b href="https://criminologysymposium.com/event/call-for-presentations.html">Contemporary criminology - A Better Understanding of Migration, Ethnicity and Crime - The Power of Crime Prevention Programs</a>(Plazo de presentación: 13.02.2026)</li>
    <li>07.-10.07.2026, British Society of Criminology Conference 2026 (Nottingham): <a target="_blank" href="https://www.ntu.ac.uk/about-us/events/events/2026/7/british-society-of-criminology-conference-2026">Building Resilience and Hope into Criminology and Criminal Justice (Plazo de presentación: 22.02.2026)</a></li>
    <li>09.–11.09.2026, Jahrestagung des Arbeitskreis Empirische Polizeiforschung: <a target="_blank" href="/krimdok_docs/CFP_Jahrestagung_2026_Polizei_zwischen_Fuhren_und_Folgen.pdf">Polizei zwischen Führen und Folgen (Plazo de presentación: 15.04.2026)</a></li>
</ul>
