<h2>Otros catálogos y bases de datos</h2>

<h3>Servicios nacionales de investigación</h3>
<ul>
    <li><a target="_blank" href="http://www.dpt-map.de">DPT-Map</a> – Portal de búsqueda sobre prevención de la delincuencia</li>
    <li><a target="_blank" href="http://rzblx1.uni-regensburg.de/ezeit/fl.phtml?bibid=UBTUE&amp;colors=7&amp;lang=de&amp;notation=P">EZB</a> – Biblioteca de revistas electrónicas</li>
    <li><a target="_blank" href="http://staatsbibliothek-berlin.de/recherche/fachgebiete/rechtswissenschaft/">FID Recht</a> – Servicio de información especializada sobre investigación jurídica internacional e interdisciplinaria</li>
    <li><a target="_blank" href="https://www.praeventionstag.de/nano.cms/forschungsprojekte">Krimdex</a> – Base de datos DPT sobre proyectos de investigación en prevención del delito y criminología</li>
    <li><a target="_blank" href="https://www.krimz.de/literaturdokumentation.html">KrimLit</a> – Documentación literaria del Centro Criminológico</li>
    <li><a target="_blank" href="https://kvk.bibliothek.kit.edu/index.html">KVK</a> – Catálogo virtual de Karlsruhe (metabuscador nacional e internacional)</li>
    <li><a target="_blank" href="https://csl.mpg.de/en/library">MPI-Freiburg</a> – Catálogo electrónico del Instituto Max Planck para la Investigación sobre la Delincuencia, la Seguridad y el Derecho</li>
    <li><a target="_blank" href="http://sunrise.rg.mpg.de/webOPAC/">MPI-Frankfurt/Main</a> – Catálogo en línea del Instituto Max Planck de Historia y Teoría del Derecho</li>
    <li><a target="_blank" href="http://rvk.uni-regensburg.de/index.php/regensburger-verbundklassifikation-online">RVK-Online</a> – Búsqueda sistemática en catálogos de unas 30 disciplinas temáticas</li>
    <li><a target="_blank" href="http://swb.bsz-bw.de/?COOKIE=U998,Pbszgast,I17,B0728+,SY,NRecherche-DB,D2.1,Ef6c6c7ad-3ac,A,H,R193.197.31.15,FY">SWB-Online</a> – Buscador de catálogos de la Red de Bibliotecas del Suroeste de Alemania</li>
    <li><a target="_blank" href="http://dispatch.opac.dnb.de/DB=1.1/">ZDB</a> – Base de datos de revistas</li>
</ul>

<h3>Ofertas internacionales de investigación (también de editoriales)</h3>
<ul>
    <li><a target="_blank" href="https://dialnet.unirioja.es/">Dialnet</a> – Base de datos en español (en parte con textos completos)</li>
    <li><a target="_blank" href="http://njlaw.rutgers.edu/cj/gray/index.php">Gray-Literature Database</a> – Base de datos sobre literatura gris en el campo de la justicia penal (Rutgers University Newark/NJ)</li>
    <li><a target="_blank" href="http://www.iisj.net/en/library/about-library">Catálogo de la Biblioteca del IISL</a> – Catálogo en línea del Instituto Internacional de Sociología Jurídica de Oñati</li>
    <li><a target="_blank" href="https://www.ncjrs.gov/App/AbstractDB/AbstractDBSearch.aspx">NCJRS Abstracts</a> – Base de datos National Criminal Justice Reference Service, EE.UU.</li>
    <li><a target="_blank" href="https://www.ncjrs.gov/library.html">NCJRS-Biblioteca virtual</a> – Metabuscador de bibliotecas y bases de datos</li>
    <li><a target="_blank" href="http://online.sagepub.com/">Sage-Journals Online</a> – Búsquedas sistemáticas en fondos de revistas (resúmenes gratuitos)</li>
    <li><a target="_blank" href="http://link.springer.com/">SpringerLink</a> – Búsquedas sistemáticas en el fondo de documentos (resúmenes gratuitos)</li>
    <li><a target="_blank" href="http://www.unicri.it/services/library_documentation/catalogue_thesaurus/catalogue.php">UNICRI Library Catalogue</a> – Documentos de investigación sobre delincuencia y justicia penal</li>
    <li><a target="_blank" href="https://www.questia.com/library/criminal-justice/criminology-and-crime/victimology">Victimology Database</a> – Referencias a artículos y libros</li>
    <li><a target="_blank" href="http://www.worldsocietyofvictimology.org/resources/publications/un-wsv-documents/">Victimology United Nations + WSV</a> – Documentos de la ONU y la WSV</li>
</ul>

<h3>Colección de enlaces sobre criminología del lfK</h3>
<ul>
    <li><a target="_blank" href="https://uni-tuebingen.de/en/61573">Directorio de instituciones nacionales, europeas e internacionales</a></li>
</ul>
