<h2>Classics</h2>
<p>Here you will find classic, copyright-free texts in criminology. Please feel free to suggest  further copyright-free classic texts via <a href="mailto:krimdok@ub.uni-tuebingen.de">krimdok@ub.uni-tuebingen.de</a>.</p>

<h3>Gustav Aschaffenburg (1866-1944)</h3>
<ul>
    <li> <a target="_blank" href="http://digital.zbmed.de/zbmednervpsych/content/titleinfo/7194425">Das Verbrechen und seine Bekämpfung</a></li>
	<li> <a target="_blank" href="http://digital.zbmed.de/zbmednervpsych/content/titleinfo/7194760">Psychiatrie und Strafrecht</a></li>
</ul>

<h3>Cesare Beccaria (1738-1794)</h3>
<ul>
    <li> <a target="_blank" href="http://reader.digitale-sammlungen.de/de/fs1/object/display/bsb10393747_00005.html">Über Verbrechen und Strafen</a></li>
</ul>

<h3>Karl von Eckartshausen (1752-1803)</h3>
<ul>
	<li> <a target="_blank" href="https://reader.digitale-sammlungen.de/de/fs1/object/display/bsb10396238_00005.html">Über die Notwendigkeit physiologischer Kenntnisse bei Beurteilung des Verbrechens</a></li>
</ul>

<h3>Enrico Ferri (1856-1929)</h3>
<ul>
    <li> <a target="_blank" href="https://archive.org/stream/dasverbrechenal00ferrgoog#page/n7/mode/2up">Das Verbrechen als sociale Erscheinung. Grundzüge der Kriminal-Sociologie</a></li>
	<li> <a target="_blank" href="https://archive.org/details/diepositivokrim00ferrgoog">Die positive kriminalistische Schule in Italien</a></li>
</ul>

<h3>Paul Johann Anselm von Feuerbach (1775-1833)</h3>
<ul>
    <li><a target="_blank" href="http://www.deutschestextarchiv.de/book/show/feuerbach_recht_1801">Lehrbuch des gemeinen in Deutschland gültigen Rechts</a></li>
    <li><a target="_blank" href="http://mdz-nbn-resolving.de/urn:nbn:de:bvb:12-bsb11276810-4">Merkwürdige Verbrechen in aktenmäßiger Darstellung</a></li>
    <li><a target="_blank" href="http://mdz-nbn-resolving.de/urn:nbn:de:bvb:12-bsb00113211-0">Kaspar Hauser. Beispiel eines Verbrechens am Seelenleben des Menschen</a></li>
    <li><a target="_blank" href="http://mdz-nbn-resolving.de/urn:nbn:de:bvb:12-bsb10396328-6">Über die Strafe als Sicherungsmittel vor künftigen Beleidigungen des Verbrechers</a></li>
    <li><a target="_blank" href="http://mdz-nbn-resolving.de/urn:nbn:de:bvb:12-bsb10394293-6">Philosophisch-juridische Untersuchungen über das Verbrechen des Hochverraths</a></li>
	<li><a target="_blank" href="http://mdz-nbn-resolving.de/urn:nbn:de:bvb:12-bsb10040501-0">Anti-Hobbes oder über die Grenzen der höchsten Gewalt und das Zwangsrecht der Bürger gegen Oberherrn: oder über die Grenzen der höchsten Gewalt und das Zwangsrecht der Bürger gegen den Oberherrn </a></li>
    <li><a target="_blank" href="http://mdz-nbn-resolving.de/urn:nbn:de:bvb:12-bsb10372952-8">Entwurf des Gesetzbuches über Verbrechen und Vergehen für das Königreich Baiern</a></li>
</ul>
	
<h3>Franz Joseph Gall (1758-1828)</h3>
<ul>
    <li><a target="_blank" href="http://mdz-nbn-resolving.de/urn:nbn:de:bvb:12-bsb10368344-1">Untersuchungen über die Anatomie des Nervensystems überhaupt und des Gehirns insbesondere : ein dem franzoesischen Institute ueberreichtes Mémoire ; nebst dem Berichte der H.H. Commissaire des Institutes und den Bemerkungen der Verfasser über diesen Bericht</a></li>
    <li><a target="_blank" href="http://mdz-nbn-resolving.de/urn:nbn:de:bvb:12-bsb11107425-1">Anatomie und Physiologie des Nervensystems im allgemeinen und des Gehirns insbesonders : mit Beobachtungen über die Möglichkeit, die Anlagen mehrerer Geistes- und Gemüthseigenschaften aus dem Baue des Kopfes der Menschen und der Thiere zu erkennen</a></li>
    <li><a target="_blank" href="http://mdz-nbn-resolving.de/urn:nbn:de:bvb:12-bsb10368342-0">Vollständige Geisteskunde : oder auf Erfahrung gestützte Darstellung der geistigen und moralischen Fähigkeiten und ihrer körperlichen Bedingungen</a></li>
</ul>

<h3>Raffaele Garofalo (1851-1934)</h3>
<ul>
    <li> <a target="_blank" href="https://archive.org/stream/criminology00garoiala#page/n5/mode/2up">Criminology</a></li>
</ul>

<h3>François Gayot de Pitaval (1673-1743)</h3>
<ul>
	<li> <a target="_blank" href="https://opacplus.bsb-muenchen.de/metaopac/singleHit.do?methodToCall=showHit&curPos=28&identifier=100_SOLR_SERVER_253841384">Merkwürdige Rechtsfälle als ein Beitrag zur Geschichte der Menschheit</a></li>
	<li> <a target="_blank" href="https://opacplus.bsb-muenchen.de/metaopac/singleHit.do?methodToCall=showHit&curPos=7&identifier=100_SOLR_SERVER_253841384">Causes Célèbres, oder Erzählung sonderbarer Rechtshändel: sammt deren gerichtlichen Entscheidung</a></li>
</ul>

<h3>Emma Goldman (1869-1940)</h3>
<ul>
    <li> <a target="_blank" href="https://babel.hathitrust.org/cgi/pt?id=mdp.39015004033182&view=1up&seq=9&skin=2021">Prisons: A social crime and failure</a></li>
</ul>

<h3>John Howard (1726-1790)</h3>
<ul>
    <li> <a target="_blank" href="http://mdz-nbn-resolving.de/urn:nbn:de:bvb:12-bsb10225172-6">The State Of The Prisons In England And Wales : With Preliminary Observations, And An Account Of Some Foreign Prisons And Hospitals</a></li>
</ul>

<h3>Peter Kropotkin (1842-1921)</h3>
<ul>
    <li> <a target="_blank" href="https://theanarchistlibrary.org/library/petr-kropotkin-law-and-authority">Law and Authority</a></li>
</ul>

<h3>Johannes Lange (1891-1938)</h3>
<ul>
    <li> <a target="_blank" href="https://archive.org/details/b29826937/mode/2up">Verbrechen als Schicksal</a></li>
</ul>

<h3>Franz von Liszt (1851-1919)</h3>
<ul>
	<li> <a target="_blank" href="http://nbn-resolving.de/urn:nbn:de:bvb:355-ubr15787-7">Der Zweckgedanke im Strafrecht</a></li>
	<li> <a target="_blank" href="http://www.nbn-resolving.org/urn/resolver.pl?urn=urn:nbn:de:kobv:b4-200905193636">Das Deutsche Reichsstrafrecht</a></li>
	<li> <a target="_blank" href="http://www.nbn-resolving.org/urn/resolver.pl?urn=urn:nbn:de:kobv:b4-200905193649">Das Völkerrecht</a></li>
</ul>

<h3>John Locke (1632-1704)</h3>
<ul>
	<li> <a target="_blank" href="https://oll.libertyfund.org/titles/locke-the-works-vol-8-some-thoughts-concerning-education-posthumous-works-familiar-letters">Some Thoughts Concerning Education</a></li>
</ul>

<h3>Karl Marx (1818-1883)</h3>
<ul>
	<li> <a target="_blank" href="http://www.mlwerke.de/me/me01/me01_109.htm">Debatten über das Holzdiebstahlsgesetz</a></li>
</ul>

<h3>Robert E. Park (1864-1944)</h3>
<ul>
	<li> <a target="_blank" href="https://archive.org/details/TheCityRobertEPark">The City: Suggestions for the Study of Human Nature in the Urban Environment</a></li>
	<li> <a target="_blank" href="https://archive.org/details/in.ernet.dli.2015.105421">Human Communities: The City and Human Ecology</a></li>
</ul>


<h3>Ferdinand Tönnies (1855-1936)</h3>
<ul>
	<li> <a target="_blank" href="https://archive.org/details/bub_gb_KngRAAAAYAAJ">Das Verbrechen als soziale Erscheinung</a></li>
</ul>

<h3>Max Weber (1864-1920)</h3>
<ul>
	<li> <a target="_blank" href="http://www.archive.org/stream/wirtschaftundges00webeuoft">Wirtschaft und Gesellschaft</a></li>
</ul>


