
<h1>Kontakt und Ansprechpersonen im FID Kriminologie</h1>
<div id="contact" class="">
    <p>
        <ul>
            <li><a href="mailto:katharina.stelzel@uni-tuebingen.de">Allgemein <span class="glyphicon-envelope" aria-hidden="true"></span></a></li>
            <li>Fachliche Betreuung: <a href="mailto:katharina.stelzel@uni-tuebingen.de">Dr. Katharina Stelzel <span class="glyphicon-envelope" aria-hidden="true"></span></a></li>
            <li>Bibliothekarische Betreuung: <a href="mailto:janina.meister@uni-tuebingen.de">Janina Meister <span class="glyphicon-envelope" aria-hidden="true"></span></a></li>
            <li>Technische Betreuung: <a href="mailto:olaf.brandt@uni-tuebingen.de">Olaf Brandt <span class="glyphicon-envelope" aria-hidden="true"></span></a></li>
        </ul>
    </p>
</div>
