<h1>Contact and person in charge at the FID Criminology</h1>
<div id="contact" class="">
    <p>
        <ul>
            <li><a href="mailto:katharina.stelzel@uni-tuebingen.de">General <span class="glyphicon-envelope" aria-hidden="true"></span></a></li>
            <li>Specialist supervision: <a href="mailto:katharina.stelzel@uni-tuebingen.de">Dr. Katharina Stelzel <span class="glyphicon-envelope" aria-hidden="true"></span></a></li>
            <li>Supervisory librarian: <a href="mailto:janina.meister@uni-tuebingen.de">Janina Meister <span class="glyphicon-envelope" aria-hidden="true"></span></a></li>
            <li>Technical supervision: <a href="mailto:olaf.brandt@uni-tuebingen.de">Olaf Brandt <span class="glyphicon-envelope" aria-hidden="true"></span></a></li>
        </ul>
    </p>
</div>
