<h1>Personas de contacto en el FID de Criminología</h1>
<div id="contact" class="">
    <p>
        <ul>
            <li><a href="mailto:katharina.stelzel@uni-tuebingen.de">General <span class="glyphicon-envelope" aria-hidden="true"></span></a></li>
            <li>Asistencia especializada: <a href="mailto:katharina.stelzel@uni-tuebingen.de">Dr. Katharina Stelzel <span class="glyphicon-envelope" aria-hidden="true"></span></a></li>
            <li>Asistencia bibliotecaria: <a href="mailto:janina.meister@uni-tuebingen.de">Janina Meister <span class="glyphicon-envelope" aria-hidden="true"></span></a></li>
            <li>Soporte técnico: <a href="mailto:olaf.brandt@uni-tuebingen.de">Olaf Brandt <span class="glyphicon-envelope" aria-hidden="true"></span></a></li>
        </ul>
    </p>
</div>
   