<h2>Habilitationen und Berufungen</h2>
<p>
    Habilitationen und Berufungen werden wörtlich aus der Zeitschrift "Forschung und Lehre" übernommen und mittels Zuschriften durch Nutzer des FID Kriminologie um den Bereich der Hochschulen für Angewandte Wissenschaften ergänzt.
</p>
<h3>Dezember 2025</h3>
<ul>
    <li>Dr. Nicole Bögelein habilitierte sich an der Universität zu Köln und es wurde ihr die Lehrbefugnis für die Fächer Kriminologie und Soziologie erteilt.</li>
</ul>

<h3>Mai 2025</h3>
<ul>
    <li>Prof. Dr. Lars <b>Berster</b>, Leuphana Universität Lüneburg, hat einen Ruf an die Deutsche Hochschule der Polizei, Münster, auf eine Professur für Strafrecht, Strafprozessrecht und Kriminalpolitik angenommen.</li>
</ul>

<h3>Dezember 2024</h3>
<ul>
    <li>Prof. Dr. Katrin <b>Höffler</b>, Universität Leipzig, hat einen Ruf an die Humboldt-Universität zu Berlin, auf eine W3-Professur für Strafrecht und Strafprozessrecht angenommen.</li>
    <li>Dr. Johannes <b>Kaspar</b>, Universität Augsburg, hat einen Ruf an die Rheinische Friedrich-Wilhelms-Universität Bonn auf eine W3-Professur für Strafrecht und Kriminologie erhalten.</li>
</ul>

<h3>November 2024</h3>
<ul>
    <li>Prof. Dr. Michael <b>Lindemann</b>, Universität Bielefeld, hat einen Ruf an die Rheinische Friedrich-Wilhelms-Universität Bonn, auf eine Professur für Strafrecht und Kriminologie abgelehnt und das Bleibeangebot der Universität Bielefeld angenommen.</li>
</ul>

<h3>September 2024</h3>
<ul>
    <li>Dr. iur. Mario <b>Bachmann</b>, habilitierte sich an der Universität zu Köln und es wurde ihm die Venia Legendi für Strafrecht, Strafprozessrecht, Kriminologie, Strafvollzug, Jugendstrafrecht und Wirtschaftsstrafrecht erteilt.</li>
</ul>

<h3>April 2022</h3>
<ul>
    <li>Dr. Aziz <b>Epik</b>, Humboldt-Universität zu Berlin, hat einen Ruf an die Universität Hamburg, auf eine W1-Professur mit Tenure Track für Rechtswissenschaft mit dem Schwerpunkt Strafrecht und Kriminologie angenommen.</li>
</ul>

<h3>März 2022</h3>
<ul>
    <li>Prof. Dr. Katrin <b>Höffler</b>, Georg-August-Universität Göttingen, hat einen Ruf an die Universität Leipzig, auf eine Professur für Strafrecht, Strafprozessrecht angenommen und hat einen Ruf an die Universität Zürich auf die Professur für Strafrecht, Strafprozessrecht und Kriminologie abgelehnt.</li>
</ul>

<h3>Februar 2022</h3>
<ul>
    <li>Jun-Prof. Dr. Lucia <b>Sommerer</b>, Georg-August-Universität Göttingen, Yale Law School, hat einen Ruf an die Martin-Luther-Universität Halle-Wittenberg, auf eine W1-Professur für Kriminologie, Criminal Compliance, Risk Management und Strafrecht angenommen.</li>
</ul>

<h3>Dezember 2021</h3>
<ul>
    <li>Prof. Dr. Tobias <b>Singelnstein</b>, Ruhr-Universität Bochum, hat einen Ruf an die Goethe-Universität Frankfurt am Main, auf eine W3-Professur für Strafrecht, Strafprozessrecht und Kriminologie angenommen und das Bleibeangebot der Ruhr-Universität Bochum abgelehnt.</li>
</ul>

<h3>August 2020</h3>
<ul>
    <li>Dr. Sebastian <b>Golla</b>, Bonn, hat einen Ruf an die Ruhr-Universität Bochum auf eine Juniorprofessur für Kriminologie, Strafrecht und Sicherheitsforschung angenommen.</li>
</ul>

<h3>März 2019</h3>
<ul>
    <li>Dr. Matthias <b>Braasch</b>, Justus-Liebig-Universität Gießen, habilitierte sich, und es wurde ihm die Lehrbefähigung für die Fächer Kriminologie und Strafrecht erteilt.</li>
</ul>

<h3>Januar 2019</h3>
<ul>
    <li>Dr. Ulrike <b>Zähringer</b>, hat einen Ruf an die Fachhochschule in der Akademie der Polizei Hamburg auf eine W2-Professur für Kriminologie angenommen.</li>
</ul>

<h3>November 2017</h3>
<ul>
    <li>Prof. Dr. Bettina <b>Noltenius</b>, Ruhr-Universität Bochum, hat einen Ruf an die Universität Passau auf eine W3-Professur für Strafrecht, Strafprozessrecht, Rechtsphilosophie und Kriminologie angenommen.</li>
</ul>

<h3>Juni 2017</h3>
<ul>
    <li>Prof. Dr. Wolfgang <b>Knöbl</b>, Hamburger Institut für Sozialforschung, hat einen Ruf an die Leuphana Universität Lüneburg auf die nebenberufliche W3-Professur für Politische Soziologie und Gewaltforschung angenommen.</li>
</ul>

<h3>März 2017</h3>
<ul>
    <li>Dr. Alexander <b>Baur</b>, Stuttgart, hat einen Ruf an die Universität Hamburg auf eine W1-Juniorprofessur für Strafrecht zum 1. April 2017 angenommen.</li>
</ul>

<h3>November 2016</h3>
<ul>
    <li>PD Dr. Jens <b>Puschke</b>, LL.M (King's College), Albert-Ludwigs-Universität Freiburg, hat einen Ruf an die Philipps-Universität Marburg auf eine W3-Professur für Strafrecht und Strafprozessrecht angenommen.</li>
    <li>Prof. Dr. Tobias Singelnstein, Freie Universität Berlin, hat einen Ruf an die Ruhr-Universität Bochum auf eine W3-Professur für Kriminologie erhalten.</li>
</ul>

<h3>April 2016</h3>
<ul>
    <li>Dr. Christine <b>Hentschel</b>, Universität Hamburg, hat einen Ruf an die Universität Hamburg auf eine W2-Professur für Kriminologie, insbesondere Sicherheit und Resilienz, angenommen.</li>
</ul>
