<h1 class="text-center" style="color: #a51e37;">Masterstudiengänge in Kriminologie und Viktimologie</h1>
    
<h2>Europa</h2>

<h3>Albanien</h3>
<ul>
    <li><span class="city">Tirana:</span> <span class="program"><a target="_blank" href="https://fdut.edu.al/master-ekzekutiv-ne-kriminologji/">Executive Master in Criminology</a></span></li>
</ul>

<h3>Belgien</h3>
<ul>
    <li><span class="city">Bruxelles:</span> <span class="program"><a target="_blank" href="https://www.ulb.be/fr/programme/ma-crim">Master en criminologie</a></span></li>
    <li><span class="city">Gent:</span> <span class="program"><a target="_blank" href="https://studiekiezer.ugent.be/2026/master-of-science-in-criminological-sciences">Master of Science in Criminological Science</a></span></li>
    <li><span class="city">Leuven (KU):</span> <span class="program"><a target="_blank" href="https://www.kuleuven.be/programmes/master-criminology">Master of Criminology</a></span></li>
    <li><span class="city">Leuven (UC):</span> <span class="program"><a target="_blank" href="https://uclouvain.be/en-prog-2025-crim2m-cond_adm">Master of Criminology</a></span></li>
    <li><span class="city">Liège:</span> <span class="program"><a target="_blank" href="https://www.programmes.uliege.be/cocoon/20252026/formations/descr/D2SINT01.html">Master en criminologie</a></span></li>
</ul>

<h3>Frankreich</h3>
<ul>
    <li><span class="city">Bordeaux:</span> <span class="program"><a target="_blank" href="https://droit.u-bordeaux.fr/formations/offre-de-formation/master/mention-droit-penal-et-sciences-criminelles/master-criminologie">Master in Criminology</a></span></li>
    <li><span class="city">Paris (Université Paris-Panthéon-Assas [Paris II]):</span> <span class="program"><a target="_blank" href="https://www.assas-universite.fr/en/research/research-centers/paris-institute-criminology-criminal-law-icp">Master 2 in Criminal Law and Criminology</a></span></li>
    <li><span class="city">Poitiers:</span> <span class="program"><a target="_blank" href="https://univ-droit.fr/formations/33081-master-2-criminologie-et-victimologie">Master 2 in Criminology and Victimology</a></span></li>
</ul>

<h3>Großbritannien</h3>

<h5><i>England</i></h5>
<ul>
    <li><span class="city">Arden:</span> <span class="program"><a target="_blank" href="https://arden.ac.uk/our-courses/postgraduate/masters/ma-serious-and-violent-crime">Master in Serious and Violent Crime</a></span></li>
    <li><span class="city">Cambridge:</span> <span class="program"><a target="_blank" href="https://www.crim.cam.ac.uk/Courses/mst-courses">MSt in Applied Criminology, Police Management, and Penology</a></span></li>
    <li><span class="city">Cambridge:</span> <span class="program"><a target="_blank" href="https://www.crim.cam.ac.uk/mphil-criminology">MPhil in Criminological Research</a></span></li>
    <li><span class="city">Lancaster:</span> <span class="program"><a target="_blank" href="https://www.lancaster.ac.uk/study/undergraduate/courses/criminology-ba-hons-m930/2027/">BA Hons in Criminology</a></span></li>
    <li><span class="city">London (University College):</span> <span class="program"><a target="_blank" href="https://www.ucl.ac.uk/prospective-students/graduate/taught-degrees/crime-science-serious-organised-crime-msc">MSc in Crime Science with Serious Organised Crime</a></span></li>
    <li><span class="city">London (London School of Economics and Political Science):</span> <span class="program"><a target="_blank" href="https://www.lse.ac.uk/study-at-lse/graduate/msc-criminology-and-criminal-justice-policy">MSc Criminology and Criminal Justice Policy</a></span></li>
    <li><span class="city">Manchester:</span> <span class="program"><a target="_blank" href="https://www.manchester.ac.uk/study/masters/courses/list/09778/ma-criminology/">MA in Criminology</a></span></li>
    <li><span class="city">Oxford:</span> <span class="program"><a target="_blank" href="https://www.ox.ac.uk/admissions/graduate/courses/msc-criminology-and-criminal-justice">MSc in Criminology and Criminal Justice</a></span></li>
    <li><span class="city">Sheffield:</span> <span class="program"><a target="_blank" href="https://sheffield.ac.uk/postgraduate/taught/courses/2026/international-criminology-ma">MA International Criminology</a></span></li> 
    <li><span class="city">Sheffield:</span> <span class="program"><a target="_blank" href="https://www.shu.ac.uk/courses/criminology/msc-criminology-and-criminal-justice-practice/full-time/2026">MSc Criminology and Criminal Justice Practice</a></span></li>
    <li><span class="city">Southampton:</span> <span class="program"><a target="_blank" href="https://www.online.southampton.ac.uk/landing/ma-artificial-intelligence-criminal-justice-systems">MA Artificial Intelligence – Criminal Justice Systems</a></span></li>
</ul>

<h5><i>Nordirland</i></h5>
<ul>
    <li><span class="city">Belfast:</span> <span class="program"><a target="_blank" href="https://www.qub.ac.uk/courses/postgraduate-taught/criminology-criminal-justice-llm/">LLM in Criminology and Criminal Justice</a></span></li>
    <li><span class="city">Belfast:</span> <span class="program"><a target="_blank" href="https://www.qub.ac.uk/courses/postgraduate-taught/violence-terrorism-security-ma/">MA in Violence, Terrorism and Security</a></span></li>
    <li><span class="city">Ulster:</span> <span class="program"><a target="_blank" href="https://www.ulster.ac.uk/courses/202627/criminology-and-criminal-justice-40666">MSc in Criminology and Criminal Justice</a></span></li>
</ul>

<h5><i>Schottland</i></h5>
<ul>
    <li><span class="city">Edinburgh (University):</span> <span class="program"><a target="_blank" href="https://www.law.ed.ac.uk/study/masters-degrees/msc-criminology-and-criminal-justice">MSc in Criminology and Criminal Justice</a></span></li>
    <li><span class="city">Edinburgh (Napier):</span> <span class="program"><a target="_blank" href="https://www.napier.ac.uk/courses/msc-applied-criminology-and-forensic-psychology-postgraduate-fulltime">MSc Applied Criminology and Forensic Psychology</a></span></li>
    <li><span class="city">Glasgow:</span> <span class="program"><a target="_blank" href="https://www.gla.ac.uk/postgraduate/taught/criminology-criminal-justice/">MSc in Criminology & Criminal Justice</a></span></li>
    <li><span class="city">Stirling:</span> <span class="program"><a target="_blank" href="https://www.stir.ac.uk/courses/pg-taught/criminology/">MSc Criminology</a> bzw. <a target="_blank" href="https://www.stir.ac.uk/courses/pg-taught/criminological-research/">MSc Criminological Research</a></span></li>
    <li><span class="city">Strathclyde:</span> <span class="program"><a target="_blank" href="https://www.strath.ac.uk/courses/postgraduatetaught/criminologysocialpolicy/">MSc Criminology & Social Policy</a></span></li>
    <li><span class="city">West of Scotland:</span> <span class="program"><a target="_blank" href="https://www.uws.ac.uk/study/postgraduate/postgraduate-course-search/criminology-and-criminal-justice/">MSc Criminology and Criminal Justice</a></span></li>
</ul>

<h5><i>Wales</i></h5>
<ul>
    <li><span class="city">Aberystwyth:</span> <span class="program"><a target="_blank" href="https://courses.aber.ac.uk/postgraduate/M983-criminology-criminal-justice/">MSc Criminology and Criminal Justice</a></span></li>
    <li><span class="city">Bangor:</span> <span class="program"><a target="_blank" href="https://www.bangor.ac.uk/courses/postgraduate-taught/criminology-and-criminal-justice-ma">MA in Criminology and Criminal Justice</a></span></li>
    <li><span class="city">Cardiff (University):</span> <span class="program"><a target="_blank" href="https://www.cardiff.ac.uk/study/postgraduate/taught/courses/course/msc-international-criminology-and-criminal-justice">MSc in International Criminology and Criminal Justice</a></span></li>
    <li><span class="city">Cardiff (Metropolitan University):</span> <span class="program"><a target="_blank" href="https://www.cardiffmet.ac.uk/courses/postgraduate/msc-criminology-and-criminal-investigations/">MSc in Criminology & Criminal Investigations</a></span></li>
    <li><span class="city">South Wales:</span> <span class="program"><a target="_blank" href="https://www.southwales.ac.uk/courses/msc-crime-and-justice/">MSc in Crime and Justice</a></span></li>
    <li><span class="city">Swansea:</span> <span class="program"><a target="_blank" href="https://www.swansea.ac.uk/postgraduate/taught/social-sciences/criminology-sociology-social-policy/ma-applied-criminal-justice-criminology/">MA in Applied Criminal Justice and Criminology</a></span></li>
    <li><span class="city">Wrexham:</span> <span class="program"><a target="_blank" href="https://wrexham.ac.uk/courses/postgraduate-courses/criminology-and-criminal-justice/">MA in Criminology & Criminal Justice</a></span></li>
</ul>

<h3>Irland</h3>
<ul>
    <li><span class="city">Cork:</span> <span class="program"><a target="_blank" href="https://www.ucc.ie/en/cke32/">MA in Criminology</a></span></li>
    <li><span class="city">Dublin:</span> <span class="program"><a target="_blank" href="https://hub.ucd.ie/usis/!W_HU_MENU.P_PUBLISH">M.Sc. in Criminology and Criminal Justice</a></span></li>
    <li><span class="city">Galway:</span> <span class="program"><a target="_blank" href="https://www.universityofgalway.ie/courses/taught-postgraduate-courses/criminology-criminal-justice-human-rights.html%23">LLM in Criminology, Criminal Justice and Human Rights</a></span></li>
    <li><span class="city">Maynooth:</span> <span class="program"><a target="_blank" href="https://www.maynoothuniversity.ie/study-maynooth/postgraduate-studies/courses/ma-comparative-criminology-and-criminal-justice">MA in Comparative Criminology and Criminal Justice</a></span></li>
</ul>

<h3>Niederlande</h3>
<ul>
    <li><span class="city">Amsterdam:</span> <span class="program"><a target="_blank" href="https://vu.nl/en/education/master/international-crimes-conflict-and-criminology">MA in International Crimes, Conflict and Criminology</a></span></li>
    <li><span class="city">Groningen:</span> <span class="program"><a target="_blank" href="https://www.rug.nl/masters/clinical-forensic-psychology-and-victimology/">MSc in Psychology (Clinical Forensic Psychology and Victimology)</a></span></li>
    <li><span class="city">Leiden:</span> <span class="program"><a target="_blank" href="https://www.universiteitleiden.nl/en/education/study-programmes/master/crime-and-criminal-justice">MSc in Crime and Criminal Justice</a></span></li>
    <li><span class="city">Maastricht:</span> <span class="program"><a target="_blank" href="https://www.maastrichtuniversity.nl/education/master/programmes/forensics-criminology-and-law">LLM in Forensics, Criminology and Law</a></span></li>
    <li><span class="city">Rotterdam:</span> <span class="program"><a target="_blank" href="https://www.eur.nl/en/master/international-masters-advanced-research-criminology-imarc">International Master's in Advanced Research in Criminology</a></span></li>
    <li><span class="city">Utrecht:</span> <span class="program"><a target="_blank" href="https://www.uu.nl/en/masters/global-criminology">MA in Global Criminology</a></span></li>
</ul>

<h3>Norwegen</h3>
<ul>
    <li><span class="city">Oslo:</span> <span class="program"><a target="_blank" href="https://www.uio.no/studier/program/kriminologi-master/">Master in Criminology</a></span></li>
</ul>

<h3>Polen</h3>
<ul>
    <li><span class="city">Warszawa (UW):</span> <span class="program"><a target="_blank" href="https://informatorects.uw.edu.pl/en/programmes-all/KR/S2-KR/">MA Criminology</a></span></li>
</ul>

<h3>Schweden</h3>
<ul>
    <li><span class="city">Malmö:</span> <span class="program"><a target="_blank" href="https://mau.se/en/study-education/programme/sakre/">Master in Criminology</a></span></li>
    <li><span class="city">Stockholm:</span> <span class="program"><a target="_blank" href="https://www.su.se/english/education/course-catalogue/sk/skrio">Master in Criminology</a></span></li>
</ul>

<h3>Schweiz</h3>
<ul>
    <li><span class="city">Bern:</span> <span class="program"><a target="_blank" href="https://www.unibe.ch/weiterbildungsangebote/mas_kriminologie/index_ger.html">Master of Advanced Studies Kriminologie</a></span></li>
    <li><span class="city">Lausanne:</span> <span class="program"><a target="_blank" href="https://www.unil.ch/unil/en/home/menuinst/etudier/masters/criminologie-et-securite.html">MLaw in Criminology and Security</a></span></li>
</ul>

<h3>Spanien</h3>
<ul>
    <li><span class="city">Ávila:</span> <span class="program"><a target="_blank" href="https://www.ucavila.es/formacion/postgrados/criminologia/">Máster en Criminología Aplicada e Investigación Policial</a></span></li>
    <li><span class="city">Barcelona (Universidad Autónoma de Barcelona):</span> <span class="program"><a target="_blank" href="https://www.uab.cat/web/estudiar/la-oferta-de-masteres-oficiales/informacion-general/criminologia-y-ejecucion-penal-1096480309770.html?cid=1096480309770&d=Touch&pagename=UAB%2FPage%2FTemplatePageDetallMOUAB_F4&param1=1266995155367">Máster Universitario en Criminología y Ejecución Penal</a></span></li>
    <li><span class="city">Barcelona (Universidad de Barcelona):</span> <span class="program"><a target="_blank" href="https://web.ub.edu/en/web/estudis/w/masterdegree-md60s">Master in Applied Criminology</a></span></li>
    <li><span class="city">Barcelona (Pompeu Fabra):</span> <span class="program"><a target="_blank" href="https://www.upf.edu/en/web/mastercriminologia">Master in Criminology and Criminal Justice System</a></span></li>
    <li><span class="city">Elche / virtuell:</span> <span class="program"><a target="_blank" href="https://www.umh.es/contenido/pdi/:tit_m_252/datos_es.html">Master in Criminological and Victimological Intervention</a></span></li>
    <li><span class="city">Valencia:</span> <span class="program"><a target="_blank" href="https://www.uv.es/uvweb/college/en/postgraduate-courses/official-master-s-degrees/official-master-s-degrees-offered/master-s-degree-criminology-security-1285848941532/Titulacio.html?id=1285860784636">Master in Criminology and Security</a></span></li>
    <li><span class="city">Valencia:</span> <span class="program"><a target="_blank" href="https://www.educations.com/institutions/viu-valencia/official-masters-degree-in-criminology-crime-and-victimology">Master in Criminology and Victimology</a></span></li>
</ul>
