<h2>Konferenzen, Tagungen und Veranstaltungen</h2>

<h2>2024</h2>

<h3>April</h3>
<ul>
	<li>23.-24.04.2024, Dresden: <a target="_blank" href="https://www.praxisforum-hochrisikotaeter.de/">Praxisforum 2024: Sexualstraftaten von Männern und Frauen</a></li>
</ul>

<h3>Mai</h3>
<ul>
	<li>22.-24.05.2024, Oranienburg/Berlin: <a target="_blank" href="https://hpolbb.de/humanrights/description">Konferenz der Hochschule Polizei Brandenburg: The Police, Investigative Interviewing and Human Rights: Legal, Psychological and Practical Aspects</a></li>
</ul>

<h3>Juni</h3>
<ul>
	<li>10.-11.06.2024, Cottbus (Brandenburg): <a target="_blank" href="https://www.lpr.sachsen.de/deutscher-praeventionstag-dpt-5706.html#:~:text=Deutsche%20Pr%C3%A4ventionstag%20findet%20am%2010,lautet%20%E2%80%9ESicherheit%20im%20Wandel%E2%80%9C.">29. Deutscher Präventionstag »Sicherheit im Wandel«</a></li>
	<li>17.-19.06.2024, Belfast (Irland): <a target="_blank" href="https://forms.office.com/pages/responsepage.aspx?id=h5QLb6hPqEKutL8uLCLU6IGyH8H3o5pAvtYp28nXSudUMkNNM0M0VlpDTUw3UUlOTFJCMUdaUkc1MS4u">Irish North/South Criminology Conference: "Criminology in Times of Conflict: Rights, Harms and Responsibilities"</a></li>
</ul>

<h3>Juli</h3>
<ul>
	<li>11.07.2024, Oranienburg/Berlin: <a target="_blank" href="https://hpolbb.de/article/save-date-fachtagung-cyberkriminologie">2. Fachtagung Cyberkriminologie der Hochschule Polizei Brandenburg</a></li>
</ul>

<h3>September</h3>
<ul>
    <li>11.-14.09.2024, Bukarest (Rumänien): <a target="_blank" href="https://www.esc-eurocrim.org/index.php/conferences/upcoming-conferences">EUROCRIM 2024: 24. Annual Conference of the European Society of Criminology</a></li>
	<li>23.-24.09.2024, Stuttgart: <a target="_blank" href="https://seehaus-ev.de/sh/symposium-gerechtigkeit-und-wiedergutmachung/">Symposium: Gerechtigkeit und Wiedergutmachung: Neue Impulse für Opferhilfe und Strafrecht der Zukunft</a></li>
	<li>25.09.2024, Online: <a target="_blank" href="https://www.dbh-online.de/aktuelles/jetzt-anmelden-webinar-verschwoerungsglaeubige-der-umgang-mit-reichsbuergerinnen-und">Webinar: Verschwörungsgläubige - Der Umgang mit Reichsbürger:innen und Selbstverwalter:innen</a></li>
	<li>26.-28.09.2024, Tübingen: <a target="_blank" href="http://www.krimg.de/drupal/node/3"> 18. Wissenschaftliche Fachtagung der Kriminologischen Gesellschaft: „Am Puls der Zeit?! Trends, Transfer und Tradition in der Kriminologie“</a></li>
</ul>

<h3>Oktober</h3>
<ul>
	<li>07.-08.10.2024, Nürnberg: <a target="_blank" href="https://www.dvjj.de/veranstaltung/sexualisierte-uebergriffe-an-kindern-und-jugendlichen-umgang-und-arbeit-mit-sexualisiert-gewalttaetigen-jugendlichen-und-jungen-maennern-nuernberg-4/">DVJJ-Seminar: Sexualisierte Übergriffe an Kindern und Jugendlichen: Umgang und Arbeit mit sexualisiert gewalttätigen Jugendlichen und jungen Männern</a></li>
	<li>24. - 25.10.2024, Wiesbaden: <a target="_blank" href="https://www.krimz.de/fachtagung-2024.html">Fachtagung: Die Zukunft der Kriminalität und ihrer Kontrolle</a></li>
</ul>

<h2>2025</h2>

<h3>März</h3>
<ul>
    <li>06.-09.03.2025, Delhi (Indien): <a target="_blank" href="https://mcusercontent.com/9a8b294cb6aa3caf7434ee8af/files/4fcf01c5-a71c-d161-a20c-043f7f47ad9b/1_International_Criminology_Conference_March_2025_CfP_08_2023.pdf">World Conference on Criminology: "Exploring the Dynamics of Crime: Contemporary Challenges and Innovations in Crime Prevention and Criminal Justice"</a></li>
</ul>
