<h2>Congresses and conferences</h2>

<h2>2022</h2>

<h3>October</h3>
<ul>
    <li>25.10.2022, Hamburg/Hybrid: <a target="_blank" href="https://akademie-der-polizei.hamburg.de/contentblob/16292042/edf9f3a32ce30356d06ba0d4cc8ecca2/data/5-srt-programm-do.pdf">5. Hamburger Sicherheitsrechtstag: Smart Big Data Policing </a></li>
    <li>26.-28.10.2022, Essen: <a target="_blank" href="https://www.dhs-fachkonferenz.de/">61. DHS Fachkonferenz SUCHT: Die Sucht- und Drogenpolitik der Gegenwart und Zukunft.</a></li>
    <li>28.10.2022, Kiel: <a target="_blank" href="https://www.soziale-strafrechtspflege.de/attachments/article/456/Save%20the%20date.pdf">SAVE THE DATE: 30. Fachtagung des Schleswig-Holsteinischen Verbandes für soziale Strafrechtspflege</a></li>
</ul>

<h3>November</h3>
<ul>
    <li>7.-8.11.2022, Bonn: <a target="_blank" href="https://www.dbh-online.de/sites/default/files/seminare/attachments/b-2322_ausschreibung_grundlagenseminar.pdf">Grundlagenseminar: Umgang mit Sexualstraftätern – professionelle Haltung, Menschenbild, Unterstützungsangebote</a></li>
    <li>7.-9.11.2022, Cologne: <a target="_blank" href="https://www.dvjj.de/veranstaltung/systemsprenger-schwierigste-jugendliche-hoffnungslose-faelle-kompetenzen-fuer-den-umgang-mit-besonders-herausfordernden-klienten-koeln/">DVJJ-Seminar: Systemsprenger, schwierigste Jugendliche, hoffnungslose Fälle? Kompetenzen für den Umgang mit besonders herausfordernden Klienten</a></li>
	<li>10.-11.11.2022, Jena/Hybrid: <a target="_blank" href="https://www.idz-jena.de/vadet/antifeminismus-und-hasskriminalitaet">Fachtagung des FGZ-Teilinstituts Jena: „Antifeminismus und Hasskriminalität“ </a></li>
    <li>14.-15.11.2022, Nuremberg: <a target="_blank" href="https://www.dvjj.de/veranstaltung/zusammenhaenge-zwischen-entwicklungstraumatisierungen-und-gewaltstraftaten-nuernberg-2/">DVJJ-Seminar: Zusammenhänge zwischen Entwicklungstraumatisierungen und Gewaltstraftaten</a></li>
    <li>17.11.2022, Hamburg: <a target="_blank" href="https://criminologia.de/2022/09/vortragsreihe-sozialwissenschaftliche-perspektiven-auf-instanzen-sozialer-kontrolle/">Sozialwissenschaftliche Perspektiven auf Instanzen Sozialer Kontrolle: Sanfte Kontrolleure revisited: Überlegungen zur sozialen Selektivität in der Jugendgerichtshilfe</a></li>
    <li>18.11.2022, Aschaffenburg: <a target="_blank" href="https://www.dbh-online.de/aktuelles/restorative-justice-fachtag-am-18112022-aschaffenburg-jetzt-anmelden">Restorative Justice-Fachtag: „Ich möchte keine Entschuldigung, ich möchte mein Leben zurück!“: Von Chancen und Grenzen einer Restorative Justice bei sexualisierter Gewalt.</a></li>
    <li>24.-25.11.2022, ONLINE: <a target="_blank" href="https://kfn.de/wp-content/uploads/2022/03/Call%20for%20Papers_final.pdf">Gender & Crime - Sexuelle Selbstbestimmung und geschlechtsspezifische Gewalt</a></li>
</ul>

<h3>December</h3>
<ul>
    <li>15.12.2022, Hamburg: <a target="_blank" href="https://criminologia.de/2022/09/vortragsreihe-sozialwissenschaftliche-perspektiven-auf-instanzen-sozialer-kontrolle/">"Sozialwissenschaftliche Perspektiven auf Instanzen Sozialer Kontrolle": Polizeiliches Theater als Präventionslogik</a></li>
</ul>

<h2>2023</h2>

<h3>January</h3>
<ul>
    <li>12.01.2022, Hamburg: <a target="_blank" href="https://criminologia.de/2022/09/vortragsreihe-sozialwissenschaftliche-perspektiven-auf-instanzen-sozialer-kontrolle/">"Sozialwissenschaftliche Perspektiven auf Instanzen Sozialer Kontrolle": Protest Policing</a></li>
</ul>

<h3>February</h3>
<ul>
    <li>13.-14.2.2023, ONLINE: <a target="_blank" href="https://www.dvjj.de/veranstaltung/psychische-stoerungen-in-haft-bzw-unter-straftaeterinnen-online-2/">DVJJ-Seminar: Psychische Störungen in Haft bzw. unter StraftäterInnen I</a></li>
    <li>15.02.2022, Hamburg: <a target="_blank" href="https://criminologia.de/2022/09/vortragsreihe-sozialwissenschaftliche-perspektiven-auf-instanzen-sozialer-kontrolle/">"Sozialwissenschaftliche Perspektiven auf Instanzen Sozialer Kontrolle": Femizid – Bedeutung und Nutzen für die strafrechtliche Normgenese bei Gewalt gegen Frauen im sozialen Nahraum</a></li>
    <li>23.-24.2.2023, ONLINE: <a target="_blank" href="https://www.dvjj.de/veranstaltung/zusammenhaenge-zwischen-entwicklungstraumatisierungen-und-gewaltstraftaten-online-2/">DVJJ-Seminar: Zusammenhänge zwischen Entwicklungstraumatisierungen und Gewaltstraftaten I</a></li>
</ul>

<h3>September</h3>
<ul>
    <li>6.-9.9.2023, Florence (Italy): <a target="_blank" href="https://www.esc-eurocrim.org/index.php/conferences/upcoming-conferences">EUROCRIM 2023: The 23rd Annual Conference of the European Society of Criminology</a></li>
    <li>15.-18.9.2023, Berlin: <a target="_blank" href="https://www.dvjj.de/veranstaltung/32-deutscher-jugendgerichtstag-2023/">DVJJ Fachtagung: 32. Deutscher Jugendgerichtstag 2023</a></li>
</ul>
