<h2>Congresses and conferences</h2>

<h2>2023</h2>

<h3>February</h3>
<ul>
    <li>23.-24.2.2023, ONLINE: <a target="_blank" href="https://www.dvjj.de/veranstaltung/zusammenhaenge-zwischen-entwicklungstraumatisierungen-und-gewaltstraftaten-online-2/">DVJJ-Seminar: Zusammenhänge zwischen Entwicklungstraumatisierungen und Gewaltstraftaten I</a></li>
</ul>

<h3>April</h3>
<ul>
    <li>27.-28.04.2023, Heidelberg: <a target="_blank" href="https://www.dbh-online.de/sites/default/files/seminare/attachments/b-2223ausschreibung.pdf">"Seminar: Desistance from Crime - Ausstieg aus kriminellen Karrieren</a></li>
</ul>

<h3>May</h3>
<ul>
    <li>31.05-02.06.2023, Greifswald: <a target="_blank" href="https://rsf.uni-greifswald.de/storages/uni-greifswald/fakultaet/rsf/lehrstuehle/ls-harrendorf/Einladung_und_Call_for_Papers_NORDKRIM_2023.pdf">NORDKRIM 2023: Tagung des Norddeutschen Kriminologischen Gesprächskreises</a></li>
</ul>

<h3>June</h3>
<ul>
    <li>12.-13.06.2023, Mannheim: <a target="_blank" href="https://www.praeventionstag.de/nano.cms/international">Deutscher Präventionstag - Krisen & Prävention</a></li>
</ul>

<h3>September</h3>
<ul>
    <li>6.-9.9.2023, Florence (Italy): <a target="_blank" href="https://www.esc-eurocrim.org/index.php/conferences/upcoming-conferences">EUROCRIM 2023: The 23rd Annual Conference of the European Society of Criminology</a></li>
    <li>14.-15.9.2023, Nuremberg: <a target="_blank" href="https://www.dvjj.de/veranstaltung/sexualisierte-uebergriffe-an-kindern-und-jugendlichen-umgang-und-arbeit-mit-sexualisiert-gewalttaetigen-jugendlichen-und-jungen-maennern-nuernberg-3/">Sexualisierte Übergriffe an Kindern und Jugendlichen: Umgang und Arbeit mit sexualisiert gewalttätigen Jugendlichen und jungen Männern</a></li>
    <li>15.-18.9.2023, Berlin: <a target="_blank" href="https://www.dvjj.de/veranstaltung/32-deutscher-jugendgerichtstag-2023/">DVJJ Fachtagung: 32. Deutscher Jugendgerichtstag 2023</a></li>
    <li>25.-26.9.2023, ONLINE: <a target="_blank" href="https://www.dvjj.de/veranstaltung/psychische-stoerungen-in-haft-bzw-unter-straftaeterinnen-ii-online/">Psychische Störungen in Haft bzw. unter StraftäterInnen II</a></li>
    <li>28.-29.9.2023, ONLINE: <a target="_blank" href="https://www.dvjj.de/veranstaltung/zusammenhaenge-zwischen-entwicklungstraumatisierungen-und-gewaltstraftaten-ii-online/">Zusammenhänge zwischen Entwicklungstraumatisierungen und Gewaltstraftaten</a></li>
</ul>

<h3>November</h3>
<ul>
    <li>15.-18.11.2023, Philadelphia (Pennsylvania): <a target="_blank" href="https://asc41.com/#av_section_2">2023 American Society of Criminology Annual Meeting: "Seeking Justice: Reconciling with our Past, Reimagining the Future" </a></li>
</ul>


<h2>2024</h2>

<h3>September</h3>
<ul>
    <li>11.-14.09.2024, Bucharest (Romania): <a target="_blank" href="https://www.esc-eurocrim.org/index.php/conferences/upcoming-conferences">EUROCRIM 2024: 24. Annual Conference of the European Society of Criminology</a></li>
	<li>26.-28.09.2024, Tübingen: <a target="_blank" href="http://www.krimg.de/drupal/node/3"> 18. Wissenschaftliche Fachtagung der Kriminologischen Gesellschaft: „Am Puls der Zeit?! Trends, Transfer und Tradition in der Kriminologie“</a></li>
</ul>