<h2>Congresses and conferences</h2>

<h2>2023</h2>

<h3>November</h3>
<ul>
    <li>03.11.2023, Berlin: <a target="_blank" href="https://protestinstitut.eu/wp-content/uploads/2022/08/CfP_2023_The-policing-of-everyday-resistance_eng.pdf">Jahrestagung des AK Soziale Bewegungen und Polizei: "Policing von Widerstand im Alltag“</a></li>
	<li>15.-18.11.2023, Philadelphia (Pennsylvania): <a target="_blank" href="https://asc41.com/#av_section_2">2023 American Society of Criminology Annual Meeting: "Seeking Justice: Reconciling with our Past, Reimagining the Future" </a></li>
	<li>17.-18.11.2023, Hanover: <a target="_blank" href="https://soziologie.de/fileadmin/sektionen/soziale-probleme-und-soziale-kontrolle/Programme/Sek_SozProbKontr_Programm_Jahrestagung_2023.pdf">Jahrestagung der DGS-Sektion „Soziale Probleme und Soziale Kontrolle“: „Alles neu!? Problemsoziologische Perspektiven auf Semantiken und Praktiken sozialer Innovation und Transformation“</a></li>
	<li>23.11.2023, HAW Hamburg: <a target="_blank" href="https://criminologia.de/wp-content/uploads/2023/10/Perspektiven-der-Kriminologie.png">Vortragsreihe: Perspektiven der Kriminologie – „Resozialisierung ja, aber bitte nicht für alle!“</a></li>
	<li>27.11.2023, Limburg: <a target="_blank" href="https://www.dbh-online.de/sites/default/files/seminare/attachments/b-4623_ausschreibung.pdf">DBH Seminar: Umgang mit Gewaltstraftätern (Anmeldefrist: 15.10.23)</a></li>
</ul>

<h3>Dezember</h3>
<ul>
	<li>23.11.2023, Akademie der Polizei Hamburg: <a target="_blank" href="https://criminologia.de/wp-content/uploads/2023/10/Perspektiven-der-Kriminologie.png">Vortragsreihe: Perspektiven der Kriminologie – „Genau hinsehen, geduldig nachdenken und sich nicht dumm machen lassen“. 36 Jahre Forschung über Polizei – eine subjektive Zwischenbilanz (Öffentliche Abschiedsvorlesung)</a></li>
</ul>

<h2>2024</h2>

<h3>Januar</h3>
<ul>
	<li>31.01.2024, Universität Hamburg: <a target="_blank" href="https://criminologia.de/wp-content/uploads/2023/10/Perspektiven-der-Kriminologie.png">Vortragsreihe: Perspektiven der Kriminologie – 100 Jahre Liselotte Pongratz | „Am Mädchen arbeiten – intersektionale Betrachtungen von Geschlecht im Zwangskontext“</a></li>
</ul>

<h3>February</h3>
<ul>
	<li>02.02.2024, ONLINE: <a target="_blank" href="https://www.dvjj.de/veranstaltung/restorative-justice-mit-jugendlichen-taeter-opfer-ausgleich-im-jgg-online-2/">DVJJ-Online: Restorative Justice mit Jugendlichen – Täter-Opfer-Ausgleich im JGG</a></li>
	<li>19.-20.02.2024, ONLINE: <a target="_blank" href="https://www.dvjj.de/veranstaltung/psychische-stoerungen-in-haft-bzw-unter-straftaeterinnen-online-3/">DVJJ-Online: Psychische Störungen in Haft bzw. unter StraftäterInnen</a></li>
	<li>22.-23.02.2024, ONLINE: <a target="_blank" href="https://www.dvjj.de/veranstaltung/zusammenhaenge-zwischen-entwicklungstraumatisierungen-und-gewaltstraftaten-online-3/">DVJJ-Online: Zusammenhänge zwischen Entwicklungstraumatisierungen und Gewaltstraftaten</a></li>
</ul>

<h3>March</h3>
<ul>
    <li>13.-14.03.2024, Zwickau: <a target="_blank" href="https://www.opferhilfe-sachsen.de/verein/fachtagungen/fachtagung-gewalt-an-menschen-mit-kognitiven-behinderungen/">Fachtagung: Gewalt an Menschen mit kognitiven Behinderungen. Erkennen - Handeln - Begleiten</a></li>
</ul>

<h3>September</h3>
<ul>
    <li>11.-14.09.2024, Bucharest (Romania): <a target="_blank" href="https://www.esc-eurocrim.org/index.php/conferences/upcoming-conferences">EUROCRIM 2024: 24. Annual Conference of the European Society of Criminology</a></li>
	<li>26.-28.09.2024, Tübingen: <a target="_blank" href="http://www.krimg.de/drupal/node/3"> 18. Wissenschaftliche Fachtagung der Kriminologischen Gesellschaft: „Am Puls der Zeit?! Trends, Transfer und Tradition in der Kriminologie“</a></li>
</ul>

<h3>October</h3>
<ul>
	<li>07.-08.10.2024, Nürnberg: <a target="_blank" href="https://www.dvjj.de/veranstaltung/sexualisierte-uebergriffe-an-kindern-und-jugendlichen-umgang-und-arbeit-mit-sexualisiert-gewalttaetigen-jugendlichen-und-jungen-maennern-nuernberg-4/">DVJJ-Seminar: Sexualisierte Übergriffe an Kindern und Jugendlichen: Umgang und Arbeit mit sexualisiert gewalttätigen Jugendlichen und jungen Männern</a></li>
</ul>