<h2>Congresses and conferences</h2>

<h2>2023</h2>

<h3>January</h3>
<ul>
    <li>12.01.2023, Hamburg: <a target="_blank" href="https://criminologia.de/2022/09/vortragsreihe-sozialwissenschaftliche-perspektiven-auf-instanzen-sozialer-kontrolle/">"Sozialwissenschaftliche Perspektiven auf Instanzen Sozialer Kontrolle": Protest Policing</a></li>
</ul>

<h3>February</h3>
<ul>
    <li>13.-14.2.2023, ONLINE: <a target="_blank" href="https://www.dvjj.de/veranstaltung/psychische-stoerungen-in-haft-bzw-unter-straftaeterinnen-online-2/">DVJJ-Seminar: Psychische Störungen in Haft bzw. unter StraftäterInnen I</a></li>
    <li>15.02.2023, Hamburg: <a target="_blank" href="https://criminologia.de/2022/09/vortragsreihe-sozialwissenschaftliche-perspektiven-auf-instanzen-sozialer-kontrolle/">"Sozialwissenschaftliche Perspektiven auf Instanzen Sozialer Kontrolle": Femizid – Bedeutung und Nutzen für die strafrechtliche Normgenese bei Gewalt gegen Frauen im sozialen Nahraum</a></li>
    <li>23.-24.2.2023, ONLINE: <a target="_blank" href="https://www.dvjj.de/veranstaltung/zusammenhaenge-zwischen-entwicklungstraumatisierungen-und-gewaltstraftaten-online-2/">DVJJ-Seminar: Zusammenhänge zwischen Entwicklungstraumatisierungen und Gewaltstraftaten I</a></li>
</ul>

<h3>April</h3>
<ul>
    <li>27.-28.04.2023, Heidelberg: <a target="_blank" href="https://www.dbh-online.de/sites/default/files/seminare/attachments/b-2223ausschreibung.pdf">"Seminar: Desistance from Crime - Ausstieg aus kriminellen Karrieren</a></li>
</ul>

<h3>September</h3>
<ul>
    <li>6.-9.9.2023, Florence (Italy): <a target="_blank" href="https://www.esc-eurocrim.org/index.php/conferences/upcoming-conferences">EUROCRIM 2023: The 23rd Annual Conference of the European Society of Criminology</a></li>
    <li>14.-15.9.2023, Nuremberg: <a target="_blank" href="https://www.dvjj.de/veranstaltung/sexualisierte-uebergriffe-an-kindern-und-jugendlichen-umgang-und-arbeit-mit-sexualisiert-gewalttaetigen-jugendlichen-und-jungen-maennern-nuernberg-3/">Sexualisierte Übergriffe an Kindern und Jugendlichen: Umgang und Arbeit mit sexualisiert gewalttätigen Jugendlichen und jungen Männern</a></li>
    <li>15.-18.9.2023, Berlin: <a target="_blank" href="https://www.dvjj.de/veranstaltung/32-deutscher-jugendgerichtstag-2023/">DVJJ Fachtagung: 32. Deutscher Jugendgerichtstag 2023</a></li>
    <li>25.-26.9.2023, ONLINE: <a target="_blank" href="https://www.dvjj.de/veranstaltung/psychische-stoerungen-in-haft-bzw-unter-straftaeterinnen-ii-online/">Psychische Störungen in Haft bzw. unter StraftäterInnen II</a></li>
    <li>28.-29.9.2023, ONLINE: <a target="_blank" href="https://www.dvjj.de/veranstaltung/zusammenhaenge-zwischen-entwicklungstraumatisierungen-und-gewaltstraftaten-ii-online/">Zusammenhänge zwischen Entwicklungstraumatisierungen und Gewaltstraftaten</a></li>
</ul>
