<h2>Konferenzen, Tagungen und Veranstaltungen</h2>

<h2>2023</h2>

<h3>Juli</h3>
<ul>
    <li>06.-08.07.2023, Augsburg: <a target="_blank" href="https://www.uni-augsburg.de/de/fakultaet/jura/lehrende/kaspar/kolloquium58/#:~:text=Inhalt-,Vom%206.,Gast%20und%20wird%20von%20Prof.">58. Kolloquium der Südwestdeutschen und Schweizerischen Kriminologischen Institute und Lehrstühle</a></li>
	<li>20.-21.07.2023, Lissabon (Portugal): <a target="_blank" href="https://societyforterrorismresearch.org/conferences/15th-annual-international-conference">15th Annual International Conference: Terrorism Research in a Polarized World</a></li>
</ul>

<h3>August</h3>
<ul>
    <li>30.08.-01.09.2023, Trondheim (Norwegien): <a target="_blank" href="https://www.iatso.org/index.php/trondheim-2022">International Association for the Treatment of Sexual Offenders (IATSO): Sex offender treatment in a lifespan perspective – New challenges from social media and from children and adolescents with harmful sexual behavior</a></li>
</ul>

<h3>September</h3>
<ul>
    <li>6.-9.9.2023, Florenz (Italien): <a target="_blank" href="https://www.esc-eurocrim.org/index.php/conferences/upcoming-conferences">EUROCRIM 2023: 23. Annual Conference of the European Society of Criminology</a></li>
	<li>13.-15.9.2023, Offenbach a. M.: <a target="_blank" href="http://www.fh-guestrow.de/files/dateien/forschung/call_tagung_empirische_polizeiforschung_2023.pdf">Arbeitskreis Empirische Polizeiforschung Jahrestagung 2023: Polizei und Forschung: Stillstand oder Fortschritt?</a></li>
    <li>14.-15.9.2023, Nürnberg: <a target="_blank" href="https://www.dvjj.de/veranstaltung/sexualisierte-uebergriffe-an-kindern-und-jugendlichen-umgang-und-arbeit-mit-sexualisiert-gewalttaetigen-jugendlichen-und-jungen-maennern-nuernberg-3/">Sexualisierte Übergriffe an Kindern und Jugendlichen: Umgang und Arbeit mit sexualisiert gewalttätigen Jugendlichen und jungen Männern</a></li>
    <li>15.-18.9.2023, Berlin: <a target="_blank" href="https://www.dvjj.de/veranstaltung/32-deutscher-jugendgerichtstag-2023/">DVJJ Fachtagung: 32. Deutscher Jugendgerichtstag 2023</a></li>
	<li>20.-22.9.2023, Mannheim: <a target="_blank" href="https://www.dbh-online.de/aktuelles/18-forum-fuer-taeter-opfer-ausgleich-und-restorative-justice#:~:text=Das%2018.,sozialen%20Frieden%22%20in%20Mannheim%20statt.">18. Forum für Täter-Opfer-Ausgleich und Restorative Justice: "Miteinander in Verbindung treten: Gemeinsam für Menschlichkeit, Gerechtigkeit und sozialen Frieden"</a></li>
    <li>25.-26.9.2023, ONLINE: <a target="_blank" href="https://www.dvjj.de/veranstaltung/psychische-stoerungen-in-haft-bzw-unter-straftaeterinnen-ii-online/">Psychische Störungen in Haft bzw. unter StraftäterInnen II</a></li>
    <li>28.-29.9.2023, ONLINE: <a target="_blank" href="https://www.dvjj.de/veranstaltung/zusammenhaenge-zwischen-entwicklungstraumatisierungen-und-gewaltstraftaten-ii-online/">Zusammenhänge zwischen Entwicklungstraumatisierungen und Gewaltstraftaten</a></li>
</ul>

<h3>Oktober</h3>
<ul>
    <li>05.-06.10.2023, Wiesbaden: <a target="_blank" href="https://www.krimz.de/tagungen/fachtagung-2023.html">KrimZ Fachtagung: Das Internet als Tatort</a></li>
</ul>

<h3>November</h3>
<ul>
    <li>03.11.2023, Berlin: <a target="_blank" href="https://protestinstitut.eu/wp-content/uploads/2022/08/Call-for-Papers_Policing-von-Widerstand-im-Alltag_de.pdf">Jahrestagung des AK Soziale Bewegungen und Polizei: "Policing von Widerstand im Alltag“</a></li>
	<li>15.-18.11.2023, Philadelphia (Pennsylvania): <a target="_blank" href="https://asc41.com/#av_section_2">2023 American Society of Criminology Annual Meeting: "Seeking Justice: Reconciling with our Past, Reimagining the Future" </a></li>
	<li>27.11.2023, Limburg: <a target="_blank" href="https://www.dbh-online.de/sites/default/files/seminare/attachments/b-4623_ausschreibung.pdf">DBH Seminar: Umgang mit Gewaltstraftätern (Anmeldefrist: 15.10.23)</a></li>
</ul>

<h2>2024</h2>

<h3>September</h3>
<ul>
    <li>11.-14.09.2024, Bukarest (Rumänien): <a target="_blank" href="https://www.esc-eurocrim.org/index.php/conferences/upcoming-conferences">EUROCRIM 2024: 24. Annual Conference of the European Society of Criminology</a></li>
	<li>26.-28.09.2024, Tübingen: <a target="_blank" href="http://www.krimg.de/drupal/node/3"> 18. Wissenschaftliche Fachtagung der Kriminologischen Gesellschaft: „Am Puls der Zeit?! Trends, Transfer und Tradition in der Kriminologie“</a></li>
</ul>