<h2>Konferenzen, Tagungen und Veranstaltungen</h2>
<h2>2025</h2>
<h3>März</h3>
<ul>
    <li>20.-21.03.2025, Bielefeld: <a target="_blank" href="https://aktuell.uni-bielefeld.de/event/narratives-in-of-criminology/">Workshop: Narratives in/of Criminology</a></li>
    <li>28.03.2025, Tübingen: <a target="_blank" href="https://baden-wuerttemberg.dvjj.de/jahrestagungen/">DVJJ Jahrestagung 2025: "Fly high: zwischen Rausch und Realität – Substanzmissbrauch durch Jugendliche"</a></li>
</ul>
<h3>April</h3>
<ul>
    <li>02.04.2025, Online: <a target="_blank" href="https://www.hspv.nrw.de/nachrichten/artikel/ringvorlesung-migration-im-fokus-2025">Digitale Ringvorlesung, Migration im Fokus: "Migration managen: Die Rolle der öffentlichen Verwaltung im Integrationsprozess"</a></li>
    <li>28.-30.04.2025, Oranienburg: <a target="_blank" href="https://www.hwr-berlin.de/aktuelles/veranstaltungen/veranstaltung-detail/1213-erfolgreich-vernehmen-die-untersuchende-vernehmung-als-effektive-und-menschenrechtskonforme-polizeipraxis/">Fachtagung: Erfolgreich Vernehmen - Die untersuchende Vernehmung als effektive und menschenrechtskonforme Polizeipraxis</a></li>
</ul>
<h3>Mai</h3>
<ul>
    <li>08.05.2025, Online: <a target="_blank" href="https://www.hspv.nrw.de/nachrichten/artikel/ringvorlesung-migration-im-fokus-2025">Digitale Ringvorlesung, Migration im Fokus: "Identitätsanker oder Traditionsabbruch? Migration und religiöser Wandel"</a></li>
    <li>09.-10.05.2025, Abtei Maria Laach: <a target="_blank" href="https://www.konfliktforscher.de/symposium-2025/">52. Symposium 2025: "Psychiatrie-Enquete auf Wiedervorlage - Integration – Rechtssicherheit – Alternativen: Alles unter Kontrolle?"</a></li>
    <li>15.-16.05.2025, Freiburg: <a target="_blank" href="https://strafrechtskalender.de/wp-content/uploads/2025/02/2025-02-17-ImpleMendez-Tagung-Programm-final.pdf">Fachtagung: Leitlinien für effektive und faire Vernehmungen in Strafverfahren"</a></li>
    <li>19.-21.05.2025, Jena: <a target="_blank" href="https://strafrechtskalender.de/tag/zeitwende-im-strafecht/">Jenaer Feuerbachtagung 2025: "Eine Zeitenwende im Strafrecht: Paul Johann Anselm von Feuerbach. Theorie und Dogmatik, Kriminologie und Kriminalpolitik, Geschichte und Rezeption"</a></li>
    <li>20.05.2025, Leonberg: <a target="_blank" href="https://seehaus-ev.de/sh/fachtag-opferhilfe/">Fachtag Opferhilfe: Rechte und Ansprüche von Opfern</a></li>
    <li>28.-29.05.2025, Prag (Tschechien): <a target="_blank" href="https://law.prf.cuni.cz/custody/">International Seminar: "Who Goes to Prison: International Developments in Structuring and Restricting the Use of Custody"</a></li>
    <li>30.05.2025, Dresden: <a target="_blank" href="https://www.forensik-dresden.de/">28. Dresdner Forensische Frühjahrstagung: "Biographie und Pathographie als Erkenntnisquelle – Methoden und Geschichte(n)"</a></li>
</ul>
<h3>Juni</h3>
<ul>
    <li>02.06.2025, Online: <a target="_blank" href="https://www.hspv.nrw.de/nachrichten/artikel/ringvorlesung-migration-im-fokus-2025">Digitale Ringvorlesung, Migration im Fokus: "Migration als Sicherheitsproblem? Einfluss von Migration auf Kriminalitätsdynamiken"</a></li>
    <li>09.-11.06.2025, Stockholm (Schweden): <a target="_blank" href="https://criminologysymposium.com/event.html">The Stockholm Criminology Symposium</a></li>
    <li>19.-22.06.2025, Delhi (Indien): <a target="_blank" href="https://mcusercontent.com/9a8b294cb6aa3caf7434ee8af/files/4fcf01c5-a71c-d161-a20c-043f7f47ad9b/1_International_Criminology_Conference_March_2025_CfP_08_2023.pdf">World Conference on Criminology: "Exploring the Dynamics of Crime: Contemporary Challenges and Innovations in Crime Prevention and Criminal Justice"</a></li>
    <li>23.-24.06.2025, Augsburg: <a target="_blank" href="www.praeventionstag.de/30">30. Deutscher Präventionstag: Prävention & gesellschaftlicher Frieden</a></li>
    <li>26.-28.06.2025, St. Gallen: <a target="_blank" href="https://www.unisg.ch/de/universitaet/schools/law/forschung/sk-hsg/tagungen-weiterbildungen-und-veranstaltungen/">60. Kolloquium der Südwestdeutschen und Schweizerischen Kriminologischen Institute und Lehrstühle</a></li>
</ul>
<h3>Juli</h3>
<ul>
    <li>01.-04.07.2025, Portsmouth (UK): <a target="_blank" href="https://www.port.ac.uk/news-events-and-blogs/events/british-society-of-criminology-conference-2025">2025 British Society of Criminology Conference: "Criminology for Social Justice"</a></li>
</ul>
<h3>August</h3>
<ul>
    <li>31.08-02.09.2025, Passau: <a target="_blank" href="https://iibsa.org/events/conference-in-passau-hate-in-transition-and-the-aftermath-of-7-october-antisemitism-and-racism-in-times-of-political-crisis/">International Conference: "Hate in Transition and the Aftermath of 7 October: Antisemitism and Racism in Times of Political Crisis"</a></li>
</ul>
<h3>September</h3>
<ul>
    <li>03.-06.09.2025, Athen: <a target="_blank" href="https://esc-eurocrim.org/v2/upcoming-conferences/">EUROCRIM 2025: 25. Annual Conference of the European Society of Criminology</a></li>
</ul>
<h3>Oktober</h3>
<ul>
    <li>13.-14.10.2025, Freiburg: <a target="_blank" href="https://kriminalistik.com/jahrestagung-2025/">Jahrestagung 2025 der Deutschen Gesellschaft für Kriminalistik: "Facetten der nationalen und internationalen Kriminalitätskontrolle"</a></li>
    <li>27.-29.10.2025, Potsdam: <a target="_blank" href="https://www.dhs-fachkonferenz.de/">DHS Fachkonferenz SUCHT 2025: "Schnittstellen im Hilfesystem verbessern"</a></li>
</ul>
<h3>November</h3>
<ul>
    <li>12.-15.11.2025, Washington D.C. (USA): <a target="_blank" href="https://asc41.org/events/">2025 ASC Annual Meeting: Criminology, Law and, The Democratic Ideal</a></li>
</ul>
<h3>Dezember</h3>
<ul>
    <li>01.-03.12.2025, Brisbane (Australia): <a target="_blank" href="https://anzsoc.org/events/">2025 ANZSOC Conference</a></li>
</ul>
<h2>2026</h2>
<h3>September</h3>
<ul>
    <li>09.-12.09.2026, Warschau (Polen): <a target="_blank" href="https://esc-eurocrim.org/v2/upcoming-conferences/">EUROCRIM 2026: 26. Annual Conference of the European Society of Criminology</a></li>
</ul>
<h3>November</h3>
<ul>
    <li>18.-21.11.2026, Chicago, IL (USA): <a target="_blank" href="https://asc41.org/events/">2026 ASC Annual Meeting</a></li>
</ul>
<h2>2027</h2>
<h3>September</h3>
<ul>
    <li>15.-18.09.2027, Skopje (Nordmazedonien): <a target="_blank" href="https://esc-eurocrim.org/v2/upcoming-conferences/">EUROCRIM 2027: 27. Annual Conference of the European Society of Criminology</a></li>
</ul>
<h3>November</h3>
<ul>
    <li>17.-20.11.2027, Dallas, TX (USA): <a target="_blank" href="https://asc41.org/events/">2027 ASC Annual Meeting</a></li>
</ul>
<h2>2028</h2>
<h3>August</h3>
<ul>
    <li>30.08-02.09.2028, Dublin (Irland): <a target="_blank" href="https://esc-eurocrim.org/v2/upcoming-conferences/">EUROCRIM 2028: 28. Annual Conference of the European Society of Criminology</a></li>
</ul>
<h3>November</h3>
<ul>
    <li>15.-18.11.2028, New Orleans, LA (USA): <a target="_blank" href="https://asc41.org/events/">2028 ASC Annual Meeting</a></li>
</ul>
<h2>2029</h2>
<h3>November</h3>
<ul>
    <li>14.-17.11.2029, Philadelphia, PA (USA): <a target="_blank" href="https://asc41.org/events/">2029 ASC Annual Meeting</a></li>
</ul>
<h2>2030</h2>
<h3>November</h3>
<ul>
    <li>20.-23.11.2030, San Francisco, CA (USA): <a target="_blank" href="https://asc41.org/events/">2030 ASC Annual Meeting</a></li>
</ul>
<h2>2031</h2>
<h3>November</h3>
<ul>
    <li>12.-15.11.2031, Washington, D.C. (USA): <a target="_blank" href="https://asc41.org/events/">2031 ASC Annual Meeting</a></li>
</ul>
<h2>2032</h2>
<h3>November</h3>
<ul>
    <li>17.-20.11.2032, Chicago, IL (USA): <a target="_blank" href="https://asc41.org/events/">2032 ASC Annual Meeting</a></li>
</ul>
<h2>2033</h2>
<h3>November</h3>
<ul>
    <li>16.-19.11.2033, Washington, D.C. (USA): <a target="_blank" href="https://asc41.org/events/">2033 ASC Annual Meeting</a></li>
</ul>
<h2>2034</h2>
<h3>November</h3>
<ul>
    <li>14.-18.11.2034, New Orleans, LA (USA): <a target="_blank" href="https://asc41.org/events/">2034 ASC Annual Meeting</a></li>
</ul>
<h2>2035</h2>
<h3>November</h3>
<ul>
    <li>13.-17.11.2035, Chicago, IL (USA): <a target="_blank" href="https://asc41.org/events/">2035 ASC Annual Meeting</a></li>
</ul>
<h2>2036</h2>
<h3>November</h3>
<ul>
    <li>19.-22.11.2036, San Francisco, CA (USA): <a target="_blank" href="https://asc41.org/events/">2036 ASC Annual Meeting</a></li>
</ul>
<h2>2039</h2>
<h3>November</h3>
<ul>
    <li>16.-20.11.2039, Chicago, IL (USA): <a target="_blank" href="https://asc41.org/events/">2039 ASC Annual Meeting</a></li>
</ul>