<h2>Reuniones y conferencias</h2>
<h2>2026</h2>
<h3>Febrero</h3>
<ul>
    <li>27.02.2026, En Línea: <a target="_blank" href="https://teams.microsoft.com/meet/38589141004722?p=jQYhNOsjD4Vc18xrqN">Research for Justice - "Cultural rights and Wrongs in Transitional Justice"</a> (Teams Lecture: 11am GMT) by Dr Colin Luoma (Brunel University of London)</li>
</ul>
<h3>Marzo</h3>
<ul>
   <li>03.-07.03.2026, Philadelphia, PA (Estados Unidos): <a target="_blank" href="https://www.acjs.org/annual-meeting/">The Academy of Criminal Justice Sciences (ACJS) 63rd Annual Meeting</a></li>
    <li>04.-05.03.2026, Wiesbaden (Alemania): <a target="_blank" href="https://www.motra.info/motra-k-26/">Jahreskonferenz des Verbundprojekts MOTRA: Extremismus/Radikalisierung/Prävention</a></li>
    <li>11.-13.03.2026, Burnaby (Canadá): <a target="_blank" href="">23rd Workshop of the Eurogang Program of Research</a></li>
    <li>12.-13.03.2026, Göttingen (Alemania): <a target="_blank" href="https://genderandcrime.kfn.de/english/">Gender & Crime conference - Gender in the Context of social polarisation</a></li>
    <li>13.03.2026, En Línea: <a target="_blank" href="https://teams.microsoft.com/meet/37431446670159?p=Aqptl4gc3cjvL73MeT">Research for Justice - "Lessons from the Global South in Criminal damage and the Sycamore Gap Tree"</a> (Teams Lecture: 11am GMT) by Dr Patrizia Hobbs (Brunel University of London)</li>
    <li>13.-14.03.2026, Lucern (Suiza): <a target="_blank" href="https://www.unilu.ch/en/events/13-law-and-economics-tagung-luzern-law-and-economics-of-crime-and-punishment-9422/">13th Law and Economics Conference: Law and Economics of Crime and Punishment</a></li>   
    <li>17.-18.03.2026, Canberra (Australia):<a target="_blank" href="https://www.trybooking.com/events/landing/1426117">AIC 2026 Conference: Transnational serious & organised crime</a></li>
    <li>19.-20.03.2026, Bochum (Alemania): <a target="_blank" href="https://www.kriminologie-nrw.de/Start.html">7. Netzwerktagung Kriminologie in NRW: "Kriminologie im Dialog"</a></li>
    <li>23.03.2026, Barrie (Canadá): <a target="_blank" href="https://casrp.org/Conference/6636/ICCCJ/">International Conference on Criminology and Criminal Justice (ICCCJ)</a></li>
    <li>27.03.2026, En Línea: <a target="_blank" href="https://teams.microsoft.com/meet/33220675799121?p=pTSrwKgBaBjlhVek75">Resarch for Justice - "Empty Signifiers and Ideological Silences: A Thematic Content Analysis of Five U.S. Newspapers' Construction of Human Trafficking (2000-2020)"</a> (Teams Lecture: 11am GMT) by Dr Janine Burroughs (Brunel University London)</li>
</ul>
<h3>Abril</h3>
<ul>
    <li>09.-10.04.2026, Prag (República Checa): <a target="_blank" href="https://tact-forsed.eu/2025/10/07/call-for-papers-for-international-conference-organised-by-tact-forsed/">International Conference organised by TaCT-FoRSED: Engaging with Conspiracy Theories, Fostering Democracy: Dynamics, Drivers, and Defences</a></li>
    <li>13.-14.04.2026, Hannover (Alemania): <a target="_blank" href="https://www.praeventionstag.de/nano.cms/dpt-31">31. Deutscher Präventionstag: "KI in der Prävention"</a></li>
    <li>21.04.2026, Beaumont, TX (Estados Unidos): <a target="_blank" href="https://www.lamar.edu/arts-sciences/research-centers/death-penalty-studies/">Justice, Resilience & The Rule of Law: 4th International Conference</a></li>
    <li>24.04.2026, En Línea: <a target="_blank" href="https://teams.microsoft.com/meet/388209432996?p=kcAIAUqlJqhxlvU0Hb">Research for Justice - "The creative arts as children's rights approach within youth justice systems?"</a> (Teams Lecture: 11am GMT) by Dr Louise Forde (Brunel Univestiy of London)</li> 
    <li>25.-30.04.2026, Abu Dhabi (Emiratos Árabes Unidos)<a target="_blank" href="https://www.unodc.org/unodc/crimecongress/about.html">The United Nations Congress on Crime Prevention and Criminal Justice: Accelerating crime prevention, criminal justice and the rule of law: protecting people and planet and achieving the 2030 Agenda for Sustainable Development in the digital age</a></li>
    <li>28.-29.04.2026, Cambridge (Reino Unido): <a target="_blank" href="https://sites.google.com/view/phdcrimconferencecambridge">4th annual PhD student Conference – Critical Crossroad: A Criminology that Confronts</a></li>
</ul>
<h3>Mayo</h3>
<ul>
    <li>04.-06.05.2026, Graz (Austria): <a target="_blank" href="https://www.wu.ac.at/fileadmin/wu/d/i/sozio/Dateien_zu_News/CfA_Digital_Criminology_STS_Graz_final.pdf">The 24th Annual STS Conference Graz 2026 „Critical Issues in Science, Technology and Society Studies“</a></li>
    <li>05.-06.05.2026, Wiesbaden (Alemania): <a target="_blank" href="https://www.bka.de/DE/AktuelleInformationen/Publikationen/ForumKI/2026/forumKI2026_node.html">Forum KI: „Gewaltbereite Jugend: Was bewegt die Gesellschaft von morgen?</a></li>
    <li>13.-15.05.2026, Athen (Grecia): <a target="_blank" href="https://www.ibanet.org/conference-details/CONF2745">28th Annual Transnational Crime Conference</a></li>
    <li>18.-19.05.2026, London (Reino Unido): <a target="_blank" href="https://www.lse.ac.uk/social-policy/research/research-clusters/mannheim/studying-criminology-at-lse">Mannheim PhD Symposium 2026 - Mannheim Center for Criminology</a></li>
    <li>18.-21.05.2026, Dallas, TX (Estados Unidos): <a target="_blank" href="https://conferencecaw.org/registration-2026/">Conference on Crimes Against Women (CCAW)</a></li>
    <li>18.-30.05.2026, Dubrovnik (Croacia): <a target="_blank" href="https://www.balkan-criminology.eu/news/40th-course-on-victimology-victim-assistance-and-criminal-justice-announcement/">XL Postgraduate Course: Victimology, Victim Assistance and Criminal Justice</a></li>
    <li>25.-30.05.2026, Sofia (Bulgaria): <a target="_blank" href="https://iafs2026.com">24th Triennial Meeting of the International Association of Forensic Sciences (IAFS 2026)</a></li>
    <li>28.-29.05.2026, Regensburg (Alemania): <a target="_blank" href="https://krimdok.uni-tuebingen.de/krimdok_docs/True_Crime_Fernsehen_und_Medien.pdf">True Crime, Fernsehen und Medien - Workshop der AG Fernsehen der GfM und der Medienwissenschaft Regensburg</a></li>
</ul>
<h3>Junio</h3>
<ul>
    <li>09.06.2026, London (Reino Unido): <a target="_blank" href="https://www.modernising-justice.co.uk/pricing">Modernising Criminal Justice Conference</a></li>
    <li>08.-10-06-2026, Stockholm (Suecia): <a target="_blank" href="https://criminologysymposium.com/">The Stockholm Criminology Symposium</a></li>
    <li>10.-12.06.2026, Coruña (España): <target="_blank" href="https://forms.office.com/e/NG1gFjXXi3">The 1st Iberian / 15th Spanish Conference of Criminology</a></li>
    <li>25.-26.06.2026, Siegen (Alemania): <a target="_blank" href="https://www.uni-siegen.de/2025/tagung-praktiken-sozialer-kontrolle">Tagung: Praktiken sozialer Kontrolle in sozial-/pädagogischen Kontexten</a></li>
    <li>25.-27.06.2026, Staufen im Breisgau (Alemania): <a target="_blank" href="https://strafrecht-online.org/archiv/kriminologie-kolloquium/">61. Kolloquium der Südwestdeutschen und Schweizerischen Kriminologischen Institute und Lehrstühle</a></li>
</ul>
<h3>Julio</h3>
<ul>
    <li>07.-10.07.2026, Nottingham (Reino Unido): <a target="_blank" href="https://www.ntu.ac.uk/about-us/events/events/2026/7/british-society-of-criminology-conference-2026">British Society of Criminology Conference 2026: "Building Resilience and Hope into Criminology and Criminal Justice"</a></li>
</ul>
<h3>Agosto</h3>
<h3>Septiembre</h3>
<ul>
    <li>03.-05.09.2026, Bern (Suiza): <a target="_blank" href="https://www.krimg.de/drupal/index.php/de/node/179">19. Wissenschaftliche Fachtagung der Kriminologischen Gesellschaft: „Kriminologie in einer diversen Gesellschaft"</a></li>
    <li>09.-12.09.2026, Warschau (Bulgaria): <a target="_blank" href="https://esc-eurocrim.org/v2/upcoming-conferences/">EUROCRIM 2026: 26. Annual Conference of the European Society of Criminology</a></li>
    <li>16.-17.09.2026, Santiago (Chile): <a target="_blank" href="https://waset.org/criminal-law-criminology-and-police-science-conference-in-september-2026-in-santiago?utm_source=conferenceindex&utm_medium=referral&utm_campaign=listing">International Conference on Criminal Law, Criminology and Police Science</a></li>    
    <li>24.09.2026, Berlin (Alemania): <a target="_blank" href="https://zeitgeschichte-extreme-rechte.de/2026/01/27/cfp-demokratieschutz/">Tagung: Demokratieschutz durch Verbote? Möglichkeiten und Grenzen staatlicher Maßnahmen gegen die extreme Rechte</a></li>
</ul>
<h3>Octubre</h3>
<h3>Noviembre</h3>
<ul>
    <li>05.-07.11.2026, Siegen (Alemania): <a target="_blank" href="https://www.uni-siegen.de/2025/tagung-selektive-strafen">Gemeinsame Tagung des AK Historische Kriminalitätsforschung, der GiwK und des CiCS: "Selektive Strafen – Kontrolle, Kriminalität und Kriminalisierung im Blick von Historischer Kriminalitätsforschung und Kriminologie"</a></li>
    <li>18.-21.11.2026, Chicago, IL (Estados Unidos): <a target="_blank" href="https://asc41.org/events/">2026 ASC Annual Meeting</a></li>
</ul>
<h3>Diciembre</h3>
<h2>2027</h2>
<h3>Marzo</h3>
<ul>
    <li>30.03.-03.04.2027, Orlando, FL (Estados Unidos): <a target="_blank" href="https://www.acjs.org/future-annual-meetings-2/">The Academy of Criminal Justice Sciences (ACJS) 64th Annual Meeting</a></li>
</ul>
<h3>Junio</h3>
<ul>    
    <li>14.-18.06.2027, Montreal (Canadá): <a target="_blank" href="https://www.worldsocietyofvictimology.org/wsv-events/">World Society of Victimology: 19th International Symposium</a></li>
</ul>
<h3>Septiembre</h3>
<ul>
    <li>15.-18.09.2027, Skopje (Macedonia del Norte): <a target="_blank" href="https://esc-eurocrim.org/v2/upcoming-conferences/">EUROCRIM 2027: 27. Annual Conference of the European Society of Criminology</a></li>
</ul>
<h3>Noviembre</h3>
<ul>
    <li>17.-20.11.2027, Dallas, TX (Estados Unidos): <a target="_blank" href="https://asc41.org/events/">2027 ASC Annual Meeting</a></li>
</ul>
<h2>2028</h2>
<h3>Agosto</h3>
<ul>
    <li>30.08-02.09.2028, Dublin (Irlanda): <a target="_blank" href="https://esc-eurocrim.org/v2/upcoming-conferences/">EUROCRIM 2028: 28. Annual Conference of the European Society of Criminology</a></li>
</ul>
<h3>Noviembre</h3>
<ul>
    <li>15.-18.11.2028, New Orleans, LA (Estados Unidos): <a target="_blank" href="https://asc41.org/events/">2028 ASC Annual Meeting</a></li>
</ul>
<h2>2029</h2>
<h3>Noviembre</h3>
<ul>
    <li>14.-17.11.2029, Philadelphia, PA (Estados Unidos): <a target="_blank" href="https://asc41.org/events/">2029 ASC Annual Meeting</a></li>
</ul>
<h2>2030</h2>
<h3>Junio</h3>
<ul>    
    <li>06.2027, Montreal (Canadá): <a target="_blank" href="https://www.worldsocietyofvictimology.org/bid-2030/">World Society of Victimology: 20th International Symposium</a></li>
</ul>
<h3>Noviembre</h3>
<ul>
    <li>20.-23.11.2030, San Francisco, CA (Estados Unidos): <a target="_blank" href="https://asc41.org/events/">2030 ASC Annual Meeting</a></li>
</ul>
<h2>2031</h2>
<h3>Noviembre</h3>
<ul>
    <li>12.-15.11.2031, Washington, D.C. (Estados Unidos): <a target="_blank" href="https://asc41.org/events/">2031 ASC Annual Meeting</a></li>
</ul>
<h2>2032</h2>
<h3>Noviembre</h3>
<ul>
    <li>17.-20.11.2032, Chicago, IL (Estados Unidos): <a target="_blank" href="https://asc41.org/events/">2032 ASC Annual Meeting</a></li>
</ul>
<h2>2033</h2>
<h3>Noviembre</h3>
<ul>
    <li>16.-19.11.2033, Washington, D.C. (Estados Unidos): <a target="_blank" href="https://asc41.org/events/">2033 ASC Annual Meeting</a></li>
</ul>
<h2>2034</h2>
<h3>Noviembre</h3>
<ul>
    <li>14.-18.11.2034, New Orleans, LA (Estados Unidos): <a target="_blank" href="https://asc41.org/events/">2034 ASC Annual Meeting</a></li>
</ul>
<h2>2035</h2>
<h3>Noviembre</h3>
<ul>
    <li>13.-17.11.2035, Chicago, IL (Estados Unidos): <a target="_blank" href="https://asc41.org/events/">2035 ASC Annual Meeting</a></li>
</ul>
<h2>2036</h2>
<h3>Noviembre</h3>
<ul>
    <li>19.-22.11.2036, San Francisco, CA (Estados Unidos): <a target="_blank" href="https://asc41.org/events/">2036 ASC Annual Meeting</a></li>
</ul>
<h2>2039</h2>
<h3>Noviembre</h3>
<ul>
    <li>16.-20.11.2039, Chicago, IL (Estados Unidos): <a target="_blank" href="https://asc41.org/events/">2039 ASC Annual Meeting</a></li>
</ul>
