<h2>Congresses and Conferences</h2>
<h2>2025</h2>

<h3>December</h3>
<ul>
    <li>15.-16.12.2025, Vilnius (Litauen): <a target="_blank" href="https://blogs.helsinki.fi/fourepochsofviolence/news/">"Imperial Experiences in Family Violence: Crimes and Criminology in 19th–20th centuries."</a></li>
</ul>
<h2>2026</h2>
<h3>January</h3>
<ul>
    <li>08.01.2026, Online: <a target="_blank" href="https://rechtssoziologie.info/2025/07/23/werkstattgespraeche-recht-und-gesellschaft-3/">Werkstattgespräche – Recht und Gesellschaft: "Recht und Ohnmacht: Armut aus rechtssoziologischer Perspektive"</a></li>
</ul>
<h3>February</h3>
<ul>
    <li>05.02.2026, Online: <a target="_blank" href="https://rechtssoziologie.info/2025/07/23/werkstattgespraeche-recht-und-gesellschaft-3/">Werkstattgespräche – Recht und Gesellschaft: "Erziehen, Strafen, Diziplinieren? Eine ethnogragische Studie in der Berliner Jugenddiversion"</a></li>
</ul>
<h3>March</h3>
<ul>
    <li>03.-07.03.2026, Philadelphia, PA (USA): <a target="_blank" href="https://www.acjs.org/annual-meeting/">The Academy of Criminal Justice Sciences (ACJS) 63rd Annual Meeting</a></li>
    <li>04.-05.03.2026, Wiesbaden: <a target="_blank" href="https://www.motra.info/motra-k-26/">Jahreskonferenz des Verbundprojekts MOTRA: Extremismus/Radikalisierung/Prävention</a></li>
    <li>11.-13.03.2026, Burnaby (Kanada): <a target="_blank" href="">23rd Workshop of the Eurogang Program of Research</a></li>
    <li>19.-20.03.2026, Bochum: <a target="_blank" href="https://www.kriminologie-nrw.de/Start.html">7. Netzwerktagung Kriminologie in NRW: "Kriminologie im Dialog"</a></li>
    <li>23.03.2026, Barrie (Kanada): <a target="_blank" href="https://casrp.org/Conference/6636/ICCCJ/">International Conference on Criminology and Criminal Justice (ICCCJ)</a></li>
</ul>
<h3>April</h3>
<ul>
    <li>09.-10.04.2026, Prag (Tschechien): <a target="_blank" href="https://tact-forsed.eu/2025/10/07/call-for-papers-for-international-conference-organised-by-tact-forsed/">International Conference organised by TaCT-FoRSED: Engaging with Conspiracy Theories, Fostering Democracy: Dynamics, Drivers, and Defences</a></li>
    <li>13.-14.04.2026, Hannover: <a target="_blank" href="https://www.praeventionstag.de/nano.cms/dpt-31">31. Deutscher Präventionstag: "KI in der Prävention"</a></li>
</ul>
<h3>May</h3>
<ul>
    <li>18.-30.05.2026, Dubrovnik (Kroatien): <a target="_blank" href="https://www.balkan-criminology.eu/news/40th-course-on-victimology-victim-assistance-and-criminal-justice-announcement/">XL Postgraduate Course: Victimology, Victim Assistance and Criminal Justice</a></li>
    <li>25.-30.05.2026, Sofia (Bulgarien): <a target="_blank" href="https://iafs2026.com">24th Triennial Meeting of the International Association of Forensic Sciences (IAFS 2026)</a></li>
</ul>
<h3>June</h3>
<h3>July</h3>
<ul>
    <li>07.-10.07.2026, Nottingham (UK): <a target="_blank" href="https://www.ntu.ac.uk/about-us/events/events/2026/7/british-society-of-criminology-conference-2026">British Society of Criminology Conference 2026: "Building Resilience and Hope into Criminology and Criminal Justice"</a></li>
</ul>
<h3>August</h3>
<h3>September</h3>
<ul>
    <li>09.-12.09.2026, Warschau (Polen): <a target="_blank" href="https://esc-eurocrim.org/v2/upcoming-conferences/">EUROCRIM 2026: 26. Annual Conference of the European Society of Criminology</a></li>
</ul>
<h3>October</h3>
<h3>November</h3>
<ul>
    <li>05.-07.11.2026, Siegen: <a target="_blank" href="https://www.uni-siegen.de/2025/tagung-selektive-strafen">Gemeinsame Tagung des AK Historische Kriminalitätsforschung, der GiwK und des CiCS: "Selektive Strafen – Kontrolle, Kriminalität und Kriminalisierung im Blick von Historischer Kriminalitätsforschung und Kriminologie"</a></li>
    <li>18.-21.11.2026, Chicago, IL (USA): <a target="_blank" href="https://asc41.org/events/">2026 ASC Annual Meeting</a></li>
</ul>
<h3>December</h3>
<h2>2027</h2>
<h3>March</h3>
<ul>
    <li>30.03.-03.04.2027, Orlando, FL (USA): <a target="_blank" href="https://www.acjs.org/future-annual-meetings-2/">The Academy of Criminal Justice Sciences (ACJS) 64th Annual Meeting</a></li>
</ul>
<h3>September</h3>
<ul>
    <li>15.-18.09.2027, Skopje (Nordmazedonien): <a target="_blank" href="https://esc-eurocrim.org/v2/upcoming-conferences/">EUROCRIM 2027: 27. Annual Conference of the European Society of Criminology</a></li>
</ul>
<h3>November</h3>
<ul>
    <li>17.-20.11.2027, Dallas, TX (USA): <a target="_blank" href="https://asc41.org/events/">2027 ASC Annual Meeting</a></li>
</ul>
<h2>2028</h2>
<h3>August</h3>
<ul>
    <li>30.08-02.09.2028, Dublin (Irland): <a target="_blank" href="https://esc-eurocrim.org/v2/upcoming-conferences/">EUROCRIM 2028: 28. Annual Conference of the European Society of Criminology</a></li>
</ul>
<h3>November</h3>
<ul>
    <li>15.-18.11.2028, New Orleans, LA (USA): <a target="_blank" href="https://asc41.org/events/">2028 ASC Annual Meeting</a></li>
</ul>
<h2>2029</h2>
<h3>November</h3>
<ul>
    <li>14.-17.11.2029, Philadelphia, PA (USA): <a target="_blank" href="https://asc41.org/events/">2029 ASC Annual Meeting</a></li>
</ul>
<h2>2030</h2>
<h3>November</h3>
<ul>
    <li>20.-23.11.2030, San Francisco, CA (USA): <a target="_blank" href="https://asc41.org/events/">2030 ASC Annual Meeting</a></li>
</ul>
<h2>2031</h2>
<h3>November</h3>
<ul>
    <li>12.-15.11.2031, Washington, D.C. (USA): <a target="_blank" href="https://asc41.org/events/">2031 ASC Annual Meeting</a></li>
</ul>
<h2>2032</h2>
<h3>November</h3>
<ul>
    <li>17.-20.11.2032, Chicago, IL (USA): <a target="_blank" href="https://asc41.org/events/">2032 ASC Annual Meeting</a></li>
</ul>
<h2>2033</h2>
<h3>November</h3>
<ul>
    <li>16.-19.11.2033, Washington, D.C. (USA): <a target="_blank" href="https://asc41.org/events/">2033 ASC Annual Meeting</a></li>
</ul>
<h2>2034</h2>
<h3>November</h3>
<ul>
    <li>14.-18.11.2034, New Orleans, LA (USA): <a target="_blank" href="https://asc41.org/events/">2034 ASC Annual Meeting</a></li>
</ul>
<h2>2035</h2>
<h3>November</h3>
<ul>
    <li>13.-17.11.2035, Chicago, IL (USA): <a target="_blank" href="https://asc41.org/events/">2035 ASC Annual Meeting</a></li>
</ul>
<h2>2036</h2>
<h3>November</h3>
<ul>
    <li>19.-22.11.2036, San Francisco, CA (USA): <a target="_blank" href="https://asc41.org/events/">2036 ASC Annual Meeting</a></li>
</ul>
<h2>2039</h2>
<h3>November</h3>
<ul>
    <li>16.-20.11.2039, Chicago, IL (USA): <a target="_blank" href="https://asc41.org/events/">2039 ASC Annual Meeting</a></li>
</ul>
