<h2>Congresos y conferencias</h2>
<h2>2025</h2>
<h3>Febrero</h3>
<ul>
    <li>05.-07.02.2025, online: <a target="_blank" href="https://www.zentrum-fuer-kriminologie-polizeiforschung.de/images/template/ZKPF-Anmeldeformular.pdf">Seminar des Zentrum für Kriminologie und Polizeiforschung - Erwachsene Missbrauchstäter:innen & Missbrauchsabbildungen</a></li>
</ul>
<h3>Marzo</h3>
<ul>
    <li>06.-09.03.2025, Delhi (Indien): <a target="_blank" href="https://mcusercontent.com/9a8b294cb6aa3caf7434ee8af/files/4fcf01c5-a71c-d161-a20c-043f7f47ad9b/1_International_Criminology_Conference_March_2025_CfP_08_2023.pdf">World Conference on Criminology: "Exploring the Dynamics of Crime: Contemporary Challenges and Innovations in Crime Prevention and Criminal Justice"</a></li>
    <li>6.-7.03.2025, Interlaken (Schweiz): <a target="_blank" href="https://kriminologie.ch/files/SAK/pdf/Geschichtliche%20Dokumente/Tagungsunterlagen%202025/SAK_GSC_Broschur_Kongress_2025_web.pdf">Kongress 2025: Vom Scheiterhaufen zur Verwahrung - Umgang mit Minderheiten im Strafsystem</a></li>
    <li>13.-14.03.2025, Münster: <a target="_blank" href="https://www.kriminologie-nrw.de/Start.html#:~:text=Die%206.,an%20der%20Universität%20Münster%20stattfinden.">6. Netzwerktagung "Kriminologie in NRW"</a></li>
</ul>
<h3>Abril</h3>
<ul>
    <li>28.-30.04.2025, Oranienburg: <a target="_blank" href="https://www.hwr-berlin.de/aktuelles/veranstaltungen/veranstaltung-detail/1213-erfolgreich-vernehmen-die-untersuchende-vernehmung-als-effektive-und-menschenrechtskonforme-polizeipraxis/">Fachtagung: Erfolgreich Vernehmen - Die untersuchende Vernehmung als effektive und menschenrechtskonforme Polizeipraxis</a></li>
</ul>
<h3>Junio</h3>
<ul>
    <li>23.-24.06.2025, Augsburg: <a target="_blank" href="www.praeventionstag.de/30">30. Deutscher Präventionstag: Prävention & gesellschaftlicher Frieden</a></li>
    <li>26.-28.06.2025, St. Gallen: <a target="_blank" href="https://www.unisg.ch/de/universitaet/schools/law/forschung/sk-hsg/tagungen-weiterbildungen-und-veranstaltungen/"> 60. Kolloquium der Südwestdeutschen und Schweizerischen Kriminologischen Institute und Lehrstühle</a></li>
</ul>
<h3>Septiembre</h3>
<ul>
    <li>03.-06.09.2025, Athen: <a target="_blank" href="https://esc-eurocrim.org/v2/upcoming-conferences/">EUROCRIM 2025: 25. Annual Conference of the European Society of Criminology</a></li>
</ul>
<h3>Noviembre</h3>
<ul>
    <li>12.-15.11.2025, Washington D.C., USA: <a target="_blank" href="https://asc41.org/events/">2025 ASC Annual Meeting: Criminology, Law and, The Democratic Ideal</a></li>
</ul>
<h2>2026</h2>
<h3>Septiembre</h3>
<ul>
    <li>09.-12.09.2026, Warschau (Polen): <a target="_blank" href="https://esc-eurocrim.org/v2/upcoming-conferences/">EUROCRIM 2026: 26. Annual Conference of the European Society of Criminology</a></li>
</ul>
<h2>2028</h2>
<h3>Agosto</h3>
<ul>
    <li>30.8-02.09.2028, Dublin (Irland): <a target="_blank" href="https://esc-eurocrim.org/v2/upcoming-conferences/">EUROCRIM 2028: 28. Annual Conference of the European Society of Criminology</a></li>
</ul>
