<h3>Información. Preguntas frecuentes</h3>

<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#NKrimDok">
        <div class="tf-panel-collapse-heading">
            ¿Por qué ya no encuentro notaciones en el nuevo KrimDok?
        </div>
    </a>
    <div id="NKrimDok" class="collapse tf-panel-collapse-body">
        <p>KrimDok es un sistema de referencia bibliográfica de literatura criminológica. La base de datos se compone de diversos fondos bibliográficos creados originalmente según diferentes aspectos que hoy pueden consultarse mediante una interfaz de búsqueda.</p>
        <p>Los fondos del <a target="_blank" href="http://www.jura.uni-tuebingen.de/einrichtungen/ifk">Instituto de Criminología de Tubinga</a> son mayormente textos en lengua alemana, mientras que los fondos del Servicio de Información de <a href="http://www.jura.uni-tuebingen.de/einrichtungen/ifk">Criminología</a> de la Biblioteca Universitaria de Tubinga tienen una elevada proporción de literatura en lengua extranjera (principalmente monografías).  Las publicaciones que no son independientes (por ejemplo, ensayos) se indexan en el KrimDok a partir de una selección de importantes revistas y series de publicaciones internacionales.</p>
        <p>Además de la criminología, se incluyen en la medida de lo posible las llamadas ciencias básicas y afines, en particular las publicaciones (relevantes en sentido amplio o de interés general debido a que se ocupan de problemas paralelos) provenientes de las ciencias jurídicas (especialmente derecho penal, derecho procesal penal, ejecución de sentencias, sistema penal), la investigación empírica en derecho, la criminalística (incluida la investigación sobre la policía), la psicología (especialmente la psicología forense y la psicología jurídica, así como la psicología social), la psiquiatría (en particular, la psiquiatría forense y el tratamiento de delincuentes), la sociología (sociología del derecho, sociología criminal) y la pedagogía (incluida la pedagogía social).</p>
        <p>Los fondos del Instituto de Criminología de Tubinga, tanto monografías como una selección de artículos de revistas (predominantemente publicaciones en lengua alemana), se indexaron hasta finales de 2014 utilizando palabras clave locales (no normalizadas) (a partir de 1990; la literatura anterior solo parcialmente). Además, las monografías también se etiquetan con palabras clave según las RSWK (reglas del catálogo de palabras clave).</p>
        <p>Los fondos del Servicio de Información de Criminología de la Biblioteca de la Universidad de Tubinga, que comprenden principalmente publicaciones en lengua extranjera, pero también en lengua alemana, se indizan utilizando palabras clave normalizadas según las RSWK.</p>
        <p>También se incluyen referencias a la oferta de textos completos del proyecto de digitalización financiado por la Sociedad Alemana de Investigación (DFG), <a href="http://idb.ub.uni-tuebingen.de/digitue/krimdok/">DigiKrimDok</a>, las que también están indexadas con palabras clave normalizadas según las RSWK. Una gran parte del archivo de ensayos de Heidelberg ha podido indexarse gracias a una subvención de la DFG. Estos artículos están indexados con palabras clave normalizadas según las RSWK.</p>
    </div>
</div>

<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#FS2015">
        <div class="tf-panel-collapse-heading">
        ¿Por qué también se encuentran palabras clave en idiomas extranjeros a partir del año de publicación 2015, o por qué no se encuentran en los años de publicación anteriores?
        </div>
    </a>
    <div id="FS2015" class="collapse tf-panel-collapse-body">
        <p>Para los artículos de revistas que ya tienen palabras clave de autor, no se asignan más palabras clave normalizadas o locales, sino que se adoptan las palabras clave existentes del autor. Por lo tanto, a partir del año de publicación 2015, también se pueden encontrar palabras clave en inglés.</p>
    </div>
</div>

<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#SigLN">
        <div class="tf-panel-collapse-heading">
            ¿Qué significan las signaturas en las referencias individuales?
        </div>
    </a>
    <div id="SigLN" class="collapse tf-panel-collapse-body">
        <p>
            Las signaturas que comienzan por "KB" se refieren a los fondos del Servicio de 
            Información Especializada de Criminología, que se encuentra en la Biblioteca Universitaria de Tubinga. 
            Todas las demás signaturas se refieren a los fondos del Instituto de Criminología de la Universidad de Tubinga. 
            Si no se indica ninguna signatura, se trata de un registro bibliográfico de la base de datos KrimDok del que no hay existencias físicas en Tubinga.
        </p>
    </div>
</div>

<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#BInL">
        <div class="tf-panel-collapse-heading">
            ¿Qué significa la designación "In:" en las referencias individuales?
        </div>
    </a>
    <div id="BInL" class="collapse tf-panel-collapse-body">
        <p> 
            La designación "In:" en el caso de un ensayo o contribución no publicada de forma independiente se refiere a la obra mayor (una revista, una obra editada o una serie de publicaciones) en la que está contenido el ensayo.
        </p>
    </div>
</div>

<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#WasIstSubito">
        <div class="tf-panel-collapse-heading">
            ¿Qué es Subito?
        </div>
    </a>
    <div id="WasIstSubito" class="collapse tf-panel-collapse-body">
        <p> 
            <a target="_blank" href="http://www.subito-doc.de/index.php?lang=de&mod=page&pid=Dokumentlieferung">Subito</a> 
            es un servicio pago de entrega de documentos que puede utilizarse para solicitar copias de artículos de revistas o libros impresos.
        </p>
    </div>
</div>

<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#WTueB">
        <div class="tf-panel-collapse-heading">
            ¿Cómo puedo consultar o tomar prestada una obra de los fondos de Tubinga?
        </div>
    </a>
    <div id="WTueB" class="collapse tf-panel-collapse-body">
        <p>
            Normalmente puede obtener libros y revistas que no están disponibles en su biblioteca local mediante préstamo interbibliotecario o a través del servicio de entrega Subito.
        </p>
        <p>
            El préstamo interbibliotecario es un acuerdo entre bibliotecas para intercambiar literatura académica (como monografías y artículos de revistas).
        </p>
        <p>
            Las disposiciones del reglamento sobre el préstamo interbibliotecario en la República Federal de Alemania (<a target="_blank" href="https://wiki.bsz-bw.de/lib/exe/fetch.php?media=fl-team:leihverkehrsordnung.pdf">Leihverkehrsordnung</a>) constituyen la base jurídica de este sistema.
        </p>
        <p>
            No es posible pedir:
        </p>
        <ul>
            <li>
                Libros y publicaciones periódicas disponibles en su biblioteca local (incluidos los libros actualmente en préstamo y los que se encuentran en la sala de lectura o en una biblioteca dependiente).
            </li>
            <li>
                Obras disponibles en venta en librerías por poco dinero (unos 10 euros)
            </li>
            <li>
                Números y volúmenes encuadernados de revistas recientes
            </li>
        </ul>
        <p>
            Puede realizar pedidos de préstamo interbibliotecario a través del sistema de bibliotecas de su biblioteca si no ha encontrado la obra deseada in situ. Puede solicitar la obra deseada mediante préstamo interbibliotecario a otra biblioteca. En el caso de las revistas, tiene la posibilidad de pedir un artículo.
        </p>
        <p>
            Por cada pedido de préstamo interbibliotecario se abonará una tasa de tramitación de 1,50 euros, independientemente de que se realice o no una entrega. El tiempo de tramitación suele ser de 1 a 3 semanas aproximadamente.
        </p>
        <p>
            En cuanto el pedido de préstamo interbibliotecario haya llegado a su biblioteca, se le notificará y podrá recoger la obra. El periodo de préstamo es determinado por la biblioteca prestataria; generalmente es de 4 semanas (en la mayoría de los casos es posible prolongar el periodo de préstamo una vez).
        </p>
    </div>
</div>

<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#KWKB">
        <div class="tf-panel-collapse-heading">
            ¿Qué hago si no puedo conseguir una obra criminológica a través de ninguna biblioteca?
        </div>
    </a>
    <div id="KWKB" class="collapse tf-panel-collapse-body">
        <p> Puede enviar una propuesta de adquisición al Servicio de Información Especializada de Criminología. Encontrará el <a href="<?=$this->url('feedback-form', ['id' => 'AcquisitionRequest'])?>">formulario</a> aquí. El perfil de adquisiciones está disponible 
            <a href="<?=$this->url('content-page', ['page' => 'acquisition'])?>">aquí</a>.
        </p>
    </div>
</div>

<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#KeineNotationen">
        <div class="tf-panel-collapse-heading">
            ¿Por qué ya no encuentro notaciones en el nuevo KrimDok?
        </div>
    </a>
    <div id="KeineNotationen" class="collapse tf-panel-collapse-body">
        <p>
            El sistema se suprimió a finales de 2014. Desde enero de 2015 no se asignan notaciones. Las obras con fecha de publicación a partir de 2015 no pueden encontrarse mediante esta clasificación. Las obras publicadas antes de finales de 2014 solo podrán encontrarse a través de este sistema si fueron adquiridas por el Servicio de Información Especializada de Criminología antes de finales de 2014.
        </p>
    </div>
</div>

<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#WNMono">
        <div class="tf-panel-collapse-heading">
            ¿Por qué hay pocas referencias de monografías de las ciencias afines?
        </div>
    </a>
    <div id="WNMono" class="collapse tf-panel-collapse-body">
        <p>
            En cuanto a las monografías, KrimDok abarca principalmente los fondos del Servicio de Información Especializada de Criminología y del Instituto de Criminología de la Universidad de Tubinga. En las categorías que contienen información general relevante para la criminología, pero solo afín y no específicamente criminológica (por ejemplo, sobre drogas, sexualidad, alcohol, etc.), el fondo bibliográfico solo ha podido ampliarse de forma limitada en los últimos años en función de los recursos financieros destinados a la bibliografía de ciencias afines.
        </p>
    </div>
</div>
