<h1>Forschungsdatenmanagement</h1>
<p>
    Um gezielt nach Forschungsdaten in KrimDok zu recherchieren, können Sie die <a href="/Content/spezialsuche/false#content">Spezialsuche</a> verwenden oder über die Facetten am rechten Rand der Ergebnisse einschränken.
</p>


<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#handouts">
        <div class="tf-panel-collapse-heading">
            FDM-Infos to go
        </div>
    </a>
    <div id="handouts" class="collapse tf-panel-collapse-body">
        <p>Hier finden sich Informationen und Hilfestellungen zum
            Forschungsdatenmanagement in der Kriminologie. In den nächsten Wochen
            werden an dieser Stelle zu verschiedenen relevanten Aspekten kurze
            "FDM-Infos to go" sukzessive eingestellt.
        </p>
    </div>
</div>

<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#frame_conditions">
        <div class="tf-panel-collapse-heading">
            Rahmenbedingungen
        </div>
    </a>
    <div id="frame_conditions" class="collapse tf-panel-collapse-body">
        <ul>
            <li>Allianz der deutschen Wissenschaftsorganisationen (Hrsg.): <a target="_blank" href="http://doi.org/10.2312/ALLIANZOA.019">Grundsätze zum Umgang mit Forschungsdaten</a>. 2010.</li>
            <li><a target="_blank" href="http://openaccess.mpg.de/Berliner-Erklaerung">Berlin Declaration on Open Access to Knowledge in the Sciences and Humanities</a>. Berlin 2003.</li>
            <li>OECD (Hrsg.): <a target="_blank" href="http://www.oecd.org/dataoecd/9/61/38500813.pdf">OECD Principles and Guidelines for Access to Research Data from Public Funding</a>. Paris 2007.</li>
            <li>The Royal Society (Hrsg.): <a target="_blank" href="https://royalsociety.org/~/media/policy/projects/sape/2012-06-20-saoe.pdf">Science as an open enterprise</a>. London 2012.</li>
        </ul>
    </div>
</div>

<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#literature">
        <div class="tf-panel-collapse-heading">
            Literatur
        </div>
    </a>
    <div id="literature" class="collapse tf-panel-collapse-body">
        <h2>Einführungen</h2>
        <ul>
            <li>Arbeitsgruppe Forschungsdaten der Schwerpunktinitiative „Digitale Information“ der Allianz der deutschen Wissenschaftsorganisationen (Hrsg.): <a target="_blank" href="http://gfzpublic.gfz-potsdam.de/pubman/faces/viewItemOverviewPage.jsp?itemId=escidoc:3055893">Forschungsdatenmanagement. Eine Handreichung</a>. 2018.</li>
            <li>Büttner, Stephan/Hobohm, Hans-Christoph/Müller, Lars: Handbuch Forschungsdatenmanagement. Bad Honnef 2011.</li>
            <li>Neuroth, Heike et al. (2012): <a target="_blank" href="http://www.nestor.sub.uni-goettingen.de/bestandsaufnahme/index.php">Langzeitarchivierung von Forschungsdaten: Eine Bestandsaufnahme</a>. Göttingen 2012.</li>
            <li>Schwerpunktinitiative „Digitale Information“ der Allianz der deutschen Wissenschaftsorganisationen (Hrsg.): <a target="_blank" href="http://doi.org/10.2312/allianzoa.024">„Research Data Vision 2025“ – ein Schritt näher: Ein Diskussionspapier der Arbeitsgruppe Forschungsdaten.</a>. 2018.</li>
        </ul>

        <h2>Spezialthemen</h2>
        <ul>
            <li>Bambey, Doris/Meyermann, Alexia/Porzelt, Maike: <a target="_blank" href="https://www.forschungsdaten-bildung.de/get_files.php?action=get_file&file=fdb-informiert_nr-7.pdf">Potentiale der Sekundärforschung von qualitativen Daten - ein Workshopbericht</a>. Frankfurt a. M. 2017.</li>
            <li>Ebel, Thoma/Meyermann, Alexia: <a target="_blank" href="https://www.forschungsdaten-bildung.de/get_files.php?action=get_file&file=fdb-informiert-nr-3.pdf">Hinweise zur Anonymisierung von quantitativen Daten.</a>. Frankfurt a. M. 2015.</li>
            <li>fdbinfo (Hrsg.): <a target="_blank" href="https://www.forschungsdaten-bildung.de/get_files.php?action=get_file&file=fdbinfo_4.pdf">Formulierungsbeispiele für "informierte Einwilligungen"</a>. Mai 2018, Version 2.0</li>
            <li>fdbinfo (Hrsg.): <a target="_blank" href="https://www.forschungsdaten-bildung.de/get_files.php?action=get_file&file=fdbinfo_1.pdf">Checkliste zur Erstellung rechtskonformer Einwilligungserklärungen mit besonderer Berücksichtigung von Erhebungen an Schulen</a>. Mai 2015, Version 1.1. (aktualisiert im Januar 2017)</li>
            <li>Hartig, Katja / Soßna, Volker: <a target="_blank" href="https://doi.org/10.15488/262">Forschungsdatenmanagement in DFG-Anträgen: Was kann, was soll, was muss beschrieben werden? Ergebnisse des Workshops VI im Rahmen der Jahrestagung der Forschungs- und Technologiereferent/innen 2016 am 18./19. Februar in Potsdam.</a>. Hannover 2016.</li>
            <li>Meyermann, Alexia/Porzelt, Maike: <a target="_blank" href="https://www.forschungsdaten-bildung.de/get_files.php?action=get_file&file=fdb-informiert-nr-1.pdf">Hinweise zur Anonymisierung von qualitativen Daten</a>. Frankfurt a. M. 2014.</li>
            <li>Rat für Sozial- und Wirtschaftsdaten (Hrsg.): <a target="_blank" href="https://doi.org/10.17620/02671.6">Handreichung Datenschutz.</a>. Berlin 2017.</li>
            <li>Rat für Sozial- und Wirtschaftsdaten (Hrsg.): <a target="_blank" href="https://doi.org/10.17620/02671.7">Forschungsdatenmanagement in den Sozial-, Verhaltens- und Wirtschaftswissenschaften: Orientierungshilfen für die Beantragung und Begutachtung datengenerierender und datennutzender Forschungsprojekte.</a>. Berlin 2016.</li>
            <li>Rat für Sozial- und Wirtschaftsdaten (Hrsg.): <a target="_blank" href="https://doi.org/10.17620/02671.9">Archivierung und Sekundärnutzung von Daten der qualitativen Sozialforschung – Eine Stellungnahme des RatSWD</a>. Berlin 2015.</li>
            <li>Trixa, Jessica/Ebel, Thomas: <a target="_blank" href="https://www.forschungsdaten-bildung.de/get_files.php?action=get_file&file=fdb-informiert-nr-4.pdf">Hinweise zur Aufbereitung quantitativer Daten</a>. Frankfurt a. M. 2015.</li>
        </ul>

        <h2>Zeitschrift</h2>
        <ul>
            <li><a target="_blank" href="https://bausteine-fdm.de/index">Bausteine Forschungsdatenmanagement</a></li>
        </ul>
    </div>
</div>

<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#links">
        <div class="tf-panel-collapse-heading">
            Links
        </div>
    </a>
    <div id="links" class="collapse tf-panel-collapse-body">
        <ul>
            <li><a target="_blank" href="https://creativecommons.org/licenses/?lang=de">Creative-Commons-Lizenz</a></li>
            <li><a target="_blank" href="https://www.gesis.org/forschung/forschungsdatenmanagement/datenschutz-und-datensicherheit/">Datenschutz und Datensicherheit (GESIS)</a></li>
            <li><a target="_blank" href="https://www.icpsr.umich.edu/icpsrweb/content/NACJD/archiving/confidential-content.html">Data with Confidential Content</a></li>
            <li><a target="_blank" href="https://www.forschungsdaten.info/">Forschungsdaten.info</a></li>
            <li><a target="_blank" href="http://www.forschungsdaten.org/index.php/Hauptseite">Forschungsdaten.org</a></li>
            <li><a target="_blank" href="https://handbuch.tib.eu/w/Lehrbuch_Forschungsdatenmanagement/_Druckversion">Lehrbuch Forschungsdatenmanagement</a></li>
            <li><a target="_blank" href="https://www.ed.ac.uk/information-services/research-support/research-data-service">Research Data Service (University of Edinburgh)</a></li>
            <li><a target="_blank" href="https://www.ed.ac.uk/information-services/research-support/research-data-service/working-with-data/sensitive-data">Research Data Service (University of Edinburgh): Datenschutz</a></li>
        </ul>

        <h2>Tutorials und Webinare</h2>
        <ul>
            <li><a target="_blank" href="https://mantra.ed.ac.uk/">Mantra – Research Data Management Training (engl.)</a></li>
            <li><a target="_blank" href="https://auffinden-zitieren-dokumentieren.de/">Auffinden – Zitieren – Dokumentieren: Forschungsdaten in den Sozial- und Wirtschaftswissenschaften</a></li>
            <li><a target="_blank" href="http://www.researchdatamanagement.ch/">E-learning Plattform zum Forschungsdatenmanagement des Train2Dacar-Projekts (deutsch und franz.)</a></li>
            <li><a target="_blank" href="https://www.youtube.com/watch?v=iNpz4fvUUZk">Webinar: Daten teilen - Wo fange ich an? (YouTube)</a></li>
            <li><a target="_blank" href="https://www.youtube.com/watch?v=YMJOhxvlmL0">Webinar: Datendokumentation und Metadaten (YouTube)</a></li>
            <li><a target="_blank" href="https://www.kcl.ac.uk/library/researchsupport/research-data-management/index.aspx">King’s College: Introduction to Research Data Management (engl.) </a></li>
        </ul>
    </div>
</div>

<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#repositories">
        <div class="tf-panel-collapse-heading">
            Repositorien und Archive
        </div>
    </a>
    <div id="repositories" class="collapse tf-panel-collapse-body">
        <h2>1. Einschlägig kriminologische Archive:</h2>
        <ul>
            <li>- <a target="_blank" href="https://www.icpsr.umich.edu/icpsrweb/content/NACJD/index.html">NACJD</a></li>
        </ul>
        <h2>2. Deutsche Datenarchive, die kriminologisch relevant sind:</h2>
        <ul>
            <li>- <a target="_blank" href="https://www.destatis.de/DE/Themen/Staat/Justiz-Rechtspflege/_inhalt.html#sprg475880">DESTATIS-Datenbank Genesis-Online</a></li>
            <li>- <a target="_blank" href="https://www.qualiservice.org/de/">Qualiservice</a></li>
            <li>- <a target="_blank" href="https://www.gesis.org/angebot/daten-finden-und-abrufen">GESIS</a></li>
            <li>- <a target="_blank" href="https://rdc-psychology.org/de">ZPID</a></li>
        </ul>
        <h2>3. Ausländische und internationale Archive und NFDIen, die kriminologisch relevant sind:</h2>
        <ul>
            <li>- <a target="_blank" href="https://www.ukdataservice.ac.uk/">UK Data Service</a></li>
            <li>- <a target="_blank" href="https://eudat.eu/target-user/researchers">EUDAT</a></li>
            <li>- <a target="_blank" href="https://ada.edu.au/">Australian Data Archive</a></li>
        </ul>
        <h2>4. Weitere Archive:</h2>
        <ul>
            <li>- <a target="_blank" href="http://datadryad.org/">Dryad</a></li>
            <li>- <a target="_blank" href="http://figshare.com/">Figshare</a></li>
            <li>- <a target="_blank" href="https://zenodo.org/">Zenodo</a></li>
        </ul>
    </div>
</div>

<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#videos">
        <div class="tf-panel-collapse-heading">
            Videos
        </div>
    </a>
    <div id="videos" class="collapse tf-panel-collapse-body">
        <h2>Übersichten</h2>
        <ul>
            <li><a target="_blank" href="https://www.youtube.com/watch?v=gYDb-GP1CA4">The what, why and how of data management planning (YouTube)</a></li>
            <li><a target="_blank" href="https://www.youtube.com/watch?v=nNBiCcBlwRA">How to avoid a data management nightmare (YouTube)</a></li>
            <li><a target="_blank" href="https://www.youtube.com/watch?v=PgqtiY7oZ6k">Persistent identifiers and data citation explained (YouTube)</a></li>
            <li><a target="_blank" href="https://www.youtube.com/watch?v=w9SCtL43vDM">'Unsere Kinder, die Forschungsdaten' Paul Vierkant beim #38 Science Slam Berlin (YouTube)</a></li>
        </ul>

        <h2>Datenschutz und Lizensierung</h2>
        <ul>
            <li><a target="_blank" href="https://www.youtube.com/watch?v=VF5A2JhiJug">Datenschutz einfach erklärt (YouTube)</a></li>
            <li><a target="_blank" href="https://www.youtube.com/watch?v=cwUiVUR7bWY">Wie ist das mit dem Urheberrecht? (YouTube)</a></li>
            <li><a target="_blank" href="https://www.youtube.com/watch?v=KNvhfiioqHc">Teil 1: Urheberrecht und freie Lizenzen (Grundbegriffe) (YouTube)</a></li>
            <li><a target="_blank" href="https://www.youtube.com/watch?v=N4E0eSBcjso">Teil 2: Urheberrecht und freie Lizenzen (Lizenzmodelle) (YouTube)</a></li>
            <li><a target="_blank" href="https://www.youtube.com/watch?v=Tvwp5LK_Wko">Open Data Licensing Animation - OERIPR Support (YouTube)</a></li>
        </ul>
    </div>
</div>

<style>
    #repositories ul li {
        list-style: none;
    }
</style>