<h1>Forschungsdatenmanagement</h1>
<p>
    Um gezielt nach Forschungsdaten in KrimDok zu recherchieren, können Sie die <a href="/Content/spezialsuche/false#content">Spezialsuche</a> verwenden oder über die Facetten am rechten Rand der Ergebnisse einschränken.
</p>


<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#handouts">
        <div class="tf-panel-collapse-heading">
            FDM-Infos to go
        </div>
    </a>
    <div id="handouts" class="collapse tf-panel-collapse-body">
        <p>Hier finden sich Informationen und Hilfestellungen zum Forschungsdatenmanagement in der Kriminologie.</p>
        <br />
        <a target="_blank" href="/krimdok_docs/Anonymisierung_qualitativer_Daten.pdf"><img src="<?=$this->imageLink('icon_pdf.png') ?>" alt="Anonymisierung qualitativer Daten" width="25" height="25"/> Anonymisierung qualitativer Daten</a><br />
        <a target="_blank" href="/krimdok_docs/Anonymisierung_quantitativer_Daten.pdf"><img src="<?=$this->imageLink('icon_pdf.png') ?>" alt="Anonymisierung quantitativer Daten" width="25" height="25"/> Anonymisierung quantitativer Daten</a><br />
        <a target="_blank" href="/krimdok_docs/Creative_Commons_Lizenzen.pdf"><img src="<?=$this->imageLink('icon_pdf.png') ?>" alt="Creative-Commons-Lizenzen" width="25" height="25"/> Creative-Commons-Lizenzen</a><br />
        <a target="_blank" href="/krimdok_docs/Datenmanagementplan.pdf"><img src="<?=$this->imageLink('icon_pdf.png') ?>" alt="Datenmanagementplan" width="25" height="25"/> Datenmanagementplan</a><br />
        <a target="_blank" href="/krimdok_docs/Datenmanagementplan_Hilfreiche_Tools.pdf"><img src="<?=$this->imageLink('icon_pdf.png') ?>" alt="Datenmanagementplan Hilfreiche Tools" width="25" height="25"/> Datenmanagementplan: Hilfreiche Tools</a><br />
        <a target="_blank" href="/krimdok_docs/Datenschutz_in_der_Kriminologie.pdf"><img src="<?=$this->imageLink('icon_pdf.png') ?>" alt="Datenschutz in der Kriminologie" width="25" height="25"/> Datenschutz in der Kriminologie</a><br />
        <a target="_blank" href="/krimdok_docs/Dokumentation_von_Forschungsdaten_in_der_Kriminologie.pdf"><img src="<?=$this->imageLink('icon_pdf.png') ?>" alt="Dokumentation von Forschungsdaten in der Kriminologie" width="25" height="25"/> Dokumentation von Forschungsdaten in der Kriminologie</a><br />
        <a target="_blank" href="/krimdok_docs/FAIR-Prinzipien.pdf"><img src="<?=$this->imageLink('icon_pdf.png') ?>" alt="FAIR-Prinzipien" width="25" height="25"/> FAIR-Prinzipien</a><br />
        <a target="_blank" href="/krimdok_docs/Forschungsdaten_richtig_zitieren.pdf"><img src="<?=$this->imageLink('icon_pdf.png') ?>" alt="Forschungsdaten richtig zitieren" width="25" height="25"/> Forschungsdaten richtig zitieren</a><br />
        <a target="_blank" href="/krimdok_docs/Informierte_Einwilligung.pdf"><img src="<?=$this->imageLink('icon_pdf.png') ?>" alt="Informierte Einwilligung" width="25" height="25"/> Informierte Einwilligung</a><br />
        <a target="_blank" href="/krimdok_docs/Metadaten_im_Forschungsdatenmanagement.pdf"><img src="<?=$this->imageLink('icon_pdf.png') ?>" alt="Metadaten im Forschungsdatenmanagement" width="25" height="25"/> Metadaten im Forschungsdatenmanagement</a><br />
        <a target="_blank" href="/krimdok_docs/Metadaten_KrimDok-Schlagwortliste.pdf"><img src="<?=$this->imageLink('icon_pdf.png') ?>" alt="Metadaten KrimDok-Schlagwortliste" width="25" height="25"/> Metadaten: KrimDok-Schlagwortliste</a>
    </div>
</div>

<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#frame_conditions">
        <div class="tf-panel-collapse-heading">
            Rahmenbedingungen
        </div>
    </a>
    <div id="frame_conditions" class="collapse tf-panel-collapse-body">
        <ul>
            <li>Allianz der deutschen Wissenschaftsorganisationen (Hrsg.): <a target="_blank" href="http://doi.org/10.2312/ALLIANZOA.019">Grundsätze zum Umgang mit Forschungsdaten</a>. 2010.</li>
            <li><a target="_blank" href="http://openaccess.mpg.de/Berliner-Erklaerung">Berlin Declaration on Open Access to Knowledge in the Sciences and Humanities</a>. Berlin 2003.</li>
            <li>OECD (Hrsg.): <a target="_blank" href="http://www.oecd.org/dataoecd/9/61/38500813.pdf">OECD Principles and Guidelines for Access to Research Data from Public Funding</a>. Paris 2007.</li>
            <li>The Royal Society (Hrsg.): <a target="_blank" href="https://royalsociety.org/~/media/policy/projects/sape/2012-06-20-saoe.pdf">Science as an open enterprise</a>. London 2012.</li>
        </ul>
    </div>
</div>

<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#literature">
        <div class="tf-panel-collapse-heading">
            Literatur
        </div>
    </a>
    <div id="literature" class="collapse tf-panel-collapse-body">
        <h2>Einführungen</h2>
        <ul>
            <li>Arbeitsgruppe Forschungsdaten der Schwerpunktinitiative „Digitale Information“ der Allianz der deutschen Wissenschaftsorganisationen (Hrsg.): <a target="_blank" href="http://gfzpublic.gfz-potsdam.de/pubman/faces/viewItemOverviewPage.jsp?itemId=escidoc:3055893">Forschungsdatenmanagement. Eine Handreichung</a>. 2018.</li>
            <li>Büttner, Stephan/Hobohm, Hans-Christoph/Müller, Lars: Handbuch Forschungsdatenmanagement. Bad Honnef 2011.</li>
            <li>Neuroth, Heike et al. (2012): <a target="_blank" href="http://www.nestor.sub.uni-goettingen.de/bestandsaufnahme/index.php">Langzeitarchivierung von Forschungsdaten: Eine Bestandsaufnahme</a>. Göttingen 2012.</li>
            <li>Schwerpunktinitiative „Digitale Information“ der Allianz der deutschen Wissenschaftsorganisationen (Hrsg.): <a target="_blank" href="http://doi.org/10.2312/allianzoa.024">„Research Data Vision 2025“ – ein Schritt näher: Ein Diskussionspapier der Arbeitsgruppe Forschungsdaten.</a>. 2018.</li>
        </ul>

        <h2>Spezialthemen</h2>
        <ul>
            <li>Bambey, Doris/Meyermann, Alexia/Porzelt, Maike: <a target="_blank" href="https://www.forschungsdaten-bildung.de/get_files.php?action=get_file&file=fdb-informiert_nr-7.pdf">Potentiale der Sekundärforschung von qualitativen Daten - ein Workshopbericht</a>. Frankfurt a. M. 2017.</li>
            <li>Ebel, Thoma/Meyermann, Alexia: <a target="_blank" href="https://www.forschungsdaten-bildung.de/get_files.php?action=get_file&file=fdb-informiert-nr-3.pdf">Hinweise zur Anonymisierung von quantitativen Daten.</a>. Frankfurt a. M. 2015.</li>
            <li>fdbinfo (Hrsg.): <a target="_blank" href="https://www.forschungsdaten-bildung.de/get_files.php?action=get_file&file=fdbinfo_4.pdf">Formulierungsbeispiele für "informierte Einwilligungen"</a>. Mai 2018, Version 2.0</li>
            <li>fdbinfo (Hrsg.): <a target="_blank" href="https://www.forschungsdaten-bildung.de/get_files.php?action=get_file&file=fdbinfo_1.pdf">Checkliste zur Erstellung rechtskonformer Einwilligungserklärungen mit besonderer Berücksichtigung von Erhebungen an Schulen</a>. Mai 2015, Version 1.1. (aktualisiert im Januar 2017)</li>
            <li>Hartig, Katja / Soßna, Volker: <a target="_blank" href="https://doi.org/10.15488/262">Forschungsdatenmanagement in DFG-Anträgen: Was kann, was soll, was muss beschrieben werden? Ergebnisse des Workshops VI im Rahmen der Jahrestagung der Forschungs- und Technologiereferent/innen 2016 am 18./19. Februar in Potsdam.</a>. Hannover 2016.</li>
            <li>Meyermann, Alexia/Porzelt, Maike: <a target="_blank" href="https://www.forschungsdaten-bildung.de/get_files.php?action=get_file&file=fdb-informiert-nr-1.pdf">Hinweise zur Anonymisierung von qualitativen Daten</a>. Frankfurt a. M. 2014.</li>
            <li>Rat für Sozial- und Wirtschaftsdaten (Hrsg.): <a target="_blank" href="https://doi.org/10.17620/02671.6">Handreichung Datenschutz.</a>. Berlin 2017.</li>
            <li>Rat für Sozial- und Wirtschaftsdaten (Hrsg.): <a target="_blank" href="https://doi.org/10.17620/02671.7">Forschungsdatenmanagement in den Sozial-, Verhaltens- und Wirtschaftswissenschaften: Orientierungshilfen für die Beantragung und Begutachtung datengenerierender und datennutzender Forschungsprojekte.</a>. Berlin 2016.</li>
            <li>Rat für Sozial- und Wirtschaftsdaten (Hrsg.): <a target="_blank" href="https://doi.org/10.17620/02671.9">Archivierung und Sekundärnutzung von Daten der qualitativen Sozialforschung – Eine Stellungnahme des RatSWD</a>. Berlin 2015.</li>
            <li>Trixa, Jessica/Ebel, Thomas: <a target="_blank" href="https://www.forschungsdaten-bildung.de/get_files.php?action=get_file&file=fdb-informiert-nr-4.pdf">Hinweise zur Aufbereitung quantitativer Daten</a>. Frankfurt a. M. 2015.</li>
        </ul>

        <h2>Zeitschrift</h2>
        <ul>
            <li><a target="_blank" href="https://bausteine-fdm.de/index">Bausteine Forschungsdatenmanagement</a></li>
        </ul>
    </div>
</div>

<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#links">
        <div class="tf-panel-collapse-heading">
            Links
        </div>
    </a>
    <div id="links" class="collapse tf-panel-collapse-body">
        <ul>
            <li><a target="_blank" href="https://creativecommons.org/licenses/?lang=de">Creative-Commons-Lizenz</a></li>
            <li><a target="_blank" href="https://www.gesis.org/forschung/forschungsdatenmanagement/datenschutz-und-datensicherheit/">Datenschutz und Datensicherheit (GESIS)</a></li>
            <li><a target="_blank" href="https://www.icpsr.umich.edu/icpsrweb/content/NACJD/archiving/confidential-content.html">Data with Confidential Content</a></li>
            <li><a target="_blank" href="https://www.forschungsdaten.info/">Forschungsdaten.info</a></li>
            <li><a target="_blank" href="http://www.forschungsdaten.org/index.php/Hauptseite">Forschungsdaten.org</a></li>
            <li><a target="_blank" href="https://handbuch.tib.eu/w/Lehrbuch_Forschungsdatenmanagement/_Druckversion">Lehrbuch Forschungsdatenmanagement</a></li>
            <li><a target="_blank" href="https://www.ed.ac.uk/information-services/research-support/research-data-service">Research Data Service (University of Edinburgh)</a></li>
            <li><a target="_blank" href="https://www.ed.ac.uk/information-services/research-support/research-data-service/working-with-data/sensitive-data">Research Data Service (University of Edinburgh): Datenschutz</a></li>
        </ul>

        <h2>Tutorials und Webinare</h2>
        <ul>
            <li><a target="_blank" href="https://mantra.ed.ac.uk/">Mantra – Research Data Management Training (engl.)</a></li>
            <li><a target="_blank" href="https://auffinden-zitieren-dokumentieren.de/">Auffinden – Zitieren – Dokumentieren: Forschungsdaten in den Sozial- und Wirtschaftswissenschaften</a></li>
            <li><a target="_blank" href="http://www.researchdatamanagement.ch/">E-learning Plattform zum Forschungsdatenmanagement des Train2Dacar-Projekts (deutsch und franz.)</a></li>
            <li><a target="_blank" href="https://www.youtube.com/watch?v=iNpz4fvUUZk">Webinar: Daten teilen - Wo fange ich an? (YouTube)</a></li>
            <li><a target="_blank" href="https://www.youtube.com/watch?v=YMJOhxvlmL0">Webinar: Datendokumentation und Metadaten (YouTube)</a></li>
            <li><a target="_blank" href="https://www.kcl.ac.uk/library/researchsupport/research-data-management/index.aspx">King’s College: Introduction to Research Data Management (engl.) </a></li>
        </ul>
    </div>
</div>

<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#repositories">
        <div class="tf-panel-collapse-heading">
            Repositorien und Archive
        </div>
    </a>
    <div id="repositories" class="collapse tf-panel-collapse-body">
        
        <h2>1. Einschlägig kriminologische Archive:</h2>
        <ul>
            <li>-   <a target="_blank" href="https://www.icpsr.umich.edu/icpsrweb/content/NACJD/index.html">National Archive of Criminal Justice Data (NACJD)</a>
                    <p>Das National Archive of Criminal Justice Data (NACJD) archiviert empirische kriminologische Daten(sätze) und stellt diese in vielen Fällen zur Nachnutzung bzw. für Sekundäranalysen zur Verfügung. Im NACJD sind neben großen nationale Statistiken (z.B. FBI Uniform Crime Report) und Befragungsdaten (z.B. National Crime Victimization Survey) auch Daten aus Forschungsprojekten enthalten. Insgesamt umfasst das NACJD bereits über 3500 Datensätze zu verschiedenen Themen.</p>
            </li>
        </ul>
        
        <h2>2. Deutsche Datenarchive, die kriminologisch relevant sind:</h2>
        <ul>
            <li>-   <a target="_blank" href="https://www.destatis.de/DE/Themen/Staat/Justiz-Rechtspflege/_inhalt.html#sprg475880">DESTATIS-Datenbank Genesis-Online</a>
                    <p>Bei GENESIS-Online handelt es sich um die digitale Datenbank der Statistischen Bundesamtes. Dort finden sich u.a. die für kriminologisch forschenden Personen wichtigen Statistiken zur Justiz und Rechtspflege.</p>
            </li>        
            <li>-   <a target="_blank" href="https://www.qualiservice.org/de/">Qualiservice</a>
                    <p>Qualiservice ist ein Forschungsdatenzentrum für qualitative sozialwissenschaftliche Forschungsdaten. Qualiservice bietet dabei einerseits die Möglichkeit qualitative Forschungsdaten im Rahmen der vorhandenen Infrastruktur zu archivieren. Andererseits stellt Qualiservice qualitative Forschungsdaten für die Sekundärnutzung durch Forschende zur Verfügung. Aktuell sind bereits 30 Studien bei Qualiservice archiviert. Darüber hinaus bietet Qualiservice Unterstützung beim Forschungsdatenmanagement.</p>
            </li>
            <li>-   <a target="_blank" href="https://www.gesis.org/angebot/daten-finden-und-abrufen">GESIS</a>
                    <p>Das GESIS-Datenarchiv beinhaltet bereits mehr als 7000 nationale und internationale quantitative empirische Studien, die für eine Sekundärnutzung zur Verfügung stehen. Die enthaltenen Studien können dabei sowohl thematisch, geografisch als auch mit Blick auf das Datenformat bzw. zugrundeliegende Forschungsdesign (z.B. Querschnittsdaten, Panel) gefiltert und ausgewiesen werden.</p>
            </li>
            <li>-   <a target="_blank" href="https://rdc-psychology.org/de">ZPID</a>
                    <p>Das Forschungsdatenzentrum (FDZ) am ZPID (vormals PsychData) ist eine vom Leibniz-Zentrum für Psychologische Information und Dokumentation (ZPID) betriebene, speziell auf die psychologische Forschung ausgerichtete Plattform für Datenarchivierung, -dokumentation und -austausch.</p>
            </li>
        </ul>        

        <h2>3. Ausländische und internationale Archive und NFDIen, die kriminologisch relevant sind:</h2>
        <ul>        
            <li>-   <a target="_blank" href="https://ukdataservice.ac.uk/">UK Data Service</a>
                    <p>Der UK Data Service umfasst wichtige von der britischen Regierung geförderte, z.T. länderübergreifende Erhebungen, Längsschnittstudien, britische Volkszählungsdaten sowie qualitative und quantitative Daten aus wissenschaftlichen Forschungsprojekten.</p>
            </li>    
            <li>-   <a target="_blank" href="https://eudat.eu/target-user/researchers">EUDAT</a>
                    <p>EUDAT ist ein langfristig angelegtes EU-Projekt. Es stellt mit B2DROP und B2SHARE eine Infrastruktur für die Sicherung, Archivierung und Publikation von Daten zur Verfügung.</p>
            </li>
            <li>-   <a target="_blank" href="https://ada.edu.au/">Australian Data Archive</a>
                    <p>Das australische Datenarchiv enthält knapp 1.900 Datensätze aus einer Vielzahl von Projekten und Studien von 1838 bis heute. Einige der Datensätze sind nach Methodik (z.B. Längsschnittstudien) und Thema (z.B. Erhebungen zu sozialen Einstellungen, Gesundheitsstudien) auffindbar.</p>
            </li>
        </ul>

        <h2>4. Weitere Archive:</h2>
        <ul>
            <li>-   <a target="_blank" href="https://datadryad.org/">Dryad</a>
                    <p>Dryad ist ein kostenpflichtiges Datenrepositorium primär für medizinische aber auch andere Daten. Es bietet eine Qualitätskontrolle und erlaubt die Datenpublikation nur im Zusammenhang mit einem entsprechenden Paper.</p>
            </li>
            <li>-   <a target="_blank" href="https://figshare.com/">Figshare</a>
                    <p>Figshare ist ein Repositorium für verschiedenste Publikationsobjekte. Es bietet die Möglichkeit, auch negative Daten zu veröffentlichen und unterstützt altmetrics, wird jedoch von einem kommerziellen Anbieter (MacMillan Group / Nature) betrieben.</p>
            </li>
            <li>-   <a target="_blank" href="https://zenodo.org/">Zenodo</a>
                    <p>Zenodo ist eine Plattform für die Archivierung und Publikation verschiedener Inhalte und Formate. Es wird von der Europäischen Kommission gefördert und am CERN betrieben. Es steht für Forschungsergebnisse aus allen Disziplinen zur Verfügung, erlaubt sowohl Text- als auch Datenpublikationen und ermöglicht deren Verknüpfung. Zenodo ist nutzerfreundlich und niedrigschwellig, betreibt aber keine Kuration / Qualitätskontrolle.</p>
            </li>
        </ul>

        <h2>5. Allgemeine Übersichten:</h2>
        <ul>
            <li>-   <a target="_blank" href="https://www.re3data.org/">Re3data</a>
                    <p>Das Registry of Research Data Repositories ist das weltgrößte disziplinübergreifende Verzeichnis von Forschungsdatenrepositorien.</p>
            </li>
            <li>-   <a target="_blank" href="https://www.psychlinker.de/category.php?cat=8">Forschungsdaten-Repositorien</a>
                    <p>Übersicht über verschiedene Forschungsdaten-Repositorien beim „PsychLinker“ – einer Sammlung digitaler Ressourcen für Psychologie</p>
            </li>
            <li>-   <a target="_blank" href="https://www.fachportal-paedagogik.de/forschungsdaten/Infrastruktur.php">Datenzentren für die Bildungsforschung</a>
                    <p>Übersicht über Forschungsdaten-Repositorien für die Bildungsforschung beim Fachportal Pädagogik</p>
            </li>
        </ul>        
    </div>
</div>

<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#videos">
        <div class="tf-panel-collapse-heading">
            Videos
        </div>
    </a>
    <div id="videos" class="collapse tf-panel-collapse-body">
        <h2>Übersichten</h2>
        <ul>
            <li><a target="_blank" href="https://www.youtube.com/watch?v=gYDb-GP1CA4">The what, why and how of data management planning (YouTube)</a></li>
            <li><a target="_blank" href="https://www.youtube.com/watch?v=nNBiCcBlwRA">How to avoid a data management nightmare (YouTube)</a></li>
            <li><a target="_blank" href="https://www.youtube.com/watch?v=PgqtiY7oZ6k">Persistent identifiers and data citation explained (YouTube)</a></li>
            <li><a target="_blank" href="https://www.youtube.com/watch?v=w9SCtL43vDM">'Unsere Kinder, die Forschungsdaten' Paul Vierkant beim #38 Science Slam Berlin (YouTube)</a></li>
        </ul>

        <h2>Datenschutz und Lizensierung</h2>
        <ul>
            <li><a target="_blank" href="https://www.youtube.com/watch?v=VF5A2JhiJug">Datenschutz einfach erklärt (YouTube)</a></li>
            <li><a target="_blank" href="https://www.youtube.com/watch?v=cwUiVUR7bWY">Wie ist das mit dem Urheberrecht? (YouTube)</a></li>
            <li><a target="_blank" href="https://www.youtube.com/watch?v=KNvhfiioqHc">Teil 1: Urheberrecht und freie Lizenzen (Grundbegriffe) (YouTube)</a></li>
            <li><a target="_blank" href="https://www.youtube.com/watch?v=N4E0eSBcjso">Teil 2: Urheberrecht und freie Lizenzen (Lizenzmodelle) (YouTube)</a></li>
            <li><a target="_blank" href="https://www.youtube.com/watch?v=Tvwp5LK_Wko">Open Data Licensing Animation - OERIPR Support (YouTube)</a></li>
        </ul>
    </div>
</div>

<style>
    #handouts img {
        width: 25px;
        height: 25px;
        margin-top: -5px;
    }
    #repositories ul li {
        list-style: none;
    }
</style>