<h1>Research Data Management</h1>

<p>To search specifically for research data in KrimDok, you can use the specific <a href="/Content/spezialsuche/false#content">search</a> and narrow it down using the facets on the right-hand side of the results.</p>

<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#frame_conditions">
        <div class="tf-panel-collapse-heading">
        Framework
        </div>
    </a>
    <div id="frame_conditions" class="collapse tf-panel-collapse-body">
        <ul>
            <li>Allianz der deutschen Wissenschaftsorganisationen (Hrsg.): <a target="_blank" href="http://doi.org/10.2312/ALLIANZOA.019">Grundsätze zum Umgang mit Forschungsdaten</a>. 2010.</li>
            <li><a target="_blank" href="http://openaccess.mpg.de/Berliner-Erklaerung">Berlin Declaration on Open Access to Knowledge in the Sciences and Humanities</a>. Berlin 2003.</li>
            <li>OECD (Hrsg.): <a target="_blank" href="http://www.oecd.org/dataoecd/9/61/38500813.pdf">OECD Principles and Guidelines for Access to Research Data from Public Funding</a>. Paris 2007.</li>
            <li>The Royal Society (Hrsg.): <a target="_blank" href="https://royalsociety.org/~/media/policy/projects/sape/2012-06-20-saoe.pdf">Science as an open enterprise</a>. London 2012.</li>
        </ul>
    </div>
</div>

<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#literature">
        <div class="tf-panel-collapse-heading">
        Literature
        </div>
    </a>
    <div id="literature" class="collapse tf-panel-collapse-body">
        <h2>Introductions</h2>
        <ul>
            <li>Arbeitsgruppe Forschungsdaten der Schwerpunktinitiative „Digitale Information“ der Allianz der deutschen Wissenschaftsorganisationen (Hrsg.): <a target="_blank" href="http://gfzpublic.gfz-potsdam.de/pubman/faces/viewItemOverviewPage.jsp?itemId=escidoc:3055893">Forschungsdatenmanagement. Eine Handreichung</a>. 2018.</li>
            <li>Büttner, Stephan/Hobohm, Hans-Christoph/Müller, Lars: Handbuch Forschungsdatenmanagement. Bad Honnef 2011.</li>
            <li>Neuroth, Heike et al. (2012): <a target="_blank" href="http://www.nestor.sub.uni-goettingen.de/bestandsaufnahme/index.php">Langzeitarchivierung von Forschungsdaten: Eine Bestandsaufnahme</a>. Göttingen 2012.</li>
            <li>Schwerpunktinitiative „Digitale Information“ der Allianz der deutschen Wissenschaftsorganisationen (Hrsg.): <a target="_blank" href="http://doi.org/10.2312/allianzoa.024">„Research Data Vision 2025“ – ein Schritt näher: Ein Diskussionspapier der Arbeitsgruppe Forschungsdaten.</a>. 2018.</li>
        </ul>

        <h2>Special Topics</h2>
        <ul>
            <li>Bambey, Doris/Meyermann, Alexia/Porzelt, Maike: <a target="_blank" href="https://www.forschungsdaten-bildung.de/get_files.php?action=get_file&file=fdb-informiert_nr-7.pdf">Potentiale der Sekundärforschung von qualitativen Daten - ein Workshopbericht</a>. Frankfurt a. M. 2017.</li>
            <li>Ebel, Thoma/Meyermann, Alexia: <a target="_blank" href="https://www.forschungsdaten-bildung.de/get_files.php?action=get_file&file=fdb-informiert-nr-3.pdf">Hinweise zur Anonymisierung von quantitativen Daten.</a>. Frankfurt a. M. 2015.</li>
            <li>fdbinfo (Hrsg.): <a target="_blank" href="https://www.forschungsdaten-bildung.de/get_files.php?action=get_file&file=fdbinfo_4.pdf">Formulierungsbeispiele für "informierte Einwilligungen"</a>. Mai 2018, Version 2.0</li>
            <li>fdbinfo (Hrsg.): <a target="_blank" href="https://www.forschungsdaten-bildung.de/get_files.php?action=get_file&file=fdbinfo_1.pdf">Checkliste zur Erstellung rechtskonformer Einwilligungserklärungen mit besonderer Berücksichtigung von Erhebungen an Schulen</a>. Mai 2015, Version 1.1. (aktualisiert im Januar 2017)</li>
            <li>Hartig, Katja / Soßna, Volker: <a target="_blank" href="https://doi.org/10.15488/262">Forschungsdatenmanagement in DFG-Anträgen: Was kann, was soll, was muss beschrieben werden? Ergebnisse des Workshops VI im Rahmen der Jahrestagung der Forschungs- und Technologiereferent/innen 2016 am 18./19. Februar in Potsdam.</a>. Hannover 2016.</li>
            <li>Meyermann, Alexia/Porzelt, Maike: <a target="_blank" href="https://www.forschungsdaten-bildung.de/get_files.php?action=get_file&file=fdb-informiert-nr-1.pdf">Hinweise zur Anonymisierung von qualitativen Daten</a>. Frankfurt a. M. 2014.</li>
            <li>Rat für Sozial- und Wirtschaftsdaten (Hrsg.): <a target="_blank" href="https://doi.org/10.17620/02671.6">Handreichung Datenschutz.</a>. Berlin 2017.</li>
            <li>Rat für Sozial- und Wirtschaftsdaten (Hrsg.): <a target="_blank" href="https://doi.org/10.17620/02671.7">Forschungsdatenmanagement in den Sozial-, Verhaltens- und Wirtschaftswissenschaften: Orientierungshilfen für die Beantragung und Begutachtung datengenerierender und datennutzender Forschungsprojekte.</a>. Berlin 2016.</li>
            <li>Rat für Sozial- und Wirtschaftsdaten (Hrsg.): <a target="_blank" href="https://doi.org/10.17620/02671.9">Archivierung und Sekundärnutzung von Daten der qualitativen Sozialforschung – Eine Stellungnahme des RatSWD</a>. Berlin 2015.</li>
            <li>Trixa, Jessica/Ebel, Thomas: <a target="_blank" href="https://www.forschungsdaten-bildung.de/get_files.php?action=get_file&file=fdb-informiert-nr-4.pdf">Hinweise zur Aufbereitung quantitativer Daten</a>. Frankfurt a. M. 2015.</li>
        </ul>

        <h2>Journal</h2>
        <ul>
            <li><a target="_blank" href="https://bausteine-fdm.de/index">Bausteine Forschungsdatenmanagement</a></li>
        </ul>
    </div>
</div>

<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#links">
        <div class="tf-panel-collapse-heading">
        Links
        </div>
    </a>
    <div id="links" class="collapse tf-panel-collapse-body">
        <ul>
            <li><a target="_blank" href="https://creativecommons.org/licenses/?lang=de">Creative-Commons-Lizenz</a></li>
            <li><a target="_blank" href="https://www.gesis.org/forschung/forschungsdatenmanagement/datenschutz-und-datensicherheit/">Datenschutz und Datensicherheit (GESIS)</a></li>
            <li><a target="_blank" href="https://www.icpsr.umich.edu/icpsrweb/content/NACJD/archiving/confidential-content.html">Data with Confidential Content</a></li>
            <li><a target="_blank" href="https://www.forschungsdaten.info/">Forschungsdaten.info</a></li>
            <li><a target="_blank" href="http://www.forschungsdaten.org/index.php/Hauptseite">Forschungsdaten.org</a></li>
            <li><a target="_blank" href="https://handbuch.tib.eu/w/Lehrbuch_Forschungsdatenmanagement/_Druckversion">Lehrbuch Forschungsdatenmanagement</a></li>
            <li><a target="_blank" href="https://www.ed.ac.uk/information-services/research-support/research-data-service">Research Data Service (University of Edinburgh)</a></li>
            <li><a target="_blank" href="https://www.ed.ac.uk/information-services/research-support/research-data-service/working-with-data/sensitive-data">Research Data Service (University of Edinburgh): Datenschutz</a></li>
        </ul>

        <h2>Tutorials and Webinars</h2>
        <ul>
            <li><a target="_blank" href="https://mantra.ed.ac.uk/">Mantra – Research Data Management Training (engl.)</a></li>
            <li><a target="_blank" href="https://auffinden-zitieren-dokumentieren.de/">Auffinden – Zitieren – Dokumentieren: Forschungsdaten in den Sozial- und Wirtschaftswissenschaften</a></li>
            <li><a target="_blank" href="http://www.researchdatamanagement.ch/">E-learning Plattform zum Forschungsdatenmanagement des Train2Dacar-Projekts (deutsch und franz.)</a></li>
            <li><a target="_blank" href="https://www.youtube.com/watch?v=iNpz4fvUUZk">Webinar: Daten teilen - Wo fange ich an? (YouTube)</a></li>
            <li><a target="_blank" href="https://www.youtube.com/watch?v=YMJOhxvlmL0">Webinar: Datendokumentation und Metadaten (YouTube)</a></li>
            <li><a target="_blank" href="https://www.kcl.ac.uk/library/researchsupport/research-data-management/index.aspx">King’s College: Introduction to Research Data Management (engl.) </a></li>
        </ul>
    </div>
</div>

<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#repositories">
        <div class="tf-panel-collapse-heading">
        Repositories and Archives
        </div>
    </a>
    <div id="repositories" class="collapse tf-panel-collapse-body">
        <h2>Overview</h2>

        <p>
            <a target="_blank" href="">Re3data</a><br />
            The Registry of Research Data Repositories is the world's largest interdisciplinary directory of research data repositories.
        </p>

        <p>   
            <a target="_blank" href="">Forschungsdaten-Repositorien (Research Data Repositories)</a><br />
            Overview of various research data repositories on "PsychLinker" - a collection of digital resources for psychology.
        </p>

        <p>  
            <a target="_blank" href="">Datenzentren für die Bildungsforschung (Data Centers for Educational Research)</a><br />
            Overview of research data repositories for educational research on the specialized portal "Pedagogy."
        </p>

        <h2>General and Criminologically Relevant Repositories and Archives</h2>

        <p>       
            <a target="_blank" href="">National Archive of Criminal Justice Data</a><br />
            The National Archive of Criminal Justice Data (NACJD) archives, curates, preserves, and disseminates data on crime and justice for secondary analysis. It is home to several large-scale and well-known datasets.
        </p>

        <p>    
            <a target="_blank" href="">UK Data Service</a><br />
            The UK Data Service, funded by the Economic and Social Research Council (ESRC), includes major UK government-sponsored surveys, cross-national surveys, longitudinal studies, UK census data, international aggregate, business data, and qualitative data.
        </p>

        <p>            
            <a target="_blank" href="">SowiDataNet (GESIS)</a><br />
            SowiDataNet is a research data network for the social and economic sciences in Germany. Institutional institutions can use this service for independent documentation, preservation, and publication of their research data to make them available for reuse by the scientific community.
        </p>

        <p>        
            <a target="_blank" href="https://data.gesis.org/sharing/#!Home">Datorium</a><br />
            Datorium is a service provided by GESIS and serves researchers in the social and economic sciences for independent documentation, publication, and exchange of their research data. The data, metadata, and associated documents can be independently and freely uploaded and additionally linked to relevant publications.
        </p>

        <p>
            <a target="_blank" href="">FDZ</a><br />
            The FDZ (former PsychData) is a platform operated by the Leibniz Center for Psychological Information and Documentation (ZPID), specifically designed for psychological research data archiving, documentation, and exchange.
        </p>

        <p>        
            <a target="_blank" href="">Dryad</a><br />
            Dryad is a paid data repository primarily for medical data but also other types of data. It provides quality control and allows data publication only in connection with a corresponding paper.
        </p>

        <p>
            <a target="_blank" href="">Figshare</a><br />
            Figshare is a repository for various types of publications. It offers the possibility to publish negative data as well and supports altmetrics but is operated by a commercial provider (MacMillan Group / Nature).
        </p>

        <p>        
            <a target="_blank" href="">Zenodo</a><br />
            Zenodo is a platform for archiving and publishing various content and formats. It is supported by the European Commission and operated at CERN. It is available for research results from all disciplines, allows both text and data publications, and enables their linking. Zenodo is user-friendly and accessible but does not perform curation/quality control.
        </p>

        <p>        
            <a target="_blank" href="">EUDAT</a><br />
            EUDAT is a long-term EU project. It provides an infrastructure for securing, archiving, and publishing data through services like B2DROP and B2SHARE.
        </p>        
    </div>
</div>

<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#videos">
        <div class="tf-panel-collapse-heading">
        Videos
        </div>
    </a>
    <div id="videos" class="collapse tf-panel-collapse-body">
        <h2>Overviews</h2>
        <ul>
            <li><a target="_blank" href="https://www.youtube.com/watch?v=gYDb-GP1CA4">The what, why and how of data management planning (YouTube)</a></li>
            <li><a target="_blank" href="https://www.youtube.com/watch?v=nNBiCcBlwRA">How to avoid a data management nightmare (YouTube)</a></li>
            <li><a target="_blank" href="https://www.youtube.com/watch?v=PgqtiY7oZ6k">Persistent identifiers and data citation explained (YouTube)</a></li>
            <li><a target="_blank" href="https://www.youtube.com/watch?v=w9SCtL43vDM">'Unsere Kinder, die Forschungsdaten' Paul Vierkant beim #38 Science Slam Berlin (YouTube)</a></li>
        </ul>

        <h2>Data Privacy and Licensing</h2>
        <ul>
            <li><a target="_blank" href="https://www.youtube.com/watch?v=VF5A2JhiJug">Datenschutz einfach erklärt (YouTube)</a></li>
            <li><a target="_blank" href="https://www.youtube.com/watch?v=cwUiVUR7bWY">Wie ist das mit dem Urheberrecht? (YouTube)</a></li>
            <li><a target="_blank" href="https://www.youtube.com/watch?v=KNvhfiioqHc">Teil 1: Urheberrecht und freie Lizenzen (Grundbegriffe) (YouTube)</a></li>
            <li><a target="_blank" href="https://www.youtube.com/watch?v=N4E0eSBcjso">Teil 2: Urheberrecht und freie Lizenzen (Lizenzmodelle) (YouTube)</a></li>
            <li><a target="_blank" href="https://www.youtube.com/watch?v=Tvwp5LK_Wko">Open Data Licensing Animation - OERIPR Support (YouTube)</a></li>
        </ul>
    </div>
</div>
