<div class="table_content">
    <div class="table_content_header">
        <h1>Kriminologie</h1>
        <h3>Master of Arts (M.A.)</h3>
        <h2>Universität Hamburg</h2>
    </div>
    <table>
        <tr>
            <td>Studienform</td>
            <td>Sozialwissenschaftlich ausgerichteter berufsbegleitender Master of Arts für kriminologisch einschlägige Berufsgruppen (Polizei, Strafjustiz/-vollzug, Rechtspflege, Soziale Arbeit), anwendungsorientiert, interdisziplinär, Blended-Learning (Präsenz- & Onlinelehre)</td>
        </tr>
        <tr>
            <td>Inhalte</td>
            <td>Sozialwissenschaft, Rechtswissenschaft, Verwaltungswissenschaft, Psychologie, Soziale Arbeit<br />
                Grundlagen der Kriminologie: Theorien, Forschungsmethoden, Strafrechtssoziologie, Kontrollprotokolle und Kriminalitätsfurcht, Policing, Strafjustiz/-vollzug, alternative Reaktionen, aktuelle Diskussionen in Kriminologie<br />
                Erwerb wissenschaftlicher Qualifikation insbesondere für Leitungsaufgaben
            </td>
        </tr>
        <tr>
            <td>Semesteranzahl</td>
            <td>3 Semester</td>
        </tr>
        <tr>
            <td>Beginn</td>
            <td>Oktober</td>
        </tr>
        <tr>
            <td>ECTS</td>
            <td>60 ECTS</td>
        </tr>
        <tr>
            <td>Voraussetzungen</td>
            <td>
                Hochschulabschluss mit 240 ECTS* in einem Fach mit kriminologischen Bezügen (Soziologie, Psychologie, Rechtswissenschaft, etc.)<br />
                Mind. 1 Jahr einschlägige Berufserfahrung in kriminologisch einschlägigem Arbeitsfeld im Anschluss an Studium (darf nicht länger als ein halbes Jahr zurückliegen)<br />
                Aktuell in einem kriminologisch relevanten Arbeitsumfeld beschäftigt (Nachweis erforderlich)
            </td>
        </tr>
        <tr>
            <td>Studiengebühren</td>
            <td>3370€ für das gesamte Studium, zzgl. Semesterbeiträge</td>
        </tr>
        <tr>
            <td>Bewerbungszeitraum</td>
            <td>Februar -01.07.</td>
        </tr>
        <tr>
            <td>Bewerbungsprozess</td>
            <td>
                Online-Bewerbung, ggf. Auswahlverfahren, falls Zahl der Bewerbungen die Anzahl der Studienplätze überwiegt Gewichtung: 30% Ergebnis erster berufsqualifizierender Abschluss, 30% nachgewiesene Vorkenntnisse im Gebiert Kriminologie,<br />
                30% berufspraktische Erfahrung in kriminologischen Arbeitsfeldern, 10% Begründung Studienwahl<br />
                Benachrichtigung über Zulassung innerhalb von 4 Wochen nach Ablauf Bewerbungsfrist 
            </td>
        </tr>
        <tr>
            <td>Sonstiges</td>
            <td>* Bei Abschluss mit weniger als 240 ECTS/8 Semester Regelstudienzeit (z.B. BA Polizeivollzugsdienst oder Soziale Arbeit) müssen weitere Nachweise zum Ausgleich der fehlenden ECTS nachgewiesen werden:
                Weitere nachgewiesene Studienzeiten mit kriminologischen Bezügen im Umfang der fehlenden ECTS<br />
                ODER<br />
                Mind. 3 Jahre Berufserfahrung in kriminologisch einschlägigen Arbeitsfeld nach Erwerb des ersten berufsqualifizierenden Hochschulabschlusses (im Zeitpunkt der Bewerbung, ohne Ausbildungszeiten)
            </td>
        </tr>
        <tr>
            <td>Link zur Homepage</td>
            <td><a target="_blank" href="https://www.zfw.uni-hamburg.de/weiterbildung/gesundheit-psychologie-kriminologie/kriminologie.html">https://www.zfw.uni-hamburg.de/weiterbildung/gesundheit-psychologie-kriminologie/kriminologie.html</a></td>
        </tr>
    </table>

    <p class="table_content_footer kursiv">Stand: 24.6.2026</p>

</div>
