<div class="table_content">
    <div class="table_content_header">
        <h1>Kriminologie</h1>
        <h3>Master of Arts (M.A.)</h3>
        <h2>Universität Hamburg</h2>
    </div>
    <table>
        <tr>
            <td>Studienform</td>
            <td>sozialwissenschaftlich ausgerichteter berufsbegleitender Master of Arts für kriminologisch einschlägige Berufsgruppen (Polizei, Strafjustiz/-vollzug, Rechtspflege, Soziale Arbeit), anwendungsorientiert, interdisziplinär, Blended-Learning (Präsenz- & Onlinelehre)</td>
        </tr>
        <tr>
            <td>Inhalte</td>
            <td>Einführung in die Kriminologie, Theorien, Forschungsmethoden, Strafrechtssoziologie, Kontrollprotokolle und Kriminalitätsfurcht, Policing, Strafjustiz/-vollzug, alternative Reaktionen <br />
                Erwerb wissenschaftlicher Qualifikation insbesondere für Leitungsaufgaben
            </td>
        </tr>
        <tr>
            <td>Semesteranzahl</td>
            <td>3 Semester</td>
        </tr>
        <tr>
            <td>Beginn</td>
            <td>Wintersemester</td>
        </tr>
        <tr>
            <td>ECTS</td>
            <td>60 ECTS</td>
        </tr>
        <tr>
            <td>Voraussetzungen</td>
            <td>
                Hochschulabschluss mit 240 ECTS* in einem Fach mit kriminologischen Bezügen (Soziologie, Psychologie, Rechtswissenschaft, etc.) <br />
                mindestens ein Jahr einschlägige Berufserfahrung in kriminologisch einschlägigem Arbeitsfeld im Anschluss an das Studium (darf nicht länger als ein halbes Jahr zurückliegen)<br />
                aktuell in einem kriminologisch relevanten Arbeitsumfeld beschäftigt (Nachweis erforderlich)
            </td>
        </tr>
        <tr>
            <td>Studiengebühren</td>
            <td>5.550€ für das gesamte Studium, zzgl. Semesterbeiträge</td>
        </tr>
        <tr>
            <td>Bewerbungszeitraum</td>
            <td>März - 15.06.</td>
        </tr>
        <tr>
            <td>Bewerbungsprozess</td>
            <td>
                postalische Bewerbung, ggf. Auswahlverfahren, falls Zahl der Bewerbungen die Anzahl der Studienplätze überwiegt <br />
                Gewichtung: 30% Ergebnis erster berufsqualifizierender Abschluss, 30% nachgewiesene Vorkenntnisse im Gebiet Kriminologie, 30% berufspraktische Erfahrung in kriminologischen Arbeitsfeldern, 10% Begründung Studienwahl<br />
                Benachrichtigung über Zulassung innerhalb von 4 Wochen nach Ablauf der Bewerbungsfrist 
            </td>
        </tr>
        <tr>
            <td>Sonstiges</td>
            <td>
                * Bei Abschluss mit weniger als 240 ECTS/8 Semestern Regelstudienzeit (z.B. BA Polizeivollzugsdienst oder Soziale Arbeit) müssen weitere Nachweise zum Ausgleich der fehlenden ECTS erbracht werden:<br />
                weitere nachgewiesene Studienzeiten mit kriminologischen Bezügen im Umfang der fehlenden ECTS<br />
                ODER<br />
                mindestens drei Jahre Berufserfahrung in einem kriminologisch einschlägigen Arbeitsfeld nach Erwerb des ersten berufsqualifizierenden Hochschulabschlusses (zum Zeitpunkt der Bewerbung, ohne Ausbildungszeiten)
            </td>
        </tr>
        <tr>
            <td>Link zur Homepage</td>
            <td><a target="_blank" href="https://www.zfw.uni-hamburg.de/weiterbildung/gesundheit-psychologie-kriminologie/kriminologie.html">https://www.zfw.uni-hamburg.de/weiterbildung/gesundheit-psychologie-kriminologie/kriminologie.html</a></td>
        </tr>
    </table>

    <p class="table_content_footer kursiv">Stand: 15.7.2026</p>

</div>
