<div class="tf-background-body">
    <div id="content" class="container">
        <div class="row">
            <?=$this->content()->renderTranslated('panels/krimdok_and_fid'); ?>
            <?=$this->content()->renderTranslated('panels/news'); ?>
            <?=$this->content()->renderTranslated('panels/fid_services'); ?>
        </div>
        <div class="row">
            <?=$this->content()->renderTranslated('panels/literature'); ?>
            <?=$this->content()->renderTranslated('panels/partners'); ?>
            <?=$this->content()->renderTranslated('panels/forschungsdatenmanagement'); ?>
        </div>
    </div>
</div>

