<div class="tf-background-body">
    <div id="content" class="container">

        <div id="breaking_news" bis_skin_checked="1">
            <h4 class="text-center" style="margin-top: 20px; margin-bottom: 2px; padding: 20px;">
            ++ FID Kriminologie: Workshop ++ Mehr Informationen finden Sie <a href="/Content/events" class="text-warning" style="color:#a51e37;" target="_blank"><u>hier</u></a> ++
            </h4>
        </div>

        <div class="row">
            <?=$this->content()->renderTranslated('panels/krimdok_and_fid'); ?>
            <?=$this->content()->renderTranslated('panels/news'); ?>
            <?=$this->content()->renderTranslated('panels/fid_services'); ?>
        </div>
        <div class="row">
            <?=$this->content()->renderTranslated('panels/partners'); ?>
            <?=$this->content()->renderTranslated('panels/unsere_partner'); ?>
            <?=$this->content()->renderTranslated('panels/forschungsdatenmanagement'); ?>
        </div>
    </div>
</div>

