<h1 class="text-center" style="color: #a51e37;">Masterstudiengänge in Kriminologie und Viktimologie</h1>
    
<h2>International</h2>

<h3>Argentinien</h3>
<ul>
    <li><span class="city">Aconcagua:</span> <span class="program"><a target="_blank" href="https://www.uda.edu.ar/index.php/oferta-educativa-fpsi/carreras-de-posgrado/maestria-en-criminologia">Maestría en Criminología</a></span></li>
    <li><span class="city">Litoral:</span> <span class="program"><a target="_blank" href="https://www.unl.edu.ar/carreras/maestria-en-criminologia/">Maestría en Criminología</a></span></li>
    <li><span class="city">Buenos Aires (UCES):</span> <span class="program"><a target="_blank" href="https://www.uces.edu.ar/carreras-posgrados/ciencias-juridicas-y-politicas/maestria-ciencias-criminologico-forenses">Maestría en Ciencias Criminológico-Forenses</a></span></li>
    <li><span class="city">Quilmes:</span> <span class="program"><a target="_blank" href="https://www.unq.edu.ar/carrera/112-maestria-en-criminologia/">Maestría en Criminología</a></span></li>
    <li><span class="city">Virtuell:</span> <span class="program"><a target="_blank" href="https://www.universidadviu.com/es/master-criminologia">Maestría en Criminología: Delincuencia y Victimología Online</a></span></li>
</ul>

<h3>Argentinien</h3>
<ul>
    <li><span class="city">Bond:</span> <span class="program"><a target="_blank" href="https://bond.edu.au/program/master-of-criminology">Master of Criminology</a></span></li>
    <li><span class="city">Deakin:</span> <span class="program"><a target="_blank" href="https://www.deakin.edu.au/course/master-criminology">Master of Criminology</a></span></li>
    <li><span class="city">Melbourne:</span> <span class="program"><a target="_blank" href="https://study.unimelb.edu.au/find/courses/graduate/master-of-criminology/">Master of Criminology</a></span></li>
    <li><span class="city">Murdoch:</span> <span class="program"><a target="_blank" href="https://www.murdoch.edu.au/course/postgraduate/m1314">Master of Criminology</a></span></li>
    <li><span class="city">Sidney:</span> <span class="program"><a target="_blank" href="https://www.sydney.edu.au/courses/courses/pc/master-of-criminology.html">Master of Criminology</a></span></li>
</ul>

<h3>Kanada</h3>
<ul>
    <li><span class="city">Brantford:</span> <span class="program"><a target="_blank" href="https://www.wlu.ca/programs/human-and-social-sciences/graduate/criminology-ma/index.html">MA in Criminology</a></span></li>
    <li><span class="city">Ontario: (University): MA in Criminology</span></li>
    <li><span class="city">Ontario (Niagara University): MA in Criminal Justice Administration</span></li>
    <li><span class="city">Ottawa:</span> <span class="program"><a target="_blank" href="https://catalogue.uottawa.ca/en/graduate/master-arts-criminology/">MA in Criminology</a></span></li>
    <li><span class="city">Toronto</span> <span class="program"><a target="_blank" href="https://www.crimsl.utoronto.ca/graduate/prospective-graduate-students/admission-masters-program">(University): MA in Criminology and Sociolegal Studies</a></span></li>
    <li><span class="city">Toronto</span> <span class="program"><a target="_blank" href="https://www.torontomu.ca/criminology/graduate/">(Metropolitan University): MA in Criminology and Social Justice</a></span></li>
    <li><span class="city">Vancouver:</span> <span class="program"><a target="_blank" href="https://www.sfu.ca/criminology/graduate/programs/ma.html">MA in Criminology</a></span></li>
</ul>

<h3>Südafrika</h3>
<ul>
    <li><span class="city">Fort Hare:</span> <span class="program"><a target="_blank" href="https://www.ufh.ac.za/course/master-of-social-science-in-criminology">Master of Social Science in Criminology</a></span></li>
    <li><span class="city">Kapstadt:</span> <span class="program"><a target="_blank" href="https://law.uct.ac.za/criminology/our-courses/masters-programme-criminology-law-society">MPhil in Criminology, Law & Society</a></span></li>
    <li><span class="city">Pretoria:</span> <span class="program"><a target="_blank" href="https://www.up.ac.za/programmes/postgraduate/ma-specialising-criminology/2026">MA in Criminology</a></span></li>
</ul>

<h3>Südafrika</h3>
<ul>
    <li><span class="city">Florida:</span> <span class="program"><a target="_blank" href="https://criminology.fsu.edu/degrees/graduate-programs/one-year-master-of-science-in-criminology">MS in Criminology</a></span></li>
    <li><span class="city">Michigan-Dearborn:</span> <span class="program"><a target="_blank" href="https://umdearborn.edu/academics/program/criminology-and-criminal-justice-ms">MS Criminology and Criminal Justice</a></span></li>
    <li><span class="city">Pennsylvania:</span> <span class="program"><a target="_blank" href="https://crim.sas.upenn.edu/graduate/master-science-criminology">MS in Criminology</a></span></li>
    <li><span class="city">San Jose:</span> <span class="program"><a target="_blank" href="https://crim.sas.upenn.edu/graduate/master-science-criminology://www.sjsu.edu/justicestudies/degrees/graduate/masters-criminology.php">MS in Criminology Concentration in Global Criminology</a></span></li>
    <li><span class="city">Texas:</span> <span class="program"><a target="_blank" href="https://www.tamusa.edu/academics/college-of-arts-and-sciences/criminology-political-science/criminology/masters-science.html">MS Criminology and Criminal Justice</a></span></li>
</ul>