<h2>Stellenausschreibungen</h2>
<ul>
	<li>Hochschule für Polizei und öffentliche Verwaltung NRW am Studienort Duisburg: <a target="_blank" href="https://www.hspv.nrw.de/ausschreibungen/ausschreibung/forschungsprojekt-demenz">Regierungsbeschäftigte (m/w/d) für die Mitarbeit im Forschungsprojekt „Menschenrechtskonforme Polizeiarbeit bei Polizeieinsätzen mit Menschen mit Demenz“ </a> 50 %, befristet (Deadline: 10.03.2023)</li>
</ul>
