<h2>Stellenausschreibungen</h2>
<ul>
    <li>Max Planck Institut zur Forschung von Kriminalität, Sicherheit and Recht, Abteilung Kriminologie, Freiburg im Breisgau,
        <a target="_blank" href="https://www.mpg.de/24149302/phd-position-k-25-02">PhD Position, Partners in Crime: Understanding Peer Offending through Virtual Reality (m/w/d, E 13, TVöD Bund)</a> (befristet auf 4 Jahre, in Vollzeit, Deadline: 09.03.2025)
    </li>
</ul>
