<h2>Stellenausschreibungen</h2>
<ul>
	<li>Landeskriminalamt NRW: <a target="_blank" href="https://lka.polizei.nrw/artikel/wissenschaftliche-mitarbeiterin-wissenschaftlicher-mitarbeiter-mwd">Wissenschaftliche:r Mitarbeiter:in (m/w/d) der Fachrichtung Soziologie, Sozialwissenschaft oder Psychologie</a> Vollzeit (Deadline: 21.02.2023)</li>
	<li>Deutsche Hochschule der Polizei (DHPol) in Münster: <a target="_blank" href="https://www.dhpol.de/Stellenausschreibung_FG_III_1_WMA_Impress_210223.pdf">Wissenschaftliche:r Mitarbeiter:in</a> 75 %, befristet(Deadline: 21.02.2023)</li>
	<li>DBH-Fachverband für Soziale Arbeit, Strafrecht und Kriminalpolitik: <a target="_blank" href="https://www.dbh-online.de/aktuelles/stellenmarkt/wissenschaftlicher-mitarbeiterin-wmd-deradikalisierung-und">Wissenschaftliche:r Mitarbeiter:in - Deradikalisierung und Wiedereingliederung im Bereich der Straffälligenhilfe</a> 50 % (Deadline: 01.03.2023)</li>
	<li>Hochschule für Wirtschaft und Recht Berlin: Fachbereich 5 „Polizei und Sicherheitsmanagement“: <a target="_blank" href="https://karriere.hwr-berlin.de/jobposting/2d19dbd8a3a2bacd3136f773aa678ef4e590d1360">Professor:in (m/w/d) für Kriminologie</a> (Deadline: 02.03.2023)</li>
</ul>
