<h1>Revistas</h1>

<p>
    KrimDok contiene unas 4.700 referencias de revistas de criminología alemanas y extranjeras publicadas en formato impreso, 
    electrónico, híbrido o (total o parcialmente) retrodigitalizado y que los editores ponen a disposición para su venta o sin licencia. 
    La mayoría de las referencias son revistas que han cambiado de título o han dejado de publicarse. 
    Con el fin de simplificar el acceso a los textos completos de acceso abierto actuales y relevantes desde el punto de vista
    criminológico, se han confeccionado listas por tema de las revistas libres de licencia. Para más información sobre 
    las revistas publicadas actualmente, así como sobre la evaluación de las contribuciones individuales para KrimDok, 
    consulte las listas que figuran a continuación.
</p>
<ul>
    <li><a target="_blank" href="https://krimdok.uni-tuebingen.de/krimdok_docs/Journals_2026.pdf">Lista de revistas ya evaluadas para KrimDok (pdf)</a></li>
    <li><a target="_blank" href="https://krimdok.uni-tuebingen.de/krimdok_docs/Journals_OA.pdf">Lista de revistas de acceso abierto de interés criminológico (pdf)</a></li>
    <li><a target="_blank" href="https://krimdok.uni-tuebingen.de/krimdok_docs/Journals_Nationallizenz_Lizenzen_aktualisiert.pdf">Lista de revistas de relevancia criminológica con licencia nacional (pdf)</a></li>
</ul>
<p> 
    La lista de revistas de relevancia criminológica con licencia nacional incluye revistas de interés criminológico que tienen una 
    licencia nacional o de alianza según las bases de datos de 
    revistas <a target="_blank" href="https://zdb-katalog.de/index.xhtml">ZDB</a> y
    <a target="_blank" href="https://ezb.uni-regensburg.de/index.phtml?bibid=UBTUE&colors=7&lang=en">EZB</a>. Las llamadas “licencias de alianza” son 
    financiadas en parte por la <a target="_blank" href="https://www.dfg.de/en">DFG</a>, lo que reduce su coste de adquisición para las instituciones. Las 
    licencias nacionales son financiadas en su totalidad por la <a target="_blank" href="https://www.dfg.de/en">DFG</a>, por lo que el acceso a estas 
    revistas de pago está disponible para todas las universidades e instituciones de investigación financiadas predominantemente con 
    fondos públicos de Alemania. Muchos de los productos adquiridos mediante una licencia nacional pueden ser utilizados por 
    investigadores y estudiantes, así como por particulares interesados en el tema. Los particulares que no tengan 
    acceso a través de una red universitaria o de su biblioteca académica 
    pueden registrarse para su uso bajo: <a target="_blank" href="https://www.nationallizenzen.de/ind_inform_registration">https://www.nationallizenzen.de/ind_inform_registration</a>. El requisito previo es tener residencia 
    permanente en Alemania. No obstante, las bibliotecas universitarias y estatales suelen ofrecer a sus usuarios registrados (externos) acceso a los 
    productos de licencia nacional, lo que significa que las personas registradas como usuarios de dichas 
    bibliotecas no necesitan registrarse por separado como usuarios individuales.
</p>