<h2>Kooperierende Institutionen</h2>
<style>
.container .list-group a{
    margin: 10px 0;
}
</style>
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="bs-example" data-example-id="list-group-custom-content">
            <div class="col-md-12 container">
                <div class="list-group">
                    <a target="_blank" href="http://www.uni-heidelberg.de/institute/fak2/krimi/index.html" class="list-group-item section-home">
                        <div class="media">
                            <div class="tf-media-left-center" style="width: 25%;">
                                <img src="<?=$this->imageLink('partners/heidelberg.jpg') ?>" class="tf-thumbnail-center"/>
                            </div>
                            <div class="tf-media-body-center" style="width: 75%;">
                                <h4 class="list-group-item-heading">Institut für Kriminologie der Universität Heidelberg<br/>(Mitgründer von KrimDok)</h4>
                            </div>
                        </div>
                    </a>
                    <a target="_blank" href="https://www.mpicc.de/de/home.cfm" class="list-group-item section-home">
                        <div class="media">
                            <div class="tf-media-left-center" style="width: 25%;">
                                <img src="<?=$this->imageLink('partners/max_planck_institut.png') ?>" class="tf-thumbnail-center"/>
                            </div>
                            <div class="tf-media-body-center" style="width: 75%;">
                                <h4 class="list-group-item-heading">Max-Planck-Institut zur Erforschung von Kriminalität, Sicherheit und Recht<br/>(Freiburg i. Br.)</h4>
                            </div>
                        </div>
                    </a>
                    <a target="_blank" href="https://www.krimz.de/" class="list-group-item section-home">
                        <div class="media">
                            <div class="tf-media-left-center" style="width: 25%;">
                                <img src="<?=$this->imageLink('partners/krimz.png') ?>" class="tf-thumbnail-center"/>
                            </div>
                            <div class="tf-media-body-center" style="width: 75%;">
                                <h4 class="list-group-item-heading">Kriminologische Zentralstelle e.V.<br/>(Wiesbaden)</h4>
                            </div>
                        </div>
                    </a>
                    <a target="_blank" href="https://kfn.de/" class="list-group-item section-home">
                        <div class="media">
                            <div class="tf-media-left-center" style="width: 25%;">
                                <img src="<?=$this->imageLink('partners/KFNLOGO_kurz.png') ?>" class="tf-thumbnail-center"/>
                            </div>
                            <div class="tf-media-body-center" style="width: 75%;">
                                <h4 class="list-group-item-heading">Kriminologisches Forschungsinstitut Niedersachsen e.V.</h4>
                            </div>
                        </div>
                    </a>
                    <a target="_blank" href="http://www.iisj.net/en/library/about-library" class="list-group-item section-home">
                        <div class="media">
                            <div class="tf-media-left-center" style="width: 25%;">
                                <img src="<?=$this->imageLink('partners/onati.jpg') ?>" class="tf-thumbnail-center"/>
                            </div>
                            <div class="tf-media-body-center" style="width: 75%;">
                                <h4 class="list-group-item-heading">Oñati International Institute for the Sociology of Law</h4>
                            </div>
                        </div>
                    </a>
                    <a target="_blank" href="https://www.praeventionstag.de" class="list-group-item section-home">
                        <div class="media">
                            <div class="tf-media-left-center" style="width: 25%;">
                                <img src="<?=$this->imageLink('partners/DPT_Logo_Institut_klein_rgb.jpg') ?>" class="tf-thumbnail-center"/>
                            </div>
                            <div class="tf-media-body-center" style="width: 75%;">
                                <h4 class="list-group-item-heading">DPT Institut für angewandte Präventionsforschung</h4>
                            </div>
                        </div>
                    </a>
                    <a target="_blank" href="https://www.kriminologie.de/index.php/krimoj" class="list-group-item section-home">
                        <div class="media">
                            <div class="tf-media-left-center" style="width: 25%;">
                                <img src="<?=$this->imageLink('partners/Logo-KrimOJ-wordmarke-claime_cmyk_m.jpg') ?>" class="tf-thumbnail-center"/>
                            </div>
                            <div class="tf-media-body-center" style="width: 75%;">
                                <h4 class="list-group-item-heading">Kriminologie - Das Online-Journal</h4>
                            </div>
                        </div>
                    </a>
                    <a target="_blank" href="https://www.qualiservice.org/de/" class="list-group-item section-home">
                        <div class="media">
                            <div class="tf-media-left-center" style="width: 25%;">
                                <img src="<?=$this->imageLink('partners/Qualiservice_Logo.png') ?>" class="tf-thumbnail-center"/>
                            </div>
                            <div class="tf-media-body-center" style="width: 75%;">
                                <h4 class="list-group-item-heading">Qualiservice Forschungsdatenzentrum für qualitative sozialwissenschaftliche Forschungsdaten</h4>
                            </div>
                        </div>
                    </a>
                    <a target="_blank" href="https://www.dbh-online.de" class="list-group-item section-home">
                        <div class="media">
                            <div class="tf-media-left-center" style="width: 25%;">
                                <img src="<?=$this->imageLink('partners/DBH_LOGO_4z_positiv_72dpi_RGB.png') ?>" class="tf-thumbnail-center"/>
                            </div>
                            <div class="tf-media-body-center" style="width: 75%;">
                                <h4 class="list-group-item-heading">DBH - Fachverband für Soziale Arbeit, Strafrecht und Kriminalpolitik</h4>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>

