<h2>Instituciones colaboradoras</h2>
<style>
.container .list-group a{
    margin: 10px 0;
}
</style>
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="bs-example" data-example-id="list-group-custom-content">
            <div class="col-md-12 container">
                <div class="list-group">
                    <a target="_blank" href="http://www.uni-heidelberg.de/institute/fak2/krimi/index.html" class="list-group-item section-home">
                        <div class="media">
                            <div class="media-left" style="width: 25%;">
                                <img src="<?=$this->imageLink('partners/heidelberg.jpg') ?>" class="thumbnail"/>
                            </div>
                            <div class="media-body" style="width: 75%;">
                                <h4 class="list-group-item-heading">Instituto de Criminología de la Universidad de Heidelberg <br/>(cofundador de KrimDok)</h4>
                            </div>
                        </div>
                    </a>
                    <a target="_blank" href="https://www.mpicc.de/de/home.cfm" class="list-group-item section-home">
                        <div class="media">
                            <div class="media-left" style="width: 25%;">
                                <img src="<?=$this->imageLink('partners/max_planck_institut.png') ?>" class="thumbnail"/>
                            </div>
                            <div class="media-body" style="width: 75%;">
                                <h4 class="list-group-item-heading">Instituto Max Planck para el Estudio de la Delincuencia, la Seguridad y el Derecho <br/> (Friburgo de Brisgovia)</h4>
                            </div>
                        </div>
                    </a>
                    <a target="_blank" href="https://www.krimz.de/" class="list-group-item section-home">
                        <div class="media">
                            <div class="media-left" style="width: 25%;">
                                <img src="<?=$this->imageLink('partners/krimz.png') ?>" class="thumbnail"/>
                            </div>
                            <div class="media-body" style="width: 75%;">
                                <h4 class="list-group-item-heading">Kriminologische Zentralstelle e.V.<br/>(Wiesbaden)</h4>
                            </div>
                        </div>
                    </a>
                    <a target="_blank" href="https://www.fid-lizenzen.de/" class="list-group-item section-home">
                        <div class="media">
                            <div class="media-left" style="width: 25%;">
                                <img src="<?=$this->imageLink('partners/KFNLOGO_kurz.png') ?>" class="thumbnail"/>
                            </div>
                            <div class="media-body" style="width: 75%;">
                                <h4 class="list-group-item-heading">Kompetenzzentrum für Lizenzierung (KfL)</h4>
                            </div>
                        </div>
                    </a>
                    <a target="_blank" href="http://www.iisj.net/en/library/about-library" class="list-group-item section-home">
                        <div class="media">
                            <div class="media-left" style="width: 25%;">
                                <img src="<?=$this->imageLink('partners/onati.jpg') ?>" class="thumbnail"/>
                            </div>
                            <div class="media-body" style="width: 75%;">
                                <h4 class="list-group-item-heading">Instituto Internacional de Sociología Jurídica de Oñati</h4>
                            </div>
                        </div>
                    </a>
                    <a target="_blank" href="https://www.praeventionstag.de" class="list-group-item section-home">
                        <div class="media">
                            <div class="media-left" style="width: 25%;">
                                <img src="<?=$this->imageLink('partners/DPT_Logo_Institut_klein_rgb.jpg') ?>" class="thumbnail"/>
                            </div>
                            <div class="media-body" style="width: 75%;">
                                <h4 class="list-group-item-heading">DPT Institut für angewandte Präventionsforschung</h4>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>

