<h2>Kooperierende Institutionen</h2>
<!--
<div class="row">
    <div class="col-xs-12 col-sm-6 partner">
        <h3>Institut für Kriminologie der Universität Heidelberg<br/>(Mitgründer von KrimDok)</h3>
        <a target="_blank" href="http://www.uni-heidelberg.de/institute/fak2/krimi/index.html">
            <img src="<?=$this->imageLink('partners/heidelberg.jpg') ?>" height="100"/>
        </a>
    </div>
    <div class="col-xs-12 col-sm-6 partner">
        <h3>Max-Planck-Institut zur Erforschung von Kriminalität, Sicherheit und Recht<br/>(Freiburg i. Br.)</h3>
        <a target="_blank" href="https://www.mpicc.de/de/home.cfm">
            <img src="<?=$this->imageLink('partners/max_planck_institut.png') ?>"/>
        </a>
    </div>
</div>
<div class="row">
    <div class="col-xs-12 col-sm-6 partner">
        <h3>Kriminologische Zentralstelle e.V.<br/>(Wiesbaden)</h3>
        <a target="_blank" href="https://www.krimz.de/">
            <img src="<?=$this->imageLink('partners/krimz.png') ?>"/>
        </a>
    </div>
    <div class="col-xs-12 col-sm-6 partner">
        <h3>Oñati International Institute for the Sociology of Law</h3>
        <a target="_blank" href="http://www.iisj.net/en/library/about-library">
            <img src="<?=$this->imageLink('partners/onati.jpg') ?>" height="100"/>
        </a>
    </div>
</div>
-->
<style>
.container .list-group a{
    margin: 10px 0;
}
</style>
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="bs-example" data-example-id="list-group-custom-content">
            <div class="col-md-12 container">
                <div class="list-group"> 
                    <a target="_blank" href="http://www.uni-heidelberg.de/institute/fak2/krimi/index.html" class="list-group-item section-home">
                        <div class="media">
                            <div class="media-left" style="width: 25%;">
                                <img src="<?=$this->imageLink('partners/heidelberg.jpg') ?>" class="thumbnail"/>
                            </div>
                            <div class="media-body" style="width: 75%;">
                                <h4 class="list-group-item-heading">Institut für Kriminologie der Universität Heidelberg<br/>(Mitgründer von KrimDok)</h4>
                            </div>
                        </div>
                    </a>
                    <a target="_blank" href="https://www.mpicc.de/de/home.cfm" class="list-group-item section-home">
                        <div class="media">
                            <div class="media-left" style="width: 25%;">
                                <img src="<?=$this->imageLink('partners/max_planck_institut.png') ?>" class="thumbnail"/>
                            </div>
                            <div class="media-body" style="width: 75%;">
                                <h4 class="list-group-item-heading">Max-Planck-Institut zur Erforschung von Kriminalität, Sicherheit und Recht<br/>(Freiburg i. Br.)</h4>
                            </div>
                        </div>
                    </a>
                    <a target="_blank" href="https://www.krimz.de/" class="list-group-item section-home">
                        <div class="media">
                            <div class="media-left" style="width: 25%;">
                                <img src="<?=$this->imageLink('partners/krimz.png') ?>" class="thumbnail"/>
                            </div>
                            <div class="media-body" style="width: 75%;">
                                <h4 class="list-group-item-heading">Kriminologische Zentralstelle e.V.<br/>(Wiesbaden)</h4>
                            </div>
                        </div>
                    </a>
                    <a target="_blank" href="http://www.iisj.net/en/library/about-library" class="list-group-item section-home">
                        <div class="media">
                            <div class="media-left" style="width: 25%;">
                                <img src="<?=$this->imageLink('partners/onati.jpg') ?>" class="thumbnail"/>
                            </div>
                            <div class="media-body" style="width: 75%;">
                                <h4 class="list-group-item-heading">Oñati International Institute for the Sociology of Law</h4>
                            </div>
                        </div>
                    </a>
                </div> 
            </div>
        </div>
    </div>
</div>

