<h2>Instituciones colaboradoras</h2>
<style>
.container .list-group a{
    margin: 10px 0;
}
</style>
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="bs-example" data-example-id="list-group-custom-content">
            <div class="col-md-12 container">
                <div class="list-group">
                    <a target="_blank" href="http://www.uni-heidelberg.de/institute/fak2/krimi/index.html" class="list-group-item section-home">
                        <div class="media">
                            <div class="tf-media-left-center" style="width: 25%;">
                                <img src="<?=$this->imageLink('partners/heidelberg.jpg') ?>" class="tf-thumbnail-center"/>
                            </div>
                            <div class="tf-media-body-center" style="width: 75%;">
                                <h4 class="list-group-item-heading">Instituto de Criminología de la Universidad de Heidelberg <br/>(cofundador de KrimDok)</h4>
                            </div>
                        </div>
                    </a>
                    <a target="_blank" href="https://www.mpicc.de/de/home.cfm" class="list-group-item section-home">
                        <div class="media">
                            <div class="tf-media-left-center" style="width: 25%;">
                                <img src="<?=$this->imageLink('partners/max_planck_institut.png') ?>" class="tf-thumbnail-center"/>
                            </div>
                            <div class="tf-media-body-center" style="width: 75%;">
                                <h4 class="list-group-item-heading">Instituto Max Planck para el Estudio de la Delincuencia, la Seguridad y el Derecho <br/> (Friburgo de Brisgovia)</h4>
                            </div>
                        </div>
                    </a>
                    <a target="_blank" href="https://www.krimg.de/drupal/" class="list-group-item section-home">
                        <div class="media">
                            <div class="tf-media-left-center" style="width: 20%; text-align:center;">
                                <img src="<?=$this->imageLink('partners/krimg_logo.gif') ?>" class="tf-thumbnail-center"/>
                            </div>
                            <div class="tf-media-body-center" style="width: 75%; padding-left:25px;">
                                <h4 class="list-group-item-heading">Sociedad Criminológica,<br/> Asociación Científica de Criminología en Alemania, Austria y Suiza</h4>
                            </div>
                        </div>
                    </a>
                    <a target="_blank" href="https://www.krimz.de/" class="list-group-item section-home">
                        <div class="media">
                            <div class="tf-media-left-center" style="width: 25%;">
                                <img src="<?=$this->imageLink('partners/krimz.png') ?>" class="tf-thumbnail-center"/>
                            </div>
                            <div class="tf-media-body-center" style="width: 75%;">
                                <h4 class="list-group-item-heading">Oficina Central Criminológica (KrimZ)</h4>
                            </div>
                        </div>
                    </a>
                    <a target="_blank" href="https://kfn.de/" class="list-group-item section-home">
                        <div class="media">
                            <div class="tf-media-left-center" style="width: 25%;">
                                <img src="<?=$this->imageLink('partners/KFNLOGO_kurz.png') ?>" class="tf-thumbnail-center"/>
                            </div>
                            <div class="tf-media-body-center" style="width: 75%;">
                                <h4 class="list-group-item-heading">El Instituto de Investigación Criminológica de Baja Sajonia</h4>
                            </div>
                        </div>
                    </a>
                    <a target="_blank" href="http://www.iisj.net/en/library/about-library" class="list-group-item section-home">
                        <div class="media">
                            <div class="tf-media-left-center" style="width: 25%;">
                                <img src="<?=$this->imageLink('partners/onati.jpg') ?>" class="tf-thumbnail-center"/>
                            </div>
                            <div class="tf-media-body-center" style="width: 75%;">
                                <h4 class="list-group-item-heading">Instituto Internacional de Sociología Jurídica de Oñati</h4>
                            </div>
                        </div>
                    </a>
                    <a target="_blank" href="https://www.praeventionstag.de" class="list-group-item section-home">
                        <div class="media">
                            <div class="tf-media-left-center" style="width: 25%;">
                                <img src="<?=$this->imageLink('partners/DPT_Logo_Institut_klein_rgb.jpg') ?>" class="tf-thumbnail-center"/>
                            </div>
                            <div class="tf-media-body-center" style="width: 75%;">
                                <h4 class="list-group-item-heading">DPT Instituto de Investigación Aplicada en Prevención</h4>
                            </div>
                        </div>
                    </a>
                    <a target="_blank" href="https://www.kriminologie.de/index.php/krimoj" class="list-group-item section-home">
                        <div class="media">
                            <div class="tf-media-left-center" style="width: 25%;">
                                <img src="<?=$this->imageLink('partners/Logo-KrimOJ-wordmarke-claime_cmyk_m.jpg') ?>" class="tf-thumbnail-center"/>
                            </div>
                            <div class="tf-media-body-center" style="width: 75%;">
                                <h4 class="list-group-item-heading">Criminología - La revista en línea</h4>
                            </div>
                        </div>
                    </a>
                    <a target="_blank" href="https://www.qualiservice.org/de/" class="list-group-item section-home">
                        <div class="media">
                            <div class="tf-media-left-center" style="width: 25%;">
                                <img src="<?=$this->imageLink('partners/Qualiservice_Logo.png') ?>" class="tf-thumbnail-center"/>
                            </div>
                            <div class="tf-media-body-center" style="width: 75%;">
                                <h4 class="list-group-item-heading">Centro de datos de investigación para datos cualitativos de investigación en ciencias sociales</h4>
                            </div>
                        </div>
                    </a>
                    <a target="_blank" href="https://www.dbh-online.de" class="list-group-item section-home">
                        <div class="media">
                            <div class="tf-media-left-center" style="width: 25%;">
                                <img src="<?=$this->imageLink('partners/DBH_LOGO_4z_positiv_72dpi_RGB.png') ?>" class="tf-thumbnail-center"/>
                            </div>
                            <div class="tf-media-body-center" style="width: 75%;">
                                <h4 class="list-group-item-heading">Asociación profesional de trabajo social, derecho penal y política criminal</h4>
                            </div>
                        </div>
                    </a>
                    <a target="_blank" href="https://kriminalpraevention.de/" class="list-group-item section-home">
                        <div class="media">
                            <div class="tf-media-left-center" style="width: 20%;">
                                <img src="<?=$this->imageLink('partners/DFK_fin_mSchriftzug.jpg') ?>" class="tf-thumbnail-center"/>
                            </div>
                            <div class="tf-media-body-center" style="width: 75%; padding-left:28px;">
                                <h4 class="list-group-item-heading">Foro Alemán para la Prevención de la Delincuencia</h4>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>

