<h3>Kooperierende FIDs</h3>
<p>Als Fachinformationsdienst für Kriminologie arbeiten wir eng mit anderen Fachinformationsdiensten zusammen, 
    darunter dem Fachinformationsdienst Religionswissenschaften/Theologie und dem FID-Verbund <a href="https://wikis.sub.uni-hamburg.de/webis/index.php/FID-Netzwerk_für_Rechts-,_Wirtschafts-_und_Sozialwissenschaften_/_REWISO%2B">ReWiSo+</a>. 
    Wir streben kontinuierlich weitere Kooperationen an, um der Fachcommunity ein breites Spektrum an fachspezifischen 
    Informationen und Ressourcen bereitzustellen.</p>