<h3>Cooperating FIDs</h3>
<p>As specialized information service (FID) for criminology, 
    we collaborate closely with other FIDs, such as those dedicated to religious studies/theology and the FID network <a href="https://wikis.sub.uni-hamburg.de/webis/index.php/FID-Netzwerk_für_Rechts-,_Wirtschafts-_und_Sozialwissenschaften_/_REWISO%2B">ReWiSo+</a>. 
    Our goal is to foster ongoing partnerships and expand cooperation, ensuring a comprehensive range of subject-specific information and resources for the community.</p>