<h2>Cooperating Institutions</h2>
<style>
.container .list-group a{
    margin: 10px 0;
}
</style>
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="bs-example" data-example-id="list-group-custom-content">
            <div class="col-md-12 container">
                <div class="list-group">
                    <a target="_blank" href="https://www.jura.uni-heidelberg.de/krimi/index.html" class="list-group-item section-home">
                        <div class="media">
                            <div class="tf-media-left-center" style="width: 25%;">
                                <img src="<?=$this->imageLink('partners/heidelberg.jpg') ?>" class="tf-thumbnail-center"/>
                            </div>
                            <div class="tf-media-body-center" style="width: 75%;">
                                <h4 class="list-group-item-heading">Institute for Criminology at the University of Heidelberg <br/>(Co-Founder of KrimDok)</h4>
                            </div>
                        </div>
                    </a>
                    <a target="_blank" href="https://csl.mpg.de/en" class="list-group-item section-home">
                        <div class="media">
                            <div class="tf-media-left-center" style="width: 25%;">
                                <img src="<?=$this->imageLink('partners/max_planck_institut.png') ?>" class="tf-thumbnail-center"/>
                            </div>
                            <div class="tf-media-body-center" style="width: 75%;">
                                <h4 class="list-group-item-heading">Max Planck Institute for the Study of Crime, Security and Law<br/>(Freiburg i. Br.)</h4>
                            </div>
                        </div>
                    </a>
                    <a target="_blank" href="https://www.krimg.de/drupal/" class="list-group-item section-home">
                        <div class="media">
                            <div class="tf-media-left-center" style="width: 20%; text-align:center;">
                                <img src="<?=$this->imageLink('partners/krimg_logo.gif') ?>" class="tf-thumbnail-center"/>
                            </div>
                            <div class="tf-media-body-center" style="width: 75%; padding-left:25px;">
                                <h4 class="list-group-item-heading">Society of Criminology in Germany, Austria and Switzerland</h4>
                            </div>
                        </div>
                    </a>
                    <a target="_blank" href="https://www.krimz.de/en/index.html" class="list-group-item section-home">
                        <div class="media">
                            <div class="tf-media-left-center" style="width: 25%;">
                                <img src="<?=$this->imageLink('partners/krimz.png') ?>" class="tf-thumbnail-center"/>
                            </div>
                            <div class="tf-media-body-center" style="width: 75%;">
                                <h4 class="list-group-item-heading">Centre for Criminology<br/>(Wiesbaden)</h4>
                            </div>
                        </div>
                    </a>
                    <a target="_blank" href="https://kfn.de/en/home/" class="list-group-item section-home">
                        <div class="media">
                            <div class="tf-media-left-center" style="width: 25%;">
                                <img src="<?=$this->imageLink('partners/KFNLOGO_kurz.png') ?>" class="tf-thumbnail-center"/>
                            </div>
                            <div class="tf-media-body-center" style="width: 75%;">
                                <h4 class="list-group-item-heading">Criminological Research Institute of Lower Saxony</h4>
                            </div>
                        </div>
                    </a>
                    <a target="_blank" href="http://www.iisj.net/en/library/about-library" class="list-group-item section-home">
                        <div class="media">
                            <div class="tf-media-left-center" style="width: 25%;">
                                <img src="<?=$this->imageLink('partners/onati.jpg') ?>" class="tf-thumbnail-center"/>
                            </div>
                            <div class="tf-media-body-center" style="width: 75%;">
                                <h4 class="list-group-item-heading">Oñati International Institute for the Sociology of Law</h4>
                            </div>
                        </div>
                    </a>
                    <a target="_blank" href="https://www.praeventionstag.de/nano.cms/31-gcocp-congress-programme-overview" class="list-group-item section-home">
                        <div class="media">
                            <div class="tf-media-left-center" style="width: 25%;">
                                <img src="<?=$this->imageLink('partners/DPT_Logo_Institut_klein_rgb.jpg') ?>" class="tf-thumbnail-center"/>
                            </div>
                            <div class="tf-media-body-center" style="width: 75%;">
                                <h4 class="list-group-item-heading">DPT Institute for Applied Prevention Research</h4>
                            </div>
                        </div>
                    </a>
                    <a target="_blank" href="https://www.kriminologie.de/index.php/krimoj" class="list-group-item section-home">
                        <div class="media">
                            <div class="tf-media-left-center" style="width: 25%;">
                                <img src="<?=$this->imageLink('partners/Logo-KrimOJ-wordmarke-claime_cmyk_m.jpg') ?>" class="tf-thumbnail-center"/>
                            </div>
                            <div class="tf-media-body-center" style="width: 75%;">
                                <h4 class="list-group-item-heading">Criminology - The Online Journal</h4>
                            </div>
                        </div>
                    </a>
                    <a target="_blank" href="https://www.qualiservice.org/en/" class="list-group-item section-home">
                        <div class="media">
                            <div class="tf-media-left-center" style="width: 25%;">
                                <img src="<?=$this->imageLink('partners/Qualiservice_Logo.png') ?>" class="tf-thumbnail-center"/>
                            </div>
                            <div class="tf-media-body-center" style="width: 75%;">
                                <h4 class="list-group-item-heading">Qualiservice - Data Service Center for Qualitative Social Science Research Data</h4>
                            </div>
                        </div>
                    </a>
                    <a target="_blank" href="https://www.dbh-online.de" class="list-group-item section-home">
                        <div class="media">
                            <div class="tf-media-left-center" style="width: 25%;">
                                <img src="<?=$this->imageLink('partners/DBH_LOGO_4z_positiv_72dpi_RGB.png') ?>" class="tf-thumbnail-center"/>
                            </div>
                            <div class="tf-media-body-center" style="width: 75%;">
                                <h4 class="list-group-item-heading">DBH - Professional Association for Social Work, Criminal Law and Criminal Policy</h4>
                            </div>
                        </div>
                    </a>
                    <a target="_blank" href="https://kriminalpraevention.de/" class="list-group-item section-home">
                        <div class="media">
                            <div class="tf-media-left-center" style="width: 20%;">
                                <img src="<?=$this->imageLink('partners/DFK_fin_mSchriftzug.jpg') ?>" class="tf-thumbnail-center"/>
                            </div>
                            <div class="tf-media-body-center" style="width: 75%; padding-left:28px;">
                                <h4 class="list-group-item-heading">German Forum for Crime Prevention Foundation</h4>
                            </div>
                        </div>
                    </a>
                    <a target="_blank" href="https://www.konsortswd.de/en/" class="list-group-item section-home">
                        <div class="media">
                            <div class="tf-media-left-center" style="width: 25%;">
                                <img src="<?=$this->imageLink('partners/KonsortSWD-NFDI4Society-300.png') ?>" class="tf-thumbnail-center"/>
                            </div>
                            <div class="tf-media-body-center" style="width: 75%; padding-left:2px;">
                                <h4 class="list-group-item-heading">KonsortSWD - Consortium for the Social, Behavioral, Educational and Economic Sciences in the National Research Data Infrastructure</h4>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>

