<div class="tf-background-body">
    <div id="content" class="container">
        <div class="row">
            <?=$this->content()->renderTranslated('panels/krimdok'); ?>
            <?=$this->content()->renderTranslated('panels/fid'); ?>
            <?=$this->content()->renderTranslated('panels/acquisition'); ?>
            <?=$this->content()->renderTranslated('panels/fulltexts'); ?>
            <?=$this->content()->renderTranslated('panels/zweitveroeffentlichungsservice'); ?>
            <?=$this->content()->renderTranslated('panels/upload_tool'); ?>
        </div>
    </div>
</div>
