<h1>FID Community-Lizenz</h1>

<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#col1">
        <div class="tf-panel-collapse-heading">
            <span>FID Community-Lizenz</span>
        </div>
    </a>
    <div id="col1" class="collapse tf-panel-collapse-body">
        <p>„Zum <b>Nutzerkreis</b> für die FID-Lizenzen im FID Kriminologie gehören die Professor*innen und die wissenschaftlichen Mitarbeiter*innen an deutschen kriminologischen Lehrstühlen und Instituten. </p>
        <p>Sie benötigen ein KrimDok-Konto, in dem Sie bevorzugt eine institutionelle E-Mail-Adresse hinterlegen sowie das Land angeben. Nach Recherche des gewünschten, lizenzierten Titels in KrimDok gelangen Sie über den Link "FID-Lizenz: Zugriff mit KrimDok-Konto" auf den Volltext. </p>
        <p>Beispiel: <a target="_blank" href="https://krimdok.uni-tuebingen.de/Record/67280669X?sid=13914307">Strafrecht und Kriminologie: Untersuchungen und Forschungsberichte aus dem Max-Planck-Institut für Ausländisches und Internationales Strafrecht, Freiburg im Breisgau</a></p>
        <p>Aktuell sind bis zu 500 Nutzer*innen im FID-Nutzerkreis vorgesehen (Stand: November 2024).</p>
    </div>
</div>

<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#col2">
        <div class="tf-panel-collapse-heading">
            <span>Nationallizenzen</span>
        </div>
    </a>
    <div id="col2" class="collapse tf-panel-collapse-body">
        <p>Nationallizenzen bieten einen deutschlandweiten Zugriff auf die jeweilige lizenzierte Ressource zu den angegebenen Bedingungen (z. B. zeitliche Beschränkung). Ermöglicht werden die hier aufgeführten Nationallizenzen durch die Förderung der Deutschen Forschungsgemeinschaft (DFG) und die Universitätsbibliothek Tübingen, ggf. auch weitere FID-Bibliotheken.</p>
        <p>Sie können auf Nationallizenzen normalerweise über die <b>IP-Range ihrer Institution</b> zugreifen: Die meisten nationalen Hochschulen und Forschungseinrichtungen sind bereits dafür registriert. <b>Einzelpersonen</b> mit ständigem Wohnsitz in der Bundesrepublik Deutschland können sich persönlich für einen kostenlosen Zugriff <a target="_blank" href="http://www.nationallizenzen.de/einzelnutzer-anmeldung">registrieren</a> lassen, falls ihnen der Zugang über ein Hochschulnetz, bzw. über ihre wissenschaftliche Bibliothek, nicht zur Verfügung steht. </p>
        <p><a target="_blank" href="https://nl.zugang.nationallizenzen.de/han/7722c170-dbf5-4c54-acb0-feaa843ba996">Login für registrierte Einzelnutzer</a></p>
        <p><a target="_blank" href="https://krimdok.uni-tuebingen.de/krimdok_docs/Journals_Nationallizenz.pdf">Liste kriminologisch relevanter Zeitschriften mit Nationallizenz</a> </p>
    </div>
</div>