<h1>FID Community-Lizenz</h1>

<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#col1">
        <div class="tf-panel-collapse-heading">
            <span>FID Community-Lizenz</span>
        </div>
    </a>
    <div id="col1" class="collapse tf-panel-collapse-body">
        <p>„Zum <b>Nutzerkreis</b> für die FID-Lizenzen im FID Kriminologie gehören die Professor*innen und die wissenschaftlichen Mitarbeiter*innen an deutschen kriminologischen Lehrstühlen und Instituten. </p>
        <p>Sie benötigen ein KrimDok-Konto, in dem Sie bevorzugt eine institutionelle E-Mail-Adresse hinterlegen sowie das Land angeben. Nach Recherche des gewünschten, lizenzierten Titels in KrimDok gelangen Sie über den Link "FID-Lizenz: Zugriff mit KrimDok-Konto" auf den Volltext. </p>
        <p>Beispiel: <a target="_blank" href="https://relbib.de/Record/1677766123">Handbuch der Religionen</a></p>
        <p>Aktuell sind bis zu 500 Nutzer*innen im FID-Nutzerkreis vorgesehen (Stand: November 2024).</p>
    </div>
</div>

<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#col2">
        <div class="tf-panel-collapse-heading">
            <span>Nationallizenzen</span>
        </div>
    </a>
    <div id="col2" class="collapse tf-panel-collapse-body">
        <p>Die Datenbank <a target="_blank" href="https://www.jewishlife.amdigital.co.uk">Jewish Life in America</a> (Adam Matthew digital) bietet Zugang zu einer Vielzahl von archivalischen Materialien, die Einblicke in die Geschichte der jüdischen Gemeinden in den USA von der Ankunft der ersten jüdischen Siedler*innen in New Amsterdam im 17. Jahrhundert bis zur Mitte des 20. Jahrhunderts geben. Es handelt sich u. a. um autobiografische Aufzeichnungen einzelner Familien, Sammlungen zu wichtigen historischen Persönlichkeiten des amerikanischen Judentums sowie Aktenbestände privater und staatlicher Organisationen. Diese reichhaltige Quellensammlung stammt aus den Archivbeständen der American Jewish Historical Society in New York City. </p>
        <p>Neben den digitalisierten Archivbeständen stellt die Datenbank auch Hilfsmittel für die Recherche zur Verfügung: u.a. eine Chronologie der wichtigsten Ereignisse, Aufsätze führender Wissenschaftler*innen, Anleitungen zu den vorgestellten Sammlungen, eine Auswahl von Artikeln aus dem American Jewish Year Book, eine Bildergalerie sowie Biografien prominenter Persönlichkeiten, die in der Datenbank enthalten sind.</p>
        <p>Die Datenbank wird dank einer Kooperation des FID <a target="_blank" href="https://www.jewishstudies.de/">Jüdische Studien</a> mit den FID für <a target="_blank" href="https://libaac.de/home/">Anglo-American Culture</a>, <a target="_blank" href="https://www.historicum.net/home">Geschichteswissenschaft</a>, <a target="_blank" href="https://www.osmikon.de/">Ost-, Ostmittel- und Südosteuropa</a> und <a target="_blank" href="https://relbib.de/">Religionswissenschaft</a> seit Januar 2023 als dauerhafte Nationallizenz bereitgestellt.</p>
        <p><a target="_blank" href="https://krimdok.uni-tuebingen.de/krimdok_docs/Journals_Nationallizenz.pdf">Liste kriminologisch relevanter Zeitschriften mit Nationallizenz</a> </p>
    </div>
</div>