<h1>FID-Licence</h1>

<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#col1">
        <div class="tf-panel-collapse-heading">
            <span>FID-Community-License</span>
        </div>
    </a>
    <div id="col1" class="collapse tf-panel-collapse-body">
        <p>FID community licences in the FID Criminology are aimed at professors and academic staff at criminological departments and institutes. They provide free access to selected electronic literature. Users need a KrimDok account in which they preferably provide an institutional email address and indicate the country in which the insitute is located. After searching for the desired licensed title in KrimDok, the link ‘FID-Lizenz: Zugriff mit KrimDok-Konto’ leads to the full text.</p>
        <p>The following licences are currently available:</p>
        <p style="padding-left: 20px;">1) Strafrecht und Kriminologie: Untersuchungen und Forschungsberichte aus dem Max-Planck-Institut für Ausländisches und Internationales Strafrecht, Freiburg im Breisgau.</p>
        <p style="padding-left: 20px;">All 20 volumes of this series are freely accessible and can also be searched using the command *kfl:duncker.</p>
        <p style="padding-left: 20px;">2) Nomos package “Kriminologie” </p>
        <p style="padding-left: 20px;">The FID, together with Nomos Publishing, has put together an e-book package containing a total of 94 criminologically relevant titles. These can also be accessed using the search command *kfl:nomos. Currently, up to 500 users per licence are provided (as of December 2025).</p>
    </div>
</div>

<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#col2">
        <div class="tf-panel-collapse-heading">
            <span>National licences</span>
        </div>
    </a>
    <div id="col2" class="collapse tf-panel-collapse-body">
        <p>National licences offer Germany-wide access to the respective licensed resource under specified conditions (e.g. time limits). The national licences listed here are made possible by funding from the German Research Foundation (DFG), the University of Tübingen Library, and in some cases, other FID libraries.</p>
        <p>You can usually access national licences via the IP range of your institution: Most national universities and research institutions are already registered for this. Individuals with permanent residence in the Federal Republic of Germany can be <a target="_blank" href="http://www.nationallizenzen.de/einzelnutzer-anmeldung">registered</a> individually for free access if access via a university network or their academic library is not available.</p>
        <p><a target="_blank" href="https://nl.zugang.nationallizenzen.de/han/7722c170-dbf5-4c54-acb0-feaa843ba996">Login as registered individual users</a></p>
        <p><a target="_blank" href="https://krimdok.uni-tuebingen.de/krimdok_docs/Journals_Nationallizenz.pdf">List of Criminology-relevant journals with national licences</a></p>
    </div>
</div>