<h1>Lizenzen</h1>

<div class="tf-panel-collapse">
    <a data-bs-toggle="collapse" href="#col1">
        <div class="tf-panel-collapse-heading">
            <span>FID-Community-Lizenzen</span>
        </div>
    </a>
    <div id="col1" class="collapse tf-panel-collapse-body">
        <p>Die FID-Community-Lizenzen richten sich an Forschende und ermöglichen einen kostenfreien Zugang zu ausgewählten elektronischen Fachressourcen.</p>
        <p>Für die Nutzung wird ein KrimDok-Konto benötigt. Bitte hinterlegen Sie dort möglichst Ihre institutionelle E-Mail-Adresse und geben Sie Ihr Land an. Nach der Recherche eines lizenzierten Titels in KrimDok gelangen Sie über den Link „FID-Lizenz: Zugriff mit KrimDok-Konto“ direkt zum Volltext.</p>
        <p>Zurzeit stehen Ihnen folgende Lizenzen zur Verfügung: </p>
        <div style="padding-left: 50px;">
            <p><span style="position: absolute; margin-left: -25px;">1)</span> <a target="_blank" href="https://krimdok.uni-tuebingen.de/Record/67280669X?sid=13914307">Strafrecht und Kriminologie: Untersuchungen und Forschungsberichte aus dem Max-Planck-Institut für Ausländisches und Internationales Strafrecht, Freiburg im Breisgau</a></p>
            <p>Alle 20 Bände dieser Reihe sind frei zugänglich und können auch über den Suchbefehl kfl:*duncker recherchiert werden.</p>
            <p><span style="position: absolute; margin-left: -25px;">2)</span> <a target="_blank" href="https://krimdok.uni-tuebingen.de/Search/Results?lookfor=kfl%3A*nomos&type=AllFields&limit=20&sort=year+desc%2C+volume_sort+desc%2C+issue_sort+desc%2C+start_page+asc&botprotect=">Nomos-Paket „Kriminologie“</a></p>
            <p>Der FID hat zusammen mit dem Nomos Verlag ein eBook-Paket mit insgesamt 94 kriminologisch relevanten Titeln geschnürt. Auf diese kann auch mit dem Suchbefehl kfl:*nomos zugegriffen werden.</p>
            <p><span style="position: absolute; margin-left: -25px;">3)</span> <a target="_blank" href="https://krimdok.uni-tuebingen.de/Record/271175559?sid=95461286">British Journal of Criminology</a></p>
            <p>Die Jahrgänge 2018 - 2026 des British Journals of Criminology wurden vollständig lizenziert und können nach Veröffentlichung auch mit dem Suchbefehl kfl:*bjc recherchiert werden. Im Übrigen existiert eine Nationallizenz für alle Jahrgänge bis einschließlich 2017. Nähere Informationen zu Nationallizenzen sind in dem untenstehenden Reiter zu finden.</p>
        </div>
        <p>Aktuell sind bis zu 500 Nutzende pro Lizenz vorgesehen (Stand: Mai 2026). Melden Sie sich gerne an. Der FID wünscht viel Spaß beim Recherchieren!</p>
    </div>
</div>

<div class="tf-panel-collapse">
    <a data-bs-toggle="collapse" href="#col2">
        <div class="tf-panel-collapse-heading">
            <span>Nationallizenzen</span>
        </div>
    </a>
    <div id="col2" class="collapse tf-panel-collapse-body">
        <p>Nationallizenzen bieten einen deutschlandweiten Zugriff auf die jeweilige lizenzierte Ressource zu den angegebenen Bedingungen (z. B. zeitliche Beschränkung). Ermöglicht werden die hier aufgeführten Nationallizenzen durch die Förderung der Deutschen Forschungsgemeinschaft (DFG) und die Universitätsbibliothek Tübingen, ggf. auch weitere FID-Bibliotheken.</p>
        <p>Sie können auf Nationallizenzen normalerweise über die <b>IP-Range ihrer Institution</b> zugreifen: Die meisten nationalen Hochschulen und Forschungseinrichtungen sind bereits dafür registriert. <b>Einzelpersonen</b> mit ständigem Wohnsitz in der Bundesrepublik Deutschland können sich persönlich für einen kostenlosen Zugriff <a target="_blank" href="http://www.nationallizenzen.de/einzelnutzer-anmeldung">registrieren</a> lassen, falls ihnen der Zugang über ein Hochschulnetz, bzw. über ihre wissenschaftliche Bibliothek, nicht zur Verfügung steht. </p>
        <p><a target="_blank" href="https://nl.zugang.nationallizenzen.de/han/7722c170-dbf5-4c54-acb0-feaa843ba996">Login für registrierte Einzelnutzer</a></p>
        <p><a target="_blank" href="https://krimdok.uni-tuebingen.de/krimdok_docs/Journals_Nationallizenz.pdf">Liste kriminologisch relevanter Zeitschriften mit Nationallizenz</a> </p>
    </div>
</div>
