<h1>Licenses</h1>

<div class="tf-panel-collapse">
    <a data-bs-toggle="collapse" href="#col1">
        <div class="tf-panel-collapse-heading">
            <span>FID-Community-Licenses</span>
        </div>
    </a>
    <div id="col1" class="collapse tf-panel-collapse-body">
        <p>The FID Community Licenses are designed for researchers and provide free access to selected electronic academic resources.</p>
        <p>A KrimDok account is required to use this service. Please provide your institutional email address – if possible – and select your country. After searching for a licensed title in KrimDok, you can access the full text directly via the link “FID-Lizenz: Zugriff mit KrimDok-Konto”.</p>
        <p>The following licenses are currently available:</p>
        <div style="padding-left: 50px;">
            <p><span style="position: absolute; margin-left: -25px;">1)</span> <a target="_blank" href="https://krimdok.uni-tuebingen.de/Record/67280669X?sid=13914307">Strafrecht und Kriminologie: Untersuchungen und Forschungsberichte aus dem Max-Planck-Institut für Ausländisches und Internationales Strafrecht, Freiburg im Breisgau</a></p>
            <p>All 20 volumes of this series are freely accessible and can also be searched using the command kfl:*duncker.</p>
            <p><span style="position: absolute; margin-left: -25px;">2)</span> <a target="_blank" href="https://krimdok.uni-tuebingen.de/Search/Results?lookfor=kfl%3A*nomos&type=AllFields&limit=20&sort=year+desc%2C+volume_sort+desc%2C+issue_sort+desc%2C+start_page+asc&botprotect=">Nomos package “Kriminologie”</a></p>
            <p>The FID, together with Nomos Publishing, has put together an e-book package containing a total of 94 criminologically relevant titles. These can also be accessed using the search command kfl:*nomos.</p>
            <p><span style="position: absolute; margin-left: -25px;">3)</span> <a target="_blank" href="https://krimdok.uni-tuebingen.de/Record/271175559?sid=95461286">British Journal of Criminology</a></p>
            <p>The British Journal of Criminology is fully licensed for the years 2018 - 2026 and can also be found, after their publication, via kfl:*bjc. Apart from that, all issues until 2017 are available under a national license. More information on national licenses can be found in the tab below.</p>
        </div>
        <p>Currently, all licensed products allow access for up to 500 users (as of May 2026). Please feel free to sign up!</p>
    </div>
</div>

<div class="tf-panel-collapse">
    <a data-bs-toggle="collapse" href="#col2">
        <div class="tf-panel-collapse-heading">
            <span>National licences</span>
        </div>
    </a>
    <div id="col2" class="collapse tf-panel-collapse-body">
        <p>National licences offer Germany-wide access to the respective licensed resource under specified conditions (e.g. time limits). The national licences listed here are made possible by funding from the German Research Foundation (DFG), the University of Tübingen Library, and in some cases, other FID libraries.</p>
        <p>You can usually access national licences via the IP range of your institution: Most national universities and research institutions are already registered for this. Individuals with permanent residence in the Federal Republic of Germany can be <a target="_blank" href="http://www.nationallizenzen.de/einzelnutzer-anmeldung">registered</a> individually for free access if access via a university network or their academic library is not available.</p>
        <p><a target="_blank" href="https://nl.zugang.nationallizenzen.de/han/7722c170-dbf5-4c54-acb0-feaa843ba996">Login as registered individual users</a></p>
        <p><a target="_blank" href="https://krimdok.uni-tuebingen.de/krimdok_docs/Journals_Nationallizenz.pdf">List of Criminology-relevant journals with national licences</a></p>
    </div>
</div>
