<h1>FID-Lizenz</h1>

<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#col1">
        <div class="tf-panel-collapse-heading">
            <span>FID-Community-Lizenz</span>
        </div>
    </a>
    <div id="col1" class="collapse tf-panel-collapse-body">
        <p>FID-Community-Lizenzen im FID Kriminologie richten sich an <b>kriminologisch Forschende in Deutschland</b>. Sie ermöglichen den <b>kostenfreien Zugriff</b> auf ausgewählte elektronische Literatur.</p>
        <p>Nutzende benötigen ein <b>KrimDok-Konto</b>, in dem Sie bevorzugt eine institutionelle E-Mail-Adresse hinterlegen sowie das Land angeben. Nach Recherche des gewünschten, lizenzierten Titels in KrimDok führt der Link "FID-Lizenz: Zugriff mit KrimDok-Konto" auf den Volltext.</p>
        <p>Zurzeit stehen folgende Lizenzen zur Verfügung: </p>
            <div style="padding-left: 50px;">
                <p><span style="position: absolute; margin-left: -25px;">1)</span> <a target="_blank" href="https://krimdok.uni-tuebingen.de/Record/67280669X">Strafrecht und Kriminologie: Untersuchungen und Forschungsberichte aus dem Max-Planck-Institut für Ausländisches und Internationales Strafrecht, Freiburg im Breisgau</a></p>
                <p>Alle 20 Bände dieser Reihe sind frei zugänglich und können auch über den Suchbefehl <i>kfl:*duncker</i> recherchiert werden.</p>
                <p><span style="position: absolute; margin-left: -25px;">2)</span> <a target="_blank" href="https://krimdok.uni-tuebingen.de/Search/Results?lookfor=kfl%3A*nomos&type=AllFields&limit=20&sort=year+desc%2C+volume_sort+desc%2C+issue_sort+desc%2C+start_page+asc&botprotect=">Nomos-Paket „Kriminologie“</a></p>
                <p>Der FID hat zusammen mit dem Nomos Verlag ein eBook-Paket mit insgesamt 94 kriminologisch relevanten Titeln geschnürt. Auf diese kann auch mit dem Suchbefehl <i>kfl:*nomos</i> zugegriffen werden.</p>
            </div>
        <p>Aktuell sind bis zu 500 Nutzer:innen pro Lizenz vorgesehen (Stand: Dezember 2025).</p>
    </div>
</div>

<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#col2">
        <div class="tf-panel-collapse-heading">
            <span>Nationallizenzen</span>
        </div>
    </a>
    <div id="col2" class="collapse tf-panel-collapse-body">
        <p>Nationallizenzen bieten einen deutschlandweiten Zugriff auf die jeweilige lizenzierte Ressource zu den angegebenen Bedingungen (z. B. zeitliche Beschränkung). Ermöglicht werden die hier aufgeführten Nationallizenzen durch die Förderung der Deutschen Forschungsgemeinschaft (DFG) und die Universitätsbibliothek Tübingen, ggf. auch weitere FID-Bibliotheken.</p>
        <p>Sie können auf Nationallizenzen normalerweise über die <b>IP-Range ihrer Institution</b> zugreifen: Die meisten nationalen Hochschulen und Forschungseinrichtungen sind bereits dafür registriert. <b>Einzelpersonen</b> mit ständigem Wohnsitz in der Bundesrepublik Deutschland können sich persönlich für einen kostenlosen Zugriff <a target="_blank" href="http://www.nationallizenzen.de/einzelnutzer-anmeldung">registrieren</a> lassen, falls ihnen der Zugang über ein Hochschulnetz, bzw. über ihre wissenschaftliche Bibliothek, nicht zur Verfügung steht. </p>
        <p><a target="_blank" href="https://nl.zugang.nationallizenzen.de/han/7722c170-dbf5-4c54-acb0-feaa843ba996">Login für registrierte Einzelnutzer</a></p>
        <p><a target="_blank" href="https://krimdok.uni-tuebingen.de/krimdok_docs/Journals_Nationallizenz.pdf">Liste kriminologisch relevanter Zeitschriften mit Nationallizenz</a> </p>
    </div>
</div>