<div class="table_content">
    <div class="table_content_header">
        <h1>Kriminologie</h1>
        <h3>Master of Arts (M.A.)</h3>
        <h2>Johannes Gutenberg Universität Mainz</h2>
    </div>
    <table>
        <tr>
            <td>Studienform</td>
            <td>Vollzeit, Präsenz, nicht berufsbegleitend möglich Interdisziplinär, forensisch, praxisnah</td>
        </tr>
        <tr>
            <td>Inhalte</td>
            <td>interdisziplinäre Verbindung zwischen Kriminologie, Rechtswissenschaft, Psychologie, Medizin und Soziologie <br />
                Vermittlung eines interdisziplinären Verständnisses für Kriminalität, ihrer Ursachen und Folgen sowie Möglichkeiten der Strafverfolgung und Prävention <br /> 
                zentraler Bestandteil: Forensische Kriminologie und damit die einzelfallbezogene Anwendung von kriminologischem Wissen innerhalb der justiziellen und behördlichen Praxis <br />
                Teilnahme an wissenschaftlichen Diskussionen, Exkursionen, Vorträgen von Expert*innen aus Justiz-vollzugsanstalten, der Jugendhilfe, der Drogenberatung und forensischen Einrichtungen <br />
                zwei Praxisprojekte während der Studienzeit
            </td>
        </tr>
        <tr>
            <td>Semesteranzahl</td>
            <td>4 Semester</td>
        </tr>
        <tr>
            <td>Beginn</td>
            <td>Wintersemester</td>
        </tr>
        <tr>
            <td>ECTS</td>
            <td>120 ECTS</td>
        </tr>
        <tr>
            <td>Voraussetzungen</td>
            <td>
                Zulassungsbeschränkt: <br />
                Verfahrensnote: 1,4 (WiSe 2026/2027) <br />
                Wartezeit: 3 Semester (WiSe 2026/2027) <br />
                Nachweis eines Bachelorabschlusses im Fach Rechtswissenschaft (mit Schwerpunkt Strafrecht, Strafrechtspflege oder Kriminologie) oder einer bestandenen ersten juristischen Prüfung (mit Schwerpunkt Strafrecht, Strafrechtspflege oder Kriminologie) <br />
                ODER <br />
                Nachweis der abgeschlossenen ärztlichen Prüfung (Staatsexamen) in Humanmedizin  <br />
                ODER <br />
                Nachweis eines Bachelorabschlusses im Fach Psychologie; hierbei müssen mindestens 100 Leistungspunkte auf Module in Psychologie entfallen, von denen mindestens 30 Leistungspunkte in klinischer Psychologie, Psychotherapie oder Sozialpsychologie erworben worden sind <br />
                ODER <br />
                Nachweis eines Bachelorabschlusses im Fach Soziologie; hierbei müssen mindestens 100 Leistungspunkte auf Module in Soziologie entfallen <br />
                ODER <br />
                Nachweis eines Bachelorabschlusses in einem anderen geistes-, kultur- oder sozialwissenschaftlichen Studiengang, soweit mindestens 60 Leistungspunkte in Modulen aus dem Bereich Strafrecht, Strafrechtspflege oder Kriminologie erworben worden sind
            </td>
        </tr>
        <tr>
            <td>Studiengebühren</td>
            <td>reguläre Semesterbeiträge</td>
        </tr>
        <tr>
            <td>Bewerbungszeitraum</td>
            <td>Anfang April – 15.05.</td>
        </tr>
        <tr>
            <td>Bewerbungsprozess</td>
            <td>Online-Bewerbung</td>
        </tr>
        <tr>
            <td>Sonstiges</td>
            <td>Keine Angaben</td>
        </tr>
        <tr>
            <td>Link zur Homepage</td>
            <td><a target="_blank" href="https://www.studium.uni-mainz.de/studienwahl/studienangebot/kriminologie-ma/">https://www.studium.uni-mainz.de/studienwahl/studienangebot/kriminologie-ma/</a></td>
        </tr>
    </table>

    <p class="table_content_footer kursiv">Stand: 10.7.2026</p>

</div>
