<div class="tf-background-body">
    <div id="content" class="container">
        <div class="row">
            <?=$this->content()->renderTranslated('panels/berlin'); ?>
            <?=$this->content()->renderTranslated('panels/bochum'); ?>
            <?=$this->content()->renderTranslated('panels/hamburg'); ?>
            <?=$this->content()->renderTranslated('panels/mainz'); ?>
            <?=$this->content()->renderTranslated('panels/regensburg'); ?>
            <?=$this->content()->renderTranslated('panels/wolfenbuttel'); ?>
        </div>
    </div>
</div>
