<h1>&nbsp;</h1>
<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#collapse1">
        <div class="tf-panel-collapse-heading">
        Physical Inventory
        </div>
    </a>
    <div id="collapse1" class="collapse tf-panel-collapse-body">
        <p>The FID offers various access options to full texts, which we aim to continuously improve and expand in the future. In KrimDok, there is already the possibility to directly access a researched electronic journal article through a link. In the future, the database will also include references to criminologically relevant e-books. In cases where the works are not available under open access conditions, they can be accessed through your library's subscription or licensing. Additionally, a selection of currently available open access journals has been compiled, which includes relevant journals in the field as well as those related to criminology. The articles in these journals can be accessed from any location due to their unrestricted access. In the project components "DigiKrimDok" and "Criminological Repository," further relevant full texts are being collected through various strategies. You can conveniently search for and access all documents through the KrimDok database.</p>
    </div>
</div>
<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#collapse2">
        <div class="tf-panel-collapse-heading">
        DigiKrimDok
        </div>
    </a>
    <div id="collapse2" class="collapse tf-panel-collapse-body">
        <p>On the DigiKrimDok portal, the FID Criminology provides retrospectively digitized, older, and mostly out-of-print individual works, series, and journals of high scientific or scientific-historical relevance for free use. Currently, we are digitizing specific suitable works upon request.</p>
    </div>
</div>
<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#collapse3">
        <div class="tf-panel-collapse-heading">
            E-Books
        </div>
    </a>
    <div id="collapse3" class="collapse tf-panel-collapse-body">
      <p>The <a href="https://publikationen.uni-tuebingen.de/xmlui/handle/10900/56358">criminological repository</a> contains a collection of online publications that are of great importance to criminological research. Unfortunately, these publications are often scattered across the internet and are only accessible with difficulty. They belong to the realm of "grey literature" and include reports from various ministries, research institutions, and other organizations, as well as crime statistics from different regions, evaluations from the practical and policy sectors, and similar materials. If you or your institution possess such documents that have not yet been included in our repository, we welcome any information or suggestions at <a href="mailto:fidkrim@ifk.uni-tuebingen.de">fidkrim@ifk.uni-tuebingen.de</a>.</p>
    </div>
</div>
