<h1>&nbsp;</h1>
<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#collapse1">
        <div class="tf-panel-collapse-heading">
            Textos Completos
        </div>
    </a>
    <div id="collapse1" class="collapse tf-panel-collapse-body">
        <p>El FID de Criminología ofrece varias opciones de acceso a textos completos, que buscamos mejorar y ampliar continuamente en el futuro.</p>
        <p>En KrimDok ya es posible acceder directamente a artículos de revistas electrónicas a través de un enlace. En el futuro, la base de datos contendrá también referencias a libros electrónicos relacionados con la criminología. En caso de que las obras no estén disponibles en condiciones de acceso abierto, podrá acceder a ellas a través del acceso de su biblioteca si esta cuenta con la licencia adecuada.</p>
        <p>Además, se recopiló una selección de <a href="<?=$this->url('content-page', ['page' => 'journals'])?>">revistas de acceso abierto</a> publicadas actualmente que contiene títulos de revistas especializadas y de referencia. Se puede acceder a estos artículos desde cualquier lugar gracias a su acceso abierto.</p>
        <p>En los módulos del proyecto "DigiKrimDok" y "Repositorio criminológico" se recopilan otros textos completos relevantes mediante diversas estrategias. Todos los documentos pueden buscarse y consultarse cómodamente a través de la base de datos KrimDok.</p>
</div>
<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#collapse2">
        <div class="tf-panel-collapse-heading">
            DigiKrimDok
        </div>
    </a>
    <div id="collapse2" class="collapse tf-panel-collapse-body">
        <p>En el portal <a target="_blank" href="http://idb.ub.uni-tuebingen.de/digitue/krimdok/">DigiKrimDok</a>, el FID de Criminología pone a disposición del público obras individuales, series de publicaciones y revistas de gran relevancia académica o histórica, digitalizadas posteriormente, antiguas y en su mayoría agotadas. Actualmente digitalizamos obras individuales adecuadas previa solicitud.</p>
    </div>
</div>
<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#collapse3">
        <div class="tf-panel-collapse-heading">
            Libros electrónicos
        </div>
    </a>
    <div id="collapse3" class="collapse tf-panel-collapse-body">

    </div>
</div>
