<h1>&nbsp;</h1>
<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#collapse1">
        <div class="tf-panel-collapse-heading">
            Existencias físicas en Tubinga
        </div>
    </a>
    <div id="collapse1" class="collapse tf-panel-collapse-body">
        <p>El FID de Criminología ofrece varias opciones de acceso a textos completos, que buscamos mejorar y ampliar continuamente en el futuro.</p>
        <p>En KrimDok ya es posible acceder directamente a artículos de revistas electrónicas a través de un enlace. En el futuro, la base de datos contendrá también referencias a libros electrónicos relacionados con la criminología. En caso de que las obras no estén disponibles en condiciones de acceso abierto, podrá acceder a ellas a través del acceso de su biblioteca si esta cuenta con la licencia adecuada.</p>
        <p>Además, se recopiló una selección de <a href="/Content/journals#content">revistas de acceso abierto</a> publicadas actualmente que contiene títulos de revistas especializadas y de referencia. Se puede acceder a estos artículos desde cualquier lugar gracias a su acceso abierto.</p>
        <p>En los módulos del proyecto "DigiKrimDok" y "Repositorio criminológico" se recopilan otros textos completos relevantes mediante diversas estrategias. Todos los documentos pueden buscarse y consultarse cómodamente a través de la base de datos KrimDok.</p>
</div>
<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#collapse2">
        <div class="tf-panel-collapse-heading">
            DigiKrimDok
        </div>
    </a>
    <div id="collapse2" class="collapse tf-panel-collapse-body">
        <p>En el portal <a href="http://idb.ub.uni-tuebingen.de/digitue/krimdok/">DigiKrimDok</a>, el FID de Criminología pone a disposición del público obras individuales, series de publicaciones y revistas de gran relevancia académica o histórica, digitalizadas posteriormente, antiguas y en su mayoría agotadas. Actualmente digitalizamos obras individuales adecuadas previa solicitud.</p>
    </div>
</div>
<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#collapse3">
        <div class="tf-panel-collapse-heading">
            Libros electrónicos
        </div>
    </a>
    <div id="collapse3" class="collapse tf-panel-collapse-body">
      <p>El <a href="https://publikationen.uni-tuebingen.de/xmlui/handle/10900/56358">repositorio criminológico </a> contiene una colección de publicaciones en línea del ámbito de la llamada "literatura gris" que son muy importantes para la investigación criminológica, pero que lamentablemente se encuentran dispersas por Internet y a menudo son de difícil acceso. Se trata de informes de diversos ministerios, institutos de investigación y otras instituciones, así como estadísticas sobre delincuencia de diversas regiones, evaluaciones del ámbito de la práctica y la política, y similares. Si usted o su institución disponen de este tipo de documentos y aún no se han incluido en nuestro repositorio, no dude en contactarnos en <a href="mailto:fidkrim@ifk.uni-tuebingen.de">fidkrim@ifk.uni-tuebingen.de</a>.</p>
    </div>
</div>
