<h1>&nbsp;</h1>
<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#collapse1">
        <div class="tf-panel-collapse-heading">
            Volltexte
        </div>
    </a>
    <div id="collapse1" class="collapse tf-panel-collapse-body">
        <p>Der FID Kriminologie bietet verschiedene Zugangsmöglichkeiten zu Volltexten an, die wir zukünftig kontinuierlich verbessern und erweitern wollen.</p>
        <p>In KrimDok besteht bereits die Möglichkeit, einen recherchierten elektronischen Zeitschriftenbeitrag direkt über einen Link aufzurufen. Zukünftig wird die Datenbank auch Nachweise für kriminologisch relevante E-Books enthalten. Für den Fall, dass die Werke nicht unter Open-Access-Bedingungen zur Verfügung stehen, können sie bei entsprechender Lizenzierung über den Zugang Ihrer Bibliothek aufgerufen werden.</p>
        <p>Darüber hinaus wurde eine Auswahl an aktuell erscheinenden <a href="/Content/journals#content">Open-Access-Zeitschriften</a> erstellt, die sowohl einschlägige als auch bezugswissenschaftliche Zeitschriftentitel enthält. Deren Zeitschriftenartikel sind aufgrund ihres lizenzfreien Zugangs von jedem Standort aus abrufbar.</p>
        <p>In den Projektbausteinen „DigiKrimDok“ und „Kriminologisches Repository“ werden über verschiedene Strategien weitere relevante Volltexte zusammengetragen. Alle Dokumente können Sie bequem über die Datenbank KrimDok recherchieren und aufrufen.</p>
    </div>
</div>
<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#collapse2">
        <div class="tf-panel-collapse-heading">
            DigiKrimDok
        </div>
    </a>
    <div id="collapse2" class="collapse tf-panel-collapse-body">
        <p>Auf dem Portal <a target="_blank" href="http://idb.ub.uni-tuebingen.de/digitue/krimdok/">DigiKrimDok</a> stellt der FID Kriminologie nachträglich digitalisierte, ältere und zumeist vergriffene Einzelwerke, Schriftenreihen und Zeitschriften von hoher wissenschaftlicher oder wissenschaftshistorischer Relevanz zur kostenlosen Nutzung zur Verfügung. Derzeit digitalisieren wir einzelne geeignete Werke auf Wunsch.</p>
    </div>
</div>
<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#collapse3">
        <div class="tf-panel-collapse-heading">
            E-Books
        </div>
    </a>
    <div id="collapse3" class="collapse tf-panel-collapse-body">

    </div>
</div>
