<div class="krimblog_block">
    <p>From December 2025, you can find all the information about new developments relating to KrimDok on our newly created “KrimBlog.”
    <p>We look forward to seeing you there!<p> <a target="_blank" href="https://krimdok.jimdofree.com/">Click here to go directly to KrimBlog</a>.</p>
</div>
<style>
.krimblog_block {
    padding: 20px;
    border: 2px solid black;
    width: 600px;
    background-color: #f5f5f5;
    margin: 80px auto;
    text-align: center;
}
.krimblog_block a {
    color: red;
    text-decoration: underline;
    font-weight: bold;
    font-size: 25px;
}
</style>