<div class="krimblog_block">
    <p>A partir de diciembre de 2025, encontrará toda la información sobre las novedades relacionadas con KrimDok en nuestro «KrimBlog». ¡Le esperamos! <br /> <a target="_blank" href="https://krimdok.jimdofree.com/">Aquí puede acceder directamente al KrimBlog.</a></p>
</div>
<style>
.krimblog_block {
    padding: 20px;
    border: 2px solid black;
    width: 600px;
    background-color: #f5f5f5;
    margin: 80px auto;
    text-align: center;
}
.krimblog_block a {
    color: red;
    text-decoration: underline;
    font-weight: bold;
    font-size: 25px;
}
</style>