<div class="krimblog_block">
    <p>Ab Dezember 2025 finden Sie alle Informationen über neue Entwicklungen rund um KrimDok in unserem „KrimBlog“. <br > <a target="_blank" href="https://krimdok.jimdofree.com/">Hier geht’s zum KrimBlog</a>.</p>
</div>
<style>
.krimblog_block {
    padding: 20px;
    border: 2px solid black;
    width: 600px;
    background-color: #f5f5f5;
    margin: 80px auto;
    text-align: center;
}
.krimblog_block a {
    color: red;
    text-decoration: underline;
    font-weight: bold;
    font-size: 25px;
}
</style>