<div class="tf-background-body">
    <div id="content" class="container">
        <div class="row">
            <?=$this->content()->renderTranslated('panels/monografien'); ?>
            <?=$this->content()->renderTranslated('panels/journals'); ?>
            <?=$this->content()->renderTranslated('panels/licenses'); ?>
            <?=$this->content()->renderTranslated('panels/research_data_management'); ?>
            <?=$this->content()->renderTranslated('panels/repository'); ?>
            <?=$this->content()->renderTranslated('panels/acquisition'); ?>
        </div>
    </div>
</div>
