<div class="tf-background-body">
    <div id="content" class="container">
        <?=$this->content()->renderTranslated('panels/monografien'); ?>
        <?=$this->content()->renderTranslated('panels/research_data_management'); ?>
        <?=$this->content()->renderTranslated('panels/repository'); ?>
        <?=$this->content()->renderTranslated('panels/acquisition'); ?>
        <?=$this->content()->renderTranslated('panels/journals'); ?>
    </div>
</div>
