<div class="table_content">
    <div class="table_content_header">
        <h1>Kriminologie und Gewaltforschung</h1>
        <h3>Master of Arts (M.A.)</h3>
        <h2>Universität Regensburg</h2>
    </div>
    <table>
        <tr>
            <td>Studienform</td>
            <td>Vollzeit, Präsenzstudium, nicht berufsbegleitend, interdisziplinär</td>
        </tr>
        <tr>
            <td>Inhalte</td>
            <td>Rechtswissenschaft, Kriminologie, (Neuro-)Biologie, Medizin, (Forensische) Psychiatrie, Psychologie, Politologie, Soziologie, Theologie, Sprach- und Kulturwissenschaften<br />
                Ursachen, Erscheinungsformen und Folgen von Straftaten, Gewalt und Aggression; Kriminologische Theorie, multidisziplinäre Perspektiven und Erkenntnisse aus der aktuellen Gewalt- & Aggressionsforschung
            </td>
        </tr>
        <tr>
            <td>Semesteranzahl</td>
            <td>4 Semester</td>
        </tr>
        <tr>
            <td>Beginn</td>
            <td>Wintersemester</td>
        </tr>
        <tr>
            <td>ECTS</td>
            <td>120 ECTS</td>
        </tr>
        <tr>
            <td>Voraussetzungen</td>
            <td>
                absolvierter Hochschulabschluss (oder gleichwertiger Abschluss) eines geistes-, sozial- oder naturwissenschaftlichen Fachs, sowie aus der Rechtswissenschaft. Vorzugsweise von Studiengängen aus den genannten Fächern der beteiligten Disziplinen<br />
                Abschlussnote: mind. 2,5 oder 5,5 Punkte für Jura<br />
                Absolvierung von mind. 3 ECTS in einer am Programm beteiligten Fächergruppe im Grundstudium
            </td>
        </tr>
        <tr>
            <td>Studiengebühren</td>
            <td>reguläre Semesterbeiträge</td>
        </tr>
        <tr>
            <td>Bewerbungszeitraum</td>
            <td>bis 22.06., 23:59 Uhr</td>
        </tr>
        <tr>
            <td>Bewerbungsprozess</td>
            <td>1. Bewerbung mit Unterlagen<br />
                2. ggf. Auswahlgespräch (findet voraussichtlich in der zweiten Hälfte des Jahres statt)
            </td>
        </tr>
        <tr>
            <td>Sonstiges</td>
            <td>Keine Angaben</td>
        </tr>
        <tr>
            <td>Link zur Homepage</td>
            <td><a target="_blank" href="https://www.uni-regensburg.de/rechtswissenschaft/strafrecht/mueller/kriminologie-gewaltforschung/">https://www.uni-regensburg.de/rechtswissenschaft/strafrecht/mueller/kriminologie-gewaltforschung/</a></td>
        </tr>
    </table>

    <p class="table_content_footer kursiv">Stand: 15.7.2026</p>

</div>
