<h2>Einführungen in KrimDok</h2>
<p>In regelmäßigen Abständen bietet der FID Kriminologie kurze, virtuelle Einführungen zu KrimDok an.</p>
<p>Neben Tipps zur erfolgreichen Literatursuche in KrimDok (beispielsweise durch Filtereinstellungen) werden auch besondere Angebote in KrimDok (etwa die Sammlung zu Rechtsextremismus & Antisemitismus, Nachweise zu Forschungsdaten, oder die Rubrik „Klassiker der Kriminologie“) vorgestellt. Da sich KrimDok über die Literatursuche hinaus als Informationsportal für die Kriminologie versteht, werden weitere in KrimDok auffindbare fachspezifische Informationen, wie etwa die Zusammenstellung aktueller Stellenausschreibungen, der Tagungskalender und die Rubrik „Tools &amp; Medien“ als Ergänzung zu Studium und Lehre in der Kriminologie präsentiert.</p>

<h3>Nächste Termine:</h3>
<ul>
    <li>23.10.2026 14:00 – 14:30 Uhr (<a target="_blank" href="https://zoom.us/j/97897151772">https://zoom.us/j/97897151772</a>)</li>
    <li>04.11.2026 10:00 – 10:30 Uhr (<a target="_blank" href="https://zoom.us/j/97897151772">https://zoom.us/j/97897151772</a>)</li>
    <li>19.01.2027 13:00 – 13:30 Uhr (<a target="_blank" href="https://zoom.us/j/97897151772">https://zoom.us/j/97897151772</a>)</li>
</ul>
<p>Die Teilnahme an den Veranstaltungen steht allen Interessierten offen. Eine Anmeldung ist nicht erforderlich.</p>
