<div class="tf-background-body">
    <div id="content" class="container">
        <?=$this->content()->renderTranslated('panels/albert_krebs_bibliothek'); ?>
        <?=$this->content()->renderTranslated('panels/statistiksuche'); ?>
        <?=$this->content()->renderTranslated('panels/suche_nach_forschungsdaten'); ?>
        <?=$this->content()->renderTranslated('panels/antisemitismus'); ?>
    </div>
</div>
