<h2>Búsqueda de estadísticas</h2>
<br />
<p>La búsqueda de estadísticas complementa la búsqueda de documentos y publicaciones, permitiendo acceder rápida y fácilmente a un gran número de estadísticas relevantes desde el punto de vista criminológico. La búsqueda puede acotarse espacial, temporal y temáticamente.</p>
<p>Ejemplo de búsqueda: por ejemplo, introduzca «estadísticas policiales sobre delincuencia» en la línea de búsqueda y active la búsqueda. A continuación, puede acotar aún más los resultados con las facetas del margen derecho, por ejemplo por idioma, tema o región.</p>
<p>&nbsp;</p> 