<h2>Statistiksuche</h2>

<p>Die Statistiksuche ergänzt die Suche nach Dokumenten und Publikationen. Hier kann schnell und einfach auf eine Vielzahl von kriminologisch relevanten Statistiken zugegriffen werden. Dabei kann räumlich, zeitlich und thematisch eingegrenzt werden.</p>
<p>Beispiel für eine Recherche: Geben Sie beispielsweise in der Suchzeile “Polizeiliche Kriminalstatistik” ein und lösen Sie die Suche aus. Dann können Sie die Treffer mit den Facetten am rechten Rand weiter einschränken, etwa nach der Sprache, dem Thema oder der Region.</p>