<h2>Statistics Search</h2>
<br />
<p>The statistics search complements the search for documents and publications. Here, a large number of criminologically relevant statistics can be accessed quickly and easily. The search can be narrowed down spatially, temporally and thematically.</p>
<p>For example, enter “Polizeiliche Kriminalstatistik” in the search line and trigger the search. Then you can further narrow down the hits with the search facets in the right margin, for example by language, topic or region.</p>
<p>&nbsp;</p> 