<h2>Búsqueda de datos de investigación</h2>

<p>La búsqueda de datos de investigación ofrece la posibilidad de buscar específicamente datos relevantes desde el punto de vista criminológico y acceder a una gran variedad de datos de investigación de forma rápida y sencilla. La búsqueda puede acotarse espacial, temporal y temáticamente.</p>
<p>Ejemplo de búsqueda: por ejemplo, introduzca el término “reincidencia” en la línea de búsqueda y active la búsqueda. A continuación, puede acotar aún más los resultados con las facetas del margen derecho, por ejemplo por idioma, tema o región.</p>