<h2>Research Data Search</h2>
<br />
<p>The research data search offers the possibility to search specifically for criminologically relevant data and to access a variety of research data quickly and easily. The search can be narrowed down spatially, temporally and thematically.</p>
<p>For example, enter the term “recidivism” in the search line and trigger the search. Then you can further narrow down the hits with the search facets in the right margin, for example by language, topic or region.</p>
<p>&nbsp;</p>