<h2>Suche nach Forschungsdaten</h2>

<p>Die Forschungsdatensuche bietet die Möglichkeit, gezielt nach kriminologisch relevanten Daten zu suchen und schnell und einfach auf eine Vielzahl von Forschungsdaten zuzugreifen. Dabei kann räumlich, zeitlich und thematisch eingegrenzt werden.</p>
<p>Beispiel für eine Recherche: Geben Sie beispielsweise in der Suchzeile den Begriff “Recidivism” ein und lösen Sie die Suche aus. Dann können Sie die Treffer mit den Facetten am rechten Rand weiter einschränken, etwa nach der Sprache, dem Thema oder der Region.</p>