<h1>Tools & Medien</h1>

<h4>Hier finden Sie eine Sammlung von Tools und Medien, die für die kriminologische Forschung und Lehre von Interesse sind. Wenn Sie weitere relevante Quellen kennen, freuen wir uns über einen Hinweis an <a href="mailto:krimdok@ub.uni-tuebingen.de">krimdok@ub.uni-tuebingen.de</a>.</h4>


<h3>Allgemeines</h3>
<ul>
    <li><a target="_blank" href="https://criminologia.de/">Criminologia</a></li>
    <li><a target="_blank" href="http://www.krimlex.de/">KrimLex</a></li>
    <li><a target="_blank" href="https://strafvollzugsarchiv.de/">Strafvollzugsarchiv</a></li>
</ul>

<h3>Quizze & Lehrmaterialien</h3>
<ul>
    <li><a target="_blank" href="https://soztheo.de/kriminalitaetstheorien/">Kriminalitätstheorien</a></li>
    <li><a target="_blank" href="www.lto.de/quiz/lto-rechtsquiz/rechtsquiz-kriminologie-und-strafvollzugsrecht/">LTO-Quiz</a></li>
    <li><a target="_blank" href="https://soztheo.de/quiz/">Quiz</a></li>
    <li><a target="_blank" href="http://quizlet.com/search?query=Kriminologie&type=all">Quizlet-Lernmaterialien</a></li>
</ul>

<h3>Podcasts</h3>
<ul>
    <li><a target="_blank" href="https://www.hspv.nrw.de/forschung/publicationen/publikation/5-minuten-kriminologie">5 Minuten Kriminologie</a></li>
    <li><a target="_blank" href="https://anchor.fm/bsc-criminology">BSC Podcast</a></li>
    <li><a target="_blank" href="https://crimpod.buzzsprout.com/">CrimPod</a></li>
    <li><a target="_blank" href="https://www.cybercrimeology.com/">Cybercrimeology</a></li>
    <li><a target="_blank" href="https://csl.mpg.de/podcasts">Doing Time, Talking Crime</a></li>
    <li><a target="_blank" href="https://www.justicefocus.org/podcast">Justice Focus</a></li>
    <li><a target="_blank" href="https://krimschnack.podigee.io/">KrimSchnack</a></li>
    <li><a target="_blank" href="https://wp.unil.ch/lm-crimpod/">L&M Criminology Podcast</a></li>
    <li><a target="_blank" href="https://www.reducingcrime.com/podcast">Reducing Crime</a></li>
    <li><a target="_blank" href="https://www.swr.de/swr2/leben-und-gesellschaft/podcast-sprechen-wir-ueber-mord-100.html">Sprechen wir über Mord</a></li>
    <li><a target="_blank" href="https://www.tatwort-podcast.de">Tatwort</a></li>
    <li><a target="_blank" href="https://kriminologie.uni-koeln.de/podcast">True Criminology</a></li>
    <li><a target="_blank" href="https://womenandcrimepodcast.com/">Women & Crime</a></li>
    <li><a target="_blank" href="https://www.zeit.de/serie/verbrechen?utm_referrer=https%3A%2F%2Fwww.google.com%2F">Zeit Verbrechen</a></li>
</ul>

<h3>Blogs</h3>
<ul>
    <li><a target="_blank" href="https://criminologia.de/">https://criminologia.de/</a></li>
    <li><a target="_blank" href="https://verfassungsblog.de/">https://verfassungsblog.de/</a></li>
    <li><a target="_blank" href="https://www.britsoccrim.org/blog/">https://www.britsoccrim.org/blog/</a></li>
    <li><a target="_blank" href="https://criminologytales.com/">https://criminologytales.com/</a></li>
    <li><a target="_blank" href="https://www.ui1.es/blog-ui1/etiqueta/criminologia">https://www.ui1.es/blog-ui1/etiqueta/criminologia</a></li>
    <li><a target="_blank" href="https://www.estudiocriminal.eu/blog/">https://www.estudiocriminal.eu/blog/</a></li>
    <li><a target="_blank" href="https://www.crimeur.nl/">https://www.crimeur.nl/</a></li>
    <li><a target="_blank" href="https://blog.associatie.kuleuven.be/ltjb/">https://blog.associatie.kuleuven.be/ltjb/</a></li>
    <li><a target="_blank" href="https://tomdaems.com/blog/">https://tomdaems.com/blog/</a></li>
</ul>

<h3>Newsletter</h3>
<ul>
    <li><a target="_blank" href="https://listserv.uni-tuebingen.de/mailman/listinfo/criminology-cj-news">CCJ-News</a></li>
    <li><a target="_blank" href="https://listserv.uni-tuebingen.de/mailman/listinfo/kriminologie-infodienst">Kriminologie-Infodienst</a></li>
    <li><a target="_blank" href="https://ea.sendcockpit.com/_s.php?&fid=52340&fpw=bb3de23366b193f655fc5c589a9e6273">KrimZ-Newsletter</a></li>
    <li><a target="_blank" href="https://kripoz.de/newsletter/">KriPoZ-Newsletter</a></li>
    <li><a target="_blank" href="https://www.motra.info/wissenstransfer/newsletter-archiv/">MOTRA-Newsletter</a></li>
    <li><a target="_blank" href="https://lists.uni-bielefeld.de/mailman2/cgi/unibi/listinfo/nordkrim">NordKrim</a></li>
    <li><a target="_blank" href="https://www.polizei-newsletter.de/">Polizei-Newsletter</a></li>
    <li><a target="_blank" href="https://resoportal.de/">Reso-Newsletter</a></li>
    <li><a target="_blank" href="https://listserv.uni-tuebingen.de/mailman/listinfo/toa">TOA-Infodienst</a></li>
</ul>

<h3>Vorlesungen und Tutorials</h3>
<ul>
    <li><a target="_blank" href="https://timms.uni-tuebingen.de/tp/UT_20110714_001_rvkrimi_0001">„Kriminalprävention: Prävention durch Strafrecht, insbesondere Sicherungsverwahrung“ (Jörg Kinzig, 2011)</a></li>
    <li><a target="_blank" href="https://www.dvjj.de/tutorials/">Videotutorials der DVJJ: Deutsche Vereinigung für Jugendgerichte und Jugendgerichtshilfen e.V. zu Themen wie Jugendstrafrecht, Jugendkriminalität, etc.</a></li>
    <li><a target="_blank" href="https://timms.uni-tuebingen.de/tp/UT_20041020_001_krimi_0001">„Vorlesung Kriminologie (Einzelfallanalyse), 1. Stunde“ (Rüdiger Wulf, 2004)</a></li>
    <li><a target="_blank" href="https://timms.uni-tuebingen.de/tp/UT_20041110_001_krimi_0001">„Vorlesung Kriminologie (Einzelfallanalyse), 2. Stunde (Rüdiger Wulf & Hans-Jürgen Kerner, 2004)</a></li>
</ul>


<h3>Social Media</h3>

<ul class="social">
    <li>KrimDok:
        <ul>
            <li><a target="_blank" href="https://youtube.com/playlist?list=PLs76r5p4LoGzWTyvj06MI2VLysyXuVUYn&si=sgRepCIn51bEfN3Y"><img src="<?=$this->imageLink('youtube_logo_icon.png')?>" alt="YouTube" width="30">https://youtube.com/playlist?list=PLs76r5p4LoGzWTyvj06MI2VLysyXuVUYn&si=sgRepCIn51bEfN3Y</a></li>
            <li><a target="_blank" href="https://mastodon.social/@KrimDok"><img src="<?=$this->imageLink('Mastodon_icon.jpeg')?>" alt="Mastodon" width="30">https://mastodon.social/@KrimDok</a></li>
            <li><a target="_blank" href="https://bsky.app/profile/krimdok.bsky.social"><img src="<?=$this->imageLink('bluesky-logo.png')?>" alt="Bluesky" width="30">https://bsky.app/profile/krimdok.bsky.social</a></li>
        </ul>
    </li>
    <li>Institut für Kriminologie
        <ul>
            <li><a target="_blank" href="https://www.facebook.com/ifktue"><img src="<?=$this->imageLink('Facebook_Logo.png')?>" alt="Facebook" width="30">https://www.facebook.com/ifktue</a></li>
            <li><a target="_blank" href="https://www.instagram.com/kriminologie_tuebingen/"><img src="<?=$this->imageLink('Instagram_icon.png')?>" alt="Instagram" width="30">https://www.instagram.com/kriminologie_tuebingen/</a></li>
            <li><a target="_blank" href="https://bawü.social/@ifk"><img src="<?=$this->imageLink('Mastodon_icon.jpeg')?>" alt="Mastodon" width="30">https://bawü.social/@ifk</a></li>
            <li><a target="_blank" href="https://bsky.app/profile/did:plc:eq5pzrwtjfyrf4ops5r7hqfw"><img src="<?=$this->imageLink('bluesky-logo.png')?>" alt="Bluesky" width="30">https://bsky.app/profile/did:plc:eq5pzrwtjfyrf4ops5r7hqfw</a></li>
        </ul>
    </li>
    <li>DBH-Fachverband
        <ul>
            <li><a target="_blank" href="https://www.linkedin.com/company/dbh-fachverband/"><img src="<?=$this->imageLink('LinkedIn_icon.png')?>" alt="LinkedIn" width="30">https://www.linkedin.com/company/dbh-fachverband/</a></li>
        </ul>
    </li>
    <li>DPT
        <ul>
            <li><a target="_blank" href="https://www.youtube.com/praeventionstag"><img src="<?=$this->imageLink('youtube_logo_icon.png')?>" alt="YouTube" width="30">https://www.youtube.com/praeventionstag</a></li>
            <li><a target="_blank" href="https://www.facebook.com/praeventionstag"><img src="<?=$this->imageLink('Facebook_Logo.png')?>" alt="Facebook" width="30">https://www.facebook.com/praeventionstag</a></li>
            <li><a target="_blank" href="https://www.linkedin.com/company/deutscher-praeventionstag/"><img src="<?=$this->imageLink('LinkedIn_icon.png')?>" alt="LinkedIn" width="30">https://www.linkedin.com/company/deutscher-praeventionstag/</a></li>
        </ul>
    </li>
    <li>KrimJ
        <ul>
            <li><a target="_blank" href="https://web-cdn.bsky.app/profile/did:plc:t6zpa6htwbpadeslxmc3teek"><img src="<?=$this->imageLink('bluesky-logo.png')?>" alt="Bluesky" width="30">https://web-cdn.bsky.app/profile/did:plc:t6zpa6htwbpadeslxmc3teek</a></li>
        </ul>
    </li>
    <li>Max-Planck-Institut
        <ul>
            <li><a target="_blank" href="https://www.linkedin.com/company/max-planck-institute-for-the-study-of-crime-security-and-law/"><img src="<?=$this->imageLink('LinkedIn_icon.png')?>" alt="LinkedIn" width="30">https://www.linkedin.com/company/max-planck-institute-for-the-study-of-crime-security-and-law/</a></li>
            <li><a target="_blank" href="https://www.youtube.com/channel/UCgGduAEp418Shfrzz9IWYCA"><img src="<?=$this->imageLink('youtube_logo_icon.png')?>" alt="YouTube" width="30">https://www.youtube.com/channel/UCgGduAEp418Shfrzz9IWYCA</a></li>
        </ul>
    </li>
    <li>Strafrecht-Online Freiburg:
        <ul>
            <li><a target="_blank" href="https://www.instagram.com/jurcoach/"><img src="<?=$this->imageLink('Instagram_icon.png')?>" alt="Instagram" width="30">https://www.instagram.com/jurcoach/</a></li>
        </ul>
    </li>
    <li>Universität Graz
        <ul>
            <li><a target="_blank" href="https://www.instagram.com/thinking_law/"><img src="<?=$this->imageLink('Instagram_icon.png')?>" alt="Instagram" width="30">https://www.instagram.com/thinking_law/</a></li>
            <li><a target="_blank" href="https://www.youtube.com/playlist?list=PLm-qGn7rbCujQdSjpC-NCr2vFm5oAehM-"><img src="<?=$this->imageLink('youtube_logo_icon.png')?>" alt="YouTube" width="30">https://www.youtube.com/playlist?list=PLm-qGn7rbCujQdSjpC-NCr2vFm5oAehM-</a></li>
            <li><a target="_blank" href="https://www.linkedin.com/school/rewi-uni-graz"><img src="<?=$this->imageLink('LinkedIn_icon.png')?>" alt="LinkedIn" width="30">https://www.linkedin.com/school/rewi-uni-graz</a></li>
        </ul>
    </li>
    <li>Weißer Ring
        <ul>
            <li><a target="_blank" href="https://www.facebook.com/WEISSERRING/"><img src="<?=$this->imageLink('Facebook_Logo.png')?>" alt="Facebook" width="30">https://www.facebook.com/WEISSERRING/</a></li>
            <li><a target="_blank" href="https://www.instagram.com/weisser_ring"><img src="<?=$this->imageLink('Instagram_icon.png')?>" alt="Instagram" width="30">https://www.instagram.com/weisser_ring</a></li>
            <li><a target="_blank" href="https://www.youtube.com/weisserringev"><img src="<?=$this->imageLink('youtube_logo_icon.png')?>" alt="YouTube" width="30">https://www.youtube.com/weisserringev</a></li>
            <li><a target="_blank" href="https://www.linkedin.com/company/weisserringev/"><img src="<?=$this->imageLink('LinkedIn_icon.png')?>" alt="LinkedIn" width="30">https://www.linkedin.com/company/weisserringev/</a></li>
        </ul>
    </li>
</ul>

<style>
    .social > li > ul > li{
        margin: 5px 0;
    }
    .social img {
        margin-right: 5px;
    }
</style>
