<div class="table_content">
    <div class="table_content_header">
        <h1>Präventive Soziale Arbeit</h1>
        <h3>Master of Arts (M.A.)</h3>
        <h2>Ostfalia Hochschule Wolfenbüttel</h2>
    </div>
    <table>
        <tr>
            <td>Studienform</td>
            <td>Präsenz, Vollzeit, nicht berufsbegleitend, interdisziplinär, praxisnah</td>
        </tr>
        <tr>
            <td>Inhalte</td>
            <td>Grundlagen von Präventionsarbeit und Spezialisierung in einem Schwerpunkt 
                (Kriminologie und Kriminalprävention <span style="text-decoration: underline;">oder</span>
                Gesundheitsförderung, Prävention und Rehabilitation) <br />
                Wissenschaft und Praxis von (Kriminal-)Prävention; Kriminologie, Soziologie, Politik- und Rechtswissenschaft, Kriminalpolitik, empirische Sozialforschung, insb. Evaluationsforschung, Projektmanagement, Personal- und Sozialmanagement inkl. betriebswirtschaftliche Anteile <br />
                Empirisches Praxisforschungsprojekt in Kooperation mit Praxispartner:innen
            </td>
        </tr>
        <tr>
            <td>Semesteranzahl</td>
            <td>4 Semester</td>
        </tr>
        <tr>
            <td>Beginn</td>
            <td>Wintersemester</td>
        </tr>
        <tr>
            <td>ECTS</td>
            <td>120 ECTS</td>
        </tr>
        <tr>
            <td>Voraussetzungen</td>
            <td>
                zulassungsfrei<br />
                erfolgreicher Abschluss eines Diplom- oder Bachelorstudiums Soziale Arbeit oder eines vergleichbaren sozial- oder geisteswissenschaftlichen Studiengangs, vorzugsweise von Studiengängen aus den genannten Fächern der beteiligten Disziplinen
            </td>
        </tr>
        <tr>
            <td>Studiengebühren</td>
            <td>reguläre Semesterbeiträge</td>
        </tr>
        <tr>
            <td>Bewerbungszeitraum</td>
            <td>bis 15.07.</td>
        </tr>
        <tr>
            <td>Bewerbungsprozess</td>
            <td>Online-Bewerbung</td>
        </tr>
        <tr>
            <td>Sonstiges</td>
            <td>Keine Angaben</td>
        </tr>
        <tr>
            <td>Link zur Homepage</td>
            <td><a target="_blank" href="https://www.ostfalia.de/s/master/praeventive-soziale-arbeit">https://www.ostfalia.de/s/master/praeventive-soziale-arbeit</a></td>
        </tr>
    </table>

    <p class="table_content_footer kursiv">Stand: 15.7.2026</p>

</div>
