<div class="table_content">
    <div class="table_content_header">
        <h1>Präventive Soziale Arbeit</h1>
        <h3>Master of Arts (M.A.)</h3>
        <h2>Ostfalia Hochschule Wolfenbüttel</h2>
    </div>
    <table>
        <tr>
            <td>Studienform</td>
            <td>Präsenz, Vollzeit</td>
        </tr>
        <tr>
            <td>Inhalte</td>
            <td>Grundlagen von Präventionsarbeit und Spezialisierung in einem Schwerpunkt 
                (Kriminologie und Kriminalprävention oder
                Gesundheitsförderung, Prävention und Rehabilitation)<br />
                Theorie und Praxis von Prävention<br />
                Empirisches Praxisforschungsprojekt 
            </td>
        </tr>
        <tr>
            <td>Semesteranzahl</td>
            <td>4 Semester</td>
        </tr>
        <tr>
            <td>Beginn</td>
            <td>Wintersemester</td>
        </tr>
        <tr>
            <td>ECTS</td>
            <td>120 ECTS</td>
        </tr>
        <tr>
            <td>Voraussetzungen</td>
            <td>
                Zulassungsfrei<br />
                Erfolgreicher Abschluss eines Diplom- oder Bachelorstudiums Soziale Arbeit oder eines vergleichbaren sozial- oder geisteswissenschaftlichen Studiengangs
            </td>
        </tr>
        <tr>
            <td>Studiengebühren</td>
            <td>reguläre Semesterbeiträge</td>
        </tr>
        <tr>
            <td>Bewerbungszeitraum</td>
            <td>bis 15.07.</td>
        </tr>
        <tr>
            <td>Bewerbungsprozess</td>
            <td>Online-Bewerbung</td>
        </tr>
        <tr>
            <td>Sonstiges</td>
            <td class="kursiv">Keine Angaben</td>
        </tr>
        <tr>
            <td>Link zur Homepage</td>
            <td><a target="_blank" href="https://www.ostfalia.de/s/master/praeventive-soziale-arbeit">https://www.ostfalia.de/s/master/praeventive-soziale-arbeit</a></td>
        </tr>
    </table>

    <p class="table_content_footer kursiv">Stand: 24.6.2026</p>

</div>
