<h1>Servicio de publicaciones secundarias</h1>

<p>
    El FID de Criminología ofrece a los investigadores la posibilidad de una publicación secundaria digital gratuita de sus contribuciones relacionadas con la criminología (artículos de revistas, contribuciones a antologías, reseñas, artículos de enciclopedias...). Como parte del servicio, el FID se encarga de la digitalización, catalogación y publicación secundaria en acceso abierto en el repositorio criminológico. Las publicaciones secundarias se indexan en KrimDok.
</p>
<p>
    Este servicio permite a toda persona activa en el campo académico ejercer su derecho de publicación secundaria 
    cómodamente de conformidad con <a target="_blank" href="https://www.gesetze-im-internet.de/urhg/__38.html">el art. 38 de la UrhG</a> (Ley alemana de propiedad intelectual). En KrimDok también se indizan artículos de 
    relevancia criminológica que no son aptos para una publicación secundaria (así como monografías). Mediante la pestaña "Personas/Entidades", 
    que se encuentra encima de la línea de búsqueda, es posible así consultar la bibliografía criminológica completa de los respectivos autores.
</p>
<p>
    Previa solicitud, el FID asiste a los autores en la comprobación de si es posible una publicación secundaria desde el punto de vista de la propiedad intelectual. Esto incluye también la aclaración de derechos con los editores, que el FID lleva a cabo en la medida de sus posibilidades.
</p>
<ul>
    <li><a target="_blank" href="/krimdok_docs/Zweitveröffentlichungsservice_FAQs_spanish.pdf">Servicio de publicaciones secundarias. Preguntas frecuentes</a></li>
</ul>
