<h1>Open Text Service</h1>

<p>
The Criminology Information Service (FID) offers researchers the possibility of free, digital second publications of their criminologically relevant contributions (journal articles, contributions to anthologies, reviews, encyclopedia articles,...). As part of the service, the FID handles the digitisation, the cataloguing, and the open access publication on the criminological repository. Second publications are indexed on KrimDok.
This service allows researchers to make use of their right of secondary publication in accordance with <a href="https://www.gesetze-im-internet.de/urhg/__38.html">§ 38 UrhG</a>. In addition, criminologically relevant contributions that are not suitable for secondary publication (including monographs) are listed on KrimDok. Using the tab "Persons/Corporations", which can be found above the search bar, users can view a complete criminological bibliography of the respective author.
Upon request, the FID supports authors in checking whether a second publication is possible under copyright law. This also includes the clarification of rights with the publishers, which the FID assumes within the scope of its possibilities.
</p>
<ul>
    <li><a href="/krimdok_docs/Zweitveröffentlichungsservice_FAQs_englisch.pdf">FAQs Open Text Service</a></li>
</ul>
