
<h1>Zweitveröffentlichungsservice</h1>

<p>Der FID Kriminologie bietet Forschenden die Möglichkeit der kostenfreien, digitalen Zweitveröffentlichung ihrer kriminologisch relevanten Beiträge (Zeitschriftenartikel, Beiträge in Sammelbänden, Rezensionen, Lexikonartikel,…). Im Rahmen des Services übernimmt der FID die Digitalisierung, Katalogisierung und Zweitveröffentlichung im Open Access auf dem kriminologischen Repositorium. Zweitveröffentlichungen werden auf KrimDok nachgewiesen.</p>
<p>Durch den Service wird es den Wissenschaftler:innen ermöglicht, auf komfortable Weise von ihrem Zweitveröffentlichungsrecht gem. <a href="https://www.gesetze-im-internet.de/urhg/__38.html">§ 38 UrhG </a> Gebrauch zu machen. Zusätzlich werden auch diejenigen kriminologisch relevanten Beiträge auf KrimDok nachgewiesen, die sich nicht für eine Zweitveröffentlichung eignen (ebenso Monographien). Mittels des Reiters „Personen/Körperschaften“, welcher über der Suchzeile zu finden ist, können Nutzer:innen somit eine vollständige kriminologische Bibliographie der jeweiligen Autor:innen einsehen.</p>
<p>Auf Wunsch unterstützt der FID Autor:innen bei der Prüfung der Frage, ob eine Zweitveröffentlichung nach urheberrechtlichen Gesichtspunkten möglich ist. Dies umfasst auch die Rechteklärung mit den Verlagen, die der FID im Rahmen seiner Möglichkeiten übernimmt.</p>

<ul>
    <li>
        <a href="/krimdok_docs/Zweitveröffentlichungsservice_FAQs.pdf">FAQs Zweitveröffentlichungsservice</a>
    </li>
</ul>
<!--
<h1>Zeitschriften</h1>
<p>
    In KrimDok finden sich rund 4.700 Nachweise zu deutsch- und fremdsprachigen kriminologischen Zeitschriftentiteln, die wahlweise gedruckt, elektronisch, hybrid oder (ganz oder teilweise) retrodigitalisiert publiziert und käuflich oder lizenzfrei von den Verlagen zur Verfügung gestellt werden oder wurden. Bei einem Großteil der Nachweise handelt es sich um Zeitschriften, die mittlerweile ihren Titel geändert oder ihr Erscheinen ganz eingestellt haben.<br/>
    Um den Zugang zu laufenden, kriminologisch relevanten Open-Access-Volltexten zu vereinfachen, wurden thematisch passende lizenzfreie Zeitschriften in einer Übersicht zusammengefasst. Weitere Informationen zu gegenwärtig erscheinenden Zeitschriften sowie zu der Auswertung von Einzelbeiträgen für KrimDok finden Sie in den unten genannten Listen.
</p>
<ul>
    <li><a href="/krimdok_docs/Journals.pdf">Liste der derzeit für KrimDok ausgewerteten Zeitschriften (pdf)</a></li>
    <li><a href="/krimdok_docs/Journals_OA.pdf">Liste kriminologisch relevanter Open-Access-Zeitschriften (pdf)</a></li>
    <li><a href="/krimdok_docs/Journals_Nationallizenz.pdf">Liste kriminologisch relevanter Zeitschriften mit Nationallizenz (pdf)</a></li>
</ul>
-->
