
<h1>Zweitveröffentlichungsservice</h1>

<p>Der FID Kriminologie bietet Forschenden die Möglichkeit der kostenfreien, digitalen Zweitveröffentlichung ihrer kriminologisch relevanten Beiträge (Zeitschriftenartikel, Beiträge in Sammelbänden, Rezensionen, Lexikonartikel,…). Im Rahmen des Services übernimmt der FID die Digitalisierung, Katalogisierung und Zweitveröffentlichung im Open Access auf dem kriminologischen Repositorium. Zweitveröffentlichungen werden auf KrimDok nachgewiesen.</p>
<p>Durch den Service wird es den Wissenschaftler:innen ermöglicht, auf komfortable Weise von ihrem Zweitveröffentlichungsrecht gem. <a href="https://www.gesetze-im-internet.de/urhg/__38.html">§ 38 UrhG </a> Gebrauch zu machen. Zusätzlich werden auch diejenigen kriminologisch relevanten Beiträge auf KrimDok nachgewiesen, die sich nicht für eine Zweitveröffentlichung eignen (ebenso Monographien). Mittels des Reiters „Personen/Körperschaften“, welcher über der Suchzeile zu finden ist, können Nutzer:innen somit eine vollständige kriminologische Bibliographie der jeweiligen Autor:innen einsehen.</p>
<p>Auf Wunsch unterstützt der FID Autor:innen bei der Prüfung der Frage, ob eine Zweitveröffentlichung nach urheberrechtlichen Gesichtspunkten möglich ist. Dies umfasst auch die Rechteklärung mit den Verlagen, die der FID im Rahmen seiner Möglichkeiten übernimmt.</p>

<ul>
    <li>
        <a href="/krimdok_docs/Zweitveröffentlichungsservice_FAQs.pdf">FAQs Zweitveröffentlichungsservice</a>
    </li>
</ul>
