<?php $account = $this->auth()->getManager();
  if (is_object($account) && $account->loginEnabled()): // hide login/logout if unavailable ?>
  <li class="nav-item logoutOptions<?php if($account->dropdownEnabled()): ?> with-dropdown<?php endif ?><?php if(!$account->isLoggedIn()): ?> hidden<?php endif ?>">
    <a class="nav-link" href="<?=$this->url('myresearch-home', [], ['query' => ['redirect' => 0]])?>"><i id="account-icon" class="fa fa-user-circle" aria-hidden="true"></i> <span class="cw-hide-for-xsmoll"><?=$this->transEsc("Your Account")?><span></a>
  </li>
  <?php if($account->dropdownEnabled()): ?>
    <li id="login-dropdown" class="nav-item dropdown<?php if(!$account->isLoggedIn()): ?> hidden<?php endif ?>">
      <a href="#" data-toggle="dropdown"><i class="fa fa-caret-down"></i></a>
      <div class="dropdown-menu">
        <?=$this->render('myresearch/menu'); ?>
      </div>
    </li>
  <?php endif; ?>
  <li class="nav-item logoutOptions<?php if(!$account->isLoggedIn()): ?> hidden<?php endif ?>">
    <a href="<?=$this->url('myresearch-logout')?>" class="logout nav-link"><i class="fa fa-sign-out" aria-hidden="true"></i> <span class="cw-hide-for-xsmoll"><?=$this->transEsc("Log Out")?><span></a>
  </li>
  <li class="nav-item <?php if($account->isLoggedIn()): ?> hidden <?php endif ?>" id="loginOptions">
    <?php if ($account->getSessionInitiator($this->serverUrl($this->url('myresearch-home')))): ?>
      <a class="nav-link" href="<?=$this->url('myresearch-userlogin')?>"><i class="fa fa-sign-in" aria-hidden="true"></i> <span class="cw-hide-for-xsmoll"><?=$this->transEsc("Institutional Login")?><span></a>
    <?php else: ?>
      <a class="nav-link" href="<?=$this->url('myresearch-userlogin')?>" data-lightbox><i class="fa fa-sign-in" aria-hidden="true"></i> <span class="cw-hide-for-xsmoll"><?=$this->transEsc("Login")?><span></a>
    <?php endif; ?>
  </li>
<?php endif; ?>