<!-- TueFind extension template -->
<!-- About -->
<li class="nav-item tf-cursor-pointer">
    <span class="dropdown-toggle black-icon" data-toggle="dropdown"  aria-haspopup="true" aria-expanded="false">
       <i class='fa fa-navicon' ></i> <span class="caret"></span>
    </span>
    <ul class="dropdown-menu">
        <li><a class="dropdown-item" href="<?=$this->url('content-page', ['page' => 'AboutUs']) ?>"><?=$this->transEsc('Index Theologicus')?></a></li>
        <li class="sub-menu"><a class="dropdown-item" href="<?=$this->url('content-page', ['page' => 'AboutUs']) ?>#ixtheo_inhalt"><?=$this->transEsc('Contents')?></a></li>
        <li class="sub-menu"><a class="dropdown-item" href="<?=$this->url('content-page', ['page' => 'AboutUs']) ?>#ixtheo_geschichte"><?=$this->transEsc('History')?></a></li>
        <li class="sub-menu"><a class="dropdown-item" href="<?=$this->url('content-page', ['page' => 'AboutUs']) ?>#ixtheo_publications"><?=$this->transEsc('Further Reading')?></a></li>
        <li role="separator" class="divider"></li>
        <li><a class="dropdown-item" href="<?=$this->url('content-page', ['page' => 'FidTheologie']) ?>"><?=$this->transEsc('Fachinformationsdienst Theologie')?></a></li>
        <li class="sub-menu"><a class="dropdown-item" href="<?=$this->url('content-page', ['page' => 'FidTheologie']) ?>#ixtheo_aufgaben"><?=$this->transEsc('Tasks')?></a></li>
        <li class="sub-menu"><a class="dropdown-item" href="<?=$this->url('content-page', ['page' => 'FidTheologie']) ?>#ixtheo_beirat"><?=$this->transEsc('Scholarly Advisory Board')?></a></li>
        <li role="separator" class="divider"></li>
        <li><a class="dropdown-item" href="<?=$this->url('content-page', ['page' => 'ContactPersons']) ?>"><?=$this->transEsc('Contact Persons')?></a></li>
        <li role="separator" class="divider"></li>
        <li><a class="dropdown-item" href="<?=$this->url('content-page', ['page' => 'A_Z']) ?>"><?=$this->transEsc('IxTheo A to Z')?></a></li>
        <li role="separator" class="divider"></li>
        <li><a class="dropdown-item" href="<?=$this->url('content-page', ['page' => 'Impressum']) ?>"><?=$this->transEsc('About this site')?></a></li>
        <li><a class="dropdown-item" href="<?=$this->url('content-page', ['page' => 'Privacy']) ?>"><?=$this->transEsc('Privacy Policy')?></a></li>
    </ul>
</li>
