<?php
$tuefind = $this->tuefind();
$currentSystem = $tuefind->getTueFindType();
$publicationEmail = $tuefind->getPublicationEmail();
?>

<?=$this->translate('authority_request_access_grant_email_text_1', ['%%currentSystem%%' => $currentSystem, '%%publicationEmail%%' => $publicationEmail])?>

<?=$this->translate('authority_request_access_grant_email_text_2', ['%%currentSystem%%' => $currentSystem, '%%publicationEmail%%' => $publicationEmail])?>

<?=$this->translate('authority_request_access_grant_email_text_3', ['%%currentSystem%%' => $currentSystem, '%%publicationEmail%%' => $publicationEmail])?>

<?=$this->translate('authority_request_access_grant_email_text_4', ['%%currentSystem%%' => $currentSystem, '%%publicationEmail%%' => $publicationEmail])?>

<?=$this->translate('authority_request_access_grant_email_text_5', ['%%currentSystem%%' => $currentSystem, '%%publicationEmail%%' => $publicationEmail])?>

<?=$this->translate('authority_request_access_grant_email_text_6', ['%%currentSystem%%' => $currentSystem, '%%publicationEmail%%' => $publicationEmail])?>

<?=$this->translate('authority_request_access_grant_email_text_7', ['%%currentSystem%%' => $currentSystem, '%%publicationEmail%%' => $publicationEmail])?>
