<h2><?=$this->escapeHtml($this->cmsPagesTranslation->getTitle())?></h2>
<?=$this->tuefind()->transformCmsPageContent($this->cmsPagesTranslation)?>
<?php if (!empty($this->cmsPage->getCustomCss())): ?>
    <style>
        <?=$this->cmsPage->getCustomCss()?>
    </style>
<?php endif; ?>

<?php if (!empty($this->cmsPage->getCustomJs())) {
    $customJs = $this->cmsPage->getCustomJs();
    $jsSnippet = <<<JS
            document.addEventListener('DOMContentLoaded', () => {
                {$customJs}
            });
        JS;
    echo $this->assetManager()->outputInlineScriptString($jsSnippet);
} ?>