<h1>FID-Beirat</h1>
<p>Seit 2018 hat der FID Religionswissenschaft einen wissenschaftlichen Beirat, der sich mit dem FID-Team mindestens einmal jährlich zu einer Sitzung trifft. Der Beirat nimmt eine wichtige Scharnierfunktion zwischen der religionswissenschaftlichen Fachcommunity mit ihren verschiedenen Teildisziplinen und dem FID ein. Die Entwicklung neuer FID-Angebote und der Ausbau der bestehenden FID-Services erfolgen in enger Abstimmung mit dem wissenschaftlichen Beirat, (neue) Arbeitsschritte des FID werden gemeinsam konstruktiv diskutiert. Der Beirat trägt die bereits angebotenen Dienste des FID in die Fachwissenschaft hinein und gibt von dort Feedback an den FID, damit nachvollziehbare Klarheit darüber besteht, ob und wie einzelne Angebote künftig aufgenommen, inhaltlich erweitert oder eingeschränkt werden sollen.</p>
<p>
    Mitglieder des Beirats FID Religionswissenschaft sind aktuell:
    <ul>
        <li>Dr. Martin Radermacher (Universität Bochum) - seit 2018</li>
        <li>Prof. Dr. Monika Schrimpf (Universität Tübingen) - seit 2018</li>
        <li>Prof. Dr. Sebastian Schüler (Universität Leipzig) - seit 2019</li>
		<li>Prof. Dr. Frederik Elwert (Universität Bochum) - seit 2021</li>          
		<li>Prof. Dr. Isabel Laack (Universität Tübingen) - seit 2023</li>
		<li>Prof. Dr. Edith Franke (Universität Marburg) - seit 2024</li>
    </ul>
</p>
<p>
    Ehemalige Mitglieder des FID-Beirats:
    <ul>
        <li>Prof. Dr. Horst Junginger (Universität Leipzig) - bis 2019</li>
        <li>Prof. Dr. Gritt Klinkhammer (Universität Bremen und Vorstandsvorsitzende der DVRW) - bis 2022</li>
		<li>Prof. Dr. Moritz Klenk (Hochschule Mannheim) - bis 2024</li>
    </ul>
</p>
