<h1>FID Advisory Board</h1>
<p>Since 2018, the FID for the Study of Religion has got an Academic Advisory Board that meets with the FID team at least once a year. The Advisory Board acts as an important interface between academics from various sub-disciplines of the study of religion on the one hand and the FID on the other. The development and enhancement of new FID services are closely coordinated with the Advisory Board,(new) work steps of the FID are constructively discussed. The Advisory Board disseminates the services already offered by the FID to the academic community and provides feedback from there to the FID so that there is clarity as to whether and how individual services should be included, expanded or restricted in the future.</p>
<p>
    Current members of the FID Advisory Board:
    <ul>
        <li>Dr. Martin Radermacher (University of Bochum) - since 2018</li>
        <li>Prof. Dr. Monika Schrimpf (University of Tübingen) - since 2018</li>
        <li>Prof. Dr. Sebastian Schüler (University of Leipzig) - since 2019</li>
		<li>Prof. Dr. Frederik Elwert (University of Bochum) - since 2021</li>          
        <li>Prof. Dr. Isabel Laack (University of Tübingen) - since 2023</li>
		<li>Prof. Dr. Edith Franke (University of Marburg) - since 2024</li>
    </ul>
</p>
<p>
    Former members of the FID Advisory Board:
    <ul>
        <li>Prof. Dr. Horst Junginger (University of Leipzig) - until 2019</li>
        <li>Prof. Dr. Gritt Klinkhammer (University of Bremen and Chief Executive Officer of the DVRW) - until 2022</li>
		<li>Prof. Dr. Moritz Klenk (Hochschule Mannheim) - until 2024</li>
    </ul>
</p>
