<?php $this->headTitle($this->translate('Impressum'));?>
<h1>Impressum</h1>
<p>Bitte beachten Sie: Dieses Impressum gilt auch für die offiziellen Social Media-Auftritte des Fachinformationsdienstes auf <a class="icon-link" href="https://bsky.app/profile/relbib.bsky.social" target="new"><?=$this->icon('external-link', 'icon-link__icon') ?><span class="icon-link__label">Bluesky</span></a>, <a class="icon-link" href="https://hcommons.social/@rel_bib" target="new"><?=$this->icon('external-link', 'icon-link__icon') ?><span class="icon-link__label">Mastodon</span></a> und <a class="icon-link" href="https://twitter.com/rel_bib" target="new"><?=$this->icon('external-link', 'icon-link__icon') ?><span class="icon-link__label">X</span></a>.</p>
<h2>Das Internetangebot wird herausgegeben von:</h2>
<table class="table table-striped">
    <tr>
        <td>Dienstanbieter</td>
        <td>Universitätsbibliothek der Eberhard Karls Universität Tübingen</td>
    </tr>
    <tr>
        <td>Anschrift</td>
        <td>Universitätsbibliothek<br/>
            Wilhelmstraße 32<br/>
            72074 Tübingen</td>
    </tr>
    <tr>
        <td>Kontakt</td>
        <td>RelBib-Team der UB Tübingen<br/>
            relbib@ub.uni-tuebingen.de<br/>
            +49 (0)7071 29 74030</td>
    </tr>
    <tr>
        <td>Rechtsform</td>
        <td>Die Universität Tübingen ist eine Körperschaft des öffentlichen Rechts. Sie wird durch die Rektorin Prof. Dr. Dr. h.c. (Dōshisha) Karla Pollmann (E-Mail: rektorin@uni-tuebingen.de) gesetzlich vertreten.</td>
    </tr>
    <tr>
        <td>Umsatzsteuer-Identifikationsnummer</td>
        <td>gemäß § 27a Umsatzsteuergesetz:<br>DE812383453</td>
    </tr>
    <tr>
        <td>Aufsichtsbehörde</td>
        <td>Ministerium für Wissenschaft, Forschung und Kunst Baden Württemberg</td>
    </tr>
    <tr>
        <td>Haftungshinweis</td>
        <td>Trotz sorgfältiger inhaltlicher Kontrolle übernehmen wir keine Haftung für die Inhalte externer Links. Für den Inhalt der verlinkten Seiten sind ausschließlich deren Betreiber verantwortlich.</td>
    </tr>
    <tr>
        <td>Inhaltlich Verantwortliche für das Informationsangebot der Religionswissenschaftlichen Bibliografie gemäß §18 Abs. 2 MStV</td>
        <td>Regine Tobias (Direktorin der Universitätsbibliothek Tübingen)</td>
    </tr>
</table>
