<h1 id="anchor">FID Lizenzen</h1>

<h2><b>Lizenzen des FID Religionswissenschaft</b></h2>
<p>Folgende Lizenzen sind derzeit über den FID Religionswissenschaft nutzbar.</p>

<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#col1">
        <div class="tf-panel-collapse-heading">
            <span><b>World Religion Database</b> – FID-Nationallizenz</span>
        </div>
    </a>
    <div id="col1" class="collapse tf-panel-collapse-body">
        <p>Die <a target="_blank" href="https://www.worldreligiondatabase.org/">World Religion Database</a> (Brill) beinhaltet umfangreiche demografische Statistiken über die jeweiligen Religionszugehörigkeiten in jedem Land der Erde. Die Daten stammen aus Erhebungen und Umfragen und werden durch wissenschaftliche Schätzungen ergänzt, um so Vergleiche zu ermöglichen und Entwicklungen aufzuzeigen. Daten und Schätzungen werden für den Zeitraum 1900 bis 2050 zur Verfügung gestellt. Die Aufstellungen sind nach verschiedenen Gesichtspunkten abrufbar, z.B. nach Glaubensrichtung oder Geografie. Diese Datenbank wird am Institute on Culture, Religion, and World Affairs (CURA), Boston University herausgegeben und regelmäßig aktualisiert.</p>
        <p>Die Datenbank wird als zeitlich befristete Nationallizenz (2022-2024) vom FID Religionswissenschaft bereitgestellt.</p>
    </div>
</div>

<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#col2">
        <div class="tf-panel-collapse-heading">
            <span><b>Jewish Life in America, c1654-1954</b> – FID-Nationallizenz</span>
        </div>
    </a>
    <div id="col2" class="collapse tf-panel-collapse-body">
        <p>Die Datenbank <a target="_blank" href="https://www.jewishlife.amdigital.co.uk">Jewish Life in America</a> (Adam Matthew digital) bietet Zugang zu einer Vielzahl von archivalischen Materialien, die Einblicke in die Geschichte der jüdischen Gemeinden in den USA von der Ankunft der ersten jüdischen Siedler*innen in New Amsterdam im 17. Jahrhundert bis zur Mitte des 20. Jahrhunderts geben. Es handelt sich u. a. um autobiografische Aufzeichnungen einzelner Familien, Sammlungen zu wichtigen historischen Persönlichkeiten des amerikanischen Judentums sowie Aktenbestände privater und staatlicher Organisationen. Diese reichhaltige Quellensammlung stammt aus den Archivbeständen der American Jewish Historical Society in New York City. </p>
        <p>Neben den digitalisierten Archivbeständen stellt die Datenbank auch Hilfsmittel für die Recherche zur Verfügung: u.a. eine Chronologie der wichtigsten Ereignisse, Aufsätze führender Wissenschaftler*innen, Anleitungen zu den vorgestellten Sammlungen, eine Auswahl von Artikeln aus dem American Jewish Year Book, eine Bildergalerie sowie Biografien prominenter Persönlichkeiten, die in der Datenbank enthalten sind.</p>
        <p>Die Datenbank wird dank einer Kooperation des FID <a target="_blank" href="https://www.jewishstudies.de/">Jüdische Studien</a> mit den FID für <a target="_blank" href="https://libaac.de/home/">Anglo-American Culture</a>, <a target="_blank" href="https://www.historicum.net/home">Geschichteswissenschaft</a>, <a target="_blank" href="https://www.osmikon.de/">Ost-, Ostmittel- und Südosteuropa</a> und <a target="_blank" href="https://relbib.de/">Religionswissenschaft</a> seit Januar 2023 als dauerhafte Nationallizenz bereitgestellt.</p>
    </div>
</div>

<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#col3">
        <div class="tf-panel-collapse-heading">
            <span><b>Handbuch der Religionen</b> – NEU ab März 2024!</span>
        </div>
    </a>
    <div id="col3" class="collapse tf-panel-collapse-body">
        <p>Das <a target="_blank" href="<?=$this->recordLinker()->getUrl('1677766123')?>">Handbuch der Religionen</a> ist ein wissenschaftlich fundiertes Nachschlagewerk über das gesamte Spektrum der Religionen in Deutschland und im deutschsprachigen Raum. Auf derzeit ca. 9.500 Seiten in 12 Bänden (Stand: März 2023) und in vier Ergänzungslieferungen pro Jahr mit je ca. 180 Seiten bietet das Handbuch der Religionen:</p>
        <ul>
            <li>wissenschaftlich fundiertes Orientierungswissen</li>
            <li>von einem Team kompetenter Expert*innen aus derzeit 3 Herausgebern, 26 Fachgebietsleiter*innen und mehreren hundert Autor*innen</li>
            <li>über Geschichte, religiöse Kernaussagen und Autoritäten, Organisationen und Verbreitung, Glaubenspraxis sowie das Verhältnis zum Staat und anderen Religionen</li>
            <li>zur gezielten Recherche nach Themenbereichen</li>
            <li>mit kontinuierlichen Informationen zu neuen Entwicklungen, ständig aktualisierten Neuerscheinungen und Kontaktadressen.</li>
        </ul>
    </div>
</div>

<h2><b>ProQuest EBook Collection for the Study of Religion</b></h2>
<p> in Vorbereitung für 2024</p>

<h2><b>Informationen zum Nutzerkreis des FID Religionswissenschaft</b></h2>
<p>Bei den Lizenzangeboten wird zwischen FID Community-Lizenzen und Nationallizenzen unterschieden.</p>

<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#col5">
        <div class="tf-panel-collapse-heading">
            <span><b>FID Community-Lizenz</b></span>
        </div>
    </a>
    <div id="col5" class="collapse tf-panel-collapse-body">
        <p>Zum <b>Nutzerkreis</b> für die FID-Lizenzen im FID Religionswissenschaft gehören neben <b>Religionswissenschaftler*innen</b> im engeren Sinne auch <b>religionsbezogen Forschende anderer Disziplinen</b>, insbesondere der Geistes- und Kulturwissenschaften. Die Anbindung an eine konkrete Institution (z. B. Deutsche Vereinigung für Religionswissenschaft / DVRW oder Universität mit religionswissenschaftlichem Lehrstuhl) ist nicht erforderlich, da Religionswissenschaftler*innen in einem breiten, heterogenen Feld forschen und arbeiten.</p>
        <p>Aufgrund der vertraglichen Vorgaben der Lizenzpartner ist die Nutzung der FID Community-Lizenzen Wissenschaftler*innen des deutschsprachigen Raums vorbehalten. Sie benötigen ein <a target="_blank" href="https://www.relbib.de/Content/my_relbib#content">RelBib-Konto</a>, in dem Sie bevorzugt eine institutionelle E-Mail-Adresse hinterlegen sowie das Land angeben. Nach Recherche des gewünschten, lizenzierten Titels in RelBib gelangen Sie über den Link "FID-Lizenz: Zugriff mit RelBib-Konto" auf den Volltext. </p>
        <p>Beispiel: <a target="_blank" href="<?=$this->recordLinker()->getUrl('1677766123')?>">Handbuch der Religionen</a></p>
        <p>Aktuell sind bis zu 500 Nutzer*innen im FID-Nutzerkreis vorgesehen (Stand: April 2024).</p>
    </div>
</div>
<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#col6">
        <div class="tf-panel-collapse-heading">
            <span><b>Nationallizenzen</b></span>
        </div>
    </a>
    <div id="col6" class="collapse tf-panel-collapse-body">
        <p>Nationallizenzen bieten einen deutschlandweiten Zugriff auf die jeweilige lizenzierte Ressource zu den angegebenen Bedingungen (z. B. zeitliche Beschränkung). Ermöglicht werden die hier aufgeführten Nationallizenzen durch die Förderung der Deutschen Forschungsgemeinschaft (DFG) und die Universitätsbibliothek Tübingen, ggf. auch weitere FID-Bibliotheken.</p>
        <p>Sie können auf Nationallizenzen normalerweise über die <b>IP-Range ihrer Institution</b> zugreifen: Die meisten nationalen Hochschulen und Forschungseinrichtungen sind bereits dafür registriert. <b>Einzelpersonen</b> mit ständigem Wohnsitz in der Bundesrepublik Deutschland können sich persönlich für einen kostenlosen Zugriff <a target="_blank" href="http://www.nationallizenzen.de/einzelnutzer-anmeldung">registrieren</a> lassen, falls ihnen der Zugang über ein Hochschulnetz, bzw. über ihre wissenschaftliche Bibliothek, nicht zur Verfügung steht. </p>
        <p><a target="_blank" href="https://nl.zugang.nationallizenzen.de/han/7722c170-dbf5-4c54-acb0-feaa843ba996">Login für registrierte Einzelnutzer</a></p>
    </div>
</div>

<h2><b>Lizenzen anderer FID</b></h2>
<p>Der FID Religionswissenschaft hat Absprachen mit anderen FID getroffen, die auch RelBib-Nutzer*innen bei entsprechendem Forschungsinteresse den Zugriff auf deren Lizenzangebote gestatten, sofern es sich nicht ohnehin um Nationallizenzen handelt. Hinweis: Der Zugang erfolgt in diesen Fällen nicht über RelBib.</p>

<span id="FID_Sudasien"></span>
<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#col7">
        <div class="tf-panel-collapse-heading">
            <span><b>FID Südasien / FID Asien (via CrossAsia)</b></span>
        </div>
    </a>
    <div id="col7" class="collapse tf-panel-collapse-body">
        <p>Folgende Lizenzprodukte der <a target="_blank" href="https://www.fid4sa.de/home">FID Südasien</a> und FID Asien könnten auch für RelBib-Nutzer*innen relevant sein:</p>
        <ul>
            <li>Brill’s Encyclopedia of Buddhism</li>
            <li>Brill’s Encyclopedia of Jainism </li>
            <li>Brill’s Encyclopedia of the Religions of the Indigenous People of South Asia </li>
            <li>Brill’s Encyclopedia of Sikhism </li>
            <li>Oxford Bibliographies: Buddhism </li>
            <li>Oxford Bibliographies: Hinduism </li>
        </ul>
        <p>Prinzipiell können Nutzer*innen des FID Religionswissenschaft auf die Datenbanken der 
        FID Südasien und Asien via <a target="_blank" href="https://crossasia.org/ressourcen/datenbanken/">CrossAsia</a> zugreifen. Voraussetzung dafür ist, 
        dass Sie einem Institut angehören, das im <a target="_blank" href="https://crossasia.org/mein-crossasia/registrierung/">Anmeldeformular</a> gelistet ist. 
        Dann können Sie sich bei CrossAsia kostenlos registrieren und haben Zugriff auf lizenzierte Ressourcen. 
        Wenn Ihr Institut nicht gelistet ist, kann das Institut mit dem FID Südasien oder mit CrossAsia einen Vertrag über die 
        kostenlose Teilnahme am „Blauen Leihverkehr“ abschließen und dann können sich die Nutzer*innen ebenfalls registrieren.</p>
    </div>
</div>


<span id="FID_Nahost"></span>
<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#col8">
        <div class="tf-panel-collapse-heading">
            <span><b>FID Nahost-, Nordafrika- und Islamstudien</b></span>
        </div>
    </a>
    <div id="col8" class="collapse tf-panel-collapse-body">
        <p>Folgende Lizenzprodukte des <a target="_blank" href="https://www.menalib.de/">FID Nahost- Nordafrika- und Islamstudien</a> könnten auch für RelBib-Nutzer*innen relevant sein:</p>
        <ul>
            <li>
                <a target="_blank" href="https://www.menalib.de/vifa/fid-lizenzen/al-manhal-islamic-studies-e-book-collection/">Al Manhal Islamic Studies E-Book Collection</a> 
                (FID-Nutzerkreislizenz) – über die <a target="_blank" href="https://nahost.fid-lizenzen.de/kfllogin-individual">Einzelnutzerregistrierung</a> können auch Personen außerhalb des vordefinierten Nutzerkreises Zugriff auf die Sammlung erhalten
            </li>
            <li>Zeitschrift <a target="_blank" href="https://www.menalib.de/vifa/fid-lizenzen/muslims-of-the-soviet-east/">Muslims of the Soviet East</a> (Nationallizenz)</li>
            <li>Zeitschriftendatenbank <a target="_blank" href="https://www.menalib.de/vifa/fid-lizenzen/russian-islamic-studies/">Russian Islamic Studies</a> (Nationallizenz)</li>
        </ul>
    </div>
</div>

<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#col9">
        <div class="tf-panel-collapse-heading">
            <span><b>FID Lateinamerika, Karibik und Latino Studies</b></span>
        </div>
    </a>
    <div id="col9" class="collapse tf-panel-collapse-body">
        <p>Folgende Lizenzprodukte des <a target="_blank" href="https://fid-lateinamerika.de/">FID Lateinamerika, Karibik und Latino Studies</a> könnten auch für RelBib-Nutzer*innen relevant sein:</p>
        <ul>
            <li><a target="_blank" href="https://dbis.ur.de/dbinfo/detail.php?titel_id=104456&bib_id=iai">Archivdatenbank Government and Church Documents for Sacatepéquez (1587-1991)</a> – Zugang mit Benutzer-ID des FID Lateinamerika möglich: Bitte wenden Sie sich mit dem Hinweis, dass Sie RelBib-Nutzer*in sind, an das Team des <a target="_blank" href="mailto:fid@iai.spk-berlin.de">FID Lateinamerika</a>.</li>
        </ul>
    </div>
</div>    

<?php
$jsSnippet = <<< 'EOD'
    $(document).ready(function () {
        let URL_string = window.location.href;
        if (URL_string.indexOf("#") > -1) {
            let URL_anchor = URL_string.split("#");
            if(URL_anchor[1].length > 0) {
                $('#'+URL_anchor[1]).next().find('a').click();
            }
        }
    });
EOD;
?>
<?=$this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, $jsSnippet, 'SET')?>
