<h1>Forschungsdatenmanagement</h1>
<p>Der Diskurs zum Umgang mit Forschungsdaten spielt in einer zunehmend digitalen Forschungswelt eine immer größere Rolle. Forschungsförderer wie die DFG verlangen oft schon bei der Beantragung eines Projektes einen Plan zum Forschungsdatenmanagement, um die gute wissenschaftliche Praxis zu sichern. Auch die religionswissenschaftliche Forschung muss sich mit diesem Thema auseinandersetzen. Der FID Religionswissenschaft versteht sich als Vermittler von fachbezogenen Informationen. Auf dieser Seite haben wir daher die wichtigsten Informationen zu Forschungsdaten und Forschungsdatenmanagement (FDM) zusammengestellt. Eine Sammlung von Links auf thematisch relevante Texte komplettiert unser Angebot.</p>
<p>Vom 4. Juni bis 7. Juli 2019 hat der FID Religionswissenschaft im Auftrag der DVRW eine Online-Befragung der Fachcommunity zum Thema „Forschungsdaten in der Religionswissenschaft“ durchgeführt. Mit der Befragung sollte in Erfahrung gebracht werden, welche Kenntnisse und welche Bedarfe bei den Religionswissenschaftler*innen zu diesem Themenkomplex bestehen.</p>

<p>
    <a href="<?=$this->url('content-page', ['page' => 'news'])?>#01_2020">Hier geht es zu den Umfrageergebnissen</a>
</p>

<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#infrastructure">
        <div class="tf-panel-collapse-heading">
            Nationale Forschungsdateninfrastruktur (NFDI)
        </div>
    </a>
    <div id="infrastructure" class="collapse tf-panel-collapse-body">
        <p>
            Mit dem großen Ziel der Integration und Vernetzung aller Akteure, die das Thema Forschungsdaten und Forschungsdatenmanagement betrifft, wurde im November 2018 von der Gemeinsamen Wissenschaftskonferenz (GWK) eine Vereinbarung zum Aufbau einer Nationalen Forschungsdateninfrastruktur (NFDI) getroffen. Die Einrichtung der NFDI soll mit Mitteln des Bundes und der Länder in Höhe von bis zu 90 Mio. Euro über eine Laufzeit von zehn Jahren (2019-2028) gefördert werden. Im Einzelnen geht es darum, Forschungsdaten langfristig systematisch zu erschließen, zu sichern und nachnutzbar zu machen.
        </p>
        <p>
            Durch die Bildung von NFDI-Konsortien sollen sich Nutzer und Anbieter von Forschungsdaten „im Zusammenwirken mit Einrichtungen der wissenschaftlichen Infrastruktur“ vernetzen.
        </p>
        <p>
            Die DFG übernimmt in diesem Prozess die Begutachtungsverfahren für die Förderanträge, auf deren Grundlage die GWK ihre Entscheidungen über die Förderung eines Konsortiums trifft.
        </p>
        <p>
            GWK (Hrsg.): <a href="https://www.gwk-bonn.de/fileadmin/Redaktion/Dokumente/Papers/NFDI.pdf" target="_blank">Bund-Länder-Vereinbarung zu Aufbau und Förderung einer Nationalen Forschungsdateninfrastruktur (NFDI)</a>. 26.11.2018
        </p>
        <p>
            <a href="https://www.dfg.de/foerderung/programme/nfdi/" target="_blank">Informationen rund um die Förderung der NFDI auf der Website der DFG</a>
        </p>
        <p>
            Auswahl an NFDI-Konsortien, die für die Religionswissenschaft relevant sein könnten:
        </p>
        <p>
            <a href="https://nfdi4culture.de/" target="_blank">NFDI4CULTURE</a>: Konsortium für Forschungsdaten aus dem Bereich der Kulturgüter (aktuell gefördert)
        </p>
        <p>
            <a href="https://www.konsortswd.de/" target="_blank">KonsortSWD</a>: Konsortium für die Sozial-, Verhaltens-, Bildungs- und Wirtschaftswissenschaften (aktuell gefördert)
        </p>
        <p>
            <a href="https://www.text-plus.org/" target="_blank">Text+</a>: Konsortium für den Aufbau einer auf Text- und Sprachdaten ausgerichteten Forschungsdateninfrastruktur
        </p>
        <p>
            <a href="https://4memory.de/" target="_blank">NFDI4MEMORY</a>: Konsortium für Forschungsdaten in den historisch arbeitenden Geisteswissenschaften
        </p>
        <p>
            <a href="https://www.nfdi4objects.net/" target="_blank">NFDI4Objects</a>: Konsortium für Forschungsdaten in den objektbezogen arbeitenden Geisteswissenschaften (v.a. Archäologien)
        </p>
        <p>
            We also recommend this short explanatory film by the DFG in English: <a href="https://www.youtube.com/watch?v=uJ01g9m8uE4" target="_blank">What is the National Research Data Infrastructure (NFDI)?</a>
        </p>
    </div>
</div>

<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#common">
        <div class="tf-panel-collapse-heading">
            Allgemeine Informationen
        </div>
    </a>
    <div id="common" class="collapse tf-panel-collapse-body">
        <p>
            Mittlerweile gibt es eine ganze Reihe von informativen Websites und Publikationen zum Thema. Wir stellen Ihnen hier nur eine kleine Auswahl davon vor, die wir als sinnvoll für eine Einführung in die Thematik erachten:
        </p>
        <p>
            <a href="https://www.forschungsdaten.org" target="_blank">Forschungsdaten.org</a> – Wiki rund um das Thema Forschungsdaten
        </p>
        <p>
            <a href="https://www.forschungsdaten.info/" target="_blank">Forschungsdaten.info</a> – Informationsplattform zum Thema „Forschung und Daten managen“
        </p>
        <p>
            <a href="http://forschungsinfrastrukturen.de/doku.php/start" target="_blank">Forschungsinfrastrukturen.de</a> – Informationsseite zu Forschungsinfrastrukturen speziell für die Geisteswissenschaften; enthält auch eine Sammlung von Positionspapieren einzelner geisteswissenschaftlicher Fächer / Fachgesellschaften
        </p>
        <p>
            <a href="https://nfdi.hypotheses.org/" target="_blank">Geisteswissenschaftliches Forum NFDI</a> – ein Blog, der als Informations- und Austauschforum für geisteswissenschaftliche Fachgesellschaften zum Thema NFDI begründet wurde; Anmeldung für eine Mailingliste möglich
        </p>
    </div>
</div>

<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#repositories">
        <div class="tf-panel-collapse-heading">
            Repositorien
        </div>
    </a>
    <div id="repositories" class="collapse tf-panel-collapse-body">
        <p>
            Es gibt bereits eine Vielzahl institutioneller, fachbezogener oder allgemeiner (kommerzieller) Repositorien, die eine Archivierung von Forschungsdaten anbieten. Da in der religionswissenschaftlichen Forschung verschiedenartige Methoden aus anderen Wissenschaften zum Einsatz kommen, können für die Datenspeicherung auch unterschiedliche Repositorien in Frage kommen. Hier finden Sie eine vorläufige Liste von für die Religionswissenschaft relevanten Repositorien:
        </p>
        <p>
            <a href="https://www.clarin-d.net/de/" target="_blank">CLARIN-D</a> – Verbund von Forschungsdatenarchiven mit textbezogenem Schwerpunkt (Sprachwissenschaften)
        </p>
        <p>
            <a href="https://de.dariah.eu/repository" target="_blank">DARIAH-DE Repository</a> – Forschungsdatenrepositorium für Geistes- und Kulturwissenschaften; eher textbezogen
        </p>
        <p>
            <a href="https://www.gesis.org/en/services/archiving-and-sharing" target="_blank">GESIS Datenarchivierung</a> (Datenarchivierungsservice) und <a href="https://data.gesis.org/sharing/#!Home" target="_blank">GESIS datorium</a> (Selbstarchivierung) – Datenarchiv für Sozialwissenschaften
        </p>
        <p>
            <a href="http://www.qualiservice.org/" target="_blank">Qualiservice</a> – Datenservicezentrum für Forschungsdaten aus der qualitativen Sozialforschung
        </p>
        <p>
            <a href="https://depositonce.tu-berlin.de/handle/11303/9911" target="_blank">aviDa</a> – Forschungsdatenzentrum für audio-visuelle Daten der qualitativen Sozialforschung (seit 1/2021 von <a href="https://www.konsortswd.de/ratswd/" target="_blank">RatSWD</a> akkreditiert)
        </p>
        <p>
            Für die Recherche nach einem geeigneten Forschungsdatenrepositorium, nach einer fachlichen Datenbank oder anderen Ressourcen mit Bezug zu Forschungsdaten existieren einige Suchportale. Diese sind allerdings nicht immer aktuell bzw. für eine Recherche nach religionswissenschaftlichen Gesichtspunkten feingestellt.
        </p>
        <p>
            <a href="https://www.re3data.org/" target="_blank">Re3data</a> – internationale Registrierungsagentur für Forschungsdatenrepositorien
        </p>
        <p>
            <a href="http://risources.dfg.de/" target="_blank">RISources</a> – Informationsportal der DFG zu Forschungsinfrastrukturen
        </p>
    </div>
</div>

<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#recommendations">
        <div class="tf-panel-collapse-heading">
            Empfehlungen und Richtlinien
        </div>
    </a>
    <div id="recommendations" class="collapse tf-panel-collapse-body">
        <p>
            Allianz der deutschen Wissenschaftsorganisationen (Hrsg.): <a href="http://doi.org/10.2312/ALLIANZOA.019" target="_blank">Grundsätze zum Umgang mit Forschungsdaten</a>. 2010
        </p>
        <p>
            Wissenschaftsrat (Hrsg.): <a href="https://www.wissenschaftsrat.de/download/archiv/2359-12.pdf" target="_blank">Empfehlungen zur Weiterentwicklung der wissenschaftlichen Informationsinfrastrukturen in Deutschland bis 2020</a>. 2012
        </p>
        <p>
            Rat für Informationsinfrastrukturen (Hrsg.): <a href="http://www.rfii.de/?p=1998" target="_blank">Leistung aus Vielfalt</a>. 2016
        </p>
        <p>
            EUROPEAN COMMISSION / Directorate-General for Research & Innovation (Hrsg.): <a href="https://ec.europa.eu/research/participants/data/ref/h2020/grants_manual/hi/oa_pilot/h2020-hi-oa-data-mgt_en.pdf" target="_blank">Guidelines on FAIR Data Management in Horizon 2020</a>. 2016
        </p>
        <p>
            DFG (Hrsg.): <a href="https://doi.org/10.5281/zenodo.6472827" target="_blank">Kodex „Leitlinien zur Sicherung guter wissenschaftlicher Praxis“</a>. 2013
        </p>
        <p>
            DFG (Hrsg.): <a href="https://www.dfg.de/resource/blob/172112/4ea861510ea369157afb499e96fb359a/leitlinien-forschungsdaten-data.pdf" target="_blank">Leitlinien zum Umgang mit Forschungsdaten</a>. 2015
        </p>
        <p>
            In Ergänzung dazu:
            <a href="https://www.dfg.de/resource/blob/173710/045c16e9430426ef321c76dabcbaaf51/handreichung-fachkollegium-106-forschungsdaten-data.pdf" target="_blank">Handreichung des DFG-Fachkollegiums 106 Sozial- und Kulturanthropologie, Außereuropäische Kulturen, Judaistik und Religionswissenschaft zum Umgang mit Forschungsdaten (PDF | 124 KB)</a>. 2019
        </p>
        <p>
            Mark D. Wilkinson und 52 weitere Autor*innen: The FAIR Guiding Principles for scientific data management and stewardship, in: Scientific Data volume 3, Article number: 160018 (2016) <a href="https://doi.org/10.1038/sdata.2016.18" target="_blank">https://doi.org/10.1038/sdata.2016.18</a>
        </p>
        <p>
            Arbeitsgruppe Forschungsdaten (Hrsg.): <a href="http://doi.org/10.2312/allianzoa.029" target="_blank">Forschungsdatenmanagement. Eine Handreichung</a> [Arbeitsgruppe Forschungsdaten der Schwerpunktinitiative „Digitale Information“ der Allianz der deutschen Wissenschaftsorganisationen]. 2018
        </p>
        <p>
            Daneben lohnt sich auf jeden Fall auch ein Blick auf die Forschungsdaten-Policy der eigenen Institution, die Sie für Ihre Forschungsarbeiten im Vorfeld konsultieren sollten.
        </p>
        <p>
            z. B. Universität Tübingen (Hrsg.): <a href="https://uni-tuebingen.de/forschung/service/unterstuetzung-bei-der-antragstellung/leitlinien-zum-forschungsdatenmanagement/" target="_blank">Leitlinien zum FDM</a>
        </p>
    </div>
</div>
