<h1>Self-archiving und Zweitveröffentlichungsservice</h1>
<h2><b>Self-archiving Service für alle Autor*innen der Religionswissenschaft</b></h2>
<p>
    Der FID Religionswissenschaft unterstützt und fördert den freien Zugang zu bereits publizierter religionswissenschaftlicher Forschungsliteratur. Zur Förderung des Green Open Access bieten wir Wissenschaftler*innen die Möglichkeit, von Ihnen verfasste Publikationen direkt über die Katalognachweise in <a href="https://relbib.de/">RelBib</a> zweitzuveröffentlichen.
</p>
<p>
    Dazu benötigen Sie ein RelBib-Konto und müssen nachweisen, dass Sie der*die Autor*in sind. Wenn Sie bereits ein RelBib-Konto haben und der Zugriff auf Ihre Autor*innen-ID genehmigt wurde, müssen Sie sich lediglich <a href="<?=$this->url('myresearch-userlogin')?>" data-lightbox>einloggen</a> und können im Anschluss beim ausgewählten Beitrag auf „<?=$this->transEsc('publication_request_button')?>“ klicken und Ihr Digitalisat hochladen.
</p>
<p>
    Wenn Sie sich noch nicht für den Service registriert haben, gehen Sie wie folgt vor:
</p>
<ol>
    <p><b>Registrierung</b></p>
    <li>Sie benötigen ein RelBib-Konto.</li>
    <p>Dafür müssen Sie sich einmalig mit einer gültigen E-Mail-Adresse registrieren. Den Link zur Registrierung und zum Login finden Sie auf der Startseite rechts oben unter dem Button „<?=$this->transEsc('Login')?>“.</p>
    <p>Sobald Sie ein RelBib-Konto haben, können Sie mit den weiteren Schritten fortfahren.</p>

    <p><b>Rechte beantragen</b></p>
    <li>Sobald Sie in Ihrem RelBib-Konto angemeldet sind, können Sie den Zugriff auf Ihre Autor*innen-ID beantragen. Dazu wählen Sie den Reiter „<?=$this->transEsc('Persons / Corporations')?>“ oberhalb des Suchschlitzes. Suchen Sie nach Ihrem Namen und wählen Sie den richtigen Eintrag aus.</li>
    <li>Klicken Sie auf den Button „<?=$this->transEsc('authority_access_request_button')?>“.</li>
    <li>Ihre Anfrage wird nun automatisch an das RelBib-Team geschickt. Wir überprüfen, ob Sie die genannte Person sind, und informieren Sie innerhalb weniger Tage per E-Mail, ob Ihr Antrag genehmigt wurde.</li>
    <br>
    <p>Nun können Sie im nächsten Schritt Ihre Publikationen hochladen.</p>

    <p><b>Upload (self-archive)</b></p>
    <li>Sobald Ihr Antrag genehmigt wurde, melden Sie sich erneut in Ihrem RelBib-Konto an. Nun können Sie jeden Titel für eine Zweitveröffentlichung auswählen, der mit Ihnen als Autor*in verknüpft ist. Wenn Sie auf den Button „<?=$this->transEsc('publication_request_button')?>“ klicken, können Sie ein Digitalisat Ihrer Publikation als PDF-Datei hochladen.</li>
    <li>Im Anschluss wird Ihre Datei auf das Repositorium hochgeladen. Im Regelfall steht sie ab dem folgenden Tag für andere Nutzer*innen im Open Access zur Verfügung. Gleichzeitig werden stabile Links (handle/doi) generiert, die Sie ebenfalls ab dem folgenden Tag abrufen können. Diese Links bleiben dauerhaft erhalten und können von Ihnen für Forschung und Lehre verwendet werden.</li>
    <br>

    <p><b>Fragen?</b></p>
    <p>Bitte beachten Sie auch das <a href="/Content/PublicationFAQ">FAQ zum Self Archiving Service</a>.</p>
    <p>Wenn Sie bei einer Publikation, die von Ihnen stammt, trotzdem keine Datei hochladen können, eine Frage haben oder auf ein anderes Problem stoßen, wenden Sie sich bitte an <a href="mailto:relbib-self-archiving@ub.uni-tuebingen.de">relbib-self-archiving@ub.uni-tuebingen.de</a>.</p>
</ol>

<h3><b>Zweitveröffentlichungsservice für Autor*innen aus dem DACH-Raum</b></h3>
<p>Für Wissenschaftler*innen aus dem DACH-Raum bietet der Fachinformationsdienst neben dem Selbstupload über den Self Archiving Service einen umfangreichen Zweitveröffentlichungsservice an, um die Online-Zugänglichkeit zu religionswissenschaftlicher Literatur zu steigern. Dabei übernehmen wir die Katalogisierung, Rechteprüfung, Digitalisierung sowie die Langzeitarchivierung der Zweitveröffentlichungen im Fachrepositorium Religionswissenschaft an der Universitätsbibliothek Tübingen. Selbstverständlich sind die Zweitveröffentlichungen dann in <a href="https://relbib.de/">RelBib</a> recherchierbar und zugänglich.</p>
<p>Wenn Sie Interesse an diesem Angebot oder Fragen haben, nehmen Sie gerne Kontakt mit uns auf: <a href="mailto:relbib@ub.uni-tuebingen.de">relbib@ub.uni-tuebingen.de</a></p>

<p>Siehe hierzu auch die <a href="/docs/Zweitveroeffentlichung_FAQ.pdf" target="_blank">Liste von FAQs zum Thema Zweitveröffentlichung</a>.</p>

<p><a href="/relbib_docs/Infoblatt_ZVP_RelBib.pdf" target="_blank"><b>Kurzinformation zum Zweitveröffentlichungsservice</b></a></p>

<h2>Kontakt</h2>
<p>
    Nikolas Magin, M. A.<br/>
    Mitarbeiter des FID Religionswissenschaft/<br/>
    Religionswissenschaftliche Bibliografie (RelBib)<br/>
    Universitätsbibliothek Tübingen
</p>
<p>
    Tel: +49 / (0) 7071 / 29-74030<br/>
    E-Mail: <a href="mailto:nikolas.magin@uni-tuebingen.de">nikolas.magin@uni-tuebingen.de</a>
</p>
