<h1>Self-archiving service</h1>
<p>
    The Special Information Service for the Study of Religion offers scholars a self-archiving service in order to increase online accessibility to literature of the study of religion. You can self-archive your essays and articles via a simple process and make them available in Green Open Access.
</p>
<p>
    If you already have a RelBib-account and your access to your author ID has been approved, you only need to <a href="<?=$this->url('myresearch-userlogin')?>" data-lightbox>login</a>, select the article you want to upload and click on "<?=$this->transEsc('publication_request_button')?>".
</p>
<p>
    If you haven't registered yet for this service, you should proceed as follows:
</p>
<ol>
    <p><b>Registration</b></p>
    <li>You need a RelBib account.</li>
    <p>You can register using a valid e-mail address. You can access the registration and login pop-up window by pressing on the „<?=$this->transEsc('Login')?>” button at the top right corner of the home page.</p>
    <p>Once you have a RelBib account, you can proceed with your request.</p>

    <p><b>Requesting Access Rights</b></p>
    <li>Once you’ve logged into your RelBib account, you can request access to your author ID. First click on the tab labelled „<?=$this->transEsc('Persons / Corporations')?>“ above the search field, then search for your name and select the right entry.</li>
    <li>Click on the button „<?=$this->transEsc('authority_access_request_button')?>“.</li>
    <li>Your request will be automatically sent to the RelBib-team. We will then verify your identity and inform you within a few days per e-mail whether your request has been approved.</li>
     <p>In the next step, you can upload your articles.</p>


    <p><b>Upload (self-archive)</b></p>
    <li>Once your request has been approved, log into your RelBib account. You can now select every essay linked to you as an author for self-archiving. When you click on the „<?=$this->transEsc('publication_request_button')?>“ button, you can upload your article as a PDF-file.</li>
    <li>Your file then gets uploaded on our repository. It should be available in Open Access to other users on the following day. At the same time, stable links (handle/doi) to the file are generated, which you can also access on the following day. These links are permanent, and you can use them in your research and teaching activities.</li>
    <br>

    <p><b>Any questions?</b></p>
    <p>Please also see our <a href="/Content/PublicationFAQ">FAQ</a> for further information.</p>
    <p>If you have any trouble uploading your files, or for any other problem or question you might have, please contact us at  <a href="mailto:relbib-self-archiving@ub.uni-tuebingen.de">relbib-self-archiving@ub.uni-tuebingen.de</a>.</p>
</ol>

<h2>Contact</h2>
<p>
    Nikolas Magin, M. A.<br/>
    Staff member of the Special Information Service for the Study of Religion/<br/>
    Bibliography of the Study of Religion (RelBib)<br/>
    Tübingen University Library
</p>
<p>
    Tel: +49 / (0)7071 / 29-74030<br/>
    E-Mail: <a href="mailto:nikolas.magin@uni-tuebingen.de">nikolas.magin@uni-tuebingen.de</a>
</p>
