<h1>VDB-Fachreferent*innen-Workshop des FID Religionswissenschaft: Ergebnisse und Präsentationen</h1>
<p class="rb-news-date" style="text-align: right; margin-right: 20px;">(Februar 2024)</p>

<p>Am 30.11.2023 und 01.12.2023 begrüßte der FID Religionswissenschaft Fachreferent*innen und Bibliothekar*innen der Religionswissenschaft im Historischen Lesesaal der Universitätsbibliothek (UB) Tübingen. Der Workshop fand unter dem Titel „Der Fachinformationsdienst Religionswissenschaft stellt sich vor: RelBib, FID-Services und die Vernetzung mit Fachreferent*innen und Bibliothekar*innen der Religionswissenschaft“ statt. Die Teilnehmenden waren aus verschiedenen Standorten in Deutschland – von Rostock bis Freiburg – angereist. </p>
<p>Dieser mit <a target="_blank" href="https://www.vdb-online.org/kommissionen/fachreferat/">Unterstützung der VDB-Kommission für Fachreferatsarbeit</a> durchgeführte Workshop richtete sich an eine Zielgruppe, die der FID bisher noch nicht in den Fokus genommen hatte. Neben der Vorstellung des FID, seiner Services, Projekte und Kooperationen stand vor allem der Austausch mit den Kolleg*innen aus den Bibliotheken an religionswissenschaftlichen Standorten im Fokus der Veranstaltung.</p>
<p>Ziel des zweitägigen Workshops war es, die Teilnehmenden über die FID-Angebote und -Dienstleistungen zu informieren, darüber hinaus aber auch die Situation und Bedarfe in der Fachreferatsarbeit vor Ort zu ermitteln. Im Rahmen des Austauschs an Thementischen konnten Erfahrungen der einzelnen Bibliotheksstandorte zusammengetragen sowie mögliche Anknüpfungspunkte für die Unterstützung vor Ort durch den FID ermittelt werden. Zudem wurden Wege für die zukünftige Kommunikation und Vernetzung ausgelotet. Für eine nachhaltigere Vernetzung und Kooperation auf Ebene der Fachreferate wurde die Einrichtung eines E-Mail-Verteilers sowie ein regelmäßiges Online-Format für den Austausch untereinander vereinbart.</p>
<p>Künftig möchte der FID mit der Gruppe der Fachreferent*innen als Multiplikator*innen für die FID-Angebote an den einzelnen Universitätsstandorten verstärkt zusammenarbeiten. Dies betrifft beispielsweise Kooperationen im Bereich der Schulungsangebote für die Fachcommunity.</p>

<img src="<?=$this->imageLink('workshop_2024/gruppenbild.jpg')?>">
<p style="text-align: right;"><b><i>Die Teilnehmenden des Workshops vor dem historischen Bonatzbau der UB Tübingen.</i></b></p>
<br />

<p>Nachfolgend ist das Programm des Workshops einschließlich der Links auf die Präsentationen aufgeführt:</p>

<h3 class="blue_title">Programm</h3>
<h4 class="blue_title">Donnerstag, 30.11.2023</h4>

<table border="2" class="table table-bordered">
    <tr>
        <td class="tbl-date">12.30 – 13.30</td>
        <td>
            <p>Ankunft, Registrierung, Kennenlernen bei einem Mittagssnack</p>
        </td>
    </tr>
    <tr>
        <td>13.30 – 14.00</td>
        <td>
            <p>Eröffnung des Workshops: Sabine Krauch (stv. Direktorin UB Tübingen), Martin Faßnacht (Leiter Abteilung Fachinformationsdienste UB Tübingen)</p>
        </td>
    </tr>
    <tr>
        <td>14.00 – 15.30</td>
        <td>
            <p>Block I</p>
        </td>
    </tr>
    <tr>
        <td></td>
        <td>
            <p><i><a target="_blank" href="http://dx.doi.org/10.15496/publikation-93479">Vorstellung des FID Religionswissenschaft: Mareike Heinritz, Nikolas Magin</a></i></p>
        </td>
    </tr>
    <tr>
        <td></td>
        <td>
            <p>Vorstellung der Aufgaben und Services des FID; Präsentation des FID-Portals RelBib und seiner Angebote für Religionswissenschaftler*innen. Wir gehen dabei insbesondere auf die Open-Access-Aktivitäten des FID ein. </p>
        </td>
    </tr>
    <tr>
        <td>15.30 – 16.00</td>
        <td>
            <p>Pause</p>
        </td>
    </tr>
    <tr>
        <td>16.00 – 17.30</td>
        <td>
            <p>Block II</p>
        </td>
    </tr>
    <tr>
        <td></td>
        <td>
            <p style="color:#951e37;"><i>Erfahrungsaustausch und Bedarfsermittlung</i></p>
        </td>
    </tr>
    <tr>
        <td></td>
        <td>
            <p>Direkter Austausch. Ziel ist, die Erfahrungen der einzelnen Bibliotheksstandorte in der Fachreferatsarbeit zusammenzutragen, mögliche Anknüpfungspunkte für die Unterstützung vor Ort durch den FID zu ermitteln sowie Wege für die zukünftige Kommunikation und Vernetzung auszuloten.</p>
        </td>
    </tr>
    <tr>
        <td>Ab 19 Uhr</td>
        <td>
            <p>Gemeinsames Abendessen</p>
        </td>
    </tr>
</table>

<h4 class="blue_title">Freitag, 01.12.2023</h4>

<table border="2" class="table table-bordered">
    <tr>
        <td class="tbl-date">09.00 – 10.15</td>
        <td>
            <p>Block III</p>
        </td>
    </tr>
    <tr>
        <td></td>
        <td>
            <p style="color:#951e37;"><i>Kooperationen mit Archiven und Sammlungen</i></p>
        </td>
    </tr>
    <tr>
        <td></td>
        <td>
            <p>Vorstellung des im Dezember 2022 abgeschlossenen Kooperationsprojekts zwischen dem FID Religionswissenschaft und dem REMID-Archiv. Dessen Übernahme in die Bestände der UB Marburg hat den Zugang zum physischen Material deutlich verbessert. Die Auffindbarkeit des Materials in RelBib führt zu einer größeren Sichtbarkeit der Sammlung. Ein weiteres geplantes Projekt zu einem thematisch ähnlichen Archivbestand an der Universität Leipzig wird ebenfalls vorgestellt. Im Austausch mit den Teilnehmenden möchten wir weitere relevante Sammlungen identifizieren, die für den zentralen Nachweis in Relbib geeignet erscheinen.</p>
        </td>
    </tr>
    <tr>
        <td></td>
        <td>
            <p>
                <ul>
                    <li>
                        <a target="_blank" href="http://dx.doi.org/10.15496/publikation-93763">REMID-Archiv / UB Marburg: Nikolas Magin</a>
                    </li>
                </ul>
            </p>
        </td>
    </tr>
    <tr>
        <td></td>
        <td>
            <p>
                <ul>
                    <li>
                        <a target="_blank" href="<?=$this->imageLink('workshop_2024/20231201_FR-Workshop_Tuebingen_Dokumentationsstelle_Leipzig_CC-BY.pdf')?>">Archiv und Dokumentationsstelle „Religiöser und weltanschaulicher Pluralismus in Deutschland“ / Universität Leipzig: Sophie Krohn </a>
                    </li>
                </ul>
            </p>
        </td>
    </tr>
    <tr>
        <td>10.15 – 10.30</td>
        <td>
            <p>Pause</p>
        </td>
    </tr>
    <tr>
        <td>10.30 – 12.00</td>
        <td>
            <p>Block IV</p>
        </td>
    </tr>
    <tr>
        <td></td>
        <td>
            <p style="color:#951e37;"><i>Kooperationen mit anderen Fachinformationsdiensten</i></p>
        </td>
    </tr>
    <tr>
        <td></td>
        <td>
            <p>Aufgrund bestehender Schnittmengen mit einigen anderen Fachinformationsdiensten engagiert sich der FID Religionswissenschaft im Aufbau von (derzeit v.a. bilateralen) Kooperationen. Insbesondere geht es um die Übernahme fachrelevanter Bestände in die RelBib-Indexierung, die gegenseitig unterstützende und ergänzende Öffentlichkeitsarbeit sowie die Beratung / Vermittlung von Nutzenden an ergänzende Angebote der anderen FID. </p>
        </td>
    </tr>
    <tr>
        <td></td>
        <td>
            <p>
                <ul>
                    <li>
                        <a target="_blank" href="<?=$this->imageLink('workshop_2024/20231201_FR-Workshop_Tuebingen_FID4SA_CC-BY-SA.pdf')?>">FID Südasien (FID4SA): Nicole Merkel-Hilf </a>
                    </li>
                </ul>
            </p>
        </td>
    </tr>
    <tr>
        <td></td>
        <td>
            <p>
                <ul>
                    <li>
                        <a target="_blank" href="<?=$this->imageLink('workshop_2024/20231201_FR-Workshop_Tuebingen_FIDNahost_CC-BY.pdf')?>">FID Nahost-, Nordafrika- und Islamstudien (FID Nahost): Volker Adam</a>
                    </li>
                </ul>
            </p>
        </td>
    </tr>
    <tr>
        <td>12:00 – 12:30</td>
        <td>
            <p>Resümee und Abschluss</p>
        </td>
    </tr>
</table>

<style>
.blue_title {
    color: #2F5496;
}
.tbl-date {
    width: 120px;
}
.table>tbody>tr>td>p {
    margin-bottom: 0;
}
</style>