<div class="ixtheo50 container-fluid">
  <section class="cw-p-3 col-md-12 bl1">
    <div class="container">
      <h1 class="cw-h1" style="font-size: 20px;"><span style="font-size: 16px; font-weight: normal;">Workshop: </span>„10 Jahre FID Religionswissenschaft – Quo vadis? 
        Wege zu einem gerechten, dauerhaften und offenen Zugang zu religionswissenschaftlicher Forschung“</h1>
      <br />
      <p>
        <b>Datum:</b> 19. November 2026, 12:00 Uhr – 20. November 2026, 12:30 Uhr<br />
        <b>Ort:</b> Historischer Lesesaal der Universitätsbibliothek Tübingen (Wilhelmstraße 32, 72074 Tübingen) & online
      </p>
      <p>
        Seit 2016 wird der Fachinformationsdienst (FID) Religionswissenschaft an der UB Tübingen betrieben. In den vergangenen 10 Jahren haben wir die Online-Bibliografie 
        RelBib als zentrales Portal für den Zugang zu religionswissenschaftlichen Fachinformationen und -ressourcen aufgebaut sowie verschiedene Open-Access-Services 
        für die deutschsprachige Fachcommunity eingeführt. In einem gemeinsamen Workshop möchten wir nun mit Ihnen unter dem Motto 
        „Vernetzung des globalen religionswissenschaftlichen Wissens“ in den Austausch treten und überlegen, wie diese (noch) besser gelingen kann.
        Dabei richten wir besonderes Augenmerk auf den gerechten, offenen und dauerhaften Zugang zu religionswissenschaftlicher Forschung weltweit.
        Mit Hinblick auf das langfristige Anschlussförderprogramm der DFG für etablierte Fachinformationsdienste möchten wir anhand dreier Themenblöcke 
        gemeinsam mit Ihnen herausfinden, in welchen Bereichen der FID noch stärker auf die fachlichen Bedarfe eingehen und die Unterstützung der 
        Fachcommunity ausbauen kann. Zugleich wünschen wir uns auch Rückkopplung aus der Fachcommunity zu Themen, 
        die vertiefte fachliche Expertise und praktische Anwendungsszenarien benötigen. 
      </p>
      <p class="mb-0">Folgende Programmblöcke haben wir geplant:</p>
      <ol class="ms-3">
        <li>
          Decoloniality und gerechten Zugang zu Wissen ermöglichen: In diesem ersten Block werden sowohl aus religionswissenschaftlicher als auch aus 
          bibliothekarischer Perspektive Überle-gungen dazu angestellt, wie u.a. wissenschaftliche Publikationen aus dem globalen Süden in 
          Portale wie RelBib Eingang finden und dort besser sichtbar gemacht werden können.
        </li>
        <li>
          Fordern und Fördern eines offenen Zugangs: Im zweiten Block werden Open-Access-Aktivitäten und -Projekte der Fachcommunity vorgestellt. 
          Wir wollen außerdem mit Ihnen den weiteren Ausbau der bestehenden Open-Access-Dienste des FID diskutieren.
        </li>
        <li>
          Dauerhaften Zugang schaffen - religionswissenschaftliche Projekte und Sammlungen im Fokus: Zum Abschluss laden wir Projekt- und Sammlungsvertreter*innen 
          ein, im Format des Lightning Talks Ihre Erfahrungen und Best Practices hinsichtlich des langfristigen Zugangs und der Sichtbarkeit von Forschungsergebnissen, 
          Archivmaterialien etc. zu teilen.
        </li>
      </ol>
      <p><b>Call for Lightning Talks:</b> Bitte senden Sie uns Ihre Themenvorschläge für einen 5-10-minütigen Beitrag bis zum <b>15. September 2026</b> an <b><a target="_blank" href="mailto:relbib@ub.uni-tuebingen.de">relbib@ub.uni-tuebingen.de</a></b>.</p>
      <p><b>Anmeldung:</b> Um Anmeldung bis spätestens <b>15. Oktober 2026</b> über die Plattform Pretix wird gebeten (<a target="_blank" href="https://pretix.eu/relbib/workshop2026/">https://pretix.eu/relbib/workshop2026/</a>). Bitte geben Sie bei der Anmeldung an, ob Sie in Präsenz oder online per Zoom teilnehmen möchten. Teilen Sie uns außerdem mit, ob Sie beim gemeinsamen Abendessen am 19. November 2026 (Donnerstag) dabei sein werden.</p>
    </div>
  </section>
  <section class="cw-p-3 col-md-12 cw-bg-gray-100 bl2">
    <div class="container">
      <h3 class="cw-mt-6"><b>Vorläufiges Programm:</b></h3>
      <div class="col-md-12 row">
        <table class="table table-striped">
          <thead>
            <tr>
              <th colspan="2" style="color:#951e37;">Donnerstag, 19. November 2026</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td class="uhr-td">12.00 – 13.00</td>
              <td>Ankommen und Mittagssnack</td>
            </tr>
            <tr>
              <td class="uhr-td">13:00 – 13:30</td>
              <td>Grußworte</td>
            </tr>
            <tr>
              <td class="uhr-td">13:30 – 14:00</td>
              <td>10 Jahre FID Religionswissenschaft – Quo vadis?</td>
            </tr>
            <tr>
              <td class="uhr-td">14:00 – 14:15</td>
              <td>Pause</td>
            </tr>
            <tr>
              <td class="uhr-td">14:15 – 15:45</td>
              <td>Programmblock 1: Decoloniality und gerechten Zugang zu Wissen ermöglichen</td>
            </tr>
            <tr>
              <td class="uhr-td">15:45 – 16:15</td>
              <td>Pause</td>
            </tr>
            <tr>
              <td class="uhr-td">16:15 – 17:45</td>
              <td>Programmblock 2: Fordern und Fördern eines offenen Zugangs</td>
            </tr>
            <tr>
              <td class="uhr-td">19:00</td>
              <td>Möglichkeit zum gemeinsamen Abendessen</td>
            </tr>
          </tbody>
        </table>
        <table class="table table-striped mb-4">
          <thead>
            <tr>
              <th colspan="2" style="color:#951e37;">Freitag, 20. November 2026</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td class="uhr-td">9:00 – 10:30</td>
              <td>Programmblock 3: Dauerhaften Zugang schaffen – religionswissenschaftliche Projekte und Sammlungen im Fokus (Lightning Talks)</td>
            </tr>
            <tr>
              <td class="uhr-td">10:30 – 11:00</td>
              <td>Pause</td>
            </tr>
            <tr>
              <td class="uhr-td">11:00 – 12:30</td>
              <td>Abschlusspanel</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </section>
  <section class="cw-p-3 col-md-12 bl1">
    <div class="container">
      <p class="mt-4 mb-1"><b>Veranstalter:</b></p>
      <p class="mb-1"><a target="_blank" href="https://www.dvrw.uni-hannover.de/">Deutsche Vereinigung für Religionswissenschaft (DVRW)</a></p>
      <p class="mb-1">FID Religionswissenschaft, UB Tübingen</p>
      <p class="mb-1"><a target="_blank" href="https://uni-tuebingen.de/fakultaeten/philosophische-fakultaet/fachbereiche/altertums-und-kunstwissenschaften/institut-fuer-religionswissenschaft/institut/">Institut für Religionswissenschaft, Universität Tübingen</a></p>
    </div>
    <div class="container">
      <p class="mt-4 mb-1"><b>Kontakt:</b></p>
      <p class="mb-1">Mareike Heinritz und Louise Neubronner (FID Religionswissenschaft)</p>
      <p class="mb-1">E-Mail: <a target="_blank" href="mailto:relbib@ub.uni-tuebingen.de">relbib@ub.uni-tuebingen.de</a>, Tel.: +49 7071 29-74030</p>
    </div>
  </section>
</div>

<style>
  .uhr-td {
    width: 180px;
  }
  .iu {
    text-decoration: underline;
  }
</style>
