<?php
  $user = $this->auth()->isLoggedIn();
  $patron = $user ? $this->auth()->getILSPatron() : false;
  $capabilityParams = $patron ? ['patron' => $patron] : [];
  $ilsOnline = ('ils-none' !== $this->ils()->getOfflineMode());
?>
<button class="close-offcanvas btn btn-link" data-toggle="offcanvas"><?=$this->transEsc('navigate_back') ?></button>
<h3><?=$this->transEsc('Your Account')?></h3>
<div class="myresearch-menu account-menu">
  <?php if ($this->userlist()->getMode() !== 'disabled'): ?>
    <a href="<?=$this->url('myresearch-favorites')?>" class="icon-link <?=$this->active == 'favorites' ? ' active' : ''?>">
      <?=$this->icon('user-favorites', 'icon-link__icon') ?>
      <span class="icon-link__label"><?=$this->transEsc('Favorites')?></span>
    </a>
    <?php /* TueFind: Moved this section from bottom next to favorites section. */?>
    <?php if ($this->accountCapabilities()->getSavedSearchSetting() === 'enabled'): ?>
    <a href="<?=$this->url('search-history')?>?require_login"<?=$this->active == 'history' ? ' class="active"' : ''?>>
      <i class="fa fa-fw fa-search" aria-hidden="true"></i> <?=$this->transEsc('history_saved_searches')?>
    </a>
    <?php endif; ?>
    <?php /* TueFind: Subscription functionality */ ?>
    <?php if ($this->accountCapabilities()->getSubscriptionSetting() === 'enabled'): ?>
      <a href="<?=$this->url('myresearch-subscriptions')?>"<?=$this->active == 'subscriptions' ? ' class="active"' : ''?>>
        <i class="fa fa-fw fa-bell"></i> <?=$this->transEsc('Subscriptions')?>
      </a>
    <?php endif; ?>
    <?php /* TueFind: RSS subscription functionality */ ?>
    <?php if ($this->accountCapabilities()->getRssSubscriptionSetting() === 'enabled'): ?>
      <a href="<?=$this->url('myresearch-rssfeedsettings')?>"<?=$this->active == 'rssFeedSettings' ? ' class="active"' : ''?>>
        <i class="fa fa-fw fa-rss" aria-hidden="true"></i> <?=$this->transEsc("My newsfeeds")?>
      </a>
    <?php endif; ?>
    <?php /* TueFind: PDA functionality */ ?>
    <?php if ($this->accountCapabilities()->getPdaSetting() === 'enabled'): ?>
      <a href="<?=$this->url('myresearch-pdasubscriptions')?>"<?=$this->active == 'pdasubscriptions' ? ' class="active"' : ''?>>
        <i class="fa fa-fw fa-book" aria-hidden="true"></i> <?=$this->transEsc('PDA')?>
      </a>
    <?php endif; ?>
    <?php /* TueFind: Publication functionality */ ?>
    <?php if ($this->accountCapabilities()->getPublicationSetting() === 'enabled'): ?>
      <a href="<?=$this->url('myresearch-publications')?>"<?=$this->active == 'publications' ? ' class="active"' : ''?>>
        <i class="fa fa-fw fa-upload" aria-hidden="true"></i> <?=$this->transEsc('My Publications')?>
      </a>
    <?php endif; ?>
  <?php endif; ?>
  <?php if ($ilsOnline && $this->ils()->checkCapability('getMyTransactions', $capabilityParams)): ?>
    <a href="<?=$this->url('myresearch-checkedout')?>" class="checkedout icon-link<?=$this->active == 'checkedout' ? ' active' : ''?>">
      <?=$this->icon('user-checked-out', 'icon-link__icon') ?>
      <span class="icon-link__label"><?=$this->transEsc('Checked Out Items')?></span>
      <span class="checkedout-status status hidden"><?=$this->icon('spinner') ?></span>
    </a>
  <?php endif; ?>
  <?php if ($ilsOnline && $this->ils()->checkFunction('getMyTransactionHistory', $capabilityParams)): ?>
    <a href="<?=$this->url('myresearch-historicloans')?>" class="icon-link<?=$this->active == 'historicloans' ? ' active' : ''?>">
      <?=$this->icon('user-loan-history') ?>
      <span class="icon-link__label"><?=$this->transEsc('Loan History')?></span>
    </a>
  <?php endif; ?>
  <?php if ($ilsOnline && $this->ils()->checkCapability('getMyHolds', $capabilityParams)): ?>
    <a href="<?=$this->url('holds-list')?>" class="icon-link <?=$this->active == 'holds' ? ' active' : ''?>">
      <?=$this->icon('user-holds', 'icon-link__icon') ?>
      <span class="icon-link__label"><?=$this->transEsc('Holds and Recalls')?></span>
      <span class="holds-status status hidden"><?=$this->icon('spinner') ?></span>
    </a>
  <?php endif; ?>
  <?php if ($ilsOnline && $this->ils()->checkFunction('StorageRetrievalRequests', $capabilityParams)): ?>
    <a href="<?=$this->url('myresearch-storageretrievalrequests')?>" class="icon-link <?=$this->active == 'storageRetrievalRequests' ? ' active' : ''?>">
      <?=$this->icon('user-storage-retrievals', 'icon-link__icon') ?>
      <span class="icon-link__label"><?=$this->transEsc('Storage Retrieval Requests')?></span>
      <span class="storageretrievalrequests-status status hidden"><?=$this->icon('spinner') ?></span>
    </a>
  <?php endif; ?>
  <?php if ($ilsOnline && $this->ils()->checkFunction('ILLRequests', $capabilityParams)): ?>
    <a href="<?=$this->url('myresearch-illrequests')?>" class="icon-link <?=$this->active == 'ILLRequests' ? ' active' : ''?>">
      <?=$this->icon('user-ill-requests', 'icon-link__icon') ?>
      <span class="icon-link__label"><?=$this->transEsc('Interlibrary Loan Requests')?></span>
      <span class="illrequests-status status hidden"><?=$this->icon('spinner') ?></span>
    </a>
  <?php endif; ?>
  <?php if ($ilsOnline && $this->ils()->checkCapability('getMyFines', $capabilityParams)): ?>
    <a href="<?=$this->url('myresearch-fines')?>" class="icon-link <?=$this->active == 'fines' ? ' active' : ''?>">
        <?php
            // Use a "fines" icon based on the configured default currency symbol:
        $currencyIcon = 'currency-' . strtolower($this->config()->get('config')->Site->defaultCurrency ?? 'usd');
          ?>
      <?=$this->icon($currencyIcon, 'icon-link__icon') ?>
      <span class="icon-link__label"><?=$this->transEsc('Fines')?></span>
      <span class="fines-status status hidden"><?=$this->icon('spinner') ?></span>
    </a>
  <?php endif; ?>
  <a href="<?=$this->url('myresearch-profile')?>" class="icon-link <?=$this->active == 'profile' ? ' active' : ''?>">
    <?=$this->icon('profile', 'icon-link__icon') ?>
    <span class="icon-link__label"><?=$this->transEsc('Profile')?></span>
  </a>
  <?php if ($ilsOnline && $user && $user->libraryCardsEnabled()): ?>
    <a href="<?=$this->url('librarycards-home')?>" class="icon-link <?=$this->active == 'librarycards' ? ' active' : ''?>">
      <?=$this->icon('barcode', 'icon-link__icon') ?>
      <span class="icon-link__label"><?=$this->transEsc('Library Cards')?></span>
    </a>
  <?php endif; ?>
  <?php if ($this->overdrive()->showMyContentLink()):?>
     <a href="<?=$this->url('overdrive-mycontent')?>" class="icon-link <?=$this->active == 'dgcontent' ? ' active' : ''?>">
      <?=$this->icon('overdrive', 'icon-link__icon') ?>
      <span class="icon-link__label"><?=$this->transEsc('Overdrive Content')?></span>
    </a>
  <?php endif; ?>
  <?php if ($this->accountCapabilities()->getSavedSearchSetting() === 'enabled'): ?>
    <a href="<?=$this->url('search-history')?>" class="icon-link <?=$this->active == 'history' ? ' active' : ''?>">
      <?=$this->icon('search', 'icon-link__icon') ?>
      <span class="icon-link__label"><?=$this->transEsc('Search History')?></span>
    </a>
  <?php endif; ?>
  <?php if ($user): ?>
    <a href="<?=$this->url('myresearch-logout')?>" class="icon-link">
      <?=$this->icon('sign-out', 'icon-link__icon') ?>
      <span class="icon-link__label"><?=$this->transEsc("Log Out")?></span>
    </a>
  <?php endif; ?>
</div>

<?php if ($user && $this->userlist()->getMode() !== 'disabled'): ?>
  <h3><?=$this->transEsc('Your Lists')?></h3>
  <div class="myresearch-menu">
    <?php /* TueFind: Hide duplicate menu entry for "myresearch-favorites" */ ?>
    <!--
    <a href="<?=$this->url('myresearch-favorites')?>"<?=$this->active == 'favorites' ? ' class="active"' : ''?>>
      <i class="fa fa-fw fa-star" aria-hidden="true"></i> <?=$this->transEsc('Your Favorites')?>
    </a>
    -->
    <?php $lists = $user->getLists() ?>
    <?php foreach ($lists as $list): ?>
      <a href="<?=$this->url('userList', ['id' => $list['id']])?>"<?=$this->active == 'list' . $list['id'] ? ' class="active"' : ''?>>
        <?=$this->escapeHtml($list['title'])?>
        <span class="badge"><?=$list->cnt ?></span>
      </a>
    <?php endforeach; ?>
    <a href="<?=$this->url('editList', ['id' => 'NEW'])?>">
      <i class="fa fa-fw fa-plus" aria-hidden="true"></i> <?=$this->transEsc('Create a List') ?>
    </a>
  </div>
<?php endif ?>

<?php /* TueFind: Admin Menu */ ?>
<?php $user = $this->auth()->isLoggedIn(); ?>
<?php if ($user && $user->tuefind_rights != null): ?>
  <h3>Admin</h3>
  <div class="myresearch-menu">
    <a href="<?=$this->url('adminfrontend-showadmins') ?>"<?=$this->active == 'showadmins' ? ' class="active"' : ''?>>
      <i class="fa fa-fw fa-user-secret" aria-hidden="true"></i> Show admins
    </a>
    <?php if ($this->accountCapabilities()->getRequestAuthorityRightsSetting() == 'enabled'): ?>
      <a href="<?=$this->url('adminfrontend-showuserauthorities') ?>"<?=$this->active == 'showuserauthorities' ? ' class="active"' : ''?>>
        <i class="fa fa-fw fa-user-plus" aria-hidden="true"></i> Show user authorities
      </a>
      <a href="<?=$this->url('adminfrontend-showuserauthorityhistory') ?>"<?=$this->active == 'showuserauthorityhistory' ? ' class="active"' : ''?>>
        <i class="fa fa-fw fa-user-plus" aria-hidden="true"></i> Show user authority history
      </a>
    <?php endif; ?>
    <?php if ($this->accountCapabilities()->getPublicationSetting() === 'enabled'): ?>
      <a href="<?=$this->url('adminfrontend-showuserpublications') ?>"<?=$this->active == 'showuserpublications' ? ' class="active"' : ''?>>
        <i class="fa fa-fw fa-user-plus" aria-hidden="true"></i> Show user publications
      </a>
      <a href="<?=$this->url('adminfrontend-showuserpublicationstatistics') ?>"<?=$this->active == 'showuserpublicationstatistics' ? ' class="active"' : ''?>>
        <i class="fa fa-fw fa-user-plus" aria-hidden="true"></i> Show user publication statistics
      </a>
    <?php endif; ?>
  </div>
<?php endif; ?>
