<?php
    $subscribedFeedIds = [];
    foreach ($rssSubscriptions as $rssSubscription) {
        $subscribedFeedIds[] = $rssSubscription->getRssFeed()->getId();
    }

    $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('My newsfeeds') . '</li>';
?>

<div class="mainbody left">
  <h2><?=$this->transEsc('My newsfeeds')?></h2>

  <p><a href="<?=$this->url('myresearch-rssfeedpreview')?>"><?=$this->transEsc('Show personal RSS feed')?></a></p>
  <table style="width: 100%">
    <tr>
      <td><?=$this->transEsc('rss_subscribe_email')?></td>
      <td class="tf-rss-feeds-switcher">
        <label class="switch">
          <input type="checkbox" <?=($this->user->getRssFeedSendEmails())?"checked":"";?>  class="rssLabel" name="action" value="<?=(!$this->user->getRssFeedSendEmails())?"unsubscribe_email":"subscribe_email";?>">
          <span class="slider round"></span>
        </label>
      </td>
    </tr>
  </table>
  <p>
    <div class="rssEmailTimestampBlock <?=(!$this->user->getRssFeedSendEmails())?"tf-d-none":"";?>">
      <?=$this->transEsc('rss_email_min_timestamp')?> <span><?=$this->user->getRssFeedLastNotification()->format($this->config()->dateTimeFormat())?></span>.
    </div>
  </p>

  <table class="search-history-table">
    <tr>
      <th><?=$this->transEsc('RSS feed')?></th>
      <th><?=$this->transEsc('Subscribe')?></th>
    </tr>
    <?php foreach($rssFeeds as $rssFeed): ?>
      <tr>
        <td><a href="<?=$rssFeed->getWebsiteUrl()?>" target="_blank"><?=$this->escapeHtml($rssFeed->getFeedName())?></a></td>
        <td class="tf-rss-feeds-switcher">
          <label class="switch">
            <?php if (in_array($rssFeed->getId(), $subscribedFeedIds)): ?>
              <input type="checkbox" checked class="rssLabel" data-id="<?=$rssFeed->getId()?>">
            <?php else: ?>
              <input type="checkbox" class="rssLabel" data-id="<?=$rssFeed->getId()?>">
            <?php endif; ?>
            <span class="slider round"></span>
          </label>
        </td>
      </tr>
    <?php endforeach; ?>
  </table>
</div>

<div class="<?=$this->layoutClass('sidebar')?>" id="myresearch-sidebar" role="navigation" aria-label="<?=$this->transEsc('account_menu_label')?>">
  <?=$this->accountMenu()->render('RssFeedSettings')?>
</div>
