<?php
$routeParams = $this->tuefind()->getRouteParams();
$authorityId = $routeParams['authority_id'];
$userAccess = $this->tuefind()->getUserAccessState($authorityId, $this->userId ?? null);
$userAlreadyMadeAuthorityRequest = $this->tuefind()->userAlreadyMadeAuthorityRequest($this->userId);?>

<h1>Request access</h1>
<?php if ($userAccess['availability'] == 'free'): ?>
  <?php if($userAlreadyMadeAuthorityRequest): ?>
    You have already made a rights request for another author
  <?php else: ?>
    <p>Would you like to request access to this authority dataset?</p>
    <form method="post" data-lightbox-onclose="VuFind.refreshPage">
      <input type="hidden" name="request" value="yes">
      <button class="btn btn-primary" type="submit">Request access</button>
    </form>
  <?php endif;?>
<?php elseif ($userAccess['availability'] == 'mine'): ?>
  <?php if ($userAccess['access_state'] == 'requested'): ?>
    <p>You have requested permission on this authority record. Our team has been informed, please wait for the approval.</p>
  <?php elseif ($userAccess['access_state'] == 'granted'): ?>
    <p>You have already been granted permission on this authority record.</p>
  <?php endif; ?>
<?php elseif ($userAccess['availability'] == 'other'): ?>
  <p>This record is already owned by someone else.</p>
<?php endif; ?>
