<?php
  // Set page title.
  $this->headTitle($this->translate('Search Home'));

  // IxTheo: Searchbox will always be shown, so do not override it (Part 1)
  // $this->layout()->searchbox = false;

  // Set default value if necessary:
  if (!isset($this->searchClassId)) {
    $config = $this->config()->get('config');
    $this->searchClassId = $config->Site->defaultSearchBackend ?? 'Solr';
  }

  $this->layout()->breadcrumbs = false;
?>

<!-- IxTheo: Searchbox will always be shown, so do not override it (Part 2) -->

<?=implode('', array_map([$this, 'contentBlock'], $blocks ?? []))?>
