<div class="cw-row">
  <div class="cw-col-lg-12">
    <div class="cw-text-block"><br>
      <h1 class="cw-h1">Digitalisierung (DigiTheo)</h1>
      <p>Im Rahmen verschiedener DFG-Projekte werden vom FID Theologie regelmäßig umfangreiche Digitalisierungsprojekte durchgeführt.</p>
      <p>Hierbei werden Zeitschriften und Bücher früherer Jahrhunderte ebenso wie aktuelle Publikationen professionell digitalisiert und die
          Digitalisate mit eigenen Einträgen im Index Theologicus (IxTheo) verknüpft.
          So können die Werke und die darin enthaltenen Aufsätze im IxTheo recherchiert und mit einem
          Klick digital eingesehen oder heruntergeladen werden. Vielfach kann außerdem der Volltext der Publikationen durchsucht werden.</p>
      <p>Bislang wurden in fünf „DigiTheo“-Projekten zahlreiche wichtige theologische Publikationen online gestellt:</p>
    </div>
  </div>
</div>

<style type="text/css">
.digiTabs .nav-tabs>li>a {
  font-size: 11px;
}
.digiTabs .tab-content {
  padding: 10px;
}
.digiTabs .nav-tabs>li>a {
  font-size: 16px;
}
</style>