<div class="panel panel-top panel-default tf-panel-home-3">
    <div class="panel-image" style="background-image: url(<?=$this->imageLink('frontpage/business-idea-diagram-innovation-40218.jpg') ?>);"></div>
    <div class="panel-content">
        <h4>FID Services</h4>
        <p>
            <ul>
                <li><a href="<?=$this->url('content-page', ['page' => 'self_archiving_service']) ?>">RelBib Self-Archiving (Green Open Access)</a></li>
                <li><a href="<?=$this->url('content-page', ['page' => 'ojs']) ?>">RelBib Open Journals (Gold Open Access)</a></li>
                <li><a href="<?=$this->url('content-page', ['page' => 'research_data_management']) ?>">Forschungsdatenmanagement</a></li>
                <li><a href="<?=$this->url('content-page', ['page' => 'cooperations_institutions']) ?>">Kooperationen</a></li>
                <li><a href="<?=$this->url('content-page', ['page' => 'licenses']) ?>">FID Lizenzen</a></li>
                <li><a href="/Feedback/Form/DoD">Digitalisierung on Demand (DoD)</a></li>
            </ul>
        </p>
    </div>
</div>
