<?php
$this->breadcrumbs()->set($this->translate('Admins'), $this->url('myresearch-home'))
      ->add($this->translate('CMS Pages Docs'), active: true);
?>

<div class="<?=$this->layoutClass('mainbody')?>">
  <div class="ajax-loader-container ajax-info d-none">
    <div class="alert alert-success" role="alert">
      <?=$this->translate('od_code_contentnotavail')?>
    </div>
  </div>
  <h1><?=$this->transEsc('CMS Images')?></h1>
  <?=$this->flashmessages()?>

  <div class="container-md">

    <div class="row col-md-12">
       <div class="input-group mb-3">
        <input type="file" class="form-control form-control-lg fileUploadInput" placeholder="Add Image" aria-label="Add Image" aria-describedby="button-addon2">
        <button class="btn btn-outline-primary uploadBtn" type="button" id="button-addon2"><?=$this->icon('upload')?></button>
      </div>
    </div>

    <div class="row col-md-12 gy-3 mt-3 ajax-content-images-container">
        <!-- AJAX content will be loaded here -->
    </div>
  </div>
</div>

<div class="<?=$this->layoutClass('sidebar')?>" id="myresearch-sidebar" role="navigation" aria-label="<?=$this->transEsc('account_menu_label')?>">
  <?=$this->accountMenu()->render('cmspagesdocs')?>
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" style="min-width: 1200px;">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title preview_title" id="exampleModalLabel"></h5>
      </div>
      <div class="modal-body">
        <div class="container " id="container">
          <div class="cw-row">
            <div class="col-12">
              <div class="">
                <div class="preview_body text-center"></div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="confirmDeleteModal" tabindex="-1" aria-labelledby="confirmDeleteLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      
      <div class="modal-header">
        <h5 class="modal-title" id="confirmDeleteLabel">Confirm deletion</h5>
        <i class="fas fa-times btn-close" type="button" data-bs-dismiss="modal"></i>
      </div>

      <div class="modal-body">
        Are you sure you want to delete <span class="sureDeleteName text-danger"></span>?
      </div>
      <div class="file-path d-none"></div>
      <div class="ajax-response d-none"></div>

      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
          Cancel
        </button>
        <button type="button" class="btn btn-danger" id="confirmDeleteBtn">
          Delete
        </button>
      </div>

    </div>
  </div>
</div>


<style>
  .smc-card img {
    max-height: 145px;
    object-fit: contain;
  }
  .preview_body img {
    max-height: 500px;
    object-fit: contain;
  }
</style>

<?php
  $script = <<<JS

    TueFind.getCMSImages();

    $('.uploadBtn').on('click', function () {
        let fileInput = $('.fileUploadInput')[0];
        if (!fileInput.files.length) {
            alert('Select file');
            return;
        }
        let formData = new FormData();
        formData.append('file', fileInput.files[0]);
        $.ajax({
            url: '/AJAX/JSON?method=CmsDocs&action=uploadImage', // VuFind endpoint
            method: 'POST', // Use GET as per the original code, but consider changing to POST for file uploads
            data: formData,
            body: formData,
            processData: false,
            contentType: false,
            success: function (response) {
                if (response.data.status === 'success') {
                    $('.ajax-info').removeClass('d-none').find('.alert').text(response.data.message);
                    setTimeout(() => {
                        $('.ajax-info').addClass('d-none');
                    }, 2000);
                    $('.fileUploadInput').val(''); // Clear the file input
                    TueFind.getCMSImages(); // Reload the table to show the new file
                } else {
                    alert(response.data.message);
                }
            },
            error: function(xhr, ajaxOptions, thrownError) {
                if (window.console && window.console.log) {
                console.log("Status: " + xhr.status + ", Error: " + thrownError);
                }
            }
        });
    });

    $(document).on('click', '.cms_preview', function(thisEvent) {
        let image =  $(thisEvent.currentTarget).parent().prev().find('img');
        let imageName = image.attr('alt');
        $('#exampleModal .preview_title').html(imageName);
        $('#exampleModal .preview_body').html(image.clone());
    });


    let currentItemName = '';
    
    $(document).on('click', '.delete-btn', function(thisEvent) {
        let cartParent = $(this).closest('.smc-card');
        cartParent.addClass('pre-delete');
        let currentItemName = cartParent.find('.card-header').text();
        $('#confirmDeleteModal .sureDeleteName').text(currentItemName);
        $('#confirmDeleteModal .file-path').html($(this).attr('href'));
    });    

    $('#confirmDeleteBtn').click(function() {
      let THIS = $(this);
      let parentModal = THIS.parents('.modal-content');
      let filePATH = parentModal.find('.file-path').html();

      //for now we just close the modal, but here we would send an AJAX request to delete the image and then refresh the page or remove the card from the DOM
      $.ajax({
        url: VuFind.path + '/AJAX/JSON',
        method: 'GET',
        data: {
          method: 'CmsDocs',
          action: 'deleteImage',
          failPATH: filePATH
        },
        dataType: 'json',
        success: function displaySubscriptionItems(items) {
  
          $('#confirmDeleteModal').modal('hide');

          $('.ajax-info').removeClass('d-none').find('.alert').text(items.data.data);
            setTimeout(() => {
                $('.ajax-info').addClass('d-none');
          }, 2000);

          TueFind.getCMSImages();
    
        },
        error: function(xhr, ajaxOptions, thrownError) {
          if (window.console && window.console.log) {
            console.log("Status: " + xhr.status + ", Error: " + thrownError);
          }
        }
      });
    });

  JS;
?>
<?=$this->assetManager()->outputInlineScriptString($script); ?>

