<?php
$this->breadcrumbs()->set($this->translate('Admins'), $this->url('myresearch-home'))
      ->add($this->translate('CMS Pages Docs'), active: true);
?>

<div class="<?=$this->layoutClass('mainbody')?>">
  <h1 class="text-center"><?=$this->transEsc('All CMS Docs')?></h1>
  <?=$this->flashmessages()?>

  <div class="container-md">
    <div class="row gy-3 mt-4 AJAXCMSDocsBlock" style="min-height: 150px;"></div>
  </div>
</div>

<div class="<?=$this->layoutClass('sidebar')?>" id="myresearch-sidebar" role="navigation" aria-label="<?=$this->transEsc('account_menu_label')?>">
  <?=$this->accountMenu()->render('cmspagesdocs')?>
</div>

<?php $this->assetManager()->appendScriptLink('cms.js'); ?>
<?=$this->assetManager()->outputInlineScriptString('CMS.GetAJAXDocs(\'AJAXCMSDocsBlock\');') ?>
