<?php
// Set up page title:
$this->headTitle($this->translate('User Publication Statistics'));

// Set up breadcrumbs:
$this->layout()->breadcrumbs = '<li><a href="' .  $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('User Publication Statistics') . '</li>';
?>

<div class="<?=$this->layoutClass('mainbody')?>">
  <h2><?=$this->transEsc('Publication Statistics')?></h2>
  <?php if (count($this->publications) == 0): ?>
    <p>No publications have been added so far.</p>
  <?php else: ?>
    <table class="table dataTable display compact table-striped table-bordered table-condensed">
      <thead>
        <tr>
            <th><?=$this->transEsc('Year')?></th>
            <th><?=$this->transEsc('title_count')?></th>
        </tr>
      </thead>
      <tbody>
        <?php foreach ($this->publications as $one): ?>
          <tr>
            <td><?=$one['year']?></td>
            <td><?=$one['count']?></td>
          </tr>
        <?php endforeach; ?>
      </tbody>
    </table>
  <?php  endif; ?>
</div>

<div class="<?=$this->layoutClass('sidebar')?>" id="myresearch-sidebar" role="navigation" aria-label="<?=$this->transEsc('account_menu_label')?>">
  <?=$this->accountMenu()->render('showuserpublicationstatistics')?>
</div>
