<?php
// Set up page title:
$this->headTitle($this->translate('Authority Access History'));

// Set up breadcrumbs:
$this->layout()->breadcrumbs = '<li><a href="' .  $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('Authority Access History') . '</li>';
?>

<div class="<?=$this->layoutClass('mainbody')?>">
  <h2>Authority Access History</h2>
  <?php if (count($this->user_authority_history_datas) == 0): ?>
    <p>No history.</p>
  <?php else: ?>
    <table class="table dataTable display compact table-striped table-bordered table-condensed" data-order="[[ 4, &quot;desc&quot; ]]">
      <thead>
        <tr>
          <th><?=$this->transEsc('Admin Name')?></th>
          <th><?=$this->transEsc('Request User')?></th>
          <th><?=$this->transEsc('Authority')?></th>
          <th><?=$this->transEsc('Access')?></th>
          <th><?=$this->transEsc('Request User Date')?></th>
          <th><?=$this->transEsc('Admin request Date')?></th>
        </tr>
      </thead>
      <tbody>
        <?php foreach ($this->user_authority_history_datas as $data): ?>
          <tr>
            <td><?=$data->admin_username." (".$data->admin_firstname." ".$data->admin_lastname.")"?></td>
            <td><?=$data->request_user_firstname." ".$data->request_user_lastname?></td>
            <td><a href="/AuthorityRecord/<?=$data->authority_id?>"><?=$data->authority_id?></a></td>
            <td><?=$data->access_state?></td>
            <td data-sort="<?=date("Y-m-d H:i:s",strtotime($data->request_user_date));?>"><?=date("d.m.Y H:i:s", strtotime($data->request_user_date));?></td>
            <td data-sort="<?=date("Y-m-d H:i:s",strtotime($data->process_admin_date));?>"><?=date("d.m.Y H:i:s", strtotime($data->process_admin_date));?></td>
        <?php endforeach; ?>
      </tbody>
    </table>
  <?php endif; ?>
</div>

<div class="<?=$this->layoutClass('sidebar')?>" id="myresearch-sidebar" role="navigation" aria-label="<?=$this->transEsc('account_menu_label')?>">
  <?=$this->accountMenu()->render('showuserauthorityhistory')?>
</div>
