<?php
// Set up page title:
$this->headTitle($this->translate('Admins'));

// Set up breadcrumbs:
$this->layout()->breadcrumbs = '<li><a href="' .  $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('Admins') . '</li>';
?>

<div class="<?=$this->layoutClass('mainbody')?>">
  <h2>Admins</h2>
  <p>Additional admins must be unlocked manually in the database by the development team.</p>
  <hr />
  <table class="table dataTable display compact table-striped table-bordered table-condensed">
    <thead>
      <tr>
        <th><?=$this->transEsc('Username')?></th>
        <th><?=$this->transEsc('First Name')?></th>
        <th><?=$this->transEsc('Last Name')?></th>
        <th><?=$this->transEsc('Email Address')?></th>
        <th><?=$this->transEsc('Institution')?></th>
        <th><?=$this->transEsc('Rights')?></th>
      </tr>
    </thead>
    <tbody>
      <?php foreach ($this->admins as $user): ?>
        <tr>
          <td><?=$this->escapeHtml($user->getUsername())?></td>
          <td><?=$this->escapeHtml($user->getFirstname())?></td>
          <td><?=$this->escapeHtml($user->getLastname())?></td>
          <td><?=$this->escapeHtml($user->getEmail())?></td>
          <td><?=$this->escapeHtml($user->getInstitution())?></td>
          <td><?=implode('<br>', $user->getTueFindRights())?></td>
        </tr>
      <?php endforeach; ?>
    </tbody>
  </table>
</div>

<div class="<?=$this->layoutClass('sidebar')?>" id="myresearch-sidebar" role="navigation" aria-label="<?=$this->transEsc('account_menu_label')?>">
  <?=$this->accountMenu()->render('showadmins')?>
</div>
