<div class="container" id="footer-bottom">
    <div class="row row-eq-height">
        <div class="col-xs-12 col-md-3 copyright">
            <?=$this->content()->renderTranslated('snippets/copyright'); ?>
        </div>
        <div class="col-xs-12 col-md-3 ">
            <?=$this->content()->renderTranslated('snippets/supporters'); ?>
        </div>
        <div class="col-xs-12 col-md-6 footer-menu">
            <ul class="footer-menu">
                <li><a href="<?=$this->url('content-page', ['page' => 'contact'])?>"><?=$this->translate('Contact');?></a></li>
                <li><a href="<?=$this->url('content-page', ['page' => 'Impressum'])?>"><?=$this->translate('Imprint');?></a></li>
                <li><a target="_blank" href="<?=$this->url('content-page', ['page' => 'privacy'])?>"><?=$this->translate('Privacy Protection');?></a></li>
                <li><a target="_blank" href="https://bsky.app/profile/krimdok.bsky.social"><img src="<?=$this->imageLink('bluesky.svg')?>" height="30" alt="Bluesky"></a></li>
                <li><a target="_blank" href="https://mastodon.social/@KrimDok"><img src="<?=$this->imageLink('mastodon.svg')?>" height="30" alt="Mastodon"></a></li>
            </ul>
        </div>
    </div>
</div>
