<section class="cw-position-relative cw-dark-overlay ix-networking-block">
    <a href="<?=$this->url('content-page', ['page' => 'networking']) ?>">
        <?php /* <img src="<?=$this->imageLink('cw/photo-1497436072909-60f360e1d4b1.jpg')?>" alt="" class="cw-bg-image"> */ ?>
        <img src="<?=$this->imageLink('searchbar.jpg')?>" alt="" class="cw-bg-image">
        <div class="container">
            <div class="cw-overlay-content cw-text-white cw-py-lg-5">
                <h3 class="cw-display-3 cw-font-weight-bold cw-text-serif cw-text-shadow cw-mb-5 ixtheo2-networking-link">Networking</h3>
            </div>
        </div>
    </a>
</section>