<h1>Cooperation Partners</h1>

<table border="1" class="cl-table-partners">
    <tr>
        <td class="cl-td-img"><img src="<?=$this->imageLink('partners/KU.png')?>" alt="Katholische Universität Eichstätt-Ingolstadt"></td>
        <td class="cl-td-text" colspan="2">
            <h3>Chair of Canon Law and Ecclesiastical Legal History at the Catholic University of Eichstätt-Ingolstadt:</h3>
            <p>The Chair of Canon Law and Ecclesiastical Legal History at the Catholic University of Eichstätt-
                Ingolstadt is a long-standing cooperation partner. Under the leadership of the chair holder, the team
                is dedicated to the collection and evaluation of the ecclesiastical official gazettes of the
                (Arch)Dioceses of Bamberg, Eichstätt, Speyer, and Würzburg. Additionally, the Chair of Canon Law
                and Ecclesiastical Legal History meticulously analyzes and systematically records important academic
                journals such as "Kirche und Recht" (Church and Law), "Zeitschrift der Savigny-Stiftung für
                Rechtsgeschichte: Kanonistische Abteilung" (Journal of the Savigny Foundation for Legal History:
                Canon Law Section), "Zeitschrift für Evangelisches Kirchenrecht" (Journal of Protestant Church Law),
                and "Kanonika." These journals serve as significant sources for current research and developments in
                the field of canon law.
            </p>
        </td>
    </tr>
    <tr>
        <td class="cl-td-text" colspan="2">
            <h3>Chair of Canon Law and Ecclesiastical Legal History at the University of Freiburg:</h3>
            <p>Within the project, the Chair of Canon Law and Ecclesiastical Legal History at the University of
                Freiburg takes care of the formal and content indexing of various legal texts as well as canonical
                literature. The legal texts include the Official Gazette of the Archdiocese of Freiburg as well as the
                Communicationes, which are published by the Dicastery for Legal Texts at the Vatican. The specialist
                literature includes De Processibus Matrimonialibus, Revista espanola de derecho canónico, Revue de
                droit canonique and The Jurist, an international and multilingual selection of canonical topics.</p>
        </td>
        <td class="cl-td-img"><img src="<?=$this->imageLink('partners/UFR.png')?>" alt="Universität Freiburg" width="300"></td>
    </tr>
    <tr>
        <td class="cl-td-img"><img src="<?=$this->imageLink('partners/limburg.jpg')?>" alt="Bistum Limburg"></td>
        <td class="cl-td-text" colspan="2">
            <h3>Diocesan Curia of Limburg:</h3>
            <p>The official gazettes of the dioceses of Fulda, Limburg and Trier as well as the official gazette of the
            Austrian Bishops' Conference are evaluated by the Diocesan Curia of Limburg for the Index
            Canonicus.</p>
        </td>
    </tr>
    <tr>
        <td class="cl-td-text" colspan="2">
            <h3>Seminar for Canon Law, Canon Law History and State-Church Law of the Johannes Gutenberg University Mainz:</h3>
            <p>The Seminar for Canon Law, Canon Law History and State-Church Law of the Johannes Gutenberg
                University Mainz has been a cooperation partner of the IKR-Münster in the processing of the canon
                law database since 2009. In addition to the official gazette of the diocese of Mainz, the chair's team
                searches and enters articles relevant to ecclesiastical and constitutional law from scholarly and
                jurisprudential journals, the Osservatore Romano (German weekly edition), the canonical journals Jus
                Missionale (Urbaniana Rome), NomoK@non (Munich), as well as the series Kirchen- und
                Religionsrecht / formerly Kirchen- und Staatskirchenrecht and Mainzer Beiträge zu Kirchen- und
                Religionsrecht.</p>
        </td>
        <td class="cl-td-img"><img src="<?=$this->imageLink('partners/JGU.png')?>" alt="Johannes Gutenberg Universität Mainz"></td>
    </tr>
    <tr>
        <td class="cl-td-img"><img src="<?=$this->imageLink('partners/IKR.jpg')?>" alt="IKR"></td>
        <td class="cl-td-text" colspan="2">
            <h3>Institute for Canon Law at the Westfälische Wilhelms University of Münster:</h3>
            <p>The "IKR" is responsible for networking and overall organisation among the equal cooperators. This is
                where the information is collected and forwarded, and the IKR can always be contacted in the event
                of problems with the recording and indexing of the various titles. The IKR also ensures that the
                individual essays and sometimes the associated keywords are transferred to the database. In
                addition, the IKR makes sure that any errors are corrected. The IKR also records journals and series
                itself. These include, for example, the Official Gazette of the Diocese of Münster, the series "Essener
                Gespräche zum Thema Staat und Kirche", the supplements to the Münsterischer Kommentar on the
                CIC, but also somewhat more internationally, for example, the newsletter of the Canon Law Society
                of Great Britain and Ireland.</p>
        </td>
    </tr>
    <tr>
        <td class="cl-td-text" colspan="2">
            <h3>Department of Canon Law at the Faculty of Catholic Theology at the University of Tübingen:</h3>
            <p>The Department of Canon Law at the Faculty of Catholic Theology at the University of
                Tübingen joined the cooperation project in 2014. We index the Official Gazette of the Diocese
                of Rottenburg-Stuttgart, the Italian journal "Daimon" as well as the "Tübinger
                Kirchenrechtlichen Studien", including the "Kleine Wissenschaftliche Reihe".</p></td>
        <td class="cl-td-img"><img src="<?=$this->imageLink('partners/tübingen.png')?>" alt="Eberhard Karls Universität Tübingen"></td>
    </tr>
</table>
