<h1>Kooperationspartner</h1>
<table border="1" class="cl-table-partners">
    <tr>
        <td class="cl-td-img"><img src="<?=$this->imageLink('partners/KU.png')?>" alt="Katholische Universität Eichstätt-Ingolstadt"></td>
        <td class="cl-td-text" colspan="2">
            <h3>Lehrstuhl für Kirchenrecht und kirchliche Rechtsgeschichte an der Katholischen Universität Eichstätt-Ingolstadt</h3>
            <p>Der Lehrstuhl für Kirchenrecht und kirchliche Rechtsgeschichte an der Katholischen Universität
                Eichstätt-Ingolstadt ist ein langjähriger Kooperationspartner. Unter der Leitung des Lehrstuhlinhabers
                widmet sich das Team der Erfassung und Auswertung der Kirchlichen Amtsblätter der (Erz-)Diözesen
                Bamberg, Eichstätt, Speyer und Würzburg. Darüber hinaus werden vom Lehrstuhl für Kirchenrecht
                und kirchliche Rechtsgeschichte wichtige Fachzeitschriften wie „Kirche und Recht“, „Zeitschrift der
                Savigny-Stiftung für Rechtsgeschichte: Kanonistische Abteilung“, „Zeitschrift für Evangelisches
                Kirchenrecht“ und „Kanonika“ sorgfältig ausgewertet und für IxTheo strukturiert erfasst. Diese
                Zeitschriften bilden eine bedeutende Quelle für aktuelle Forschung und Entwicklungen im Bereich
                des Kirchenrechts.
            </p>
        </td>
    </tr>
    <tr>
        <td class="cl-td-text" colspan="2">
            <h3>Lehrstuhl für Kirchenrecht und Kirchliche Rechtsgeschichte an der Albert-Ludwigs-Universität
            Freiburg:</h3>
            <p>Der Lehrstuhl Kirchenrecht und Kirchliche Rechtsgeschichte der Universität Freiburg kümmert sich
            innerhalb des Projekts um die formale und inhaltliche Erschließung verschiedener Rechtstexte sowie
            kanonistischer Fachliteratur. Zu den Rechtstexten zählen das Amtsblatt der Erzdiözese Freiburg sowie
            die Communicationes, die vom Dikasterium für die Gesetzestexte im Vatikan herausgegeben werden.
            Die Fachliteratur umfasst mit De Processibus Matrimonialibus, Revista espanola de derecho
            canónico, Revue de droit canonique sowie The Jurist eine internationale und multilinguale Auswahl
            kanonistischer Themen.</p>
        </td>
        <td class="cl-td-img"><img src="<?=$this->imageLink('partners/UFR.png')?>" alt="Universität Freiburg" width="300"></td>
    </tr>
    <tr>
        <td class="cl-td-img"><img src="<?=$this->imageLink('partners/limburg.jpg')?>" alt="Bistum Limburg"></td>
        <td class="cl-td-text" colspan="2">
            <h3>Bischöfliches Ordinariat Limburg:</h3>
            <p>Durch das Bischöfliche Ordinariat Limburg werden die Amtsblätter der Diözesen Fulda, Limburg und
            Trier sowie das Amtsblatt der Österreichischen Bischofskonferenz für den Index Canonicus
            ausgewertet.</p>
        </td>
    </tr>
    <tr>
        <td class="cl-td-text" colspan="2">
            <h3>Seminar für Kirchenrecht, kirchliche Rechtsgeschichte und Staatskirchenrecht der JohannesGutenberg-Universität Mainz:</h3>
            <p>Das Seminar für Kirchenrecht, kirchliche Rechtsgeschichte und Staatskirchenrecht der Johannes
            Gutenberg-Universität Mainz ist seit 2009 Kooperationspartner des IKR-Münster bei der Bearbeitung
            der kirchenrechtlichen Datenbank. Neben dem Amtsblatt des Bistums Mainz werden vom
            Lehrstuhlteam insbesondere die kirchen- und staatskirchenrechtlich relevanten Beiträge aus
            Wissenschaft und Rechtsprechung juristischer Fachzeitschriften, der Osservatore Romano (dt.
            Wochenausgabe), die kanonistischen Zeitschriften Jus Missionale (Urbaniana Rom), NomoK@non
            (München), sowie die Reihenwerke Kirchen- und Religionsrecht / vormals Kirchen- und
            Staatskirchenrecht und Mainzer Beiträge zu Kirchen- und Religionsrecht sondiert und eingepflegt.</p>
        </td>
        <td class="cl-td-img"><img src="<?=$this->imageLink('partners/JGU.png')?>" alt="Johannes Gutenberg Universität Mainz"></td>
    </tr>
    <tr>
        <td class="cl-td-img"><img src="<?=$this->imageLink('partners/IKR.jpg')?>" alt="IKR"></td>
        <td class="cl-td-text" colspan="2">
            <h3>Institut für Kanonisches Recht der Westfälischen Wilhelms-Universität Münster:</h3>
            <p>Das „IKR“ ist unter den gleichberechtigten Kooperierenden für die Vernetzung und
            Gesamtorganisation zuständig. Hier werden die Informationen gesammelt und weitergeleitet und
            das IKR ist auch bei Problemen bei der Aufnahme und Verschlagwortung der diversen Titel immer
            ansprechbar. Das IKR sorgt auch dafür, dass die einzelnen Aufsätze und manchmal auch die
            zugehörigen Schlagworte in die Datenbank übertragen werden. Zudem kümmert sich das IKR darum,
            dass ggf. Fehler beseitigt werden. Das IKR nimmt auch selber Zeitschrift und Reihen auf. Dazu zählt
            beispielsweise das Amtsblatt der Diözese Münster, die Reihe „Essener Gespräche zum Thema Staat
            und Kirche“, die Beihefte zum Münsterischen Kommentar zum CIC, aber auch etwas internationaler
            beispielsweise der Newsletter der Canon Law Society of Great Britain and Ireland.</p>
        </td>
    </tr>
    <tr>
        <td class="cl-td-text" colspan="2">
            <h3>Abteilung für Kirchenrecht an der Katholisch-Theologischen Fakultät der Universität Tübingen:</h3>
            <p>Die Abteilung für Kirchenrecht an der Katholisch-Theologischen Fakultät der Universität
            Tübingen ist seit 2014 am Kooperationsprojekt beteiligt. Wir erfassen und verschlagworten
            das Amtsblatt der Diözese Rottenburg-Stuttgart, die italienische Zeitschrift „Daimon“ sowie
            die „Tübinger Kirchenrechtlichen Studien“, inklusive der „Kleinen Wissenschaftlichen Reihe“.</p></td>
        <td class="cl-td-img"><img src="<?=$this->imageLink('partners/tübingen.png')?>" alt="Eberhard Karls Universität Tübingen"></td>
    </tr>
</table>
