<?php $this->headTitle($this->translate('Impressum'));?>
<h1>Ansprechpartner</h1>
<h2>Institut für Kanonisches Recht (DaKaR)</h2>
<p>
    Katholisch-Theologische Fakultät Münster<br>
    Universität Münster (Deutschland)
</p>
<p>
    Julia Klesel (<a href="mailto:julia.klesel@uni-muenster.de">julia.klesel@uni-muenster.de</a>)
</p>

<h2>Kirchenrecht</h2>
<p>
    Institut für Praktische Theologie<br>
    Katholisch-Theologische Fakultät Innsbruck (Österreich)
</p>
<p>
    Ass.-Prof. Dr. Konrad Breitsching (<a href="mailto:Konrad.Breitsching@uibk.ac.at">Konrad.Breitsching@uibk.ac.at</a>)
</p>

<h2>Fachinformationsdienst (FID) Theologie</h2>
<p>Universitätsbibliothek Tübingen (Deutschland)</p>
<p>Dr. Martin Faßnacht (<a href="mailto:martin.fassnacht@uni-tuebingen.de">martin.fassnacht@uni-tuebingen.de</a>)</p>

<br><br>

<h1>Impressum</h1>
<p>Allgemeine Informationen gem. § 5 TMG, § 55 RStVG</p>
<table class="table table-striped">
    <tr>
        <td>Dienstanbieter</td>
        <td>Universitätsbibliothek der Eberhard Karls Universität Tübingen</td>
    </tr>
    <tr>
        <td>Anschrift</td>
        <td>Universitätsbibliothek<br/>
            Wilhelmstraße 32<br/>
            72074 Tübingen</td>
    </tr>
    <tr>
        <td>Kontakt</td>
        <td>IxTheo-Team der UB Tübingen<br/>
            ixtheo@ub.uni-tuebingen.de<br/>
            +49 (0)7071 2974029</td>
    </tr>
    <tr>
        <td>Rechtsform</td>
        <td>Die Universität Tübingen ist eine Körperschaft des öffentlichen Rechts. Sie wird durch die Rektorin Prof. Dr. Karla Pollmann (E-Mail: rektorin@uni-tuebingen.de) gesetzlich vertreten.</td>
    </tr>
    <tr>
        <td>Umsatzsteuer-Identifikationsnummer</td>
        <td>gemäß § 27a Umsatzsteuergesetz:<br>DE812383453</td>
    </tr>
    <tr>
        <td>Aufsichtsbehörde</td>
        <td>Ministerium für Wissenschaft, Forschung und Kunst Baden Württemberg</td>
    </tr>
    <tr>
        <td>Haftungshinweis</td>
        <td>Trotz sorgfältiger inhaltlicher Kontrolle übernehmen wir keine Haftung für die Inhalte externer Links. Für den Inhalt der verlinkten Seiten sind ausschließlich deren Betreiber verantwortlich.</td>
    </tr>
    <tr>
        <td>Inhaltlich Verantwortliche für das Informationsangebot des Index Canonicus gemäß §18 Abs. 2 MStV</td>
        <td>Regine Tobias (Direktorin der Universitätsbibliothek Tübingen)</td>
    </tr>
</table>
