<?php $subsystem = $this->tuefind()->getTueFindSubsystem()?>
<?php echo "system_type=", $subsystem == 'relbib' ? 'relbib' : 'ixtheo', "\n" ?>
<?php foreach ($this->fields as $data): ?>
<?php if($data['name'] != 'name' && $data['name'] != 'email' && $data['name'] != 'comment'): ?>
<?php $name_ = ($data['name'] ?? '') ?>
<?php if ($data['type'] === 'textarea'): ?>
<?=$name_ ? "$name_=" : ''?>

<?=$data['value']?>

<?php elseif (in_array($data['type'], ['checkbox', 'radio', 'select'])): ?>
<?=($name_ ? "$name_=" : '') . implode(', ', array_map([$this, 'translate'], (array)$data['value'])) . PHP_EOL ?>
<?php else: ?>
<?=($name_ ? "$name_=" : '') . $data['value'] . PHP_EOL ?>
<?php endif ?>
<?php endif ?>
<?php endforeach ?>
