<?php
$tuefind = $this->tuefind();
$currentSystem = $tuefind->getTueFindType();
$publicationEmail = $tuefind->getPublicationEmail();
?>

<h2>Publication FAQ</h2>

<h3>Rechtliche & allgemeine Fragen</h3>
<p>Die folgenden Angaben wurden sorgfältig geprüft, stellen aber keine verbindliche Rechtsberatung dar. Für mögliche Fehler kann keine Haftung übernommen werden.</p>

<p><b>Was kann ich zweitveröffentlichen?</b></p>
<ul>
    <li>Die Rechtslage in Bezug auf Zweitveröffentlichungen ist leider nicht eindeutig. Es können abhängig vom Sitz des Verlags unterschiedliche nationale Gesetze gelten. Viele Verlage haben außerdem auf ihren jeweiligen Webseiten Policies veröffentlicht, in denen Regeln für die Zweitveröffentlichung festgelegt werden. Sie können diese Policies oft unter den Begriffen “Self-Archiving” oder “Open Access” finden. Bitte prüfen Sie die jeweilige Rechtslage und erfragen Sie im Zweifel beim jeweiligen Verlag die Erlaubnis zur Zweitveröffentlichung.</li>
    <li>Für Publikationen, die bei Verlagen mit Sitz in Deutschland erschienen sind, gilt §38 Urheberrechtsgesetz <a href="https://www.gesetze-im-internet.de/urhg/__38.html">[https://www.gesetze-im-internet.de/urhg/__38.html]</a>. Die Zweitveröffentlichung von Aufsätzen aus Zeitschriften, Sammelbänden und Lexika ist grundsätzlich möglich, aber unter Umständen abhängig von den individuell mit dem Verlag getroffenen Vereinbarungen. Monografien können nicht zweitveröffentlicht werden, sofern nicht individuelle Vereinbarungen mit dem Verlag (z. B. bei vergriffenen Dissertationsschriften) getroffen wurden.</li>
</ul>

<p><b>Welche Rolle spielen Verlagsverträge & Verlagspolicies?</b></p>
<ul>
    <li>Bei der Erstveröffentlichung haben Sie häufig einen Vertrag mit dem veröffentlichenden Verlag abgeschlossen, in dem die Nutzungsrechte an Ihrer Publikation geregelt sind. Diese sind für Ihre Rechte zur Zweitveröffentlichung maßgeblich, sofern die rechtlichen Vorgaben dem nicht widersprechen. </li>
    <li>Zur Vereinfachung haben viele Verlage auch Policies auf ihren Webseiten veröffentlicht, in denen sie Regeln für die Zweitveröffentlichung festlegen. Sie können diese Policies in der Regel unter den Begriffen “Zweitveröffentlichung”, “Selbstarchivierung” oder “Open Access” finden. Sollte Ihr Verlag keine Policy zur Zweitveröffentlichung veröffentlicht haben, erfragen Sie bitte die Regelungen direkt beim Verlag.</li>
</ul>

<p><b>Wo wird mein Artikel zweitveröffentlicht?</b></p>
<ul>
    <li>Wenn Sie über <?=$currentSystem;?> Publikationen zweitveröffentlichen, werden diese in einem von der Universität Tübingen betriebenen Repositorium abgelegt. Das Repositorium von <?=$currentSystem;?> zählt zu den nichtkommerziell betriebenen Fachrepositorien (“non-commercial subject repository”). Zweitveröffentlichungen sind je nach Verlagspolicy auf der persönlichen Webseite, dem Repositorium der eigenen Institution oder nichtkommerziellen Fachrepositorien möglich. Kommerzielle Anbieter, wie z.B. Academia oder ResearchGate, sind häufig ausgeschlossen.</li>
    <li>Sollte die Zweitveröffentlichung auf einem nichtkommerziellen Fachrepositorium nicht gestattet sein, können Sie Ihre Publikation evtl. auf dem Repositorium Ihrer eigenen Institution zweitveröffentlichen. Bitte wenden Sie sich in diesem Fall an die Open Access-Beauftragten Ihrer Hochschulbibliothek. Teilen Sie uns gerne mit, welche Publikationen Sie in Ihrem institutionellen Repositorium zweitveröffentlicht haben, damit wir diese in <?=$currentSystem;?> nachweisen können.</li>
</ul>

<p><b>Was ist mit meinen Ko-Autor*innen? / Gilt das Zweitveröffentlichungsrecht auch bei geteilter Autor*innenschaft?</b></p>
<ul>
    <li>Wenn Sie Ihre Publikationen gemeinsam mit anderen Autor*innen verfasst haben, benötigen Sie deren Einverständnis zur Zweitveröffentlichung. Bitte holen Sie deren Einverständnis vor der Zweitveröffentlichung ein.</li>
</ul>

<p><b>Braucht meine Zweitveröffentlichung ein Deckblatt?</b></p> 
<p>Bitten stellen Sie Ihrer Publikation ein Deckblatt mit den vollständigen bibliographischen Angaben der Erstveröffentlichung voran.</p>
<p>Das Deckblatt muss mindestens die folgenden Angaben enthalten:</p>  
<ul>
    <li>Ein Hinweis, dass es sich um eine Zweitveröffentlichung im Green Open Access handelt</li>
    <li>Titel des Beitrags</li>
    <li>Ihr Name sowie die evtl. beteiligter Ko-Autor*innen</li>
    <li>Titel der Zeitschrift bzw. des Sammelwerks</li>
    <li>Herausgeber*innen bzw. beteiligte Personen des Sammelwerks</li>
    <li>Erscheinungsort</li>
    <li>Verlag</li>
    <li>Erscheinungsjahr</li>
    <li>Seitenzahlen des Beitrags in der Originalpublikation</li>
    <li>Soweit vorhanden: permanenter Link (z.B. DOI, URN, Handle) zur Online-Ausgabe oder Link zur Verlagswebseite</li>
    <li>Zweitveröffentlichungen von Manuskriptversionen müssen einen Hinweis enthalten, dass die veröffentlichte Version der Verlagsversion inhaltlich entspricht, aber nicht im Verlagslayout gesetzt ist, woraus sich Unterschiede bei der Seitenzählung ergeben können.</li>
</ul>

<p><b>Benötige ich zusätzliche Bildrechte?</b></p>
<ul>
    <li>Das Recht zur Verwendung von Bildmaterial erstreckt sich nicht automatisch auf die Zweitveröffentlichung. Bitte prüfen Sie daher, ob Sie die Rechte an allen verwendeten Abbildungen auch für die Zweitveröffentlichung haben und holen sie bei Bedarf erneut ein.</li>
    <li>Ausnahmen können nach deutschem Recht für Abbildungen von gemeinfreien Werken und Bildzitate [https://www.gesetze-im-internet.de/urhg/__51.html] gelten.</li>
    <li>Sollten Sie keine Bildrechte erhalten, müssen die jeweiligen Bilder aus der Publikation gelöscht oder geschwärzt / geweißt werden.<li>
</ul>

<p><b>Sind meine hochgeladenen Artikel zitierfähig?</b></p>
<ul>
    <li>Durch die Angabe des Digital Object Identifiers (DOI) in der Literaturangabe können Sie dauerhaft und eindeutig auf die verwendete Version verweisen. Damit sind Ihre Artikel in Forschung und Lehre voll zitierfähig und teilbar.</li>
</ul>

<h3>Technische Probleme und Ablauf</h3> 

<p><b>Was brauche ich für die Nutzung des Selbstupload-Formulars?</b></p>
<ul>
    <li>Ein Konto bei <?=$currentSystem;?>, das Sie hier [LINK zum Accounterstellungsformular] kostenlos anlegen können</li>
    <li>Den Zugriff auf Ihre Autor*innen-ID, die Sie mit Ihrem <?=$currentSystem;?>-Konto beansprucht haben [LINK zu „Wie beanspruche ich meine Autor*innen-ID“]</li>
    <li>Publikationen, die Sie zweitveröffentlichen dürfen </li>
</ul>

<p><b>Wie funktioniert der Selbstupload meiner Zweitveröffentlichungen?</b></p>
<p>Um eine Publikation auf <?=$currentSystem;?> hochzuladen, gehen Sie wie folgt vor:</p> 
<p>Registrierung</p>
<ol>
    <li>
        <p>Sie benötigen einen IxTheo-Account.</p>
        <p>Dafür müssen Sie sich lediglich einmalig mit einer gültigen E-Mail-Adresse registrieren. Den Link zur Registrierung und zum Login finden Sie auf der Startseite rechts oben unter dem Button „Login“. Sobald Sie einen IxTheo-Account haben, können Sie mit den weiteren Schritten fortfahren.</p>
        <p>Rechte beantragen</p>
    </li>
    <li>
        <p>Sobald Sie in Ihrem IxTheo Konto angemeldet sind, können Sie den Zugriff auf Ihre Autor*innen-ID beantragen. Dazu wählen Sie den Reiter „Personen/Körperschaften“ oberhalb des Suchschlitzes. Suchen Sie nach Ihrem Namen und wählen Sie den richtigen Eintrag aus.</p>
    </li>
    <li>
        <p>Klicken Sie auf den Button „Request Access Rights (This is me!)”</p>
    </li>
    <li>
        <p>Ihre Anfrage wird nun automatisch an das IxTheo-Team geschickt. Wir überprüfen, ob Sie die genannte Person sind, und informieren Sie innerhalb weniger Tage per E-Mail, ob Ihr Antrag genehmigt wurde.</p>
        <p>Nun können Sie im nächsten Schritt Ihre Publikationen hochladen.</p>
        <p>Upload (republish)</p>
    </li>
    <li>
        <p>Sobald Ihr Antrag genehmigt wurde, melden Sie sich erneut in Ihrem IxTheo-Konto an. Nun können Sie jeden Aufsatz für eine Zweitveröffentlichung auswählen, der mit Ihnen als Autor*in verknüpft ist. Wenn Sie auf den Button „republish“ klicken, können Sie ein Digitalisat Ihrer Publikation als PDF-Datei hochladen.</p>
    </li>
    <li>
        <p>Im Anschluss wird Ihre Datei auf das Repositorium hochgeladen. Im Regelfall steht sie ab dem folgenden Tag für andere Nutzer*innen im Open Access zur Verfügung. Gleichzeitig werden stabile Links (handle/doi) generiert, die Sie ebenfalls ab dem folgenden Tag abrufen können. Diese Links bleiben dauerhaft erhalten und können von Ihnen für Forschung und Lehre verwendet werden.</p>
    </li>
</ol>

<p><b>Was ist eine Autor*innen-ID?</b></p>
<ul>
    <li>Eine Autor*innen-ID ist eine eindeutige und stabile Nummer in der Gemeinsamen Normdatenbank (GND) [https://www.dnb.de/DE/Professionell/Standardisierung/GND/gnd_node.html], die von <?=$currentSystem;?> nachgenutzt wird, um Sie als Autor*in eindeutig zu identifizieren und Ihre Publikationen zuordnen zu können.</li>
</ul>

<p><b>Wie beantrage ich den Zugriff auf meine Autor*innen-ID?</b></p> 
<ul>
    <li>Gehen Sie zunächst auf Ihre Personenseite, bspw. über die Personensuche von <?=$currentSystem;?> oder einen Klick auf die Autorenanzeige neben Ihrem Namen bei einem Aufsatz. Am oberen Rand der Übersicht finden Sie den Button [Request access rights (This is me!)]. Bitte loggen Sie sich hier in Ihr <?=$currentSystem;?>-Konto ein, sofern noch nicht geschehen. Ihre Anfrage wird nun automatisch an das IxTheo-Team geschickt. Wir überprüfen, ob Sie die genannte Person sind, und informieren Sie innerhalb weniger Tage per E-Mail, ob Ihr Antrag genehmigt wurde.</li>
    <li>Bitte beachten Sie, dass pro <?=$currentSystem;?>-Konto nur die Rechte für eine Autor*innen-ID vergeben werden können. Ebenso kann eine Autor*innen-ID nur von einem Konto beansprucht werden.</li>
    <li>Bei Problemen wenden Sie sich bitte an: <?=$publicationEmail;?>.</li> 
</ul>

<p><b>Warum habe ich keine Autor*innen-ID? /  Ich finde meine Autor*innen-ID nicht.</b></p> 
<ul>
    <li>Bitte prüfen Sie zunächst, ob für Ihre Person bereits eine Autor*innen-ID existiert, etwa durch eine Suche nach Ihrem Namen im Reiter „Personen/Körperschaften“ in <?=$currentSystem;?>. Sollte diese Suche ergeben, dass Sie noch keine Autor*innen-ID haben, nehmen Sie gerne Kontakt zu uns auf: <?=$publicationEmail;?>.</li>
</ul>

<p><b>Warum funktioniert der Button für den Upload meines Artikels nicht?</b></p>
<p>Hierfür kann es mehrere Gründe geben:</p> 
<ul>
    <li>Sie sind nicht eingeloggt. Bitte loggen Sie sich ein.[LINK zur Login-Seite]</li>
    <li>Sie haben den Zugriff auf Ihre Autor*innen-ID noch nicht beantragt.[LINK: Wie beantrage ich den Zugriff auf meine Autor*innen-ID?]</li>
    <li>Falls keiner der genannten Punkte das Problem löst, wenden Sie sich bitte an uns <?=$publicationEmail;?>.</li>
</ul>

<p><b>Ich habe bereits den Zugriff auf meine Autor*innen-ID beantragt. Warum kann ich meinen Artikel nicht hochladen?</b></p> 
<ul>
    <li>Die Publikation, die Sie hochladen möchten, ist nicht mit Ihrer Autor*innen-ID verknüpft. Das Personen-Icon hinter Ihrem Namen in der Autor*innenangabe des Beitrags fehlt.[Bild vom Icon] Wenden Sie sich in diesem Fall bitte mit dem Link zu Ihrer Publikation in <?=$currentSystem;?> an uns: <?=$publicationEmail;?>.</li>
</ul>

<p><b>Meine Publikation ist nicht verzeichnet.</b></p>
<ul>
    <li>Wenn Sie Publikationen hochladen möchten, die noch nicht in <?=$currentSystem;?> verzeichnet sind, wenden Sie sich bitte mit der vollständigen bibliographischen Angabe an uns: <?=$publicationEmail;?>.</li>
</ul>

<p><b>Ich bin im Eintrag einer meiner Publikationen nicht als Autor*in aufgeführt.</b></p> 
<ul>
    <li>Falls Ihre Publikation in <?=$currentSystem;?> auffindbar ist, Sie aber nicht als Autor*in verzeichnet sind, wenden Sie sich bitte an uns <?=$publicationEmail;?>. Bitte fügen Sie Ihrer Mail die vollständige bibliografische Angabe sowie den Link zu der Publikation in <?=$currentSystem;?> bei.</li>
</ul>

<p><b>In welchem Dateiformat kann ich meine Publikation hochladen?</b></p>
<ul>
    <li>Ihre Publikation muss im PDF-Format hochgeladen werden, wenn möglich im PDF/A-Format. Eine Anleitung zur Erstellung einer PDF/A-Datei finden Sie z.B. hier [z.B. https://edoc-info.hu-berlin.de/de/zentral/diss_anleitungen_pdf/view]. Das PDF/A-Format wurde für die Langzeitarchivierung von Dokumenten entwickelt. Der Upload in anderen Formaten (z.B. .docx, .odt, etc.) ist nicht möglich.</li>
</ul>

<p><b>Was sind persistente Identifier und stabile Links?</b></p> 
<ul>
    <li>Um die Wiederauffindbarkeit Ihrer Zweitveröffentlichung zu gewährleisten, wird jeder Datei ein persistenter Identifier bzw. stabiler Link zugeordnet. Dieser Link wird sich nicht verändern, auch wenn sich der Speicherort der Datei verändert. Dadurch ist Ihre Publikation im Repositorium dauerhaft zitierfähig. Für <?=$currentSystem;?> werden Digital Object Identifier (DOI) und Handle-Links genutzt. Da der DOI erst erzeugt werden muss, steht der DOI ca. 24 Stunden nach dem Upload zur Verfügung und erscheint innerhalb weniger Tage in <?=$currentSystem;?>. Nachdem der DOI erzeugt wurde, erhalten Sie von uns eine Mail.</li>
</ul>

<p><b>Wann ist meine zweitveröffentlichte Publikation online verfügbar?</b></p> 
<ul>
    <li>Ihre Publikation ist nach dem Upload auf dem Repositorium verfügbar und ist über den Handle-Link teilbar. Eine rechtliche oder inhaltliche Prüfung durch unser Team erfolgt nicht. Bitte achten Sie daher darauf, die korrekten Dateien hochzuladen.</li>
    <li>Der Digital Object Identifier (DOI) steht erst nach ca. 24 Stunden zur Verfügung und erscheint nach wenigen Tagen in <?=$currentSystem;?>.</li>
</ul>

<p><b>Kann ich meine hochgeladene Publikation nachträglich selbst ändern oder löschen?</b></p> 
<ul>
    <li>Eine nachträgliche Änderung oder Löschung Ihres Beitrags ist leider nicht möglich. Bitte achten Sie deshalb im Vorfeld auf die Einhaltung von Urheber-, Verwertungs-, Bild- und Persönlichkeitsrechten. Aus rechtlichen Gründen kann der Zugriff auf bereits veröffentlichte Dokumente gesperrt werden.</li>
</ul>

<p><b>Kann ich meine Publikation mit einem Kopierschutz oder Passwort versehen?</b></p> 
<ul>
    <li>Bitte verzichten Sie darauf, Ihre Dateien mit Kopier- oder Passwortschutz zu versehen. Dem Grundgedanken des Open Access folgend sollen zweitveröffentlichte Publikationen ohne weitere Hürden zugänglich sein.</li>
</ul>

<p><b>Was mache ich bei falschen oder veralteten Angaben auf meiner Personenseite?</b></p> 
<ul>
    <li>Die Angaben auf Ihrer Personenseite werden automatisiert aus verschiedenen Quellen (z.B. GND, ORCID, etc.) zusammengestellt und sind daher nicht immer aktuell.</li>
    <li>Sollten Ihnen Fehler auffallen, wenden Sie sich bitte an <?=$publicationEmail;?>.</li>
</ul>
 
<p><b>Meine Frage wurde nicht beantwortet / Ich habe weitere Fragen.</b></p> 
<ul>
    <li>Haben Sie noch weitere Fragen oder Anliegen? Wenden Sie sich gerne an: [Kontaktdaten FID]</li>
</ul>
