<?php
    $tuefind = $this->tuefind();
    $currentSystem = $tuefind->getTueFindType();
    $selfArchivingEmail = $tuefind->getSelfArchivingEmail();

    // Set up page title:
    $this->headTitle($this->translate('Self Archiving'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li>';
?>

<?=$this->component('show-account-menu-button')?>

<div class="<?=$this->layoutClass('mainbody')?>">
  <h2>Neue Publikation melden</h2>
  <p>Möchten Sie eine Publikation melden, die in <?=$currentSystem;?> noch nicht verzeichnet ist?</p>
  <p>Hier finden Sie unsere Formulare:</p>
  <ul>
      <li><a href="/Feedback/Form/SelfArchivingAufsatz">Aufsatz in einer Zeitschrift oder einem Sammelband</a></li>
      <li><a href="/Feedback/Form/SelfArchivingRezension">Rezension</a></li>
      <li><a href="/Feedback/Form/SelfArchivingLexikonartikel">Lexikonartikel</a></li>
      <li><a href="/Feedback/Form/SelfArchivingMonographie">Monographie oder herausgegebenes Werk</a></li>
  </ul>
  <p>Nach der erfolgreichen Übermittlung des Formulars wird der gemeldete Titel geprüft und in <?=$currentSystem;?> aufgenommen. Sie können den neuen Eintrag nach wenigen Tagen in <?=$currentSystem;?> finden. Ab diesem Zeitpunkt können Sie bei eigenen Titeln außerdem unseren Self-Archiving Service nutzen und ein Digitalisat Ihrer Publikation als PDF-Datei hochladen.</p>
  <p>Falls sich im Zuge der Bearbeitung Fragen ergeben sollten, kommen wir auf Sie zu.</p>
  <p>Wenn Sie eine Publikation anderen Typs melden möchten, wenden Sie sich bitte per E-Mail an uns: <a href="mailto:<?=$selfArchivingEmail;?>"><?=$selfArchivingEmail;?></a></p>
</div>

<div class="<?=$this->layoutClass('sidebar')?>" id="myresearch-sidebar" role="navigation" aria-label="<?=$this->transEsc('account_menu_label')?>">
  <?=$this->accountMenu()->render('SelfArchiving')?>
</div>