<?php
$form = $this->form;
$form->prepare();

$title = $form->getTitle();
$title = !empty($title)
  ? $this->translate($title) : null;

$formUrl = $this->url('feedback-form', ['id' => $this->formId]);
$form->setAttribute('action', $formUrl);
$form->setAttribute('class', 'dynamic-form');
$form->setAttribute('method', 'post');

$translateParams = ['%%TueFindType%%' => $this->tuefind()->getTueFindType(),
                    '%%FIDType%%' => $this->tuefind()->getTueFindFID()];

$help = $form->getHelp();
$helpPre = $helpPost = null;
$helpPre = isset($help['pre']) ? $form->getDisplayString($help['pre'], null, $translateParams) : null;
$helpPost = isset($help['post']) ? $form->getDisplayString($help['post'], null, $translateParams) : null;

$formInfo = true;
if($this->formId == "DoD") {
    $helpPre = $this->content()->renderTranslated('feedback/dod');
    $formInfo = false;
}

// TueFind: load a custom PHTML template for this form if it exists
print $this->content()->renderTranslated($this->formId, 'feedback');

?>
<?php if (!$this->inLightbox): ?>
<div class="feedback-content"><?php endif; ?>
  <?php if ($title): ?>
  <?php $this->headTitle($title); ?>
  <?php $headTag = $this->inLightbox ? 'h2' : 'h1'; ?>
  <<?=$headTag?>><?=$this->escapeHtml($title)?></<?=$headTag?>>
  <?php endif; ?>
  <?=$this->flashmessages()?>

  <?= $this->form()->openTag($form); ?>
  <?php if ($helpPre): ?>
  <div class="form-group">
    <?php $formInfo ? '<div class="form-info pre">' : '' ?>
    <?=$helpPre?>
    <?php $formInfo ? '</div>' : '' ?>
  </div>
  <?php endif ?>

  <?php
  $currentGroup = null;
$elementsInGroup = 0;
$groupMultiFieldtext = "";
$isOpen_groupMultiFieldtext = false;
?>
  <?php foreach ($form->getFormElementConfig() as $el): ?>
  <?php
$formElement = $form->get($el['name']);

      // Group form elements into field sets
      $groupName = '';
      $groupClass = '';
      $elementsInGroupByName = 0;
      $handleGroup = $group = null;
      $allElementsInGroup = 0;
      if (isset($el['group']) && !empty($el['group'])) {
          $group = $el['group'];
          $explodeGroupName = explode("_", $group);

          if(isset($explodeGroupName[1])) {
              if(empty($groupName)) {
                  $groupName = $el['label'];
                  $groupClass = $explodeGroupName[0];
                  $allElementsInGroup = intval($explodeGroupName[1]);
              }
              if($elementsInGroup == $allElementsInGroup) {
                  $elementsInGroup = 0;
              } else {
                  $elementsInGroup++;
              }
          }
      }
      if ($group && $currentGroup === null) {
          $handleGroup = 'open';
          $currentGroup = $group;
      } elseif ($currentGroup && !$group) {
          $handleGroup = 'close';
          $currentGroup = null;
      } elseif ($currentGroup !== $group) {
          $handleGroup = 'openAndClose';
          $currentGroup = $group;
      }
      $elementHelpPre = $elementHelpPost = '';
      if ($elementHelp = $el['help'] ?? null) {
          if (is_string($elementHelp)) {
              $elementHelpPre = $elementHelp;
          } else {
              $elementHelpPre = $elementHelp['pre'] ?? '';
              $elementHelpPost = $elementHelp['post'] ?? '';
          }
          $elementHelpPre = $form->getDisplayString($elementHelpPre);
          $elementHelpPost = $form->getDisplayString($elementHelpPost);
      }
      ?>

  <?php if (in_array($handleGroup, ['close', 'openAndClose'])): ?>
</div>
<?php endif ?>
<?php
if($el['type'] == 'multifieldtext') {
    if($groupMultiFieldtext == "") {
        $isOpen_groupMultiFieldtext = true;
        $groupMultiFieldtext = $el['groupMultiFieldtext'];
        echo "<div class='multifieldtext_group'>";
    } else {
        if($groupMultiFieldtext != $el['groupMultiFieldtext']) {
            echo "</div>\n";
            $isOpen_groupMultiFieldtext = true;
            $groupMultiFieldtext = $el['groupMultiFieldtext'];
            echo "<div class='multifieldtext_group'>";

        }
    }
} else {
    if($isOpen_groupMultiFieldtext == true) {
        $isOpen_groupMultiFieldtext = false;
        echo "</div>";
    }
}
      ?>
  <?php if($allElementsInGroup != 0 && $elementsInGroup == 1): ?> 
    <div class="<?php echo $groupClass; ?>">
  <?php endif;?>
  <?php if (in_array($handleGroup, ['open', 'openAndClose'])): ?>
    <?php if (in_array($el['type'], ['checkbox', 'radio'])): ?>
      <div class="field-set" role="group" <?= !empty($el['label']) ? ' aria-labelledby="' . $this->escapeHtmlAttr($el['name']) . '"' : ''?>>
    <?php else: ?>
      <div class="field-set"
      <?= !empty($elementHelpPre) ? ' role="contentinfo" aria-label="' . $this->escapeHtmlAttr($elementHelpPre) . '"' : ''?>>
    <?php endif ?>
  <?php endif ?>

  <div class="form-group <?= $el['type'] ?> group-<?=$this->escapeHtmlAttr($el['name'])?>">
    <?php if (!empty($elementHelpPre)): ?>
      <p class="info pre"><?=$elementHelpPre?></p>
    <?php endif ?>
    <?php if ($el['type'] !== 'submit'): ?>
      <?php if ($el['label']): ?>
        <?php
              $required = $el['required'] ?? false;
              $requireOne = $el['requireOne'] ?? false;
            ?>
        <?php if (in_array($el['type'], ['checkbox', 'radio'])): ?>
          <p id="<?=$this->escapeHtmlAttr($el['name'])?>"
          class="control-label radio-label<?=$required && !$requireOne ? ' required' : ''?><?=$requireOne ? ' require-one' : ''?>">
          <?=$this->transEsc($el['label'])?>:</p>
        <?php else: ?>
          <label for="<?=$this->escapeHtmlAttr($el['name'])?>"
        class="control-label<?=$required ? ' required' : ''?>"><?=$this->transEsc($el['label'])?>:</label>
        <?php endif ?>
      <?php endif ?>
      <?php else: ?>
        <?php if ($helpPost): ?>
          <div class="form-info post">
            <?=$helpPost?>
          </div>
        <?php endif ?>
        <?=$this->captcha()->html($this->useCaptcha) ?>
      <?php endif ?>
    <?= $this->formRow($formElement) ?>
    <?php if($allElementsInGroup != 0 && $elementsInGroup == $allElementsInGroup) :?>
        </div> 
      <?php $elementsInGroup = 0; ?>
    <?php endif ?>
    <?php if (!empty($elementHelpPost)): ?>
        <p class="info post"><?=$elementHelpPost?></p>
    <?php endif ?>
    </div>
    <?php endforeach ?>
    <?php 
    if($isOpen_groupMultiFieldtext == true) {
        $isOpen_groupMultiFieldtext = false;
        echo "</div>";
    } 
    ?>
    <?= $this->form()->closeTag() ?>
    <?php if (!$this->inLightbox): ?>
      </div>
    <?php endif; ?>