<?php

$script = <<<JS
    $(function() {

      function linkOnlineversion() {
        $('.group-onlineversion_werk_group_fulltext').toggle();
        $('.group-onlineversion_werk_group_openaccess').toggle();
      }

      function zeitschriftSelected() {
        $('.group-sammelband_werk_group_ISBN').hide();
        $('.group-sammelband_werk_group_Herausgeber').hide();
        $('.inwerkgroup .multifieldtext_group').hide();
        $('.inwerkgroup .group-sammelband_werk_group_erscheinungsjahr').hide();

        $('.group-zeitschrift_werk_group_ISSN').show();
        $('.group-zeitschrift_werk_group_band').show();
        $('.group-zeitschrift_werk_group_heft').show();
        $('.group-zeitschrift_werk_group_jahr').show();
        $('.group-zeitschrift_werk_group_aufsatz_ID').show();
      }

      function sammelbandSelected() {
        $('.group-zeitschrift_werk_group_ISSN').hide();
        $('.group-zeitschrift_werk_group_band').hide();
        $('.group-zeitschrift_werk_group_heft').hide();
        $('.group-zeitschrift_werk_group_jahr').hide();
        $('.group-zeitschrift_werk_group_aufsatz_ID').hide();

        $('.group-zeitschrift_werk_group_erscheinungsjahr').show();
        $('.group-sammelband_werk_group_ISBN').show();
        $('.group-sammelband_werk_group_Herausgeber').show();
        $('.inwerkgroup .multifieldtext_group').show();
        $('.inwerkgroup .group-sammelband_werk_group_erscheinungsjahr').show();
      }
      
      zeitschriftSelected();

      $(document).on("change", "#form_SelfArchivingAufsatz_inwerkradio_o2", function() {
        $(this).parents('.inwerkgroup').find('i').show();
        sammelbandSelected();
      })

      $(document).on("change", "#form_SelfArchivingAufsatz_inwerkradio_o1", function() {
        $(this).parents('.inwerkgroup').find('i').hide();

        zeitschriftSelected();
      })

      $('#form_SelfArchivingAufsatz_onlineversion_o1,#form_SelfArchivingAufsatz_onlineversion_o2').change(function(){
        linkOnlineversion();
      })

    });

  JS;

print $this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, $script, 'SET');
?>
