<?php

$script = <<<JS
    $(function() {

      removeValidation($(this).find('input:checked').val());

      function removeValidation (blockSelected) {
        $('.jshide').each(function(){
          let thisBlock = $(this);
          if(thisBlock.hasClass(blockSelected+"")) {
            thisBlock.find('input').each(function(){
              if($(this).prev().hasClass('required')){
                $(this).prop('required',true);
              }
            })
            thisBlock.show();
          }else{
            thisBlock.find('input').each(function(){
              $(this).prop('required',false);
            })
            thisBlock.hide();
          }
        })
      }

      $(document).on("change", ".inclusiveSelect", function() {
        removeValidation($(this).find('input:checked').val());
      })

      $('.feedback-content form .btn.btn-primary').on( "click", function(e) {
          $('.jshide').each(function(){
            let thisBlock = $(this);
            if(thisBlock.css('display') != 'none') {
              thisBlock.find('input').each(function(){
                $(this).prop('required',false);
              })
            }
          })
      });
    });

  JS;

print $this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, $script, 'SET');
?>
